Repository BeeStation/BeeStation-Hornet, pull requests merged in 2019-10, with the labels that each got.

#471 Tgbuggies
  code/game/machinery/porta_turret/portable_turret.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_actions.dm
  code/game/objects/buckling.dm
  code/game/objects/items/devices/chameleonproj.dm
  code/game/objects/items/devices/taperecorder.dm
  code/game/objects/items/toys.dm
  code/modules/food_and_drinks/food/snacks_bread.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/monkey/combat.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/hostile/bees.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  code/modules/paperwork/filingcabinet.dm
Labels: DONT MERGE, bug, code cleanup

#482 Plasmeme helmet fix
  code/modules/clothing/outfits/plasmaman.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/clothing/under/jobs/Plasmaman/civilian_service.dm
  code/modules/clothing/under/jobs/Plasmaman/engineering.dm
  code/modules/clothing/under/jobs/Plasmaman/medsci.dm
  code/modules/clothing/under/jobs/Plasmaman/security.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/vending/wardrobes.dm
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Needs Vote, balance

#485 Adds tiny fans to supply shuttle(s)
  _maps/shuttles/cargo_birdboat.dmm
  _maps/shuttles/cargo_box.dmm
  _maps/shuttles/cargo_delta.dmm
  _maps/shuttles/cargo_kilo.dmm
Labels: mapping

#466 Made health analyzer information readout display columns
  code/game/objects/items/devices/scanners.dm
Labels: Port

#531 New IPC screens
  code/modules/mob/dead/new_player/sprite_accessories.dm
  icons/mob/ipc_accessories.dmi
Labels: Feature, Grammar and Formatting, Sprites

#530 Automatically label and close stale PRs
  .github/workflows/stale.yml
Labels: GitHub

#533 Joker Suit/Coat
  code/modules/clothing/outfits/standard.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/vending/autodrobe.dm
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, Sprites

#534 Bumps Playtime Reqs
  code/modules/jobs/job_types/ai.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/virologist.dm
  code/modules/jobs/job_types/warden.dm
Labels: Tweak

#489 Cross Server Ban option
  SQL/beestation_schema.sql
  SQL/database_changelog.txt
  code/modules/admin/sql_ban_system.dm
  html/admin/banpanel.css
Labels: THIS IS VERY IMPORTANT, admin, sql, test merged

#537 Moves departmental budget cards to lockers
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/quartermaster.dm
  code/modules/jobs/job_types/research_director.dm
Labels: Needs Vote, Tweak

#538 Adds Transport Zeta Shuttle
  _maps/shuttles/emergency_zeta.dmm
  code/__DEFINES/shuttles.dm
  code/datums/shuttles.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
  code/modules/research/techweb/_techweb.dm
  code/modules/research/techweb/_techweb_node.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Map Edit

#523 Baytiles without the replacements
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/turfs/simulated/floor/misc_floor.dm
  code/game/turfs/simulated/floor/plasteel_floor.dm
  code/game/turfs/simulated/floor/reinf_floor.dm
  icons/obj/tiles.dmi
  icons/turf/floors.dmi
Labels: Sprites

#540 [BOUNTY] Zesko separated chems
  code/modules/hydroponics/plant_genes.dm
Labels: Balance/Rebalance, Needs Rebalancing, Needs Testmerge, Needs Vote

#547 Uwu
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/vending/wardrobes.dm
Labels: Grammar and Formatting, code cleanup

#532 EMTs [Ready]
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  beestation.dme
  code/__DEFINES/jobs.dm
  code/datums/traits/negative.dm
  code/game/machinery/computer/crew.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/religion.dm
  code/modules/client/preferences.dm
  code/modules/crew_objectives/medical_objectives.dm
  code/modules/events/wizard/departmentrevolt.dm
  code/modules/jobs/job_types/emt.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  config/jobs.txt
  icons/mob/hud.dmi
Labels: Config Update, Feature, Map Edit, Needs Review, Sprites, test merged

#554 Revised Ninja Logic
  code/modules/antagonists/ninja/ninja.dm
Labels: Tweak

#548 JaniDrobes now have equipment for two janitors
  code/modules/vending/wardrobes.dm
Labels: enhancement

#557 Revert "Recompiles TGUI"
  tgui/assets/tgui.css
  tgui/assets/tgui.js
Labels: Revert, UI

#561 Allows the AI and cyborgs to join midround
  config/jobs.txt
Labels: Config Update, Feature

#542 Exowear Pockets
  code/datums/components/storage/concrete/pockets.dm
  code/modules/clothing/suits/_suits.dm
  code/modules/clothing/suits/cloaks.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/suits/reactive_armour.dm
Labels: Feature, Port, Vote Passed

#562 Advanced Camera Console is now obtainable
  code/game/machinery/computer/camera_advanced.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/modules/research/designs/comp_board_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature

#558 Adds an award for the HoP to give
  code/game/objects/items/storage/lockbox.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/under/accessories.dm
Labels: Feature

#556 Cursed slot machine now causes IPCs brain damage, still causes humans cloneless
  code/modules/ruins/objects_and_mobs/sin_ruins.dm
Labels: Feature, Needs Vote, balance, ike approved™

#576 Improved stasis bed sprite
  icons/obj/machines/stasis.dmi
Labels: Sprites

#571 Multi-Z Fixes/Tweaks [PORT]
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/obj_flags.dm
  code/controllers/subsystem/throwing.dm
  code/game/objects/structures/lattice.dm
  code/game/objects/structures/stairs.dm
  code/game/turfs/openspace/openspace.dm
  code/modules/mob/living/living.dm
  code/modules/power/gravitygenerator.dm
  code/modules/power/supermatter/supermatter.dm
Labels: Fix, Tweak

#577 in hindsight I probably should have assumed this
  icons/mob/head.dmi
Labels: Fix, Sprites

#579 Revert "Automatically label and close stale PRs"
  .github/workflows/stale.yml
Labels: GitHub, Revert

#563 Gives suit storage units the ability to remove radiation from mobs
  code/game/machinery/suit_storage_unit.dm
Labels: Port, Tweak, Vote Passed

#580 Fixes the shuttle href exploit
  code/modules/shuttle/computer.dm
Labels: Fix

#581 Fixes advanced camera console circuit board being invisible
  code/game/objects/items/circuitboards/computer_circuitboards.dm
Labels: Fix

#582 Adds anti-rad kits to radsuit lockers
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
Labels: Feature, Needs Vote

#587 makes floorpills more common
  code/_globalvars/lists/maintenance_loot.dm
Labels: Tweak

#552 Revised antag check logic
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/clock_cult/clock_cult.dm
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/devil/devil_game_mode.dm
  code/game/gamemodes/gangs/gangs.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/game/gamemodes/revolution/revolution.dm
  code/game/gamemodes/wizard/wizard.dm
  code/game/machinery/cryopod.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Labels: Tweak

#574 "Saves a significant amount of memory from empty material lists with 2 lines of code" - Port from TG/ninjanomnom
  code/game/atoms.dm
Labels: Port

#594 A unreasonable amount of sprite ports from /TG/, and some QoL features.
  code/__DEFINES/components.dm
  code/game/objects/items/devices/megaphone.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/tanks/watertank.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/simple_animal/slime/powers.dm
  code/modules/projectiles/gun.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/uplink/uplink_items.dm
  icons/mob/back.dmi
  icons/mob/inhands/equipment/backpack_lefthand.dmi
  icons/mob/inhands/equipment/backpack_righthand.dmi
  icons/mob/inhands/equipment/medical_lefthand.dmi
  icons/mob/inhands/equipment/medical_righthand.dmi
  icons/mob/inhands/equipment/mister_lefthand.dmi
  icons/mob/inhands/equipment/mister_righthand.dmi
  icons/mob/inhands/misc/megaphone_lefthand.dmi
  icons/mob/inhands/misc/megaphone_righthand.dmi
  icons/mob/spacedragon.dmi
  icons/obj/hydroponics/equipment.dmi
  icons/obj/janitor.dmi
  icons/obj/syringe.dmi
Labels: Feature, Sprites

#546 Adds Circuit apparatus and beaker holders as cyborg upgrades
  code/__DEFINES/components.dm
  code/game/objects/items/robot/robot_items.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/game/objects/objs.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/reagents/reagent_containers/bottle.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/research/designs/mechfabricator_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/mob/robot_items.dmi
Labels: Needs Testmerge, Port, Sprites, Vote Passed

#572 Azlan's Radsuit/Hazard Vest Sprite Update
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites

#578 Reworks the Build Your Own Shuttle Kit to be more appealing. (#44433)
  _maps/shuttles/emergency_airless.dmm
  _maps/shuttles/emergency_construction.dmm
  code/datums/shuttles.dm
  config/unbuyableshuttles.txt
Labels: Balance/Rebalance, Config Update, Map Edit, Port, Tweak

#596 Storage implants drop their items when removed.
  code/game/objects/items/implants/implant_storage.dm
Labels: Tweak

#592 Exosuit tweaks
  code/datums/components/storage/concrete/pockets.dm
  code/modules/clothing/spacesuits/hardsuit.dm
Labels: Tweak

#595 New teleporter sprites
  code/game/machinery/computer/teleporter.dm
  code/game/machinery/teleporter.dm
  icons/obj/machines/teleporter.dmi
Labels: Sprites

#597 Crispy Status Displays (#44232)
  code/game/machinery/doors/brigdoors.dm
  code/game/machinery/status_display.dm
Labels: Tweak

#584 Made Ladders Buildable
  code/__DEFINES/construction.dm
  code/game/objects/items/RCD.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/structures/ladders.dm
  code/game/turfs/simulated/floor.dm
  icons/mob/radial.dmi
Labels: Feature, Sprites

#598 Bamboomk2
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/twohanded.dm
  code/modules/cargo/packs.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/reagents/reagent_containers/syringes.dm
  icons/mob/back.dmi
  icons/mob/inhands/misc/sheets_lefthand.dmi
  icons/mob/inhands/misc/sheets_righthand.dmi
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/mob/inhands/weapons/polearms_lefthand.dmi
  icons/mob/inhands/weapons/polearms_righthand.dmi
  icons/obj/hydroponics/equipment.dmi
  icons/obj/hydroponics/growing.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
  icons/obj/items_and_weapons.dmi
  icons/obj/stack_objects.dmi
Labels: Feature, Sprites

#599 pAI Update
  code/game/objects/items/devices/paicard.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/pai/software.dm
  icons/mob/pai.dmi
  icons/mob/pai_item_head.dmi
  icons/mob/pai_item_lh.dmi
  icons/mob/pai_item_rh.dmi
  icons/obj/aicards.dmi
Labels: Sprites

#586 IPC bugsquashing and minor fixes.
  code/modules/food_and_drinks/kitchen_machinery/icecream_vat.dm
  code/modules/mob/living/carbon/human/species_types/IPC.dm
  code/modules/mob/living/simple_animal/slime/powers.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/surgery/organ_manipulation.dm
Labels: Balance/Rebalance, Feature, Fix, Tweak

#608 Adds gamepad keybindings
  code/modules/keybindings/bindings_client.dm
Labels: Fix

#604 Abductor Chemical Dispenser
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/antagonists/abductor/machinery/console.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  icons/obj/abductor.dmi
Labels: Feature, Sprites

#612 Fixes airlock cycling breaking when somethings in the way
  code/game/machinery/embedded_controller/access_controller.dm
Labels: Fix

#611 Fixes Cyborg Buckling
  code/modules/mob/mob.dm
Labels: Fix

#573 Arena Controllers - Port from /tg/ [Ready]
  _maps/arenas/2fort.dmm
  _maps/arenas/2sides.dmm
  _maps/arenas/README.md
  _maps/arenas/Stage.dmm
  _maps/arenas/aiupload.dmm
  _maps/arenas/bar.dmm
  _maps/arenas/beach.dmm
  _maps/arenas/cargobelt.dmm
  _maps/arenas/clockwork.dmm
  _maps/arenas/defaultarena.dmm
  _maps/arenas/dorms.dmm
  _maps/arenas/laserbox.dmm
  _maps/arenas/lavaland.dmm
  _maps/arenas/lavaland_arena_2.0.dmm
  _maps/arenas/mazemap.dmm
  _maps/arenas/monkey.dmm
  _maps/arenas/singularity.dmm
  _maps/arenas/solars.dmm
  _maps/arenas/soviet.dmm
  _maps/arenas/supermatter.dmm
  _maps/arenas/survival pod.dmm
  _maps/arenas/thunderdome.dmm
  _maps/map_files/generic/CentCom.dmm
  beestation.dme
  code/game/machinery/computer/arena.dm
  code/game/objects/effects/countdown.dm
  code/modules/antagonists/_common/antag_hud.dm
Labels: Administration, Config Update, Feature, Map Edit, Needs Review, Needs Testmerge, Port

#618 Reduces pain and suffering for admins
  code/game/machinery/computer/arena.dm
Labels: Administration

#619 Fixed charcoal reagent error
  code/modules/reagents/reagent_containers/pill.dm
Labels: Fix

#622 Ports "Lets the kinetic crusher be one-hand carried"
  code/datums/status_effects/debuffs.dm
  code/game/objects/items/twohanded.dm
  code/modules/mining/equipment/kinetic_crusher.dm
  code/modules/mining/machine_vending.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
  icons/mob/inhands/weapons/hammers_lefthand.dmi
  icons/mob/inhands/weapons/hammers_righthand.dmi
Labels: Feature, Sprites

#624 Adjusts ID sprites
  icons/obj/card.dmi
Labels: Sprites

#626 Catwalks on top of plating
  beestation.dme
  code/__DEFINES/layers.dm
  code/game/machinery/navbeacon.dm
  code/game/objects/structures/catwalk.dm
  code/game/objects/structures/lattice.dm
  code/game/turfs/simulated/floor/plating.dm
  code/game/turfs/simulated/floor/reinf_floor.dm
  code/modules/power/cable.dm
Labels: Feature, Tweak

#628 Changelog Fix(?)
  html/templates/header.html
Labels: Tweak

#640 Changes foam (thermo-nuclear) extinguisher sprite
  icons/obj/items_and_weapons.dmi
Labels: Sprites

#633 Mentorhelp Muting
  code/__DEFINES/admin.dm
  code/modules/admin/admin.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/mentor/mentorhelp.dm
Labels: Administration

#638 fixes holocarp type chooser
  code/modules/mob/living/simple_animal/guardian/guardian.dm
Labels: Fix

#643 Better movement slowdown and longer softcrit
  code/__DEFINES/combat.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Tweak

#616 Riot shotguns for cargo : Revised Edition 2019 GOTY
  code/modules/cargo/packs.dm
Labels: Needs Vote, good first issue

#642 Catwalk bugfix
  code/game/objects/structures/catwalk.dm
  code/game/turfs/simulated/floor/plating.dm
Labels: Fix, Tweak

#644 Sleeper fix (and some circuit text)
  code/game/machinery/Sleeper.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Tweak

#647 DeltaStation QoL Changes / Bugfixes
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Feature, Map Edit

#646 MetaStation QoL Changes v2
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Feature, Map Edit, Tweak

#617 Extended xenobiology mutation toxins
  code/game/objects/items/stacks/sheets/mineral.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
Labels: Feature, Tweak, Vote Passed

#645 [BOUNTY] Beecoin shop
  beestation.dme
  code/__HELPERS/_lists.dm
  code/game/world.dm
  code/modules/client/loadout/loadout.dm
  code/modules/client/loadout/loadout_accessories.dm
  code/modules/client/loadout/loadout_cosmestics.dm
  code/modules/client/loadout/loadout_general.dm
  code/modules/client/loadout/loadout_hat.dm
  code/modules/client/loadout/loadout_ooc.dm
  code/modules/client/loadout/loadout_suit.dm
  code/modules/client/loadout/loadout_uniform.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/mime.dm
  code/modules/metacoin/metacoin.dm
  code/modules/mob/mob.dm
Labels: Feature, bounty

#569 Sawn off improv has recoil like everything else
  code/modules/projectiles/guns/ballistic/shotgun.dm
Labels: Fix

#650 Additional Loadout Gear: Accessories
  code/modules/client/loadout/loadout_accessories.dm
  code/modules/client/preferences.dm
Labels: Feature, Tweak

#653 Renames the Loadout tab to BeeCoin Shop
  code/modules/client/preferences.dm
Labels: Tweak

#649 Clown Updates
  code/datums/components/waddling.dm
  code/modules/clothing/shoes/_shoes.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/vehicles/cars/clowncar.dm
Labels: Balance/Rebalance, Feature, Tweak

#564 TGUI Upgrade
  code/modules/client/asset_cache.dm
  code/modules/client/darkmode.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/goonchat/browserassets/css/browserOutput_white.css
  code/modules/goonchat/browserassets/css/font-awesome.css
  code/modules/goonchat/browserassets/html/browserOutput.html
  code/modules/tgui/tgui.dm
  html/font-awesome/README.MD
  html/font-awesome/css/all.min.css
  html/font-awesome/css/v4-shims.min.css
  html/font-awesome/webfonts/fa-regular-400.eot
  html/font-awesome/webfonts/fa-regular-400.woff
  html/font-awesome/webfonts/fa-solid-900.eot
  html/font-awesome/webfonts/fa-solid-900.woff
  tgui/assets/font-awesome.min.css
  tgui/assets/fonts/SIL-OFL-1.1-LICENSE.md
  tgui/assets/fonts/fontawesome-webfont.eot
  tgui/assets/fonts/fontawesome-webfont.svg
  tgui/assets/fonts/fontawesome-webfont.ttf
  tgui/assets/fonts/fontawesome-webfont.woff
  tgui/assets/fonts/fontawesome-webfont.woff2
  tgui/assets/tgui.css
  tgui/assets/tgui.js
  tgui/gulp/css.js
  tgui/gulp/js.js
  tgui/gulp/plugins.js
  tgui/package-lock.json
  tgui/package.json
  tgui/src/components/titlebar.ract
  tgui/src/components/titlebar.styl
  tgui/src/components/warnings.ract
  tgui/src/interfaces/acclimator.ract
  tgui/src/interfaces/airlock_electronics.ract
  tgui/src/interfaces/airlock_electronics.styl
  tgui/src/interfaces/cargo.ract
  tgui/src/interfaces/chem_dispenser.ract
  tgui/src/interfaces/chem_press.ract
  tgui/src/interfaces/chem_splitter.ract
  tgui/src/interfaces/chemical_filter.ract
  tgui/src/interfaces/crayon.ract
  tgui/src/interfaces/gulag_item_reclaimer.ract
  tgui/src/interfaces/labor_claim_console.ract
  tgui/src/interfaces/launchpad_console.ract
  tgui/src/interfaces/medical_kiosk.ract
  tgui/src/interfaces/nanite_comm_remote.ract
  tgui/src/interfaces/ore_redemption_machine.ract
  tgui/src/interfaces/reaction_chamber.ract
  tgui/src/interfaces/roulette.ract
  tgui/src/interfaces/roulette.styl
  tgui/src/interfaces/synd_contract.ract
  tgui/src/interfaces/synthesizer.ract
  tgui/src/interfaces/vault_controller.ract
  tgui/src/styles/clockwork.styl
  tgui/src/styles/nanotrasen.styl
  tgui/src/styles/syndicate.styl
  tgui/src/tgui.js
  tgui/src/tgui.ract
Labels: Port, Refactor, THIS IS VERY IMPORTANT, UI, code cleanup, test merged

#660 Reduces travis log spam
  code/modules/oracle_ui/themed.dm
  tools/travis/check_grep.sh
Labels: Tools

#609 New Carpets
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/structures/table_frames.dm
  code/game/objects/structures/tables_racks.dm
  code/game/turfs/simulated/floor/fancy_floor.dm
  code/modules/cargo/packs.dm
  icons/mob/inhands/misc/tiles_lefthand.dmi
  icons/mob/inhands/misc/tiles_righthand.dmi
  icons/obj/smooth_structures/fancy_table_blue.dmi
  icons/obj/smooth_structures/fancy_table_cyan.dmi
  icons/obj/smooth_structures/fancy_table_green.dmi
  icons/obj/smooth_structures/fancy_table_orange.dmi
  icons/obj/smooth_structures/fancy_table_purple.dmi
  icons/obj/smooth_structures/fancy_table_red.dmi
  icons/obj/smooth_structures/fancy_table_royalblack.dmi
  icons/obj/smooth_structures/fancy_table_royalblue.dmi
  icons/obj/structures.dmi
  icons/obj/tiles.dmi
  icons/turf/floors/carpet_blue.dmi
  icons/turf/floors/carpet_cyan.dmi
  icons/turf/floors/carpet_green.dmi
  icons/turf/floors/carpet_orange.dmi
  icons/turf/floors/carpet_purple.dmi
  icons/turf/floors/carpet_red.dmi
  icons/turf/floors/carpet_royalblack.dmi
  icons/turf/floors/carpet_royalblue.dmi
Labels: Feature, Sprites

#667 Updated miasma canister sprites #44539
  icons/obj/atmos.dmi
Labels: Sprites, Tweak

#484 MultiHUDs
  code/modules/clothing/glasses/hud.dm
  icons/mob/eyes.dmi
  icons/obj/clothing/glasses.dmi
Labels: enhancement

#662 Ports the very much needed autolathe change
  code/modules/research/designs/autolathe_designs.dm
Labels: Feature

#668 Roboticist Contraband
  code/modules/clothing/suits/jobs.dm
  code/modules/vending/wardrobes.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, Sprites

#671 Ports a tgui fix
  tgui-next/packages/tgui/drag.js
  tgui-next/packages/tgui/public/tgui.bundle.js
  tgui/assets/tgui.js
  tgui/src/components/resize.ract
  tgui/src/components/titlebar.ract
  tgui/src/tgui.ract
  tgui/src/util/dragresize.js
Labels: UI

#669 Makes ghost hud default on, ghost darkness default to NV level #44184
  code/modules/mob/dead/observer/observer.dm
Labels: ike approved™

#672 Revert "Ports a tgui fix"
  tgui-next/packages/tgui/drag.js
  tgui-next/packages/tgui/public/tgui.bundle.js
  tgui/assets/tgui.js
  tgui/src/components/resize.ract
  tgui/src/components/titlebar.ract
  tgui/src/tgui.ract
  tgui/src/util/dragresize.js
Labels: Revert, UI

#670 [READY] Ports Launchpad Revival
  code/__DEFINES/atom_hud.dm
  code/game/data_huds.dm
  code/game/machinery/computer/launchpad_control.dm
  code/game/machinery/launch_pad.dm
  icons/effects/effects.dmi
Labels: Feature, Needs Review, Sprites, Tweak

#673 Ports a tgui fix except also accounts for yarn being stupid
  tgui-next/packages/tgui/drag.js
  tgui-next/packages/tgui/public/tgui.bundle.js
  tgui/assets/tgui.js
  tgui/src/components/resize.ract
  tgui/src/components/titlebar.ract
  tgui/src/tgui.ract
  tgui/src/util/dragresize.js
Labels: UI

#675 Updates repo config to latest
  config/config.txt
Labels: Config Update, Fix

#676 Fixes "Beestation Station 13" on changelog
  html/templates/header.html
Labels: Grammar and Formatting

#674 Removes all pixel_x/y = 0 vars
  _maps/arenas/lavaland.dmm
  _maps/arenas/lavaland_arena_2.0.dmm
  _maps/arenas/survival pod.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/shuttles/arrival_kilo.dmm
  _maps/shuttles/emergency_kilo.dmm
  _maps/shuttles/emergency_zeta.dmm
  _maps/shuttles/ferry_kilo.dmm
Labels: Code Improvement, Map Edit, Removal

#682 Adds potted plants and new carpets to BoxStation
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit

#681 Abductor Scientist Bugfix.
  code/modules/antagonists/abductor/equipment/gland.dm
  code/modules/surgery/surgery.dm
Labels: Fix

#678 New Potted Plant Variants
  code/game/objects/structures/flora.dm
  icons/obj/flora/plants.dmi
Labels: Sprites

#677 New Cryopod features
  code/game/machinery/announcement_system.dm
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Feature

#551 Cultists can now snuff out blood magic by dropping it
  code/modules/antagonists/cult/blood_magic.dm
Labels: Needs Testmerge, Port, Stale, Tweak
