Repository BeeStation/BeeStation-Hornet, pull requests merged in 2019-09, with the labels that each got.

#389 CockCult Nerfs
  code/modules/antagonists/clockcult/clock_effects/clock_sigils.dm
Labels: Needs Vote, ike approved™

#388 Glass Shard nerf / Slipping time reduced
  code/datums/components/caltrop.dm
  code/game/turfs/open.dm
Labels: Needs Vote, ike approved™

#390 Mood Changes: Reduced Penalty, Increased Insanity Tolerance
  code/datums/components/mood.dm
Labels: Needs Vote, ike approved™

#387 Buffed: Cloning Pods, slightly
  code/game/machinery/cloning.dm
Labels: Needs Vote

#400 Code contributors in the credits
  code/_onclick/hud/credits.dm
  tools/fetchContributors.py
Labels: tooling

#370 Plasmaman envirosuits for wardrobes
  code/game/objects/items/tanks/tank_types.dm
  code/modules/clothing/under/jobs/Plasmaman/civilian_service.dm
  code/modules/mining/mine_items.dm
  code/modules/research/designs/autolathe_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/vending/engineering.dm
  code/modules/vending/robotics.dm
  code/modules/vending/wardrobes.dm
Labels: ike approved™

#399 Dynamic gamemode [READY BUT CHECK WITH CAUTION]
  beestation.dme
  code/__DEFINES/maths.dm
  code/__HELPERS/roundend.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_rulesets.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/dynamic/readme.md
  code/game/gamemodes/game_mode.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
Labels: Needs Testmerge, dme, enhancement

#414 Better Job Playtime Requirements
  beestation.dme
  code/modules/admin/verbs/randomverbs.dm
  code/modules/better_exempt/exempt_but_better.dm
  code/modules/client/preferences.dm
  code/modules/jobs/job_exp.dm
  code/modules/jobs/job_types/atmospheric_technician.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/chemist.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/geneticist.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/jobs/job_types/scientist.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/station_engineer.dm
  code/modules/jobs/job_types/virologist.dm
  config/config.txt
Labels: Needs Testmerge, Needs Vote, THIS IS VERY IMPORTANT, code, config, dme, enhancement, ike approved™

#413 Changed the health analyzer icon back to the original one
  icons/obj/device.dmi
Labels: ike approved™

#401 Cryopod Port: An AFK despawner, role opener.
  _maps/map_files/Deltastation/DeltaStation2.dmm
  beestation.dme
  code/_globalvars/game_modes.dm
  code/controllers/subsystem/job.dm
  code/datums/mind.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/clock_cult/clock_cult.dm
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/devil/devil_game_mode.dm
  code/game/gamemodes/gangs/gangs.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/game/gamemodes/objective.dm
  code/game/gamemodes/revolution/revolution.dm
  code/game/gamemodes/wizard/wizard.dm
  code/game/machinery/cryopod.dm
  code/modules/antagonists/cult/cult.dm
  code/modules/client/client_defines.dm
  icons/obj/cryogenic2.dmi
  icons/turf/areas.dmi
Labels: Needs Vote, ike approved™, test merged

#445 (Hopefully) Final fix for cryopod maps
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: mapping

#438 Fixes morgue Maint APC
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: mapping

#447 Adds 'Gangster' to the ban panel
  code/__DEFINES/role_preferences.dm
  code/modules/admin/sql_ban_system.dm
Labels: admin

#440 Noslip turfs under medbay showers
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: ike approved™, mapping

#452 Utilizes the sql server name
  SQL/beestation_schema.sql
  SQL/database_changelog.txt
  code/controllers/subsystem/blackbox.dm
  code/controllers/subsystem/dbcore.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/admin/sql_message_system.dm
  code/modules/client/client_procs.dm
Labels: THIS IS VERY IMPORTANT, sql

#441 Arcade Tokens
  _maps/map_files/Deltastation/DeltaStation2.dmm
  code/game/machinery/computer/arcade.dm
  code/modules/mining/ores_coins.dm
Labels: Needs Testmerge, mapping

#456 Adds the ability to put all small items into boots
  code/datums/components/storage/concrete/pockets.dm
Labels: Needs Vote

#461 Updates the byond version to the current server version
  Dockerfile
Labels: dependencies

#460 Playtime tweaks to heads and the warden
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/job_types/warden.dm
Labels: admin

#462 Cryocell shortcuts
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
Labels: Port

#463 Oracle IPC port, by some unsatisfied mapper.
  beestation.dme
  code/__DEFINES/DNA.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mobs.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/lists/flavor_misc.dm
  code/datums/emotes.dm
  code/game/mecha/mech_fabricator.dm
  code/game/objects/items.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/damage_procs.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/IPC.dm
  code/modules/mob/living/carbon/human/species_types/abductors.dm
  code/modules/mob/living/carbon/human/species_types/android.dm
  code/modules/mob/living/carbon/human/species_types/ipcitems.dm
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
  code/modules/mob/living/carbon/human/status_procs.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  code/modules/mob/living/taste.dm
  code/modules/mob/mob_helpers.dm
  code/modules/power/apc.dm
  code/modules/projectiles/projectile.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/research/designs/mechfabricator_designs.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  code/modules/surgery/bodyparts/dismemberment.dm
  code/modules/surgery/bodyparts/head.dm
  code/modules/surgery/organ_manipulation.dm
  code/modules/surgery/organs/augments_arms.dm
  code/modules/surgery/organs/ears.dm
  code/modules/surgery/organs/eyes.dm
  code/modules/surgery/organs/liver.dm
  code/modules/surgery/organs/stomach.dm
  code/modules/surgery/organs/tongue.dm
  config/game_options.txt
  icons/mob/human_parts.dmi
  icons/mob/human_parts_greyscale.dmi
  icons/mob/ipc_accessories.dmi
  icons/mob/ipc_antennas.dmi
  icons/mob/ipc_screens.dmi
  icons/obj/surgery.dmi
Labels: Needs Testmerge, Needs Vote, Port
