Repository BeeStation/BeeStation-Hornet, pull requests merged in 2019-12, with the labels that each got.

#851 A little late with this (turkies)
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  icons/mob/animal.dmi
  sound/creatures/turkey.ogg
Labels: Feature, Sound, Sprites

#871 [PORT] Adds a solo abductor option to traitor panel
  code/modules/antagonists/abductor/abductor.dm
  code/modules/antagonists/abductor/equipment/abduction_outfits.dm
Labels: Administration

#845 Paywall firing pins
  code/game/objects/items/storage/boxes.dm
  code/modules/cargo/packs.dm
  code/modules/projectiles/pins.dm
Labels: Feature, Vote Passed

#875 Throatslicing, take II
  code/__DEFINES/components.dm
  code/__DEFINES/status_effects.dm
  code/_onclick/item_attack.dm
  code/datums/components/butchering.dm
  code/datums/status_effects/debuffs.dm
Labels: Feature

#877 A few meta atmos fixes
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Fix, Map Edit

#854 [PORT] Delete .dm files in _maps folder
  _maps/boxstation.dm
  _maps/deltastation.dm
  _maps/donutstation.dm
  _maps/kilostation.dm
  _maps/metastation.dm
  _maps/multiz_debug.dm
  _maps/pubbystation.dm
  _maps/runtimestation.dm
Labels: Feature, Map Edit

#878 [PORT] Fixes CAS and adds the hourglass
  beestation.dme
  code/__HELPERS/matrices.dm
  code/game/objects/effects/countdown.dm
  code/game/objects/items/hourglass.dm
  code/game/objects/items/toys.dm
  code/modules/games/cas.dm
  code/modules/vending/games.dm
  icons/obj/hourglass.dmi
  strings/cas_black.txt
  strings/cas_white.txt
Labels: Feature, Fix, Sprites

#879 [PORT] Adds inhands for all the surgery tools. (#45864)
  code/modules/surgery/tools.dm
  icons/mob/inhands/equipment/medical_lefthand.dmi
  icons/mob/inhands/equipment/medical_righthand.dmi
Labels: Sprites

#861 [PORT] Health analyzer font scaling hotfix
  code/game/objects/items/devices/scanners.dm
Labels: Feature

#880 adds syringe and surgical drapes designs to medlathe #44453
  code/modules/research/designs/autolathe_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Tweak

#883 [IMPORTANT] No more cross map punches
  code/modules/clothing/gloves/miscellaneous.dm
Labels: Fix

#809 Mac Space Restaurant
  _maps/RandomRuins/SpaceRuins/Fast_Food.dmm
Labels: Feature, Map Edit, Vote Passed

#881 [PORT] conveyor belt now are stacks (#47656)
  code/modules/cargo/packs.dm
  code/modules/recycling/conveyor2.dm
  code/modules/research/designs/autolathe_designs.dm
Labels: Tweak

#886 Fixes ghost seizures. #44438
  code/__HELPERS/matrices.dm
  code/datums/components/orbiter.dm
Labels: Fix

#888 Fixes nuke shuttle console/drop pod href exploit
  code/modules/shuttle/syndicate.dm
Labels: Fix

#885 Animal Hospital is now actually useful instead of being a reference to a dead meme
  _maps/RandomRuins/LavaRuins/lavaland_surface_animal_hospital.dmm
  code/datums/ruins/lavaland.dm
  code/game/objects/structures/ghost_role_spawners.dm
Labels: Balance/Rebalance, Map Edit

#792 New diseases, Levels 0 and 9 for diseases [BOUNTY]
  beestation.dme
  code/datums/diseases/advance/presets.dm
  code/datums/diseases/advance/symptoms/beesymptom.dm
  code/datums/diseases/advance/symptoms/braindamage.dm
  code/datums/diseases/advance/symptoms/choking.dm
  code/datums/diseases/advance/symptoms/fire.dm
  code/datums/diseases/advance/symptoms/flesh_eating.dm
  code/datums/diseases/advance/symptoms/heal.dm
  code/datums/diseases/advance/symptoms/lubefeet.dm
  code/datums/diseases/advance/symptoms/pierrot.dm
  code/datums/diseases/advance/symptoms/radiation.dm
  code/datums/diseases/advance/symptoms/symptoms.dm
  code/datums/diseases/advance/symptoms/wizarditis.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/reagent_containers/bottle.dm
Labels: Code Improvement, Feature, Fix, Tweak, dme

#884 Adds lighting to xenobiology on Boxstation and Metastation
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Feature, Map Edit

#893 Azlan's Free Golem Ship Remake
  _maps/RandomRuins/LavaRuins/lavaland_surface_golem_ship.dmm
Labels: Feature, Map Edit

#891 Fixes broken sword icons
  code/game/objects/items/holy_weapons.dm
  code/game/objects/items/toys.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/holodeck/items.dm
Labels: Fix

#896 More robust dorfs. (#45304)
  code/datums/mutations/body.dm
Labels: Tweak

#863 Fix defib paddles burning desync (#44827)
  code/game/objects/items/defib.dm
Labels: Fix

#867 [PORT] Ash Lizard Improvements
  _maps/RandomRuins/LavaRuins/lavaland_surface_ash_walker1.dmm
  beestation.dme
  code/__DEFINES/components.dm
  code/datums/components/crafting/recipes.dm
  code/datums/mood_events/generic_negative_events.dm
  code/game/gamemodes/objective.dm
  code/game/objects/items/cigs_lighters.dm
  code/game/objects/items/handcuffs.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/game/objects/structures/headpike.dm
  code/modules/antagonists/_common/antag_team.dm
  code/modules/antagonists/ashwalker/ashwalker.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/gutlunch.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  code/modules/ruins/objects_and_mobs/ash_walker_den.dm
Labels: Feature, Fix, Map Edit, Tweak

#872 [PORT] Buffs tracking beacon EMPs, and makes EMP damage temporarily disable mech equipment (#44452)
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_construction_paths.dm
  code/game/mecha/mecha_control_console.dm
  code/game/mecha/mecha_defense.dm
  code/game/mecha/medical/medical.dm
  code/game/mecha/working/working.dm
  icons/mecha/mecha_mouse-disable.dmi
Labels: Balance/Rebalance, Sprites, Vote Passed

#897 [PORT] Drink Improvements
  _maps/RandomRuins/LavaRuins/lavaland_surface_ash_walker1.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  _maps/RandomRuins/SpaceRuins/deepstorage.dmm
  _maps/shuttles/ruin_caravan_victim.dmm
  _maps/shuttles/whiteship_box.dmm
  _maps/shuttles/whiteship_delta.dmm
  _maps/shuttles/whiteship_meta.dmm
  beestation.dme
  code/__DEFINES/construction.dm
  code/datums/components/crafting/crafting.dm
  code/datums/components/crafting/recipes.dm
  code/datums/mood_events/generic_positive_events.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/tanks/watertank.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/food_and_drinks/food/condiment.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_drink.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
  code/modules/reagents/reagent_containers/bottle.dm
  code/modules/reagents/reagent_containers/dropper.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/vending/boozeomat.dm
  code/modules/vending/cola.dm
  icons/obj/drinks.dmi
  icons/obj/reagentfillings.dmi
Labels: Code Improvement, Feature, Map Edit, Sprites, Tweak

#467 [READY] Elevators
  _maps/map_files/debug/multiz.dmm
  _maps/shuttles/turbolifts/debug_primary.dmm
  beestation.dme
  code/datums/shuttles.dm
  code/modules/shuttle/docking.dm
  code/modules/turbolift/README.md
  code/modules/turbolift/turbolift_areas.dm
  code/modules/turbolift/turbolift_docks.dm
  code/modules/turbolift/turbolift_machines.dm
  icons/obj/turbolift.dmi
  icons/obj/turbolift_door.dmi
  sound/effects/turbolift/elevatormusic.ogg
  sound/effects/turbolift/turbolift-close.ogg
  sound/effects/turbolift/turbolift.ogg
  tgui-next/packages/tgui/interfaces/TurboLift.js
  tgui-next/packages/tgui/public/tgui.bundle.js
  tgui-next/packages/tgui/routes.js
Labels: Map Edit, Needs Review, Sound, Sprites, UI, mapping

#890 Fixes most of mark's symptoms
  code/datums/diseases/advance/symptoms/beesymptom.dm
  code/datums/diseases/advance/symptoms/braindamage.dm
  code/datums/diseases/advance/symptoms/lubefeet.dm
  code/datums/diseases/advance/symptoms/pierrot.dm
  code/datums/diseases/advance/symptoms/skin.dm
  code/datums/diseases/advance/symptoms/wizarditis.dm
Labels: Tweak

#901 Adds lots of New Items to Syndicate Kits (#44509)
  code/game/objects/items/melee/energy.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/projectiles/ammunition/energy/special.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/projectile/energy/misc.dm
Labels: Feature

#902 Add match strike sound (#44949)
  code/game/objects/items/cigs_lighters.dm
  sound/items/match_strike.ogg
Labels: Sound

#906 SlimeHUD #44666
  beestation.dme
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/screen_objects.dm
  code/_onclick/hud/slime.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  icons/mob/screen_slime.dmi
Labels: Feature, Sprites

#905 Fixes butchering #47657
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Fix

#908 Fix swappers not working (#45027)
  code/game/objects/items/devices/swapper.dm
Labels: Fix

#900 Reduces number of traitors on brothers+traitors
  code/game/gamemodes/brother/traitor_bro.dm
Labels: Feature

#910 fixes a missing vendor board #44177
  code/game/objects/items/circuitboards/machine_circuitboards.dm
Labels: Fix

#909 Add log message when player dies (#44855)
  code/modules/mob/living/carbon/human/death.dm
Labels: Tweak

#894 [PORT] New Mime spells and icons
  code/game/objects/items/granters.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/structures/beds_chairs/chair.dm
  code/modules/jobs/job_types/mime.dm
  code/modules/spells/spell_types/mime.dm
  icons/mob/actions/actions_mime.dmi
  icons/mob/actions/actions_spells.dmi
Labels: Feature, Sprites, Tweak, Vote Passed

#731 Ports Bluespace Navigation Gigabeacon (#44807)
  _maps/map_files/Mining/Lavaland.dmm
  beestation.dme
  code/controllers/subsystem/shuttle.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/shuttle/navigation_computer.dm
  code/modules/shuttle/spaceship_navigation_beacon.dm
Labels: Feature, Map Edit, Port

#918 [PORT] command role species overrides happen before bank account update (#47…
  code/modules/jobs/job_types/_job.dm
Labels: Fix

#917 [PORT] purges the unclean janitors var (#47306)
  code/modules/jobs/job_types/janitor.dm
Labels: Fix

#913 SImplemob Limiters
  code/__DEFINES/mobs.dm
  code/_globalvars/misc.dm
  code/controllers/configuration/entries/game_options.dm
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/slime/death.dm
  code/modules/mob/living/simple_animal/slime/powers.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  config/game_options.txt
Labels: Config Update, Tweak

#914 Changed delay round end to +ADMIN
  code/modules/admin/topic.dm
Labels: Administration

#920 [PORT] Geiger counter will display the correct contamination values now. (#4…
  code/datums/components/radioactive.dm
Labels: Fix

#921 [PORT] Fixes gun overlays not updating when the cell is deleted (#48107)
  code/modules/projectiles/guns/energy.dm
Labels: Fix

#924 Fixes and speedups to spraycans/crayons (#44561)
  code/__HELPERS/text.dm
  code/game/objects/items/crayons.dm
  tgui/assets/tgui.js
Labels: Fix, Removal, Tweak, UI

#926 Radio jammers jam the radio more (#44313)
  code/game/objects/items/devices/radio/radio.dm
Labels: Balance/Rebalance

#916 [PORT] Fixes R&D Materials Exploit.
  code/modules/research/destructive_analyzer.dm
Labels: Fix

#929 Prevent abductors from abducting the disk #44234
  code/datums/components/stationloving.dm
Labels: Fix

#927 Changes dogs to neutral faction. (#44295)
  code/modules/mob/living/simple_animal/friendly/dog.dm
Labels: Fix

#932 Removes process() from comms console, no longer steals focus #44207
  code/game/machinery/computer/communications.dm
Labels: Fix, Removal

#933 Fixes windoors bump/hand interactions #44205
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/windowdoor.dm
Labels: Fix

#903 Blobs can choose from 4 different strains when rerolling #44209
  code/_onclick/hud/blob_overmind.dm
  code/modules/antagonists/blob/blobstrains/_blobstrain.dm
  code/modules/antagonists/blob/overmind.dm
  code/modules/antagonists/blob/powers.dm
Labels: Balance/Rebalance, Vote Passed

#931 Click intecepts stop ghost teleports #44214
  code/_onclick/observer.dm
Labels: Administration

#898 Durathread and loom changes. (#45261)
  _maps/map_files/KiloStation/KiloStation.dmm
  code/datums/components/crafting/tailoring.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/sheets/sheets.dm
  code/game/objects/structures/loom.dm
  code/modules/ruins/lavaland_ruin_code.dm
Labels: Code Improvement, Feature, Fix, Map Edit

#923 Fixes CNS rebooter. (#44630)
  code/modules/surgery/organs/augments_internal.dm
Labels: Fix

#937 Traitor Panel now shows the names of blood brothers' brothers. (#44040)
  code/modules/antagonists/brother/brother.dm
Labels: Administration

#938 Let service techfab make power cells (#44048)
  code/modules/research/designs/power_designs.dm
Labels: Tweak

#939 Fixes magic missile (#44147)
  code/modules/spells/spell_types/inflict_handler.dm
  code/modules/spells/spell_types/wizard.dm
Labels: Fix

#940 cargo crates fixes n tweaks (#44000)
  code/modules/cargo/packs.dm
Labels: Fix, Tweak

#942 Syndicate Bomb Bugfixes and Quality of Death Changes #43996
  code/datums/wires/syndicatebomb.dm
  code/game/machinery/syndicatebomb.dm
Labels: Feature, Tweak

#943 Fixes between the sheets (#44053)
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Labels: Fix

#944 ling fixes (#44055)
  code/__DEFINES/DNA.dm
  code/datums/diseases/transformation.dm
  code/datums/mutations/body.dm
  code/modules/antagonists/changeling/powers/augmented_eyesight.dm
  code/modules/antagonists/changeling/powers/humanform.dm
  code/modules/antagonists/changeling/powers/lesserform.dm
  code/modules/antagonists/changeling/powers/tiny_prick.dm
  code/modules/antagonists/monkey/monkey.dm
  code/modules/mob/transform_procs.dm
Labels: Fix, Tweak

#945 Stops corpses from receiving new information about their damaged brain #44028
  code/modules/mob/living/carbon/damage_procs.dm
Labels: Fix

#946 Colossus chest ignores colossus bolts (#44050)
  code/modules/mining/lavaland/necropolis_chests.dm
Labels: Fix, Tweak

#935 new symptom fixes p2
  code/datums/diseases/advance/symptoms/radiation.dm
Labels: Fix, Tweak

#934 New midround join screen (#44193)
  code/modules/jobs/job_types/bartender.dm
  code/modules/mob/dead/new_player/new_player.dm
  html/browser/playeroptions.css
Labels: Tweak

#949 Smoking is now rad. [Ready] (#44066)
  code/modules/power/supermatter/supermatter.dm
  strings/tips.txt
Labels: Feature, Needs Review

#957 Changed two occurrences of "rice" into "sugar" to make them use the sugar icon instead of the rice icon (#48148)
  code/modules/food_and_drinks/food/condiment.dm
Labels: Fix

#950 Fixes some missing adjancency checks. (#44020)
  code/game/machinery/aug_manipulator.dm
  code/game/machinery/computer/apc_control.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/stasis.dm
  code/game/machinery/washing_machine.dm
  code/game/objects/items/RPD.dm
  code/game/objects/items/cardboard_cutouts.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/devices/transfer_valve.dm
  code/game/objects/items/storage/book.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/safe.dm
  code/modules/assembly/health.dm
  code/modules/events/pirates.dm
  code/modules/food_and_drinks/kitchen_machinery/microwave.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/modular_computers/computers/item/computer.dm
  code/modules/modular_computers/computers/item/laptop.dm
  code/modules/reagents/chemistry/machinery/reagentgrinder.dm
Labels: Fix

#961 adds a new roundend sound (why ban)
  code/controllers/subsystem/ticker.dm
  sound/roundend/whyban.ogg
Labels: Sound

#960 Exclude beebot from the credits contrib list
  tools/fetchContributors.py
Labels: Config Update, Fix, Tools

#928 Improved Wanted Posters
  code/game/machinery/computer/security.dm
  code/game/objects/effects/wanted_poster.dm
  icons/Font_Minimal.dmi
  icons/obj/poster_wanted.dmi
Labels: Feature, Sprites

#965 Silicon reach increased #47510
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/security.dm
Labels: Fix

#967 Mining cyborgs can choose the old mining cyborg icon plus one other from Citadel. #47973
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  icons/mob/robots.dmi
Labels: Feature, Sprites, Tweak

#968 Adds headcrabs back to the gold extract pool.
  code/modules/mob/living/simple_animal/hostile/headcrab.dm
Labels: Feature, Vote Passed

#963 adds 32 emojis from tg
  icons/emoji.dmi
Labels: Feature, Sprites, Vote Passed

#953 Adds the Pushover and Frail quirks #44894
  code/__DEFINES/traits.dm
  code/datums/traits/negative.dm
  code/modules/mob/living/living.dm
Labels: Feature, Vote Passed

#889 [Port] Interns! by Shapsy.
  code/datums/ert.dm
  code/modules/antagonists/ert/ert.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/jobs/access.dm
  icons/mob/head.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, Sprites

#922 Makes the Syndibase look more evil. #44490
  _maps/map_files/generic/CentCom.dmm
  code/game/turfs/closed.dm
Labels: Map Edit, Tweak

#930 Deletes a single pipe on BoxStation
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Fix, Map Edit

#959 Lets make that Beacon Wonderful
  code/modules/shuttle/spaceship_navigation_beacon.dm
  icons/obj/machines/NavBeacon.dmi
Labels: Sprites

#990 Adds surgical drill suicide ported from tgstation
  code/modules/surgery/tools.dm
Labels: Feature

#994 Resprites the entirety of the beret set, take two
  icons/mob/head.dmi
Labels: Sprites

#978 Fix Random Parallax Layers
  code/_onclick/hud/parallax.dm
Labels: Fix

#956 brings back the clown planet as a new space ruin (now with a sense of style) (#46953)
  _maps/RandomRuins/SpaceRuins/clownplanet.dmm
  code/datums/ruins/space.dm
  code/game/area/areas/ruins/lavaland.dm
  config/spaceruinblacklist.txt
Labels: Config Update, Feature, Map Edit

#995 Admins with R_ADMIN can now also restart the server.
  code/controllers/subsystem/ticker.dm
Labels: Administration, Fix

#821 [PORT] Vomitgoose
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/turfs/turf.dm
  code/modules/mob/living/simple_animal/hostile/goose.dm
  icons/mob/animal.dmi
Labels: Feature, Map Edit, Port, Sprites

#874 [PORT] Makes mechtopic look nice. (#45902)
  code/game/mecha/mecha_topic.dm
Labels: Code Improvement, Needs Testmerge, Tweak

#998 Players can now see their own notes.
  config/config.txt
Labels: Config Update

#999 Removes Headslugs from gold slime pool (again) (READ FULL PR)
  code/modules/mob/living/simple_animal/hostile/headcrab.dm
Labels: Removal

#1001 Map changes for randomized lavaland atmos
  _maps/RandomRuins/LavaRuins/lavaland_biodome_beach.dmm
  _maps/RandomRuins/LavaRuins/lavaland_biodome_clown_planet.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_animal_hospital.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_biodome_winter.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_cultaltar.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_dead_ratvar.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_hermit.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_pizzaparty.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_swarmer_crash.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_ufo_crash.dmm
Labels: Map Edit

#1004 Fix issues with Central Command
  _maps/map_files/generic/CentCom.dmm
  code/game/machinery/doors/poddoor.dm
  code/game/machinery/doors/shutters.dm
Labels: Map Edit, Tweak

#919 Fixes windows on the Free Golem Ship
  _maps/RandomRuins/LavaRuins/lavaland_surface_golem_ship.dmm
Labels: Fix, Map Edit

#1003 Crossbreed Descriptions #44125
  code/modules/research/xenobiology/crossbreeding/__corecross.dm
  code/modules/research/xenobiology/crossbreeding/burning.dm
  code/modules/research/xenobiology/crossbreeding/charged.dm
  code/modules/research/xenobiology/crossbreeding/chilling.dm
  code/modules/research/xenobiology/crossbreeding/consuming.dm
  code/modules/research/xenobiology/crossbreeding/industrial.dm
  code/modules/research/xenobiology/crossbreeding/prismatic.dm
  code/modules/research/xenobiology/crossbreeding/recurring.dm
  code/modules/research/xenobiology/crossbreeding/regenerative.dm
  code/modules/research/xenobiology/crossbreeding/reproductive.dm
  code/modules/research/xenobiology/crossbreeding/selfsustaining.dm
  code/modules/research/xenobiology/crossbreeding/stabilized.dm
Labels: Feature

#1002 It's loose
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Feature, Map Edit

#985 Dexalin, Dex+, and two new chems
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
Labels: Feature, Vote Passed

#952 Small dish drive improvements #44756
  code/game/machinery/dish_drive.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/vending/wardrobes.dm
Labels: Feature, Tweak

#991 Slap My Hand
  code/game/objects/items/weaponry.dm
  code/modules/mob/living/emote.dm
Labels: Feature

#1006 Removes miasma from the lavaland gasses
  code/datums/atmosphere/planetary.dm
Labels: Removal

#1008 Fixes reading paper on airlocks
  code/modules/paperwork/paper.dm
Labels: Fix

#1010 set parent.orbiters on register (#47344)
  code/datums/components/orbiter.dm
Labels: Fix

#1011 Stimpack syringe changed into medipen #46075
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/uplink/uplink_items.dm
  icons/obj/syringe.dmi
Labels: Sprites, Tweak

#1000 Brig Physicians
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  beestation.dme
  code/__DEFINES/jobs.dm
  code/datums/traits/negative.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/clock_cult/clock_cult.dm
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/gangs/gangs.dm
  code/game/gamemodes/revolution/revolution.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/machinery/computer/card.dm
  code/game/machinery/computer/crew.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/religion.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/client/preferences.dm
  code/modules/clothing/head/soft_caps.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/crew_objectives/security_objectives.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/brigphys.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  config/jobs.txt
  icons/mob/head.dmi
  icons/mob/hud.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/closet.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/radio.dmi
Labels: Config Update, Feature, Fix, Map Edit, Sprites, Vote Passed, ike approved™

#1013 [PORT] crusher miner eye trophy slowdown bugfix (#46371)
  code/datums/status_effects/buffs.dm
Labels: Fix

#1017 Brig Phys get medical themed bags
  code/modules/jobs/job_types/brigphys.dm
Labels: Fix

#971 Minor ghost notify changes (#45759)
  code/game/machinery/syndicatebomb.dm
  code/game/objects/items/devices/reverse_bear_trap.dm
  code/game/objects/items/eightball.dm
  code/game/objects/items/grenades/plastic.dm
  code/game/objects/structures/spirit_board.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/awaymissions/capture_the_flag.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/simple_animal/friendly/drone/drones_as_items.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/power/singularity/field_generator.dm
  code/modules/projectiles/guns/energy/pulse.dm
  code/modules/ruins/objects_and_mobs/necropolis_gate.dm
Labels: Feature

#1021 Oxygen treatment kits contain Dexalin medipens
  code/game/objects/items/storage/firstaid.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  icons/mob/inhands/equipment/medical_lefthand.dmi
  icons/mob/inhands/equipment/medical_righthand.dmi
  icons/obj/syringe.dmi
Labels: Feature, Sprites

#1023 Revert "Beesease bugfixes" -_-
  code/datums/diseases/advance/symptoms/beesymptom.dm
Labels: Revert

#975 FIXES/COMPLETES ALL (new) DISEASES, /tg/ style cures, new level 0
  code/datums/diseases/advance/advance.dm
  code/datums/diseases/advance/symptoms/beesymptom.dm
  code/datums/diseases/advance/symptoms/braindamage.dm
  code/datums/diseases/advance/symptoms/cockroach.dm
  code/datums/diseases/advance/symptoms/lubefeet.dm
  code/datums/diseases/advance/symptoms/radiation.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature, Fix, Tweak

#873 Adds beating vending machines for free stuff/getting crushed to death
  beestation.dme
  code/datums/elements/squish.dm
  code/modules/vending/_vending.dm
  code/modules/vending/medical_wall.dm
Labels: Feature, Stale

#1022 Renames a space ruin GPS signal
  _maps/shuttles/ruin_caravan_victim.dmm
Labels: Map Edit

#1029 Adds new chaplain armor to the armament beacon (#46734)
  code/game/objects/items/holy_weapons.dm
Labels: Feature

#993 Lavaland Elites (Free bugfixes included!)
  _maps/RandomRuins/LavaRuins/lavaland_surface_elite_tumor.dmm
  beestation.dme
  code/_onclick/hud/lavaland_elite.dm
  code/_onclick/hud/screen_objects.dm
  code/datums/mood_events/generic_positive_events.dm
  code/datums/ruins/lavaland.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/elite.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/goliath_broodmother.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/herald.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/legionnaire.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/pandora.dm
  icons/mob/accessories.dmi
  icons/mob/actions/actions_elites.dmi
  icons/mob/lavaland/lavaland_elites.dmi
  icons/mob/neck.dmi
  icons/mob/screen_elite.dmi
  icons/obj/lavaland/artefacts.dmi
  icons/obj/lavaland/elite_trophies.dmi
  icons/obj/lavaland/legionnaire_bonfire.dmi
  icons/obj/lavaland/tumor.dmi
Labels: Feature, Map Edit, Sprites

#1025 Fixes my mistakes
  beestation.dme
  code/datums/diseases/advance/symptoms/beesymptom.dm
  code/datums/diseases/advance/symptoms/cockroach.dm
Labels: Fix

#1026 Viro Fixes/Rebalances (Semi-urgent)
  code/datums/diseases/advance/symptoms/lubefeet.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/reagent_containers/bottle.dm
Labels: Code Improvement, Feature, Fix, Tweak

#1020 Squids Color Change ability uses a color picker
  code/modules/mob/living/carbon/human/species_types/squidpeople.dm
Labels: Tweak

#1030 Actual antag token in the beecoin shop
  code/modules/client/loadout/loadout_general.dm
  code/modules/client/loadout/loadout_ooc.dm
Labels: Feature, Needs Vote

#1041 Enables antag rep
  code/controllers/configuration/entries/game_options.dm
  code/modules/jobs/job_types/_job.dm
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Config Update, Feature

#1035 Removes roburger from fast food ruin
  _maps/RandomRuins/SpaceRuins/Fast_Food.dmm
Labels: Map Edit, Removal

#1037 No more cargo pod steal shuttle ports. (#45962)
  code/modules/shuttle/supply.dm
Labels: Fix

#1042 Shuttle fixes and improvements
  _maps/RandomZLevels/snowdin.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/generic/CentCom.dmm
  code/modules/shuttle/navigation_computer.dm
  code/modules/shuttle/shuttle.dm
Labels: Fix, Map Edit

#1038 New admin only gamemode: traitorchan with no protected roles
  code/game/gamemodes/changeling/traitor_chan.dm
Labels: Feature, Vote Passed

#1036 Small cigarette refactor and Syndie cigs more viable for healing (#45711)
  code/game/objects/items/cigs_lighters.dm
Labels: Code Improvement, Refactor, Tweak

#1048 Makes Travis's check_grep script work on json files with multiple maps
  tools/travis/check_grep.sh
Labels: Config Update, Fix, Tools

#1046 New mining scanner sprites, ERT hardsuits get integrated jetpacks, misc sprite changes.
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/mining/equipment/mineral_scanner.dm
  icons/mob/human.dmi
  icons/mob/human_parts.dmi
  icons/mob/human_parts_greyscale.dmi
  icons/obj/Bamboo_assetsUPDATE.dmi
  icons/obj/device.dmi
Labels: Feature, Fix, Removal, Sprites, Vote Passed

#1051 Adds speedwagon's sexy hat
  beestation.dme
  code/modules/client/loadout/loadout_hat.dm
  code/modules/clothing/head/misc_special.dm
  icons/mob/large-worn-icons/64x64/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Feature, Sprites

#1050 Prevents roundstart suicide on Sage
  code/controllers/configuration/entries/game_options.dm
  code/modules/client/verbs/suicide.dm
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Config Update, Feature

#892 [PORT] Improves chem dispenser macros (#45397)
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
Labels: Feature, Fix, Removal

#1052 Bulk port of TG fixes & code improvements
  code/__DEFINES/movespeed_modification.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/names.dm
  code/__HELPERS/type2type.dm
  code/controllers/subsystem/timer.dm
  code/datums/components/uplink.dm
  code/datums/martial/cqc.dm
  code/datums/martial/psychotic_brawl.dm
  code/datums/martial/sleeping_carp.dm
  code/game/area/areas.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/sandbox/h_sandbox.dm
  code/game/objects/items.dm
  code/game/objects/items/RCD.dm
  code/game/objects/items/handcuffs.dm
  code/game/objects/items/tools/wrench.dm
  code/game/turfs/space/space.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/cargo/exports/seeds.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/mining/machine_redemption.dm
  code/modules/mining/machine_silo.dm
  code/modules/mining/machine_stacking.dm
  code/modules/mining/mine_items.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_movement.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/living_movement.dm
  code/modules/mob/mob.dm
  code/modules/modular_computers/hardware/network_card.dm
  code/modules/research/machinery/_production.dm
  code/modules/surgery/bodyparts/dismemberment.dm
Labels: Balance/Rebalance, Feature, Fix

#1043 emptytable
  _maps/RandomRuins/SpaceRuins/Fast_Food.dmm
Labels: Feature, Map Edit

#1009 Add copper to the derelict
  _maps/RandomRuins/SpaceRuins/TheDerelict.dmm
Labels: Feature, Map Edit

#992 Mech Thrusters
  code/game/gamemodes/clown_ops/clown_weapons.dm
  code/game/mecha/combat/gygax.dm
  code/game/mecha/combat/marauder.dm
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/equipment/tools/other_tools.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_actions.dm
  code/game/mecha/mecha_topic.dm
  code/modules/research/designs/mecha_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/mecha/mecha_equipment.dmi
Labels: Feature, Sprites, Tweak

#996 Adds surgical equipment to Brig on all stations except Kilo
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit

#988 Makes the Mining Base Better
  _maps/map_files/Mining/Lavaland.dmm
Labels: Fix, Map Edit, Tweak

#1053 Generic title
  _maps/RandomRuins/SpaceRuins/bus.dmm
  code/game/objects/items/manuals.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/food_and_drinks/recipes/processor_recipes.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pizza.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_salad.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_soup.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_spaghetti.dm
  code/modules/holiday/easter.dm
Labels: Map Edit

#958 Adds groin kick with conditional damage
  code/modules/mob/living/carbon/human/human.dm
Labels: Feature, Vote Passed

#1055 Adds BeeBot to the AI name list
  strings/names/ai.txt
Labels: Feature

#1049 CARPS.
  code/game/objects/items/pneumaticCannon.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/game/objects/items/weaponry.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
Labels: Balance/Rebalance, Fix, Sprites, Tweak, Vote Passed

#1061 [BOUNTY] Bluespace Mining Machine
  beestation.dme
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/mining/machine_bluespaceminer.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature

#1062 Sentient Lavaland Elites will now give a ghost orbit notification (#48347)
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/elite.dm
Labels: Tweak

#1070 Removes felinids from roundstart races
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Config Update, Needs Vote, Removal

#1059 Adds support for 513 while maintaining support for 512
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/maths.dm
  code/__DEFINES/misc.dm
  code/__DEFINES/typeids.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/text.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/hud/plane_master.dm
  code/datums/emotes.dm
  code/game/machinery/newscaster.dm
  code/game/machinery/status_display.dm
  code/game/objects/structures/musician.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/modifyvariables.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob_helpers.dm
  code/modules/surgery/organs/organ_internal.dm
  tools/Redirector/textprocs.dm
Labels: Tools

#1074 Final 513 changes
  Dockerfile
  SQL/ban_conversion_2018-10-28.py
  SQL/beestation_schema.sql
Labels: sql

#1071 New brigphys spriters, emt sprites and envirosuits for both
  code/modules/clothing/outfits/plasmaman.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/clothing/under/jobs/Plasmaman/medsci.dm
  code/modules/clothing/under/jobs/Plasmaman/security.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/jobs/job_types/emt.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, Sprites

#1076 Removes a loophole
  code/game/machinery/computer/communications.dm
Labels: Removal

#1057 More plushies
  _maps/RandomRuins/SpaceRuins/Fast_Food.dmm
Labels: Feature, Map Edit

#1012 Mergingruins
  _maps/RandomRuins/SpaceRuins/power_puzzle.dmm
  _maps/RandomRuins/SpaceRuins/scav_mining.dmm
  code/datums/ruins/space.dm
  code/game/area/areas/ruins/space.dm
Labels: Feature, Map Edit

#1075 Fix: power sink's power_drained change limited to APC cell's charge
  code/game/objects/items/devices/powersink.dm
Labels: Fix
