Repository BeeStation/BeeStation-Hornet, pull requests merged in 2019-11, with the labels that each got.

#685 More fixes for Box Station
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit

#683 Renault exists on BoxStation
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Feature, Map Edit

#690 BoxStation Enhancements, Departmental Signs
  _maps/map_files/BoxStation/BoxStation.dmm
  code/game/objects/structures/signs/signs_departments.dm
  icons/obj/decals.dmi
Labels: Map Edit, Sprites, Tweak

#694 Gives zombies a big bad message #44986
  code/modules/zombie/organs.dm
Labels: Feature

#693 [READY] Ore Redemption Fix
  code/modules/mining/machine_redemption.dm
Labels: Fix, Needs Review, Tweak

#691 Emags can now be used on closets, regardless of whatever intent you use. #45743
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Tweak

#665 Inhand sprites for tiles #45611
  code/game/objects/items/stacks/tiles/tile_mineral.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/modules/research/xenobiology/xenobiology.dm
  icons/mob/inhands/misc/sheets_lefthand.dmi
  icons/mob/inhands/misc/sheets_righthand.dmi
Labels: Sprites

#705 Fixes the holodeck computer
  code/modules/holodeck/computer.dm
Labels: Fix

#695 [Bounty] Banana mutation
  code/game/machinery/computer/dna_console.dm
Labels: Feature

#699 [Bounty] Plumbing
  beestation.dme
  code/__DEFINES/access.dm
  code/__DEFINES/components.dm
  code/__DEFINES/plumbing.dm
  code/__DEFINES/reagents.dm
  code/datums/components/plumbing/_plumbing.dm
  code/datums/components/plumbing/chemical_acclimator.dm
  code/datums/components/plumbing/filter.dm
  code/datums/components/plumbing/plumbing.dm
  code/datums/components/plumbing/reaction_chamber.dm
  code/datums/components/plumbing/splitter.dm
  code/datums/ductnet.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/machinery/_machinery.dm
  code/game/objects/effects/effect_system/effects_smoke.dm
  code/game/objects/items/RCD.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/manuals.dm
  code/modules/crafting/recipes.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/chemist.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/medical_doctor.dm
  code/modules/plumbing/ducts.dm
  code/modules/plumbing/plumbers/_plumb_machinery.dm
  code/modules/plumbing/plumbers/acclimator.dm
  code/modules/plumbing/plumbers/destroyer.dm
  code/modules/plumbing/plumbers/filter.dm
  code/modules/plumbing/plumbers/pill_press.dm
  code/modules/plumbing/plumbers/pumps.dm
  code/modules/plumbing/plumbers/reaction_chamber.dm
  code/modules/plumbing/plumbers/splitters.dm
  code/modules/plumbing/plumbers/synthesizer.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/chemistry/machinery/chem_heater.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/reagents/chemistry/machinery/chem_synthesizer.dm
  code/modules/reagents/chemistry/machinery/smoke_machine.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  code/modules/reagents/reagent_dispenser.dm
  code/modules/research/designs/autolathe_designs.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/obj/2x2.dmi
  icons/obj/library.dmi
  icons/obj/plumbing/fluid_ducts.dmi
  icons/obj/plumbing/plumbers.dmi
  icons/obj/tools.dmi
  icons/turf/areas.dmi
  tgui-next/packages/tgui/public/bundles/tgui.bundle.js
  tgui/assets/tgui.js
  tgui/src/interfaces/acclimator.ract
  tgui/src/interfaces/chem_splitter.ract
  tgui/src/interfaces/chemical_filter.ract
  tgui/src/interfaces/reaction_chamber.ract
Labels: Feature, Needs Testmerge, Port, Sprites, UI

#708 Ports husking visual fix #45648
  code/modules/mob/living/status_procs.dm
Labels: Fix

#707 More tgui-next
  code/game/machinery/computer/Operating.dm
  code/game/machinery/computer/atmos_control.dm
  code/modules/atmospherics/machinery/airalarm.dm
  code/modules/atmospherics/machinery/components/trinary_devices/filter.dm
  code/modules/atmospherics/machinery/components/trinary_devices/mixer.dm
  code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
  tgui-next/bin/tgui-build.bat
  tgui-next/packages/tgui-dev-server/link/retrace.js
  tgui-next/packages/tgui/components/AnimatedNumber.js
  tgui-next/packages/tgui/components/NumberInput.js
  tgui-next/packages/tgui/components/Table.scss
  tgui-next/packages/tgui/components/Tabs.js
  tgui-next/packages/tgui/components/index.js
  tgui-next/packages/tgui/constants.js
  tgui-next/packages/tgui/interfaces/AirAlarm.js
  tgui-next/packages/tgui/interfaces/AtmosControlConsole.js
  tgui-next/packages/tgui/interfaces/AtmosFilter.js
  tgui-next/packages/tgui/interfaces/AtmosMixer.js
  tgui-next/packages/tgui/interfaces/AtmosPump.js
  tgui-next/packages/tgui/interfaces/ChemHeater.js
  tgui-next/packages/tgui/interfaces/ChemMaster.js
  tgui-next/packages/tgui/interfaces/CrewConsole.js
  tgui-next/packages/tgui/interfaces/OperatingComputer.js
  tgui-next/packages/tgui/interfaces/ThermoMachine.js
  tgui-next/packages/tgui/interfaces/common/atmos.js
  tgui-next/packages/tgui/public/tgui.bundle.css
  tgui-next/packages/tgui/public/tgui.bundle.js
  tgui-next/packages/tgui/routes.js
  tgui-next/packages/tgui/styles/color-map.scss
  tgui-next/packages/tgui/styles/variables.scss
Labels: UI

#698 More fixes and tweaks for BoxStation
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Feature, Fix, Map Edit

#655 Berets
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/head/jobs.dm
  code/modules/vending/wardrobes.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Feature, Sprites, Vote Passed, ike approved™

#713 DeltaStation Departmental signs and carpets
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Feature, Map Edit

#702 MetaStation Departmental signs, bar update, carpets and plants
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Feature, Map Edit, Tweak

#712 Ports Improved Beach Away Mission #44673
  _maps/RandomZLevels/TheBeach.dmm
  _maps/RandomZLevels/beach.dmm
  _maps/RandomZLevels/beach2.dmm
  config/awaymissionconfig.txt
Labels: Config Update, Feature, Map Edit, Removal

#704 RSC Changes
  README.md
  code/_compile_options.dm
  config/external_rsc_urls.txt
Labels: Config Update

#721 Adds white no slip tiles to MetaStation
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Map Edit, Tweak

#724 Adds caramel (#44419)
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/recipes/food_mixtures.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
Labels: Feature, Port

#701 Gives borg tools unused sprites #45939
  code/game/objects/items/kitchen.dm
  code/game/objects/items/theft_tools.dm
  code/game/objects/items/tools/crowbar.dm
  code/game/objects/items/tools/screwdriver.dm
  code/game/objects/items/tools/weldingtool.dm
  code/game/objects/items/tools/wirecutters.dm
  code/game/objects/items/tools/wrench.dm
  code/modules/surgery/organs/augments_arms.dm
  icons/obj/items_cyborg.dmi
  icons/obj/surgery.dmi
Labels: Port, Sprites, Tweak

#722 Restoration of a lost relic, Alien queen maid.
  code/modules/mob/living/carbon/alien/humanoid/queen.dm
  icons/mob/alienqueen.dmi
Labels: Sprites

#723 Ports Make a crapload of new cardboard boxes craftable (#44744)
  code/game/objects/items/stacks/sheets/sheet_types.dm
Labels: Feature, Port

#725 Validate committed tgui build in Travis
  tgui-next/.gitattributes
  tgui-next/README.md
  tgui-next/bin/tgui
  tgui-next/bin/tgui-dev-server.bat
  tgui-next/package.json
  tools/hooks/install.sh
  tools/travis/build_tgui.sh
Labels: Port, Tools, UI

#696 Pixel vars now cause travis to fail
  tools/travis/check_grep.sh
Labels: Tools

#726 Language and Crafting tgui-next
  _maps/RandomZLevels/TheBeach.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  beestation.dme
  code/__DEFINES/components.dm
  code/_onclick/hud/generic_dextrous.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/screen_objects.dm
  code/datums/components/crafting/crafting.dm
  code/datums/components/crafting/guncrafting.dm
  code/datums/components/crafting/recipes.dm
  code/datums/components/crafting/tailoring.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  code/modules/holodeck/computer.dm
  code/modules/language/language_menu.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/login.dm
  tgui-next/packages/tgui/components/Icon.js
  tgui-next/packages/tgui/interfaces/CrewConsole.js
  tgui-next/packages/tgui/interfaces/LanguageMenu.js
  tgui-next/packages/tgui/interfaces/PersonalCrafting.js
  tgui-next/packages/tgui/public/tgui.bundle.js
  tgui-next/packages/tgui/routes.js
Labels: Map Edit, Port, Tweak, UI

#714 2 New Screams
  code/modules/mob/living/carbon/human/emote.dm
  sound/voice/human/femalescream_4.ogg
  sound/voice/human/malescream_5.ogg
Labels: Feature, Port, Sound, Vote Passed

#733 Ports Changes IC button to not be as infuriating #44583
  code/modules/admin/verbs/adminhelp.dm
Labels: Administration

#730 Being attacked now shows the correct attacker
  code/_onclick/item_attack.dm
Labels: Fix

#729 Ports Modifies the Mechfab to use the Ore Silo #47619
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  code/game/mecha/mech_fabricator.dm
Labels: Feature, Map Edit, Port

#732 Makes the medical job selection options blue
  code/modules/jobs/job_types/chemist.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/emt.dm
  code/modules/jobs/job_types/geneticist.dm
  code/modules/jobs/job_types/medical_doctor.dm
  code/modules/jobs/job_types/virologist.dm
Labels: Tweak

#728 Plumbing icons
  icons/obj/plumbing/fluid_ducts.dmi
  icons/obj/plumbing/plumbers.dmi
Labels: Sprites, Vote Passed

#736 Ports Improved station ambience
  sound/ambience/shipambience.ogg
Labels: Sound

#737 Blood brother alert now has sound and bigger text #44293
  code/datums/mind.dm
  code/modules/antagonists/brother/brother.dm
  code/modules/antagonists/creep/creep.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/goonchat/browserassets/css/browserOutput_white.css
Labels: Feature

#720 Plasmamen get plasma in their box (#45538)
  code/game/objects/items/storage/boxes.dm
  code/modules/jobs/job_types/clown.dm
  code/modules/jobs/job_types/station_engineer.dm
Labels: Port, Vote Passed

#711 Xeno WinConditions
  code/modules/antagonists/xeno/xeno.dm
  code/modules/shuttle/emergency.dm
Labels: Feature, Port

#747 Fixes Janitor Cyborg Reagents
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Fix

#763 Ports refactors event announce chance (#47085)
  code/modules/admin/secrets.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/events/_event.dm
  code/modules/events/blob.dm
  code/modules/events/ion_storm.dm
  code/modules/paperwork/contract.dm
Labels: Administration, Refactor

#716 Ports Antagonist tips from Hippie Station
  beestation.dme
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/antagonists/_common/antag_popup.dm
  code/modules/antagonists/_common/tips.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/client/asset_cache.dm
  html/antagtips/abductor.html
  html/antagtips/blob.html
  html/antagtips/changeling.html
  html/antagtips/cult.html
  html/antagtips/nukie.html
  html/antagtips/traitor.html
  html/antagtips/wizard.html
  html/antagtips/xeno.html
  html/img/abaton.png
  html/img/absorb.png
  html/img/alienorgan.png
  html/img/archives.png
  html/img/ayylmao.png
  html/img/blobcore.png
  html/img/blobfactory.png
  html/img/blobnode.png
  html/img/blobresource.png
  html/img/bloodcult.png
  html/img/changeling.gif
  html/img/dagger.png
  html/img/disk.png
  html/img/emporium.gif
  html/img/eshield.png
  html/img/facehugger.png
  html/img/headset.png
  html/img/hivemind.png
  html/img/mech.png
  html/img/nuke.png
  html/img/nukie.png
  html/img/pda.png
  html/img/pen.png
  html/img/sacrune.png
  html/img/scitool.png
  html/img/scroll.png
  html/img/spellbook.png
  html/img/sting_extract.png
  html/img/tentacle.png
  html/img/traitor.png
  html/img/wizard.png
  html/img/xeno.png
  html/img/xenolarva.png
  html/img/xenoqueen.png
Labels: Feature, Port

#765 Ports separated Medical Weaponry tech node
  code/modules/research/techweb/all_nodes.dm
Labels: Vote Passed

#764 Added, Tweaked: Flypeople (BEES!)
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/lists/flavor_misc.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
  icons/mob/human_parts.dmi
Labels: Feature, Sprites, Tweak, Vote Passed

#738 Ports energy cake and modifies birthday cake
  code/modules/clothing/head/misc_special.dm
  code/modules/food_and_drinks/food/snacks_cake.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_cake.dm
  icons/mob/head.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/food/piecake.dmi
Labels: Feature, Fix, Port, Sprites, Vote Passed

#771 Ports you can now only check yourself for injuries if you are conscious
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Fix, Tweak

#777 Fixes clockwork slab interface
  tgui/assets/tgui.js
  tgui/src/interfaces/clockwork_slab.ract
Labels: Fix, UI

#768 Station Donksoft Vendor Resprite
  code/modules/vending/toys.dm
  icons/obj/vending.dmi
Labels: Sprites, Vote Passed

#770 Ports increases dual wielded energy weapon spread
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
Labels: Balance/Rebalance, Vote Passed

#769 [port] you now always face the direction you're crawling
  code/modules/mob/living/carbon/update_icons.dm
  code/modules/mob/living/living.dm
Labels: Tweak, test merged

#775 Ports Pepperspray rework
  code/__DEFINES/inventory.dm
  code/__DEFINES/movespeed_modification.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/hailer.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/spacesuits/_spacesuits.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/suits/bio.dm
  code/modules/clothing/suits/utility.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/reagent_containers/spray.dm
Labels: Balance/Rebalance, Feature, Tweak, Vote Passed

#774 Ports Explosion rebalancing
  code/__DEFINES/combat.dm
  code/game/objects/effects/effect_system/effects_other.dm
  code/game/objects/items/devices/doorCharge.dm
  code/game/objects/items/grenades/plastic.dm
  code/modules/antagonists/devil/true_devil/_true_devil.dm
  code/modules/mob/living/carbon/alien/alien_defense.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/monkey/monkey_defense.dm
  code/modules/mob/living/simple_animal/animal_defense.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
Labels: Balance/Rebalance, Code Improvement, Vote Passed

#787 Fixes circuits. Finally.
  code/modules/integrated_electronics/core/integrated_circuit.dm
Labels: Fix

#788 Ports Better shuttle sound algorithm (#43884)
  code/modules/shuttle/shuttle.dm
  sound/effects/hyperspace_begin_distance.ogg
  sound/effects/hyperspace_end_distance.ogg
  sound/effects/hyperspace_progress_distance.ogg
Labels: Fix, Sound

#785 [PORT] 3 new gas interactions for the SM
  code/modules/power/supermatter/supermatter.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature

#793 Fix Cryostasis Shotgun Darts
  code/modules/research/designs/weapon_designs.dm
Labels: Fix

#790 Adds 2% chance xeno egg to the maps that don't have it
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Feature, Map Edit

#779 [Needs Vote] Ports Reebe Change from YogStation
  _maps/map_files/generic/City_of_Cogs.dmm
  code/game/gamemodes/clock_cult/clock_cult.dm
  icons/effects/clockwork_effects.dmi
Labels: Feature, Map Edit, Port, Sprites, Vote Passed

#794 [PORT] Removes SSreligion and adds the hypertool
  beestation.dme
  code/_globalvars/misc.dm
  code/controllers/subsystem/religion.dm
  code/game/objects/items/holy_weapons.dm
  code/game/objects/items/storage/book.dm
  code/modules/admin/verbs/pray.dm
  code/modules/jobs/job_types/chaplain.dm
  code/modules/library/lib_machines.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  icons/mob/inhands/equipment/tools_lefthand.dmi
  icons/mob/inhands/equipment/tools_righthand.dmi
  icons/obj/device.dmi
  icons/obj/storage.dmi
Labels: Feature, Port, Removal, Sprites, Tweak

#743 [READY] Repipes BoxStation
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit, Needs Review, Tweak

#803 [PORT]Humanizing a monkey no longer yeets any buried smuggler's satchels from the tile onto their person.
  code/modules/mob/transform_procs.dm
Labels: Fix

#801 [PORT] Fixes powernet avail checks
  code/modules/power/apc.dm
  code/modules/power/cable.dm
  code/modules/power/power.dm
Labels: Fix, Port

#791 Ports Advanced space hitch-hiking apparatus (#47679)
  code/game/objects/items/devices/instruments.dm
  icons/mob/inhands/equipment/instruments_lefthand.dmi
  icons/mob/inhands/equipment/instruments_righthand.dmi
  icons/obj/musician.dmi
  sound/instruments/banjo/Ab3.ogg
  sound/instruments/banjo/Ab4.ogg
  sound/instruments/banjo/Ab5.ogg
  sound/instruments/banjo/An3.ogg
  sound/instruments/banjo/An4.ogg
  sound/instruments/banjo/An5.ogg
  sound/instruments/banjo/Bb3.ogg
  sound/instruments/banjo/Bb4.ogg
  sound/instruments/banjo/Bb5.ogg
  sound/instruments/banjo/Bn2.ogg
  sound/instruments/banjo/Bn3.ogg
  sound/instruments/banjo/Bn4.ogg
  sound/instruments/banjo/Bn5.ogg
  sound/instruments/banjo/Cn3.ogg
  sound/instruments/banjo/Cn4.ogg
  sound/instruments/banjo/Cn5.ogg
  sound/instruments/banjo/Cn6.ogg
  sound/instruments/banjo/Db3.ogg
  sound/instruments/banjo/Db4.ogg
  sound/instruments/banjo/Db5.ogg
  sound/instruments/banjo/Db6.ogg
  sound/instruments/banjo/Dn3.ogg
  sound/instruments/banjo/Dn4.ogg
  sound/instruments/banjo/Dn5.ogg
  sound/instruments/banjo/Dn6.ogg
  sound/instruments/banjo/Eb3.ogg
  sound/instruments/banjo/Eb4.ogg
  sound/instruments/banjo/Eb5.ogg
  sound/instruments/banjo/En3.ogg
  sound/instruments/banjo/En4.ogg
  sound/instruments/banjo/En5.ogg
  sound/instruments/banjo/Fn3.ogg
  sound/instruments/banjo/Fn4.ogg
  sound/instruments/banjo/Fn5.ogg
  sound/instruments/banjo/Gb3.ogg
  sound/instruments/banjo/Gb4.ogg
  sound/instruments/banjo/Gb5.ogg
  sound/instruments/banjo/Gn3.ogg
  sound/instruments/banjo/Gn4.ogg
  sound/instruments/banjo/Gn5.ogg
  sound/weapons/banjoslap.ogg
Labels: Feature, Port, Sound, Sprites

#745 [Port] Makes the BSA more stylish
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/station_goals/bsa.dm
  icons/effects/beam.dmi
  icons/effects/beam_splash.dmi
Labels: Port, Sprites

#746 Ports improved char customization options from TG
  code/game/objects/structures/dresser.dm
  code/modules/admin/create_mob.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/species.dm
  icons/mob/underwear.dmi
Labels: Feature, Port, Removal, Sprites, Tweak

#780 [PORT] Updating ratvarian computer sprites.
  code/game/machinery/computer/_computer.dm
  icons/obj/computer.dmi
Labels: Port, Sprites

#800 ID Painting Port
  code/game/machinery/PDApainter.dm
  code/game/machinery/aug_manipulator.dm
  icons/obj/pda.dmi
  icons/obj/robotics.dmi
Labels: Feature, Fix, Port, Sprites, Tweak

#815 [PORT] Some ghost improvements (#47700)
  code/datums/mind.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/mob.dm
Labels: Feature, Fix

#813 Color manipulator fix (PDA/ID icons)
  code/game/machinery/PDApainter.dm
Labels: Feature, Fix

#819 Random resprites before the great Ike port.
  code/modules/projectiles/guns/energy/special.dm
  icons/mob/aibots.dmi
  icons/mob/hands.dmi
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/obj/clothing/gloves.dmi
  icons/turf/walls/reinforced_wall.dmi
  icons/turf/walls/wall.dmi
Labels: Sprites

#818 Adds minimum pop requirements for Power Sink and Sleeping Carp.
  code/modules/uplink/uplink_items.dm
Labels: Balance/Rebalance, Vote Passed

#816 Fixes global server bans and adds new config options
  code/controllers/configuration/entries/general.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/metacoin/metacoin.dm
  config/config.txt
Labels: Config Update, Fix, THIS IS VERY IMPORTANT

#811 [PORT] Medborg Crew Monitor Upgrade (#46598)
  code/datums/action.dm
  code/game/objects/items/robot/robot_upgrades.dm
Labels: Feature, Needs Vote, Port

#766 Reduces riot suit slowdown from 50% to 20%
  code/modules/clothing/suits/armor.dm
Labels: Balance/Rebalance, Port, Vote Passed

#810 [PORT] Adds Purified Soulstones and Constructs #44036
  code/game/objects/items/storage/book.dm
  code/game/objects/items/weaponry.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/antagonists/wizard/equipment/soulstone.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/spells/spell_types/construct_spells.dm
  icons/mob/mob.dmi
  icons/obj/wizard.dmi
Labels: Feature, Port, Removal, Sprites, Vote Passed

#814 [PORT] Grenade fixes from /TG/, Beaker Panel
  beestation.dme
  code/__DEFINES/misc.dm
  code/datums/wires/explosive.dm
  code/game/objects/effects/proximity.dm
  code/game/objects/items/grenades/chem_grenade.dm
  code/game/objects/items/plushes.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/beakerpanel.dm
  code/modules/assembly/health.dm
  code/modules/atmospherics/machinery/portable/canister.dm
Labels: Administration, Port, Refactor

#808 Ports PDA Message Server can be constructed (#43961)
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/__DEFINES/radio.dm
  code/game/machinery/requests_console.dm
  code/game/machinery/telecomms/computers/message.dm
  code/game/machinery/telecomms/machines/bus.dm
  code/game/machinery/telecomms/machines/hub.dm
  code/game/machinery/telecomms/machines/message_server.dm
  code/game/machinery/telecomms/telecomunications.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/mining/machine_redemption.dm
  code/modules/research/designs/telecomms_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/obj/machines/telecomms.dmi
Labels: Feature, Map Edit, Port, Sprites, Tweak

#827 Fixes the OOC mute HTML
  code/modules/admin/admin.dm
Labels: Administration

#833 [PORT] crafting fix (#47730)
  code/datums/components/crafting/crafting.dm
  tgui-next/packages/tgui/interfaces/PersonalCrafting.js
Labels: Fix, UI

#786 Tweak: Shuffled the Map Vote List
  code/controllers/subsystem/vote.dm
Labels: Tweak, Vote Passed

#739 Baton Change, Heads get batons back
  code/__DEFINES/traits.dm
  code/game/objects/items/melee/misc.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/research_director.dm
Labels: Balance/Rebalance, Feature, Needs Vote, Port

#836 Adds random parallax layers (#47054)
  code/_onclick/hud/parallax.dm
  code/controllers/subsystem/parallax.dm
  icons/effects/parallax.dmi
Labels: Feature, Sprites

#822 [PORT] BoH bombing rework II (#45174)
  _maps/map_files/generic/CentCom.dmm
  beestation.dme
  code/__DEFINES/admin.dm
  code/datums/components/stationloving.dm
  code/datums/components/storage/concrete/bag_of_holding.dm
  code/game/area/areas/centcom.dm
  code/game/objects/structures/ladders.dm
  code/game/turfs/simulated/chasm.dm
  code/modules/admin/topic.dm
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
  code/modules/power/singularity/boh_tear.dm
  icons/effects/96x96.dmi
  icons/turf/floors/magic_chasm.dmi
Labels: Map Edit, Port, Sprites, Tweak

#832 [PORT] Clothing additions and fixes
  code/modules/clothing/head/misc.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_defense.dm
  code/modules/vending/autodrobe.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, Fix, Sprites

#829 [PORT] Finishing tgui-next cards
  code/datums/components/uplink.dm
  code/datums/spawners_menu.dm
  code/game/machinery/computer/station_alert.dm
  code/game/objects/items/tanks/tanks.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/antagonists/swarmer/swarmer.dm
  code/modules/awaymissions/corpse.dm
  code/modules/awaymissions/mission_code/snowdin.dm
  code/modules/modular_computers/computers/item/computer_ui.dm
  code/modules/modular_computers/file_system/programs/ntdownloader.dm
  code/modules/modular_computers/file_system/programs/powermonitor.dm
  code/modules/modular_computers/file_system/programs/sm_monitor.dm
  code/modules/power/monitor.dm
  code/modules/power/turbine.dm
  code/modules/ruins/lavaland_ruin_code.dm
  code/modules/tgui/tgui.dm
  code/modules/uplink/uplink_items.dm
  tgui-next/.eslintrc.yml
  tgui-next/README.md
  tgui-next/packages/tgui/components/Box.js
  tgui-next/packages/tgui/components/Chart.js
  tgui-next/packages/tgui/drag.js
  tgui-next/packages/tgui/hotkeys.js
  tgui-next/packages/tgui/interfaces/DnaVault.js
  tgui-next/packages/tgui/interfaces/EngravedMessage.js
  tgui-next/packages/tgui/interfaces/Holodeck.js
  tgui-next/packages/tgui/interfaces/Mint.js
  tgui-next/packages/tgui/interfaces/NtosMain.js
  tgui-next/packages/tgui/interfaces/NtosNetDownloader.js
  tgui-next/packages/tgui/interfaces/NtosSupermatterMonitor.js
  tgui-next/packages/tgui/interfaces/NtosWrapper.js
  tgui-next/packages/tgui/interfaces/PortableGenerator.js
  tgui-next/packages/tgui/interfaces/Smes.js
  tgui-next/packages/tgui/interfaces/SpaceHeater.js
  tgui-next/packages/tgui/interfaces/SpawnersMenu.js
  tgui-next/packages/tgui/interfaces/StationAlertConsole.js
  tgui-next/packages/tgui/interfaces/Tank.js
  tgui-next/packages/tgui/interfaces/TurbineComputer.js
  tgui-next/packages/tgui/interfaces/Uplink.js
  tgui-next/packages/tgui/interfaces/VaultController.js
  tgui-next/packages/tgui/layout.js
  tgui-next/packages/tgui/public/tgui-main.html
  tgui-next/packages/tgui/public/tgui.bundle.css
  tgui-next/packages/tgui/public/tgui.bundle.js
  tgui-next/packages/tgui/routes.js
  tgui-next/packages/tgui/styles/atomic/display.scss
  tgui-next/packages/tgui/styles/atomic/margin.scss
  tgui-next/packages/tgui/styles/atomic/position.scss
  tgui-next/packages/tgui/styles/atomic/text.scss
  tgui-next/packages/tgui/styles/components/Layout.scss
  tgui-next/packages/tgui/styles/components/ProgressBar.scss
  tgui-next/packages/tgui/styles/components/Tabs.scss
  tgui-next/packages/tgui/styles/main.scss
  tgui-next/packages/tgui/styles/themes/ntos.scss
  tgui-next/packages/tgui/styles/themes/syndicate.scss
Labels: Feature, Fix, Tweak, UI

#812 Box Piping followup PR
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Fix, Map Edit

#830 [PORT] [READY] Syndicate Contracts
  beestation.dme
  code/__DEFINES/antagonists.dm
  code/__HELPERS/text.dm
  code/game/gamemodes/objective.dm
  code/game/objects/items/melee/misc.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/antagonists/traitor/syndicate_contract.dm
  code/modules/cargo/supplypod.dm
  code/modules/clothing/spacesuits/syndi.dm
  code/modules/modular_computers/computers/item/tablet.dm
  code/modules/modular_computers/computers/item/tablet_presets.dm
  code/modules/modular_computers/file_system/programs/antagonist/contract_uplink.dm
  code/modules/modular_computers/hardware/hard_drive.dm
  code/modules/uplink/uplink_items.dm
  icons/mob/head.dmi
  icons/mob/inhands/weapons/melee_lefthand.dmi
  icons/mob/inhands/weapons/melee_righthand.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/items_and_weapons.dmi
  sound/effects/confirmdropoff.ogg
  sound/effects/contractorbatonhit.ogg
  sound/effects/contractstartup.ogg
  sound/effects/podwoosh.ogg
  sound/machines/uplinkerror.ogg
  sound/weapons/contractorbatonextend.ogg
  tgui/assets/tgui.js
  tgui/src/interfaces/synd_contract.ract
Labels: Feature, Needs Review, Sound, Sprites, UI

#837 Adds original "Endless Space" track as title0.ogg #47904
  sound/ambience/license.txt
  sound/ambience/title0.ogg
Labels: Sound

#742 [Port] Reworks Durand abilities, Adds proyectile components from TG
  code/__DEFINES/components.dm
  code/__DEFINES/is_helpers.dm
  code/game/machinery/porta_turret/portable_turret.dm
  code/game/mecha/combat/durand.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_actions.dm
  code/game/mecha/mecha_defense.dm
  code/game/mecha/mecha_topic.dm
  code/game/objects/items/robot/robot_items.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/mecha_pilot.dm
  code/modules/power/singularity/emitter.dm
  code/modules/projectiles/ammunition/_firing.dm
  code/modules/projectiles/ammunition/caseless/_caseless.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/dueling.dm
  code/modules/projectiles/projectile.dm
  icons/mecha/durand_shield.dmi
  sound/mecha/mech_shield_deflect.ogg
  sound/mecha/mech_shield_drop.ogg
  sound/mecha/mech_shield_raise.ogg
Labels: Feature, Port, Sound, Sprites, Tweak, Vote Passed

#834 [PORT] Action button swapping (#44658)
  code/_onclick/hud/action_button.dm
  code/_onclick/hud/movable_screen_objects.dm
Labels: Feature

#840 Saving/loading custom outfits. (#44183)
  beestation.dme
  code/datums/outfit.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/outfits.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/clothing/outfits/vv_outfit.dm
Labels: Administration

#762 [PORT] RCD ore silo link
  code/__DEFINES/construction.dm
  code/game/objects/items/RCD.dm
  code/modules/research/designs/tool_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature, Port

#841 [BOUNTY] New help emotes
  code/modules/mob/living/carbon/carbon_defense.dm
Labels: Feature

#842 Telescopic batons no longer do damage
  code/game/objects/items/melee/misc.dm
Labels: Tweak

#843 Nerfs contractor baton to 10 damage
  code/game/objects/items/melee/misc.dm
Labels: Tweak

#846 Thrown objects phase through thrower #44208
  code/controllers/subsystem/throwing.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/mob/living/living_movement.dm
Labels: Fix

#839 [PORT] [READY] Contractor Hub #45117
  beestation.dme
  code/__DEFINES/antagonists.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/game.dm
  code/__HELPERS/names.dm
  code/__HELPERS/roundend.dm
  code/_globalvars/lists/poll_ignore.dm
  code/controllers/subsystem/ticker.dm
  code/datums/browser.dm
  code/datums/mind.dm
  code/game/gamemodes/objective.dm
  code/game/objects/items/melee/misc.dm
  code/game/objects/items/pinpointer.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/antagonists/_common/antag_team.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/antagonists/traitor/equipment/contractor.dm
  code/modules/antagonists/traitor/syndicate_contract.dm
  code/modules/clothing/spacesuits/syndi.dm
  code/modules/events/grid_check.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/carbon/say.dm
  code/modules/modular_computers/computers/item/tablet.dm
  code/modules/modular_computers/computers/item/tablet_presets.dm
  code/modules/modular_computers/file_system/programs/antagonist/contract_uplink.dm
  code/modules/ninja/suit/n_suit_verbs/energy_net_nets.dm
  html/browser/roundend.css
  icons/mob/head.dmi
  icons/mob/inhands/weapons/melee_righthand.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/contractor_tablet.dmi
  sound/machines/uplinkpurchase.ogg
  tgui/assets/tgui.js
  tgui/src/interfaces/synd_contract.ract
Labels: Feature, Needs Review, Sound, Sprites, Tweak, UI, Vote Passed

#847 Fixes BSA target selection (#47477)
  tgui-next/packages/tgui/interfaces/BluespaceArtillery.js
  tgui-next/packages/tgui/public/tgui.bundle.js
Labels: Fix, UI

#844 Adds "Never for this round" to a few more ghost rolls. #44197
  code/_globalvars/lists/poll_ignore.dm
  code/datums/brain_damage/imaginary_friend.dm
  code/datums/brain_damage/split_personality.dm
  code/game/machinery/exp_cloner.dm
  code/game/objects/effects/anomalies.dm
  code/modules/antagonists/wizard/equipment/soulstone.dm
Labels: Feature

#831 More xeno toxins
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
Labels: Feature, Vote Passed

#807 [PORT] Adds Snow Golems and improved cabin away mission
  _maps/RandomZLevels/Cabin.dmm
  _maps/RandomZLevels/SnowCabin.dmm
  beestation.dme
  code/game/objects/structures/statues.dm
  code/modules/antagonists/abductor/ice_abductor.dm
  code/modules/awaymissions/mission_code/Cabin.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/ruins/lavaland_ruin_code.dm
  config/awaymissionconfig.txt
  icons/effects/freeze.dmi
  icons/mob/human_parts.dmi
  icons/obj/statue.dmi
Labels: Config Update, Feature, Map Edit, Port, Removal, Sprites, Vote Passed

#778 [PORT] Randomized Lavaland Atmos
  beestation.dme
  code/__DEFINES/atmospherics.dm
  code/controllers/subsystem/air.dm
  code/datums/atmosphere/_atmosphere.dm
  code/datums/atmosphere/planetary.dm
  code/modules/atmospherics/gasmixtures/gas_mixture.dm
  code/modules/hydroponics/grown/towercap.dm
Labels: Feature, Port, Vote Passed

#850 [PORT] Fix the newline problem in editorconfig
  .editorconfig
Labels: Feature

#852 Agent card automatically assigns your account number on first time use + change it anytime (#45032)
  code/game/objects/items/cards_ids.dm
  code/modules/antagonists/traitor/syndicate_contract.dm
Labels: Tweak

#857 Reorders the items and weapons dmi. #45128
  code/game/objects/items/charter.dm
  code/game/objects/items/defib.dm
  code/game/objects/items/holy_weapons.dm
  code/game/objects/items/melee/energy.dm
  code/game/objects/items/melee/misc.dm
  code/game/objects/items/religion.dm
  code/game/objects/items/shields.dm
  code/game/objects/items/twohanded.dm
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/antagonists/changeling/powers/tiny_prick.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/awaymissions/capture_the_flag.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  icons/obj/banner.dmi
  icons/obj/changeling_items.dmi
  icons/obj/defib.dmi
  icons/obj/items_and_weapons.dmi
  icons/obj/shields.dmi
  icons/obj/transforming_energy.dmi
Labels: Removal, Sprites

#860 [PORT] G U L P
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm
Labels: Fix

#862 [PORT] Button linkage fix (#48022)
  code/modules/holodeck/area_copy.dm
Labels: Fix

#856 IC filter port and followups
  code/__DEFINES/say.dm
  code/__HELPERS/text.dm
  code/_globalvars/lists/names.dm
  code/controllers/configuration/configuration.dm
  code/controllers/subsystem/pai.dm
  code/datums/components/spooky.dm
  code/game/mecha/mecha_topic.dm
  code/game/objects/items/AI_modules.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/holy_weapons.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/game/objects/structures/mirror.dm
  code/modules/antagonists/changeling/powers/mimic_voice.dm
  code/modules/antagonists/cult/cult_comms.dm
  code/modules/antagonists/disease/disease_mob.dm
  code/modules/antagonists/wizard/wizard.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/simple_animal/bot/construction.dm
  code/modules/reagents/chemistry/machinery/pandemic.dm
  code/modules/research/xenobiology/crossbreeding/stabilized.dm
  code/modules/research/xenobiology/xenobiology.dm
  config/in_character_filter.txt
Labels: Config Update, Feature

#870 [PORT] Adds a verb to force recreate the chat object #979
  code/modules/client/verbs/ooc.dm
Labels: Feature

#868 Adds animations to RCD construction
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/RCD.dm
  icons/effects/effects_rcd.dmi
Labels: Sprites

#865 Fixes IC filter and adds OOC filter
  code/__DEFINES/say.dm
  code/_globalvars/lists/names.dm
  code/controllers/configuration/configuration.dm
  code/modules/client/verbs/looc.dm
  code/modules/client/verbs/ooc.dm
  code/modules/goonchat/browserOutput.dm
  code/modules/goonchat/browserassets/js/browserOutput.js
  code/modules/mob/living/say.dm
  config/in_character_filter.txt
  config/ooc_filter.txt
Labels: Config Update

#869 Adds a new server restart option: regular restart with a custom delay time
  code/modules/admin/admin.dm
Labels: Administration
