Repository BeeStation/BeeStation-Hornet, pull requests merged in 2019-07, with the labels that each got.

#214 [S] fixes exploding pdas
  code/datums/components/uplink.dm
Labels: THIS IS VERY IMPORTANT, bug

#252 Adds spam prevention to clients
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
Labels: admin

#255 finally fixes the round id 0 problem
  code/controllers/subsystem/dbcore.dm
Labels: THIS IS VERY IMPORTANT, admin, bug, sql

#256 fixes a typo
  code/modules/jobs/job_types/chaplain.dm
Labels: petty af

#250 Plumbing Port
  beestation.dme
  code/__DEFINES/plumbing.dm
  code/controllers/subsystem/processing/fluids.dm
  code/datums/components/plumbing/plumbing.dm
  code/datums/ductnet.dm
  code/game/machinery/_machinery.dm
  code/game/objects/items/RPD.dm
  code/game/objects/objs.dm
  code/game/objects/structures/lavaland/geyser.dm
  code/game/turfs/simulated/floor/plating/asteroid.dm
  code/modules/client/asset_cache.dm
  code/modules/plumbing/ducts.dm
  code/modules/plumbing/plumbers/pumps.dm
  code/modules/reagents/reagent_dispenser.dm
  icons/obj/2x2.dmi
  icons/obj/lavaland/terrain.dmi
  icons/obj/objects.dmi
  icons/obj/plumbing/fluid_ducts.dmi
  icons/obj/plumbing/plumbers.dmi
  icons/obj/tools.dmi
  icons/obj/watercloset.dmi
  tgui/assets/tgui.css
  tgui/src/interfaces/rpd.ract
Labels: DONT MERGE

#253 uplink item rebalance
  code/modules/uplink/uplink_items.dm
Labels: balance

#261 OracleUI
  beestation.dme
  code/modules/oracle_ui/README.md
  code/modules/oracle_ui/assets.dm
  code/modules/oracle_ui/hookup_procs.dm
  code/modules/oracle_ui/oracle_ui.dm
  code/modules/oracle_ui/themed.dm
  code/modules/paperwork/paper.dm
  code/modules/recycling/disposal/bin.dm
  html/oracle_ui/content/disposal_bin/index.html
  html/oracle_ui/editor_tool.html
  html/oracle_ui/themes/nano/index.html
  html/oracle_ui/themes/nano/sui-nano-common.css
  html/oracle_ui/themes/nano/sui-nano-common.js
  html/oracle_ui/themes/nano/sui-nano-jquery.min.js
  html/oracle_ui/themes/paper/index.html
  html/oracle_ui/themes/paper/sui-paper-common.css
  html/oracle_ui/themes/paper/sui-paper-common.js
Labels: DONT MERGE, enhancement

#264 foolish attempt to stop atmos from getting out of hand
  code/__DEFINES/atmospherics.dm
Labels: DONT MERGE

#281 fixes dos exploits
  code/datums/mind.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
Labels: THIS IS VERY IMPORTANT

#282 Buffs paperwork
  code/modules/paperwork/paper.dm
Labels: enhancement
