Repository BeeStation/BeeStation-Hornet, pull requests merged in 2020-04, with the labels that each got.

#1450 PIZZA GANG
  code/__HELPERS/names.dm
  code/__HELPERS/priority_announce.dm
  code/modules/antagonists/gang/gang_datums.dm
Labels: Fix

#1454 Pizza Time
  icons/effects/parallax.dmi
Labels: Sprites

#1466 Pizza Gulag
  _maps/map_files/Mining/Lavaland.dmm
  code/modules/mining/laborcamp/laborstacker.dm
  code/modules/station_goals/bsa.dm
Labels: Feature, Map Edit

#1464 Added a retrowave titlescreen.
  config/title_screens/images/title6.dmi
Labels: Config Update, Sprites

#1471 Port of Fireman Carry Exploit Fix from TG#50398
  code/modules/mob/living/carbon/human/human.dm
Labels: Feature

#1458 Fixing RnD servers disappearing
  code/modules/research/server.dm
  icons/obj/machines/research.dmi
Labels: Fix, Sprites

#1387 Opens a new viro slot
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/datums/traits/negative.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/jobs/job_types/virologist.dm
  config/jobs.txt
Labels: Config Update, Feature, Map Edit, Tweak

#1422 Adds Unum deck
  beestation.dme
  code/game/objects/items/toys.dm
  code/modules/games/unum.dm
  code/modules/vending/games.dm
  icons/obj/toy.dmi
Labels: Feature, Sprites

#1451 Cooking Oil Recipe
  code/modules/reagents/chemistry/recipes/others.dm
Labels: Feature

#1456 Making mining circuits
  beestation.dme
  code/modules/integrated_electronics/subtypes/mining.dm
Labels: Feature

#1440 Stun baton rework
  code/game/objects/items/stunbaton.dm
  code/modules/surgery/bodyparts/bodyparts.dm
Labels: Tweak

#1431 [BOUNTY] Redoes the 1429: Adds more detailed ion law addition logging.
  code/modules/admin/verbs/randomverbs.dm
  code/modules/events/ion_storm.dm
  code/modules/paperwork/contract.dm
Labels: Administration

#1438 Ports Nooses to bee so you can hang people
  beestation.dme
  code/game/objects/noose.dm
  code/modules/power/cable.dm
  icons/obj/objects.dmi
  sound/effects/noose_idle.ogg
  sound/effects/noosed.ogg
Labels: Feature, Fix, Sound, Sprites

#1447 Getting robusted by the cat surgeon is a fate worse than death
  code/modules/mob/living/simple_animal/hostile/cat_butcher.dm
  code/modules/projectiles/projectile/bullets/dart_syringe.dm
  icons/mob/simple_human.dmi
Labels: Feature, Sprites

#1473 Ayyliens: Abductor Frequency Increase
  code/modules/antagonists/abductor/abductor.dm
  code/modules/events/abductor.dm
Labels: Feature, Tweak

#1457 Changing appearance of card hands
  code/game/objects/items/toys.dm
  icons/obj/toy.dmi
Labels: Sprites, Tweak

#1483 Adds Noose Attempted Hang logging.
  code/game/objects/noose.dm
Labels: Administration

#1460 Less HOPcurity
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/jobs/job_types/head_of_personnel.dm
Labels: Balance/Rebalance, Tweak

#1409 adds needlessly complex finger gun emote
  code/modules/mob/living/emote.dm
  code/modules/projectiles/ammunition/ballistic/revolver.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/boxes_magazines/internal/_cylinder.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/projectile/bullets/revolver.dm
Labels: Feature, ike approved™

#1489 Fixes a few noose things
  code/game/objects/noose.dm
Labels: Fix

#1488 Adds in an adminhud icon for survivalists (including the magic guys too)
  code/__DEFINES/atom_hud.dm
  code/datums/hud.dm
  code/modules/antagonists/survivalist/survivalist.dm
  icons/mob/hud.dmi
Labels: Administration, Sprites

#1493 Adds agent ID name randomizing and logging
  code/_globalvars/lists/names.dm
  code/game/objects/items/cards_ids.dm
Labels: Administration, Feature

#1492 Adds more clown synthesizer sounds
  code/game/objects/items/devices/sound_synth.dm
  sound/effects/audience-aww.ogg
  sound/effects/audience-boo.ogg
  sound/effects/audience-gasp.ogg
  sound/effects/audience-ooh.ogg
Labels: Feature, Sound

#1481 Flypeople Slight Tweak
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
Labels: Feature, Tweak

#1468 Virus spiked skin (Cornu Cutaneum)
  beestation.dme
  code/datums/diseases/advance/symptoms/spiked.dm
Labels: Needs Wiki Changes

#1443 Re-Adds Public Autolathes
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit

#1478 Adds a vaccinate all disease admin verb
  code/modules/admin/secrets.dm
Labels: Administration

#1368 [BOUNTY] Adds the blob spores symptom
  beestation.dme
  code/__DEFINES/antagonists.dm
  code/datums/diseases/advance/presets.dm
  code/datums/diseases/advance/symptoms/blobspores.dm
  code/datums/diseases/advance/symptoms/symptoms.dm
  code/modules/antagonists/blob/blob_mobs.dm
  code/modules/antagonists/blob/structures/factory.dm
  code/modules/antagonists/blob/structures/node.dm
  code/modules/antagonists/blob/structures/shield.dm
  code/modules/reagents/reagent_containers/bottle.dm
Labels: Feature, Fix, Needs Wiki Changes

#1496 [REPULL- QWERT IF YOU PUT THIS UP TO VOTE OR LET IT SIT A MONTH AGAIN I SWEAR] monkey gorilla leaders
  code/datums/diseases/transformation.dm
  code/modules/antagonists/monkey/monkey.dm
  code/modules/mob/living/simple_animal/hostile/gorilla/gorilla.dm
  code/modules/mob/transform_procs.dm
Labels: Balance/Rebalance, Feature, Fix, Tweak

#1495 [Bounty] Adds logging for anomaly explosions
  code/game/objects/effects/anomalies.dm
Labels: Administration

#1459 [BOUNTY] More logging
  code/datums/wires/explosive.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/flamethrower.dm
  code/game/objects/items/grenades/grenade.dm
  code/modules/atmospherics/machinery/portable/portable_atmospherics.dm
  code/modules/hydroponics/grown/tomato.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/power/apc.dm
Labels: Administration, Feature

#1499 Adds another funny round end..ogg
  sound/roundend/hullbreach.ogg
Labels: Sound

#1347 cool whip and baton changes
  code/game/objects/items/melee/misc.dm
Labels: Balance/Rebalance, Tweak

#1501 [REPULL] severity refactor, or, why i hate gitkraken
  code/__DEFINES/diseases.dm
  code/datums/diseases/_disease.dm
  code/datums/diseases/advance/advance.dm
  code/datums/diseases/advance/symptoms/beard.dm
  code/datums/diseases/advance/symptoms/beesymptom.dm
  code/datums/diseases/advance/symptoms/blobspores.dm
  code/datums/diseases/advance/symptoms/braindamage.dm
  code/datums/diseases/advance/symptoms/choking.dm
  code/datums/diseases/advance/symptoms/cockroach.dm
  code/datums/diseases/advance/symptoms/confusion.dm
  code/datums/diseases/advance/symptoms/cough.dm
  code/datums/diseases/advance/symptoms/deafness.dm
  code/datums/diseases/advance/symptoms/fever.dm
  code/datums/diseases/advance/symptoms/fire.dm
  code/datums/diseases/advance/symptoms/flesh_eating.dm
  code/datums/diseases/advance/symptoms/genetics.dm
  code/datums/diseases/advance/symptoms/hallucigen.dm
  code/datums/diseases/advance/symptoms/headache.dm
  code/datums/diseases/advance/symptoms/heal.dm
  code/datums/diseases/advance/symptoms/heartattack.dm
  code/datums/diseases/advance/symptoms/itching.dm
  code/datums/diseases/advance/symptoms/lubefeet.dm
  code/datums/diseases/advance/symptoms/narcolepsy.dm
  code/datums/diseases/advance/symptoms/necropolis.dm
  code/datums/diseases/advance/symptoms/oxygen.dm
  code/datums/diseases/advance/symptoms/pierrot.dm
  code/datums/diseases/advance/symptoms/radiation.dm
  code/datums/diseases/advance/symptoms/sensory.dm
  code/datums/diseases/advance/symptoms/shedding.dm
  code/datums/diseases/advance/symptoms/shivering.dm
  code/datums/diseases/advance/symptoms/skin.dm
  code/datums/diseases/advance/symptoms/sneeze.dm
  code/datums/diseases/advance/symptoms/spiked.dm
  code/datums/diseases/advance/symptoms/symptoms.dm
  code/datums/diseases/advance/symptoms/vision.dm
  code/datums/diseases/advance/symptoms/voice_change.dm
  code/datums/diseases/advance/symptoms/vomit.dm
  code/datums/diseases/advance/symptoms/weight.dm
  code/datums/diseases/advance/symptoms/wizarditis.dm
  code/game/data_huds.dm
  code/game/machinery/scan_gate.dm
  code/modules/antagonists/changeling/powers/panacea.dm
  code/modules/antagonists/disease/disease_disease.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  icons/mob/hud.dmi
Labels: Balance/Rebalance, Feature, Fix, Refactor, Sprites, Tweak

#1505 Adds spawn human verb (for admins)
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/randomverbs.dm
Labels: Administration, Feature

#1507 Removes funny words
  _maps/RandomZLevels/caves.dmm
  code/datums/mutations/speech.dm
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/hydroponics/hydroponics.dm
  html/archivedchangelog.html
  icons/obj/food/food.dmi
  strings/ion_laws.json
  strings/names/death_commando.txt
  strings/traumas.json
Labels: Map Edit, Removal, Sprites

#1506 Fixes some issues with the config
  config/Sage/config.txt
  config/config.txt
Labels: Config Update, Fix

#1398 Ship construction through the power of science!
  beestation.dme
  code/controllers/configuration/entries/game_options.dm
  code/game/area/areas/shuttles.dm
  code/game/machinery/shuttle/custom_shuttle.dm
  code/game/machinery/shuttle/shuttle_engine.dm
  code/game/machinery/shuttle/shuttle_heater.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/shuttle_creator.dm
  code/game/objects/items/shuttle_upgrades.dm
  code/modules/research/designs/comp_board_designs.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/designs/tool_designs.dm
  code/modules/research/machinery/circuit_imprinter.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/shuttle/custom_shuttle.dm
  code/modules/shuttle/shuttle.dm
  config/Sage/config.txt
  config/config.txt
  config/dbconfig.txt
  icons/obj/module.dmi
  icons/obj/tools.dmi
  icons/turf/shuttle.dmi
Labels: Config Update, Feature, Golden ⭐, Sound, Sprites, Vote Passed

#1503 Additions for Ethereals.
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
  code/modules/power/apc.dm
  code/modules/power/cell.dm
  code/modules/surgery/bodyparts/head.dm
Labels: Feature

#1517 Fixes the labour camp point claim console
  code/modules/mining/laborcamp/laborstacker.dm
Labels: Fix

#1498 Zesko's take on carp, AKA aggro grab nerf
  code/datums/martial/cqc.dm
  code/datums/martial/sleeping_carp.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/mob_movement.dm
Labels: Needs Vote, ike approved™

#1518 Fixes the cool and new surgeries not being able to be performed with advanced tools.
  code/modules/surgery/coronary_bypass.dm
  code/modules/surgery/healing.dm
  code/modules/surgery/lobectomy.dm
Labels: Fix

#1525 Adds Droppers to autolathe construction
  code/modules/research/designs/autolathe_designs.dm
Labels: Feature

#1529 Allows custom shuttles to land on some forms of plating, but not the …
  code/modules/shuttle/custom_shuttle.dm
Labels: Tweak

#1520 Change of chat colors (medical and service)
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/goonchat/browserassets/css/browserOutput_white.css
Labels: Tweak

#1531 [S] Patch for admins being able to view a system's file-tree
  code/__HELPERS/files.dm
  code/modules/admin/verbs/getlogs.dm
Labels: security

#1537 Fix rules links in config
  config/Sage/config.txt
  config/config.txt
Labels: Config Update

#1534 Fixes vanilla icecream
  code/modules/food_and_drinks/kitchen_machinery/icecream_vat.dm
Labels: Fix

#1535 Fixes self sustaining rainbow slime
  code/modules/research/xenobiology/crossbreeding/selfsustaining.dm
Labels: Fix

#1532 Swapped nukie implants order so you don't have to destroy your firearm auth to get a macrobomb
  code/game/gamemodes/nuclear/nuclear.dm
Labels: Tweak

#1527 Fixes contractor baton working like a police/telebaton
  _maps/RandomRuins/SpaceRuins/TheDerelict.dmm
  _maps/RandomZLevels/research.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/shuttles/ruin_pirate_cutter.dmm
  _maps/shuttles/whiteship_box.dmm
  code/__DEFINES/inventory.dm
  code/controllers/subsystem/traumas.dm
  code/game/objects/items/melee/misc.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/awaymissions/mission_code/snowdin.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/mining/abandoned_crates.dm
Labels: Fix, Map Edit

#1390 Cult nerfs and hearing protection refactor repull
  beestation.dme
  code/datums/components/earprotection.dm
  code/game/objects/items/devices/radio/headset.dm
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/ears/_ears.dm
  code/modules/clothing/head/helmet.dm
  code/modules/mob/living/carbon/carbon_defense.dm
Labels: Balance/Rebalance, Code Improvement, Fix, Refactor, Tweak

#1541 New ban option for DSAY
  code/modules/admin/sql_ban_system.dm
  code/modules/mob/say.dm
Labels: Administration

#1536 Removes stray pixel on durathread helmet
  icons/mob/head.dmi
Labels: Removal, Sprites

#1553 Adds support for defining preset tags for issues reported mid-game
  code/controllers/configuration/entries/general.dm
  config/Sage/config.txt
  config/config.txt
  interface/interface.dm
Labels: Code Improvement, Config Update

#1528 Makes toxin treatment kits not just boxes of charcoal
  code/game/objects/items/storage/firstaid.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/reagent_containers/syringes.dm
Labels: Tweak, Vote Passed

#1538 Updates the client warn & error versions in the config
  config/Sage/config.txt
  config/config.txt
Labels: Config Update

#1556 flash nerf i guess
  code/modules/antagonists/devil/true_devil/_true_devil.dm
  code/modules/assembly/flash.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/living_defense.dm
Labels: Balance/Rebalance

#1573 Revert "Increased reagent cap"
  code/modules/mob/living/carbon/carbon.dm
Labels: Revert, Tweak

#1574 fucky wucky
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/debug.dm
  code/modules/client/asset_cache.dm
  html/fuckywucky.png
  sound/misc/fuckywucky.ogg
Labels: Administration, Sound

#1560 [BOUNTY] Adds a mini-chem dispenser to botany
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
Labels: Feature, Map Edit

#1555 adds more botany spawn flags to box and pubby
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit

#1480 Arrivals Door Replacement + New Door Type
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/airlock_types.dm
  icons/obj/doors/airlocks/external/arrivals_external.dmi
Labels: Feature, Map Edit, Sprites, Tweak, Vote Passed

#1578 Revert "Remakes Cyanide"
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
Labels: Revert

#1579 fixes a few issues with the flash nerf
  code/modules/assembly/flash.dm
  code/modules/mob/living/silicon/silicon_defense.dm
Labels: Fix, Tweak

#1580 Flypeople nutrition changes
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
Labels: Fix, Vote Passed

#1576 replaces the normal sunglasses in the detectives office with a sechud
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Feature, Map Edit, Vote Passed

#1564 removes nometabolism from skeletons and zombies
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
Labels: Removal, Tweak, Vote Passed

#1595 Classic EMP grenades break lights
  code/game/objects/items/grenades/emgrenade.dm
Labels: Feature, Vote Passed

#1539 Changeling names
  code/modules/antagonists/changeling/changeling.dm
Labels: Tweak

#1533 Fixes energy chainsaws reverting to normal chainsaws when implanted
  code/game/objects/items/weaponry.dm
  code/modules/surgery/prosthetic_replacement.dm
Labels: Fix, Revert

#1597 Revert "Flypeople nutrition changes"
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
Labels: Revert

#1584 Flash rebalance / rework
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/machinery/flasher.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/antagonists/devil/true_devil/_true_devil.dm
  code/modules/antagonists/revolution/revolution.dm
  code/modules/assembly/flash.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/silicon_defense.dm
  code/modules/research/designs/mechfabricator_designs.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/bodyparts/robot_bodyparts.dm
  code/modules/vending/robotics.dm
  icons/obj/assemblies/new_assemblies.dmi
Labels: Balance/Rebalance, Feature, Map Edit, Removal, Sprites, Tweak, Vote Passed

#1586 Adds non-flashproof sunglasses to ClothesMate and replaces static maint sunglasses spawns with dynamic lootspawners
  _maps/RandomRooms/3x3/sk_rdm004_tanning.dmm
  _maps/RandomRuins/LavaRuins/lavaland_biodome_beach.dmm
  _maps/RandomRuins/SpaceRuins/spacehotel.dmm
  _maps/RandomRuins/SpaceRuins/vaporwave.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/generic/CentCom.dmm
  code/datums/components/crafting/tailoring.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/game/objects/structures/crates_lockers/closets/gimmick.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/antagonists/fugitive/fugitive_outfits.dm
  code/modules/awaymissions/corpse.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/jobs/job_types/bartender.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/quartermaster.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/vending/autodrobe.dm
  code/modules/vending/clothesmate.dm
  code/modules/vending/security.dm
  code/modules/vending/wardrobes.dm
Labels: Balance/Rebalance, Feature, Map Edit, Tweak, Vote Passed

#1598 Capital letters for gaseous decomposition
  code/modules/hydroponics/plant_genes.dm
Labels: Grammar and Formatting

#1602 Reverts contractor baton knockdown to cause item drop again
  code/game/objects/items/melee/misc.dm
Labels: Revert, Tweak, Vote Passed

#1300 Mirrors the stats of various helmets and exosuits that had mismatched stats
  code/modules/antagonists/cult/cult_items.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/suits/armor.dm
Labels: Balance/Rebalance, Fix, Tweak

#1585 Adds the explosive flashbulb (Requires flash rework)
  beestation.dme
  code/game/objects/items/devices/explosive_flashbulb.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature, Vote Passed

#1565 PubbyStation Engine Overhaul
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/__DEFINES/atmospherics.dm
  code/game/machinery/computer/atmos_control.dm
Labels: Feature, Map Edit, Removal, Tweak

#1603 Runescape style chat again but this time its legal
  beestation.dme
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/burgerchat.dm
  code/modules/mob/living/say.dm
  interface/skin.dmf
Labels: Feature

#1619 fixes maint lootdrops not having real sunglasses
  code/_globalvars/lists/maintenance_loot.dm
Labels: Feature

#1600 Gives atmos techs access to the Pubby Engine Room/engi protolathe
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit, Tweak

#1622 cat surgeon healing buff
  code/modules/mob/living/simple_animal/hostile/cat_butcher.dm
Labels: Balance/Rebalance

#1617 Security keycard auth
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/modules/jobs/job_types/brigphys.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/warden.dm
Labels: Feature, Map Edit

#1568 Adds Karate, a cheap martial art for traitors
  beestation.dme
  code/__DEFINES/melee.dm
  code/datums/martial/karate.dm
  code/game/objects/items/granters.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature

#1614 Lets you shove people into the trash (#48960)
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#1608 Fixes vehicles not being able to go down z-levels
  code/game/mecha/mecha.dm
  code/modules/vehicles/cars/car.dm
Labels: Fix

#1611 Fixes cyborg hyper fast charging
  code/game/objects/items/robot/robot_items.dm
Labels: Code Improvement, Fix

#1566 Adds lethal autoturrets to nuke operative uplink
  code/game/machinery/porta_turret/portable_turret.dm
  code/game/machinery/syndicatebeacon.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature, Work In Progress

#1628 No more subsystem initialization messages
  code/controllers/subsystem.dm
Labels: Removal

#1626 Departmental skirts
  code/_globalvars/lists/flavor_misc.dm
  code/datums/outfit.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/syndicate.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/under/color.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/clothing/under/syndicate.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/vending/autodrobe.dm
  code/modules/vending/clothesmate.dm
  code/modules/vending/wardrobes.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/hats_deconflict.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/clothing/uniforms_deconflict.dmi
Labels: Feature, Sprites

#1633 runechat cleanup and small tweak
  code/modules/mob/living/burgerchat.dm
Labels: Code Improvement, Tweak

#1621 You can spraypaint eye coverings to make them flashproof
  code/__DEFINES/traits.dm
  code/game/objects/items/clown_items.dm
  code/game/objects/items/crayons.dm
  code/modules/detectivework/footprints_and_rag.dm
Labels: Feature

#1607 Adds request consoles to every department
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit

#1620 Fixes Aspera tea containing no reagents
  code/modules/hydroponics/grown/tea_coffee.dm
Labels: Feature, Fix

#1636 Revert "merge conflicts"
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/atmospheric_technician.dm
  code/modules/jobs/job_types/bartender.dm
  code/modules/jobs/job_types/botanist.dm
  code/modules/jobs/job_types/brigphys.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/cargo_technician.dm
  code/modules/jobs/job_types/chaplain.dm
  code/modules/jobs/job_types/chemist.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/clown.dm
  code/modules/jobs/job_types/cook.dm
  code/modules/jobs/job_types/curator.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/emt.dm
  code/modules/jobs/job_types/geneticist.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/janitor.dm
  code/modules/jobs/job_types/lawyer.dm
  code/modules/jobs/job_types/medical_doctor.dm
  code/modules/jobs/job_types/mime.dm
  code/modules/jobs/job_types/quartermaster.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/jobs/job_types/scientist.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/shaft_miner.dm
  code/modules/jobs/job_types/station_engineer.dm
  code/modules/jobs/job_types/virologist.dm
  code/modules/jobs/job_types/warden.dm
  code/modules/mob/living/burgerchat.dm
Labels: Revert

#1637 Avendors assemble - Fixes YouTool and Boda Vending machines
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/cargo/packs.dm
  code/modules/vending/sovietsoda.dm
  code/modules/vending/youtool.dm
Labels: Code Improvement, Feature, Fix

#1657 Revert "Departmental skirts"
  code/_globalvars/lists/flavor_misc.dm
  code/datums/outfit.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/syndicate.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/under/color.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/clothing/under/syndicate.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/vending/autodrobe.dm
  code/modules/vending/clothesmate.dm
  code/modules/vending/wardrobes.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/hats_deconflict.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/clothing/uniforms_deconflict.dmi
Labels: Revert, Sprites

#1645 Fix brain damage not giving traumas (#46582)
  code/modules/mob/living/brain/brain_item.dm
Labels: Fix

#1641 Makes Concentrated BZ orderable from cargo and fixes a bug with it not causing enough gasping.
  code/modules/cargo/packs.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/reagent_containers/bottle.dm
Labels: Feature, Fix

#1610 More Crates And Some Changes To Other Crates
  code/game/objects/items/stacks/bscrystal.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/modules/cargo/packs.dm
Labels: Feature, Tweak

#1561 [READ THIS PR] Changeling balance changes
  beestation.dme
  code/datums/status_effects/buffs.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/objective.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/changeling/powers/absorb.dm
  code/modules/antagonists/changeling/powers/augmented_eyesight.dm
  code/modules/antagonists/changeling/powers/chameleon_skin.dm
  code/modules/antagonists/changeling/powers/fakedeath.dm
  code/modules/antagonists/changeling/powers/fleshmend.dm
  code/modules/antagonists/changeling/powers/headcrab.dm
  code/modules/antagonists/changeling/powers/hivemind.dm
  code/modules/antagonists/changeling/powers/lesserform.dm
  code/modules/antagonists/changeling/powers/linglink.dm
  code/modules/antagonists/changeling/powers/mimic_voice.dm
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/antagonists/changeling/powers/panacea.dm
  code/modules/antagonists/changeling/powers/pheromone_receptors.dm
  code/modules/antagonists/changeling/powers/regenerate.dm
  code/modules/antagonists/changeling/powers/shriek.dm
  code/modules/antagonists/changeling/powers/spiders.dm
  code/modules/antagonists/changeling/powers/teratoma.dm
  code/modules/antagonists/changeling/powers/tiny_prick.dm
  code/modules/mining/equipment/survival_pod.dm
  code/modules/mob/living/simple_animal/hostile/headcrab.dm
  icons/mob/actions/actions_changeling.dmi
  icons/mob/animal.dmi
Labels: Balance/Rebalance, Removal, Sprites, Tweak, Vote Passed

#1589 Adds Deputies and increases security playtime requirements
  beestation.dme
  code/__DEFINES/jobs.dm
  code/game/gamemodes/overthrow/overthrow.dm
  code/game/machinery/computer/card.dm
  code/game/machinery/computer/crew.dm
  code/game/objects/items/melee/misc.dm
  code/game/objects/items/religion.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/brigphys.dm
  code/modules/jobs/job_types/deputy.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/warden.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/modular_computers/file_system/programs/card.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/projectile/energy/misc.dm
  code/modules/vending/security.dm
  config/jobs.txt
  icons/mob/head.dmi
  icons/mob/hud.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/hats_deconflict.dmi
Labels: Config Update, Feature, Sprites, Tweak

#1653 new traitor bartender drink: the threequal
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  icons/obj/drinks.dmi
Labels: Sprites

#1666 Revert "Safety Moth(TM) Posters from your friends at Nanotrasen! [Spritework Edition]"
  code/game/objects/effects/contraband.dm
  icons/obj/contraband.dmi
Labels: Revert, Sprites

#1662 Map QoL Tweaks: All 4
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit, Tweak

#1512 Adds in support for additional roundstart special roles
  beestation.dme
  code/__DEFINES/antagonists.dm
  code/__DEFINES/role_preferences.dm
  code/__HELPERS/mobs.dm
  code/datums/mind.dm
  code/datums/mood_events/generic_positive_events.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/gangs/gangtool.dm
  code/game/gamemodes/objective.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/antagonists/roundstart_special/special_antagonist.dm
  code/modules/antagonists/roundstart_special/undercover/undercover.dm
  code/modules/events/special_antag_event.dm
  code/modules/mob/dead/new_player/new_player.dm
Labels: Code Improvement, Needs Testmerge

#1682 Medical staff spawn with a unique first-aid kit
  code/game/objects/items/storage/firstaid.dm
  code/modules/jobs/job_types/brigphys.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/emt.dm
  code/modules/jobs/job_types/medical_doctor.dm
  icons/mob/inhands/equipment/medical_lefthand.dmi
  icons/obj/storage.dmi
Labels: Feature, Sprites, Vote Passed

#1667 Updated Sage map pop requirements (mainly less Pubby)
  config/Sage/maps.txt
Labels: Config Update, Tweak, Vote Passed

#1686 Augmentation surgery now takes 2 less steps
  code/modules/surgery/limb_augmentation.dm
Labels: Balance/Rebalance, Vote Passed

#1684 Differentiates mech punches between durand and gygax + removes auto punch from leg acurator
  code/game/mecha/combat/gygax.dm
  code/game/mecha/mecha_actions.dm
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Balance/Rebalance, Needs Vote, Removal
