Repository BeeStation/BeeStation-Hornet, pull requests merged in 2020-06, with the labels that each got.

#1738 Copper Golems, Golem Code Fixes
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/ruins/lavaland_ruin_code.dm
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Config Update, Feature, Needs Wiki Changes

#1894 Replaces Qwert with Ike in the admins.txt files
  config/Sage/admins.txt
  config/admins.txt
Labels: Administration, config

#1895 Update compile_changelogs.yml
  .github/workflows/compile_changelogs.yml
  .github/workflows/make_changelogs.yml
Labels: Tweak

#1896 Don't generate Cls for commits with the skip tag
  .github/workflows/make_changelogs.yml
Labels: Tweak

#1897 Don't you love conflicting documentation?
  .github/workflows/make_changelogs.yml
Labels: Tweak

#1893 Issue#1892 fix
  code/modules/hydroponics/grown/tobacco.dm
  icons/obj/hydroponics/harvest.dmi
Labels: Feature, Sprites

#1899 Removes Qwerty as a CODEOWNER
  .github/CODEOWNERS
Labels: GitHub

#1890 Two new clown ERTs
  code/datums/ert.dm
  code/game/objects/items/pneumaticCannon.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/antagonists/ert/ert.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/jobs/access.dm
  code/modules/reagents/reagent_containers/spray.dm
Labels: Code Improvement, Feature

#1829 Optimizes Life()
  code/modules/mob/living/carbon/alien/life.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/life.dm
Labels: Code Improvement

#1901 Reduces autotransfer vote time to 90 minutes
  config/Sage/config.txt
  config/config.txt
Labels: Tweak

#1900 Fix custom supply pod sound effects
  code/modules/cargo/centcom_podlauncher.dm
Labels: Administration

#1889 Fixes the preserve virus and synthmeat chemical recipe conflict
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/reagent_containers/bottle.dm
Labels: Feature, Fix, Refactor, Tweak

#1782 Adds objective logging
  code/__HELPERS/_logging.dm
  code/_globalvars/logging.dm
  code/controllers/configuration/entries/general.dm
  code/datums/mind.dm
  code/game/gamemodes/devil/devil agent/devil_agent.dm
  code/game/gamemodes/devil/game_mode.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/world.dm
  code/modules/admin/secrets.dm
  code/modules/admin/team_panel.dm
  code/modules/admin/verbs/one_click_antag.dm
  code/modules/antagonists/abductor/abductor.dm
  code/modules/antagonists/blob/blob.dm
  code/modules/antagonists/blood_contract/blood_contract.dm
  code/modules/antagonists/brainwashing/brainwashing.dm
  code/modules/antagonists/brother/brother.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/creep/creep.dm
  code/modules/antagonists/cult/cult.dm
  code/modules/antagonists/devil/imp/imp.dm
  code/modules/antagonists/devil/sintouched/sintouched.dm
  code/modules/antagonists/disease/disease_datum.dm
  code/modules/antagonists/fugitive/fugitive.dm
  code/modules/antagonists/fugitive/hunter.dm
  code/modules/antagonists/greentext/greentext.dm
  code/modules/antagonists/highlander/highlander.dm
  code/modules/antagonists/hivemind/hivemind.dm
  code/modules/antagonists/hivemind/vessel.dm
  code/modules/antagonists/monkey/monkey.dm
  code/modules/antagonists/ninja/ninja.dm
  code/modules/antagonists/nukeop/nukeop.dm
  code/modules/antagonists/overthrow/overthrow.dm
  code/modules/antagonists/revenant/revenant_antag.dm
  code/modules/antagonists/revolution/revolution.dm
  code/modules/antagonists/roundstart_special/undercover/undercover.dm
  code/modules/antagonists/santa/santa.dm
  code/modules/antagonists/slaughter/slaughter_antag.dm
  code/modules/antagonists/space_dragon/space_dragon.dm
  code/modules/antagonists/survivalist/survivalist.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/antagonists/valentines/heartbreaker.dm
  code/modules/antagonists/valentines/valentine.dm
  code/modules/antagonists/wishgranter/wishgranter.dm
  code/modules/antagonists/wizard/wizard.dm
  code/modules/awaymissions/corpse.dm
  code/modules/guardian/guardian.dm
  code/modules/ruins/objects_and_mobs/ash_walker_den.dm
  code/modules/spells/spell_types/hivemind.dm
  config/Sage/config.txt
  config/config.txt
Labels: admin, config

#1905 Shuttle construction kit with the power of cargo
  code/modules/cargo/packs.dm
Labels: Feature

#1906 Drying racks no longer use power
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
Labels: Tweak

#1911 Message for ghosts upon creation of AIs or law changes to AIs/Unsynced cyborgs
  code/__DEFINES/misc.dm
  code/__DEFINES/preferences.dm
  code/__HELPERS/mobs.dm
  code/game/objects/items/AI_modules.dm
  code/game/objects/structures/ai_core.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_toggles.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/laws.dm
  code/modules/mob/living/silicon/robot/laws.dm
  code/modules/mob/living/silicon/silicon.dm
Labels: Feature

#1902 Maint airlocks
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature

#1913 Delta cargo fix
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Fix, Removal

#1910 Nerfs legion core transformation disease
  code/datums/diseases/transformation.dm
Labels: Balance/Rebalance

#1907 fixes 3 runtimes
  code/controllers/subsystem/job.dm
  code/game/objects/items/grenades/flashbang.dm
  code/modules/mob/living/carbon/human/species_types/abductors.dm
Labels: Fix

#1916 [Fix] fix beam rifles
  code/modules/projectiles/gun.dm
Labels: Fix

#1920 [fix] MultiZ openspace turfs will no longer crash the game.
  code/modules/mapping/space_management/multiz_helpers.dm
Labels: Fix

#1922 small pressure fix
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Fix, Removal

#1928 Fastmos QoL
  code/game/machinery/airlock_cycle_control.dm
  code/modules/atmospherics/environmental/LINDA_turf_tile.dm
Labels: Tweak

#1929 Internals lag fix
  code/modules/mob/mob.dm
Labels: Fix

#1904 Revamped shuttle creation through the power of science!
  beestation.dme
  code/modules/shuttle/shuttle_creation/shuttle_creator.dm
  code/modules/shuttle/shuttle_creation/shuttle_creator_actions.dm
  code/modules/shuttle/shuttle_creation/shuttle_creator_console.dm
  code/modules/shuttle/shuttle_creation/shuttle_creator_eye.dm
  code/modules/shuttle/shuttle_creation/shuttle_creator_overlay.dm
  code/modules/shuttle/shuttle_creation/shuttle_upgrades.dm
  icons/mob/actions/actions_shuttle.dmi
Labels: Refactor

#1931 Emergency shuttles now with actual air
  _maps/shuttles/emergency_arena.dmm
  _maps/shuttles/emergency_asteroid.dmm
  _maps/shuttles/emergency_backup.dmm
  _maps/shuttles/emergency_bar.dmm
  _maps/shuttles/emergency_birdboat.dmm
  _maps/shuttles/emergency_box.dmm
  _maps/shuttles/emergency_cere.dmm
  _maps/shuttles/emergency_clown.dmm
  _maps/shuttles/emergency_construction.dmm
  _maps/shuttles/emergency_cramped.dmm
  _maps/shuttles/emergency_delta.dmm
  _maps/shuttles/emergency_discoinferno.dmm
  _maps/shuttles/emergency_donut.dmm
  _maps/shuttles/emergency_goon.dmm
  _maps/shuttles/emergency_kilo.dmm
  _maps/shuttles/emergency_meta.dmm
  _maps/shuttles/emergency_mini.dmm
  _maps/shuttles/emergency_omega.dmm
  _maps/shuttles/emergency_pod.dmm
  _maps/shuttles/emergency_pubby.dmm
  _maps/shuttles/emergency_raven.dmm
  _maps/shuttles/emergency_russiafightpit.dmm
  _maps/shuttles/emergency_scrapheap.dmm
  _maps/shuttles/emergency_supermatter.dmm
  _maps/shuttles/emergency_wabbajack.dmm
  _maps/shuttles/emergency_zeta.dmm
Labels: Tweak

#1933 shuttle patch on mobile
  code/modules/shuttle/shuttle_creation/shuttle_creator.dm
Labels: Fix

#1938 fixes floorpill supersoldier mutation toxin
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Fix

#1903 Floorpills are now an actual lottery
  code/modules/integrated_electronics/subtypes/reagents.dm
  code/modules/reagents/chemistry/machinery/reagentgrinder.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/pill.dm
Labels: Tweak, ike approved™

#1937 fixes a bug i didnt know about for like 2 bloody months
  code/modules/mining/equipment/regenerative_core.dm
Labels: Fix

#1888 Add dermal button to nanites
  code/modules/research/techweb/all_nodes.dm
Labels: Feature

#1945 Adds citation functionality to sechuds
  code/controllers/configuration/entries/game_options.dm
  code/game/machinery/computer/security.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Feature

#1951 Travis Update + Docker Fix
  Dockerfile
Labels: Tools

#1915 [kinda-bounty]adds a new level 9 symptom
  beestation.dme
  code/datums/diseases/advance/presets.dm
  code/datums/diseases/advance/symptoms/macrophage.dm
  code/modules/mob/living/simple_animal/hostile/macrophage.dm
  code/modules/reagents/reagent_containers/bottle.dm
  icons/mob/animal.dmi
Labels: Feature, Sprites, Tweak, Vote Passed

#1947 Adds weighting to random rooms, new rooms by gizkafreechman
  _maps/RandomRooms/10x10/sk_rdm070_pubbybar.dmm
  _maps/RandomRooms/10x10/sk_rdm098_graffitiroom.dmm
  _maps/RandomRooms/10x10/sk_rdm102_podrepairbay.dmm
  _maps/RandomRooms/10x5/sk_rdm046_deltaarcade.dmm
  _maps/RandomRooms/10x5/sk_rdm100_meetingroom.dmm
  _maps/RandomRooms/10x5/sk_rdm105_phage.dmm
  _maps/RandomRooms/3x3/sk_rdm093_bubblegumaltar.dmm
  _maps/RandomRooms/3x5/sk_rdm085_hank.dmm
  _maps/RandomRooms/3x5/sk_rdm094_canisterroom.dmm
  _maps/RandomRooms/3x5/sk_rdm095_durandwreck.dmm
  _maps/RandomRooms/5x3/sk_rdm099_incompletefloor.dmm
  _maps/RandomRooms/5x3/sk_rdm101_minibreakroom.dmm
  _maps/RandomRooms/5x3/sk_rdm103_stroreroom.dmm
  _maps/RandomRooms/5x3/sk_rdm104_pills.dmm
  _maps/RandomRooms/5x4/sk_rdm096_comproom.dmm
  _maps/RandomRooms/5x4/sk_rdm097_firemanroom.dmm
  code/game/objects/effects/spawners/roomspawner.dm
  code/modules/antagonists/nukeop/nukeop.dm
  code/modules/mapping/random_rooms.dm
  code/modules/paperwork/paper.dm
Labels: Balance/Rebalance, Feature, Fix, Tweak

#1940 Adds toe stubbing
  code/game/objects/structures/tables_racks.dm
Labels: Feature, Vote Passed

#1959 Fixes runtime in diseases
  code/datums/diseases/advance/presets.dm
Labels: Code Improvement, Fix

#1955 Fixes hermit doctor and legion cultist outfits
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
Labels: Fix

#1925 Pipebow balance
  code/datums/components/crafting/recipes.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  icons/obj/guns/projectile.dmi
Labels: Balance/Rebalance, Feature, Sprites, Tweak

#1977 Ghost filter checking
  code/modules/mob/dead/observer/say.dm
Labels: Code Improvement

#1971 Revert "Headspiders IV: Actually balanced edition"
  code/modules/antagonists/changeling/changeling.dm
  code/modules/mob/living/simple_animal/hostile/headcrab.dm
Labels: Removal

#1983 Directional Airlock Cycle Controllers
  code/game/machinery/airlock_cycle_control.dm
Labels: Feature

#1958 Datum-based poll creation and vote handling
  SQL/beestation_schema.sql
  SQL/database_changelog.txt
  beestation.dme
  code/__DEFINES/subsystems.dm
  code/_globalvars/misc.dm
  code/game/world.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/poll_management.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/admin/topic.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/dead/new_player/poll.dm
  html/admin/admin_panels.css
  html/admin/admin_panels_css3.css
  html/admin/banpanel.css
Labels: Administration, sql

#1988 Attack_verb grammar
  code/game/objects/items/bodybag.dm
  code/game/objects/items/holy_weapons.dm
  code/game/objects/items/kitchen.dm
  code/game/objects/items/melee/energy.dm
  code/game/objects/items/melee/misc.dm
  code/game/objects/items/melee/transforming.dm
  code/game/objects/items/miscellaneous.dm
  code/game/objects/items/twohanded.dm
  code/game/objects/items/weaponry.dm
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/hydroponics/hydroitemdefines.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/ninja/energy_katana.dm
  code/modules/paperwork/pen.dm
  code/modules/surgery/tools.dm
Labels: Fix, Grammar and Formatting

#2000 Changes for latest stable
  Dockerfile
  code/_globalvars/lists/flavor_misc.dm
Labels: Tools

#1954 BUffs stimulum
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Balance/Rebalance, Vote Passed

#1996 Prevents detective_scanner from working through walls
  code/modules/detectivework/scanner.dm
Labels: Balance/Rebalance

#1998 Fixes a toe stubbing oversight
  code/game/objects/structures/tables_racks.dm
Labels: Fix

#1950 Fix slot machines
  code/game/machinery/slotmachine.dm
Labels: security

#1990 laser pointer
  code/game/objects/items/devices/laserpointer.dm
Labels: Balance/Rebalance

#1970 Skeleton spawner fix
  beestation.dme
  code/modules/awaymissions/corpse.dm
Labels: Fix

#1967 The return of flypeople
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Config Update

#2012 Parallax fix (#49850)
  code/game/turfs/open/space/space.dm
  code/game/turfs/turf.dm
Labels: Fix

#2003 Edited sprite for the stacking machine.
  code/modules/mining/machine_bluespaceminer.dm
  icons/obj/machines/mining_machines.dmi
Labels: Tweak

#1975 Fix lighting on CameraConsole and Spy Bug (#50669)
  code/_onclick/hud/map_popups.dm
  code/game/machinery/computer/camera.dm
Labels: Fix

#1956 random maint: delta station
  _maps/RandomRooms/10x10/sk_rdm106_sanitarium.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  code/__DEFINES/jobs.dm
  code/game/machinery/computer/crew.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/modules/jobs/job_types/gimmick.dm
  code/modules/mapping/random_rooms.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
Labels: Feature

#1969 Reveal ghosts when the round ends (#51572)
  code/__HELPERS/mobs.dm
  code/__HELPERS/roundend.dm
Labels: Feature, Vote Passed

#1856 Admin verb reorganization + extra
  code/controllers/subsystem/events.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/create_poll.dm
  code/modules/admin/team_panel.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminjump.dm
  code/modules/admin/verbs/adminsay.dm
  code/modules/admin/verbs/cinematic.dm
  code/modules/admin/verbs/deadsay.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/diagnostics.dm
  code/modules/admin/verbs/modify_antag_tokens.dm
  code/modules/admin/verbs/one_click_antag.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/admin/verbs/reestablish_db_connection.dm
  code/modules/admin/verbs/shuttlepanel.dm
  code/modules/cargo/centcom_podlauncher.dm
Labels: Administration, Feature, Vote Passed

#1924 Revert gold necklace name in beecoin shop
  code/modules/client/loadout/loadout_accessories.dm
Labels: Fix

#1926 Removes stasis bed pipes overlay sprite
  code/game/machinery/stasis.dm
  icons/obj/machines/stasis.dmi
Labels: Removal

#1968 TGUI Orbit Menu
  beestation.dme
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/antagonists/abductor/abductor.dm
  code/modules/antagonists/ashwalker/ashwalker.dm
  code/modules/antagonists/blob/blob.dm
  code/modules/antagonists/devil/devil.dm
  code/modules/antagonists/disease/disease_datum.dm
  code/modules/antagonists/ert/ert.dm
  code/modules/antagonists/monkey/monkey.dm
  code/modules/antagonists/nightmare/nightmare.dm
  code/modules/antagonists/ninja/ninja.dm
  code/modules/antagonists/nukeop/nukeop.dm
  code/modules/antagonists/official/official.dm
  code/modules/antagonists/pirate/pirate.dm
  code/modules/antagonists/revenant/revenant_antag.dm
  code/modules/antagonists/santa/santa.dm
  code/modules/antagonists/slaughter/slaughter_antag.dm
  code/modules/antagonists/space_dragon/space_dragon.dm
  code/modules/antagonists/wizard/wizard.dm
  code/modules/antagonists/xeno/xeno.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/dead/observer/orbit.dm
  html/ghost.png
  tgui/packages/tgui/interfaces/Orbit.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Feature

#2014 fixes Cyborg and Integrated Circuit cameras
  code/game/machinery/computer/camera.dm
Labels: Fix

#2018 Changes cat butcher dodge to true
  code/modules/mob/living/simple_animal/hostile/cat_butcher.dm
Labels: Tweak

#2007 Removes support for versions below 513.1526.
  config/Sage/config.txt
  config/config.txt
Labels: Config Update, DO NOT MERGE

#1943 Optimizes lighting
  code/modules/lighting/lighting_corner.dm
Labels: Code Improvement, Refactor

#2020 small mapping fixes
  _maps/RandomRooms/10x10/sk_rdm106_sanitarium.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Fix

#2022 changes to lexorin and sulfonal recipes
  code/modules/reagents/chemistry/recipes/toxins.dm
Labels: Balance/Rebalance

#2034 Removes Exploitable World/Topic Command server_hop (#51793)
  code/datums/world_topic.dm
  code/modules/mob/dead/dead.dm
Labels: Removal, server

#1957 Fixes some DoS vectors
  code/modules/client/client_defines.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/silicon/silicon.dm
Labels: Tweak

#2039 Corrects the schema version
  SQL/beestation_schema.sql
Labels: sql

#2041 Fixes ban check queries
  code/modules/admin/sql_ban_system.dm
Labels: Administration, sql

#2037 Add dermal button icons
  icons/mob/actions/actions_items.dmi
Labels: Sprites

#2044 [Port] Fix Malformed SQL Queries When Editing Admin Permissions
  code/modules/admin/permissionedit.dm
Labels: Administration, Port, sql

#2051 Adds the dice cup, and dice show which side is face up on examine
  code/game/objects/items/dice.dm
  code/game/objects/items/stacks/sheets/leather.dm
  icons/obj/dice.dmi
Labels: Feature, Tweak

#2002 Updated Pumps in MetaStation
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Tweak

#2050 Fixes broken botany iconstates
  code/modules/hydroponics/hydroponics.dm
Labels: Fix

#2052 Fixes squid attack verb
  code/modules/mob/living/carbon/human/species_types/squidpeople.dm
Labels: Fix

#2054 Metastation SM used Neutrogena and has volume now
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Tweak

#2055 fixes skinsuit helmet
  code/modules/clothing/spacesuits/miscellaneous.dm
Labels: Fix

#2049 Log arguments on query leak and Slow Query
  code/controllers/subsystem/dbcore.dm
Labels: server

#2061 Fixes push brooms breaking things
  code/game/objects/items/twohanded.dm
Labels: Fix, Tweak

#2063 Removes bad squidnames
  strings/names/squid_female.txt
  strings/names/squid_male.txt
Labels: Removal

#2065 Fixes the skin
  code/modules/client/darkmode.dm
  interface/skin.dmf
Labels: Fix

#2066 Fixes addiction runtime
  code/datums/traits/negative.dm
Labels: code cleanup

#2071 Rust-g SQL Fixes Round 2
  code/controllers/subsystem/dbcore.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/admin/sql_message_system.dm
Labels: Administration, Fix, Removal

#2072 Brings the Dockerfile up to date
  Dockerfile
Labels: Tools

#2070 Makes the status panel less laggy by removing multi-column stats()
  code/modules/antagonists/swarmer/swarmer.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Code Improvement

#2075 Fixes Metastation patrol route looping outside engineering
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Fix

#2013 Adds the Virus Extrapolator, removes Viral Base bottle
  _maps/RandomRooms/10x10/sk_rdm033_deltalibrary.dmm
  _maps/RandomRooms/10x10/sk_rdm060_snakefighter.dmm
  _maps/RandomRooms/10x10/sk_rdm102_podrepairbay.dmm
  _maps/RandomRooms/10x5/sk_rdm039_deltaclutter1.dmm
  _maps/RandomRooms/10x5/sk_rdm045_deltacafeteria.dmm
  _maps/RandomRooms/10x5/sk_rdm091_skidrow.dmm
  _maps/RandomRooms/10x5/sk_rdm105_phage.dmm
  _maps/RandomRooms/3x3/sk_rdm006_gibs.dmm
  _maps/RandomRooms/3x3/sk_rdm010_hazmat.dmm
  _maps/RandomRooms/3x3/sk_rdm020_boxclutter6.dmm
  _maps/RandomRooms/3x3/sk_rdm022_boxchemcloset.dmm
  _maps/RandomRooms/3x3/sk_rdm050_medicloset.dmm
  _maps/RandomRooms/3x3/sk_rdm059_pubbyclutter3.dmm
  _maps/RandomRooms/3x3/sk_rdm069_pubbyartism.dmm
  _maps/RandomRooms/3x3/sk_rdm072_donutcapgun.dmm
  _maps/RandomRooms/3x3/sk_rdm092_hobohut.dmm
  _maps/RandomRooms/3x5/sk_rdm086_laststand.dmm
  _maps/RandomRooms/3x5/sk_rdm094_canisterroom.dmm
  _maps/RandomRooms/3x5/sk_rdm095_durandwreck.dmm
  _maps/RandomRooms/5x3/sk_rdm043_deltaclutter3.dmm
  _maps/RandomRooms/5x3/sk_rdm071_pubbykitchen.dmm
  _maps/RandomRooms/5x3/sk_rdm089_nastytrap.dmm
  _maps/RandomRooms/5x3/sk_rdm103_stroreroom.dmm
  _maps/RandomRooms/5x3/sk_rdm104_pills.dmm
  _maps/RandomRooms/5x4/sk_rdm012_boxbar.dmm
  _maps/RandomRooms/5x4/sk_rdm029_deltabar.dmm
  _maps/RandomRooms/5x4/sk_rdm035_deltasurgery.dmm
  _maps/RandomRooms/5x4/sk_rdm047_metarobotics.dmm
  _maps/RandomRooms/5x4/sk_rdm076_kilohauntedlibrary.dmm
  _maps/RandomRooms/5x4/sk_rdm090_tinybarbershop.dmm
  _maps/RandomRooms/5x4/sk_rdm096_comproom.dmm
  _maps/RandomRooms/5x4/sk_rdm097_firemanroom.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/__DEFINES/components.dm
  code/_globalvars/lists/maintenance_loot.dm
  code/datums/components/infective.dm
  code/datums/diseases/advance/presets.dm
  code/datums/diseases/advance/symptoms/blobspores.dm
  code/game/atoms.dm
  code/game/objects/effects/decals/cleanable/humans.dm
  code/game/objects/effects/decals/cleanable/misc.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/lavaland/necropolis_tendril.dm
  code/modules/antagonists/blob/blob_mobs.dm
  code/modules/jobs/job_types/virologist.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/friendly/hamster.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/hostile/macrophage.dm
  code/modules/mob/living/simple_animal/hostile/wumborian_fugu.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/research/designs/stock_parts_designs.dm
  icons/obj/device.dmi
Labels: Balance/Rebalance, Feature, Fix, Removal, Sprites, Tweak, Vote Passed

#2042 weekly cat surgeon buff [hopefully the last one]
  code/modules/mapping/random_rooms.dm
  code/modules/mob/living/simple_animal/hostile/cat_butcher.dm
Labels: Balance/Rebalance, Fix, Tweak, Vote Passed

#2074 Adds prove P.R.O.V.E. cartridge to deltastation
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Feature

#2016 nerfs macrophage
  code/datums/diseases/advance/symptoms/macrophage.dm
  code/modules/mob/living/simple_animal/hostile/macrophage.dm
Labels: Balance/Rebalance

#2082 fixes to disease channels
  code/datums/diseases/advance/advance.dm
  code/datums/diseases/advance/symptoms/symptoms.dm
Labels: Code Improvement, Fix, Refactor
