Repository BeeStation/BeeStation-Hornet, pull requests merged in 2020-05, with the labels that each got.

#1697 fixes up severity code a bit
  code/datums/diseases/advance/advance.dm
  code/datums/diseases/advance/symptoms/beesymptom.dm
  code/datums/diseases/advance/symptoms/blobspores.dm
  code/datums/diseases/advance/symptoms/braindamage.dm
  code/datums/diseases/advance/symptoms/choking.dm
  code/datums/diseases/advance/symptoms/confusion.dm
  code/datums/diseases/advance/symptoms/cough.dm
  code/datums/diseases/advance/symptoms/deafness.dm
  code/datums/diseases/advance/symptoms/fever.dm
  code/datums/diseases/advance/symptoms/fire.dm
  code/datums/diseases/advance/symptoms/genetics.dm
  code/datums/diseases/advance/symptoms/hallucigen.dm
  code/datums/diseases/advance/symptoms/headache.dm
  code/datums/diseases/advance/symptoms/heal.dm
  code/datums/diseases/advance/symptoms/heartattack.dm
  code/datums/diseases/advance/symptoms/lubefeet.dm
  code/datums/diseases/advance/symptoms/narcolepsy.dm
  code/datums/diseases/advance/symptoms/necropolis.dm
  code/datums/diseases/advance/symptoms/pierrot.dm
  code/datums/diseases/advance/symptoms/radiation.dm
  code/datums/diseases/advance/symptoms/shivering.dm
  code/datums/diseases/advance/symptoms/spiked.dm
  code/datums/diseases/advance/symptoms/symptoms.dm
  code/datums/diseases/advance/symptoms/vision.dm
  code/datums/diseases/advance/symptoms/voice_change.dm
  code/datums/diseases/advance/symptoms/wizarditis.dm
Labels: Code Improvement, Fix

#1694 Syndicate Revolver rebalance
  code/modules/projectiles/ammunition/ballistic/shotgun.dm
  code/modules/research/designs/autolathe_designs.dm
  code/modules/uplink/uplink_items.dm
Labels: Needs Vote

#1692 QoL Map Upgrades v2: Boxstation
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Fix, Map Edit, Tweak

#1612 Refactors screen object update_icon to call parent #47094
  code/__DEFINES/components.dm
  code/_onclick/hud/ai.dm
  code/_onclick/hud/alien.dm
  code/_onclick/hud/alien_larva.dm
  code/_onclick/hud/blob_overmind.dm
  code/_onclick/hud/blobbernauthud.dm
  code/_onclick/hud/constructs.dm
  code/_onclick/hud/devil.dm
  code/_onclick/hud/drones.dm
  code/_onclick/hud/generic_dextrous.dm
  code/_onclick/hud/ghost.dm
  code/_onclick/hud/guardian.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/monkey.dm
  code/_onclick/hud/revenanthud.dm
  code/_onclick/hud/robot.dm
  code/_onclick/hud/screen_objects.dm
  code/_onclick/hud/slime.dm
  code/_onclick/hud/swarmer.dm
  code/datums/martial/sleeping_carp.dm
  code/game/area/areas.dm
  code/game/atoms.dm
  code/game/machinery/buttons.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/devices/transfer_valve.dm
  code/game/objects/items/robot/robot_items.dm
  code/game/objects/objs.dm
  code/game/objects/structures/divine.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/wall/reinf_walls.dm
  code/game/turfs/space/transit.dm
  code/modules/assembly/flash.dm
  code/modules/cargo/gondolapod.dm
  code/modules/holodeck/turfs.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/honkbot.dm
  code/modules/mob/living/simple_animal/bot/secbot.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_movement.dm
Labels: Refactor

#1702 small fire rate refactor, truly automatic guns, dual wielding
  code/game/objects/items/robot/robot_items.dm
  code/modules/projectiles/ammunition/_ammunition.dm
  code/modules/projectiles/ammunition/_firing.dm
  code/modules/projectiles/ammunition/caseless/misc.dm
  code/modules/projectiles/ammunition/energy/special.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/laser_gatling.dm
  code/modules/projectiles/guns/ballistic/launchers.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/guns/ballistic/toy.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/pulse.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/guns/magic/staff.dm
  code/modules/projectiles/guns/magic/wand.dm
  code/modules/projectiles/guns/misc/chem_gun.dm
  code/modules/projectiles/guns/misc/grenade_launcher.dm
  code/modules/projectiles/guns/misc/syringe_gun.dm
  code/modules/projectiles/projectile/special/plasma.dm
Labels: Balance/Rebalance, Feature, Fix, Refactor, Tweak

#1708 Some viro QoL stuff
  code/__DEFINES/diseases.dm
  code/datums/diseases/advance/advance.dm
  code/datums/diseases/advance/symptoms/heal.dm
  code/datums/diseases/advance/symptoms/lubefeet.dm
  code/datums/diseases/advance/symptoms/spiked.dm
  code/modules/mob/living/blood.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/vending/medical.dm
Labels: Feature, Sound, Tweak

#1689 Ports "Edited Gygax diamond cost to be silver and gold but the same values #46385" from /tg/
  code/modules/research/designs/mechfabricator_designs.dm
Labels: Balance/Rebalance

#1646 Fix BADDNA brains transferring minds (#49214)
  code/modules/mob/living/brain/brain_item.dm
Labels: Fix

#1676 Skateboard Overhaul (#45657)
  code/__DEFINES/traits.dm
  code/__HELPERS/mobs.dm
  code/datums/mutations/body.dm
  code/game/objects/items/weaponry.dm
  code/modules/vehicles/scooter.dm
  code/modules/vehicles/vehicle_actions.dm
  code/modules/vending/games.dm
  icons/mob/actions/actions_vehicle.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/items_and_weapons.dmi
  icons/obj/vehicles.dmi
  sound/vehicles/skateboard_ollie.ogg
  sound/vehicles/skateboard_roll.ogg
Labels: Feature, Removal, Sound, Sprites

#1571 Apids (Bee People) Approved™ Pectoral Edition
  beestation.dme
  code/__HELPERS/mobs.dm
  code/__HELPERS/names.dm
  code/_globalvars/lists/names.dm
  code/datums/action.dm
  code/modules/food_and_drinks/food/snacks/meat.dm
  code/modules/language/apidite.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species_types/apid.dm
  code/modules/surgery/organs/eyes.dm
  code/modules/surgery/organs/lungs.dm
  code/modules/surgery/organs/tongue.dm
  config/Sage/game_options.txt
  config/game_options.txt
  icons/misc/language.dmi
  icons/mob/feet.dmi
  icons/mob/human_parts.dmi
  icons/mob/neck.dmi
  icons/mob/wings.dmi
  icons/obj/food/food.dmi
  strings/names/apid_first_female.txt
  strings/names/apid_first_male.txt
  strings/names/apid_last.txt
Labels: Config Update, Feature, Needs Wiki Changes, Sprites, Work In Progress

#1713 Fix a bunch of issues
  _maps/map_files/MetaStation/MetaStation.dmm
  code/datums/traits/negative.dm
  code/game/gamemodes/gangs/gang_pen.dm
  code/game/objects/effects/countdown.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/antagonists/swarmer/swarmer.dm
  code/modules/cargo/packs.dm
  code/modules/keybindings/bindings_client.dm
Labels: Fix, Map Edit

#1714 Update CODEOWNERS
  .github/CODEOWNERS
Labels: GitHub

#1670 RANDOM MAINT EXPANSION 1: JOBS
  _maps/RandomRooms/10x10/sk_rdm083_bigtheatre.dmm
  _maps/RandomRooms/10x10/sk_rdm088_bigconstruction.dmm
  _maps/RandomRooms/10x5/sk_rdm011_barbershop.dmm
  _maps/RandomRooms/10x5/sk_rdm_082_maintmedical.dmm
  _maps/RandomRooms/3x3/sk_rdm028_tranquility.dmm
  _maps/RandomRooms/3x3/sk_rdm081_biohazard.dmm
  _maps/RandomRooms/3x5/sk_rdm084_monky.dmm
  _maps/RandomRooms/3x5/sk_rdm085_hank.dmm
  _maps/RandomRooms/3x5/sk_rdm086_laststand.dmm
  _maps/RandomRooms/3x5/sk_rdm087_junkcloset.dmm
  _maps/RandomRooms/5x3/sk_rdm080_cloner.dmm
  _maps/RandomRooms/5x3/sk_rdm089_nastytrap.dmm
  _maps/RandomRooms/5x4/sk_rdm048_metatheatre.dmm
  _maps/RandomRooms/5x4/sk_rdm090_tinybarbershop.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  beestation.dme
  code/__DEFINES/jobs.dm
  code/controllers/subsystem/job.dm
  code/datums/traits/negative.dm
  code/game/machinery/computer/card.dm
  code/game/machinery/computer/crew.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/devices/traitordevices.dm
  code/game/objects/items/miscellaneous.dm
  code/game/objects/structures/bedsheet_bin.dm
  code/modules/client/preferences.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/outfits/plasmaman.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/clothing/under/jobs/Plasmaman/civilian_service.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/gimmick.dm
  code/modules/mapping/random_rooms.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/recycling/disposal/bin.dm
  icons/mob/head.dmi
  icons/mob/neck.dmi
  icons/mob/uniform.dmi
  icons/obj/bedsheets.dmi
  icons/obj/clothing/hats.dmi
Labels: Config Update, Feature, Fix, Map Edit, Needs Wiki Changes, Sprites, Tweak

#1687 Fixes radio implant preventing your headset from sending messages
  code/modules/mob/living/say.dm
Labels: Fix

#1705 flashbang changes
  code/game/objects/items/grenades/flashbang.dm
  code/modules/surgery/organs/ears.dm
Labels: Tweak

#1733 Apid Fixes
  code/modules/surgery/organs/tongue.dm
  icons/mob/neck.dmi
Labels: Fix, Sprites

#1731 Updates actions to only run within our repository
  .github/workflows/compile_changelogs.yml
  .github/workflows/docker.yml
  .github/workflows/stale_issues.yml
  .github/workflows/stale_prs.yml
Labels: GitHub

#1739 TGUI Tutorial fix and BYOND cache locator ports
  tgui/docs/tutorial-and-examples.md
  tgui/packages/tgui-dev-server/reloader.js
  tgui/packages/tgui-dev-server/winreg.js
Labels: UI

#1592 Cult stun protected against by mindshields instead, and it only offers partial immunity
  code/modules/antagonists/cult/blood_magic.dm
Labels: Balance/Rebalance, Vote Passed

#1680 Removes the "To Kill" wish option from the wishgranter (#47084)
  code/modules/awaymissions/mission_code/wildwest.dm
Labels: Removal, Vote Failed

#1755 Apids now friendly with bee faction
  code/modules/mob/living/carbon/human/species_types/apid.dm
Labels: Feature

#1756 Actions: Generate and Compile CLs without needing a webhook!™
  .github/workflows/compile_changelogs.yml
  .github/workflows/make_changelogs.yml
  TGS3.json
  tools/changelog/generate_cl.py
  tools/changelog/makeChangelog.bat
  tools/changelog/ss13_genchangelog.py
  tools/changelog/tags.yml
  tools/tgs4_scripts/PreSynchronize.ps1
  tools/tgs4_scripts/PreSynchronize.sh
  tools/travis/check_changelogs.sh
Labels: Code Improvement, GitHub, Tools

#1759 Actions: Make CL depth adjustment
  .github/workflows/make_changelogs.yml
Labels: Code Improvement

#1761 Actions: CL Token Adjustment
  .github/workflows/make_changelogs.yml
Labels: Feature, Sprites

#1762 Updates Travis to use the latest version
  Dockerfile
Labels: Feature, Sprites

#1764 Actions: Another Make CL edge case fix
  .github/workflows/make_changelogs.yml
Labels: Tweak

#1765 Update README.md
  README.md
Labels: Grammar and Formatting

#1767 I'm taking a break from actions after this
  .github/workflows/make_changelogs.yml
  tools/changelog/generate_cl.py
Labels: Fix

#1763 fixes id console blacklist of gimmick jobs
  code/game/machinery/computer/card.dm
  code/modules/jobs/job_types/gimmick.dm
Labels: Fix

#1575 BeeCoin shop & Loadout additions
  beestation.dme
  code/modules/client/loadout/loadout.dm
  code/modules/client/loadout/loadout_accessories.dm
  code/modules/client/loadout/loadout_cosmestics.dm
  code/modules/client/loadout/loadout_footwear.dm
  code/modules/client/loadout/loadout_general.dm
  code/modules/client/loadout/loadout_hat.dm
  code/modules/client/loadout/loadout_ooc.dm
  code/modules/client/loadout/loadout_suit.dm
  code/modules/client/loadout/loadout_uniform.dm
  code/modules/client/preferences.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/color.dm
  code/modules/clothing/under/jobs/security.dm
Labels: Code Improvement, Feature, Fix, Grammar and Formatting

#1567 A few radiation optimizations
  code/__DEFINES/radiation.dm
  code/__HELPERS/radiation.dm
  code/datums/components/radioactive.dm
  code/datums/radiation_wave.dm
Labels: Fix

#1711 Build-a-Stand Mk1: JoJo Harder
  _maps/RandomRuins/LavaRuins/lavaland_surface_standruin.dmm
  _maps/RandomZLevels/Academy.dmm
  _maps/templates/pocket_dimension.dmm
  beestation.dme
  code/__DEFINES/components.dm
  code/__DEFINES/medal.dm
  code/__DEFINES/misc.dm
  code/__DEFINES/role_preferences.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/hud/guardian.dm
  code/_onclick/item_attack.dm
  code/datums/mind.dm
  code/game/area/areas/ruins/lavaland.dm
  code/game/machinery/cloning.dm
  code/game/machinery/computer/arcade.dm
  code/modules/antagonists/guardian/guardian.dm
  code/modules/antagonists/wizard/equipment/spellbook.dm
  code/modules/fields/timestop.dm
  code/modules/guardian/abilities/_ability.dm
  code/modules/guardian/abilities/major/assassin.dm
  code/modules/guardian/abilities/major/explosive.dm
  code/modules/guardian/abilities/major/frenzy.dm
  code/modules/guardian/abilities/major/gravity.dm
  code/modules/guardian/abilities/major/hand.dm
  code/modules/guardian/abilities/major/healing.dm
  code/modules/guardian/abilities/major/predator.dm
  code/modules/guardian/abilities/major/scout.dm
  code/modules/guardian/abilities/major/time.dm
  code/modules/guardian/abilities/minor/snares.dm
  code/modules/guardian/abilities/minor/teleport.dm
  code/modules/guardian/abilities/special/absolution.dm
  code/modules/guardian/abilities/special/pocket.dm
  code/modules/guardian/abilities/special/time.dm
  code/modules/guardian/guardian.dm
  code/modules/guardian/guardianability.dm
  code/modules/guardian/guardianbuilder.dm
  code/modules/guardian/guardianstats.dm
  code/modules/guardian/standarrow.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/spells/spell_types/rightandwrong.dm
  code/modules/uplink/uplink_items.dm
  code/modules/vending/autodrobe.dm
  code/modules/vending/toys.dm
  icons/effects/effects.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/items_and_weapons.dmi
  sound/effects/kingcrimson_end.ogg
  sound/effects/kingcrimson_start.ogg
  sound/effects/vector_appear.ogg
  sound/effects/vector_rush.ogg
  sound/effects/zahando.ogg
  tgui/packages/tgui/components/LabeledList.js
  tgui/packages/tgui/interfaces/Guardian.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Feature, Map Edit, Needs Wiki Changes, Sound, Sprites, UI, Vote Passed, test merged

#1749 Stop 'special additional role' from being spawned as an event.
  code/controllers/subsystem/events.dm
  code/game/gamemodes/game_mode.dm
  code/modules/antagonists/roundstart_special/special_antagonist.dm
  code/modules/events/_event.dm
  code/modules/events/special_antag_event.dm
Labels: Code Improvement, Fix

#1605 Ports "Cleans up saycode by removing random hook stubs and using a signal where relevant"
  code/__DEFINES/components.dm
  code/_globalvars/bitfields.dm
  code/datums/brain_damage/brain_trauma.dm
  code/datums/brain_damage/creepy_trauma.dm
  code/datums/brain_damage/mild.dm
  code/datums/brain_damage/phobia.dm
  code/datums/brain_damage/split_personality.dm
  code/datums/diseases/pierrot_throat.dm
  code/datums/dna.dm
  code/datums/mutations.dm
  code/datums/mutations/hulk.dm
  code/datums/mutations/speech.dm
  code/game/atoms_movable.dm
  code/game/machinery/announcement_system.dm
  code/game/machinery/bank_machine.dm
  code/game/machinery/cloning.dm
  code/game/machinery/requests_console.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/instruments.dm
  code/game/objects/items/devices/megaphone.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/taster.dm
  code/game/objects/objs.dm
  code/game/say.dm
  code/modules/antagonists/blob/blob_mobs.dm
  code/modules/antagonists/blob/overmind.dm
  code/modules/antagonists/clockcult/clock_mobs.dm
  code/modules/antagonists/swarmer/swarmer.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/masks/_masks.dm
  code/modules/clothing/masks/boxing.dm
  code/modules/clothing/masks/cluwne.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/integrated_electronics/subtypes/output.dm
  code/modules/mob/living/brain/brain.dm
  code/modules/mob/living/brain/say.dm
  code/modules/mob/living/carbon/alien/say.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/IPC.dm
  code/modules/mob/living/carbon/human/species_types/dullahan.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/human/species_types/synths.dm
  code/modules/mob/living/carbon/say.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/silicon/ai/say.dm
  code/modules/mob/living/silicon/say.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  code/modules/mob/living/simple_animal/friendly/drone/say.dm
  code/modules/mob/say.dm
  code/modules/power/supermatter/supermatter.dm
  code/modules/surgery/organs/tongue.dm
Labels: Code Improvement

#1673 Revert "More Crates And Some Changes To Other Crates"
  code/game/objects/items/stacks/bscrystal.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/modules/cargo/packs.dm
Labels: Revert, Vote Failed

#1745 Antagonists can now be set to not prevent round end
  code/game/gamemodes/game_mode.dm
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/antagonists/roundstart_special/special_antagonist.dm
  code/modules/awaymissions/corpse.dm
Labels: Code Improvement

#1778 Fixes conveyors and probably makes them faster.
  code/game/atoms_movable.dm
  code/game/objects/effects/effects.dm
  code/modules/mob/dead/dead.dm
  code/modules/mob/living/living.dm
  code/modules/recycling/conveyor2.dm
Labels: Fix

#1742 Removes references to role_special
  code/__DEFINES/role_preferences.dm
  code/game/gamemodes/game_mode.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/antagonists/roundstart_special/special_antagonist.dm
  code/modules/events/special_antag_event.dm
Labels: Code Improvement, Removal

#1695 Plasmamen flash/welding protection is now a toggleable visor
  code/datums/action.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Balance/Rebalance, Sprites, Vote Passed

#1779 Actions: CL Generator script - Adds documentation to the script and improves the push method
  .github/workflows/make_changelogs.yml
  tools/changelog/generate_cl.py
Labels: Tweak, tooling

#1735 Researchable Smartmines + Exploding Rubber Duck traitor item
  code/game/objects/effects/mines.dm
  code/modules/cargo/packs.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature, Tweak

#1780 Revert "Cult stun protected against by mindshields instead, and it only offers partial immunity"
  code/modules/antagonists/cult/blood_magic.dm
Labels: Balance/Rebalance, Needs Vote

#1744 adds upgrade wand, magicman balance changes
  code/game/objects/items/devices/traitordevices.dm
  code/game/objects/items/miscellaneous.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/uplink/uplink_items.dm
Labels: Balance/Rebalance, Feature, Needs Vote

#1655 Exosuit refactors - /tg/ #46579 and 49299
  code/__DEFINES/mecha.dm
  code/game/mecha/equipment/tools/work_tools.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_construction_paths.dm
  code/game/mecha/mecha_defense.dm
  code/game/mecha/mecha_topic.dm
Labels: Code Improvement, Feature, Needs Testmerge, Needs Wiki Changes, Refactor, Tweak

#1700 Better gauze + medical patch crafting
  code/datums/components/crafting/recipes.dm
  code/game/objects/items/stacks/medical.dm
Labels: Feature, Vote Passed

#1781 various small tweaks to #1642
  code/__DEFINES/traits.dm
  code/game/objects/items.dm
  code/game/objects/items/melee/energy.dm
  code/game/objects/items/powerfist.dm
  code/game/objects/items/shields.dm
  code/game/objects/items/storage/briefcase.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/twohanded.dm
  code/game/objects/items/weaponry.dm
  code/game/objects/structures/beds_chairs/chair.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
Labels: Balance/Rebalance, Feature, Fix, THIS IS VERY IMPORTANT, Tweak

#1729 Lavaland shuttle fix + Some other fix
  code/game/objects/items/shuttle_creator.dm
Labels: Fix, Tweak

#1724 [READY] [PORT] Making the RD Servers do something than take up space from /tg/
  code/controllers/subsystem/research.dm
  code/modules/research/server.dm
  tgui/packages/tgui/interfaces/RDConsole.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Feature, Port, UI

#1783 Adds the Billy club, a new sec tool
  _maps/map_files/generic/CentCom.dmm
  code/datums/components/crafting/recipes.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/weaponry.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/warden.dm
  icons/obj/items_and_weapons.dmi
Labels: Feature, Tweak, Vote Passed

#1792 tgui: Biogenerator #51022
  code/modules/hydroponics/biogenerator.dm
  tgui/packages/tgui/interfaces/Biogenerator.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Feature, Port

#1794 Fixes felinid virus speech
  code/datums/diseases/transformation.dm
Labels: Fix

#1777 adds parrying
  code/__DEFINES/traits.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items.dm
  code/game/objects/items/shields.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/mob_movement.dm
  sound/weapons/deflect.ogg
Labels: Feature, Sound, Tweak, Vote Passed

#1795 small qol change
  code/modules/mob/living/living_defense.dm
Labels: Tweak

#1737 buffs relic water bottle
  code/modules/mining/lavaland/necropolis_chests.dm
Labels: Balance/Rebalance

#1734 autodoc sprite change
  code/game/machinery/autodoc.dm
  icons/obj/machines/autodoc.dmi
Labels: Sprites

#1768 adds plasmaman chameleon envirosuit, some blasmasuit refactors
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/clothing/chameleon.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/uplink/uplink_items.dm
Labels: Code Improvement, Feature, Refactor, Tweak

#1703 Traitor uplink items rework
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/clothing/shoes/taeclowndo.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/uplink/uplink_items.dm
Labels: Balance/Rebalance, Tweak, Vote Passed

#1740 adds a bee gun
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/projectiles/ammunition/special/syringe.dm
  code/modules/projectiles/guns/misc/chem_gun.dm
  code/modules/projectiles/projectile/bullets/dart_syringe.dm
  icons/obj/guns/projectile.dmi
Labels: Balance/Rebalance, Feature, Sprites, Vote Passed

#1797 Adds random maint to pubby, new gimmick job
  _maps/RandomRooms/10x5/sk_rdm091_skidrow.dmm
  _maps/RandomRooms/3x3/sk_rdm092_hobohut.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/__DEFINES/jobs.dm
  code/__DEFINES/traits.dm
  code/game/objects/effects/landmarks.dm
  code/modules/clothing/gloves/color.dm
  code/modules/clothing/outfits/plasmaman.dm
  code/modules/jobs/job_types/gimmick.dm
  code/modules/mapping/random_rooms.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/reagents/reagent_containers/pill.dm
Labels: Feature

#1709 My take on northstar gloves
  code/modules/clothing/gloves/miscellaneous.dm
Labels: Feature, Fix, Vote Passed

#1799 Full-auto firemode
  beestation.dme
  code/_onclick/drag_drop.dm
  code/modules/projectiles/autofire.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
Labels: Feature

#1790 Citations (#44853)
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  beestation.dme
  code/datums/datacore.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/computer/warrant.dm
  code/game/machinery/telecomms/machines/message_server.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/game/objects/items/devices/PDA/PDA.dm
Labels: Feature, Needs Wiki Changes, Vote Passed

#1798 Fixes some guardian bugs
  code/modules/guardian/guardian.dm
Labels: Fix

#1616 Mob Faction refactor + Lizard wings
  beestation.dme
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/angel.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/mushpeople.dm
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/mob/living/simple_animal/slime/life.dm
  icons/mob/moth_wings.dmi
  icons/mob/wings.dmi
Labels: Code Improvement, Feature, Fix, Refactor, Sprites

#1806 Fixes spammy comms consoles destroying the ears of the playerbase
  code/game/machinery/computer/communications.dm
Labels: Fix

#1803 fixes, parry removal, etc
  code/__DEFINES/traits.dm
  code/game/objects/items.dm
  code/game/objects/items/holy_weapons.dm
  code/game/objects/items/shields.dm
  code/game/objects/items/toys.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/mob_movement.dm
  code/modules/projectiles/autofire.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
Labels: Balance/Rebalance, Fix, Removal, Tweak

#1811 my name really be spelled wrong in da changelog doe
  html/templates/header.html
Labels: Fix, Grammar and Formatting

#1812 Removes OracleUI
  beestation.dme
  code/modules/oracle_ui/README.md
  code/modules/oracle_ui/assets.dm
  code/modules/oracle_ui/hookup_procs.dm
  code/modules/oracle_ui/oracle_ui.dm
  code/modules/oracle_ui/themed.dm
  code/modules/paperwork/paper.dm
  code/modules/recycling/disposal/bin.dm
  html/oracle_ui/content/disposal_bin/index.html
  html/oracle_ui/editor_tool.html
  html/oracle_ui/themes/nano/index.html
  html/oracle_ui/themes/nano/sui-nano-common.css
  html/oracle_ui/themes/nano/sui-nano-common.js
  html/oracle_ui/themes/nano/sui-nano-jquery.min.js
  html/oracle_ui/themes/paper/index.html
  html/oracle_ui/themes/paper/sui-paper-common.css
  html/oracle_ui/themes/paper/sui-paper-common.js
Labels: Fix, Removal, server

#1814 Emergency combat fix
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Fix

#1804 Makes secret extended actually exist.
  code/game/gamemodes/extended/extended.dm
Labels: Feature

#1819 EMERGENCY FIX can_interact logic issues
  code/game/machinery/_machinery.dm
Labels: Fix

#1801 Burn and brute patch balance
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Balance/Rebalance, Vote Passed

#1663 [Ready] Resprites MedSci uniforms & backpacks, sorts icon files internally
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/jobs/job_types/research_director.dm
  icons/mob/back.dmi
  icons/mob/feet.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/storage.dmi
Labels: Code Improvement, Feature, Grammar and Formatting, Sprites, Tweak, Vote Passed

#1522 Saving places
  beestation.dme
  code/__DEFINES/mapexporting.dm
  code/game/objects/items/storage/storage.dm
  code/game/objects/objs.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/buildmode/submodes/save_area.dm
  code/modules/mapexporting/mapexporter.dm
  code/modules/mining/machine_silo.dm
Labels: Needs Testmerge

#1816 Tgui ticket system
  beestation.dme
  code/__DEFINES/admin.dm
  code/datums/datumvars.dm
  code/modules/admin/admin_follow.dm
  code/modules/admin/admin_more_info.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/holder2.dm
  code/modules/admin/sql_message_system.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminjump.dm
  code/modules/admin/verbs/adminpm.dm
  tgui/packages/tgui/index.js
  tgui/packages/tgui/interfaces/TicketBrowser.js
  tgui/packages/tgui/interfaces/TicketMessenger.js
  tgui/packages/tgui/public/tgui.bundle.css
  tgui/packages/tgui/public/tgui.bundle.js
  tgui/packages/tgui/styles/themes/admin.scss
Labels: Administration

#1796 Removes one-time use on holoparasite resetting
  code/modules/guardian/guardian.dm
Labels: Tweak

#1805 More Holoparasite fixes and tweaks
  beestation.dme
  code/__DEFINES/components.dm
  code/__DEFINES/maps.dm
  code/__HELPERS/level_traits.dm
  code/modules/guardian/abilities/special/pocket.dm
  code/modules/guardian/guardian.dm
  code/modules/guardian/guardianbuilder.dm
  code/modules/guardian/standarrow.dm
  code/modules/mob/living/living.dm
  icons/mob/screen_alert.dmi
Labels: Balance/Rebalance, Fix, Tweak

#1821 More valid keys
  code/modules/keybindings/bindings_client.dm
Labels: Administration, Fix

#1820 Nerfs healing holoparasites
  code/modules/guardian/abilities/major/healing.dm
Labels: Balance/Rebalance

#1809 Makes Mimes better
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/PDA_types.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/modules/client/asset_cache.dm
  code/modules/emoji/emoji_parse.dm
  code/modules/spells/spell_types/mime.dm
  icons/pda_icons/pda_emoji.png
Labels: Feature, Tweak, Vote Passed

#1826 Tgui ticket hotfix
  code/modules/admin/verbs/adminhelp.dm
Labels: Fix

#1830 Oopsie Woopsie
  code/modules/admin/verbs/debug.dm
Labels: Fix, server

#1832 Should fix the revolution issue
  code/game/gamemodes/game_mode.dm
  code/modules/antagonists/ashwalker/ashwalker.dm
Labels: Fix

#1834 Bags of Holding can now bomb again and can't be used for infinite storage
  code/game/objects/items/storage/backpack.dm
Labels: Fix

#1837 Title Screens
  config/Sage/title_screens/images/bee_wars.dmi
  config/Sage/title_screens/images/delaminating_issues.dmi
  config/Sage/title_screens/images/extended.dmi
  config/Sage/title_screens/images/how_can_i_help_you.dmi
  config/Sage/title_screens/images/janitor.dmi
  config/Sage/title_screens/images/singuloose.dmi
  config/Sage/title_screens/images/title2.dmi
  config/Sage/title_screens/images/title4.dmi
  config/Sage/title_screens/images/title5.dmi
  config/Sage/title_screens/images/vaporwave.dmi
  config/title_screens/images/delaminating_issues.dmi
  config/title_screens/images/extended.dmi
  config/title_screens/images/greytide_worldwide.dmi
  config/title_screens/images/janitor.dmi
  config/title_screens/images/meta_boiz.dmi
  config/title_screens/images/singuloose.dmi
  config/title_screens/images/title2.dmi
  config/title_screens/images/title4.dmi
  config/title_screens/images/title5.dmi
  config/title_screens/images/vaporwave.dmi
Labels: Feature

#1840 bag of holding fix
  code/datums/components/storage/concrete/bag_of_holding.dm
Labels: Fix

#1842 Removes game and server crashing stand power
  _maps/templates/pocket_dimension.dmm
  beestation.dme
  code/modules/guardian/abilities/special/pocket.dm
Labels: Removal

#1843 Reduces the space ruin budget
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Tweak

#1839 DMAPI 5.2
  code/__DEFINES/tgs.dm
  code/modules/tgs/core/core.dm
  code/modules/tgs/core/datum.dm
  code/modules/tgs/v3210/api.dm
  code/modules/tgs/v4/api.dm
  code/modules/tgs/v5/_defines.dm
  code/modules/tgs/v5/api.dm
  code/modules/tgs/v5/undef.dm
Labels: Tools, server

#1844 Ports trauma ghostrole fix from au
  code/datums/brain_damage/imaginary_friend.dm
  code/datums/brain_damage/split_personality.dm
Labels: Fix

#1852 Right to be hidden
  SQL/beestation_schema.sql
  SQL/database_changelog.txt
  code/__DEFINES/subsystems.dm
  code/modules/admin/sql_ban_system.dm
Labels: sql

#1853 Removes clickable links from OOC
  code/modules/client/verbs/ooc.dm
Labels: Administration, Removal

#1851 Fix PDA double messages
  code/game/objects/items/devices/PDA/PDA.dm
Labels: Fix

#1858 Fixes devil gamemode
  code/game/gamemodes/devil/devil_game_mode.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
Labels: Tweak

#1855 Ports Crew Transfer Vote from AuStation
  beestation.dme
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/autotransfer.dm
  code/controllers/subsystem/vote.dm
  config/Sage/config.txt
  config/config.txt
Labels: Feature

#1860 Disables Midround OOC for Sage
  config/Sage/game_options.txt
Labels: Config Update

#1863 Fixes shooting while in softcrit
  code/modules/projectiles/autofire.dm
Labels: Fix

#1861 Radios in both barbershops are now actual radios instead of implants
  _maps/RandomRooms/10x5/sk_rdm011_barbershop.dmm
  _maps/RandomRooms/5x4/sk_rdm090_tinybarbershop.dmm
Labels: Fix

#1864 Couple tiny fixes
  code/controllers/subsystem/title.dm
  code/game/objects/items/devices/compressionkit.dm
  code/modules/paperwork/paper.dm
  code/modules/research/server.dm
Labels: Fix

#1815 i dunno what to title this
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Fix

#1866 Fixes LOOC on Sage
  code/controllers/configuration/entries/game_options.dm
  code/modules/client/verbs/looc.dm
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Config Update, Fix

#1868 [s] Autofire magdump fix
  code/modules/projectiles/autofire.dm
  code/modules/projectiles/gun.dm
Labels: Fix

#1867 Shuttles save like shuttles now
  code/modules/shuttle/shuttle.dm
Labels: Fix

#1859 Space is cool, so should be the suits: spacesuits set resprite
  code/modules/clothing/spacesuits/miscellaneous.dm
  icons/mob/head.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, Fix, Needs Vote, Sprites

#1827 adds a few chems to the abductor chem dispenser
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
Labels: Needs Rebalancing, Needs Vote

#1865 Skinsuits
  beestation.dme
  code/__DEFINES/atmospherics.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, Vote Passed, test merged

#1875 Faster-Than-Liver from FTL13
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  icons/obj/drinks.dmi
Labels: Feature, Sprites

#1879 delta fixes, comments out a room causing runtimes
  _maps/map_files/Deltastation/DeltaStation2.dmm
  code/modules/mapping/random_rooms.dm
Labels: Fix, Removal

#1874 Adds multi-z support for pinpointers [NSV13 port]
  code/game/objects/items/pinpointer.dm
  icons/obj/device.dmi
Labels: Feature, Sprites

#1869 New contribution guidelines
  .github/CONTRIBUTING.md
Labels: Feature, Removal

#1878 Fixes the second worst shuttle
  code/modules/shuttle/shuttle.dm
Labels: Fix

#1886 Headspiders IV: Actually balanced edition
  code/modules/antagonists/changeling/changeling.dm
  code/modules/mob/living/simple_animal/hostile/headcrab.dm
Labels: Balance/Rebalance, Feature

#1885 Ashwalkers can no longer use shuttle consoles
  code/modules/shuttle/computer.dm
Labels: Tweak

#1877 Sanitation Update
  _maps/RandomRuins/SpaceRuins/crashedship.dmm
  _maps/RandomZLevels/Academy.dmm
  code/datums/components/crafting/recipes.dm
  code/datums/traits/negative.dm
  code/game/objects/items/mop.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/twohanded.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/janicart.dm
  code/modules/cargo/packs.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/opo/mop.dm
  code/modules/research/designs/autolathe_designs.dm
  code/modules/vending/wardrobes.dm
  icons/mob/inhands/equipment/custodial_lefthand.dmi
  icons/mob/inhands/equipment/custodial_righthand.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/janitor.dmi
Labels: Feature, Sprites, Tweak

#1870 Nitryl gas reaction now uses pluoxium as a catalyst
  code/modules/atmospherics/gasmixtures/reactions.dm
Labels: Feature, Needs Vote, Removal
