Repository BeeStation/BeeStation-Hornet, pull requests merged in 2020-11, with the labels that each got.

#2865 Patches instagib tablestacking
  code/game/objects/structures/table_frames.dm
Labels: Fix

#2857 Paramedics finally get EVA access
  code/modules/jobs/job_types/emt.dm
Labels: Feature, Vote Passed

#2767 Adds Showers to Engie
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit, Tweak

#2768 Changeling Ability - Limbsnake
  code/modules/antagonists/changeling/powers/regenerate.dm
  icons/mob/actions/actions_changeling.dmi
Labels: Feature

#2866 EMPs now randomize suit sensors if they're on (#44398)
  code/modules/clothing/under/_under.dm
Labels: Feature

#2503 [PORT] Makes rads glow, buffs rad goggles
  code/__DEFINES/layers.dm
  code/datums/components/radioactive.dm
  code/datums/radiation_wave.dm
  code/game/atoms.dm
  code/modules/clothing/glasses/engine_goggles.dm
Labels: Feature, Fix, Tweak

#2854 Allows felinids to laugh.
  code/modules/mob/living/emote.dm
Labels: Feature

#2870 Adds pensive
  icons/emoji.dmi
Labels: Feature

#2844 Fixes stealthmode showing your ckey
  code/modules/admin/verbs/adminpm.dm
Labels: Administration

#2458 Bridge and other high security areas now start with reinforced airlocks
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/machinery/doors/airlock_types.dm
Labels: Tweak, Vote Passed

#2522 Brig physician tweaks
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/jobs/job_types/brigphys.dm
Labels: Feature, Tweak

#2650 Removes syndicate encryption key from incursion mode, brings back 40 TC box
  code/modules/uplink/uplink_items.dm
Labels: Tweak

#2872 fixes "The Mad's labcoat"
  icons/mob/suit.dmi
Labels: Fix

#2668 Increased View Width 17x15
  code/__HELPERS/view.dm
  code/_onclick/hud/_defines.dm
  code/controllers/configuration/entries/general.dm
  code/datums/components/mirage_border.dm
  code/datums/explosion.dm
  code/datums/view.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/items/twohanded.dm
  code/game/sound.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/guardian/guardian.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/login.dm
  code/world.dm
  config/Sage/config.txt
  config/config.txt
Labels: Code Improvement, Fix, Needs Testmerge, Tweak, Vote Passed

#2876 Bumps the savefile version to 31 enabling auto_fit_viewport by default
  code/modules/client/preferences_savefile.dm
Labels: Tweak

#2361 Factstationio - Autolathe Automation / UI improvement
  code/datums/wires/autolathe.dm
  code/game/machinery/autolathe.dm
  tgui/packages/tgui/interfaces/ModularFabricator.js
  tgui/packages/tgui/styles/interfaces/ModularFabricator.scss
  tgui/packages/tgui/styles/main.scss
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
Labels: TGUI-Changes, Vote Passed

#2880 [s] Ports gulag fix
  code/modules/mining/laborcamp/laborstacker.dm
Labels: Fix

#2873 [PORT] Advanced explosions
  code/datums/explosion.dm
  code/game/sound.dm
  sound/effects/creak1.ogg
  sound/effects/creak2.ogg
  sound/effects/creak3.ogg
  sound/effects/explosioncreak1.ogg
  sound/effects/explosioncreak2.ogg
Labels: Code Improvement, Needs Testmerge, Tweak, test merged

#2726 The name and job of the announcer are now shown in announcements
  code/__HELPERS/priority_announce.dm
  code/controllers/subsystem/communications.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/requests_console.dm
Labels: Feature, Vote Passed

#2707 Fix assmly GUI not working in TGUI TTV
  code/game/objects/items/devices/transfer_valve.dm
  code/modules/assembly/assembly.dm
Labels: Fix, TGUI-Changes

#2738 standardizes spray stuns
  code/__DEFINES/inventory.dm
  code/game/objects/items/crayons.dm
  code/modules/antagonists/eldritch_cult/eldritch_items.dm
  code/modules/clothing/chameleon.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/hailer.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/spacesuits/_spacesuits.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/suits/bio.dm
  code/modules/clothing/suits/utility.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
Labels: Code Improvement, Fix

#2837 Simplifies crimes + hud clean up
  code/__DEFINES/traits.dm
  code/datums/datacore.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/computer/warrant.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/silicon/pai/software.dm
  code/modules/paperwork/filingcabinet.dm
  code/modules/surgery/organs/augments_eyes.dm
Labels: Code Improvement, Feature, Merge Conflict, Needs Testmerge, Refactor, Removal, Tweak, test merged

#2614 Fixes Fatal Flaw of Fusion While Making It Not That Boring
  code/__DEFINES/reactions.dm
  code/modules/atmospherics/gasmixtures/reactions.dm
  code/modules/projectiles/projectile/energy/nuclear_particle.dm
Labels: Balance/Rebalance, Code Improvement, Feature, Fix, Refactor, Removal, Tweak, test merged

#2812 Guns no longer use changeNext_move
  code/modules/projectiles/gun.dm
Labels: Tweak

#2790 Borgs no longer get confused after they get flashed/flashbanged
  code/game/objects/items/grenades/flashbang.dm
  code/modules/assembly/flash.dm
Labels: Tweak, Vote Passed

#2784 Updated mining vendor items - diet edition
  code/modules/mining/equipment/explorer_gear.dm
  code/modules/mining/machine_vending.dm
Labels: Feature, Tweak, Vote Passed

#2890 Makes searing tool small sized item.
  code/modules/surgery/tools.dm
Labels: Balance/Rebalance

#2891 Fixes reviving stasis double deathgasp
  code/modules/antagonists/changeling/powers/fakedeath.dm
Labels: Fix

#2886 Flashbang changes 2
  code/game/objects/items/grenades/flashbang.dm
  code/modules/mob/living/carbon/carbon_defense.dm
Labels: Merge Conflict, Tweak

#2808 Refactors cyborg spray bottles, adds cyborg weedspray to janiborgs
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/reagents/reagent_containers/spray.dm
Labels: Feature, Refactor

#2895 People drift through z levels properly now (#52686)
  code/game/turfs/open/space/space.dm
Labels: Fix

#2869 Dynamic Mode Fixes: Take II
  code/__DEFINES/traits.dm
  code/__HELPERS/roundend.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/ticker.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_rulesets.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/revolution/revolution.dm
  code/modules/antagonists/abductor/abductor.dm
  code/modules/antagonists/revolution/revolution.dm
  code/modules/antagonists/wizard/equipment/spellbook.dm
  code/modules/mob/living/carbon/human/death.dm
  config/Sage/dynamic.json
  config/Sage/game_options.txt
  config/dynamic.json
  config/game_options.txt
Labels: Feature, Fix

#2898 Updated RD cloak sprite
  icons/mob/neck.dmi
  icons/obj/clothing/cloaks.dmi
Labels: Tweak, Vote Passed

#2867 More botany logging
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/hydroponics/plant_genes.dm
Labels: Administration

#2803 Space Station 13: Battle Royale.
  beestation.dme
  code/__DEFINES/traits.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/battle_royale.dm
  code/modules/cargo/supplypod.dm
  code/modules/mob/dead/new_player/new_player.dm
Labels: Feature

#2836 Makes integration cogs suppress power warnings.
  code/modules/power/apc.dm
Labels: Tweak

#2838 Replaces syndicate playing cards from maintenance tunnels.
  _maps/RandomRooms/5x4/sk_rdm041_deltagamble.dmm
Labels: Tweak

#2882 Slight shotgun screenshake.
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/guns/ballistic/toy.dm
Labels: Feature

#2911 Probably fixes the statue bug
  code/__HELPERS/view.dm
  code/modules/mob/living/simple_animal/hostile/statue.dm
Labels: Fix

#2919 Game mode overrides no longer change the default mode
  code/controllers/subsystem/vote.dm
  code/modules/admin/topic.dm
Labels: admin

#2913 Adds the crazy hamburger as a new item the chef can make
  code/modules/food_and_drinks/food/snacks_burgers.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_burger.dm
  icons/obj/food/burgerbread.dmi
Labels: Feature, Sprites

#2927 Lets biogenerator make toolbelts.
  code/modules/research/designs/biogenerator_designs.dm
Labels: Feature

#2782 Teratomas are actual antags now
  beestation.dme
  code/__DEFINES/role_preferences.dm
  code/datums/diseases/advance/symptoms/heal.dm
  code/game/gamemodes/objective.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/antagonists/changeling/powers/teratoma.dm
  code/modules/antagonists/changeling/teratoma.dm
  code/modules/antagonists/monkey/monkey.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/transform_procs.dm
Labels: Code Improvement, Feature, Fix, Refactor, Tweak

#2798 Makes stasis beds halt progressions of diseases
  code/datums/diseases/_disease.dm
  code/modules/mob/living/carbon/alien/special/alien_embryo.dm
  code/modules/mob/living/simple_animal/hostile/headcrab.dm
  code/modules/zombie/organs.dm
Labels: Fix, Vote Passed

#2889 fixes VIP
  code/modules/jobs/job_types/gimmick.dm
Labels: Tweak

#2714 Radios now make noises when you use them
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/implants/implant_misc.dm
  sound/effects/radio1.ogg
  sound/effects/radio2.ogg
Labels: Feature, Vote Passed

#2930 Fixes misplaced var that caused abductor lockers to be animated
  code/game/objects/structures/crates_lockers/closets/gimmick.dm
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
Labels: Fix

#2932 Renamed smeltable alloys in the techfab
  code/modules/research/designs/smelting_designs.dm
Labels: Tweak

#2935 Removes SRM-8 missile rack from security autolathe
  code/modules/research/designs/mecha_designs.dm
Labels: Removal

#2934 Some lavaland map qol fixes - science outpost and hermit
  _maps/RandomRuins/LavaRuins/lavaland_surface_hermit.dmm
  _maps/map_files/Mining/Lavaland.dmm
Labels: Tweak

#2826 [PORT] Xeno queens delay the shuttle, and lets them hijack it.
  code/modules/mob/living/carbon/alien/humanoid/queen.dm
  code/modules/shuttle/emergency.dm
Labels: Removal, Tweak, Voting

#2928 Explosions throw things farther and also throw any ungrounded atom, not just mobs and items
  code/datums/explosion.dm
Labels: Tweak

#2924 Round will not end the instant all heretics are dead
  code/game/gamemodes/eldritch_cult/eldritch_cult.dm
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Tweak

#2969 Fixes dynamic bug
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_rulesets.dm
Labels: Fix

#2899 Contractor Balance Changes
  code/game/objects/items/storage/uplink_kits.dm
Labels: Feature, Tweak

#2970 Recyclers will no longer grind raw materials
  code/game/machinery/recycler.dm
Labels: Tweak

#2931 Glass shards can now be crafted by using glass in-hand
  code/game/objects/items/stacks/sheets/glass.dm
Labels: Feature

#2977 Makes radio sounds only play to mobs that are holding them.
  code/game/objects/items/devices/radio/radio.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/mob.dm
Labels: Tweak

#2926 Better Budget Increases
  code/controllers/subsystem/economy.dm
  code/modules/research/techweb/_techweb.dm
Labels: Balance/Rebalance

#2978 Updates the TGS3 json file to remove libmariadb.dll
  .dockerignore
  TGS3.json
Labels: server

#2956 Setting gamemode as default now requires dbranks permission
  code/modules/admin/topic.dm
Labels: Administration

#2917 Adds crate animation
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/crates_lockers/crates/bins.dm
  code/game/objects/structures/crates_lockers/crates/critter.dm
  code/game/objects/structures/crates_lockers/crates/large.dm
  code/modules/mining/abandoned_crates.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  icons/obj/crates.dmi
Labels: Feature

#2654 Removes Exolocomotive Xenomitosis
  beestation.dme
  code/datums/diseases/advance/symptoms/fleshgrowth.dm
  code/datums/diseases/advance/symptoms/macrophage.dm
  code/game/objects/structures/aliens.dm
  code/modules/mob/living/simple_animal/hostile/macrophage.dm
  icons/mob/animal.dmi
  icons/obj/smooth_structures/alien/flesh1.dmi
  icons/obj/smooth_structures/alien/flesh2.dmi
  icons/obj/smooth_structures/alien/flesh3.dmi
  icons/obj/smooth_structures/alien/fleshpolyp.dmi
Labels: Removal

#2915 Prevents the eminence from blocking bullets.
  code/modules/antagonists/clock_cult/mobs/eminence.dm
Labels: Tweak

#2983 Prevents wizards from mindswapping with slaughter demons
  code/modules/spells/spell_types/mind_transfer.dm
Labels: Balance/Rebalance

#2976 fix(AltClick): AltClick on things that use AltClick no longer opens the contens of the turf
  code/game/machinery/airlock_cycle_control.dm
  code/game/machinery/aug_manipulator.dm
  code/game/machinery/cloning.dm
  code/game/machinery/computer/buildandrepair.dm
  code/game/machinery/computer/prisoner/_prisoner.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/devices/sound_synth.dm
  code/game/objects/items/etherealdiscoball.dm
  code/game/objects/items/implants/implantpad.dm
  code/game/objects/items/storage/lockbox.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/morgue.dm
  code/modules/atmospherics/machinery/airalarm.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/atmospherics/machinery/components/binary_devices/passive_gate.dm
  code/modules/atmospherics/machinery/components/binary_devices/pump.dm
  code/modules/atmospherics/machinery/components/binary_devices/volume_pump.dm
  code/modules/atmospherics/machinery/components/trinary_devices/filter.dm
  code/modules/atmospherics/machinery/components/trinary_devices/mixer.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/atmospherics/machinery/components/unary_devices/outlet_injector.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/head/soft_caps.dm
  code/modules/clothing/masks/breath.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/neck/_neck.dm
  code/modules/clothing/suits/toggles.dm
  code/modules/hydroponics/biogenerator.dm
  code/modules/mining/equipment/marker_beacons.dm
  code/modules/mining/machine_redemption.dm
  code/modules/modular_computers/computers/item/computer.dm
  code/modules/modular_computers/computers/item/laptop.dm
  code/modules/power/apc.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/chemistry/machinery/pandemic.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/research/nanites/nanite_remote.dm
  code/modules/shuttle/emergency.dm
  code/modules/vehicles/ridden.dm
Labels: Tweak

#2974 Replica Pod Seeds: Fixes, new features
  code/modules/hydroponics/grown/replicapod.dm
Labels: Feature, Fix

#2985 Really annoying autolathe bug fix
  code/game/machinery/autolathe.dm
Labels: Fix

#2821 Replaces arrival sound
  code/modules/mob/dead/new_player/new_player.dm
  sound/voice/ApproachingTG.ogg
  sound/voice/welcomeBee.ogg
Labels: Feature, Voting

#2988 Cult Buffs - tiles and magic missile
  code/game/turfs/open/floor/plasteel_floor.dm
  code/modules/spells/spell_types/construct_spells.dm
Labels: Balance/Rebalance

#2811 THICKMATERIAL fixes
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#2938 Nar'sie and Rat'var don't like each other
  beestation.dme
  code/modules/antagonists/clock_cult/clockwork_massive.dm
  code/modules/antagonists/clock_cult/helpers/battle_of_the_gods.dm
  code/modules/antagonists/cult/cult.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/power/singularity/narsie.dm
Labels: Feature, Fix, Tweak

#2975 Fixes removing syringes while dead
  code/datums/status_effects/debuffs.dm
Labels: Fix

#2842 Adds 16 random maintenance rooms
  _maps/RandomRooms/10x10/sk_rdm132_conveyorroom.dmm
  _maps/RandomRooms/10x10/sk_rdm141_6sectorsdown.dmm
  _maps/RandomRooms/10x10/sk_rdm142_olddiner.dmm
  _maps/RandomRooms/10x10/sk_rdm143_gamercave.dmm
  _maps/RandomRooms/10x10/sk_rdm144_smallmagician.dmm
  _maps/RandomRooms/10x10/sk_rdm145_ladytesla_altar.dmm
  _maps/RandomRooms/10x10/sk_rdm146_blastdoor_interchange.dmm
  _maps/RandomRooms/10x10/sk_rdm146_botany_apiary.dmm
  _maps/RandomRooms/10x10/sk_rdm147_advbotany.dmm
  _maps/RandomRooms/10x5/sk_rdm149_cratewindow.dmm
  _maps/RandomRooms/10x5/sk_rdm150_smallmedlobby.dmm
  _maps/RandomRooms/10x5/sk_rdm151_ratburger.dmm
  _maps/RandomRooms/10x5/sk_rdm152_geneticsoffice.dmm
  _maps/RandomRooms/10x5/sk_rdm153_hobowithpeter.dmm
  _maps/RandomRooms/10x5/sk_rdm154_butchersden.dmm
  _maps/RandomRooms/10x5/sk_rdm155_punjiconveyor.dmm
  _maps/RandomRooms/10x5/sk_rdm156_oldairlock_interchange.dmm
  code/modules/mapping/random_rooms.dm
Labels: Feature

#3012 Issue #2529 Dexalin Recipe Conflict Fix
  code/modules/reagents/chemistry/recipes/medicine.dm
Labels: Tweak

#3015 Proper QDEL_NULL for looping_sound
  code/game/machinery/fat_sucker.dm
  code/game/objects/items/devices/geiger_counter.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
  code/modules/food_and_drinks/kitchen_machinery/grill.dm
  code/modules/food_and_drinks/kitchen_machinery/microwave.dm
Labels: Fix

#3018 Removes linkify from chat unless its manually turned on in to_chat
  code/modules/admin/verbs/adminpm.dm
  code/modules/admin/verbs/adminsay.dm
  code/modules/client/verbs/ooc.dm
  code/modules/mob/dead/new_player/login.dm
  code/modules/tgchat/to_chat.dm
  tgui/packages/tgui-panel/chat/renderer.js
  tgui/public/tgui-panel.bundle.js
Labels: Fix, THIS IS VERY IMPORTANT

#2946 [Bounty] Crystalized Crossbreeds (Adamantine)
  beestation.dme
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/research/xenobiology/crossbreeding/_misc.dm
  code/modules/research/xenobiology/crossbreeding/_structures.dm
  code/modules/research/xenobiology/crossbreeding/crystalized.dm
  icons/obj/slimecrossing.dmi
Labels: Feature

#3022 Fixes admanantine crossbreeds
  code/modules/research/xenobiology/crossbreeding/_structures.dm
  code/modules/research/xenobiology/crossbreeding/crystalized.dm
Labels: Fix

#3028 [HOTFIX] Stack max amount check
  code/game/objects/items/stacks/stack.dm
Labels: Fix

#3029 fixes some bugs with adamantines
  code/modules/research/xenobiology/crossbreeding/_structures.dm
  code/modules/research/xenobiology/crossbreeding/crystalized.dm
Labels: Fix

#3001 [GOON] Mob properties
  beestation.dme
  code/__DEFINES/_mob_properties.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
Labels: Code Improvement, Port

#3035 [s] XSS via invalid keypress protection
  code/modules/keybindings/bindings_client.dm
Labels: security

#3036 [PORT] restart votes check for deadmins
  code/controllers/subsystem/vote.dm
Labels: Administration

#2862 Service Speciality Modules, but it's working and tested
  code/game/objects/items/kitchen.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/game/objects/items/stacks/tiles/light.dm
  code/game/objects/items/toys.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/reagents/reagent_containers/borghydro.dm
  code/modules/research/designs/mechfabricator_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature

#2680 Sound fading subsystem, ambience fading.
  beestation.dme
  code/controllers/subsystem/ambience.dm
  code/controllers/subsystem/sound.dm
  code/modules/client/client_defines.dm
  code/modules/client/preferences_toggles.dm
Labels: Feature

#2834 Fixes fucking floors
  icons/turf/floors.dmi
Labels: Feature, Sprites

#2875 Fixes Obsessed photo objective
  code/modules/antagonists/creep/creep.dm
Labels: Fix, Tweak

#2914 fixes chapels mail and fixes mining disposals
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Fix, Tweak

#2920 Make dangerous shuttles unbuyable + emags & hacking
  code/controllers/subsystem/mapping.dm
  code/datums/shuttles.dm
  code/game/machinery/computer/communications.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  config/Sage/shuttles_illegal.txt
  config/Sage/shuttles_unbuyable.txt
  config/shuttles_illegal.txt
  config/shuttles_unbuyable.txt
Labels: Feature, Tweak

#3037 Removes Skewium
  code/modules/cargo/bounties/reagent.dm
  code/modules/mob/living/simple_animal/hostile/floor_cluwne.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/reagents/chemistry/recipes/toxins.dm
  strings/cas_white.txt
Labels: Removal

#3039 Adds a craftable charcoal pen
  code/__DEFINES/misc.dm
  code/modules/paperwork/pen.dm
  icons/obj/bureaucracy.dmi
Labels: Feature

#2843 [PORT] Blob Minor Buffs
  code/datums/saymode.dm
  code/modules/antagonists/blob/blob_mobs.dm
  code/modules/antagonists/blob/overmind.dm
  code/modules/antagonists/blob/powers.dm
  code/modules/antagonists/blob/structures/core.dm
  code/modules/antagonists/blob/structures/factory.dm
  code/modules/antagonists/blob/structures/node.dm
  code/modules/antagonists/blob/structures/resource.dm
Labels: Balance/Rebalance, Feature, Tweak

#3005 Removes monkey from rotation(again)
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Config Update, Vote Passed

#3043 Adds coordinate logging to admin spawn commands
  code/modules/admin/topic.dm
Labels: Administration, Tweak
