Repository BeeStation/BeeStation-Hornet, pull requests merged in 2020-09, with the labels that each got.

#2362 gives engi borgs a holofan projector
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Feature, Vote Passed

#2303 [Port] Animate pointing
  code/modules/mob/mob.dm
Labels: Feature, Vote Passed

#2360 Comms Agent Starts With A Paper Containing Comms Frequencies
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  code/modules/ruins/lavalandruin_code/syndicate_base.dm
Labels: Feature

#2333 Syndie kit lootbox
  code/modules/uplink/uplink_items.dm
Labels: Feature, Fix

#2373 Ports "Bees can now vent crawl"
  code/modules/mob/living/simple_animal/hostile/bees.dm
Labels: Feature

#2067 Adds origami
  beestation.dme
  code/game/objects/items/granters.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/paperwork/origami.dm
  code/modules/paperwork/paperplane.dm
  icons/obj/bureaucracy.dmi
Labels: Feature, Needs Vote

#2371 Adds plungers to chem closets
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
Labels: Feature

#2374 Makes scrubbers filter BZ out of the air by default.
  code/modules/atmospherics/machinery/airalarm.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
Labels: Tweak

#2376 Oversight in IAA code that prevents nonHuman (AI) IAAs from completing their Escape objectives
  code/modules/antagonists/traitor/IAA/internal_affairs.dm
Labels: Fix

#2330 Observers no longer highlight items they hover over
  code/game/objects/items.dm
Labels: Fix

#2329 SLOWS_IN_HAND fix
  code/game/objects/items.dm
Labels: Fix

#2240 Electric razor and wig added to chameleon kit
  code/game/objects/items/storage/uplink_kits.dm
Labels: Feature

#2377 Makes the click button sound effect not terrible.
  code/_onclick/hud/action_button.dm
Labels: Tweak

#2382 Defibrilators now snatch ghosts from the world of the dead.
  code/game/objects/items/defib.dm
  code/modules/surgery/advanced/revival.dm
Labels: Tweak, Vote Passed

#2178 Fixes ethereal charging
  code/modules/power/apc.dm
  code/modules/power/cell.dm
  code/modules/power/lighting.dm
Labels: Fix

#2388 paper wizard den fastmos fix.
  _maps/RandomRuins/SpaceRuins/originalcontent.dmm
Labels: Fix

#2383 Punpun
  code/modules/mob/living/carbon/monkey/punpun.dm
Labels: Tweak

#2385 Ports "Shotguns blow people away at point blank"
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/guns/ballistic/toy.dm
Labels: Feature

#2342 Robo life quality improvement
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/modules/vending/wardrobes.dm
Labels: Feature

#2285 Improves Life again
  code/controllers/subsystem/mobs.dm
  code/modules/mob/living/life.dm
Labels: Code Improvement, Needs Testmerge, Untested

#2400 Updates debug outfit and ports omnitool
  beestation.dme
  code/game/objects/items/RCD.dm
  code/game/objects/items/debug_items.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/outfits/standard.dm
Labels: Balance/Rebalance, Feature

#2405 Adds a fire that doesn't require oxygen to ashwalker lavaland base
  _maps/RandomRuins/LavaRuins/lavaland_surface_ash_walker1.dmm
  code/modules/hydroponics/grown/towercap.dm
Labels: Fix

#2129 Phobia Rework
  code/__DEFINES/movespeed_modification.dm
  code/datums/brain_damage/phobia.dm
Labels: Tweak, Vote Passed

#2036 Makes mindshield block cult stuns instead
  code/modules/antagonists/cult/blood_magic.dm
Labels: Tweak

#2386 new shit tweak (like clockwork)
  code/datums/diseases/advance/symptoms/clockwork.dm
  code/datums/diseases/advance/symptoms/fleshgrowth.dm
  code/datums/diseases/advance/symptoms/heal.dm
  code/modules/mob/living/simple_animal/hostile/macrophage.dm
  icons/mob/animal.dmi
  icons/mob/human_parts.dmi
Labels: Feature, Fix, Sprites, Tweak

#2394 nerfs organ decay
  code/__DEFINES/DNA.dm
Labels: Tweak, Untested

#2412 Fixes a bug with cargo not selling the contents of anchored objects
  code/modules/cargo/exports.dm
  code/modules/shuttle/supply.dm
Labels: Fix, THIS IS VERY IMPORTANT

#2229 [Port] Non temp workaround for admins matching stickybans because of a byond bug.
  beestation.dme
  code/_globalvars/lists/admin.dm
  code/controllers/subsystem/stickyban.dm
  code/modules/admin/IsBanned.dm
  code/modules/client/client_procs.dm
Labels: Triaged

#2406 Fixes the default zone_selected from null to the chest
  code/modules/mob/mob_defines.dm
Labels: Fix

#2419 Fixing origami folding
  code/modules/paperwork/origami.dm
Labels: Fix

#2241 Fixes sec belt and webbing storage regression
  code/game/objects/items/storage/belt.dm
Labels: Fix, Vote Passed

#2172 Improves Boxstation medbay
  _maps/map_files/BoxStation/BoxStation.dmm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
Labels: Feature, Needs Testmerge, Removal, Vote Passed

#2446 Ghosts can't order stuff from the express cargo console anymore
  code/modules/cargo/expressconsole.dm
Labels: Fix

#2439 Fixes infinite spraycans
  code/game/objects/items/crayons.dm
Labels: Fix

#2448 Adds severity to the pandemic UI
  code/datums/diseases/advance/advance.dm
  code/modules/reagents/chemistry/machinery/pandemic.dm
  tgui/packages/tgui/interfaces/Pandemic.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Feature

#2222 ports tg # 46423
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
  code/modules/research/xenobiology/crossbreeding/regenerative.dm
Labels: Tweak, Vote Passed

#2393 fast zombies count as dead
  code/__HELPERS/game.dm
Labels: Fix, Untested

#2391 vehicles no longer block projectiles
  code/modules/vehicles/_vehicle.dm
  code/modules/vehicles/sealed.dm
Labels: Tweak, Untested

#2450 The old research station ghost role now actually has a title
  code/game/objects/structures/ghost_role_spawners.dm
Labels: Fix

#2462 Fixes multiple for-loop errors detected by DreamChecker
  code/datums/mutations.dm
  code/game/objects/obj_defense.dm
  code/modules/recycling/disposal/bin.dm
Labels: Fix

#2411 Synthflesh recipe now has silver sulfadizine in it.
  code/modules/reagents/chemistry/recipes/medicine.dm
Labels: Balance/Rebalance, Needs Vote

#2430 Increases Projectile Speed
  code/modules/projectiles/projectile.dm
Labels: Needs Vote, Tweak

#2445 Changes felinid diet to be more like a cat's and less like a human's
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
Labels: Feature, Tweak

#2470 Updated HoS cloak sprite
  icons/mob/neck.dmi
  icons/obj/clothing/cloaks.dmi
Labels: Needs Vote, Tweak

#2456 You can now recolo(u)r lightbulbs (#44122)
  code/modules/power/lighting.dm
Labels: Feature

#2481 pAI Hotfix! (Is that what I call it? Fuck it that's the name now)
  code/modules/mob/living/silicon/pai/pai.dm
  icons/mob/pai.dmi
Labels: Feature, Fix, Sprites

#2452 Recharging Station Crate
  code/modules/cargo/packs.dm
Labels: Feature

#2451 Replaces the firelocks with windoors in the public garden on MetaStation
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Tweak

#2483 More Turf Decals
  code/game/objects/effects/decals/turfdecal/markings.dm
  code/game/objects/effects/decals/turfdecal/tilecoloring.dm
  icons/turf/decals.dmi
Labels: Feature, Sprites, Tweak

#2468 Removes broodmothers from gold slime pool
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
Labels: Removal

#2467 Adds immersion smite
  beestation.dme
  code/__DEFINES/admin.dm
  code/__DEFINES/components.dm
  code/datums/components/manual_blinking.dm
  code/datums/components/manual_breathing.dm
  code/modules/admin/secrets.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/emote.dm
  code/modules/surgery/organs/organ_internal.dm
Labels: Feature

#2465 Renames the gps signal of the bubblegum and blood drunk miner to better fit them.
  code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
Labels: Feature, Needs Wiki Changes

#2479 Pet holding update + Walter
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  code/game/machinery/washing_machine.dm
  code/game/objects/structures/beds_chairs/bed.dm
  code/modules/cargo/packs.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_bread.dm
  code/modules/mob/living/inhand_holder.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/pai/pai_shell.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  code/modules/mob/living/simple_animal/friendly/fox.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/friendly/sloth.dm
  icons/mob/pets.dmi
  icons/mob/pets_held.dmi
  icons/mob/pets_held_lh.dmi
  icons/mob/pets_held_rh.dmi
Labels: Feature

#2434 nerfs toe stubbing
  code/game/objects/structures/tables_racks.dm
Labels: Balance/Rebalance

#2442 Action movie explosions
  code/datums/explosion.dm
  code/game/objects/items.dm
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Balance/Rebalance

#2457 Increases ATMOSfan max signs to 6
  code/game/objects/items/holosign_creator.dm
Labels: Balance/Rebalance, Needs Vote

#2486 Shoulder holsters are now an accessory, not a belt
  _maps/RandomRuins/SpaceRuins/caravanambush.dmm
  code/datums/components/storage/concrete/pockets.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/under/accessories.dm
  code/modules/research/designs/biogenerator_designs.dm
Labels: Tweak

#2464 Adds ID modification logging
  code/__DEFINES/logging.dm
  code/__HELPERS/_logging.dm
  code/_globalvars/logging.dm
  code/controllers/configuration/entries/general.dm
  code/game/machinery/computer/card.dm
  code/game/objects/items/cards_ids.dm
  code/game/world.dm
  code/modules/mining/machine_vending.dm
  code/modules/modular_computers/file_system/programs/card.dm
  config/Sage/config.txt
  config/config.txt
Labels: Config Update, Feature

#2407 Adds lizard scream sound effect
  code/modules/mob/living/carbon/human/emote.dm
  sound/voice/lizard/credits.txt
  sound/voice/lizard/lizard_scream_1.ogg
  sound/voice/lizard/lizard_scream_2.ogg
  sound/voice/lizard/lizard_scream_3.ogg
  sound/voice/lizard/lizard_scream_4.ogg
Labels: Feature, Sound

#2480 Dragnet Beacons
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/objects/items/devices/beacon.dm
  code/modules/projectiles/projectile/energy/net_snare.dm
  code/modules/research/designs/bluespace_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature, Tweak, Vote Passed

#2502 travis runtime
  code/game/objects/structures/tables_racks.dm
Labels: Fix

#2433 misc viro fixes
  code/datums/diseases/advance/symptoms/clockwork.dm
  code/datums/diseases/advance/symptoms/heal.dm
  code/datums/diseases/advance/symptoms/macrophage.dm
  code/game/objects/items/devices/antivirus.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/simple_animal/hostile/macrophage.dm
  icons/mob/human_parts.dmi
Labels: Fix

#2506 [Heretics] Day 1 bugfixing patch
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Fix

#2508 Super quick pai hotfix
  code/modules/mob/living/silicon/pai/pai.dm
Labels: Fix

#2228 Multilingual Trait Addition
  code/__DEFINES/language.dm
  code/__DEFINES/traits.dm
  code/datums/traits/good.dm
Labels: Code Improvement, Feature

#2507 Fixes eating deepfried pets
  code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
Labels: Removal, Tweak

#2535 APMs now autoclaim tickets
  code/modules/admin/verbs/adminpm.dm
Labels: Administration

#2441 Disables the Gateway
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Config Update, ike like

#2524 [PORT] arcade carpet and more arcade state icons.
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/turfs/open/floor/fancy_floor.dm
  icons/obj/computer.dmi
  icons/obj/tiles.dmi
  icons/turf/floors.dmi
Labels: Feature

#2550 Fixes bugs from the carpet port and adds it to cargo.
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/turfs/open/floor/fancy_floor.dm
  code/modules/cargo/packs.dm
Labels: Feature, Fix

#2544 Fixes is_valid_target not being called
  code/game/gamemodes/objective.dm
Labels: Fix

#2534 Reduces Multilingual quirk's cost from 2 to 1
  code/datums/traits/good.dm
Labels: Balance/Rebalance

#2555 Disables Gangs on Sage/Golden
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Config Update

#2556 Fixes heretics config
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Config Update

#2561 Fixes clockcult reebe map bug
  code/game/machinery/telecomms/machines/relay.dm
Labels: Fix

#2513 Changes the position of the starting game message for players.
  code/controllers/subsystem/ticker.dm
Labels: Tweak

#2557 Rebalancing Foreigner
  code/datums/traits/negative.dm
  code/datums/traits/neutral.dm
Labels: Balance/Rebalance

#2511 (PORT) Recolors the computer circuit boards and machine circuit boards into department-based colors.
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  icons/obj/module.dmi
Labels: Feature, Refactor, Sprites

#2493 Makes mining airlocks more convenient..
  _maps/map_files/Mining/Lavaland.dmm
Labels: Fix, Voting

#2558 Command, QM and Warden now require more playtime hours
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/quartermaster.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/job_types/warden.dm
Labels: Tweak, ike like

#2568 Revert "[Port] Non temp workaround for admins matching stickybans because of a byond bug."
  beestation.dme
  code/_globalvars/lists/admin.dm
  code/controllers/subsystem/stickyban.dm
  code/modules/admin/IsBanned.dm
  code/modules/client/client_procs.dm
Labels: test merged

#2543 fix strtohex and passkeys for circuits
  code/__HELPERS/type2type.dm
Labels: Fix

#2567 The return of qwerty lighting
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas.dm
  code/modules/power/lighting.dm
Labels: Code Improvement, Feature, Voting

#2569 Locks felinids behind paywall
  beestation.dme
  code/__HELPERS/patrons.dm
  code/_onclick/hud/credits.dm
  code/controllers/subsystem/job.dm
  code/modules/admin/IsBanned.dm
  code/modules/client/preferences.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
Labels: Tweak, Voting

#2565 Adds input capping and sanitization where needed
  code/__HELPERS/text.dm
  code/_onclick/hud/movable_screen_objects.dm
  code/controllers/subsystem/pai.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/computer/dna_console.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/magnet.dm
  code/game/machinery/navbeacon.dm
  code/game/machinery/telecomms/computers/message.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/game/objects/items/devices/paicard.dm
  code/game/objects/structures/musician.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/callproc/callproc.dm
  code/modules/admin/create_poll.dm
  code/modules/admin/permissionedit.dm
  code/modules/admin/secrets.dm
  code/modules/admin/stickyban.dm
  code/modules/admin/team_panel.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/deadsay.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/admin/verbs/playsound.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/antagonists/blob/powers.dm
  code/modules/antagonists/wizard/equipment/artefact.dm
  code/modules/cargo/console.dm
  code/modules/client/preferences.dm
  code/modules/events/wizard/madness.dm
  code/modules/guardian/standarrow.dm
  code/modules/integrated_electronics/core/printer.dm
  code/modules/library/lib_machines.dm
  code/modules/mentor/mentor_memo.dm
  code/modules/mentor/mentorpm.dm
  code/modules/mentor/mentorsay.dm
  code/modules/mining/abandoned_crates.dm
  code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/silicon/ai/say.dm
  code/modules/mob/mob_transformation_simple.dm
  code/modules/paperwork/folders.dm
  code/modules/paperwork/paper.dm
  code/modules/photography/photos/photo.dm
  code/modules/procedural_mapping/mapGenerator.dm
  code/modules/reagents/chemistry/machinery/chem_synthesizer.dm
  code/modules/shuttle/spaceship_navigation_beacon.dm
Labels: Config Update, Fix, Needs Testmerge, Untested

#2579 Unfucks cloning
  code/game/objects/items/circuitboards/machine_circuitboards.dm
Labels: Fix

#2515 Random screaming when hurt
  code/modules/mob/living/carbon/human/damage_procs.dm
Labels: Tweak

#2580 Move the race paywall stuff to config
  code/controllers/configuration/entries/game_options.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Config Update, Feature

#2572 Fix to mutation toxins
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Fix

#2589 Emergency clockcult patch, fixes deconversion, removes broadcasting from the hierophant relay.
  code/game/machinery/telecomms/machines/relay.dm
  code/modules/antagonists/clock_cult/clockwork_outfits.dm
  code/modules/antagonists/clock_cult/mobs/clockwork_marauder.dm
  code/modules/antagonists/clock_cult/scriptures/_clockwork_scripture.dm
  code/modules/antagonists/clock_cult/servant_of_ratvar.dm
  code/modules/antagonists/clock_cult/structure/clockwork_structure.dm
Labels: Fix, Removal

#2590 Fixes toy dualsaber injuring clowns
  code/game/objects/items/toys.dm
Labels: Fix

#2592 Reverts and reports colored circuit boards
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  icons/obj/module.dmi
Labels: Feature, Fix

#2584 Allows server operators to dummy out SSBlackbox
  code/controllers/configuration/entries/dbconfig.dm
  code/controllers/subsystem/blackbox.dm
  config/dbconfig.txt
Labels: server
