Repository BeeStation/BeeStation-Hornet, pull requests merged in 2020-02, with the labels that each got.

#1169 Adds Ian Cakehat Sprite
  icons/mob/corgi_head.dmi
Labels: Fix, Sprites

#1174 [PORT] TG - Correct atmos reaction priority. (#48871)
  code/modules/atmospherics/gasmixtures/gas_mixture.dm
  code/modules/atmospherics/gasmixtures/reactions.dm
Labels: Fix, Port, test merged

#1152 Hulk and bath salts now make you immune to stunbatons again
  code/__DEFINES/traits.dm
  code/datums/mutations/hulk.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/mob_movement.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Feature, Needs Vote, Tweak

#1108 [TG Port] Surgery tool refactor
  code/__DEFINES/tools.dm
  code/game/mecha/equipment/tools/mining_tools.dm
  code/game/mecha/equipment/tools/work_tools.dm
  code/game/objects/items/holy_weapons.dm
  code/game/objects/items/melee/energy.dm
  code/game/objects/items/twohanded.dm
  code/game/objects/items/weaponry.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/surgery/advanced/bioware/experimental_dissection.dm
  code/modules/surgery/advanced/brainwashing.dm
  code/modules/surgery/advanced/lobotomy.dm
  code/modules/surgery/advanced/pacification.dm
  code/modules/surgery/advanced/reconstruction.dm
  code/modules/surgery/advanced/viral_bonding.dm
  code/modules/surgery/amputation.dm
  code/modules/surgery/brain_surgery.dm
  code/modules/surgery/core_removal.dm
  code/modules/surgery/eye_surgery.dm
  code/modules/surgery/helpers.dm
  code/modules/surgery/implant_removal.dm
  code/modules/surgery/limb_augmentation.dm
  code/modules/surgery/lipoplasty.dm
  code/modules/surgery/mechanic_steps.dm
  code/modules/surgery/organ_manipulation.dm
  code/modules/surgery/organic_steps.dm
  code/modules/surgery/plastic_surgery.dm
  code/modules/surgery/tools.dm
Labels: DONT MERGE, Needs Vote, Refactor, Tweak, test merged

#1164 Genetics Tweaks
  code/game/machinery/computer/dna_console.dm
Labels: Feature, Needs Vote, Tweak, test merged

#1173 Makes Goliath Cloak fire proof
  code/modules/clothing/suits/cloaks.dm
Labels: Feature

#1178 [BOUNTY] [PORT] Ports Empty Clones from TG
  code/game/machinery/cloning.dm
  code/game/machinery/computer/cloning.dm
Labels: Feature

#1183 Repeated ethereal charging
  code/modules/power/lighting.dm
Labels: Tweak

#1180 You can now set actual objectives to the make everyone traitor option.
  code/modules/admin/secrets.dm
Labels: Administration

#1185 Fixes multiz gravity generation
  beestation.dme
  code/modules/power/gravitygenerator.dm
Labels: Fix

#1175 Adds the Autodoc
  beestation.dme
  code/game/machinery/autodoc.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature, Needs Vote

#1192 Sergei's Map Modernization Project
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit, Tweak

#1191 Fixes multi-z photography (#49287)
  code/modules/photography/camera/camera.dm
Labels: Fix

#1190 Mass antag secret V3
  code/modules/admin/secrets.dm
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/antagonists/blob/blob.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/monkey/monkey.dm
  code/modules/antagonists/ninja/ninja.dm
  code/modules/antagonists/nukeop/nukeop.dm
  code/modules/antagonists/revolution/revolution.dm
  code/modules/antagonists/santa/santa.dm
  code/modules/antagonists/space_dragon/space_dragon.dm
  code/modules/antagonists/survivalist/survivalist.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/antagonists/wizard/wizard.dm
Labels: Administration, Fix

#1196 Autodoc fixes
  code/game/machinery/autodoc.dm
Labels: Fix

#1208 Finger Snapping
  code/modules/mob/living/emote.dm
  sound/misc/fingersnap1.ogg
  sound/misc/fingersnap2.ogg
Labels: Feature, Sound

#1207 Remakes Cyanide
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
Labels: Tweak, Vote Passed

#1204 TG's Got the Pop Factor: The Singing Update (#49063)
  code/__DEFINES/say.dm
  code/game/atoms_movable.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/goonchat/browserassets/css/browserOutput_white.css
  code/modules/language/aphasia.dm
  code/modules/language/beachbum.dm
  code/modules/language/common.dm
  code/modules/language/draconic.dm
  code/modules/language/drone.dm
  code/modules/language/language.dm
  code/modules/language/machine.dm
  code/modules/language/monkey.dm
  code/modules/language/mushroom.dm
  code/modules/language/narsian.dm
  code/modules/language/piratespeak.dm
  code/modules/language/slime.dm
  code/modules/language/swarmer.dm
  code/modules/language/xenocommon.dm
  code/modules/mob/living/say.dm
  code/modules/mob/say.dm
  interface/stylesheet.dm
  strings/names/verbs.txt
Labels: Feature, Vote Passed

#1215 Fixes Taste that have been absent for 5 months.
  code/modules/mob/living/taste.dm
Labels: Fix

#1213 Added captain access requirement for antique laser cases.
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit

#1197 The Ghostbuster kit
  code/game/objects/items/grenades/chem_grenade.dm
  code/game/objects/items/miscellaneous.dm
  code/game/objects/items/storage/belt.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/clothing/under/color.dm
  code/modules/mob/living/carbon/carbon.dm
  icons/mob/eyes.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/clothing/glasses.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, Needs Vote, Sprites

#1188 Adds the PTSD
  code/modules/projectiles/guns/energy/stun.dm
  icons/obj/guns/energy.dmi
Labels: Feature, Needs Vote, Sprites

#1216 Throat slicing intent from harm to grab
  code/datums/components/butchering.dm
Labels: Tweak

#1222 Nice mask bro!
  code/modules/clothing/masks/hailer.dm
Labels: Tweak

#1218 Adds anomaly core activation effects
  code/game/objects/effects/anomalies.dm
  code/modules/assembly/assembly.dm
  code/modules/assembly/signaler.dm
Labels: Feature

#1230 MetaStation medbay was missing wire, preventing medbay storage and security post APC's from charging
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Feature, Map Edit

#1232 Surgery changes (Self surgery, tend wounds, anesthetics do something, nerfed surgery table, buffed abductor table)
  code/modules/surgery/advanced/bioware/vein_threading.dm
  code/modules/surgery/advanced/reconstruction.dm
  code/modules/surgery/advanced/viral_bonding.dm
  code/modules/surgery/amputation.dm
  code/modules/surgery/cavity_implant.dm
  code/modules/surgery/dental_implant.dm
  code/modules/surgery/implant_removal.dm
  code/modules/surgery/organ_manipulation.dm
  code/modules/surgery/prosthetic_replacement.dm
  code/modules/surgery/remove_embedded_object.dm
  code/modules/surgery/surgery.dm
  code/modules/surgery/surgery_step.dm
Labels: Balance/Rebalance, Feature, Tweak

#1227 Ports Superglue and Bluespace Compression device
  beestation.dme
  code/__DEFINES/traits.dm
  code/game/objects/items/devices/compressionkit.dm
  code/game/objects/items/devices/glue.dm
  code/modules/uplink/uplink_items.dm
  icons/obj/tools.dmi
Labels: Feature, Removal, Sprites

#1228 Increases Energy protection on most armor
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/spacesuits/syndi.dm
  code/modules/clothing/suits/armor.dm
Labels: Tweak

#1233 Removes Spirit Board from curators spectral kit
  code/game/objects/items/miscellaneous.dm
Labels: Removal

#1223 Tasers are no longer an instant win
  code/modules/projectiles/projectile/energy/stun.dm
Labels: Balance/Rebalance

#1203 Beeviro part 2: beneficial symptoms, stat rebalance
  beestation.dme
  code/__DEFINES/mobs.dm
  code/datums/diseases/advance/symptoms/beesymptom.dm
  code/datums/diseases/advance/symptoms/choking.dm
  code/datums/diseases/advance/symptoms/dizzy.dm
  code/datums/diseases/advance/symptoms/fire.dm
  code/datums/diseases/advance/symptoms/genetics.dm
  code/datums/diseases/advance/symptoms/hallucigen.dm
  code/datums/diseases/advance/symptoms/heal.dm
  code/datums/diseases/advance/symptoms/narcolepsy.dm
  code/datums/diseases/advance/symptoms/oxygen.dm
  code/datums/diseases/advance/symptoms/skin.dm
  code/datums/diseases/advance/symptoms/sneeze.dm
  code/datums/diseases/advance/symptoms/vision.dm
  code/datums/diseases/advance/symptoms/vomit.dm
  code/datums/diseases/advance/symptoms/weight.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/modules/antagonists/disease/disease_abilities.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  code/modules/surgery/bodyparts/head.dm
  icons/mob/animal_parts.dmi
  icons/mob/monkey.dmi
Labels: Feature, Needs Vote, Removal, Sprites, Tweak

#1239 Updates Extools
  Dockerfile
  byond-extools.dll
Labels: Fix

#1236 Romerol is back
  code/modules/uplink/uplink_items.dm
Labels: Tweak

#1240 Small self surgery fixes and feedback
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/surgery/organ_manipulation.dm
Labels: Fix, Tweak

#1243 Docker updates phase 1
  Dockerfile
  config/admin_nicknames.json
  config/admin_ranks.txt
  config/admins.txt
  dependencies.sh
Labels: Code Improvement, Config Update, enhancement, tooling

#1245 Adds click interactions and extended examine text to heater/freezer port
  code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
Labels: Feature

#1247 PDA cart swapping, eject hotkey and verb; toggle light action button port
  code/datums/action.dm
  code/game/objects/items/devices/PDA/PDA.dm
Labels: Feature, Fix

#1250 Adds actions - attempt 2
  .github/workflows/compile_changelogs.yml
  .github/workflows/docker.yml
  .github/workflows/stale.yml
Labels: GitHub

#1252 Plumbing Icon Fix
  icons/obj/plumbing/plumbers.dmi
Labels: Fix, Sprites

#1238 Synthflesh cloning port
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/machinery/cloning.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
Labels: Map Edit, Tweak

#1256 Defib Rework port
  code/__DEFINES/status_effects.dm
  code/datums/status_effects/debuffs.dm
  code/game/objects/items/defib.dm
  code/modules/mob/status_procs.dm
Labels: Balance/Rebalance, Feature

#1244 Krav Maga rework port
  code/datums/martial/krav_maga.dm
Labels: Balance/Rebalance, Feature

#1214 regenerative core changes (read the damn pr)
  code/__DEFINES/traits.dm
  code/datums/diseases/transformation.dm
  code/datums/status_effects/buffs.dm
  code/modules/mining/equipment/regenerative_core.dm
Labels: Balance/Rebalance, Feature

#1264 Dedicated action for stale issue handling
  .github/workflows/stale_issues.yml
  .github/workflows/stale_prs.yml
Labels: GitHub
