Repository BeeStation/BeeStation-Hornet, pull requests merged in 2020-01, with the labels that each got.

#1083 Brainwash disk and radioactive medical scanner change.
  beestation.dme
  code/modules/uplink/uplink_items.dm
Labels: Tweak, Vote Passed

#1087 "Autophagocytosis Necrosis" can now conditionally create romerol
  code/datums/diseases/advance/symptoms/flesh_eating.dm
Labels: Feature, Vote Passed

#1089 Multitool Examine runtime fix
  code/game/objects/items/devices/multitool.dm
Labels: Fix

#1066 Lowers DeltaStation min pop requirement
  config/Sage/maps.txt
  config/maps.txt
Labels: Config Update, Tweak

#1086 Adds an option to specify a minimum playtime requirement in polls
  SQL/beestation_schema.sql
  SQL/database_changelog.txt
  code/modules/admin/create_poll.dm
  code/modules/jobs/job_exp.dm
  code/modules/mob/dead/new_player/poll.dm
Labels: Feature, sql

#1093 Readds Viral aggressive metabolism
  code/datums/diseases/advance/symptoms/viral.dm
Labels: Feature, Vote Passed

#1098 Adds toy holoparasites
  beestation.dme
  code/game/machinery/computer/arcade.dm
  code/modules/mob/living/simple_animal/guardian/guardian.dm
  code/modules/mob/living/simple_animal/guardian/types/gravity.dm
  code/modules/mob/living/simple_animal/guardian/types/standard.dm
  code/modules/mob/living/simple_animal/guardian/types/toy.dm
  code/modules/uplink/uplink_items.dm
  code/modules/vending/autodrobe.dm
  code/modules/vending/toys.dm
  icons/obj/syringe.dmi
  icons/obj/toy.dmi
Labels: Feature, Sprites, Tweak

#1095 fixes zombie, SBG, alk persp
  code/datums/diseases/advance/symptoms/cockroach.dm
  code/datums/diseases/advance/symptoms/fire.dm
  code/datums/diseases/advance/symptoms/flesh_eating.dm
  code/datums/diseases/advance/symptoms/symptoms.dm
  code/modules/mob/living/death.dm
Labels: Fix

#849 [Sage Only] Ports /tg/ Kilo Station
  _maps/kilostation.json
  _maps/map_files/KiloStation/KiloStation.dmm
  config/Sage/maps.txt
Labels: Config Update, Feature, Map Edit

#1103 Lists number of connected players on Status panel
  code/modules/mob/mob.dm
Labels: Feature

#1097 [PORT] BSA works (with interactions included), minor QoL stuff, Rad Collectors can be upgraded.
  beestation.dme
  code/__DEFINES/components.dm
  code/datums/elements/bsa_blocker.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/gift.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/awaymissions/corpse.dm
  code/modules/power/singularity/narsie.dm
  code/modules/power/singularity/singularity.dm
  code/modules/power/supermatter/supermatter.dm
  code/modules/station_goals/bsa.dm
Labels: Feature, Fix, Needs Testmerge, Tweak

#1007 Space Dolphins from YogStation two
  beestation.dme
  code/modules/events/dolphin_migration.dm
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/dolphin.dm
  icons/mob/animal.dmi
Labels: Feature, Needs Testmerge, Sprites, Vote Passed

#1104 Fugitive fixes & ports
  _maps/shuttles/fugitive_hunter_space_cop.dmm
  _maps/shuttles/hunter_bounty.dmm
  _maps/shuttles/hunter_russian.dmm
  _maps/shuttles/hunter_space_cop.dmm
  _maps/templates/shelter_2.dmm
  beestation.dme
  code/datums/shuttles.dm
  code/game/objects/effects/contraband.dm
  code/game/objects/items/pinpointer.dm
  code/game/objects/structures/fugitive_role_spawners.dm
  code/game/objects/structures/traps.dm
  code/game/objects/structures/watercloset.dm
  code/modules/antagonists/fugitive/fugitive.dm
  code/modules/antagonists/fugitive/fugitive_outfits.dm
  code/modules/antagonists/fugitive/fugitive_ship.dm
  code/modules/antagonists/fugitive/hunter.dm
  code/modules/antagonists/fugitive/old_god.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/events/fugitive_spawning.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/projectiles/ammunition/ballistic/shotgun.dm
  code/modules/projectiles/boxes_magazines/internal/misc.dm
  code/modules/projectiles/boxes_magazines/internal/shotgun.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
  icons/mob/hud.dmi
  icons/mob/mask.dmi
  icons/mob/suit.dmi
  icons/obj/ammo.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/contraband.dmi
  icons/obj/device.dmi
  icons/obj/guns/projectile.dmi
  icons/obj/objects.dmi
  icons/obj/watercloset.dmi
Labels: Feature, Fix, Map Edit, Removal, Sprites, Tweak

#1111 Adds crewsimov as a default law option
  code/datums/ai_laws.dm
Labels: Feature

#1112 ports a thing for ike
  code/__HELPERS/areas.dm
  code/modules/mob/mob_defines.dm
Labels: Tweak

#1110 fail2topic
  beestation.dme
  code/__DEFINES/subsystems.dm
  code/controllers/configuration/configuration.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/fail2topic.dm
  code/game/world.dm
  config/Sage/config.txt
  config/config.txt
  config/topic_rate_limit_whitelist.txt
Labels: Config Update

#1120 Enables extended in Sage config
  config/Sage/game_options.txt
Labels: Config Update

#1122 make local jobbans actually work boys
  code/modules/admin/sql_ban_system.dm
Labels: DONT MERGE, Fix, Needs Testmerge, THIS IS VERY IMPORTANT, admin

#1116 Fixes VOG
  code/modules/surgery/organs/vocal_cords.dm
Labels: Fix

#1094 [Map Tweak] Pubbystation QoL Changes
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit, Tweak

#1114 [BOUNTY] New level 9 symptom
  beestation.dme
  code/datums/diseases/advance/symptoms/heartattack.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/simple_animal/hostile/heart.dm
Labels: Feature

#1115 Makes Carbon Cluwnes work, cluwnemute obtainable
  code/datums/mutations/_combined.dm
  code/datums/mutations/cluwne.dm
  code/game/objects/items/dna_injector.dm
  code/modules/clothing/under/cluwne.dm
  icons/mob/feet.dmi
  icons/mob/mask.dmi
Labels: Sprites, Tweak

#1133 Sage config update
  config/Sage/config.txt
Labels: Config Update

#1134 Fixing sepchems
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/plant_genes.dm
Labels: Fix

#1138 Fixes issue #1031 and stops you from stomping your own face
  code/modules/mob/living/carbon/human/human.dm
Labels: Code Improvement

#1102 Buffs Goliath Cloak and HECK suit/helmet
  code/modules/clothing/suits/cloaks.dm
  code/modules/mining/equipment/explorer_gear.dm
Labels: Balance/Rebalance

#1100 Confusion now only works if running
  code/modules/mob/mob_movement.dm
Labels: Needs Vote, Tweak

#1131 Ling Nerfs
  code/datums/status_effects/buffs.dm
  code/modules/antagonists/changeling/powers/fleshmend.dm
  code/modules/antagonists/changeling/powers/humanform.dm
  code/modules/antagonists/changeling/powers/lesserform.dm
  code/modules/antagonists/changeling/powers/shriek.dm
  code/modules/antagonists/changeling/powers/tiny_prick.dm
Labels: Balance/Rebalance, Needs Rebalancing

#1119 Removes lag 2: Electric Boogaloo
  byond-extools.dll
  code/__DEFINES/_tick.dm
  code/_globalvars/misc.dm
  code/controllers/master.dm
  code/game/world.dm
Labels: Removal

#1127 Adds the Ethereal dance grenade (properly this time)
  beestation.dme
  code/game/objects/items/grenades/discogrenade.dm
  code/modules/uplink/uplink_items.dm
  icons/obj/grenade.dmi
Labels: Balance/Rebalance, Sprites, Tweak

#1139 Nameable plants
  code/modules/hydroponics/hydroponics.dm
  code/modules/hydroponics/seeds.dm
  code/modules/vending/megaseed.dm
Labels: Feature, Fix, Tweak

#1140 add random rooms to the travis map check
  tools/travis/template_dm_generator.py
Labels: Code Improvement, Tools

#1117 Prevents academy wizard from spawning in the wiz den
  code/modules/antagonists/wizard/wizard.dm
Labels: Tweak

#1144 removes the rooms that dont even compile
  _maps/RandomRooms/5x4/electronics.dmm
  _maps/RandomRooms/5x4/surgery.dmm
  code/modules/mapping/random_rooms.dm
Labels: Code Improvement, Map Edit, Removal

#1118 Event changes
  code/modules/events/abductor.dm
  code/modules/events/blob.dm
  code/modules/events/brain_trauma.dm
  code/modules/events/disease_outbreak.dm
  code/modules/events/space_dragon.dm
  code/modules/events/spontaneous_appendicitis.dm
  code/modules/events/wizard/shuffle.dm
Labels: Needs Vote, Tweak

#1128 Random maintenance rooms: Framework
  code/game/objects/effects/spawners/roomspawner.dm
Labels: Feature

#1129 3x3 Maint templates
  _maps/RandomRooms/3x3/sk_rdm001_9storage.dmm
  _maps/RandomRooms/3x3/sk_rdm002_shrine.dmm
  _maps/RandomRooms/3x3/sk_rdm003_plasma.dmm
  _maps/RandomRooms/3x3/sk_rdm004_tanning.dmm
  _maps/RandomRooms/3x3/sk_rdm005_wash.dmm
  _maps/RandomRooms/3x3/sk_rdm006_gibs.dmm
  _maps/RandomRooms/3x3/sk_rdm007_radspill.dmm
  _maps/RandomRooms/3x3/sk_rdm008_2storage.dmm
  _maps/RandomRooms/3x3/sk_rdm009_airstation.dmm
  _maps/RandomRooms/3x3/sk_rdm010_hazmat.dmm
  code/modules/mapping/random_rooms.dm
Labels: Feature, Map Edit

#1145 Ports chem recording code
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
Labels: Feature

#1146 Reduces ethereal dance grenade price
  code/modules/uplink/uplink_items.dm
Labels: Balance/Rebalance

#1125 Enables map rotation, turns off auto map vote
  config/Sage/config.txt
  config/config.txt
Labels: Config Update, Vote Passed

#1147 Buildable IPC parts
  code/game/mecha/mech_fabricator.dm
  code/modules/mob/living/carbon/human/species_types/IPC.dm
  code/modules/research/designs/mechfabricator_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature, Fix

#1143 Traitor Item Rebalance
  code/modules/uplink/uplink_items.dm
Labels: Balance/Rebalance, Needs Vote

#1155 Adds absinthe and triple sec to the serviceborg shaker.
  code/modules/reagents/reagent_containers/borghydro.dm
Labels: Feature, Needs Vote

#1135 tinfoil envirosuit helmet, aka ghetto plasmaman hat
  code/datums/components/crafting/tailoring.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Feature, Sprites, Tweak

#1156 Disables Kilo due to frequent crashes
  config/Sage/maps.txt
Labels: Config Update

#1149 No more baseball bat stunlocks
  code/game/objects/items/weaponry.dm
Labels: Balance/Rebalance, Needs Vote, Tweak

#1162 Service borg shaker refactor
  code/modules/reagents/reagent_containers/borghydro.dm
Labels: Refactor

#1160 Adrenals buffing
  code/game/objects/items/implants/implant_misc.dm
  code/modules/antagonists/changeling/powers/adrenaline.dm
Labels: Needs Vote
