Repository BeeStation/BeeStation-Hornet, pull requests merged in 2020-03, with the labels that each got.

#1265 Adds fluid ducts and plumbing constructors to chem lockers
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
Labels: Feature

#1279 Limited colour-changing crayon sources
  code/datums/diseases/advance/symptoms/skin.dm
  code/game/objects/items/crayons.dm
  code/modules/food_and_drinks/food/snacks_burgers.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/hydroponics/grown/rainbow_bunch.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Removal

#1260 Small QoL Brig additions
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Feature, Map Edit

#1258 Simplemobs fooled by fake death
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Needs Vote, Tweak

#1281 Inhand sprites for bolas port
  code/game/objects/items/handcuffs.dm
  code/modules/antagonists/cult/cult_items.dm
  icons/mob/inhands/weapons/thrown_lefthand.dmi
  icons/mob/inhands/weapons/thrown_righthand.dmi
Labels: Sprites

#1282 [PORT] Makes supermatter melt walls if it finds itself in one (#44068)
  code/modules/power/supermatter/supermatter.dm
Labels: Fix

#1287 Zombie infection chance is lowered by armor port
  code/modules/zombie/items.dm
Labels: Feature

#1255 Fixes bug that made burn tend wounds surgery heal brute instead
  code/modules/surgery/advanced/reconstruction.dm
Labels: Fix

#1267 PDA can now sort by name or job port
  code/__HELPERS/cmp.dm
  code/game/machinery/telecomms/computers/message.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/mob/living/silicon/pai/software.dm
Labels: Feature

#1293 [BOUNTY] Adds Necropolis Seed Symptom
  beestation.dme
  code/__DEFINES/movespeed_modification.dm
  code/datums/diseases/advance/presets.dm
  code/datums/diseases/advance/symptoms/necropolis.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/reagents/reagent_containers/bottle.dm
Labels: Feature

#1291 Fixed issues with SM on Pubby
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit, Removal, Tweak

#1259 beepsky nulls repull
  code/modules/cargo/packs.dm
  code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
Labels: Balance/Rebalance

#1286 Tabling Rework port
  beestation.dme
  code/datums/martial/_martial.dm
  code/datums/martial/cqc.dm
  code/datums/martial/sleeping_carp.dm
  code/datums/mood_events/generic_negative_events.dm
  code/game/objects/structures/tables_racks.dm
  sound/effects/tableheadsmash.ogg
  sound/effects/tableslam.ogg
Labels: Balance/Rebalance, Feature, Sound

#1298 Here we go again (Fixes all necropolis seed issues)
  code/datums/diseases/advance/symptoms/necropolis.dm
Labels: Fix

#1297 Fixes pda sort being reversed
  code/game/objects/items/devices/PDA/PDA.dm
Labels: Fix

#1301 PDA tweaks
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/cart.dm
Labels: Feature, Tweak

#1299 Small numbers tweak for beepskys
  code/modules/cargo/packs.dm
Labels: Tweak

#1304 Adds pipe layers to freezers/heaters
  code/game/machinery/constructable_frame.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
  icons/obj/atmospherics/components/thermomachine.dmi
Labels: Feature, Sprites

#1308 Adds roundstart tips and 3 new abductor objectives.
  strings/abductee_objectives.txt
  strings/sillytips.txt
  strings/tips.txt
Labels: Feature

#1309 New engi/atmos traitor item: Crushing Magboots
  code/modules/clothing/shoes/magboots.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature

#1296 Adds a cargo crate with overpriced synthflesh
  code/modules/cargo/packs.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  icons/obj/drinks.dmi
Labels: Feature, Sprites

#1305 Tanks now tell internal mol
  code/game/objects/items/tanks/tanks.dm
Labels: Feature

#1326 Adds plague doctor costume to ViroDrobe
  code/modules/vending/wardrobes.dm
Labels: Feature

#1313 Alt-click to unlock robots
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
Labels: Tweak

#1319 Adds lavaland tobacco with lipolicide
  _maps/RandomRuins/LavaRuins/lavaland_surface_ash_walker1.dmm
  code/modules/hydroponics/grown/tobacco.dm
  icons/obj/hydroponics/growing.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
Labels: Feature, Map Edit, Sprites

#1321 Adds handholding
  code/modules/mob/living/living.dm
Labels: Feature

#1324 More surgical supplies, plumbing gear, stasis beds and synthflesh
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/shuttles/emergency_asteroid.dmm
  _maps/shuttles/emergency_bar.dmm
  _maps/shuttles/emergency_birdboat.dmm
  _maps/shuttles/emergency_box.dmm
  _maps/shuttles/emergency_cere.dmm
  _maps/shuttles/emergency_clown.dmm
  _maps/shuttles/emergency_delta.dmm
  _maps/shuttles/emergency_donut.dmm
  _maps/shuttles/emergency_goon.dmm
  _maps/shuttles/emergency_kilo.dmm
  _maps/shuttles/emergency_luxury.dmm
  _maps/shuttles/emergency_meta.dmm
  _maps/shuttles/emergency_mini.dmm
  _maps/shuttles/emergency_omega.dmm
  _maps/shuttles/emergency_pubby.dmm
  _maps/shuttles/emergency_raven.dmm
  _maps/shuttles/emergency_russiafightpit.dmm
  _maps/shuttles/emergency_wabbajack.dmm
  _maps/shuttles/emergency_zeta.dmm
  _maps/templates/shelter_1.dmm
  _maps/templates/shelter_2.dmm
  code/game/machinery/Sleeper.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/vending/medical.dm
  code/modules/vending/medical_wall.dm
Labels: Feature, Map Edit

#1205 Brighter and Whiter Lighting
  code/modules/power/lighting.dm
Labels: Tweak

#1303 Reduces riot suit slowdown
  code/modules/clothing/suits/armor.dm
Labels: Balance/Rebalance

#1311 New clown traitor item: Taeclowndo martial art
  beestation.dme
  code/game/objects/items/devices/PDA/PDA_types.dm
  code/modules/clothing/shoes/taeclowndo.dm
  code/modules/food_and_drinks/food/snacks_pie.dm
  code/modules/spells/spell_types/aimed.dm
  code/modules/spells/spell_types/godhand.dm
  code/modules/spells/spell_types/taeclowndo.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature

#1306 Replaces ED-209's dragnet with a disabler
  code/modules/mob/living/simple_animal/bot/construction.dm
  code/modules/mob/living/simple_animal/bot/ed209bot.dm
Labels: Fix, Tweak

#1307 New scientist traitor item: Australian Slime Mutator / Spider Injector
  code/modules/goonchat/browserassets/css/browserOutput_white.css
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes.dm
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature

#1316 New chaplain traitor item: Cult Construct Kit
  code/game/machinery/syndicatebeacon.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature

#1320 Revival is not Repair
  code/modules/surgery/advanced/revival.dm
Labels: Fix

#1323 Liquid electricity tweaks
  code/game/machinery/rechargestation.dm
  code/modules/food_and_drinks/food/snacks/meat.dm
  code/modules/food_and_drinks/food/snacks_burgers.dm
  code/modules/food_and_drinks/food/snacks_cake.dm
  code/modules/food_and_drinks/food/snacks_vend.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
Labels: Feature, Fix, Tweak

#1310 Bottle and Patch dispensers for plumbing.
  beestation.dme
  code/modules/plumbing/plumbers/bottle_dispenser.dm
  code/modules/plumbing/plumbers/patch_dispenser.dm
  tgui-next/packages/tgui/interfaces/BottleDispenser.js
  tgui-next/packages/tgui/interfaces/PatchDispenser.js
  tgui-next/packages/tgui/public/tgui.bundle.js
  tgui-next/packages/tgui/routes.js
  tgui/assets/tgui.js
Labels: Feature, UI

#1167 Fixes potions and spray cans
  code/game/objects/items/crayons.dm
  code/modules/research/xenobiology/crossbreeding/_potions.dm
  code/modules/research/xenobiology/xenobiology.dm
Labels: Fix

#1202 Antag Rep Changes
  code/game/gamemodes/brother/traitor_bro.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/changeling/traitor_chan.dm
  code/game/gamemodes/clock_cult/clock_cult.dm
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/devil/devil_game_mode.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/hivemind/hivemind.dm
  code/game/gamemodes/overthrow/overthrow.dm
  code/game/gamemodes/revolution/revolution.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/gamemodes/wizard/wizard.dm
Labels: Needs Testmerge, Needs Vote

#1285 v2 Adds Tactical Breaching Shotguns and Grenade Launchers port
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/objects/items/storage/boxes.dm
  code/modules/projectiles/ammunition/ballistic/shotgun.dm
  code/modules/projectiles/boxes_magazines/external/shotgun.dm
  code/modules/projectiles/boxes_magazines/internal/shotgun.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/uplink/uplink_items.dm
  icons/obj/ammo.dmi
  icons/obj/guns/projectile.dmi
  icons/obj/storage.dmi
Labels: Feature, Map Edit, Sprites

#1181 Grants Xeno impregnation immunity to Abductors, Androids, IPCs, and Skeletons
  code/__DEFINES/traits.dm
  code/game/objects/items/body_egg.dm
  code/modules/mob/living/carbon/alien/organs.dm
  code/modules/mob/living/carbon/alien/special/facehugger.dm
  code/modules/mob/living/carbon/human/species_types/IPC.dm
  code/modules/mob/living/carbon/human/species_types/abductors.dm
  code/modules/mob/living/carbon/human/species_types/android.dm
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
Labels: Balance/Rebalance, Feature

#1334 [Port][s] Fixes XSS Exploit Defeating Sanitization of Any String in Goonchat
  code/modules/goonchat/browserassets/js/browserOutput.js
Labels: Fix, security

#1317 Pestle is now made of regular metal
  code/game/objects/items/stacks/sheets/sheet_types.dm
Labels: Tweak

#1336 random reagent changes repull
  code/modules/antagonists/blob/blobstrains/_reagent.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
  code/modules/reagents/reagent_containers/pill.dm
Labels: Balance/Rebalance, Tweak

#1339 Fixed virodrobe contraband being empty
  code/modules/vending/wardrobes.dm
Labels: Fix

#1315 Reduces the stun on tourettes
  code/datums/mutations/body.dm
Labels: Balance/Rebalance

#1294 v2 Tend Wounds buffs and related tweaks port
  beestation.dme
  code/__DEFINES/traits.dm
  code/game/machinery/computer/Operating.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/stasis.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  code/modules/mob/mob.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/advanced/bioware/ligament_hook.dm
  code/modules/surgery/advanced/bioware/ligament_reinforcement.dm
  code/modules/surgery/advanced/bioware/nerve_grounding.dm
  code/modules/surgery/advanced/bioware/nerve_splicing.dm
  code/modules/surgery/advanced/bioware/vein_threading.dm
  code/modules/surgery/advanced/brainwashing.dm
  code/modules/surgery/advanced/lobotomy.dm
  code/modules/surgery/advanced/necrotic_revival.dm
  code/modules/surgery/advanced/pacification.dm
  code/modules/surgery/advanced/reconstruction.dm
  code/modules/surgery/advanced/revival.dm
  code/modules/surgery/advanced/viral_bonding.dm
  code/modules/surgery/amputation.dm
  code/modules/surgery/brain_surgery.dm
  code/modules/surgery/cavity_implant.dm
  code/modules/surgery/core_removal.dm
  code/modules/surgery/dental_implant.dm
  code/modules/surgery/eye_surgery.dm
  code/modules/surgery/healing.dm
  code/modules/surgery/implant_removal.dm
  code/modules/surgery/limb_augmentation.dm
  code/modules/surgery/lipoplasty.dm
  code/modules/surgery/mechanic_steps.dm
  code/modules/surgery/organ_manipulation.dm
  code/modules/surgery/organic_steps.dm
  code/modules/surgery/plastic_surgery.dm
  code/modules/surgery/prosthetic_replacement.dm
  code/modules/surgery/remove_embedded_object.dm
  code/modules/surgery/surgery.dm
  code/modules/surgery/surgery_step.dm
Labels: Balance/Rebalance, Code Improvement, Feature, Fix, Removal, Tweak, test merged

#1344 Removes the unused global_ban parameter from the unban panel + fixes page number formatting
  code/modules/admin/sql_ban_system.dm
Labels: Administration, test merged

#1343 Adds location information to bans
  code/modules/admin/IsBanned.dm
  code/modules/admin/sql_ban_system.dm
Labels: Administration

#1349 RCD and belt related tweaks
  code/game/machinery/doors/firedoor.dm
  code/game/objects/items/RCD.dm
  code/game/objects/items/RPD.dm
  code/game/objects/items/storage/bags.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/structures/door_assembly.dm
  code/modules/research/designs/autolathe_designs.dm
  code/modules/research/designs/tool_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/organs/augments_arms.dm
  code/modules/surgery/organs/liver.dm
  code/modules/surgery/organs/lungs.dm
  code/modules/surgery/organs/stomach.dm
Labels: Balance/Rebalance, Feature, Tweak

#1342 [Port] Fixes bugs in the mc related to combos of SS_BACKGROUND and other flags
  code/__DEFINES/MC.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
Labels: Port

#1330 Motorised wheelchairs
  beestation.dme
  code/datums/components/crafting/recipes.dm
  code/modules/vehicles/motorized_wheelchair.dm
  code/modules/vehicles/wheelchair.dm
Labels: Feature

#1366 Auto profile port
  beestation.dme
  code/__DEFINES/profile.dm
  code/__DEFINES/subsystems.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/profiler.dm
  code/game/world.dm
  code/modules/admin/verbs/debug.dm
  config/config.txt
Labels: Config Update, Feature

#1372 Minor TGUI Fixes
  code/modules/reagents/chemistry/machinery/chem_master.dm
  tgui-next/packages/tgui/interfaces/Cargo.js
  tgui-next/packages/tgui/interfaces/CrewConsole.js
  tgui-next/packages/tgui/public/tgui.bundle.js
  tgui/assets/tgui.js
Labels: Fix, Port, UI

#1392 Fixes Sleepers again
  code/game/machinery/Sleeper.dm
Labels: Fix

#1384 he monke
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Config Update, Feature, Needs Vote

#1385 Fixes Pubby medbay and Delta gear room access
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Fix, Map Edit, Needs Vote

#1377 Tripled the amount of starting monkeys in jungle fever
  code/game/gamemodes/monkey/monkey.dm
Labels: Balance/Rebalance, Needs Vote

#1352 Adds flashproofing to CMO hardsuit
  code/game/machinery/suit_storage_unit.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
Labels: Tweak, Vote Passed

#1395 Adminbus-only toxoplasmosis
  code/datums/diseases/_disease.dm
  code/datums/diseases/transformation.dm
  code/modules/mob/living/carbon/say.dm
  code/modules/reagents/reagent_containers/bottle.dm
  strings/owo_talk.json
Labels: Feature

#1397 Hepatectomy Surgery
  beestation.dme
  code/modules/surgery/hepatectomy.dm
Labels: Feature

#1393 Fixes health scanners
  code/game/objects/items/devices/scanners.dm
Labels: Fix

#1391 Fixed pipes on Delta
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Fix, Map Edit

#1335 Fixes stasis beds not having a surgery success probability
  code/modules/surgery/surgery.dm
Labels: Fix

#1348 Tasers no longer have stacking confusion
  code/modules/projectiles/projectile/energy/stun.dm
Labels: Balance/Rebalance, Fix

#1389 Brig Physician and Pubby tweaks
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/__DEFINES/access.dm
  code/modules/jobs/job_types/brigphys.dm
Labels: Map Edit, Tweak

#1388 Increased reagent cap
  code/modules/mob/living/carbon/carbon.dm
Labels: Tweak

#1381 A new, unobtrusive disease symptom for people who want that shit
  code/datums/diseases/advance/symptoms/heal.dm
Labels: Feature

#1379 Nukie reinforcements work on the station
  code/modules/antagonists/_common/antag_spawner.dm
Labels: Tweak

#1359 Fixes changeling chem reset on respec
  code/modules/antagonists/changeling/changeling.dm
Labels: Fix

#1328 Adds Doomguy ERT and two new traitor/nukie items: Energy Chainsaw and Super Energy Chainsaw
  beestation.dme
  code/datums/ert.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/bags.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/twohanded.dm
  code/modules/antagonists/ert/ert.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species_types/supersoldier.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/uplink/uplink_items.dm
  icons/mob/head.dmi
  icons/mob/inhands/weapons/chainsaw_lefthand.dmi
  icons/mob/inhands/weapons/chainsaw_righthand.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/items_and_weapons.dmi
  icons/obj/janitor.dmi
  icons/obj/storage.dmi
  sound/weapons/echainsawhit1.ogg
  sound/weapons/echainsawhit2.ogg
  sound/weapons/echainsawoff.ogg
  sound/weapons/echainsawon.ogg
Labels: Feature, Port, Sound, Sprites

#1346 Adds the grenade launcher to nukie uplink
  code/__DEFINES/inventory.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature, Tweak

#1365 changes to knockdowns and true stuns v2
  code/game/turfs/open.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/status_procs.dm
Labels: Tweak

#1354 Splits cargo's virus crate into 3 different crates
  code/game/objects/items/toys.dm
  code/modules/cargo/packs.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  icons/obj/drinks.dmi
  icons/obj/toy.dmi
Labels: Feature, Sprites, Tweak

#1369 [FIXED]Role restricted items are publicly available when discounted
  code/datums/components/uplink.dm
  code/modules/uplink/uplink_items.dm
Labels: Tweak

#1408 Fixed gear room access regression
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Fix, Map Edit

#1396 I have done nothing but code bread for three hours
  beestation.dme
  code/__DEFINES/components.dm
  code/datums/helper_datums/teleport.dm
  code/game/atoms.dm
  code/modules/food_and_drinks/food/snacks_bread.dm
  code/modules/mob/living/simple_animal/hostile/bread.dm
  icons/obj/food/burgerbread.dmi
Labels: Code Improvement, Feature, Sprites

#1411 add config ic and ooc filter toggles
  code/__DEFINES/say.dm
  code/controllers/configuration/entries/general.dm
  config/Sage/config.txt
  config/config.txt
Labels: Config Update

#1413 New Pet, Frank the Turtle!
  _maps/map_files/Mining/Lavaland.dmm
  beestation.dme
  code/modules/clothing/head/misc_special.dm
  code/modules/mob/living/simple_animal/friendly/turtle.dm
  icons/mob/pets.dmi
Labels: Feature, Map Edit, Sprites, Vote Passed

#1363 Adds two new craftable switchblades
  code/datums/components/crafting/recipes.dm
  code/game/objects/items/weaponry.dm
  icons/mob/inhands/weapons/swords_lefthand.dmi
  icons/mob/inhands/weapons/swords_righthand.dmi
  icons/obj/items_and_weapons.dmi
Labels: Feature, Needs Vote, Port, Sprites

#1415 Adds more Job slots to sage
  config/Sage/game_options.txt
  config/Sage/jobs.txt
Labels: Config Update

#1412 Adds Concentrated BZ, a dedicated anti changeling chemical
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
Labels: Feature

#1410 [TG PORT] Adds the Bar Capsule from TG
  _maps/templates/shelter_3.dmm
  code/modules/mining/equipment/survival_pod.dm
  code/modules/mining/machine_vending.dm
  code/modules/mining/shelters.dm
Labels: Feature, Map Edit

#1405 Caltrop effects require standing
  code/datums/components/caltrop.dm
Labels: Balance/Rebalance

#1425 [Bounty] Add an icon to brainwash victoms adminhud
  code/__DEFINES/atom_hud.dm
  code/datums/hud.dm
  code/modules/antagonists/brainwashing/brainwashing.dm
  icons/mob/hud.dmi
Labels: Administration, Sprites

#1419 Pubby access fixes
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Fix, Map Edit

#1361 Adds sleep healing
  code/datums/status_effects/debuffs.dm
Labels: Feature, Needs Vote

#1356 Adds two husking cures
  code/__DEFINES/reagents.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Balance/Rebalance, Port

#1434 Revert "Take 4, syndie items changes"
  code/game/objects/items/grenades/plastic.dm
  code/game/objects/items/toys.dm
  code/modules/projectiles/ammunition/energy/ebow.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/projectile/energy/ebow.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/uplink/uplink_items.dm
Labels: Revert

#1435 Revert "Revert "Take 4, syndie items changes""
  code/game/objects/items/grenades/plastic.dm
  code/game/objects/items/toys.dm
  code/modules/projectiles/ammunition/energy/ebow.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/projectile/energy/ebow.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/uplink/uplink_items.dm
Labels: Revert

#1420 Adds 2 extra medHUDs to medical lockers
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
Labels: Tweak

#1428 Stand customization
  beestation.dme
  code/__DEFINES/components.dm
  code/game/atoms.dm
  code/game/machinery/doors/door.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/simple_animal/guardian/guardian.dm
  code/modules/mob/living/simple_animal/guardian/guardiannaming.dm
  code/modules/mob/living/simple_animal/guardian/types/assassin.dm
  code/modules/mob/living/simple_animal/guardian/types/charger.dm
  code/modules/mob/living/simple_animal/guardian/types/dextrous.dm
  code/modules/mob/living/simple_animal/guardian/types/explosive.dm
  code/modules/mob/living/simple_animal/guardian/types/fire.dm
  code/modules/mob/living/simple_animal/guardian/types/gravitokinetic.dm
  code/modules/mob/living/simple_animal/guardian/types/gravity.dm
  code/modules/mob/living/simple_animal/guardian/types/lightning.dm
  code/modules/mob/living/simple_animal/guardian/types/protector.dm
  code/modules/mob/living/simple_animal/guardian/types/ranged.dm
  code/modules/mob/living/simple_animal/guardian/types/standard.dm
  code/modules/mob/living/simple_animal/guardian/types/support.dm
  icons/mob/guardian.dmi
  sound/effects/gravhit.ogg
Labels: Feature, Sound, Sprites, Tweak

#1437 Atmos inheritance take two
  code/game/mecha/equipment/tools/work_tools.dm
  code/game/mecha/mech_bay.dm
  code/game/objects/effects/effect_system/effects_foam.dm
  code/game/objects/items/melee/misc.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/twohanded.dm
  code/game/objects/structures/lattice.dm
  code/game/objects/structures/lavaland/necropolis_tendril.dm
  code/game/objects/structures/stairs.dm
  code/game/turfs/change_turf.dm
  code/game/turfs/closed.dm
  code/game/turfs/open.dm
  code/game/turfs/openspace/openspace.dm
  code/game/turfs/simulated/chasm.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor/plating.dm
  code/game/turfs/simulated/floor/reinf_floor.dm
  code/game/turfs/simulated/lava.dm
  code/game/turfs/space/space.dm
  code/game/turfs/turf.dm
  code/modules/antagonists/clockcult/clock_items/replica_fabricator.dm
  code/modules/antagonists/clockcult/clock_structures/wall_gear.dm
  code/modules/antagonists/cult/cult_structures.dm
  code/modules/buildmode/submodes/basic.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/simple_animal/bot/floorbot.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
  code/modules/projectiles/projectile/magic.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
  code/modules/ruins/objects_and_mobs/sin_ruins.dm
  code/modules/spells/spell_types/conjure.dm
  code/modules/spells/spell_types/devil.dm
Labels: Fix

#1436 Hotel staff can finally cook properly.
  _maps/RandomRuins/SpaceRuins/spacehotel.dmm
Labels: Fix, Map Edit

#1432 Fixes #1430
  code/modules/mob/living/carbon/human/species_types/supersoldier.dm
Labels: Fix

#1318 Two new traitor items: Energy Saw Arm Implant for MDs/CMO and Laser Arm Implant for robos/RD
  code/game/objects/items/melee/energy.dm
  code/modules/surgery/organs/augments_arms.dm
  code/modules/surgery/organs/augments_internal.dm
  code/modules/surgery/organs/autosurgeon.dm
  code/modules/uplink/uplink_items.dm
  icons/obj/device.dmi
Labels: Feature, Port, Sprites

#1439 Patron popcap bypass + overflow redirecting
  code/_onclick/hud/credits.dm
  code/controllers/configuration/configuration.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/job.dm
  code/modules/admin/IsBanned.dm
  code/modules/mob/dead/new_player/new_player.dm
  config/Sage/config.txt
  config/config.txt
Labels: Config Update, Feature

#1441 Fixes redirects
  code/modules/admin/IsBanned.dm
  code/modules/client/client_procs.dm
  config/Sage/config.txt
  config/config.txt
Labels: Config Update

#1444 fix ling chat runtimes
  code/datums/saymode.dm
Labels: Fix

#1445 Doantion -> Donation (typo)
  interface/interface.dm
Labels: Fix
