Repository BeeStation/BeeStation-Hornet, pull requests merged in 2020-07, with the labels that each got.

#2001 meth brain damage is not broken anymore
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
Labels: Balance/Rebalance, Needs Vote

#2076 New ctf map
  _maps/map_files/generic/CentCom.dmm
Labels: Map Edit, Needs Vote, Tweak

#1952 Ports hat throwing from TG
  code/__DEFINES/obj_flags.dm
  code/_globalvars/bitfields.dm
  code/controllers/subsystem/throwing.dm
  code/game/atoms_movable.dm
  code/modules/clothing/chameleon.dm
  code/modules/clothing/head/_head.dm
  code/modules/clothing/head/collectable.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/spacesuits/_spacesuits.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/suits/bio.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/suits/toggles.dm
  code/modules/clothing/suits/utility.dm
  code/modules/clothing/suits/wiz_robe.dm
  code/modules/hydroponics/beekeeping/beekeeper_suit.dm
  code/modules/research/xenobiology/crossbreeding/_clothing.dm
Labels: Code Improvement, Feature, Needs Vote, Refactor

#1965 A change to stand's healing ability
  code/modules/guardian/abilities/major/healing.dm
Labels: Tweak

#1961 virus food progresses diseases
  code/modules/reagents/chemistry/reagents/food_reagents.dm
Labels: Feature

#2094 Modify Canister Gas verb
  code/__DEFINES/vv.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/debug.dm
  code/modules/atmospherics/machinery/portable/canister.dm
Labels: Feature

#1981 [BOUNTY] Log item cremation and deep frying
  code/game/objects/structures/morgue.dm
  code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
Labels: Feature

#2086 Optional, customisable inventory outline
  code/_onclick/hud/screen_objects.dm
  code/datums/components/storage/concrete/_concrete.dm
  code/datums/components/storage/storage.dm
  code/game/objects/items.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/mob.dm
Labels: Feature, Fix

#2093 Alt-clicking the sound synthisizer changes the sound
  code/game/objects/items/devices/sound_synth.dm
Labels: Tweak

#2097 Fixes a division-by-zero runtime in carbon_defense.dm
  code/modules/mob/living/carbon/carbon_defense.dm
Labels: Fix

#2102 Brings back pages to the unban panel
  code/modules/admin/sql_ban_system.dm
Labels: Fix, sql

#2087 Slime Life Script Clean Up
  code/modules/mob/living/simple_animal/slime/life.dm
Labels: Fix

#2083 Gentle slimecross extracts
  beestation.dme
  code/modules/research/xenobiology/crossbreeding/__corecross.dm
  code/modules/research/xenobiology/crossbreeding/gentle.dm
  code/modules/research/xenobiology/xenobiology.dm
Labels: Feature, Needs Wiki Changes

#2033 TGUI Secrets Panel
  code/modules/admin/admin_verbs.dm
  code/modules/admin/secrets.dm
  code/modules/admin/topic.dm
  tgui/packages/tgui/interfaces/AdminSecretsPanel.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Administration, Feature

#2101 Fixes Hyperspeed Conveyors
  code/modules/recycling/conveyor2.dm
Labels: Fix

#2116 [s] Fix for server crashing coin / mint exploit.
  code/game/objects/items/cards_ids.dm
  code/modules/mining/mint.dm
Labels: Fix

#2035 Paper now uses markdown
  code/game/machinery/newscaster.dm
  code/game/machinery/telecomms/computers/message.dm
  code/game/objects/objs.dm
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/awaymissions/pamphlet.dm
  code/modules/detectivework/scanner.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/mob/living/simple_animal/guardian/guardian.dm
  code/modules/modular_computers/hardware/printer.dm
  code/modules/paperwork/folders.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/paper_cutter.dm
  code/modules/paperwork/paperbin.dm
  code/modules/paperwork/paperplane.dm
  code/modules/paperwork/photocopier.dm
  code/modules/photography/photos/photo.dm
  tgui/packages/tgui/components/TextArea.js
  tgui/packages/tgui/components/index.js
  tgui/packages/tgui/index.js
  tgui/packages/tgui/interfaces/PaperSheet.js
  tgui/packages/tgui/package.json
  tgui/packages/tgui/public/tgui.bundle.css
  tgui/packages/tgui/public/tgui.bundle.js
  tgui/packages/tgui/styles/components/TextArea.scss
  tgui/packages/tgui/styles/main.scss
  tgui/packages/tgui/styles/themes/paper.scss
  tgui/yarn.lock
Labels: Code Improvement, Feature, Removal

#2089 added back the razor
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Feature

#2095 removes CTF map crates and fixes the glass
  _maps/map_files/generic/CentCom.dmm
Labels: Fix

#2047 Nanite research points and programs
  code/__DEFINES/research.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Code Improvement, Feature

#2029 telecommunications SMES and the gravity gen SMES are now both wired to the wirenet [boxstation]
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Feature

#2077 Autolathes can no longer print surgical tools
  code/modules/research/designs/autolathe_designs.dm
Labels: Tweak

#2128 Fixes superficial healing resistance threshhold, maybe some other stuff
  code/datums/diseases/advance/symptoms/heal.dm
Labels: Fix

#2123 adds a prox check to the magician's hat
  code/game/objects/items/miscellaneous.dm
Labels: Fix

#2073 Ports Custom Vendors from /tg/station
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/research/designs/autolathe_designs.dm
  code/modules/vending/_vending.dm
  code/modules/vending/assist.dm
  icons/obj/device.dmi
  icons/obj/vending_restock.dmi
  tgui/packages/tgui/interfaces/Vending.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Feature, Fix, Vote Passed

#2134 Space Cleaner now counters viro
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/reagent_containers/spray.dm
Labels: Balance/Rebalance

#2090 Dissable the space wizard academy from gateway missions untill its fixed
  config/Sage/awaymissionconfig.txt
  config/awaymissionconfig.txt
Labels: Removal

#2147 Enables viro bottle printing and infection logging
  config/Sage/config.txt
  config/config.txt
Labels: Administration

#2149 a (ports msay bug fix from NSV)
  code/modules/client/client_procs.dm
Labels: Fix

#2132 Nanite Programs now respect rules when triggered
  code/modules/research/nanites/nanite_programs.dm
Labels: Fix

#2113 Atmos fire suits can now carry any internals tank
  code/modules/clothing/suits/utility.dm
Labels: Tweak

#2133 Cakehat
  code/modules/clothing/head/misc_special.dm
Labels: Balance/Rebalance

#2021 Poison knife
  code/game/objects/items/kitchen.dm
  code/modules/uplink/uplink_items.dm
  icons/obj/kitchen.dmi
Labels: Feature, Vote Passed

#2126 Telescopic riot shield can be equipped in security belt
  code/game/objects/items/storage/belt.dm
Labels: Tweak

#2169 Fixes PDA chat filter
  code/game/objects/items/devices/PDA/PDA.dm
Labels: Fix

#2163 UUID generation / Discord verification
  SQL/beestation_schema.sql
  SQL/database_changelog.txt
  code/__DEFINES/subsystems.dm
  code/datums/browser.dm
  code/datums/world_topic.dm
  code/modules/client/client_procs.dm
Labels: Administration, DO NOT MERGE, sql

#2120 spiked skin rework, or "zesko finally learns components"
  beestation.dme
  code/__DEFINES/components.dm
  code/datums/components/spikes.dm
  code/datums/diseases/advance/advance.dm
  code/datums/diseases/advance/symptoms/spiked.dm
  code/datums/dna.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Balance/Rebalance, Code Improvement, Tweak

#2148 Changes Bee Infestation Thresholds
  code/datums/diseases/advance/symptoms/beesymptom.dm
Labels: Fix, Tweak

#2079 Changing stack merging with inheritance
  code/game/objects/items/stacks/stack.dm
Labels: Fix

#2152 Telekinetic Slime Fix & More Cleaning
  code/modules/mob/living/simple_animal/slime/life.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
Labels: Fix

#2153 Replace Peacekeeper borg Dizzying Solution with Inabizine
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/reagent_containers/borghydro.dm
Labels: Feature, Tweak

#2174 ports tg#52322 (fixing arrhythmic knife)
  code/game/objects/items/holy_weapons.dm
Labels: Balance/Rebalance, Fix

#2122 makes spacevines threatening
  code/modules/events/spacevine.dm
Labels: Balance/Rebalance, Fix, Tweak

#2184 Updates Travis to use the latest version of BYOND
  Dockerfile
Labels: server, tooling

#2185 Make cybernetic organs Inedible and show up in medscanners
  code/modules/surgery/organs/heart.dm
  code/modules/surgery/organs/liver.dm
  code/modules/surgery/organs/lungs.dm
Labels: Fix

#2177 Increases kitchen coldroom temperature to sane temperature
  code/__DEFINES/atmospherics.dm
  code/modules/atmospherics/machinery/airalarm.dm
  code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
Labels: Tweak

#2112 Add gas miners to metastation's atmos
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Feature

#2130 buffs tinfoil hat
  code/game/data_huds.dm
  code/game/gamemodes/gangs/gang_pen.dm
  code/game/machinery/porta_turret/portable_turret.dm
  code/game/objects/effects/mines.dm
  code/game/objects/items/grenades/discogrenade.dm
  code/game/objects/items/implants/implantchair.dm
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/events/wizard/shuffle.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/projectiles/projectile/magic.dm
  code/modules/spells/spell_types/hivemind.dm
  code/modules/spells/spell_types/mind_transfer.dm
  code/modules/spells/spell_types/telepathy.dm
  code/modules/surgery/organs/vocal_cords.dm
Labels: Balance/Rebalance, Tweak, Vote Passed

#2131 small riot shield nerf
  code/game/objects/items/shields.dm
Labels: Balance/Rebalance

#2142 Button timer countdown effect
  beestation.dme
  code/_onclick/hud/action_button.dm
  code/datums/action.dm
  code/game/objects/effects/overlays.dm
  code/modules/spells/spell.dm
  icons/effects/cooldown.dmi
Labels: Feature

#2144 Area lighting colours
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas.dm
  code/game/area/areas/mining.dm
  code/game/area/areas/shuttles.dm
  code/modules/power/lighting.dm
Labels: Feature

#2161 fixes the weird chin that the skin got from a previous edit.
  interface/skin.dmf
Labels: Fix

#2162 Adds a sugar sack option to the biogenerator
  code/modules/research/designs/biogenerator_designs.dm
Labels: Feature

#2164 Restores missing plasma suits
  code/modules/mining/mine_items.dm
  code/modules/vending/wardrobes.dm
Labels: Fix

#2175 Oopsies forgot to add foreigner quirk
  code/datums/traits/neutral.dm
  icons/misc/language.dmi
Labels: Feature

#2173 fixes adamantine armor slowdown
  code/__DEFINES/movespeed_modification.dm
  code/modules/research/xenobiology/crossbreeding/_clothing.dm
Labels: Fix

#2191 Adds tiny fans to Centcomm shuttle dock
  _maps/map_files/generic/CentCom.dmm
Labels: Feature

#2078 clown car can no longer be cheesed
  code/modules/mob/living/carbon/human/human.dm
  code/modules/vehicles/cars/car.dm
  code/modules/vehicles/cars/clowncar.dm
  code/modules/vehicles/sealed.dm
Labels: Balance/Rebalance, Vote Passed

#2197 Fixes tenses while punching with krav maga
  code/datums/martial/krav_maga.dm
Labels: Fix

#2183 Adds checks to reject book author/title entries longer than 45 characters
  code/modules/library/lib_items.dm
  code/modules/library/lib_machines.dm
Labels: Feature

#2211 Gives the abductor helmet flash protection
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
Labels: Tweak

#2202 Failing self surgery no longer forces you to eat organs you try to insert
  code/modules/surgery/organs/organ_internal.dm
Labels: Tweak

#2205 Adds synthesizer piano to default module cyborg
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Feature

#2201 Makes the sec beret have the same armor value as the helmet
  code/modules/clothing/head/jobs.dm
Labels: Tweak

#2195 fixing various language bugs
  code/__DEFINES/language.dm
  code/datums/traits/neutral.dm
  code/modules/mob/living/carbon/human/status_procs.dm
  code/modules/surgery/organs/tongue.dm
Labels: Fix

#2212 AHEAL ALL NOW HAS CONFIRMATION
  code/modules/admin/verbs/healall.dm
Labels: Administration

#2196 Plumbing sprites update
  icons/obj/plumbing/plumbers.dmi
Labels: Feature, Sprites

#2223 [S] Updates pillow and pygit2
  tools/mapmerge2/requirements.txt
Labels: security

#2226 Adds volume up/down as valid keypresses
  code/modules/keybindings/bindings_client.dm
Labels: Fix

#2215 Fixes warden beret typo
  code/modules/clothing/head/jobs.dm
Labels: Grammar and Formatting

#2207 CentCom Galatic Ban DB
  beestation.dme
  code/controllers/configuration/entries/general.dm
  code/datums/http.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  config/Sage/config.txt
  config/config.txt
Labels: Feature, server

#2143 WINGS ARE NOW ORGANS HOLY SHIT
  beestation.dme
  code/__DEFINES/DNA.dm
  code/__DEFINES/mobs.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/cargo/bounties/medical.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/apid.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/mob/living/emote.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/organs/wings.dm
  icons/mob/wings.dmi
  icons/obj/surgery.dmi
Labels: Balance/Rebalance, Code Improvement, Feature, Fix, Sprites, Tweak

#2168 Syndie Incursion (Team based traitors)
  beestation.dme
  code/__DEFINES/atom_hud.dm
  code/__DEFINES/role_preferences.dm
  code/__HELPERS/game.dm
  code/controllers/configuration/entries/game_options.dm
  code/datums/components/uplink.dm
  code/datums/hud.dm
  code/datums/mind.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/incursion/incursion.dm
  code/game/gamemodes/objective.dm
  code/game/objects/items/AI_modules.dm
  code/game/objects/items/implants/implant.dm
  code/game/objects/items/implants/implant_misc.dm
  code/modules/antagonists/incursion/incursion.dm
  code/modules/uplink/uplink_devices.dm
  code/modules/uplink/uplink_items.dm
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Feature, Refactor

#2238 Fixes some shitcode in centcom ban db, youre welcome
  code/modules/admin/topic.dm
Labels: Code Improvement

#2236 Fixes exploding rubber ducks being only available to clown ops
  code/modules/uplink/uplink_items.dm
Labels: Fix
