Repository BeeStation/BeeStation-Hornet, pull requests merged in 2021-03, with the labels that each got.

#3777 Audits do_after calls at heretics code
  code/modules/antagonists/eldritch_cult/eldritch_magic.dm
Labels: Fix

#3779 SSgarbage now shows up in the MC tab
  code/controllers/subsystem/garbage.dm
Labels: Fix

#3575 Weakens mining armour while in high pressure environments
  code/datums/diseases/_MobProcs.dm
  code/game/objects/items.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/suits/cloaks.dm
  code/modules/mining/equipment/explorer_gear.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  code/modules/mob/living/simple_animal/friendly/drone/interaction.dm
Labels: Balance/Rebalance, Vote Passed

#3534 Prevents cremating indestructible items.
  code/game/objects/structures/morgue.dm
Labels: Fix, Vote Passed

#3446 Mask of Madness Port
  code/__DEFINES/antagonists.dm
  code/__DEFINES/components.dm
  code/datums/components/mood.dm
  code/modules/antagonists/eldritch_cult/eldritch_items.dm
  code/modules/antagonists/eldritch_cult/knowledge/ash_lore.dm
  icons/mob/mask.dmi
  icons/obj/clothing/masks.dmi
Labels: Feature, sprites

#3780 Fixes some things with gimmick positions
  code/__DEFINES/preferences.dm
  code/modules/jobs/job_types/gimmick.dm
  code/modules/jobs/jobs.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
  tgui/public/tgui-panel.bundle.css
Labels: Fix, TGUI-Changes

#3782 Fixed Necropolis seed stealth 8 threshold and virology pda
  code/datums/diseases/advance/symptoms/necropolis.dm
  code/modules/jobs/job_types/virologist.dm
Labels: Fix

#3784 Gimmick highlighting respects no chat colours.
  tgui/packages/tgui-panel/chat/renderer.js
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
  tgui/public/tgui-panel.bundle.js
Labels: TGUI-Changes

#3774 [minor] damage overlays fix
  code/modules/surgery/bodyparts/bodyparts.dm
Labels: Fix

#3792 Adds missing stuff back to autodrobe
  code/modules/vending/autodrobe.dm
Labels: Fix

#3785 Beret
  code/modules/clothing/head/beanie.dm
  code/modules/clothing/head/jobs.dm
Labels: Balance/Rebalance

#3796 Fixes up some warnings
  code/modules/client/loadout/loadout_accessories.dm
Labels: Code Improvement, Fix

#3798 Ports timer cooldowns + bonus fix to abductor implants
  beestation.dme
  code/__DEFINES/cooldowns.dm
  code/controllers/subsystem/timer.dm
  code/datums/action.dm
  code/datums/components/caltrop.dm
  code/datums/datum.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/items/implants/implant_abductor.dm
  code/game/objects/items/robot/robot_upgrades.dm
Labels: Code Improvement, Fix, Refactor

#3735 Crystallized cerulean tweaks
  code/modules/research/xenobiology/crossbreeding/_misc.dm
  code/modules/research/xenobiology/crossbreeding/_structures.dm
  code/modules/research/xenobiology/crossbreeding/crystalized.dm
Labels: Feature, Tweak

#3803 Ports: Ghost Pool Protection Admin Button
  beestation.dme
  code/__DEFINES/admin.dm
  code/__HELPERS/game.dm
  code/controllers/subsystem/pai.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/objects/items/holy_weapons.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/ghost_pool_protection.dm
  code/modules/awaymissions/capture_the_flag.dm
  code/modules/awaymissions/corpse.dm
  code/modules/events/_event.dm
  code/modules/mob/living/brain/posibrain.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  tgui/packages/tgui/interfaces/GhostPoolProtection.js
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: Administration, TGUI-Changes

#3775 adds file cabinet to HoP's office on meta
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Feature, mapping

#3804 Fixes Mask of Madness not having cost
  code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
  code/modules/antagonists/eldritch_cult/knowledge/ash_lore.dm
Labels: Fix

#3647 i try and add fans to shuttle without fucking up try #2
  _maps/shuttles/mining_box.dmm
  _maps/shuttles/mining_delta.dmm
  _maps/shuttles/mining_large.dmm
  _maps/shuttles/science_outpost.dmm
Labels: Feature, mapping

#3612 Add maximum reccomended version #tgstation/TerraGov-Marine-Corps/pull/5989
  code/_compile_options.dm
  code/modules/client/client_procs.dm
Labels: server

#3793 [Port]"Adds moodlet for moth wings burning off"
  code/datums/mood_events/generic_negative_events.dm
  code/modules/surgery/organs/wings.dm
Labels: Feature

#3790 Eminence now has it's special move that lets it pass clockwalls
  code/__DEFINES/mobs.dm
  code/modules/antagonists/clock_cult/mobs/eminence.dm
  code/modules/mob/mob_movement.dm
Labels: Feature

#3778 Organ storage bag can insert organs into a smart organ storage
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/surgery/tools.dm
Labels: Feature

#3797 Attempts to bring Dynamic more up to date
  beestation.dme
  code/__DEFINES/components.dm
  code/__DEFINES/dynamic.dm
  code/__DEFINES/mobs.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/roundend.dm
  code/controllers/subsystem/ticker.dm
  code/datums/mocking/client.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_hijacking.dm
  code/game/gamemodes/dynamic/dynamic_logging.dm
  code/game/gamemodes/dynamic/dynamic_rulesets.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/dynamic/dynamic_simulations.dm
  code/game/gamemodes/dynamic/readme.md
  code/game/gamemodes/dynamic/ruleset_picking.dm
  code/game/gamemodes/game_mode.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/antagonists/ashwalker/ashwalker.dm
  code/modules/antagonists/revenant/revenant_spawn_event.dm
  code/modules/antagonists/slaughter/slaughterevent.dm
  code/modules/antagonists/swarmer/swarmer_event.dm
  code/modules/antagonists/wizard/equipment/spellbook.dm
  code/modules/events/_event.dm
  code/modules/events/abductor.dm
  code/modules/events/alien_infestation.dm
  code/modules/events/blob.dm
  code/modules/events/nightmare.dm
  code/modules/events/operative.dm
  code/modules/events/pirates.dm
  code/modules/events/space_dragon.dm
  code/modules/events/spider_infestation.dm
  code/modules/mob/dead/dead.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/brain/MMI.dm
  code/modules/mob/living/brain/posibrain.dm
  code/modules/mob/living/death.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/pai/death.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/login.dm
  code/modules/mob/logout.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_lists.dm
  code/modules/ninja/ninja_event.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/dynamic_ruleset_sanity.dm
  config/Sage/dynamic.json
  config/Sage/game_options.txt
  config/dynamic.json
  config/game_options.txt
Labels: Administration, Config Update, Feature, Fix, Removal, Tweak

#3739 Removes billy club from officer's standard loadout, moves it to their vendor
  code/game/objects/items/storage/belt.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/warden.dm
  code/modules/vending/security.dm
Labels: Balance/Rebalance, Tweak

#3662 Teleporting objects use do_teleport rather than forcemove
  code/datums/brain_damage/special.dm
  code/datums/dash_weapon.dm
  code/datums/diseases/wizarditis.dm
  code/game/machinery/computer/prisoner/gulag_teleporter.dm
  code/game/mecha/mecha.dm
  code/game/objects/effects/bump_teleporter.dm
  code/game/objects/items/teleportation.dm
  code/modules/antagonists/abductor/machinery/experiment.dm
  code/modules/antagonists/abductor/machinery/pad.dm
  code/modules/antagonists/clock_cult/structure/dimensional_rift.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/antagonists/devil/devil.dm
  code/modules/clothing/spacesuits/chronosuit.dm
  code/modules/clothing/suits/reactive_armour.dm
  code/modules/guardian/abilities/major/hand.dm
  code/modules/mining/fulton.dm
  code/modules/mining/lavaland/necropolis_chests.dm
Labels: Code Improvement

#3814 The various types of rods now properly merge.
  code/game/objects/items/stacks/rods.dm
Labels: Fix

#3808 Floorbot Fixes
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/floorbot.dm
Labels: Fix

#3734 Miscellaneous fixes (2021-02-24)
  _maps/RandomZLevels/TheFactory.dmm
  code/datums/dna.dm
  code/game/machinery/dance_machine.dm
  code/game/objects/effects/mainttraps.dm
  code/game/objects/items/RCD.dm
  code/modules/awaymissions/capture_the_flag.dm
  code/modules/guardian/abilities/special/absolution.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/projectiles/projectile/bullets/revolver.dm
  code/modules/recycling/disposal/bin.dm
  code/modules/spells/spell_types/construct_spells.dm
  code/modules/surgery/blood_filter.dm
  code/modules/vehicles/wheelchair.dm
Labels: Fix, mapping

#3816 Dynamic: Fixes a division by zero runtime (tg#56728)
  code/game/gamemodes/dynamic/dynamic.dm
Labels: Fix

#3762 [Port] Telecommunications Updated Machine UI
  code/_globalvars/misc.dm
  code/game/machinery/telecomms/machine_interactions.dm
  code/game/machinery/telecomms/machines/receiver.dm
  tgui/packages/tgui/interfaces/Telecomms.js
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: Balance/Rebalance, Code Improvement, Feature, Removal, TGUI-Changes, Vote Passed, server

#3818 Audits merge_type
  code/game/objects/items/stacks/bscrystal.dm
  code/game/objects/items/stacks/telecrystal.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/modules/recycling/conveyor2.dm
Labels: Fix

#3815 Fixes teleporting weiredness
  _maps/RandomZLevels/TheFactory.dmm
  code/__DEFINES/misc.dm
  code/__HELPERS/areas.dm
  code/datums/helper_datums/teleport.dm
  code/game/area/areas.dm
  code/game/area/areas/centcom.dm
  code/game/area/areas/shuttles.dm
  code/game/machinery/computer/teleporter.dm
  code/game/objects/items/teleportation.dm
  code/modules/antagonists/abductor/machinery/experiment.dm
  code/modules/antagonists/abductor/machinery/pad.dm
  code/modules/antagonists/clock_cult/helpers/servant_warp.dm
  code/modules/awaymissions/mission_code/TheFactory.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/silicon/ai/multicam.dm
  code/modules/projectiles/projectile/energy/net_snare.dm
  code/modules/research/xenobiology/crossbreeding/warping.dm
  code/modules/ruins/spaceruin_code/hilbertshotel.dm
Labels: Fix, Refactor, mapping

#3716 Ports sects from tg
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  beestation.dme
  code/__DEFINES/flags.dm
  code/__DEFINES/misc.dm
  code/_globalvars/misc.dm
  code/_globalvars/religion.dm
  code/datums/components/religious_tool.dm
  code/datums/mind.dm
  code/datums/traits/good.dm
  code/game/objects/items/holy_weapons.dm
  code/game/objects/items/storage/book.dm
  code/modules/antagonists/clock_cult/items/clock_components.dm
  code/modules/antagonists/ert/ert.dm
  code/modules/jobs/job_types/chaplain.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/species_types/android.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/religion/religion_sects.dm
  code/modules/religion/religion_structures.dm
  code/modules/religion/rites.dm
Labels: Feature, Vote Passed, mapping

#3817 Clockwork cult changes and fixes for brass manacles
  code/modules/antagonists/clock_cult/items/clockwork_slab.dm
  code/modules/antagonists/clock_cult/scriptures/hateful_manacles.dm
  code/modules/antagonists/clock_cult/servant_of_ratvar.dm
Labels: Feature, Fix, Tweak

#3827 slimes no longer attack their master
  code/modules/mob/living/simple_animal/slime/slime.dm
  code/modules/research/xenobiology/crossbreeding/transformative.dm
Labels: Tweak

#3824 Synthflesh unhusk change
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Tweak

#3829 Splits the Summon Equipment spell into two different spells, fixes a bug with Summon Equipment (tg#52685)
  code/modules/antagonists/cult/blood_magic.dm
Labels: Balance/Rebalance, Fix, Needs Wiki Changes

#3766 Sets config master_mode to secret_extended
  config/game_options.txt
Labels: Config Update

#3846 Stops the box mining dock from plasmaflooding itself.
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Fix, mapping

#3852 Fixes getting deleted by teleportation
  code/datums/helper_datums/teleport.dm
Labels: Fix, Removal

#3848 Temporarily removes code ownership for config/tgs files
  .github/CODEOWNERS
Labels: GitHub

#3745 Nerf hierophant melee facetank
  code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
Labels: Fix, Tweak

#3714 Baguette blade and mime heirloom rework
  code/datums/traits/negative.dm
  code/game/objects/items/melee/energy.dm
  code/game/objects/items/melee/misc.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/food_and_drinks/food/snacks_bread.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature

#3677 Adds pools to box and meta
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Feature, Vote Passed, mapping

#3856 removes unused/bad helpers
  code/__HELPERS/_lists.dm
  code/__HELPERS/text.dm
  code/controllers/subsystem/persistence.dm
  code/controllers/subsystem/ticker.dm
  code/datums/helper_datums/events.dm
  code/game/machinery/newscaster.dm
  code/game/mecha/mech_fabricator.dm
  code/game/mecha/mecha.dm
  code/modules/admin/admin.dm
  code/modules/cargo/centcom_podlauncher.dm
  code/modules/food_and_drinks/food/snacks_pastry.dm
  code/modules/mob/living/simple_animal/parrot.dm
Labels: Administration, Code Improvement

#3868 Fixes issue examining modular computer with a printer
  code/modules/modular_computers/computers/_modular_computer_shared.dm
Labels: Fix

#3839 Removes freezer from metastation kitchen backroom
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Removal, Vote Passed, mapping

#3854 Welder fuel tank explosion change
  code/modules/reagents/reagent_dispenser.dm
Labels: Tweak

#3869 Changeling transform fixes
  code/game/gamemodes/changeling/changeling.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/changeling/powers/transform.dm
Labels: Fix

#3861 Adds a handful of nice sprite related things from TG. (Inhands etc.)
  code/game/objects/items/devices/traitordevices.dm
  code/game/objects/items/extinguisher.dm
  code/game/objects/items/flamethrower.dm
  code/game/objects/items/singularityhammer.dm
  code/game/objects/structures/bedsheet_bin.dm
  code/modules/projectiles/guns/misc/syringe_gun.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/mob/inhands/misc/bedsheet_lefthand.dmi
  icons/mob/inhands/misc/bedsheet_righthand.dmi
  icons/mob/inhands/misc/sheets_lefthand.dmi
  icons/mob/inhands/misc/sheets_righthand.dmi
  icons/mob/inhands/weapons/flamethrower_lefthand.dmi
  icons/mob/inhands/weapons/flamethrower_righthand.dmi
  icons/mob/inhands/weapons/hammers_lefthand.dmi
  icons/mob/inhands/weapons/hammers_righthand.dmi
  icons/obj/guns/projectile.dmi
  icons/obj/items_and_weapons.dmi
Labels: Feature, Grammar and Formatting, Removal, Tweak, sprites

#3729 Milk Has an Overdose
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
Labels: Feature

#3753 Helps doctors follow the SOP
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  beestation.dme
  code/__DEFINES/obj_flags.dm
  code/game/machinery/iv_drip.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/surgery/anesthetic_machine.dm
  code/modules/surgery/latex_glove_box.dm
  icons/obj/iv_drip.dmi
  icons/obj/surgery.dmi
Labels: Feature, mapping, sprites

#3885 Fixes Adamantine Shield dealing 0 damage
  code/modules/research/xenobiology/crossbreeding/_weapons.dm
Labels: Fix

#3878 Fixes his grace being pullable.
  code/game/objects/items/his_grace.dm
Labels: Fix

#3865 More lines for various string pools
  strings/abductee_objectives.txt
  strings/cas_black.txt
  strings/italian_replacement.json
  strings/pirates.json
  strings/redpill.json
  strings/revenant_names.json
  strings/sillytips.txt
  strings/traumas.json
  strings/valentines.json
Labels: Feature, Fix, Grammar and Formatting

#3877 Fixes being able to flash genetically blind people.
  code/modules/mob/living/carbon/carbon_defense.dm
Labels: Fix

#3862 Changes felinid say verb to "meows"
  code/modules/mob/living/carbon/human/species_types/felinid.dm
Labels: Feature, Grammar and Formatting, Tweak, Vote Passed

#3741 Brig physician is not security (this time for real!)
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/modules/antagonists/roundstart_special/special_antagonist.dm
  code/modules/antagonists/roundstart_special/undercover/undercover.dm
  code/modules/events/special_antag_event.dm
  code/modules/jobs/jobs.dm
Labels: Tweak

#3819 makes the Syndicate base a little "safer" while also adding minor QoL
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
Labels: Feature, Vote Passed, mapping

#3884 fixes an issue with riot suits not having sounds.
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/suits/armor.dm
Labels: Fix

#3896 Fixes clockcult manacles invocation being spoken on radio
  code/modules/antagonists/clock_cult/scriptures/abscond.dm
  code/modules/antagonists/clock_cult/scriptures/clockwork_armaments.dm
  code/modules/antagonists/clock_cult/scriptures/dimensional_breach.dm
  code/modules/antagonists/clock_cult/scriptures/hateful_manacles.dm
  code/modules/antagonists/clock_cult/scriptures/interdiction_lens.dm
  code/modules/antagonists/clock_cult/scriptures/sigil_of_submission.dm
  code/modules/antagonists/clock_cult/scriptures/sigil_transmission.dm
  code/modules/antagonists/clock_cult/scriptures/summon_marauder.dm
  code/modules/mob/living/simple_animal/parrot.dm
Labels: Fix

#3908 Clockwork cult gear base fixes
  code/modules/antagonists/clock_cult/scriptures/interdiction_lens.dm
  code/modules/antagonists/clock_cult/scriptures/prosperity_prism.dm
  code/modules/antagonists/clock_cult/structure/gear_base.dm
  icons/obj/clockwork_objects.dmi
Labels: Fix, sprites

#3368 Special beeshop cosmetics for donators!
  beestation.dme
  code/controllers/configuration/entries/game_options.dm
  code/game/objects/items/plushes.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/client/client_procs.dm
  code/modules/client/loadout/loadout.dm
  code/modules/client/loadout/loadout_donator.dm
  code/modules/client/preferences.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/neck/_neck.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/clothing/under/skirt_dress.dm
  config/Sage/game_options.txt
  config/game_options.txt
  icons/mob/back.dmi
  icons/mob/head.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/inhands/equipment/backpack_lefthand.dmi
  icons/mob/inhands/equipment/backpack_righthand.dmi
  icons/mob/neck.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/neck.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/clothing/uniforms_deconflict.dmi
  icons/obj/plushes.dmi
  icons/obj/storage.dmi
Labels: Config Update, Feature, Stale, sprites

#3918 War Declaration Music
  code/modules/antagonists/nukeop/equipment/nuclear_challenge.dm
  sound/soundtrack/future_perception.ogg
Labels: Feature, Vote Passed, sound

#3909 Reworking Zombie Powder into a unique toxin
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
Labels: Tweak

#3920 Revert "Special beeshop cosmetics for donators!"
  beestation.dme
  code/controllers/configuration/entries/game_options.dm
  code/game/objects/items/plushes.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/client/client_procs.dm
  code/modules/client/loadout/loadout.dm
  code/modules/client/loadout/loadout_donator.dm
  code/modules/client/preferences.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/neck/_neck.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/clothing/under/skirt_dress.dm
  config/Sage/game_options.txt
  config/game_options.txt
  icons/mob/back.dmi
  icons/mob/head.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/inhands/equipment/backpack_lefthand.dmi
  icons/mob/inhands/equipment/backpack_righthand.dmi
  icons/mob/neck.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/neck.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/clothing/uniforms_deconflict.dmi
  icons/obj/plushes.dmi
  icons/obj/storage.dmi
Labels: Config Update, Removal, sprites

#3837 attempts to bring supply pod's code up to date + updates adminbuse pod launcher tgui
  _maps/map_files/generic/CentCom.dmm
  code/__DEFINES/cargo.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/obj_flags.dm
  code/game/area/areas/centcom.dm
  code/game/atoms.dm
  code/game/objects/effects/misc.dm
  code/game/objects/items/miscellaneous.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/admin/admin.dm
  code/modules/admin/battle_royale.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/antagonists/traitor/equipment/contractor.dm
  code/modules/antagonists/traitor/syndicate_contract.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/cargo/centcom_podlauncher.dm
  code/modules/cargo/expressconsole.dm
  code/modules/cargo/gondolapod.dm
  code/modules/cargo/supplypod.dm
  icons/effects/supplypod_pickturf.dmi
  icons/effects/supplypod_pickturf_down.dmi
  icons/mob/gondolapod.dmi
  icons/obj/supplypods.dmi
  icons/obj/supplypods_32x32.dmi
  tgui/package.json
  tgui/packages/tgui-dev-server/package.json
  tgui/packages/tgui/components/Button.js
  tgui/packages/tgui/components/DraggableControl.js
  tgui/packages/tgui/components/Flex.js
  tgui/packages/tgui/components/Knob.js
  tgui/packages/tgui/components/LabeledControls.js
  tgui/packages/tgui/components/Section.js
  tgui/packages/tgui/components/Tooltip.js
  tgui/packages/tgui/drag.js
  tgui/packages/tgui/interfaces/CentcomPodLauncher.js
  tgui/packages/tgui/package.json
  tgui/packages/tgui/styles/components/Section.scss
  tgui/packages/tgui/styles/components/Tooltip.scss
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.css
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
  tgui/yarn.lock
Labels: Administration, Code Improvement, Feature, Refactor, Removal, TGUI-Changes, mapping, sprites, test merged

#3922 Fixes shields getting damaged by stamina.
  code/game/objects/items/shields.dm
Labels: Fix

#3924 AI Eyes jump to shell when it disconnects
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Tweak

#3929 Fixes a battle royale typo
  code/modules/admin/battle_royale.dm
Labels: Administration, Grammar and Formatting, Removal

#3928 IPCs get pulled into body when revived
  code/modules/mob/living/carbon/human/species_types/IPC.dm
Labels: Tweak

#3886 [MINOR] mostly oozeling tweaks and a feature
  code/modules/mob/living/carbon/human/species_types/oozelings.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
Labels: Balance/Rebalance, Feature, Tweak

#3902 Fixes Styptic Powder and Silver Sulfadiazine
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Fix

#3897 Mob_holders can now be thrown
  code/modules/antagonists/devil/true_devil/inventory.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/alien/humanoid/inventory.dm
  code/modules/mob/living/carbon/alien/larva/inventory.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/inventory.dm
  code/modules/mob/living/inhand_holder.dm
  code/modules/mob/living/simple_animal/friendly/drone/inventory.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
Labels: Feature

#3917 Fixed Cyborgs not being able to harvest plants with Plant Bag
  code/modules/hydroponics/hydroponics.dm
Labels: Fix

#3934 Prevents guardians from teleporting things while in scout mode.
  code/modules/guardian/abilities/major/scout.dm
  code/modules/guardian/abilities/minor/snares.dm
  code/modules/guardian/abilities/minor/teleport.dm
  code/modules/guardian/guardian.dm
Labels: Fix

#3895 Standarizes coldroom tiles, removes roundstart cold tile.
  _maps/RandomRooms/5x4/sk_rdm124_oldcryoroom.dmm
  _maps/RandomZLevels/TheFactory.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/__DEFINES/atmospherics.dm
  code/game/turfs/open/floor/plasteel_floor.dm
Labels: Removal, Tweak, mapping

#3936 PORT adds airalarms, firealarms, and APCs to the simple circuits RCD upgrade
  code/game/machinery/firealarm.dm
  code/modules/atmospherics/machinery/airalarm.dm
  code/modules/power/apc.dm
Labels: Fix

#3923 Donator items 2 electric boogaloo
  beestation.dme
  code/controllers/configuration/entries/game_options.dm
  code/game/objects/items/plushes.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/client/client_procs.dm
  code/modules/client/loadout/loadout.dm
  code/modules/client/loadout/loadout_donator.dm
  code/modules/client/preferences.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/neck/_neck.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/clothing/under/skirt_dress.dm
  config/Sage/game_options.txt
  config/game_options.txt
  icons/mob/back.dmi
  icons/mob/head.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/inhands/equipment/backpack_lefthand.dmi
  icons/mob/inhands/equipment/backpack_righthand.dmi
  icons/mob/neck.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/neck.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/clothing/uniforms_deconflict.dmi
  icons/obj/plushes.dmi
  icons/obj/storage.dmi
Labels: Config Update, Feature, sprites

#3943 Misc donator fixes
  code/game/objects/items/storage/backpack.dm
  code/modules/client/preferences.dm
  code/modules/clothing/neck/_neck.dm
  code/modules/jobs/job_types/_job.dm
Labels: Code Improvement, Fix

#3946 Fixes suit movement sounds not working if you take them off and put them back on again.
  code/modules/clothing/suits/_suits.dm
Labels: Fix

#3941 BUFFS ANIME (updates schoolgirl outfits)
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, sprites

#3899 Central Command jokes or we're doing big amount of trolling.
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/effects/spawners/xeno_egg_delivery.dm
  code/game/objects/structures/aliens.dm
  code/modules/paperwork/paper.dm
Labels: Tweak

#3781 Meteor wave changes.
  beestation.dme
  code/modules/events/asteroid_impact.dm
  code/modules/events/meteor_wave.dm
Labels: Tweak

#3366 Ports tgui lists
  beestation.dme
  code/__HELPERS/files.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/hud/ai.dm
  code/datums/mind.dm
  code/datums/mutations/actions.dm
  code/game/atoms.dm
  code/game/gamemodes/objective.dm
  code/game/machinery/camera/tracking.dm
  code/game/machinery/hologram.dm
  code/game/objects/items/holy_weapons.dm
  code/modules/mob/living/simple_animal/bot/mulebot.dm
  code/modules/modular_computers/computers/item/computer.dm
  code/modules/shuttle/assault_pod.dm
  code/modules/spells/spell_types/area_teleport.dm
  code/modules/surgery/helpers.dm
  code/modules/tgui/tgui_input_list.dm
  tgui/packages/tgui/interfaces/ListInput.js
  tgui/packages/tgui/styles/interfaces/ListInput.scss
  tgui/packages/tgui/styles/main.scss
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
Labels: Feature, TGUI-Changes, test merged

#3588 Replaces the spectre inspector's ability to see all ghosts with a team locator that points to the position of all ghosts.
  code/modules/antagonists/clock_cult/mobs/eminence.dm
  code/modules/antagonists/revenant/revenant.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/ghost.dm
Labels: Tweak

#3607 Bullet primer x screwdriver
  code/modules/projectiles/ammunition/_firing.dm
Labels: Feature

#3644 adds the geisha suit to the beecoin shop
  code/modules/client/loadout/loadout_uniform.dm
Labels: Feature

#3646 Makes automatic shotguns heavy weapons
  code/modules/projectiles/guns/ballistic/shotgun.dm
Labels: Balance/Rebalance, Fix, Tweak

#3655 Prevents indestructable items from being destroyed 2.
  code/modules/power/supermatter/supermatter.dm
  code/modules/research/destructive_analyzer.dm
Labels: Tweak

#3664 Energy katana gets deleted when the ninja dies.
  code/modules/ninja/energy_katana.dm
  code/modules/ninja/suit/suit.dm
Labels: Tweak

#3679 Tweaks contraband prices for cargo
  code/modules/cargo/packs.dm
Labels: Tweak, Vote Passed

#3950 Quick-Create-Antagonist tweaks
  code/modules/admin/topic.dm
  code/modules/admin/verbs/one_click_antag.dm
Labels: Administration

#3744 Adds Yatzy
  code/game/objects/items/toys.dm
  code/modules/vending/games.dm
Labels: Feature

#3746 Deltastation third brig cell
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Feature, Fix, Removal, Tweak, mapping

#3763 Adds Chess Crates and a Maints Chess Room
  _maps/RandomRooms/10x10/sk_rdm157_chess.dmm
  _maps/map_files/generic/CentCom.dmm
  code/game/objects/items/cardboard_cutouts.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/modules/cargo/packs.dm
  code/modules/mapping/random_rooms.dm
Labels: Feature, mapping

#3789 TG PORT: New sprite animation
  icons/mob/mutant_bodyparts.dmi
Labels: sprites

#3942 Oozeling Tweak: Increase cost of limb regen, make limbs recede sooner
  code/modules/mob/living/carbon/human/species_types/oozelings.dm
Labels: Fix, Tweak

#3708 Removes completely unfit away missions.
  _maps/RandomZLevels/Academy.dmm
  _maps/RandomZLevels/TheFactory.dmm
  _maps/RandomZLevels/challenge.dmm
  _maps/RandomZLevels/wildwest.dmm
  config/Sage/awaymissionconfig.txt
  config/awaymissionconfig.txt
Labels: Config Update, Removal, Triaged, mapping

#3957 Fixes drone DoUnequip
  code/modules/mob/living/simple_animal/friendly/drone/inventory.dm
Labels: Fix

#3787 TG PORT: Folder TGUI
  beestation.dme
  code/modules/paperwork/folder_premade.dm
  code/modules/paperwork/folders.dm
  code/modules/paperwork/paper.dm
  tgui/packages/tgui/interfaces/Folder.js
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: Stale, TGUI-Changes

#3959 Adjust dynamic requirements for clockwork cult
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
Labels: Tweak

#3879 Stat panel updates
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/mob/mob_stat.dm
  tgui/packages/tgui-panel/stat/StatStatus.js
  tgui/packages/tgui-panel/stat/StatTabs.js
  tgui/packages/tgui-panel/stat/StatText.js
  tgui/packages/tgui-panel/stat/StatTicket.js
  tgui/packages/tgui-panel/styles/components/Stat.scss
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.css
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: Administration, TGUI-Changes, Tweak

#3960 installing a circuit into an APC using an RCD no longer locks the APC
  code/modules/power/apc.dm
Labels: Tweak

#3939 Changeling last resort spawns the headcrab instantly instead of being delayed by 0.8 seconds.
  code/modules/antagonists/changeling/powers/headcrab.dm
Labels: Tweak

#3945 Sleeping carp no longer deflects validhunter bullets
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets/revolver.dm
  code/modules/projectiles/projectile/magic.dm
  code/modules/projectiles/projectile/reusable/foam_dart.dm
  code/modules/projectiles/projectile/special/floral.dm
  code/modules/projectiles/projectile/special/wormhole.dm
Labels: Tweak

#3810 Boxstation changes and fixes
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Feature, Fix, Removal, Tweak, mapping

#3977 Reverts to old cat tail
  icons/mob/mutant_bodyparts.dmi
Labels: Feature, Removal, sprites

#3979 Disable circuit cloning in config
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Config Update

#3975 Doesn't remove circuits
  beestation.dme
  code/modules/integrated_electronics/subtypes/manipulation.dm
  code/modules/integrated_electronics/subtypes/reagents.dm
Labels: Removal

#3980 Revert "Ports tgui lists (#3366)"
  beestation.dme
  code/__HELPERS/files.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/hud/ai.dm
  code/datums/mind.dm
  code/datums/mutations/actions.dm
  code/game/atoms.dm
  code/game/gamemodes/objective.dm
  code/game/machinery/camera/tracking.dm
  code/game/machinery/hologram.dm
  code/game/objects/items/holy_weapons.dm
  code/modules/mob/living/simple_animal/bot/mulebot.dm
  code/modules/modular_computers/computers/item/computer.dm
  code/modules/shuttle/assault_pod.dm
  code/modules/spells/spell_types/area_teleport.dm
  code/modules/surgery/helpers.dm
  code/modules/tgui/tgui_input_list.dm
  tgui/packages/tgui/interfaces/ListInput.js
  tgui/packages/tgui/styles/interfaces/ListInput.scss
  tgui/packages/tgui/styles/main.scss
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
Labels: Removal, Revert, TGUI-Changes

#3967 Imaginary Friends/Split Personalities can no longer occur on catatonic people/playerless monkeys
  code/datums/brain_damage/imaginary_friend.dm
  code/datums/brain_damage/split_personality.dm
Labels: Fix

#3991 Logs emotes
  code/datums/emotes.dm
Labels: Administration

#3986 Fix servant golems created by clockwork cultists not receiving the antag status
  code/datums/mind.dm
Labels: Fix

#3996 Gives brig physician medical's traitor items
  code/modules/uplink/uplink_items.dm
Labels: Feature

#4000 Trash Bag of Holding Cargo Bounty
  code/modules/cargo/bounties/science.dm
Labels: Tweak

#3841 updates british
  code/datums/mutations/speech.dm
  strings/british_talk.json
Labels: Refactor

#3906 fixes ex_act being called multiple times on the same items, thus destroying it in any explosion strengths
  code/controllers/subsystem/explosion.dm
  code/game/atoms.dm
  code/game/machinery/doors/airlock.dm
  code/game/mecha/mecha_defense.dm
  code/game/objects/effects/anomalies.dm
  code/game/objects/items/weaponry.dm
  code/game/objects/obj_defense.dm
  code/game/objects/structures/extinguisher.dm
  code/game/turfs/turf.dm
  code/modules/antagonists/swarmer/swarmer.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/events/processor_overload.dm
  code/modules/holodeck/computer.dm
  code/modules/hydroponics/biogenerator.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/modular_computers/computers/machinery/modular_computer.dm
  code/modules/power/cell.dm
  code/modules/projectiles/guns/misc/beam_rifle.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/special/meteor.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/reagents/chemistry/machinery/reagentgrinder.dm
  code/modules/station_goals/bsa.dm
Labels: Fix, test merged

#2929 Stamina Healing Improvements
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/carbon/status_procs.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  icons/mob/screen_gen.dmi
Labels: Feature, Refactor, Voting, sprites, test merged

#4016 Makes the Detective a real security officer
  code/modules/jobs/job_types/detective.dm
Labels: Feature
