Repository BeeStation/BeeStation-Hornet, pull requests merged in 2021-01, with the labels that each got.

#3274 Random Pill bottle colors
  code/game/objects/items/storage/firstaid.dm
  icons/obj/chemical.dmi
Labels: Feature

#3267 Adds tiny fans to the raven shuttle
  _maps/shuttles/emergency_raven.dmm
Labels: Fix

#3282 Adds a note to syndicate excommunicates during incursion
  code/modules/antagonists/incursion/incursion.dm
Labels: Feature

#3294 A Radiation Math Rework (read: contamination nerf)
  code/__DEFINES/maths.dm
  code/__DEFINES/radiation.dm
  code/__HELPERS/radiation.dm
  code/datums/components/rad_insulation.dm
  code/datums/components/radioactive.dm
  code/datums/radiation_wave.dm
Labels: Balance/Rebalance, Needs Testmerge

#3297 Space Ambience Music: 'Starlight'
  code/__DEFINES/sound.dm
  sound/ambience/qwerty/starlight.ogg
Labels: Feature

#3298 Makes "inverseDir" a global proc
  code/__HELPERS/unsorted.dm
  code/modules/shuttle/shuttle_creation/shuttle_creator.dm
Labels: Code Improvement

#3303 It's no longer spessmess
  icons/ss13_32.png
  icons/ss13_64.png
Labels: Tweak

#3296 Improves extools detection for linux
  code/_compile_options.dm
Labels: server

#2981 Massive crate cost rebalance and fixed multiple cargo money exploits.
  code/game/objects/items/stacks/bscrystal.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/modules/cargo/packs.dm
Labels: Balance/Rebalance, Feature, Removal, Tweak

#3308 Makes emergency shuttle console indestructable
  code/modules/shuttle/emergency.dm
Labels: Fix

#3284 fixes #3269
  code/modules/reagents/chemistry/recipes/others.dm
Labels: Fix

#3286 Adds logging for chemical smoke
  code/game/objects/effects/effect_system/effects_smoke.dm
Labels: Administration

#3266 Adds missing jobs to sages jobs.txt
  config/Sage/jobs.txt
Labels: Feature

#3314 prevent morph from impersonating camera eyes
  code/modules/antagonists/morph/morph.dm
Labels: Fix

#3290 [Port] Fixes log collisions
  code/modules/mob/mob_helpers.dm
Labels: Administration

#3323 Removes mob_has_gravity()
  code/game/area/areas.dm
  code/game/objects/noose.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/living/silicon/robot/robot_movement.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  code/modules/mob/mob_movement.dm
  code/modules/power/gravitygenerator.dm
Labels: Code Improvement, Fix

#3271 More Detective Office ambience
  code/game/area/Space_Station_13_areas.dm
  sound/ambience/ambidet3.ogg
  sound/ambience/ambidet4.ogg
  sound/ambience/license.txt
Labels: Code Improvement, Feature, Sound

#3327 Neurotoxin Rebalance
  code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
  code/modules/projectiles/projectile/special/neurotoxin.dm
Labels: Balance/Rebalance

#3321 [FIX] weapon circuit logging
  code/modules/integrated_electronics/subtypes/manipulation.dm
Labels: Administration

#2964 CE and CMO cloak sprite updated.
  icons/mob/neck.dmi
  icons/obj/clothing/cloaks.dmi
Labels: Feature, Sprites, Vote Passed

#3324 Fixes bluespace tear nullspacing issue
  code/modules/power/singularity/boh_tear.dm
Labels: Fix

#3310 add tiny fan to luxury shuttle poor department
  _maps/shuttles/emergency_luxury.dmm
Labels: Feature

#3108 [PORT] Extools ref tracking frontend from TG and and improvements
  beestation.dme
  code/__DEFINES/qdel.dm
  code/__DEFINES/vv.dm
  code/_compile_options.dm
  code/controllers/subsystem/garbage.dm
  code/controllers/subsystem/throwing.dm
  code/datums/datumvars.dm
  code/game/atoms_movable.dm
  code/game/world.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/view_variables/reference_tracking.dm
  code/modules/admin/view_variables/topic_basic.dm
  code/modules/admin/view_variables/view_variables.dm
Labels: Feature, Fix, Removal

#3328 Cleans up a common mob helper proc
  code/__HELPERS/game.dm
  code/__HELPERS/unsorted.dm
  code/game/machinery/computer/arena.dm
  code/game/objects/effects/effect_system/effects_smoke.dm
  code/game/objects/items/devices/transfer_valve.dm
  code/game/objects/items/tanks/tanks.dm
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/integrated_electronics/subtypes/text.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
Labels: Code Improvement

#3293 Pet Beacons
  code/game/machinery/computer/arcade.dm
  code/game/objects/items/miscellaneous.dm
  code/modules/jobs/job_types/gimmick.dm
Labels: Feature

#3338 Optimize your codebase with one easy trick
  code/__HELPERS/game.dm
Labels: Code Improvement, test merged

#3333 makes nullcrate griefsky a proper syndicate
  code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
Labels: Tweak

#3339 Moves smoke logging to mob logs
  code/game/objects/effects/effect_system/effects_smoke.dm
Labels: Administration

#3080 Adds international garbage day, a day to respect janitors everywhere
  code/__DEFINES/time.dm
  code/modules/holiday/holidays.dm
  code/modules/jobs/job_types/janitor.dm
Labels: Feature, Vote Passed

#3352 Fixed naming issues with some pet beacons
  code/game/objects/items/miscellaneous.dm
Labels: Fix

#3353 Removes CBZ
  code/modules/cargo/packs.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/reagent_containers/bottle.dm
Labels: Removal

#3209 Fix of one forgotten AI feature
  code/modules/keybindings/bindings_client.dm
Labels: Fix

#3042 Adds laughing gas clown internals
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/tanks/tank_types.dm
  icons/mob/belt.dmi
  icons/mob/inhands/equipment/tanks_lefthand.dmi
  icons/mob/inhands/equipment/tanks_righthand.dmi
  icons/obj/tank.dmi
Labels: Feature, Vote Passed

#3357 Fixes a bug/exploit with cloning
  code/game/machinery/cloning.dm
Labels: Fix

#3225 [FIX] Pre Calculates the crate animation math to fix the perfomance issues breaking crate animation
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/crates_lockers/crates/critter.dm
Labels: Code Improvement, Feature, Fix, Refactor

#3347 Adds a new restricted-use comms key for cross-community comms
  code/_globalvars/misc.dm
  code/controllers/configuration/entries/comms.dm
  code/datums/world_topic.dm
  code/game/machinery/computer/communications.dm
  config/Sage/comms.txt
  config/comms.txt
Labels: Config Update, server

#3202 Fixes syndicate hardsuit remaining in EVA mode when head gear is disengaged.
  code/modules/clothing/spacesuits/hardsuit.dm
Labels: Fix

#3371 Fix empty uplink category
  code/modules/uplink/uplink_items.dm
Labels: Fix

#3348 Adds softshell jacket
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/client/loadout/loadout_suit.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/vending/clothesmate.dm
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, Vote Passed

#3387 Fixes some GC issues
  code/game/objects/structures/watercloset.dm
Labels: Fix, Removal, server

#3124 Ion Law Overhaul
  code/modules/events/ion_storm.dm
  strings/ion_laws.json
Labels: Tweak

#3396 Fixes an instance of AAC not working
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Fix

#3157 Improves powertool code + Changes some cases of checking for tool typepaths to tool behaviours instead.
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/debug/multiz.dmm
  _maps/map_files/debug/runtimestation.dmm
  _maps/map_files/generic/CentCom.dmm
  beestation.dme
  code/__DEFINES/traits.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/wallets.dm
  code/game/objects/items/tools/crowbar.dm
  code/game/objects/items/tools/powertools.dm
  code/game/objects/items/tools/screwdriver.dm
  code/game/objects/items/tools/wirecutters.dm
  code/game/objects/items/tools/wrench.dm
  code/game/objects/noose.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/cardboardbox.dm
  code/game/turfs/open/floor.dm
  code/game/turfs/open/floor/fancy_floor.dm
  code/modules/cargo/exports/tools.dm
  code/modules/clothing/suits/utility.dm
  code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
  code/modules/research/designs/tool_designs.dm
  code/modules/surgery/organic_steps.dm
Labels: Code Improvement

#3360 Fixes size powergaming #48913
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Fix

#3206 Adds Ketamine
  code/datums/traits/negative.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/recipes/drugs.dm
Labels: Feature, Vote Passed

#3165 Optional improved / vibrant say formatting
  code/game/objects/effects/mainttraps.dm
  code/game/objects/items/grenades/grenade.dm
  code/game/say.dm
  code/modules/antagonists/blob/blob_mobs.dm
  code/modules/antagonists/changeling/powers/regenerate.dm
  code/modules/antagonists/clock_cult/mobs/clockwork_marauder.dm
  code/modules/antagonists/clock_cult/mobs/cogscarab.dm
  code/modules/antagonists/devil/imp/imp.dm
  code/modules/antagonists/devil/true_devil/_true_devil.dm
  code/modules/antagonists/morph/morph.dm
  code/modules/antagonists/revenant/revenant.dm
  code/modules/antagonists/slaughter/slaughter.dm
  code/modules/antagonists/swarmer/swarmer.dm
  code/modules/awaymissions/mission_code/Cabin.dm
  code/modules/guardian/guardian.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/deputy.dm
  code/modules/mob/living/carbon/alien/alien.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/eldritch_demons.dm
  code/modules/mob/living/simple_animal/friendly/crab.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/friendly/fox.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/mob/living/simple_animal/hostile/bread.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/floor_cluwne.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/mob/living/simple_animal/hostile/killertomato.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
  code/modules/mob/living/simple_animal/hostile/pirate.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm
  code/modules/mob/living/simple_animal/hostile/russian.dm
  code/modules/mob/living/simple_animal/hostile/skeleton.dm
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  code/modules/mob/living/simple_animal/hostile/zombie.dm
  code/modules/mob/living/simple_animal/kalo.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/living/simple_animal/shade.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  tgui/packages/tgui-panel/chat/middleware.js
  tgui/packages/tgui-panel/chat/renderer.js
  tgui/packages/tgui-panel/settings/SettingsPanel.js
  tgui/packages/tgui-panel/settings/reducer.js
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
  tgui/public/tgui-panel.bundle.css
  tgui/public/tgui-panel.bundle.js
Labels: Feature, Tweak

#3075 Locker staff fixes and tweaks
  code/modules/projectiles/projectile/magic.dm
Labels: Code Improvement, Fix, Refactor, Removal, Tweak

#3166 You can remove cuffed orange shoes with your hand
  code/modules/clothing/shoes/colour.dm
Labels: Tweak

#3367 TGUI Panel Stat Hotpatch #1
  code/__DEFINES/stat_panel.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/icons.dm
  code/controllers/subsystem/acid.dm
  code/controllers/subsystem/adjacent_air.dm
  code/controllers/subsystem/air.dm
  code/controllers/subsystem/augury.dm
  code/controllers/subsystem/disease.dm
  code/controllers/subsystem/fire_burning.dm
  code/controllers/subsystem/idlenpcpool.dm
  code/controllers/subsystem/lighting.dm
  code/controllers/subsystem/machines.dm
  code/controllers/subsystem/mobs.dm
  code/controllers/subsystem/npcpool.dm
  code/controllers/subsystem/overlays.dm
  code/controllers/subsystem/processing/processing.dm
  code/controllers/subsystem/spacedrift.dm
  code/controllers/subsystem/stat.dm
  code/controllers/subsystem/sun.dm
  code/controllers/subsystem/tgui.dm
  code/controllers/subsystem/throwing.dm
  code/controllers/subsystem/timer.dm
  code/game/gamemodes/sandbox/h_sandbox.dm
  code/game/verbs.dm
  code/modules/mob/mob_stat.dm
  tgui/packages/tgui-panel/Panel.js
  tgui/packages/tgui-panel/settings/SettingsPanel.js
  tgui/packages/tgui-panel/stat/StatStatus.js
  tgui/packages/tgui-panel/stat/StatTabs.js
  tgui/packages/tgui-panel/stat/StatText.js
  tgui/packages/tgui-panel/stat/index.js
  tgui/packages/tgui-panel/stat/reducer.js
  tgui/packages/tgui-panel/stat/statPanel.js
  tgui/packages/tgui-panel/styles/components/Stat.scss
  tgui/packages/tgui-panel/styles/main.scss
  tgui/packages/tgui-panel/styles/themes/light.scss
  tgui/packages/tgui-panel/themes.js
  tgui/packages/tgui/components/ScrollableBox.js
  tgui/packages/tgui/components/index.js
  tgui/packages/tgui/styles/components/Button.scss
  tgui/packages/tgui/styles/components/Tabs.scss
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.css
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
Labels: Fix, TGUI-Changes, test merged

#3403 fix softshell jacket
  icons/mob/suit.dmi
Labels: Fix

#3402 fix those new errors about compile overlayer in vsc
  code/__DEFINES/subsystems.dm
Labels: Fix

#3316 Adds "search" and "monitor" icons for SecHUDs
  code/game/data_huds.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/computer/warrant.dm
  code/modules/mob/living/carbon/human/human.dm
  icons/mob/hud.dmi
Labels: Feature

#3401 Fixes some mob sprites and corpse loot not matching each other
  code/modules/mob/living/simple_animal/corpse.dm
Labels: Fix

#3404 Minor box medbay (and escape) fixes
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Fix, Tweak

#3374 [Port] Loaded mobs in MULEbots cannot be pulled
  code/modules/mob/living/simple_animal/bot/mulebot.dm
Labels: Code Improvement, Fix

#3285 Refactors cable and disposal pipe construction/deconstruction code to improve performance
  code/modules/power/cable.dm
  code/modules/recycling/disposal/bin.dm
  code/modules/recycling/disposal/construction.dm
  code/modules/recycling/disposal/outlet.dm
  code/modules/recycling/disposal/pipe.dm
Labels: Code Improvement, Fix, Refactor

#3407 Stops sofas from turning into chairs
  code/game/objects/structures/beds_chairs/sofa.dm
Labels: Fix

#3412 TBoH is no longer overwritten by the hammerspace admin spawn item
  code/game/objects/items/storage/bags.dm
Labels: Administration, Fix

#3388 Enables the science shuttle
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/shuttles/science_outpost.dmm
Labels: Tweak

#3381 Ports tgchat sanitization
  tgui/packages/tgui-panel/chat/middleware.js
  tgui/packages/tgui-panel/package.json
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
  tgui/yarn.lock
Labels: Administration

#3415 Fixes a pacifist oversight with curbstomping and groin kicks
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#3382 fixes crate animation breaking at closing
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/crates_lockers/crates/critter.dm
Labels: Fix, Removal, Tweak

#3416 Ghosts can't flip pipes anymore
  code/game/machinery/pipe/construction.dm
Labels: Fix

#3418 Fixes metastation's white ship TRIPLE PROTECTION
  _maps/shuttles/whiteship_meta.dmm
Labels: Fix

#3419 Jaws of life can now force doors when first spawned into the world
  code/game/objects/items/tools/powertools.dm
Labels: Fix

#3424 Cyborgs get Ratvar laws upon conversion
  code/modules/antagonists/clock_cult/servant_of_ratvar.dm
Labels: Fix

#3428 Modernizes the github actions
  .github/.github/autolabeler.yml
  .github/file_labeler.yml
  .github/workflows/compile_changelogs.yml
  .github/workflows/continuous_integration.yml
  .github/workflows/docker.yml
  .github/workflows/extra_pr_labels.yml
  .github/workflows/make_changelogs.yml
  .github/workflows/stale_issues.yml
  .github/workflows/stale_prs.yml
  .github/workflows/update_tgs_dmapi.yml
Labels: GitHub

#3340 Optimizes the game across the board
  code/__HELPERS/game.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/flamethrower.dm
  code/game/objects/items/grenades/flashbang.dm
  code/game/objects/items/robot/robot_items.dm
  code/game/objects/items/storage/secure.dm
  code/game/objects/items/teleportation.dm
  code/game/objects/objs.dm
  code/game/objects/structures/guillotine.dm
  code/game/objects/structures/musician.dm
  code/game/sound.dm
  code/modules/antagonists/changeling/powers/shriek.dm
  code/modules/assembly/infrared.dm
  code/modules/assembly/proximity.dm
  code/modules/assembly/signaler.dm
  code/modules/assembly/timer.dm
  code/modules/client/verbs/looc.dm
  code/modules/economy/account.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/integrated_electronics/subtypes/input.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  code/modules/shuttle/shuttle.dm
  code/modules/surgery/organs/vocal_cords.dm
  code/modules/surgery/surgery_step.dm
Labels: Code Improvement, Needs Testmerge

#3427 Fix securitron not dropping loot
  code/modules/mob/living/simple_animal/bot/secbot.dm
Labels: Fix

#3432 Fixes AI tracking not working near roundstart
  code/modules/mob/living/silicon/ai/freelook/cameranet.dm
Labels: Fix

#3429 Border firelock frames can now be walked through
  code/game/machinery/doors/firedoor.dm
  icons/obj/doors/edge_Doorfire.dmi
Labels: Feature, Tweak, sprites

#3423 Fixes AI wiping core while dead
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Fix

#3414 Replaces remnants of old firelocks on most maps
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Tweak

#3389 Nerfs sawn off shotgun
  code/game/objects/items/robot/robot_items.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/projectiles/ammunition/_firing.dm
  code/modules/projectiles/ammunition/caseless/_caseless.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/energy/dueling.dm
Labels: Balance/Rebalance

#3438 space ruins but they don't destroy themselves by a random spessman that just opened a door
  _maps/RandomRuins/SpaceRuins/Fast_Food.dmm
  _maps/RandomRuins/SpaceRuins/hilbertshoteltestingsite.dmm
  _maps/RandomRuins/SpaceRuins/intactemptyship.dmm
  _maps/RandomRuins/SpaceRuins/shuttlerelic.dmm
  _maps/RandomRuins/SpaceRuins/whiteshipruin_box.dmm
Labels: mapping

#3377 Buff heretic blade
  code/modules/antagonists/eldritch_cult/eldritch_items.dm
Labels: Balance/Rebalance, Vote Passed

#3453 Fix Name on Burn Kits
  code/modules/cargo/packs.dm
Labels: Grammar and Formatting

#3057 Coffee Cart
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/modules/food_and_drinks/kitchen_machinery/food_cart.dm
Labels: Feature, Fix, Vote Passed

#3372 Adds the Prototype Syndicate Teleporter from Paradise Station
  code/__HELPERS/unsorted.dm
  code/game/objects/items/teleportation.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/uplink/uplink_items.dm
  icons/obj/device.dmi
Labels: Feature, Vote Passed, sprites

#3457 Fixes clown megaphone
  code/__DEFINES/say.dm
Labels: Fix

#3449 Improves mulebot movement code
  code/modules/mob/living/simple_animal/bot/mulebot.dm
Labels: Fix

#3459 Fixes IAA message being the wrong way around
  code/modules/antagonists/traitor/IAA/internal_affairs.dm
Labels: Fix

#3322 Roundstart Slimepeople Race: Oozelings
  beestation.dme
  code/__DEFINES/is_helpers.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/names.dm
  code/_globalvars/lists/names.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/cargo/packs.dm
  code/modules/language/language_holder.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species_types/oozelings.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
  code/modules/surgery/organs/lungs.dm
  config/Sage/game_options.txt
  config/game_options.txt
  strings/names/ooze_first.txt
  strings/names/ooze_last.txt
Labels: Code Improvement, Config Update, Feature, Tweak, Vote Passed

#3471 Removes NOBLOOD Trait from Oozelings
  code/modules/mob/living/carbon/human/species_types/oozelings.dm
Labels: Fix

#3464 Fixes radios not working in mechs
  code/__HELPERS/game.dm
Labels: Fix

#3441 Heretics Objective Revision
  code/modules/antagonists/eldritch_cult/eldritch_antag.dm
Labels: Feature, Removal

#3375 Sandbox tweaks with [Ports]
  beestation.dme
  code/game/gamemodes/sandbox/airlock_maker.dm
  code/game/gamemodes/sandbox/h_sandbox.dm
  code/game/gamemodes/sandbox/sandbox.dm
Labels: Feature, Fix, Removal, Tweak

#3331 You can no longer bypass the paraplegic or light drinker quirks
  code/datums/traits/negative.dm
  code/game/objects/items/storage/firstaid.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/surgery/limb_augmentation.dm
  code/modules/vehicles/motorized_wheelchair.dm
Labels: Balance/Rebalance, Code Improvement, Fix

#3474 Adjusts the file labels slightly and makes it a bit easier to read
  .github/file_labeler.yml
Labels: GitHub

#3477 Fixes typo in BZ research points generation
  code/modules/atmospherics/gasmixtures/reactions.dm
Labels: Fix

#3479 Remove duplicate var in teleportation.dm
  code/game/objects/items/teleportation.dm
Labels: Feature

#3478 Ports https://github.com/tgstation/tgstation/pull/44206
  code/modules/atmospherics/machinery/portable/scrubber.dm
Labels: Feature, Fix

#3480 Fixes stat panel not showing map
  code/modules/mob/mob_stat.dm
Labels: Fix

#3436 New syndicate discounts (tm)
  code/modules/uplink/uplink_items.dm
Labels: Feature, Vote Passed

#3458 Clearer secHUD icons
  icons/mob/hud.dmi
Labels: Tweak, sprites

#3447 Fixes weapon circuit runtime and some slightly logging changes
  code/modules/integrated_electronics/subtypes/manipulation.dm
Labels: Feature, Fix, Tweak

#3201 Gives blood brothers better chat colouring.
  code/__DEFINES/colors.dm
  code/game/objects/items/implants/implant_bb.dm
  code/modules/antagonists/brother/brother.dm
Labels: Tweak

#3210 Pipenet fixes
  code/__DEFINES/atmospherics.dm
  code/controllers/subsystem/air.dm
  code/game/objects/items/tanks/tanks.dm
  code/modules/admin/verbs/atmosdebug.dm
  code/modules/atmospherics/gasmixtures/gas_mixture.dm
  code/modules/atmospherics/machinery/components/binary_devices/dp_vent_pump.dm
  code/modules/atmospherics/machinery/components/binary_devices/valve.dm
  code/modules/atmospherics/machinery/components/components_base.dm
  code/modules/atmospherics/machinery/components/trinary_devices/mixer.dm
  code/modules/atmospherics/machinery/datum_pipeline.dm
  code/modules/atmospherics/machinery/portable/portable_atmospherics.dm
Labels: Code Improvement, Fix

#3222 [PORT?] Reworks lighting overlay
  code/modules/power/lighting.dm
  icons/obj/lighting_overlay.dmi
Labels: Code Improvement, Fix

#3152 Shotgun nerf / rebalance
  code/__DEFINES/combat.dm
  code/modules/projectiles/ammunition/ballistic/shotgun.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
Labels: Balance/Rebalance

#3488 Aligns lighting overlays to lighting fixtures on direction changes.
  code/modules/power/lighting.dm
Labels: Fix

#3492 Fix: IV Drip Punctuation
  code/game/machinery/iv_drip.dm
Labels: Fix

#3455 [PORT] SuperLube! from TG
  _maps/RandomRuins/LavaRuins/lavaland_biodome_clown_planet.dmm
  code/__DEFINES/misc.dm
  code/__DEFINES/mobs.dm
  code/datums/components/wet_floor.dm
  code/game/turfs/open/_open.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/reagent_containers/spray.dm
  icons/obj/chemical.dmi
Labels: Feature, Removal, Tweak, Vote Passed, mapping, sprites

#3489 Fixes another MacSpace stuff
  _maps/RandomRuins/SpaceRuins/Fast_Food.dmm
  code/game/turfs/open/water.dm
Labels: Fix, mapping

#3491 Fix aliens not understanding all surgeries
  code/modules/surgery/surgery.dm
Labels: Fix

#3495 Fixes package discounts claiming to be 400% off when they are 75% off.
  code/modules/uplink/uplink_items.dm
Labels: Fix

#3475 Felinids are now forced to use cat tails and ears.
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/synths.dm
Labels: Fix

#3452 Xenobiology Cargo Pack
  code/modules/cargo/packs.dm
Labels: Feature, Vote Passed

#3509 Update axios to 0.21.1
  tgui/packages/tgui-dev-server/package.json
  tgui/yarn.lock
Labels: TGUI-Changes, dependencies

#3511 Makes sunHUDs need advanced sunglasses to be crafted.
  code/datums/components/crafting/tailoring.dm
Labels: Balance/Rebalance

#3508 Prevents GODMODE shades from hanging around
  code/modules/antagonists/wizard/equipment/soulstone.dm
Labels: Administration, Fix

#3483 Oozelings - No Augments, Constantly Clean, Fleshmend Fix, Medibox Fix, Changeling Panacea Fix, Food Buff, Spellcheck fix, Rust Heretic fix
  code/datums/diseases/advance/symptoms/heal.dm
  code/datums/status_effects/buffs.dm
  code/modules/antagonists/changeling/powers/panacea.dm
  code/modules/antagonists/eldritch_cult/knowledge/rust_lore.dm
  code/modules/mob/living/carbon/human/species_types/oozelings.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  code/modules/surgery/limb_augmentation.dm
  code/modules/surgery/prosthetic_replacement.dm
Labels: Balance/Rebalance, Feature, Fix, Grammar and Formatting, Tweak

#3253 Ventcrawling and welding dual-port air vents
  code/modules/atmospherics/machinery/components/binary_devices/dp_vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/mob/living/ventcrawling.dm
Labels: Feature

#3519 Fixes a typo in heart simplemob
  code/modules/mob/living/simple_animal/hostile/heart.dm
Labels: Grammar and Formatting

#3153 New Away Mission map
  _maps/RandomZLevels/TheFactory.dmm
  beestation.dme
  code/modules/awaymissions/mission_code/TheFactory.dm
  code/modules/mob/living/simple_animal/corpse.dm
  code/modules/projectiles/boxes_magazines/internal/shotgun.dm
  code/modules/projectiles/guns/ballistic/laser_gatling.dm
  config/awaymissionconfig.txt
  icons/mob/eyes.dmi
  icons/mob/inhands/weapons/64x_guns_left.dmi
  icons/mob/inhands/weapons/64x_guns_right.dmi
  icons/mob/simple_human.dmi
  icons/obj/clothing/glasses.dmi
  icons/obj/guns/projectile.dmi
  sound/ambience/ambibasement.ogg
  sound/ambience/ambiearth.ogg
  sound/ambience/ambiearthduring.ogg
  sound/ambience/ambifac.ogg
  sound/ambience/ambiwind.ogg
  sound/ambience/secrets.ogg
  sound/ambience/singulambience.ogg
  sound/creatures/bosspain.ogg
  sound/creatures/bosspain2.ogg
  sound/creatures/bosssight.ogg
  sound/creatures/bosssight2.ogg
  sound/creatures/guarddeath.ogg
  sound/creatures/guarddeath2.ogg
  sound/creatures/guarddeath3.ogg
  sound/creatures/guarddeath4.ogg
  sound/creatures/heavydeath1.ogg
  sound/creatures/heavysight1.ogg
  sound/creatures/psycdeath1.ogg
  sound/creatures/psycdeath2.ogg
  sound/creatures/psychattack1.ogg
  sound/creatures/psychdeath.ogg
  sound/creatures/psychdeath2.ogg
  sound/creatures/psychhead.ogg
  sound/creatures/psychhead2.ogg
  sound/creatures/psychidle.ogg
  sound/creatures/psychidle2.ogg
  sound/creatures/psychsight.ogg
  sound/creatures/psychsight2.ogg
  sound/creatures/psycidle1.ogg
  sound/creatures/psycidle2.ogg
  sound/creatures/psycidle3.ogg
  sound/creatures/szombiedeath.ogg
  sound/creatures/szombiesight.ogg
  sound/creatures/szombiesight2.ogg
  sound/creatures/wardendeath.ogg
  sound/effects/radio3.ogg
  sound/spookoween/spookywind.ogg
  sound/weapons/attributions.txt
  sound/weapons/deaglelock.ogg
  sound/weapons/deaglerack.ogg
  sound/weapons/deagleshot.ogg
  sound/weapons/deagleslidedrop.ogg
  sound/weapons/heavyminigunshoot.ogg
  sound/weapons/heavyminigunstart.ogg
  sound/weapons/heavyminigunstop.ogg
  sound/weapons/leveractionrack.ogg
  sound/weapons/leveractionshot.ogg
Labels: Code Improvement, Config Update, Feature, sound, sprites

#3521 Small TGUI stat panel fixes
  code/controllers/subsystem/stat.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/mob/mob_stat.dm
Labels: Administration, Fix

#3525 fix funny mask
  code/modules/clothing/masks/miscellaneous.dm
Labels: Fix

#3456 Insecure Crosscomms newscasters and small QoL
  code/__HELPERS/unsorted.dm
  code/controllers/configuration/entries/comms.dm
  code/controllers/subsystem/ticker.dm
  code/datums/world_topic.dm
  code/game/machinery/computer/communications.dm
  config/Sage/comms.txt
  config/comms.txt
Labels: Config Update, Feature, server

#3502 Halves the chance of floor tile ripping.
  code/modules/atmospherics/environmental/LINDA_turf_tile.dm
Labels: Vote Passed

#3524 Lets slow this dance down
  config/game_options.txt
Labels: Config Update

#3516 Fixes a runtime when crawling in dual-port air vents
  code/modules/mob/living/ventcrawling.dm
Labels: Fix

#3490 Allow Admins to Add/Remove Traits (tg#45503)
  beestation.dme
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/datumvars.dm
  code/modules/admin/verbs/randomverbs.dm
Labels: Administration

#3528 [PORT] Cryoxadone taste improvement
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Tweak

#3522 Oozeling Sprite Changes
  code/modules/mob/living/carbon/human/species_types/oozelings.dm
  icons/mob/human_parts_greyscale.dmi
Labels: Feature, Fix, sprites

#3421 Bluespace Miner Config
  code/controllers/configuration/entries/game_options.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/modules/research/techweb/all_nodes.dm
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Config Update

#3070 [bounty] transformative Crossbreeds (black)
  beestation.dme
  code/__DEFINES/mobs.dm
  code/_onclick/other_mobs.dm
  code/datums/mind.dm
  code/datums/spawners_menu.dm
  code/game/atoms_movable.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/obj_defense.dm
  code/modules/cargo/exports/xenobio.dm
  code/modules/food_and_drinks/kitchen_machinery/processor.dm
  code/modules/mob/living/carbon/alien/alien_defense.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/monkey/monkey_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/robot/robot_defense.dm
  code/modules/mob/living/simple_animal/animal_defense.dm
  code/modules/mob/living/simple_animal/slime/life.dm
  code/modules/mob/living/simple_animal/slime/powers.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  code/modules/research/xenobiology/crossbreeding/transformative.dm
  code/modules/research/xenobiology/xenobiology.dm
  code/modules/surgery/core_removal.dm
  icons/obj/slimecrossing.dmi
Labels: Feature, Needs Wiki Changes, Vote Passed, sprites

#3205 Better Spells Vol. 2
  code/datums/action.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/debug.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/spells/spell.dm
  code/modules/spells/spell_types/barnyard.dm
  code/modules/spells/spell_types/cluwnecurse.dm
  code/modules/spells/spell_types/construct_spells.dm
  code/modules/spells/spell_types/godhand.dm
  code/modules/spells/spell_types/touch_attacks.dm
Labels: Tweak

#3529 0 gax mixes and unstated temperatures purged
  _maps/RandomZLevels/TheFactory.dmm
  _maps/RandomZLevels/caves.dmm
  _maps/RandomZLevels/snowdin.dmm
  _maps/RandomZLevels/undergroundoutpost45.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  code/game/turfs/open/floor/plating/asteroid.dm
  code/game/turfs/open/floor/plating/misc_plating.dm
  code/modules/awaymissions/mission_code/snowdin.dm
Labels: Fix, mapping

#3512 Buffs shotgun slugs
  code/modules/projectiles/projectile/bullets/shotgun.dm
Labels: Balance/Rebalance

#3496 Felinids always land on their feet when falling.
  code/modules/mob/living/carbon/human/human.dm
Labels: Tweak

#3204 Fixes energy bolas ignoring catching and other throw checks.
  code/game/objects/items/handcuffs.dm
Labels: Fix

#3160 Pool party
  _maps/RandomRuins/SpaceRuins/spacehotel.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/shuttles/emergency_luxury.dmm
  beestation.dme
  code/__DEFINES/components.dm
  code/__DEFINES/movespeed_modification.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/squidpeople.dm
  code/modules/pool/components/swimming.dm
  code/modules/pool/components/swimming_dissolve.dm
  code/modules/pool/components/swimming_ethereal.dm
  code/modules/pool/components/swimming_felinid.dm
  code/modules/pool/components/swimming_golem.dm
  code/modules/pool/components/swimming_squid.dm
  code/modules/pool/pool.dm
  code/modules/pool/pool_items.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/mob/inhands/weapons/melee_lefthand.dmi
  icons/mob/inhands/weapons/melee_righthand.dmi
  icons/obj/pool.dmi
  sound/effects/splash.ogg
  sound/effects/splosh.ogg
Labels: Feature

#3535 emergency fix
  _maps/map_files/Deltastation/DeltaStation2.dmm
  code/modules/pool/components/swimming.dm
Labels: Fix, Removal, mapping

#3536 Fixes pool noodles being cleanable
  code/modules/pool/pool.dm
  code/modules/pool/pool_items.dm
Labels: Fix

#3533 Oozelings die in the pool
  code/modules/mob/living/carbon/human/species_types/oozelings.dm
  code/modules/pool/components/swimming_dissolve.dm
Labels: Feature, Fix

#3530 Cleans up late joining, fixes admins failing to join.
  code/modules/mob/dead/new_player/new_player.dm
Labels: Fix
