Repository BeeStation/BeeStation-Hornet, pull requests merged in 2021-02, with the labels that each got.

#3538 Fixes rainbow slimes
  code/modules/mob/living/simple_animal/slime/powers.dm
Labels: Fix

#3460 Replaces plasmaglass windows on lavaland with a lava moat.
  _maps/map_files/Mining/Lavaland.dmm
Labels: Feature, Removal, mapping

#3454 Small Heretics Buff
  code/modules/antagonists/eldritch_cult/eldritch_items.dm
  code/modules/antagonists/eldritch_cult/eldritch_magic.dm
  code/modules/antagonists/eldritch_cult/knowledge/ash_lore.dm
  code/modules/antagonists/eldritch_cult/knowledge/rust_lore.dm
Labels: Balance/Rebalance, Feature, Tweak, Vote Passed

#3433 tgui: Abductors
  beestation.dme
  code/modules/antagonists/abductor/equipment/orderable_gear.dm
  code/modules/antagonists/abductor/machinery/console.dm
  code/modules/antagonists/abductor/machinery/dispenser.dm
  code/modules/antagonists/abductor/machinery/experiment.dm
  tgui/packages/tgui/interfaces/AbductorConsole.js
  tgui/packages/tgui/interfaces/GlandDispenser.js
  tgui/packages/tgui/interfaces/ProbingConsole.js
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: Feature, Tweak

#3422 Makes it harder to meta heretics through poppies and kitchen knives
  code/_globalvars/lists/maintenance_loot.dm
  code/datums/components/crafting/recipes.dm
  code/datums/mood_events/generic_positive_events.dm
  code/game/objects/items/kitchen.dm
  code/game/objects/items/weaponry.dm
  code/modules/clothing/under/accessories.dm
  icons/obj/clothing/accessories.dmi
Labels: Feature, Tweak, Vote Passed

#3540 Halved most window integrity, now only double of pre-fastmos
  code/game/objects/structures/window.dm
Labels: Balance/Rebalance, Vote Passed

#3545 Fix Multiple Citation Bugs
  code/game/machinery/computer/security.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: Feature, Fix, Removal

#3203 Cap slaughter & laughter demons to 1 each
  code/modules/antagonists/wizard/equipment/spellbook.dm
Labels: Balance/Rebalance, Vote Failed

#3520 [bounty] Adminbuse race conversion/hypnosis machine!
  beestation.dme
  code/game/machinery/race_converter.dm
Labels: Feature

#3552 Xenos now break firelock window shutters instead of opening them
  code/game/machinery/doors/firedoor.dm
Labels: Tweak

#3553 Fixes a few rogue AIStatus usages
  code/controllers/subsystem/idlenpcpool.dm
  code/controllers/subsystem/npcpool.dm
  code/modules/mob/living/simple_animal/eldritch_demons.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/swarmer.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Fix

#3507 Adds an atmosbot to the mining base and fixes up outpost access
  _maps/map_files/Mining/Lavaland.dmm
Labels: mapping

#3562 Poppy pin removal fix
  code/datums/components/crafting/recipes.dm
Labels: Fix

#3560 Fixes thermomachines being able to run without power
  code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
Labels: Fix

#3469 Fix Changeling Absorbtion Bug
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/changeling/powers/absorb.dm
Labels: Fix

#3527 Some balance changes on Factory away mission
  _maps/RandomZLevels/TheFactory.dmm
  code/modules/awaymissions/mission_code/TheFactory.dm
Labels: Balance/Rebalance, mapping

#3369 Hot Chocolate now works like chocolate
  code/datums/diseases/transformation.dm
  code/modules/events/vent_clog.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/food/snacks_pastry.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/food_and_drinks/recipes/food_mixtures.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
Labels: Feature

#3568 You can take out lighter with alt
  code/game/objects/items/storage/fancy.dm
Labels: Tweak

#3572 [PORT] [s] Sanitizes modular console ID edits
  code/modules/modular_computers/file_system/programs/card.dm
Labels: Fix

#3569 Improves throw mode
  code/_onclick/click.dm
  code/modules/mob/living/carbon/carbon.dm
Labels: Tweak

#3558 Elite Strike Team Location Track Assister 9000
  beestation.dme
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/hud.dm
  code/datums/action.dm
  code/datums/components/team_monitor.dm
  code/game/alternate_appearance.dm
  code/game/machinery/syndicatebomb.dm
  code/modules/antagonists/ert/ert.dm
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
  code/modules/antagonists/nukeop/nukeop.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/uplink/uplink_items.dm
  icons/mob/actions.dmi
  icons/mob/hud.dmi
Labels: Feature, sprites

#3576 Removes ancient synth
  _maps/RandomZLevels/TheFactory.dmm
  code/modules/awaymissions/mission_code/TheFactory.dm
Labels: Removal, mapping

#3542 Add turret control panel to the syndicate shuttle
  _maps/shuttles/infiltrator_basic.dmm
  code/game/machinery/porta_turret/portable_turret.dm
Labels: Feature, mapping

#3582 Makes nullcrate beepsky EMP proof
  code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
Labels: Tweak

#3584 Fixes runtimes at wild west load
  code/modules/antagonists/cult/cult_structures.dm
Labels: Fix

#3577 Various GC fixes
  code/modules/antagonists/cult/cult_comms.dm
  code/modules/mob/living/carbon/human/species_types/squidpeople.dm
  code/modules/mob/living/simple_animal/slime/death.dm
  code/modules/mob/living/simple_animal/slime/powers.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  code/modules/mob/mob.dm
Labels: Fix, Removal

#3517 New antag objective: Steal Blackbox (tg#49298)
  code/game/gamemodes/objective_items.dm
  code/game/machinery/telecomms/machines/message_server.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/stationobjs.dmi
Labels: Feature, Vote Passed, sprites

#3580 Plasma taste change
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
Labels: Tweak

#3591 Atropine/Hepanephrodaxon fix
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Fix

#3593 Xenobiology: Buffs /datum/status_effect/in_love
  code/datums/status_effects/neutral.dm
Labels: Balance/Rebalance

#3559 You can now tuck plushies and nuke disks into bed
  beestation.dme
  code/datums/elements/bed_tucking.dm
  code/game/objects/items/plushes.dm
  code/game/objects/structures/bedsheet_bin.dm
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
Labels: Feature

#3565 Removes bolt of change from Chaos Carp
  code/modules/events/wizard/magicarp.dm
Labels: Balance/Rebalance

#3592 Xenobiology: Nerfs /obj/item/slimepotion/speed
  code/modules/research/xenobiology/xenobiology.dm
Labels: Balance/Rebalance

#3600 [Port] Fixes railings
  code/game/objects/structures/railings.dm
Labels: Fix

#3567 Fixes weird unicode rendering in station announcements
  code/__HELPERS/priority_announce.dm
Labels: Fix

#3550 [PORT] 2 PRs from Project>Features, missed file change
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/datums/components/material_container.dm
  code/game/machinery/computer/arcade.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
Labels: Feature, Removal, Tweak, mapping

#3561 Makes the Brig Physician antag eligible, removes security officer specific access and items
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/devil/devil_game_mode.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/eldritch_cult/eldritch_cult.dm
  code/game/gamemodes/gangs/gangs.dm
  code/game/gamemodes/incursion/incursion.dm
  code/game/gamemodes/overthrow/overthrow.dm
  code/game/gamemodes/revolution/revolution.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/antagonists/traitor/traitor_spawner.dm
  code/modules/events/special_antag_event.dm
  code/modules/jobs/job_types/brigphys.dm
Labels: Balance/Rebalance, Tweak

#3307 Makes energy guns bigger
  code/modules/clothing/outfits/ert.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
  code/modules/projectiles/guns/energy/laser.dm
Labels: Tweak

#3598 Small crate animation adjustments and coffin animation
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/crates_lockers/crates/critter.dm
  code/game/objects/structures/crates_lockers/crates/large.dm
  code/game/objects/structures/crates_lockers/crates/secure.dm
  code/modules/mining/abandoned_crates.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  icons/obj/crates.dmi
Labels: Feature, Fix, Removal, Tweak, sprites

#3601 Nitryl Gloves reduce firefighter carry delay (tg#46735)
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/modules/clothing/gloves/color.dm
  code/modules/mob/living/carbon/human/human.dm
  icons/mob/hands.dmi
Labels: Feature, Removal, sprites

#3590 Bumping into grilles damages them
  code/game/objects/structures/grille.dm
Labels: Tweak

#3329 balances bluespace miners
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/research/designs/machine_designs.dm
Labels: Balance/Rebalance

#3603 Miscellaneous fixes (2021-02-10)
  code/game/objects/effects/mines.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/monkey/combat.dm
  code/modules/mob/living/simple_animal/slime/life.dm
  code/modules/pool/pool.dm
Labels: Fix

#3611 Oozelings are not part of slime faction
  code/modules/mob/living/carbon/human/species_types/oozelings.dm
Labels: Balance/Rebalance

#3617 Oozeling translucency tweak
  icons/mob/human_parts_greyscale.dmi
Labels: Tweak, sprites

#3613 removes zesko from codeowners
  .github/CODEOWNERS
Labels: GitHub

#3555 drip tgstation#56491
  code/modules/client/loadout/loadout_footwear.dm
  code/modules/client/loadout/loadout_uniform.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/under/costume.dm
  icons/mob/feet.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, Vote Passed, sprites

#3437 Brings Heretics Up To Date
  code/game/alternate_appearance.dm
  code/modules/antagonists/eldritch_cult/eldritch_antag.dm
  code/modules/antagonists/eldritch_cult/eldritch_book.dm
  code/modules/antagonists/eldritch_cult/eldritch_effects.dm
  code/modules/antagonists/eldritch_cult/eldritch_items.dm
  code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
  code/modules/antagonists/eldritch_cult/eldritch_monster_antag.dm
  code/modules/antagonists/eldritch_cult/knowledge/ash_lore.dm
  code/modules/antagonists/eldritch_cult/knowledge/flesh_lore.dm
  code/modules/antagonists/eldritch_cult/knowledge/rust_lore.dm
Labels: Balance/Rebalance, Grammar and Formatting, Tweak, Voting

#3623 Fixes a few runtimes
  code/__HELPERS/roundend.dm
  code/controllers/subsystem/ambience.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/antagonists/traitor/IAA/internal_affairs.dm
Labels: Code Improvement, Fix

#3450 Heretics' Mansus Grasp Lays Runes
  code/modules/antagonists/eldritch_cult/eldritch_book.dm
  code/modules/antagonists/eldritch_cult/eldritch_magic.dm
Labels: Balance/Rebalance

#3629 Fixes valentines
  code/modules/events/holiday/vday.dm
Labels: Fix

#3630 Update vday.dm
  code/modules/events/holiday/vday.dm
Labels: Fix

#3624 Miscellaneous fixes (2021-02-13)
  code/datums/brain_damage/phobia.dm
  code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
  code/modules/atmospherics/machinery/datum_pipeline.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/mob/living/silicon/ai/vox_sounds.dm
  code/modules/mob/mob.dm
  code/modules/pool/pool_items.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/surgery/tools.dm
  code/modules/uplink/uplink_items.dm
Labels: Fix

#3608 Added the ability to freely change chat fonts
  tgui/packages/tgui-panel/settings/SettingsPanel.js
  tgui/packages/tgui-panel/settings/constants.js
  tgui/packages/tgui-panel/settings/middleware.js
  tgui/packages/tgui-panel/settings/reducer.js
  tgui/packages/tgui/styles/components/Dropdown.scss
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.css
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
Labels: TGUI-Changes

#3619 Solves centcom escape exploits.
  _maps/map_files/generic/CentCom.dmm
  code/game/turfs/closed/wall/misc_walls.dm
  icons/turf/walls.dmi
Labels: mapping, sprites

#3622 Gives Laughter (reagent) a new functionality
  code/datums/components/mood.dm
  code/datums/mood_events/generic_positive_events.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
Labels: Feature

#3615 [Port] tgui: RCD Access Control
  code/game/machinery/doors/airlock_electronics.dm
  code/game/objects/items/RCD.dm
  code/game/turfs/open/floor.dm
Labels: Feature, Tweak

#3610 Removes Sec Holobarriers from lockers, adds them to vendors.
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/vending/security.dm
Labels: Feature, Removal

#3554 Fixes slimes randomly no longer processing
  code/controllers/subsystem/npcpool.dm
  code/modules/mob/living/simple_animal/slime/life.dm
Labels: Fix

#3632 Miscellaneous fixes (2021-02-14)
  code/controllers/subsystem/vis_overlays.dm
  code/datums/diseases/advance/advance.dm
  code/game/atoms_movable.dm
  code/game/machinery/computer/arcade.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/hostile/venus_human_trap.dm
  code/modules/shuttle/special.dm
Labels: Fix

#3596 [PORT] Cryotube reagent fix, tweaks and Extinguishes mob on fire
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Code Improvement, Feature, Fix, Tweak

#3639 Fixes firelocks and window doors not updating atmos properly on destroy and keeping pressure
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doors/windowdoor.dm
Labels: Fix

#3635 Brig Phys Locker Can Actually Be Opened Again
  code/__DEFINES/access.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/jobs/job_types/brigphys.dm
Labels: Fix

#3643 Stops qdeleted pipes from building pipeline
  code/modules/atmospherics/machinery/datum_pipeline.dm
Labels: Fix, Removal

#3641 Miscellaneous fixes (2021-02-15)
  code/game/objects/items/RCD.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/modules/mining/equipment/kinetic_crusher.dm
  code/modules/mob/mob_stat.dm
  code/modules/ruins/objects_and_mobs/ash_walker_den.dm
Labels: Fix

#3648 Miscellaneous Fixes (2021-02-16)
  code/__HELPERS/global_lists.dm
  code/_globalvars/lists/objects.dm
  code/datums/components/team_monitor.dm
  code/game/mecha/mech_fabricator.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/admin/permissionedit.dm
  code/modules/mining/machine_vending.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/modular_computers/computers/item/computer_ui.dm
  code/modules/modular_computers/file_system/program.dm
  code/modules/power/singularity/collector.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/research/rdconsole.dm
  code/modules/tgui/tgui.dm
Labels: Administration, Code Improvement, Fix

#3640 Adds gas miners to every map. There are 3 maps that already have them, all maps should have them.
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, mapping

#3544 Adds vault door to gulag
  _maps/map_files/Mining/Lavaland.dmm
Labels: Feature, mapping

#3653 The View Audit Hotfix 1
  code/game/objects/items/grenades/spawnergrenade.dm
  code/game/objects/items/storage/secure.dm
  code/modules/power/supermatter/supermatter.dm
  code/modules/spells/spell_types/godhand.dm
  code/modules/tgui/states.dm
Labels: Fix

#3654 The View Audit Hotfix 2
  code/__HELPERS/game.dm
  code/modules/mining/equipment/mineral_scanner.dm
Labels: Fix

#3616 [Port] Fixes the atmos subsystem locking up on rare occasions
  code/controllers/subsystem/air.dm
Labels: Fix

#3656 Miscellaneous fixes (2021-02-17)
  code/controllers/subsystem/ambience.dm
  code/game/objects/items/miscellaneous.dm
  code/modules/admin/sql_message_system.dm
  code/modules/antagonists/blob/overmind.dm
  code/modules/antagonists/changeling/powers/headcrab.dm
  code/modules/cargo/packs.dm
  code/modules/crew_objectives/security_objectives.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Administration, Code Improvement, Fix

#3659 Upgrades clockie code
  beestation.dme
  code/game/gamemodes/clock_cult/clockcult.dm
  code/modules/antagonists/clock_cult/helpers/servant_warp.dm
  code/modules/antagonists/clock_cult/items/clockwork_slab.dm
  code/modules/tgui/states/clockcult_state.dm
Labels: Code Improvement

#3280 Re-adds apid dash, adds honeycomb crafting for apids
  code/__DEFINES/DNA.dm
  code/__DEFINES/is_helpers.dm
  code/datums/action.dm
  code/datums/components/crafting/crafting.dm
  code/datums/mutations/cold.dm
  code/game/objects/effects/effect_system/effects_smoke.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/stacks/tiles/tile_mineral.dm
  code/game/turfs/open/floor/fancy_floor.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_drink.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/species_types/apid.dm
  code/modules/mob/living/living.dm
  code/modules/surgery/organs/wings.dm
  icons/mob/actions/actions_spells.dmi
  icons/mob/inhands/misc/tiles_lefthand.dmi
  icons/mob/inhands/misc/tiles_righthand.dmi
  icons/obj/stack_objects.dmi
  icons/obj/tiles.dmi
  icons/turf/floors.dmi
Labels: Balance/Rebalance, Feature, Removal, Vote Passed, sprites

#3634 Cap slimepeople duping
  code/controllers/configuration/entries/game_options.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Balance/Rebalance, Config Update

#3651 Port airlock painter fixes and code cleanups
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/airlock_types.dm
  code/game/objects/items/airlock_painter.dm
  code/modules/antagonists/clock_cult/clockwork_turfs.dm
Labels: Code Improvement, Feature, Fix, Refactor, Tweak

#3671 Emoji filtered word fix
  icons/emoji.dmi
Labels: Fix, sprites

#3673 Fix pubby SM roundstart gas mix
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Fix, mapping

#3682 adds air alarm to morgue on Box Station
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Feature, mapping

#3676 Fixes private cargo purchases ignoring crate access restrictions
  code/game/objects/structures/crates_lockers/crates/secure.dm
  code/modules/shuttle/supply.dm
Labels: Fix

#3420 Updated bishop outfit sprites, added bishop cloak and black bishop outfit
  code/modules/client/loadout/loadout_accessories.dm
  code/modules/client/loadout/loadout_hat.dm
  code/modules/client/loadout/loadout_suit.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/suits/chaplainsuits.dm
  code/modules/clothing/suits/cloaks.dm
  code/modules/vending/wardrobes.dm
  icons/mob/head.dmi
  icons/mob/neck.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/cloaks.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, Tweak, sprites

#3657 Now is time to sanitize pickweight
  code/__HELPERS/_lists.dm
Labels: Code Improvement, Fix

#3686 Removes :p and :d radio hotkeys.
  code/__DEFINES/say.dm
  code/modules/mob/dead/observer/say.dm
  code/modules/mob/living/say.dm
Labels: Removal

#3690 Miscellaneous fixes (2021-02-20)
  code/game/machinery/firealarm.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/assembly/assembly.dm
  code/modules/atmospherics/machinery/components/binary_devices/dp_vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/outlet_injector.dm
  code/modules/atmospherics/machinery/components/unary_devices/passive_vent.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/he_pipes.dm
  code/modules/mining/fulton.dm
  code/modules/mob/living/silicon/ai/ai_defense.dm
  code/modules/power/singularity/emitter.dm
  code/modules/projectiles/autofire.dm
Labels: Fix, test merged

#3667 Miscellaneous fixes (2021-02-18)
  code/datums/mind.dm
  code/game/gamemodes/clock_cult/clockcult.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/modules/antagonists/clock_cult/items/clockwork_slab.dm
  code/modules/antagonists/swarmer/swarmer.dm
  code/modules/power/turbine.dm
Labels: Fix

#3675 Fix minor issues with the clockwork cult
  code/__DEFINES/clockcult.dm
  code/game/gamemodes/clock_cult/clockcult.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/modules/antagonists/clock_cult/clockwork_massive.dm
  code/modules/antagonists/clock_cult/mobs/eminence.dm
  code/modules/antagonists/clock_cult/servant_of_ratvar.dm
  code/modules/mob/living/living.dm
Labels: Feature, Fix, Tweak

#3678 Updates Herald sprites, animations and prophet cloak.
  icons/mob/lavaland/lavaland_elites.dmi
  icons/mob/neck.dmi
  icons/obj/lavaland/elite_trophies.dmi
Labels: Feature, Tweak, sprites

#3695 Makes purchases actually check that you actually purchased it.
  code/datums/components/uplink.dm
  code/modules/uplink/uplink_purchase_log.dm
Labels: Fix

#3687 [PORT] fixes the lava not burning things inside problem
  code/game/turfs/open/lava.dm
Labels: Tweak

#3445 Crucifixes and Warding Off Curses
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/game/objects/items/holy_weapons.dm
  code/modules/antagonists/eldritch_cult/eldritch_items.dm
  code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
  code/modules/cargo/packs.dm
  code/modules/spells/spell_types/barnyard.dm
  code/modules/spells/spell_types/curse.dm
  code/modules/vending/wardrobes.dm
  icons/obj/objects.dmi
Labels: Feature, Fix, Vote Passed, sprites

#3701 Adds check_click_intercept for revenants
  code/modules/antagonists/revenant/revenant_abilities.dm
Labels: Fix

#3658 Buffs my little cogchamps.
  code/game/mecha/mecha.dm
  code/modules/antagonists/clock_cult/clockwork_massive.dm
  code/modules/antagonists/clock_cult/clockwork_turfs.dm
  code/modules/antagonists/clock_cult/helpers/clockcult_ending.dm
  code/modules/antagonists/clock_cult/items/brass_clothing.dm
  code/modules/antagonists/clock_cult/items/clockwork_weapon.dm
  code/modules/antagonists/clock_cult/mobs/clockwork_marauder.dm
  code/modules/antagonists/clock_cult/mobs/eminence.dm
  code/modules/antagonists/clock_cult/scriptures/abscond.dm
  code/modules/antagonists/clock_cult/scriptures/abstraction_crystal.dm
  code/modules/antagonists/clock_cult/scriptures/clockwork_armaments.dm
  code/modules/antagonists/clock_cult/scriptures/dimensional_breach.dm
  code/modules/antagonists/clock_cult/scriptures/interdiction_lens.dm
  code/modules/antagonists/clock_cult/scriptures/ocular_warden.dm
  code/modules/antagonists/clock_cult/scriptures/prosperity_prism.dm
  code/modules/antagonists/clock_cult/scriptures/sentinels_compromise.dm
  code/modules/antagonists/clock_cult/scriptures/sigil_of_vitality.dm
  code/modules/antagonists/clock_cult/scriptures/stargazer.dm
  code/modules/antagonists/clock_cult/scriptures/summon_marauder.dm
  code/modules/antagonists/clock_cult/scriptures/vanguard.dm
  code/modules/antagonists/clock_cult/servant_of_ratvar.dm
  code/modules/power/apc.dm
  code/modules/power/lighting.dm
Labels: Balance/Rebalance, Feature, Tweak

#3652 Fix morph becoming invisible and unclickable if it disguises as an airlock
  code/modules/antagonists/morph/morph.dm
Labels: Fix

#3702 Every spider action now requires consciousness
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
Labels: Fix

#3705 The View Audit Hotfix 3
  code/modules/antagonists/eldritch_cult/eldritch_effects.dm
  code/modules/antagonists/morph/morph.dm
Labels: Fix

#3711 make ruko happy / add a cautery to CentCom
  _maps/map_files/generic/CentCom.dmm
Labels: Feature, mapping

#3719 Area mood fixes
  code/datums/components/mood.dm
  code/game/area/Space_Station_13_areas.dm
Labels: Fix

#3668 Remove the extended gamemode from Sage
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Config Update

#3661 Disable jobs.txt loading.
  config/Sage/config.txt
  config/config.txt
Labels: Config Update

#3722 Adds Topic() calls to get and adjust metacoins
  code/datums/world_topic.dm
Labels: server

#3674 Miscellaneous fixes (2021-02-19)
  code/modules/admin/antag_panel.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
Labels: Administration, Fix

#3482 Allows the use of shovel on stacks of grass
  code/game/objects/items/stacks/tiles/tile_types.dm
Labels: Feature

#3698 Metastation Coldroom and Cryogenics fixes
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Fix, mapping

#3694 Repaths skinsuits, moves them from boxes to o2 lockers
  code/game/objects/items/storage/boxes.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  icons/obj/clothing/suits.dmi
Labels: Feature, Removal, Tweak, sprites

#3726 Adjust firelock reclose delay
  code/game/machinery/doors/firedoor.dm
Labels: Tweak

#3325 [bounty] Warping Crossbreeds (bluespace)
  _maps/templates/warped_room.dmm
  beestation.dme
  code/game/objects/effects/forcefields.dm
  code/game/objects/empulse.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  code/modules/research/xenobiology/crossbreeding/warping.dm
  code/modules/research/xenobiology/xenobiology.dm
  icons/obj/slimecrossing.dmi
Labels: Feature, Vote Passed, mapping, sprites

#3395 Removes ability to ban players from specific gimmick roles
  code/datums/datacore.dm
  code/game/gamemodes/clock_cult/clockcult.dm
  code/game/gamemodes/game_mode.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/antagonists/creep/creep.dm
  code/modules/jobs/job_types/gimmick.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/modular_computers/file_system/programs/card.dm
Labels: Administration

#3398 Block abductors from AI sat
  code/game/area/ai_monitored.dm
  code/modules/antagonists/abductor/machinery/camera.dm
Labels: Balance/Rebalance

#3487 step sounds
  code/datums/components/footstep.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/suits/_suits.dm
  code/modules/clothing/suits/armor.dm
  code/modules/mob/living/carbon/human/species_types/IPC.dm
Labels: Feature, Vote Passed

#3476 Updates telecommunications interceptor for circuits.
  code/_globalvars/lists/objects.dm
  code/game/machinery/telecomms/machines/receiver.dm
  code/modules/integrated_electronics/subtypes/input.dm
Labels: Balance/Rebalance

#3727 [PORT] Fix security camera console not following moving borgs
  code/game/machinery/computer/camera.dm
Labels: Fix

#3736 Fix Crystalline Gold Crossbreed
  code/modules/research/xenobiology/crossbreeding/_structures.dm
Labels: Code Improvement, Fix, Refactor, Tweak

#3747 add a real microwave to the bluesbace room.
  _maps/templates/warped_room.dmm
Labels: Feature, mapping

#3730 [Bounty] Camera Implant
  beestation.dme
  code/game/objects/items/implants/implant_camera.dm
Labels: Feature

#3752 Protects Heads From Being Antags on Golden
  config/game_options.txt
Labels: Config Update

#3748 Prevents Die of Fate spam
  code/modules/awaymissions/mission_code/Academy.dm
Labels: Fix

#3696 Removes nullcrates
  code/modules/cargo/packs.dm
  code/modules/uplink/uplink_items.dm
Labels: Removal

#3749 Fix of a surgery runtime for cyborgs
  code/modules/surgery/helpers.dm
Labels: Fix

#3759 Temporary fix for Warping gold crossbreed
  code/modules/research/xenobiology/crossbreeding/warping.dm
Labels: Tweak

#3725 Updates Hos Coat.
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, Vote Passed, sprites

#3757 Updates Descriptions for #3450.
  code/modules/antagonists/eldritch_cult/eldritch_book.dm
  code/modules/antagonists/eldritch_cult/eldritch_magic.dm
Labels: Fix

#3738 Moves input bar under the chat
  interface/skin.dmf
  tgui/packages/tgui-panel/index.js
  tgui/public/tgui-panel.bundle.js
  tgui/yarn.lock
Labels: TGUI-Changes, Tweak

#3740 Fixes Brig Physician permissions / Sec perm cleanup
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  code/__DEFINES/access.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/brigphys.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/warden.dm
Labels: Feature, Tweak, mapping

#3772 Upgrades TGUI's marked dependency to ^2.0.0
  tgui/packages/tgui/package.json
  tgui/public/tgui-common.chunk.js
  tgui/yarn.lock
Labels: TGUI-Changes

#3765 Hygiene is now tied to mood
  code/__DEFINES/atmospherics.dm
  code/__DEFINES/mobs.dm
  code/datums/components/mood.dm
  code/datums/mood_events/needs_events.dm
  code/datums/traits/neutral.dm
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Balance/Rebalance, Code Improvement, Tweak, Vote Passed
