Repository BeeStation/BeeStation-Hornet, pull requests merged in 2021-06, with the labels that each got.

#4401 port tg's machinery processing refactor
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/machines.dm
  code/game/atoms.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/defibrillator_mount.dm
  code/game/machinery/rechargestation.dm
  code/game/machinery/syndicatebomb.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/mining/machine_processing.dm
  code/modules/mining/machine_redemption.dm
  code/modules/mining/machine_unloading.dm
  code/modules/mining/mint.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/chemistry/machinery/smoke_machine.dm
  code/modules/recycling/conveyor2.dm
  code/modules/station_goals/shield.dm
Labels: Code Improvement, Refactor

#4430 Minor optimizations to `propagate_network()`
  code/modules/power/power.dm
Labels: Refactor

#4391 Staff now have access to donor items
  code/modules/client/preferences.dm
Labels: Feature

#4443 Allows blind people to feel around them to examine things
  code/__DEFINES/mobs.dm
  code/__HELPERS/mobs.dm
  code/game/atoms.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
Labels: Tweak

#4450 Makes the hos gun set to stun have an inhand icon
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
Labels: Feature, sprites

#4452 Fixes runtime in death.dm
  code/modules/mob/living/death.dm
Labels: Fix

#4249 Changes volume pumps to normal pumps in meta's SM
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: mapping

#4262 Head revs cannot deplete flashes.
  code/modules/antagonists/revolution/revolution.dm
  code/modules/assembly/flash.dm
Labels: Tweak

#4403 Fixes mat duping using the autolathe
  code/game/machinery/fabricators/modular_fabricator.dm
Labels: Fix

#4367 Makes multi z pipes layer-compatible
  code/modules/atmospherics/multiz.dm
  icons/obj/atmos.dmi
Labels: Feature, sprites

#4389 Adds a preference to switch walk hotkey toggle.
  code/datums/keybinding/mob.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_toggles.dm
Labels: Feature, Tweak

#4444 Fixes equipment not spawning
  code/game/gamemodes/objective.dm
Labels: Fix

#4427 Roboticist jumpsuit + envirosuit resprite
  icons/mob/head.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, Voting, sprites

#4447 Changes the thermomachine board name to be consistent.
  code/modules/research/designs/machine_designs.dm
Labels: Tweak

#4448 Fixes issues with skeleton and zombie cloning
  code/game/machinery/cloning.dm
  code/modules/mob/living/damage_procs.dm
Labels: Fix, Tweak

#4107 New Ling Ability (Gaseous Pores)
  beestation.dme
  code/modules/antagonists/changeling/powers/gaseous_pores.dm
  icons/mob/actions/actions_changeling.dmi
Labels: Feature, sprites

#4293 [ready] Pubby Engine Easy Mode
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Fix, Tweak, mapping

#4355 pethats [bugfix]
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  icons/mob/pets_held.dmi
Labels: Fix, sprites

#4462 Fixes slight error with the robotics jumpsuit sprite
  icons/mob/uniform.dmi
Labels: Fix, sprites

#4456 Fixes recharger animation
  code/game/machinery/recharger.dm
Labels: Fix

#4455 Revert "Adds a preference to switch walk hotkey toggle."
  code/datums/keybinding/mob.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_toggles.dm
Labels: Removal

#4464 removes reagent explosions runtime
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
Labels: Fix

#4356 adds a new clown mask, the madman, a madness combat reference
  code/modules/clothing/masks/gasmask.dm
  icons/mob/mask.dmi
  icons/obj/clothing/masks.dmi
Labels: Feature, sprites

#4476 [s]Prevent autolathes from voiding storage item inventories
  code/datums/components/material_container.dm
Labels: Fix, petty af

#4477 Fix "Target Cyborgs" for Turret Control Panel + Fix for syndicate turrets not shooting
  code/game/machinery/porta_turret/portable_turret.dm
Labels: Feature, Fix

#4441 fixes airlock alpha filter breaking on 514
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/airlock_types.dm
  icons/obj/doors/airlocks/mask_32x32.dmi
  icons/obj/doors/airlocks/mask_32x32_airlocks.dmi
  icons/obj/doors/airlocks/mask_64x32.dmi
  icons/obj/doors/airlocks/mask_64x32_airlocks.dmi
Labels: Fix, sprites

#4478 Warning system for special CIDs
  code/controllers/configuration/configuration.dm
  code/modules/admin/sql_ban_system.dm
  config/protected_cids.json
Labels: Administration, Config Update, Feature

#4175 Heretic pop minimum raised to 25
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Config Update, Stale

#4481 Updates the max compile version to 1556
  code/_compile_options.dm
Labels: Code Improvement

#4472 Updates corgstation holodeck
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: Feature, mapping

#4461 Allows admins to edits expired and removed bans
  code/modules/admin/sql_ban_system.dm
Labels: Administration

#4486 Updates to auxtools debugging
  SpacemanDMM.toml
  code/__DEFINES/spaceman_dmm.dm
  code/game/world.dm
Labels: Code Improvement, tools

#4488 fixes breathing
  code/controllers/subsystem/mobs.dm
Labels: Fix

#4426 Improves the mime jumpsuit
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, Vote Passed, sprites

#4282 Riot Armor resprite
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Fix, Vote Passed, sprites

#4489 Fixes virtual Z-levels
  code/__HELPERS/virtual_z_level.dm
  code/game/area/areas.dm
  code/game/area/areas/shuttles.dm
  code/modules/research/xenobiology/crossbreeding/warping.dm
  code/modules/ruins/spaceruin_code/hilbertshotel.dm
Labels: Fix

#4496 fixes infinite holodeck scooters
  code/modules/holodeck/items.dm
Labels: Fix

#4485 Moves Adrenaline nanites back to the Augmentation tab
  code/modules/research/designs/nanite_designs.dm
Labels: Tweak

#4498 tgui: notes
  code/controllers/subsystem/job.dm
  code/datums/mind.dm
  code/modules/antagonists/changeling/powers/absorb.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/mob.dm
  tgui/packages/tgui/interfaces/PaperSheet.js
  tgui/public/tgui.bundle.js
Labels: Feature, TGUI-Changes

#4308 Cat butcher super
  code/modules/mob/living/simple_animal/hostile/cat_butcher.dm
  code/modules/projectiles/projectile/bullets/dart_syringe.dm
  icons/mob/simple_human.dmi
Labels: Balance/Rebalance, Feature, Fix, Tweak, sprites

#4487 Advanced Telemetry Parsing 1: Maybe we should do more than just check bans
  code/__DEFINES/tgui.dm
  code/modules/admin/admin.dm
  code/modules/tgui_panel/telemetry.dm
Labels: Administration

#4414 Ports balloon alerts
  beestation.dme
  code/__DEFINES/balloon_alert.dm
  code/__DEFINES/layers.dm
  code/__DEFINES/misc.dm
  code/__DEFINES/text.dm
  code/__HELPERS/game.dm
  code/controllers/subsystem/runechat.dm
  code/datums/chatmessage.dm
  code/datums/components/storage/concrete/rped.dm
  code/datums/components/storage/storage.dm
  code/game/mecha/combat/durand.dm
  code/game/mecha/equipment/tools/work_tools.dm
  code/game/mecha/mecha_actions.dm
  code/game/objects/items/control_wand.dm
  code/game/objects/items/melee/energy.dm
  code/game/objects/items/melee/transforming.dm
  code/game/objects/items/stunbaton.dm
  code/game/objects/items/tools/powertools.dm
  code/game/objects/items/tools/weldingtool.dm
  code/game/objects/structures/catwalk.dm
  code/game/objects/structures/girders.dm
  code/game/turfs/closed/wall/reinf_walls.dm
  code/game/turfs/closed/walls.dm
  code/game/turfs/turf.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/patch.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/surgery/helpers.dm
Labels: Feature, Needs Testmerge

#4515 Revert "tgui: notes"
  code/controllers/subsystem/job.dm
  code/datums/mind.dm
  code/modules/antagonists/changeling/powers/absorb.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/mob.dm
  tgui/packages/tgui/interfaces/PaperSheet.js
  tgui/public/tgui.bundle.js
Labels: TGUI-Changes

#4511 Fixed showing as unknown if you had an unnamed ID in your second modular pc ID slot
  code/modules/mob/living/carbon/human/human_helpers.dm
Labels: Fix

#4524 Revert just a little bit of "Speeds up SSinput"
  code/modules/keybindings/bindings_atom.dm
  code/modules/mob/mob_movement.dm
Labels: Fix

#4509 Fixes magician's invisibility cloak
  code/game/objects/items/devices/traitordevices.dm
Labels: Fix

#4068 Ports hygiene bot
  beestation.dme
  code/__DEFINES/robots.dm
  code/game/atoms.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/structures/shower.dm
  code/modules/lighting/lighting_object.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/construction.dm
  code/modules/mob/living/simple_animal/bot/hygienebot.dm
  icons/obj/watercloset.dmi
  sound/effects/hygienebot_angry.ogg
  sound/effects/hygienebot_happy.ogg
Labels: Feature, Vote Passed, sound, sprites

#4224 Recharging flashbulb, Cyborg flash nerf, flash nerf.
  _maps/map_files/Mining/Lavaland.dmm
  code/modules/assembly/flash.dm
Labels: mapping

#4525 Feedback alt clicking to maximize atmos devices from /tg/
  code/modules/atmospherics/machinery/components/binary_devices/passive_gate.dm
  code/modules/atmospherics/machinery/components/binary_devices/pump.dm
  code/modules/atmospherics/machinery/components/binary_devices/volume_pump.dm
  code/modules/atmospherics/machinery/components/trinary_devices/filter.dm
  code/modules/atmospherics/machinery/components/trinary_devices/mixer.dm
  code/modules/atmospherics/machinery/components/unary_devices/outlet_injector.dm
  code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
Labels: Feature

#4466 Corgi Related Fixes
  code/game/objects/items/miscellaneous.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Fix, Tweak

#4467 Holodeck Fixes
  _maps/holodeck/animeschool.dmm
  _maps/holodeck/anthophillia.dmm
  _maps/holodeck/basketball.dmm
  _maps/holodeck/beach.dmm
  _maps/holodeck/burntest.dmm
  _maps/holodeck/chapelcourt.dmm
  _maps/holodeck/dodgeball.dmm
  _maps/holodeck/emptycourt.dmm
  _maps/holodeck/firingrange.dmm
  _maps/holodeck/gamer.dmm
  _maps/holodeck/holdoutbunker.dmm
  _maps/holodeck/kobayashi.dmm
  _maps/holodeck/lounge.dmm
  _maps/holodeck/medicalsim.dmm
  _maps/holodeck/offline.dmm
  _maps/holodeck/petpark.dmm
  _maps/holodeck/photobooth.dmm
  _maps/holodeck/refuelingstation.dmm
  _maps/holodeck/skatepark.dmm
  _maps/holodeck/spacecheckers.dmm
  _maps/holodeck/spacechess.dmm
  _maps/holodeck/thunderdome.dmm
  _maps/holodeck/thunderdome1218.dmm
  _maps/holodeck/wildlifesim.dmm
  _maps/holodeck/winterwonderland.dmm
  code/modules/holodeck/holodeck_map_templates.dm
Labels: Fix, Tweak, mapping

#4521 Borg laws
  code/datums/wires/robot.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/computer/robot.dm
  code/game/machinery/transformer.dm
  code/game/objects/items/AI_modules.dm
  code/game/objects/items/robot/robot_parts.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/mob/living/silicon/robot/laws.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_defense.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Administration, Code Improvement, Feature

#4528 Revert "Ports hygiene bot"
  beestation.dme
  code/__DEFINES/robots.dm
  code/game/atoms.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/structures/shower.dm
  code/modules/lighting/lighting_object.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/construction.dm
  code/modules/mob/living/simple_animal/bot/hygienebot.dm
  icons/obj/watercloset.dmi
  sound/effects/hygienebot_angry.ogg
  sound/effects/hygienebot_happy.ogg
Labels: sound, sprites

#4531 Fixes a runtime in SSinput
  code/controllers/subsystem/input.dm
Labels: Fix

#4537 Fixes balloon alerts pref not saving
  code/modules/client/preferences_savefile.dm
Labels: Fix

#4535 Makes mint toxin actually gib fat people
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
Labels: Fix

#4538 Ghoul Moodlet + Max HP fix
  code/datums/status_effects/debuffs.dm
  code/modules/antagonists/eldritch_cult/knowledge/flesh_lore.dm
Labels: Fix, Tweak

#4544 Pubby SM no longer delams roundstart (again)
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Fix, Removal, mapping

#4545 Fixes some bugs with balloon alerts
  code/modules/client/preferences_savefile.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/projectile/bullets/dart_syringe.dm
Labels: Fix

#4436 Departmental Skirts : Service/Civilian
  beestation.dme
  code/_globalvars/lists/flavor_misc.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/under/color.dm
  code/modules/clothing/under/jobs/civilian/civilian.dm
  code/modules/clothing/under/jobs/civilian/clown_mime.dm
  code/modules/clothing/under/jobs/civilian/curator.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/vending/autodrobe.dm
  code/modules/vending/wardrobes.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, sprites

#4542 Makes spray cans recyclable again
  code/game/objects/items/crayons.dm
Labels: Tweak

#4548 Fixes up some of the lawyer skirts
  code/modules/clothing/under/jobs/civilian/civilian.dm
  code/modules/clothing/under/suits.dm
  code/modules/vending/wardrobes.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Fix, sprites

#4534 Fixes runtime on tablet id check
  code/modules/mob/living/carbon/human/human_helpers.dm
Labels: Fix

#4474 New Holodeck Programs
  _maps/templates/holodeck_asylum.dmm
  _maps/templates/holodeck_clownworld.dmm
  _maps/templates/holodeck_kitchen.dmm
  _maps/templates/holodeck_teahouse.dmm
  code/modules/assembly/flash.dm
  code/modules/holodeck/holo_effect.dm
  code/modules/holodeck/holodeck_map_templates.dm
  code/modules/holodeck/turfs.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Feature, mapping

#4458 Fixes/adds? clown, mime, and miner envirohelm welding screens and clown drawn on smile usage
  code/modules/clothing/spacesuits/plasmamen.dm
Labels: Fix

#4550 Hopefully fixes diseases?
  code/datums/diseases/advance/advance.dm
  code/modules/holodeck/holodeck_map_templates.dm
Labels: Fix

#4530 Magboots prevent unsafe pipe wrenching from throwing you
  code/modules/atmospherics/machinery/atmosmachinery.dm
Labels: Feature

#4514 Adds the ability to remove ids data disks and ai cards from laptops from /tg/
  code/modules/modular_computers/computers/item/laptop.dm
Labels: Feature

#4549 makes operating computers shows surgery procedures on stasis tables
  code/game/machinery/computer/Operating.dm
Labels: Fix

#4416 Gang Hotfix
  beestation.dme
  code/game/gamemodes/gangs/gang_items.dm
  code/game/gamemodes/gangs/gang_tags.dm
  code/game/gamemodes/gangs/gangs.dm
  code/game/gamemodes/gangs/implant_gang.dm
  code/game/objects/items/crayons.dm
  code/modules/antagonists/_common/antag_spawner.dm
Labels: Balance/Rebalance, Fix

#4546 Adds more stuff to Corg
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: Feature, Fix, Tweak, mapping

#4560 admins hiding music title and link will actually hide it from the tgui music player too
  code/modules/admin/verbs/playsound.dm
Labels: Administration, Feature

#4561 Makes alarm manager update even while off and fire alarms clear
  code/_globalvars/lists/objects.dm
  code/game/machinery/computer/station_alert.dm
  code/game/machinery/firealarm.dm
  code/modules/modular_computers/file_system/programs/alarm.dm
Labels: Fix

#4556 Makes TRAIT_NODROP shoes unstealable
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#4553 Teratomas can no longer be humanized or have their brain removed
  code/__DEFINES/traits.dm
  code/datums/diseases/advance/symptoms/necropolis.dm
  code/datums/dna.dm
  code/modules/mob/living/carbon/human/species_types/dullahan.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
Labels: Tweak

#4554 Fixes meta's kitchen backroom air alarm going off roundstart
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Fix, mapping

#4504 Adds .38 Rubbers To Autolathes
  code/modules/research/designs/autolathe_designs.dm
Labels: Balance/Rebalance, Feature

#4442 Ports suit storage quickdraw and rest hotkeys from /tg/
  code/datums/keybinding/human.dm
  code/datums/keybinding/living.dm
Labels: Feature

#4505 Splits Adrenaline Nanites In Two Separate Programs
  code/modules/research/designs/nanite_designs.dm
  code/modules/research/nanites/nanite_programs/buffing.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Balance/Rebalance, Feature, Tweak

#4364 ports tgui cloning console from cit, removes maint cloning code copypasta
  _maps/RandomRooms/5x3/sk_rdm080_cloner.dmm
  _maps/RandomRuins/SpaceRuins/cloning_facility.dmm
  _maps/shuttles/emergency_zeta.dmm
  beestation.dme
  code/game/machinery/cloning.dm
  code/game/machinery/computer/cloning.dm
  code/game/machinery/exp_cloner.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/game/objects/items/implants/implant_misc.dm
  tgui/packages/tgui/interfaces/CloningConsole.js
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: Code Improvement, Feature, Refactor, Removal, TGUI-Changes, Tweak, mapping

#4536 Reverts the odd smoothing on unconscious people
  code/__DEFINES/mobs.dm
  code/game/atoms_movable.dm
  code/game/objects/buckling.dm
  code/modules/mob/living/carbon/carbon.dm
Labels: Tweak

#4558 Departmental Skirts : Cargo
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/modules/clothing/under/jobs/cargo.dm
  code/modules/vending/wardrobes.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, sprites

#4562 :trollface:
  icons/emoji.dmi
Labels: Feature, sprites

#4349 port tg's sound reverb system
  beestation.dme
  code/__DEFINES/sound.dm
  code/_globalvars/lists/ambience.dm
  code/controllers/subsystem/ambience.dm
  code/controllers/subsystem/explosion.dm
  code/datums/brain_damage/magic.dm
  code/datums/diseases/heart_failure.dm
  code/datums/status_effects/buffs.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/area/ai_monitored.dm
  code/game/area/areas.dm
  code/game/area/areas/away_content.dm
  code/game/area/areas/centcom.dm
  code/game/area/areas/holodeck.dm
  code/game/area/areas/mining.dm
  code/game/area/areas/ruins/_ruins.dm
  code/game/area/areas/ruins/lavaland.dm
  code/game/area/areas/ruins/space.dm
  code/game/area/areas/shuttles.dm
  code/game/machinery/computer/arcade.dm
  code/game/machinery/dance_machine.dm
  code/game/machinery/quantum_pad.dm
  code/game/objects/structures/musician.dm
  code/game/sound.dm
  code/modules/antagonists/brother/brother.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/creep/creep.dm
  code/modules/antagonists/cult/cult.dm
  code/modules/antagonists/eldritch_cult/eldritch_antag.dm
  code/modules/antagonists/eldritch_cult/eldritch_monster_antag.dm
  code/modules/antagonists/nukeop/nukeop.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/antagonists/traitor/equipment/Malf_Modules.dm
  code/modules/awaymissions/mission_code/TheFactory.dm
  code/modules/awaymissions/mission_code/centcomAway.dm
  code/modules/awaymissions/mission_code/moonoutpost19.dm
  code/modules/chatter/chatter.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences_toggles.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/carbon/status_procs.dm
  code/modules/mob/living/silicon/ai/multicam.dm
  code/modules/mob/mob_defines.dm
  code/modules/modular_computers/file_system/programs/arcade.dm
  code/modules/ruins/spaceruin_code/hilbertshotel.dm
  code/modules/shuttle/shuttle.dm
  code/modules/surgery/organs/heart.dm
  code/modules/turbolift/turbolift_areas.dm
Labels: Feature, Refactor, Removal

#4314 Port tgstation "Makes timer subsystems available as a new subsystem type"
  beestation.dme
  code/__DEFINES/MC.dm
  code/__DEFINES/subsystems.dm
  code/controllers/subsystem/sound_loops.dm
  code/controllers/subsystem/timer.dm
  code/datums/looping_sounds/_looping_sound.dm
Labels: Code Improvement, test merged

#4563 Fixes spyglasses
  code/_onclick/hud/map_popups.dm
  interface/skin.dmf
Labels: Fix

#4186 Adds more anti-toxin to green first aid kit
  code/game/objects/items/storage/firstaid.dm
  code/modules/reagents/reagent_containers/bottle.dm
Labels: Tweak, Vote Passed

#4437 Ports centcom envirosuits from tg
  beestation.dme
  code/modules/antagonists/ert/ert.dm
  code/modules/antagonists/official/official.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/clothing/outfits/plasmaman.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/clothing/under/jobs/Plasmaman/centcom.dm
  code/modules/mob/living/carbon/human/inventory.dm
  icons/mob/head.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, Fix, Tweak, sprites

#4574 Fixes twohanded icons
  code/datums/martial/sleeping_carp.dm
  code/game/objects/items/broom.dm
  code/game/objects/items/dualsaber.dm
  code/game/objects/items/fireaxe.dm
  code/game/objects/items/pitchfork.dm
  code/game/objects/items/singularityhammer.dm
  code/game/objects/items/spear.dm
  code/game/objects/items/weaponry.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/mining/equipment/kinetic_crusher.dm
Labels: Fix

#4576 Fixes toy dualsaber damage
  code/game/objects/items/toys.dm
Labels: Fix

#4577 Removes ERP
  code/modules/food_and_drinks/food/snacks_meat.dm
Labels: Removal

#4581 Runtime fix for Spirit Realm rune
  code/modules/mob/living/living_sentience.dm
Labels: Fix

#4578 Debtor martial art no longer bypasses pacifism
  code/datums/martial/psychotic_brawl.dm
Labels: Fix

#4584 Arming nuke now has cooldown
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
Labels: Feature

#4590 ais shouldn't be able to strip at all
  code/modules/mob/mob.dm
Labels: Balance/Rebalance

#4557 [PORT] Small resist act refactor
  code/game/atoms_movable.dm
  code/game/objects/objs.dm
  code/modules/mob/living/living.dm
Labels: Code Improvement

#4601 Remove duplicate mindshield message in gang code
  code/game/gamemodes/gangs/implant_gang.dm
Labels: Fix

#4600 Make the plating examine() message more accurate
  code/game/turfs/open/floor/plating.dm
Labels: Grammar and Formatting

#4588 Fixes spawners menu killing itself and mob harddels
  code/datums/soullink.dm
  code/modules/mob/living/death.dm
  code/modules/mob/living/living_sentience.dm
  code/modules/mob/living/simple_animal/slime/death.dm
  code/modules/research/xenobiology/crossbreeding/transformative.dm
Labels: Fix

#4589 Fixes small runtime in balloon
  code/datums/chatmessage.dm
  code/game/objects/items/tools/weldingtool.dm
Labels: Grammar and Formatting

#4610 Thank you cenrus, aka adds cooldown to cargo console
  code/__DEFINES/cargo.dm
  code/modules/cargo/console.dm
  code/modules/cargo/expressconsole.dm
Labels: Feature

#4613 Fixes cloning runtime
  code/game/machinery/computer/cloning.dm
Labels: Fix

#4611 Possibly fixes runechat runtime
  code/datums/chatmessage.dm
Labels: Fix

#4622 Fixes global proc calls using Advanced ProcCall and SDQL
  code/modules/admin/callproc/callproc.dm
  code/modules/admin/verbs/SDQL2/SDQL_2.dm
Labels: Administration

#4625 Fix arcade icons
  code/game/machinery/computer/arcade.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  icons/obj/computer.dmi
Labels: Feature, Fix, sprites

#4618 lithium no longer make you walk out of a mech
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Fix

#4370 ports tgui dna consoles
  _maps/RandomZLevels/research.dmm
  code/datums/dna.dm
  code/datums/mutations.dm
  code/game/machinery/cloning.dm
  code/game/machinery/computer/dna_console.dm
  code/game/machinery/dna_scanner.dm
  code/game/objects/items/chromosome.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/hydroponics/grown/replicapod.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/transform_procs.dm
  code/modules/spells/spell_types/lichdom.dm
  html/dna_discovered.gif
  html/dna_discovered.png
  html/dna_extra.gif
  html/dna_extra.png
  html/dna_undiscovered.gif
  html/dna_undiscovered.png
  tgui/packages/tgui/interfaces/DnaConsole.js
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: Administration, Code Improvement, Refactor, TGUI-Changes, Tweak, mapping

#4564 Departmental Skirts : Security
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/vending/wardrobes.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, sprites

#4627 Fixes infinite hallucinations related to delamination.
  code/modules/flufftext/Hallucination.dm
Labels: Fix

#4614 make can_scan checks work again
  code/game/machinery/computer/cloning.dm
Labels: Fix

#4629 fixes bombproof containers not protecting their content in some cases, fixes light explosions have a higher chance of delimbing people
  code/__HELPERS/unsorted.dm
  code/controllers/subsystem/explosion.dm
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Fix, Removal

#4565 Improves the syndicate teleporter
  code/__HELPERS/text.dm
  code/game/objects/items/teleportation.dm
Labels: Balance/Rebalance, Feature

#4619 fixes mechs unable to move in space
  code/game/mecha/mecha.dm
Labels: Fix

#4583 Ports remaining time estimation on tend wounds from /tg/
  code/modules/surgery/healing.dm
Labels: Feature

#4603 Port "Fixes shock paddles being insertable in BoH"
  code/__DEFINES/traits.dm
  code/datums/components/storage/storage.dm
  code/game/objects/items/defib.dm
Labels: Feature, Fix

#4633 Fixed crematorium access checks.
  code/game/machinery/buttons.dm
Labels: Fix

#4637 Fixes toy swords dealing esword damage
  code/game/objects/items/dualsaber.dm
  code/game/objects/items/toys.dm
Labels: Fix

#4594 No more roundstart blob zombie
  _maps/RandomRuins/SpaceRuins/sos4.dmm
Labels: mapping

#4640 fixes cloning message
  code/game/machinery/computer/cloning.dm
Labels: Fix

#4638 Reduces price of the M-90Gl Carbine
  code/modules/uplink/uplink_items.dm
Labels: Balance/Rebalance

#4599 Corg AI Cams are no longer public network
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: Fix, mapping

#4666 Fixes fireman carries and other buckles not working
  code/datums/components/_component.dm
Labels: Fix

#4415 Removes the icon rendering from altclicks
  code/modules/mob/mob_stat.dm
  tgui/packages/tgui-panel/stat/StatText.js
  tgui/public/tgui-panel.bundle.js
Labels: DO NOT MERGE, Removal, TGUI-Changes

#4661 Wabbajack shuttle is now illegal on Sage
  config/Sage/shuttles_illegal.txt
  config/Sage/shuttles_unbuyable.txt
Labels: Balance/Rebalance, Config Update

#4674 Fixes Safety Moth Poster Typo
  code/game/objects/effects/contraband.dm
Labels: Fix, Grammar and Formatting

#4662 Gloves for MDs and Corgs medical modifications
  _maps/map_files/CorgStation/CorgStation.dmm
  code/modules/jobs/job_types/brigphys.dm
  code/modules/jobs/job_types/medical_doctor.dm
Labels: Feature, Tweak, mapping

#4407 Makes station traits config option
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/processing/station.dm
  config/Sage/config.txt
  config/config.txt
Labels: Config Update, Feature

#4679 Bump the client version
  code/modules/client/client_procs.dm
Labels: Tweak

#4657 Departmental skirts: Science
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/clothing/under/jobs/rnd.dm
  code/modules/vending/wardrobes.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Code Improvement, Feature, Fix, Voting, sprites

#4677 Fixes entertainment monitors.
  code/game/machinery/computer/camera.dm
Labels: Fix

#4680 Fixes typo in hos' trenchcoat
  code/modules/clothing/suits/armor.dm
Labels: Fix, Grammar and Formatting

#4673 Heretic Ritual now creates an empty book
  code/modules/antagonists/eldritch_cult/eldritch_book.dm
  code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
Labels: Balance/Rebalance

#4518 Makes the WT and Mosin bulky
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
Labels: Balance/Rebalance
