Repository BeeStation/BeeStation-Hornet, pull requests merged in 2021-07, with the labels that each got.

#4687 fixes empty statpanels before init
  code/modules/tgui_panel/stat.dm
Labels: Fix

#4691 Stop shuttles squashing mobs that shouldn't be squashed
  code/modules/shuttle/on_move.dm
Labels: Fix

#4693 removes a define that was not removed by PR #3969
  code/__DEFINES/say.dm
Labels: Removal

#4678 Ports ability to upload honk virus to airlocks
  beestation.dme
  code/__DEFINES/dcs/signals.dm
  code/datums/chatmessage.dm
  code/datums/components/soundplayer.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/PDA_types.dm
Labels: Code Improvement, Feature

#4694 You can no longer eat thru the miner gas mask
  code/modules/mining/equipment/explorer_gear.dm
Labels: Fix

#4705 Fix lumi eyes toggle not working
  code/modules/surgery/organs/eyes.dm
Labels: Fix

#4710 Minor telemetry cleanup
  code/__DEFINES/tgui.dm
  code/modules/tgui_panel/telemetry.dm
Labels: server

#4709 Fixes explorer mask toggle
  code/modules/mining/equipment/explorer_gear.dm
Labels: Fix

#4712 Ops get an ion carbine instead of an ion rifle
  _maps/map_files/generic/CentCom.dmm
  code/modules/projectiles/guns/energy/special.dm
Labels: Tweak, mapping

#4719 Envirohelm sprite fixes
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Feature, Fix, Removal, sprites

#4690 Solder now makes hallucinations go away
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Tweak

#4724 Nerfs stabilized light pink extract.
  code/__DEFINES/traits.dm
  code/modules/research/xenobiology/crossbreeding/_status_effects.dm
Labels: Balance/Rebalance

#4684 Fixes shell related runtime
  code/modules/hydroponics/grown.dm
Labels: Fix

#4683 Fixes ORM runtime
  code/modules/mining/machine_redemption.dm
Labels: Fix

#4406 Some station traits now have announcements, minor refactor to priority_announce
  code/__HELPERS/priority_announce.dm
  code/controllers/subsystem/shuttle.dm
  code/datums/station_traits/_station_trait.dm
  code/datums/station_traits/negative_traits.dm
  code/datums/weather/weather_types/radiation_storm.dm
  code/game/gamemodes/gangs/dominator.dm
  code/game/machinery/slotmachine.dm
  code/game/objects/effects/anomalies.dm
  code/game/objects/items/crab17.dm
  code/modules/admin/battle_royale.dm
  code/modules/admin/secrets.dm
  code/modules/antagonists/blob/overmind.dm
  code/modules/antagonists/nukeop/equipment/nuclear_challenge.dm
  code/modules/awaymissions/bluespaceartillery.dm
  code/modules/events/_event.dm
  code/modules/events/anomaly.dm
  code/modules/events/anomaly_bluespace.dm
  code/modules/events/anomaly_flux.dm
  code/modules/events/anomaly_grav.dm
  code/modules/events/anomaly_pyro.dm
  code/modules/events/anomaly_vortex.dm
  code/modules/events/asteroid_impact.dm
  code/modules/events/brand_intelligence.dm
  code/modules/events/bureaucratic_error.dm
  code/modules/events/carp_migration.dm
  code/modules/events/communications_blackout.dm
  code/modules/events/dolphin_migration.dm
  code/modules/events/electrical_storm.dm
  code/modules/events/fugitive_spawning.dm
  code/modules/events/high_priority_bounty.dm
  code/modules/events/holiday/halloween.dm
  code/modules/events/holiday/vday.dm
  code/modules/events/holiday/xmas.dm
  code/modules/events/immovable_rod.dm
  code/modules/events/major_dust.dm
  code/modules/events/pirates.dm
  code/modules/events/portal_storm.dm
  code/modules/events/prison_break.dm
  code/modules/events/processor_overload.dm
  code/modules/events/sentience.dm
  code/modules/events/shuttle_loan.dm
  code/modules/events/space_dragon.dm
  code/modules/events/vent_clog.dm
  code/modules/events/wizard/magicarp.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/holiday/easter.dm
  code/modules/mob/living/carbon/alien/humanoid/queen.dm
  code/modules/power/singularity/narsie.dm
  code/modules/shuttle/emergency.dm
Labels: Administration, Feature, Fix, Refactor

#4726 Removes /client/MouseMove()
  code/_onclick/drag_drop.dm
  code/datums/components/lockon_aiming.dm
  code/game/objects/structures/manned_turret.dm
  code/modules/mob/mob_defines.dm
  code/modules/projectiles/guns/misc/beam_rifle.dm
Labels: Code Improvement

#4727 Mask adjusting fixes
  code/modules/clothing/masks/_masks.dm
  code/modules/mining/equipment/explorer_gear.dm
Labels: Fix

#4732 Fix beer nuke paper
  code/modules/paperwork/paper.dm
Labels: Code Improvement, Fix

#4739 Ports contractor tablet cryo fix from tg
  code/game/machinery/cryopod.dm
  code/modules/modular_computers/file_system/programs/antagonist/contract_uplink.dm
Labels: Fix

#4698 Allows the nanite program hub and programmer to be deconstructed
  code/modules/research/nanites/nanite_program_hub.dm
  code/modules/research/nanites/nanite_programmer.dm
Labels: Fix

#4741 Heretic blade shatter now uses magic channel
  code/modules/antagonists/eldritch_cult/eldritch_items.dm
Labels: Fix

#4711 Departmental skirts: Medical
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/clothing/under/jobs/medical.dm
  code/modules/vending/wardrobes.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, Tweak, Vote Passed, sprites

#4682 Removes xray from genetics
  code/datums/mutations/_combined.dm
Labels: Removal

#4707 Ports directional armor mech fix from Paradise [PORT]
  code/game/mecha/mecha_defense.dm
Labels: Fix

#4612 Clockwork fixes, gamemode map load refactor, eminence refactoring
  _maps/RandomRuins/LavaRuins/lavaland_surface_dead_ratvar.dmm
  beestation.dme
  code/controllers/subsystem/ticker.dm
  code/game/gamemodes/clock_cult/clockcult.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/game_mode.dm
  code/game/machinery/buttons.dm
  code/game/machinery/firealarm.dm
  code/game/machinery/flasher.dm
  code/game/machinery/lightswitch.dm
  code/game/objects/items/pneumaticCannon.dm
  code/modules/antagonists/clock_cult/clockwork_outfits.dm
  code/modules/antagonists/clock_cult/clockwork_turfs.dm
  code/modules/antagonists/clock_cult/helpers/reebe_loader.dm
  code/modules/antagonists/clock_cult/items/clockwork_weapon.dm
  code/modules/antagonists/clock_cult/items/integration_cog.dm
  code/modules/antagonists/clock_cult/mobs/eminence.dm
  code/modules/antagonists/clock_cult/structure/clockwork_camera.dm
  code/modules/mapping/map_template.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/power/apc.dm
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Balance/Rebalance, Config Update, Fix, Refactor, mapping

#4699 Fixes diagonal movement delay
  code/modules/mob/mob_movement.dm
Labels: Tweak

#4748 Fixes multitool
  code/game/objects/items/devices/multitool.dm
Labels: Balance/Rebalance, Code Improvement, Feature, Fix, Grammar and Formatting, Refactor, Removal, Tweak, server

#4728 Sync golden and sage map config
  config/Sage/maps.txt
  config/maps.txt
Labels: Config Update

#4620 makes the firefighter radproof
  code/game/mecha/working/ripley.dm
Labels: Balance/Rebalance

#4753 Ports Important TGUI Fix
  tgui/packages/common/storage.js
  tgui/public/tgui-common.bundle.js
Labels: TGUI-Changes

#4716 Fix my TGUI mistakes & tweak uplink atomized edition
  tgui/packages/tgui-panel/Panel.js
  tgui/packages/tgui/interfaces/AirAlarm.js
  tgui/packages/tgui/interfaces/SyndContractor.js
  tgui/packages/tgui/interfaces/Uplink.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: Fix, TGUI-Changes, Tweak

#4681 Adds service and cargo techfabs instead of protolathes on Corg
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: Tweak, mapping

#4688 Fixes mistake with pipe painter instead of a hand labeler on corg
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: Fix, mapping

#4642 updates pubbystation's holodeck
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Fix, mapping

#4760 Ports Cache asset/mappings results
  code/modules/asset_cache/asset_list.dm
  code/modules/tgui/tgui_window.dm
Labels: Code Improvement

#4761 Fixes exponents in 2 files
  code/modules/events/ghost_role.dm
  code/modules/power/lighting.dm
Labels: Code Improvement, Fix

#4733 You can't radio whisper in crit + radio messages don't double for ghosts
  code/datums/chatmessage.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/say.dm
  code/modules/mob/say.dm
Labels: Balance/Rebalance, Fix

#4763 Fix a runtime
  code/modules/tgui_panel/telemetry.dm
Labels: Fix

#4670 [PORT] Datumized AI + implemented for monkeys from TG
  beestation.dme
  code/__DEFINES/DNA.dm
  code/__DEFINES/ai.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/inventory.dm
  code/__DEFINES/monkeys.dm
  code/__DEFINES/subsystems.dm
  code/__DEFINES/vv.dm
  code/_globalvars/lists/mobs.dm
  code/controllers/subsystem/processing/ai_controllers.dm
  code/datums/ai/README.md
  code/datums/ai/_ai_behaviour.dm
  code/datums/ai/_ai_controller.dm
  code/datums/ai/generic_actions.dm
  code/datums/ai/monkey/monkey_behaviours.dm
  code/datums/ai/monkey/monkey_controller.dm
  code/datums/mutations/body.dm
  code/game/atoms.dm
  code/game/objects/items.dm
  code/game/objects/items/handcuffs.dm
  code/modules/antagonists/changeling/powers/tiny_prick.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/emote.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/monkey/punpun.dm
  code/modules/mob/living/living.dm
  code/modules/mob/logout.dm
  code/modules/mob/transform_procs.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/recycling/disposal/bin.dm
  sound/creatures/monkey/monkey_screech_1.ogg
  sound/creatures/monkey/monkey_screech_2.ogg
  sound/creatures/monkey/monkey_screech_3.ogg
  sound/creatures/monkey/monkey_screech_4.ogg
  sound/creatures/monkey/monkey_screech_5.ogg
  sound/creatures/monkey/monkey_screech_6.ogg
  sound/creatures/monkey/monkey_screech_7.ogg
Labels: Feature, sound

#4755 Ports #44391 and #48637 from TGStation
  code/__DEFINES/dcs/signals.dm
  code/datums/brain_damage/brain_trauma.dm
  code/datums/brain_damage/hypnosis.dm
  code/datums/brain_damage/phobia.dm
  code/datums/brain_damage/split_personality.dm
  code/datums/status_effects/debuffs.dm
  code/datums/status_effects/neutral.dm
  code/game/say.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/mob/living/carbon/say.dm
  code/modules/mob/living/say.dm
Labels: Code Improvement, Fix, Refactor

#4768 Fixes admin template uploads
  code/modules/admin/verbs/map_template_loadverb.dm
  code/modules/mapping/reader.dm
Labels: Administration, Fix

#4749 Reponse Team Tweaks
  code/modules/clothing/outfits/ert.dm
  code/modules/clothing/outfits/plasmaman.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/clothing/under/jobs/Plasmaman/centcom.dm
Labels: Feature, Tweak

#4434 ports tg's filter debug menu & minor filter refactor
  beestation.dme
  code/__DEFINES/colors.dm
  code/__DEFINES/vv.dm
  code/__HELPERS/filters.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/hud/plane_master.dm
  code/game/atoms.dm
  code/modules/admin/holder2.dm
  code/modules/admin/view_variables/filterrific.dm
  code/modules/antagonists/nukeop/equipment/borgchameleon.dm
  code/modules/cargo/supplypod.dm
  code/modules/client/client_procs.dm
  tgui/docs/component-reference.md
  tgui/packages/common/math.js
  tgui/packages/tgui/components/Dropdown.js
  tgui/packages/tgui/interfaces/Filteriffic.js
  tgui/public/tgui-common.bundle.js
  tgui/public/tgui.bundle.js
Labels: Administration, Feature, TGUI-Changes

#4774 Adds a delay to the application of the gender change potion
  code/modules/research/xenobiology/xenobiology.dm
Labels: Removal, Tweak

#4777 Configures the TGUI recompile bot
  .github/comment-agent.yml
Labels: GitHub

#4778 Adds the tgui recompile workflow
  .github/workflows/tgui_recompile.yml
Labels: GitHub

#4752 Cryostasis Shotgun Shells Now at Seclathe
  code/modules/research/designs/weapon_designs.dm
Labels: Balance/Rebalance

#4766 Allow clockers to summon their basic outfit loadout
  code/modules/antagonists/clock_cult/scriptures/clockwork_armaments.dm
Labels: Feature

#4639 Ports Fission360 and Lifeline program from /tg/
  beestation.dme
  code/game/gamemodes/nuclear/nuclear.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/modular_computers/computers/item/computer.dm
  code/modules/modular_computers/computers/item/computer_ui.dm
  code/modules/modular_computers/computers/item/tablet.dm
  code/modules/modular_computers/computers/item/tablet_presets.dm
  code/modules/modular_computers/computers/machinery/modular_computer.dm
  code/modules/modular_computers/file_system/program.dm
  code/modules/modular_computers/file_system/programs/ntdownloader.dm
  code/modules/modular_computers/file_system/programs/radar.dm
  code/modules/modular_computers/hardware/hard_drive.dm
  icons/UI_Icons/tgui/ntosradar_background.png
  icons/UI_Icons/tgui/ntosradar_pointer.png
  icons/UI_Icons/tgui/ntosradar_pointer_S.png
  icons/obj/modular_laptop.dmi
  icons/obj/modular_tablet.dmi
  tgui/packages/tgui/interfaces/NtosRadar.js
  tgui/packages/tgui/interfaces/NtosRadarSyndicate.js
  tgui/public/tgui.bundle.js
Labels: Feature, TGUI-Changes, sprites

#4781 Update tgui_recompile.yml to be beebot
  .github/workflows/tgui_recompile.yml
Labels: GitHub

#4567 Filters + plane_master atomized
  beestation.dme
  code/__DEFINES/colors.dm
  code/__DEFINES/layers.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/plane_master.dm
  code/_onclick/hud/plane_master_controller.dm
  code/game/objects/items.dm
  code/modules/admin/view_variables/filterrific.dm
  code/modules/antagonists/clock_cult/items/brass_clothing.dm
  code/modules/mob/status_procs.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  tgui/public/tgui-common.chunk.js
Labels: Administration, Feature, TGUI-Changes

#4773 Prevents the sonic jackhammer from breaking reinforced walls, plastitanium walls, CC walls and cult walls.
  code/game/turfs/closed/wall/mineral_walls.dm
  code/game/turfs/closed/wall/misc_walls.dm
  code/game/turfs/closed/wall/reinf_walls.dm
  code/modules/antagonists/clock_cult/clockwork_turfs.dm
Labels: Balance/Rebalance

#4792 Fixes loading admin shuttle templates
  code/datums/shuttles.dm
  code/modules/admin/verbs/map_template_loadverb.dm
  code/modules/mapping/map_template.dm
Labels: Administration, Fix

#4675 [PORT] Area map generation datum + jungle generator
  beestation.dme
  code/__DEFINES/maps.dm
  code/controllers/subsystem/mapping.dm
  code/datums/mapgen/JungleGenerator.dm
  code/datums/mapgen/_MapGenerator.dm
  code/datums/mapgen/biomes/_biome.dm
  code/game/area/areas.dm
  code/game/turfs/open/floor/plating/dirt.dm
  code/game/turfs/open/floor/plating/planet.dm
  code/game/turfs/open/water.dm
  icons/turf/debug.dmi
  icons/turf/floors.dmi
Labels: Feature, sprites

#4785 Fix the Github Actions Caching
  .github/workflows/continuous_integration.yml
Labels: GitHub

#4799 holodeck harddel fix
  code/modules/holodeck/computer.dm
Labels: Fix, Removal

#4802 Fixes the worst typo to ever exist
  code/modules/admin/verbs/adminhelp.dm
Labels: Administration, Grammar and Formatting

#4798 Makes the black pill contain enough mutation toxin to transform
  code/modules/reagents/reagent_containers/pill.dm
Labels: Fix

#4808 Monkey AI fixes
  code/datums/ai/monkey/monkey_controller.dm
  code/modules/mob/living/living_defense.dm
Labels: Fix

#4786 Clock cult brass sword emp changes and plasmaman clockwork armaments
  code/modules/antagonists/clock_cult/clockwork_outfits.dm
  code/modules/antagonists/clock_cult/items/clockwork_weapon.dm
  code/modules/antagonists/clock_cult/scriptures/clockwork_armaments.dm
  code/modules/clothing/chameleon.dm
Labels: Feature, Fix

#4743 Fixes cargo skirt with digitigrade legs + captain jumpskirt
  code/modules/clothing/under/jobs/cargo.dm
  code/modules/clothing/under/jobs/command.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, Fix, sprites

#4689 Fixes Tinea Luxor
  code/modules/reagents/chemistry/reagents/food_reagents.dm
Labels: Fix

#4692 fix static in ai multicameramode
  code/modules/mob/living/silicon/ai/freelook/cameranet.dm
Labels: Fix

#4635 Tweaks cargo values and contents
  code/modules/cargo/packs.dm
Labels: Fix

#4650 some holodeck fixes and changes
  _maps/holodeck/beach.dmm
  _maps/holodeck/photobooth.dmm
Labels: Tweak, mapping

#4604 Arm augments refactor
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/mob.dm
  code/modules/surgery/organs/augments_arms.dm
Labels: Balance/Rebalance, Feature

#4758 Adds logging to the antimatter and groups all the engines into one log
  code/__DEFINES/logging.dm
  code/modules/admin/admin_investigate.dm
  code/modules/admin/topic.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/power/antimatter/control.dm
  code/modules/power/singularity/boh_tear.dm
  code/modules/power/singularity/collector.dm
  code/modules/power/singularity/emitter.dm
  code/modules/power/singularity/field_generator.dm
  code/modules/power/singularity/investigate.dm
  code/modules/power/singularity/particle_accelerator/particle_accelerator.dm
  code/modules/power/singularity/particle_accelerator/particle_control.dm
  code/modules/power/singularity/singularity.dm
  code/modules/power/smes.dm
  code/modules/power/supermatter/supermatter.dm
Labels: Administration, Feature

#4769 Removes positive stage speed threshold from DNA saboteur
  code/datums/diseases/advance/symptoms/genetics.dm
Labels: Balance/Rebalance

#4791 Fixes stupid meme shuttle
  _maps/shuttles/emergency_arena.dmm
  _maps/templates/the_arena.dmm
  code/datums/shuttles.dm
  code/game/machinery/computer/communications.dm
Labels: Feature, Fix, mapping

#4811 Gives the circuit multitool its own sprite
  code/modules/wiremod/marker.dm
  icons/mob/inhands/equipment/tools_lefthand.dmi
  icons/mob/inhands/equipment/tools_righthand.dmi
  icons/obj/device.dmi
Labels: Feature, sprites

#4815 Fixes game hanging itself if it cannot start gamemode
  code/controllers/subsystem/ticker.dm
Labels: Fix, THIS IS VERY IMPORTANT

#4819 Changes the trauma lines that reference tgstation servers
  strings/traumas.json
Labels: Tweak, server

#4794 Makes being tableported give the table mood buff/debuff.
  code/modules/clothing/suits/reactive_armour.dm
Labels: Feature

#4829 Ratvar clockifies more stuff
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/structures/beds_chairs/chair.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/window.dm
  code/modules/antagonists/clock_cult/clockwork_turfs.dm
Labels: Feature

#4827 Fixes xenomorph neurotoxin spit not logging the shooter
  code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
Labels: Fix

#4833 Drag'n'drop in tgui statpanel after alt-click
  code/modules/mob/mob_stat.dm
  tgui/packages/tgui-panel/stat/StatText.js
  tgui/public/tgui-panel.bundle.js
Labels: Feature, TGUI-Changes

#4816 Cult pylons heal at the same rate again
  code/modules/antagonists/cult/cult_structures.dm
Labels: Fix

#4824 Make smoke machine rotatable
  code/modules/reagents/chemistry/machinery/smoke_machine.dm
Labels: Feature

#4809 Consistent Cargo Pack Descriptions
  code/modules/cargo/packs.dm
Labels: Fix

#4842 Fixes witch hunter hat having no armor
  code/game/objects/items/holy_weapons.dm
Labels: Fix

#4822 Makes the ghost arrows on the spectre inspector goggles a toggle
  code/modules/clothing/glasses/_glasses.dm
Labels: Feature

#4789 Automatable Cooking
  code/modules/food_and_drinks/food/snacks.dm
  code/modules/reagents/chemistry/holder.dm
Labels: Feature, Fix

#4736 More circuit entity outputs
  beestation.dme
  code/__DEFINES/dcs/signals.dm
  code/game/machinery/doors/airlock.dm
  code/modules/research/designs/wiremod_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/wiremod/shell/airlock.dm
  code/modules/wiremod/shell/moneybot.dm
  code/modules/wiremod/shell/scanner.dm
Labels: Feature, Tweak

#4858 Fixes luminescent eyes making a magical eye lighting visible effect
  code/modules/surgery/organs/eyes.dm
Labels: Fix

#4848 Ports fix iron duplication bug with reinforced floors and disposals
  code/modules/recycling/disposal/pipe.dm
Labels: Fix

#4846 Nerfs scatter laser shotgun damage
  code/modules/projectiles/projectile/beams.dm
Labels: Balance/Rebalance

#4654 Ability to construct showers and sinks
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/shower.dm
  code/game/objects/structures/watercloset.dm
  icons/obj/watercloset.dmi
Labels: Feature, sprites

#4647 Fixes blocking thrown items
  code/game/atoms_movable.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defense.dm
Labels: Fix

#4828 Define get_area (tg#44073)
  code/__DEFINES/misc.dm
  code/__HELPERS/game.dm
  code/game/machinery/requests_console.dm
  code/game/objects/items/blueprints.dm
  code/game/objects/items/crab17.dm
  code/modules/antagonists/clock_cult/scriptures/dimensional_breach.dm
  code/modules/antagonists/clock_cult/structure/clockwork_camera.dm
  code/modules/antagonists/roundstart_special/undercover/undercover.dm
  code/modules/mapexporting/mapexporter.dm
Labels: Code Improvement

#4845 Admins can choose to instantly trigger meteors when they select it.
  code/modules/admin/topic.dm
  code/modules/events/_event.dm
  code/modules/events/meteor_wave.dm
Labels: Administration, Tweak

#4663 Buckling from adjacent tiles from /tg/
  code/game/objects/buckling.dm
  code/game/objects/structures/beds_chairs/chair.dm
Labels: Feature

#4804 Fixes bug with orion trail dropping a radio when the monitor gets disconnected
  code/game/machinery/computer/arcade.dm
Labels: Fix

#4853 Explorer jumpsuit now covers jumpsuit
  code/modules/mining/equipment/explorer_gear.dm
Labels: Tweak

#4817 [PORT] Makes pressure proofing check for clothing coverage
  code/modules/mob/living/carbon/human/life.dm
Labels: Tweak

#4872 FIX GET HEARERS IN VIEW
  code/__HELPERS/_lists.dm
  code/game/atoms_movable.dm
Labels: Fix

#4874 fixes the photobooth holodeck breaking the holodeck
  _maps/holodeck/photobooth.dmm
  code/modules/holodeck/turfs.dm
Labels: Fix, mapping

#4810 Apids with Space Adaptation no longer sleep in the cold
  code/modules/mob/living/carbon/human/species_types/apid.dm
Labels: Fix

#4868 Makes baseball bats unable to stunlock
  code/game/objects/items/weaponry.dm
Labels: Balance/Rebalance, Tweak

#4879 fixes sink and shower frame description
  code/game/objects/structures/shower.dm
  code/game/objects/structures/watercloset.dm
Labels: Grammar and Formatting

#4886 fixes the beach holodeck
  _maps/holodeck/beach.dmm
Labels: Fix, mapping

#4884 fixes grammar error in a moth name
  strings/names/moth_last.txt
Labels: Grammar and Formatting

#4881 Reload mentors on edit
  code/modules/admin/verbs/mentors_edit.dm
Labels: Administration

#4875 makes soporific ammo not apply it's effect to non-human targets
  code/modules/projectiles/projectile/bullets/shotgun.dm
Labels: Fix

#4888 Resprites the lawyer suits and skirts
  code/modules/vending/wardrobes.dm
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, sprites

#4762 [MDB IGNORE] Remove Fastmos Changes From All Maps
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Removal, mapping

#4899 Adds sanity checking to bloodcult pre_setup()
  code/game/gamemodes/cult/cult.dm
Labels: Fix

#4901 Removes a sleepless while loop
  code/game/objects/effects/decals/cleanable/food.dm
Labels: Fix, Tweak

#4900 Fixes n2o being replaced with nitryl in multiple cases
  code/game/objects/items/tanks/tank_types.dm
  code/modules/atmospherics/gasmixtures/reactions.dm
  code/modules/atmospherics/machinery/airalarm.dm
  code/modules/atmospherics/machinery/other/miner.dm
  code/modules/atmospherics/machinery/portable/scrubber.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/simple_animal/bot/atmosbot.dm
  code/modules/power/supermatter/supermatter.dm
Labels: Fix

#4897 Fixes absorb requirements
  code/modules/antagonists/changeling/changeling_power.dm
Labels: Fix

#4568 Vend-a-tray and displaycase changes atomized
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/obj_defense.dm
  code/game/objects/structures/displaycase.dm
  icons/obj/stationobjs.dmi
  sound/effects/cashregister.ogg
  tgui/packages/tgui/interfaces/Vendatray.js
  tgui/public/tgui.bundle.js
Labels: Feature, Fix, TGUI-Changes, mapping, sound, sprites

#4796 Fixes the blind spell.
  beestation.dme
  code/__DEFINES/traits.dm
  code/game/objects/items/granters.dm
  code/modules/spells/spell_types/barnyard.dm
  code/modules/spells/spell_types/blind.dm
  code/modules/spells/spell_types/construct_spells.dm
  code/modules/spells/spell_types/inflict_handler.dm
Labels: Code Improvement, Fix, Refactor, Removal

#4913 [MDB Ignore] Removes the rest of the remaining fastmos airlocks, fixes a delta map mistake.
  _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/shuttles/arrival_corg.dmm
  _maps/shuttles/emergency_asteroid.dmm
  _maps/shuttles/emergency_bar.dmm
  _maps/shuttles/emergency_birdboat.dmm
  _maps/shuttles/emergency_box.dmm
  _maps/shuttles/emergency_cere.dmm
  _maps/shuttles/emergency_clown.dmm
  _maps/shuttles/emergency_construction.dmm
  _maps/shuttles/emergency_corg.dmm
  _maps/shuttles/emergency_cramped.dmm
  _maps/shuttles/emergency_delta.dmm
  _maps/shuttles/emergency_discoinferno.dmm
  _maps/shuttles/emergency_donut.dmm
  _maps/shuttles/emergency_goon.dmm
  _maps/shuttles/emergency_kilo.dmm
  _maps/shuttles/emergency_meta.dmm
  _maps/shuttles/emergency_mini.dmm
  _maps/shuttles/emergency_omega.dmm
  _maps/shuttles/emergency_pubby.dmm
  _maps/shuttles/emergency_raven.dmm
  _maps/shuttles/emergency_russiafightpit.dmm
  _maps/shuttles/emergency_scrapheap.dmm
  _maps/shuttles/emergency_wabbajack.dmm
  _maps/shuttles/whiteship_meta.dmm
Labels: Tweak, mapping

#4927 Bump auxmos to 0.2.3, fixes fusion
  auxtools/auxmos.dll
  dependencies.sh
Labels: Fix

#4929 some delta time fixes
  code/modules/antagonists/clock_cult/scriptures/interdiction_lens.dm
  code/modules/antagonists/clock_cult/scriptures/prosperity_prism.dm
Labels: Fix

#4876 Fixes the TGUI Rebuild Action Again
  .github/comment-agent.yml
  .github/workflows/tgui_recompile.yml
Labels: GitHub

#4856 Ports profiling improvements from TG
  beestation.dme
  code/__DEFINES/_profile.dm
  code/__DEFINES/subsystems.dm
  code/__HELPERS/_logging.dm
  code/_compile_options.dm
  code/_globalvars/logging.dm
  code/controllers/subsystem/profiler.dm
  code/controllers/subsystem/time_track.dm
  code/game/world.dm
  code/modules/admin/admin_verbs.dm
Labels: Administration, Code Improvement

#4261 Chat badges
  beestation.dme
  code/controllers/configuration/entries/game_options.dm
  code/game/world.dm
  code/modules/admin/admin_ranks.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/debug.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/badges/badges.dm
  code/modules/client/client_procs.dm
  code/modules/client/verbs/ooc.dm
  code/modules/mentor/mentor_verbs.dm
  config/Sage/badges.json
  config/Sage/game_options.txt
  config/badges.json
  config/game_options.txt
  icons/badges.dmi
Labels: Administration, Config Update, Feature, sprites

#4570 Converts Slime processor process to a Proximity Monitor
  code/modules/food_and_drinks/kitchen_machinery/processor.dm
Labels: Code Improvement, Fix

#4880 Increase Borg Light Replacer Restock Rate
  code/game/objects/items/devices/lightreplacer.dm
Labels: Tweak

#4721 Illegal tech rework
  code/__DEFINES/obj_flags.dm
  code/_globalvars/bitfields.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/research/techweb/__techweb_helpers.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/uplink/uplink_items.dm
Labels: Refactor

#4917 Adds new pai holoforms, Crow and Mushroom from bay
  code/modules/mob/living/silicon/pai/pai.dm
  icons/mob/pai.dmi
  icons/mob/pai_item_lh.dmi
  icons/mob/pai_item_rh.dmi
Labels: Feature, sprites

#4918 fix IPC muting using antivirus
  code/game/objects/items/devices/antivirus.dm
Labels: Fix

#4500 Embedding rework
  code/__DEFINES/combat.dm
  code/__DEFINES/dcs/signals.dm
  code/datums/components/embedded.dm
  code/datums/elements/embed.dm
  code/game/objects/items.dm
  code/game/objects/items/kitchen.dm
  code/game/objects/items/melee/energy.dm
  code/game/objects/items/mop.dm
  code/game/objects/items/spear.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weaponry.dm
  code/modules/antagonists/clock_cult/items/clockwork_weapon.dm
  code/modules/mob/living/carbon/examine.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/ninja/suit/n_suit_verbs/ninja_stars.dm
  code/modules/paperwork/pen.dm
  code/modules/vending/_vending.dm
  strings/tips.txt
Labels: Refactor

#4926 Doors no longer chain paralyze.
  code/game/machinery/doors/door.dm
Labels: Balance/Rebalance

#4653 Moves borg apparatus drop from alt z to alt click so it works
  code/game/objects/items/robot/robot_items.dm
Labels: Fix

#4630 Plasmaman Captain and Security/Brigphys Quality of Life
  code/modules/clothing/outfits/plasmaman.dm
  code/modules/clothing/under/jobs/Plasmaman/civilian_service.dm
  code/modules/clothing/under/jobs/Plasmaman/security.dm
Labels: Feature, Fix

#4867 Adds ability to buckle to stasis units and beds adjacently
  code/game/objects/buckling.dm
  code/game/objects/noose.dm
  code/game/objects/structures/beds_chairs/alien_nest.dm
  code/game/objects/structures/beds_chairs/chair.dm
  code/game/objects/structures/guillotine.dm
  code/game/objects/structures/kitchen_spike.dm
  code/game/objects/structures/manned_turret.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/ninja/suit/n_suit_verbs/energy_net_nets.dm
  code/modules/power/singularity/emitter.dm
Labels: Feature

#4502 Standardizes Access Cards
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/modules/jobs/job_types/deputy.dm
  code/modules/mining/machine_vending.dm
Labels: Feature, Tweak

#4931 Fixes the wiki button
  interface/interface.dm
Labels: Fix

#4757 Adds cyborg recharger to delta dorms bathroom
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Feature, mapping

#4821 Adds a 1.5 second delay to adding equipment and trackers to mechs.
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/mecha_control_console.dm
Labels: Feature

#4807 Fixes envirohelm inventory sprite using the wrong image
  icons/obj/clothing/hats.dmi
Labels: Removal, sprites

#4885 fixes get hearing yet again
  code/game/atoms_movable.dm
Labels: Fix

#4944 Fixes lack of head sprite for scooped Crow Pai holoform, Ads Corgi Puppy Pai Holoform
  code/modules/mob/living/silicon/pai/pai.dm
  icons/mob/pai.dmi
  icons/mob/pai_item_head.dmi
Labels: Feature, Fix, sprites

#4837 adds bronze windows and airlocks (#46921)
  code/game/machinery/doors/airlock_types.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/door_assembly_types.dm
  code/game/objects/structures/window.dm
Labels: Feature

#4946 Updates corgstation shuttle
  _maps/shuttles/emergency_corg.dmm
Labels: Feature, Fix, Tweak, mapping

#4911 Firelocks stay open with atmos holosigns from /tg/
  code/__DEFINES/traits.dm
  code/game/machinery/doors/firedoor.dm
  code/game/objects/structures/holosign.dm
Labels: Feature

#4948 Fix the TGUI Action Again
  .github/workflows/tgui_recompile.yml
Labels: GitHub

#4823 [PORT] Tgui stack menu
  code/game/objects/items/stacks/stack.dm
  tgui/packages/tgui/interfaces/Stack.js
  tgui/public/tgui.bundle.js
Labels: Feature, TGUI-Changes

#4949 Fixes metastation engineering being named "Gas to Filter"
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Fix, mapping

#4904 Fixes Delta Bar Disposals
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Fix, mapping

#4706 Adds BEEF BROTH and BEEF FIZZ
  code/game/objects/items/trash.dm
  code/modules/cargo/packs.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  icons/obj/drinks.dmi
  icons/obj/food/food.dmi
Labels: Code Improvement, Feature, sprites

#4439 Ports "Surgery now goes slower before failing" from /tg/ and operating table buff
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/surgery/organ_manipulation.dm
  code/modules/surgery/surgery.dm
  code/modules/surgery/surgery_step.dm
Labels: Balance/Rebalance, Feature, Fix, Tweak, Vote Passed

#4938 Adds medical berets to MediDrobes
  code/modules/vending/wardrobes.dm
Labels: Feature

#4844 Fixes shields not working in offhand
  code/game/objects/items/shields.dm
Labels: Fix

#4955 Fixes boxstation detective disposals
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Fix, mapping

#4966 Fixes X4
  code/game/objects/items/grenades/plastic.dm
Labels: Fix

#4954 Dadbot lawset from austation
  code/datums/ai_laws.dm
  code/game/objects/items/AI_modules.dm
  code/modules/research/designs/AI_module_designs.dm
Labels: Feature

#4964 Fixes blind spell in spellbook
  code/modules/antagonists/wizard/equipment/spellbook.dm
Labels: Fix

#4978 fix aliens getting trapped in vents
  code/modules/mob/living/carbon/alien/larva/powers.dm
Labels: Fix
