Repository BeeStation/BeeStation-Hornet, pull requests merged in 2021-10, with the labels that each got.

#5473 Fixes typo in supercruise.
  code/modules/shuttle/super_cruise/orbital_poi_generator/objective_types/alien_artifact.dm
Labels: Grammar and Formatting

#5472 Debug uplinks now actually use the debug toggle.
  code/modules/uplink/uplink_devices.dm
Labels: Fix, hacktoberfest-accepted

#5456 Space hotel fixes
  _maps/RandomRuins/SpaceRuins/spacehotel.dmm
  code/game/area/areas/ruins/space.dm
Labels: mapping, Feature, Fix

#5408 You can no longer drag blobbernauts.
  code/modules/antagonists/blob/blob_mobs.dm
Labels: Tweak

#5446 DeltaStation Holodeck Update
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: mapping, Fix

#5466 Updates Alkali Perspiration's Severity to match its thresholds.
  code/datums/diseases/advance/symptoms/fire.dm
Labels: Fix

#5475 Resolves a bad index exception thrown by tgui-stat
  code/modules/mob/mob_stat.dm
Labels: Fix, hacktoberfest-accepted

#5164 Mobs no longer create blood trails while being thrown
  code/__DEFINES/flags.dm
  code/controllers/subsystem/throwing.dm
  code/game/atoms_movable.dm
  code/modules/mob/living/living.dm
Labels: Voting, Feature

#5474 Spellcheck & store history in memory for VIP extraction POI
  code/modules/shuttle/super_cruise/orbital_poi_generator/objective_types/vip_extraction.dm
Labels: Grammar and Formatting, hacktoberfest-accepted

#5480 Report round id as int in ?status
  code/datums/world_topic.dm
Labels: server, hacktoberfest-accepted

#5479 Fixes runtime related to missing clients in mentorhelps
  code/modules/mentor/mentorpm.dm
Labels: Fix, hacktoberfest-accepted

#5477 Station trait command report is now generated independly
  code/controllers/subsystem/processing/station.dm
  code/datums/station_traits/positive_traits.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/extended/extended.dm
  code/game/gamemodes/game_mode.dm
Labels: Tweak

#5478 Fixes lavaland turret setup runtime
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
Labels: mapping, Fix, hacktoberfest-accepted

#5501 Show "important" messages in created chat tabs
  tgui/packages/tgui-panel/chat/model.js
Labels: Fix, Removal, TGUI-Changes

#5493 I fixed shuttles being overweight!
  code/modules/shuttle/custom_shuttle.dm
Labels: Fix

#5457 Unique Uniforms for Exploration Crew Plasmamen
  code/modules/clothing/outfits/plasmaman.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/clothing/under/jobs/Plasmaman/medsci.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  icons/mob/head.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, sprites

#5504 Properly reset view_size when entering a mob
  code/modules/mob/login.dm
Labels: Fix

#5363 Sprite_Sheets, a new system to allow for better species
  beestation.dme
  code/__DEFINES/mobs.dm
  code/game/objects/items.dm
  code/game/objects/items/cards_ids.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/IPC.dm
  code/modules/mob/living/carbon/human/species_types/apid.dm
  code/modules/mob/living/carbon/human/species_types/debug.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/mob/living/carbon/human/species_types/oozelings.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/carbon/human/species_types/squidpeople.dm
  code/modules/mob/living/carbon/human/species_types/synths.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/mob/species/debug/debug_all.dmi
Labels: sprites, Code Improvement, Plannedemic💉

#5509 Fix view_size again
  code/datums/view.dm
  code/modules/client/preferences.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/login.dm
Labels: Fix

#5517 Removes deathrattle station traits
  code/datums/station_traits/positive_traits.dm
Labels: Removal

#5513 Adds admin Jump link to EMP logs.
  code/game/objects/empulse.dm
Labels: Administration

#5497 Adds Custom Shuttle as a Station Goal
  beestation.dme
  code/modules/station_goals/custom_shuttle.dm
Labels: Feature

#5495 Squidpeople don't wear socks anymore.
  code/__DEFINES/DNA.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/squidpeople.dm
Labels: Tweak, Feature

#5304 deadchat_control is now a special brain trauma and an admin smite
  code/__DEFINES/admin.dm
  code/datums/brain_damage/special.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/mob/living/simple_animal/hostile/goose.dm
Labels: Feature, Administration

#5521 Several typo fixes
  code/game/objects/structures/girders.dm
  code/modules/admin/battle_royale.dm
  code/modules/antagonists/clock_cult/items/brass_clothing.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/objective_types/vip_extraction.dm
Labels: Grammar and Formatting, Administration

#5487 Fixing afterattack to call lighteater_act properly
  code/game/mecha/mecha.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
Labels: Fix, hacktoberfest-accepted

#5647 Fixing a minor typo in preferences_toggles
  code/modules/client/preferences_toggles.dm
Labels: Fix, Grammar and Formatting

#5520 Better borg mesons
  code/_onclick/hud/robot.dm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Tweak

#5526 Fixes objectives disappearing on cryo
  code/game/machinery/cryopod.dm
  code/modules/antagonists/incursion/incursion.dm
Labels: Fix, Code Improvement

#5648 Punch damage is now consistent
  _maps/map_files/MetaStation/MetaStation.dmm
  code/modules/antagonists/clock_cult/mobs/eminence.dm
  code/modules/antagonists/revenant/revenant.dm
  code/modules/mob/living/carbon/alien/alien_defense.dm
  code/modules/mob/living/carbon/alien/humanoid/humanoid_defense.dm
  code/modules/mob/living/carbon/alien/larva/larva_defense.dm
  code/modules/mob/living/silicon/silicon_defense.dm
  code/modules/mob/living/simple_animal/animal_defense.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/hostile/bees.dm
  code/modules/mob/living/simple_animal/hostile/eyeballs.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/elite.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
  code/modules/mob/living/simple_animal/hostile/wumborian_fugu.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: mapping, Tweak, Fix, Balance/Rebalance

#5657 Fixes dd.log not holding revision information
  code/datums/helper_datums/getrev.dm
Labels: Fix, server

#5660 Corrects the burn chamber's mapping area on Pubby
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: mapping, Fix

#5656 +1 GBP
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: Feature, Code Improvement

#5669 Fixes spin and flip confusion
  code/modules/mob/emote.dm
Labels: Fix
