Repository BeeStation/BeeStation-Hornet, pull requests merged in 2021-08, with the labels that each got.

#4999 Fixes igniters and sparks failing to ignite flammable gases
  code/modules/atmospherics/environmental/LINDA_fire.dm
Labels: Fix

#5001 Corrects the resources.txt file for local dev
  config/resources.txt
Labels: Config Update

#4991 [PORT] Emag pAIs to unbind them
  code/modules/mob/living/silicon/pai/pai.dm
Labels: Feature

#4997 Chat message optimisations
  code/__DEFINES/say.dm
  code/datums/brain_damage/imaginary_friend.dm
  code/datums/chatmessage.dm
  code/datums/emotes.dm
  code/game/atoms.dm
  code/game/machinery/hologram.dm
  code/game/machinery/telecomms/broadcasting.dm
  code/game/say.dm
  code/modules/antagonists/disease/disease_mob.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/mob/dead/observer/say.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
  code/modules/mob/mob.dm
Labels: Needs Testmerge, Refactor, Somewhat important, test merged

#4836 Stat panel verb caching
  code/game/objects/items.dm
  code/game/verbs.dm
  code/modules/mob/login.dm
  code/modules/mob/mob_stat.dm
  code/modules/tgui_panel/stat.dm
  code/modules/tgui_panel/tgui_panel.dm
  tgui/packages/tgui-panel/stat/StatText.js
  tgui/packages/tgui-panel/stat/reducer.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.css
Labels: Refactor, Somewhat important, TGUI-Changes, test merged

#5010 Brutally fixes tgui
  tgui/public/tgui.bundle.css
Labels: TGUI-Changes

#5017 Fixes false positive quirk cap trigger
  code/modules/client/preferences.dm
Labels: Fix

#4980 Clarifies Sentience Potion Spawns in the popup
  code/modules/research/xenobiology/xenobiology.dm
Labels: Feature

#5019 Fixes deaf people being able to see runechat messages.
  code/datums/chatmessage.dm
  code/game/machinery/hologram.dm
  code/game/machinery/telecomms/broadcasting.dm
  code/game/say.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob.dm
Labels: Fix

#5021 Improves get all open uis()
  code/controllers/subsystem/tgui.dm
Labels: Code Improvement

#5026 Sets auto update on Sleeper and Operating Computer
  code/game/machinery/Sleeper.dm
  code/game/machinery/computer/Operating.dm
Labels: Feature

#5009 Makes the telescreen UI activate on examine rather than click
  code/game/machinery/computer/camera.dm
Labels: Tweak

#5007 Replaces station bounced radio sprite
  icons/obj/radio.dmi
Labels: Feature, Vote Passed, Voting, sprites

#5031 Fixes crafting UI not updating after crafting but I commit to the right branch
  code/datums/components/crafting/crafting.dm
Labels: Fix

#5016 Ghosts can now examine wires to check their power status
  code/modules/power/cable.dm
Labels: Feature

#5022 The cancel button on the supply requests console now works
  code/modules/cargo/console.dm
Labels: Fix

#5030 Fixes the beecoin shop nurse uniform... hopefully?
  code/modules/client/loadout/loadout_uniform.dm
Labels: Fix

#5037 Sets the Gene Console UI to auto update
  code/game/machinery/computer/dna_console.dm
Labels: Feature

#5042 Get approval from a Maintainer for species changes
  .github/CONTRIBUTING.md
Labels: GitHub

#5041 Nuke now autoupdates ui
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
Labels: Feature

#5043 fix door timer UI update
  code/game/machinery/doors/brigdoors.dm
Labels: Fix

#4696 Fixes a missing wire in Box maint, floating light and replaces the blank computer with a SciDrobe on lavaland
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Mining/Lavaland.dmm
Labels: mapping, Tweak, Fix

#5003 Removes the Pheromone Receptor ability
  beestation.dme
  code/modules/antagonists/changeling/powers/pheromone_receptors.dm
Labels: Removal

#4961 fix midwife wrapping
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
Labels: Fix

#4977 Lets Ethereals wear socks, underwear, and t-shirts
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
Labels: Tweak

#4937 Sets a description for the teratoma ghost spawner.
  code/datums/diseases/advance/symptoms/heal.dm
Labels: Feature

#4891 Fixes some runtimes related to outfits
  code/__DEFINES/mobs.dm
  code/datums/components/_component.dm
  code/datums/components/stationloving.dm
  code/game/objects/items/implants/implant_abductor.dm
  code/game/objects/items/implants/implant_exile.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/debug.dm
  code/modules/antagonists/abductor/equipment/abduction_outfits.dm
  code/modules/antagonists/fugitive/fugitive_outfits.dm
  code/modules/clothing/outfits/event.dm
  code/modules/clothing/shoes/taeclowndo.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/gimmick.dm
  code/modules/mob/living/carbon/human/damage_procs.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/IPC.dm
  code/modules/mob/living/carbon/human/species_types/android.dm
  code/modules/mob/living/carbon/life.dm
Labels: Fix, Administration

#4903 Moves stuff around in Delta kitchen
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: mapping, Tweak

#4990 Adds the ability to clear a pAI's zeroth law.
  code/game/objects/items/devices/paicard.dm
Labels: Feature

#5052 pAI PDA messages now show up as actually from a person, and can be replied to.
  code/modules/mob/living/silicon/pai/software.dm
Labels: Feature

#5051 Fixing Jellypeople
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
Labels: Fix

#5045 wzhzhzh Port of TGStation #53366
  code/modules/food_and_drinks/kitchen_machinery/microwave.dm
Labels: Code Improvement

#5039 Round time starts counting from round-start, not world-start
  code/__HELPERS/time.dm
  code/_globalvars/misc.dm
  code/game/world.dm
  code/modules/mob/mob_stat.dm
Labels: Tweak

#5032 New bans default to global
  code/modules/admin/sql_ban_system.dm
Labels: Administration

#5023 Defibrillator paddle fixes
  code/game/objects/items/defib.dm
Labels: Feature, Fix

#4975 Mediborg's Amputation Adventure - Emag Edition
  code/game/machinery/computer/arcade.dm
Labels: Feature

#4960 Adds ERT Override AI laws.
  code/datums/ai_laws.dm
  code/game/objects/items/AI_modules.dm
  code/modules/clothing/outfits/ert.dm
Labels: Tweak, Feature, Fix, Grammar and Formatting, Balance/Rebalance, Refactor, Removal, Code Improvement, server

#4932 Fixes animals not being able to move after being tabled
  code/game/objects/structures/tables_racks.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
Labels: Fix

#5040 Fix some CRLF json files
  TGS3.json
  _maps/boxstation.json
  _maps/multiz_debug.json
  _maps/runtimestation.json
Labels: GitHub

#4940 FIXES HEARING FOR THE 17TH TIME
  code/game/machinery/Sleeper.dm
  code/game/machinery/harvester.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/pet_carrier.dm
  code/game/turfs/open/lava.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/spells/spell_types/shapeshift.dm
Labels: Fix

#5006 Removes the soul from chaplain.dm (Removes banbait religions)
  code/modules/jobs/job_types/chaplain.dm
Labels: Removal

#4988 baby's first PR / ports plasmaglass tables from Cit
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/structures/tables_racks.dm
  icons/obj/smooth_structures/plasmaglass_table.dmi
Labels: Feature, sprites, Removal

#4866 Changes Commando Names.
  strings/names/death_commando.txt
Labels: Tweak, Fix

#4764 Retro jacket and retro chicken head - new donator items
  code/modules/client/loadout/loadout_donator.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/mob/head.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, sprites

#4967 You can no longer deconstruct tables and racks on help intent.
  code/game/objects/structures/tables_racks.dm
Labels: Stale, Tweak

#4861 Juke Build Reforged
  .dockerignore
  .editorconfig
  .github/workflows/continuous_integration.yml
  .gitignore
  .tgs4.yml
  .vscode/launch.json
  .vscode/tasks.json
  BUILD.bat
  Dockerfile
  README.md
  code/_compile_options.dm
  code/modules/asset_cache/asset_list_items.dm
  dependencies.sh
  tgui/.gitignore
  tgui/bin/tgui
  tgui/packages/tgfont/dist/tgfont.css
  tgui/packages/tgfont/dist/tgfont.eot
  tgui/packages/tgfont/dist/tgfont.woff2
  tgui/public/tgui-common.bundle.js
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.css
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
  tools/bootstrap/node
  tools/bootstrap/node.bat
  tools/bootstrap/node_.ps1
  tools/build/.editorconfig
  tools/build/README.md
  tools/build/build
  tools/build/build.bat
  tools/build/build.js
  tools/build/cbt/dm.js
  tools/build/cbt/fs.js
  tools/build/cbt/winreg.js
  tools/build/cbt/yarn.js
  tools/build/juke/index.d.ts
  tools/build/juke/index.js
  tools/ci/build.ps1
  tools/ci/build_tgui.sh
  tools/ci/dm.sh
  tools/ci/install_build_tools.sh
  tools/ci/install_node.sh
  tools/ci/run_server.sh
  tools/deploy.sh
  tools/linux_build.py
  tools/tgs4_scripts/PreCompile.bat
  tools/tgs4_scripts/PreCompile.sh
  yarn.lock
Labels: Feature, GitHub, tools, Code Improvement, server, TGUI-Changes

#4800 Ports tg's cavegen, bitfields, area_flags, improved random mineral rocks
  _maps/RandomRuins/SpaceRuins/crashedship.dmm
  _maps/RandomRuins/SpaceRuins/derelict4.dmm
  _maps/RandomRuins/SpaceRuins/derelict5.dmm
  _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
  _maps/map_files/Mining/Lavaland.dmm
  beestation.dme
  code/__DEFINES/bitfields.dm
  code/__DEFINES/flags.dm
  code/__DEFINES/mobs.dm
  code/__HELPERS/areas.dm
  code/__HELPERS/unsorted.dm
  code/_globalvars/bitfields.dm
  code/_globalvars/lists/mapping.dm
  code/controllers/subsystem/mapping.dm
  code/datums/mapgen/CaveGenerator.dm
  code/datums/mapgen/Cavegens/LavalandGenerator.dm
  code/datums/wires/airalarm.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas.dm
  code/game/area/areas/centcom.dm
  code/game/area/areas/holodeck.dm
  code/game/area/areas/mining.dm
  code/game/area/areas/ruins/_ruins.dm
  code/game/area/areas/ruins/space.dm
  code/game/area/areas/shuttles.dm
  code/game/machinery/bank_machine.dm
  code/game/objects/items/crayons.dm
  code/game/objects/items/stacks/bscrystal.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/teleportation.dm
  code/game/objects/structures/ai_core.dm
  code/game/turfs/closed/minerals.dm
  code/game/turfs/open/floor/plating/asteroid.dm
  code/modules/antagonists/blob/overmind.dm
  code/modules/antagonists/blob/powers.dm
  code/modules/antagonists/blob/structures/_blob.dm
  code/modules/antagonists/cult/cult.dm
  code/modules/antagonists/cult/ritual.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/antagonists/gang/gang.dm
  code/modules/atmospherics/machinery/airalarm.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/mining/equipment/survival_pod.dm
  code/modules/mining/ores_coins.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/silicon/ai/multicam.dm
  code/modules/research/xenobiology/xenobio_camera.dm
  code/modules/research/xenobiology/xenobiology.dm
  code/modules/ruins/spaceruin_code/hilbertshotel.dm
Labels: mapping, Needs Testmerge, Tweak, Feature, Refactor, Removal

#4958 [PORT] EVEN MORE HARDDEL FIXES
  code/_onclick/observer.dm
  code/controllers/subsystem/throwing.dm
  code/datums/brain_damage/split_personality.dm
  code/datums/components/chasm.dm
  code/datums/holocall.dm
  code/datums/mutations/antenna.dm
  code/datums/status_effects/status_effect.dm
  code/game/atoms_movable.dm
  code/game/communications.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/camera/motion.dm
  code/game/machinery/camera/presets.dm
  code/game/machinery/computer/atmos_control.dm
  code/game/machinery/computer/crew.dm
  code/game/machinery/computer/teleporter.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/doors/brigdoors.dm
  code/game/machinery/hologram.dm
  code/game/machinery/teleporter.dm
  code/game/objects/items/devices/camera_bug.dm
  code/game/objects/items/implants/implant_misc.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/tanks/tanks.dm
  code/game/objects/items/teleportation.dm
  code/game/objects/objs.dm
  code/game/objects/structures/girders.dm
  code/game/turfs/turf.dm
  code/modules/admin/verbs/diagnostics.dm
  code/modules/antagonists/traitor/equipment/Malf_Modules.dm
  code/modules/atmospherics/machinery/components/unary_devices/heat_exchanger.dm
  code/modules/buildmode/buildmode.dm
  code/modules/detectivework/detective_work.dm
  code/modules/mob/login.dm
  code/modules/mob/mob.dm
  code/modules/plumbing/ducts.dm
  code/modules/projectiles/ammunition/_ammunition.dm
  code/modules/station_goals/bsa.dm
  code/modules/tgui/tgui.dm
Labels: Fix, Administration, Merge Conflict, Removal

#4742 Security blue shirt uniform fix
  code/modules/client/loadout/loadout_uniform.dm
  code/modules/clothing/under/jobs/security.dm
Labels: Stale, Fix

#4626 STOP wearing replacement envirosuit helmets when you're not a plasmaman
  code/modules/clothing/outfits/plasmaman.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/clothing/under/jobs/Plasmaman/engineering.dm
  code/modules/vending/wardrobes.dm
Labels: Feature, Fix, Grammar and Formatting, Balance/Rebalance

#4865 Ability to fireman carry or have monkeys piggyback you
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
Labels: Feature

#5033 Updates RPED and BSRPED inhands
  code/modules/research/stock_parts.dm
  icons/mob/inhands/misc/devices_lefthand.dmi
  icons/mob/inhands/misc/devices_righthand.dmi
Labels: Tweak, Feature, sprites

#4928 Teleporter things
  code/game/machinery/computer/teleporter.dm
  code/game/machinery/teleporter.dm
Labels: Feature, Fix

#5062 Fixes the medical skirt sprites.
  icons/mob/uniform.dmi
Labels: sprites, Fix

#5066 Fix precompile.bat for TGS
  tools/tgs4_scripts/PreCompile.bat
Labels: Fix, tools, server, TGS

#5067 Updates CODEOWNERS
  .github/CODEOWNERS
Labels: GitHub

#5071 Removes the bluespace miner
  beestation.dme
  code/controllers/configuration/entries/game_options.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/modules/mining/machine_bluespaceminer.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/techweb/all_nodes.dm
  config/game_options.txt
Labels: Config Update, Removal

#5060 Lighting Quickfixes, Seclights and Swarmers
  code/datums/components/overlay_lighting.dm
  code/modules/antagonists/swarmer/swarmer.dm
Labels: Fix

#5038 Increases the rate at which welders burn fuel
  code/game/objects/items/tools/weldingtool.dm
Labels: Balance/Rebalance, Vote Passed

#5068 Removes non static typecacheof uses in storage component
  code/__DEFINES/dcs/signals.dm
  code/datums/components/storage/storage.dm
  code/modules/mining/satchel_ore_boxdm.dm
  code/modules/reagents/chemistry/machinery/reagentgrinder.dm
  code/modules/research/xenobiology/crossbreeding/reproductive.dm
Labels: Refactor

#5081 Cheap lighter no longer costs more than Zippo
  code/game/objects/items/cigs_lighters.dm
Labels: Balance/Rebalance

#5085 Shameless self-insert
  sound/voice/lizard/credits.txt
Labels: sound

#5063 Dockerfile updates + BYOND version bump
  Dockerfile
  dependencies.sh
Labels: dependencies, GitHub, Refactor

#4720 Removes heretics gamemode, they can only spawn on dynamic now.
  config/game_options.txt
Labels: Config Update, Refactor

#5092 A couple plumbing fixes
  code/datums/components/plumbing/_plumbing.dm
  code/modules/plumbing/ducts.dm
Labels: Fix

#5087 Laptops and tablets no longer drop a battery when destroyed
  code/modules/modular_computers/hardware/battery_module.dm
Labels: Tweak, Fix, Removal

#5100 Has the run_all_tests job actually run tests
  .github/workflows/continuous_integration.yml
  code/controllers/subsystem/title.dm
  icons/runtime/README.md
  icons/runtime/default_title.dmi
Labels: sprites, GitHub

#5102 Fixes midround spawning
  code/modules/events/_event.dm
Labels: Fix

#5084 AIs can no longer strip people
  code/modules/mob/mob.dm
Labels: Fix

#3801 Topic System Overhaul
  beestation.dme
  code/__DEFINES/subsystems.dm
  code/__HELPERS/unsorted.dm
  code/_globalvars/misc.dm
  code/controllers/configuration/entries/comms.dm
  code/controllers/subsystem/fail2topic.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/topic.dm
  code/datums/world_topic.dm
  code/game/machinery/computer/communications.dm
  code/game/world.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/discord/discord.dm
  code/modules/discord/from_discord.dm
  code/modules/mob/dead/dead.dm
  config/README.md
  config/comms.txt
  tools/WebhookProcessor/github_webhook_processor.php
Labels: ike like, Config Update, Administration, tools, Triaged, server

#5112 Game mode config change time
  config/game_options.txt
Labels: Config Update

#5061 Makes the handheld crew pinpointer display who it's pinpointing.
  code/game/objects/items/pinpointer.dm
Labels: Feature

#5109 Makes the Muscled Veins surgery actually work.
  code/modules/surgery/advanced/bioware/muscled_veins.dm
Labels: Fix

#5115 Allow Case-Sensitive Topic Tokens
  code/controllers/configuration/config_entry.dm
  code/controllers/configuration/entries/comms.dm
Labels: Fix

#5113 Ports the TG Stasis Bed Sprite
  icons/obj/machines/stasis.dmi
Labels: Feature, sprites

#5094 The Incredible Fusion of Medical HUD and Prescription Glasses
  code/modules/clothing/glasses/hud.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/mob/eyes.dmi
  icons/obj/clothing/glasses.dmi
Labels: Feature, sprites

#5004 Adjusts requirements to unlock jobs (Take two)
  code/modules/jobs/job_types/ai.dm
  code/modules/jobs/job_types/atmospheric_technician.dm
  code/modules/jobs/job_types/brigphys.dm
  code/modules/jobs/job_types/chemist.dm
  code/modules/jobs/job_types/emt.dm
  code/modules/jobs/job_types/geneticist.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/medical_doctor.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/jobs/job_types/scientist.dm
  code/modules/jobs/job_types/station_engineer.dm
  code/modules/jobs/job_types/virologist.dm
Labels: Tweak

#5124 turtle_nerf
  code/modules/mob/living/simple_animal/friendly/turtle.dm
Labels: Balance/Rebalance

#5125 Hides mentor badge if admin badge shows
  code/modules/badges/badges.dm
Labels: Tweak, Administration

#5126 fix roundstart cultists not getting objectives
  code/modules/antagonists/cult/cult.dm
Labels: Fix

#5107 EMP damage holosigns and holobarriers
  code/game/objects/structures/holosign.dm
Labels: Feature

#5131 Turtle_buff
  code/modules/mob/living/simple_animal/friendly/turtle.dm
Labels: Balance/Rebalance

#5000 EORG Arena Prototype [MDB IGNORE]
  _maps/map_files/generic/CentCom.dmm
  code/__HELPERS/roundend.dm
  code/_globalvars/misc.dm
  code/game/area/areas/centcom.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/structures/barsigns.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_toggles.dm
Labels: mapping, Tweak, Feature

#5135 Revert "EORG Arena Prototype [MDB IGNORE]"
  _maps/map_files/generic/CentCom.dmm
  code/__HELPERS/roundend.dm
  code/_globalvars/misc.dm
  code/game/area/areas/centcom.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/structures/barsigns.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_toggles.dm
Labels: mapping, Removal

#5012 Adds Bulk Discount as an option for Uplink Discounts
  code/modules/uplink/uplink_items.dm
Labels: Feature

#5119 Intercomms are above windows
  code/game/objects/items/devices/radio/intercom.dm
Labels: Tweak

#5121 juggernauts cant be pulled
  code/modules/mob/living/simple_animal/constructs.dm
Labels: Balance/Rebalance

#5020 Converts the component printer to modular fabricator.
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/debug/runtimestation.dmm
  code/__DEFINES/wiremod.dm
  code/game/machinery/fabricators/modular_fabricator.dm
  code/modules/research/designs/wiremod_designs.dm
  code/modules/research/techweb/_techweb.dm
  code/modules/wiremod/component_printer.dm
  tgui/packages/tgui/interfaces/ComponentPrinter.tsx
Labels: mapping, Refactor, TGUI-Changes

#4870 fixes turrets not working after it's turned off and on again
  code/game/machinery/porta_turret/portable_turret.dm
Labels: Fix

#5146 Bumps auxmos to latest version
  Dockerfile
  auxtools/auxmos.dll
  code/_compile_options.dm
  dependencies.sh
Labels: Feature

#4832 [PORT] Popper Tooltips 2 (they don't crash this time)
  tgui/docs/component-reference.md
  tgui/packages/tgui-panel/Panel.js
  tgui/packages/tgui/components/Button.js
  tgui/packages/tgui/components/Popper.tsx
  tgui/packages/tgui/components/Tooltip.js
  tgui/packages/tgui/components/Tooltip.tsx
  tgui/packages/tgui/components/index.js
  tgui/packages/tgui/interfaces/Canister.js
  tgui/packages/tgui/interfaces/CentcomPodLauncher.js
  tgui/packages/tgui/interfaces/ComputerFabricator.js
  tgui/packages/tgui/interfaces/Guardian.js
  tgui/packages/tgui/interfaces/NtosRoboControl.js
  tgui/packages/tgui/interfaces/manually-routed/KitchenSink.js
  tgui/packages/tgui/layouts/NtosWindow.js
  tgui/packages/tgui/package.json
  tgui/packages/tgui/stories/Popper.stories.js
  tgui/packages/tgui/stories/Tooltip.stories.js
  tgui/packages/tgui/styles/components/Tooltip.scss
  tgui/public/tgui.html
  tgui/yarn.lock
Labels: Fix, Code Improvement, TGUI-Changes

#5151 Updates our CL header to include a few more spriters + coders
  html/templates/header.html
Labels: Tweak, Code Improvement

#5134 Spiders: Prevents player-controlled spiders from reproducing without a directive.
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
Labels: Tweak, Feature

#5158 another important recursive contents fix
  code/game/atoms_movable.dm
Labels: Fix

#5160 Fixes poll voting
  code/modules/mob/dead/new_player/poll.dm
Labels: Fix

#5157 Fixes a typo
  code/modules/surgery/organs/lungs.dm
Labels: Fix, Grammar and Formatting

#5163 Gives layer manifolds volume
  code/modules/atmospherics/machinery/pipes/layermanifold.dm
Labels: Feature

#5149 rouny
  code/game/machinery/computer/arcade.dm
  code/game/objects/items/plushes.dm
  icons/obj/plushes.dmi
Labels: Feature, sprites

#5097 Fixes ChemPress.js which is used for the plumbing pill press
  tgui/packages/tgui/interfaces/ChemPress.js
Labels: Fix, TGUI-Changes

#5161 'Archival Tape' Announcer
  beestation.dme
  code/datums/announcers/baystation_announcer.dm
  code/datums/station_traits/neutral_traits.dm
  sound/ai/baystation/aliens.ogg
  sound/ai/baystation/attention.ogg
  sound/ai/baystation/commandreport.ogg
  sound/ai/baystation/granomalies.ogg
  sound/ai/baystation/intercept.ogg
  sound/ai/baystation/ionstorm.ogg
  sound/ai/baystation/meteors.ogg
  sound/ai/baystation/outbreak5.ogg
  sound/ai/baystation/outbreak7.ogg
  sound/ai/baystation/poweroff.ogg
  sound/ai/baystation/poweron.ogg
  sound/ai/baystation/radiation.ogg
  sound/ai/baystation/shuttlecalled_static.ogg
  sound/ai/baystation/shuttledock.ogg
  sound/ai/baystation/shuttlerecalled.ogg
  sound/ai/baystation/spanomalies.ogg
  sound/ai/baystation/welcome.ogg
Labels: test merged, Feature, sound

#5152 SSmetrics
  beestation.dme
  code/__DEFINES/MC.dm
  code/__HELPERS/time.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem.dm
  code/controllers/subsystem/acid.dm
  code/controllers/subsystem/fire_burning.dm
  code/controllers/subsystem/garbage.dm
  code/controllers/subsystem/lighting.dm
  code/controllers/subsystem/machines.dm
  code/controllers/subsystem/metrics.dm
  code/controllers/subsystem/mobs.dm
  code/controllers/subsystem/processing/processing.dm
  code/controllers/subsystem/spacedrift.dm
  code/controllers/subsystem/tgui.dm
  code/controllers/subsystem/throwing.dm
  code/controllers/subsystem/timer.dm
  code/controllers/subsystem/weather.dm
  code/game/world.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/subsystem_metric_sanity.dm
  config/config.txt
Labels: Config Update, server

#4957 adds a way to vv edit gas mixtures
  code/__DEFINES/vv.dm
  code/modules/atmospherics/gasmixtures/gas_mixture.dm
Labels: Feature

#4902 Adds Coffee the Crab to BoxStation
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: mapping, Stale, Feature

#5222 Hardens admin permissions procs against abuse
  code/modules/admin/permissionedit.dm
Labels: Administration

#5218 New Badge
  config/badges.json
  icons/badges.dmi
Labels: sprites

#5089 Changes the corporate lawset
  code/datums/ai_laws.dm
Labels: Tweak

#5227 Fix solar control visuals
  code/modules/power/solar.dm
  icons/obj/computer.dmi
Labels: sprites, Fix

#5235 Fix bad tooltip positions in admin pod launcher
  tgui/packages/tgui/interfaces/CentcomPodLauncher.js
Labels: Fix, TGUI-Changes

#5228 Fix broken computer overlays glowing in the dark and having redundant opaque shadows
  code/game/machinery/computer/_computer.dm
  code/game/machinery/computer/arcade.dm
  code/game/machinery/computer/camera.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/security.dm
  code/modules/antagonists/clock_cult/structure/clockwork_camera.dm
  code/modules/library/lib_machines.dm
  icons/obj/computer.dmi
Labels: sprites, Fix

#5213 Adds the extremely fake nuke disk as an arcade prize
  code/game/machinery/computer/arcade.dm
Labels: Feature

#5232 Discord round report now includes dynamic summary
  code/__HELPERS/roundend.dm
Labels: Feature

#5233 Finger gun no longer moves you in space.
  code/modules/projectiles/ammunition/_ammunition.dm
  code/modules/projectiles/ammunition/_firing.dm
  code/modules/projectiles/ammunition/ballistic/revolver.dm
Labels: Fix

#5231 Ai multi-z cam jump
  beestation.dme
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/ai.dm
  icons/mob/screen_ai.dmi
Labels: Feature, sprites

#5225 Bans now properly register notes
  code/modules/admin/sql_ban_system.dm
Labels: sql, Administration, server

#5240 Fixes the Discord dynamic report
  code/__HELPERS/roundend.dm
Labels: Fix

#4806 Clothing armor value tag on examine from /tg/
  code/modules/clothing/clothing.dm
Labels: Feature

#4859 Tgui botany
  code/modules/hydroponics/gene_modder.dm
  code/modules/hydroponics/seed_extractor.dm
  tgui/packages/tgui/interfaces/PlantDNAManipulator.js
  tgui/packages/tgui/interfaces/SeedExtractor.js
Labels: Feature, TGUI-Changes

#5175 Fixes blood brother on the antag panel.
  code/modules/antagonists/brother/brother.dm
Labels: Fix

#5238 Changes the budget pre-initialize name
  code/game/objects/items/cards_ids.dm
Labels: Tweak

#5110 Replaces the spriteless security jumpsuit in delta sec maints
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: mapping, Fix, Removal
