Repository BeeStation/BeeStation-Hornet, pull requests merged in 2021-09, with the labels that each got.

#5242 Power monitors now report 100% power on cogged APCs
  code/game/objects/items/devices/PDA/cart.dm
  code/modules/modular_computers/file_system/programs/powermonitor.dm
  code/modules/power/monitor.dm
Labels: Balance/Rebalance

#5248 RD now has exploration access
  code/modules/jobs/job_types/research_director.dm
Labels: Fix

#5253 Budget cards are indestructible
  code/game/objects/items/cards_ids.dm
Labels: Tweak

#5254 Explo HUD, Better HoP console, Better HUD
  code/game/machinery/computer/card.dm
  code/modules/jobs/access.dm
  icons/mob/hud.dmi
Labels: Feature, sprites, Fix

#5259 Fixes corgstation disposals.
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: mapping, Fix

#5265 Shadow realm changes.
  code/game/turfs/open/_open.dm
  code/modules/antagonists/wizard/equipment/artefact.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/loot/alien_artifact.dm
Labels: Tweak

#5264 Corgstation fix #2
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: mapping, Tweak, Fix

#5261 Fixes QM headset having and defaulting exploration access.
  code/game/objects/items/devices/radio/headset.dm
Labels: Fix

#5267 Fixes custom shuttle docking
  code/modules/shuttle/custom_shuttle.dm
  code/modules/shuttle/super_cruise/shuttle_components/shuttle_console.dm
  code/modules/shuttle/super_cruise/shuttle_components/shuttle_docking.dm
Labels: Fix, Somewhat important

#5269 Improves BR loot
  code/modules/admin/battle_royale.dm
Labels: Feature, Administration

#5223 Fix missing equipment for mecha
  code/game/mecha/equipment/mecha_equipment.dm
Labels: Fix

#5271 Paramedic Nitrile Gloves Commit
  code/modules/jobs/job_types/emt.dm
Labels: Tweak, Feature

#5239 Bone axe now properly changes sprites when wielded
  code/game/objects/items/fireaxe.dm
Labels: Fix

#5226 IPC EMP soft rework
  code/__DEFINES/language.dm
  code/__DEFINES/status_effects.dm
  code/datums/status_effects/debuffs.dm
  code/modules/surgery/organs/ears.dm
  code/modules/surgery/organs/tongue.dm
Labels: Balance/Rebalance

#5136 fixes instruments not beeing hearable by mobs in content lists etc.
  code/game/objects/structures/musician.dm
Labels: Fix, Code Improvement

#5277 Some Exploration Gear fits in Exploration Webbing
  code/game/objects/items/storage/belt.dm
Labels: Tweak

#5272 Fixes a typo that causes warnings.
  code/modules/shuttle/super_cruise/orbital_poi_generator/loot/alien_artifact.dm
Labels: THIS IS VERY IMPORTANT, Fix

#5255 You can now print multiple wanted/missing posters
  code/game/machinery/computer/security.dm
Labels: Feature

#5280 More Explorer Web Additions
  code/game/objects/items/storage/belt.dm
Labels: Tweak

#5244 Wagging your tail is a visible emote again
  code/modules/mob/living/carbon/human/emote.dm
Labels: Tweak

#5279 Fixes LoadReebe
  code/modules/antagonists/clock_cult/helpers/reebe_loader.dm
Labels: Fix

#5289 Fixes Instruments t2
  code/game/objects/structures/musician.dm
Labels: Fix

#5295 Runechat fixes
  code/modules/mob/living/say.dm
Labels: Fix

#5293 Gives meta and pubby proper exploration comms setup.
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: mapping, Tweak, Somewhat important, Supercruise

#5292 Removes skywalker from the list of random last names
  strings/names/last.txt
Labels: Removal

#5257 Asteroid mining improvements
  code/game/objects/structures/flora.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/asteroid_generator.dm
Labels: Tweak, Supercruise

#5230 Ai multi-z uploading.
  code/game/machinery/computer/law.dm
Labels: Fix

#5285 Updates exploration allinonbox.
  code/game/machinery/telecomms/machines/allinone.dm
Labels: Fix, Supercruise

#5249 Adds pets to a variety of places!
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/shuttles/capsule_traitor.dmm
  _maps/shuttles/exploration_corg.dmm
  _maps/shuttles/exploration_delta.dmm
  _maps/shuttles/exploration_shuttle.dmm
Labels: mapping, Feature

#5221 Adds Debtor and Assistant traitor item, Bottle of Mystery Pills
  code/modules/uplink/uplink_items.dm
Labels: Voting, Feature

#5299 Deadchat controlled Birdboat (and Singularity)
  beestation.dme
  code/__DEFINES/dcs/signals.dm
  code/datums/components/deadchat_control.dm
  code/datums/components/orbiter.dm
  code/modules/mob/living/simple_animal/hostile/goose.dm
  code/modules/mob/say.dm
  code/modules/power/singularity/singularity.dm
Labels: Feature

#5300 Ports the Requests Manager
  beestation.dme
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/pray.dm
  code/modules/admin/verbs/requests.dm
  code/modules/client/client_procs.dm
  code/modules/requests/request.dm
  code/modules/requests/request_manager.dm
  tgui/packages/tgui/interfaces/RequestManager.js
  tgui/packages/tgui/styles/interfaces/RequestManager.scss
  tgui/packages/tgui/styles/main.scss
Labels: Administration, Code Improvement, TGUI-Changes

#4979 Port fixes and refactors for adminhelp and TGS/IRC/Discord communication
  code/__HELPERS/roundend.dm
  code/_onclick/ai.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/mobs.dm
  code/controllers/subsystem/ticker.dm
  code/modules/admin/chat_commands.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/admin/sql_message_system.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/verbs/who.dm
  code/modules/mob/living/carbon/update_icons.dm
  code/modules/shuttle/emergency.dm
Labels: Refactor, Administration

#5091 Removes adminheal and instant death bolts from xenobiology magicarps (Chaos + regular).
  code/modules/events/wizard/magicarp.dm
Labels: Balance/Rebalance

#5111 Minor radio/intercom fixes and improvements
  code/game/objects/items/devices/radio/intercom.dm
  code/game/objects/items/devices/radio/radio.dm
Labels: Fix

#5148 IPC hands clipping fix
  icons/mob/human_parts.dmi
  icons/mob/human_parts_greyscale.dmi
Labels: sprites, Fix

#5241 Refactor to syndie boxes/kits
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/admin/battle_royale.dm
  code/modules/awaymissions/mission_code/Academy.dm
  code/modules/uplink/uplink_items.dm
Labels: Refactor, Administration

#5302 Nuclear detonation countdown music
  code/game/sound.dm
  code/modules/antagonists/nukeop/equipment/nuclear_challenge.dm
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
  sound/soundtrack/countdown.ogg
Labels: Feature, Vote Passed, sound

#4685 X-ray flash protection changes
  code/game/objects/items/grenades/flashbang.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/surgery/organs/autosurgeon.dm
  code/modules/surgery/organs/eyes.dm
Labels: Feature, Balance/Rebalance

#4665 Fireman carry qol from /tg/
  code/datums/components/riding.dm
  code/game/objects/buckling.dm
  code/game/objects/structures/morgue.dm
  code/game/objects/structures/tables_racks.dm
Labels: Feature, Balance/Rebalance

#4790 Remote Material Connections may not cross Z-levels
  code/datums/components/remote_materials.dm
Labels: Balance/Rebalance

#4772 Bluespace bag of holdings now require line of site to dump contents at range.
  code/datums/components/storage/concrete/bluespace.dm
Labels: Balance/Rebalance

#4969 Supermatter Surge
  beestation.dme
  code/modules/events/supermatter_surge.dm
Labels: Feature

#4986 Port a bunch of small things from the project
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/shuttles.dm
  code/__HELPERS/roundend.dm
  code/controllers/subsystem/garbage.dm
  code/datums/cinematic.dm
  code/datums/components/crafting/recipes.dm
  code/datums/components/material_container.dm
  code/game/atoms.dm
  code/game/objects/items/spear.dm
  code/game/objects/structures/transit_tubes/transit_tube_construction.dm
  code/game/turfs/closed/walls.dm
  code/game/turfs/open/floor.dm
  code/modules/admin/verbs/SDQL2/SDQL_2.dm
  code/modules/mining/machine_processing.dm
  code/modules/mining/machine_redemption.dm
  code/modules/mining/machine_stacking.dm
  code/modules/mining/machine_unloading.dm
  code/modules/mining/mint.dm
  code/modules/modular_computers/file_system/programs/alarm.dm
  code/modules/projectiles/gun.dm
Labels: Needs Testmerge, Tweak, Feature, Fix, Administration

#4987 Tgui bounty console and NTOS bounty program
  beestation.dme
  code/modules/cargo/bounty_console.dm
  code/modules/modular_computers/computers/item/tablet_presets.dm
  code/modules/modular_computers/file_system/programs/arcade.dm
  code/modules/modular_computers/file_system/programs/cargobounty.dm
  code/modules/modular_computers/hardware/printer.dm
  icons/obj/modular_console.dmi
  icons/obj/modular_laptop.dmi
  icons/obj/modular_tablet.dmi
  tgui/packages/tgui/interfaces/CargoBountyConsole.js
  tgui/packages/tgui/interfaces/NtosBountyConsole.js
Labels: Feature, sprites, TGUI-Changes

#5018 Replaces some of the more egregious spawn()s with timers
  code/game/machinery/_machinery.dm
  code/game/machinery/computer/teleporter.dm
  code/game/machinery/porta_turret/portable_turret_cover.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/tanks/watertank.dm
  code/game/objects/items/toys.dm
  code/game/objects/structures/crates_lockers/crates/bins.dm
  code/game/objects/structures/statues.dm
  code/modules/clothing/suits/reactive_armour.dm
  code/modules/hydroponics/grown/tomato.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/mob/living/silicon/ai/death.dm
  code/modules/mob/living/silicon/pai/pai_defense.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
  code/modules/mob/living/simple_animal/bot/ed209bot.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/guardian/types/lightning.dm
  code/modules/mob/living/simple_animal/hostile/mecha_pilot.dm
Labels: Refactor

#5055 Cryo syringes now freeze their reagents rather than just stopping them from reacting.
  code/game/objects/items/storage/boxes.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/research/designs/medical_designs.dm
Labels: Balance/Rebalance

#5123 Moves the ash walkers malf AI module to the syndicate vault.
  _maps/RandomRuins/LavaRuins/lavaland_surface_ash_walker1.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
Labels: mapping, Tweak, Feature, Removal

#4916 Fixes cult failing to setup, Fixes pre_setup not being run at the correct time and place.
  code/controllers/subsystem/ticker.dm
  code/game/gamemodes/clock_cult/clockcult.dm
  code/game/gamemodes/cult/cult.dm
  code/modules/admin/topic.dm
  code/modules/antagonists/clock_cult/helpers/reebe_loader.dm
Labels: Fix, Administration

#5306 Removes separated chemicals from botany
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/grown/berries.dm
  code/modules/hydroponics/plant_genes.dm
Labels: Removal

#4956 Enables Random Laws for AI
  config/game_options.txt
Labels: Config Update

#4984 Adds a living time config to the panic bunker
  code/controllers/configuration/entries/general.dm
  code/modules/admin/verbs/panicbunker.dm
  code/modules/client/client_procs.dm
  config/config.txt
Labels: Config Update, Administration

#5311 Communications consoles also work on the centcom z level
  code/game/machinery/computer/communications.dm
Labels: Tweak

#5283 Adds the AI lab ruin room.
  _maps/RuinGeneration/13x13_ai-lab.dmm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/ruin_part_types.dm
Labels: mapping, Feature, Supercruise

#5234 Reduce unnecessary tgui updates
  code/modules/tgui/tgui.dm
Labels: Code Improvement

#5047 Refactors / Rebalances some gun stuff
  code/__DEFINES/inventory.dm
  code/datums/components/twohanded.dm
  code/modules/antagonists/clock_cult/mobs/cogscarab.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/launchers.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
Labels: Balance/Rebalance

#5278 Meteor storm inbound
  beestation.dme
  code/__DEFINES/layers.dm
  code/game/gamemodes/meteor/meteors.dm
  code/modules/events/meteor_wave.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/meteor.dm
Labels: Refactor, Supercruise

#5245 Removes blocking from batongs
  code/game/objects/items/stunbaton.dm
Labels: test merged, Balance/Rebalance

#5237 Moths can no longer eat certain items.
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/_spacesuits.dm
Labels: Tweak

#5243 Chap's soulstone can no longer shard dead bodies with souls.
  code/modules/antagonists/wizard/equipment/soulstone.dm
Labels: Balance/Rebalance

#5219 More math related components for Wiremod
  beestation.dme
  code/__DEFINES/wiremod.dm
  code/modules/research/designs/wiremod_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/wiremod/components/abstract/arbitrary_input_amount.dm
  code/modules/wiremod/components/math/arithmetic.dm
  code/modules/wiremod/components/math/bitflag.dm
  code/modules/wiremod/components/math/bitwise.dm
  code/modules/wiremod/components/math/round.dm
  code/modules/wiremod/components/math/trig.dm
Labels: Tweak, Feature

#5212 fixes mech radios acting funny
  code/game/mecha/mecha.dm
Labels: Fix

#5200 More lavaland cave generation fixes
  _maps/RandomRuins/LavaRuins/lavaland_surface_seed_vault.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_swarmer_crash.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_xeno_nest.dmm
  code/__DEFINES/maps.dm
  code/controllers/subsystem/mapping.dm
  code/datums/mapgen/CaveGenerator.dm
  code/datums/mapgen/Cavegens/LavalandGenerator.dm
  code/datums/mapgen/JungleGenerator.dm
  code/game/area/areas.dm
  code/modules/mapping/preloader.dm
  code/modules/mapping/reader.dm
  icons/turf/floors.dmi
Labels: mapping, sprites

#5321 Makes abandoned crates explode on being EMPed
  code/modules/mining/abandoned_crates.dm
Labels: Feature

#5313 Supercruise - Optimised + Improved collision detection
  code/__DEFINES/orbit_defines.dm
  code/__HELPERS/names.dm
  code/controllers/subsystem/processing/orbits.dm
  code/game/turfs/open/space/transit.dm
  code/modules/events/meteor_wave.dm
  code/modules/shuttle/custom_shuttle.dm
  code/modules/shuttle/super_cruise/interface/orbital_map_interface.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_map.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_object.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/beacon.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/lavaland.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/meteor.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/phobos.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/shuttle.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/space_station.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/star.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/z_linked.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_vector.dm
  code/modules/shuttle/super_cruise/shuttle_components/shuttle_console.dm
  code/modules/shuttle/super_cruise/shuttle_supercruise.dm
Labels: Code Improvement, Supercruise

#5329 Exploration nuke no longer plays alarm.ogg
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
Labels: Removal

#5332 Fixes ambience and adds "constellations" space ambience song
  code/_globalvars/lists/ambience.dm
  code/controllers/subsystem/ambience.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas.dm
  sound/ambience/qwerty/constellations.ogg
Labels: Feature, Fix, sound

#5328 Ruins no longer spam the It's Loose notification
  code/modules/antagonists/clock_cult/clockwork_massive.dm
  code/modules/antagonists/wizard/equipment/artefact.dm
  code/modules/power/singularity/boh_tear.dm
  code/modules/power/singularity/field_generator.dm
  code/modules/power/singularity/narsie.dm
  code/modules/power/singularity/singularity.dm
Labels: Fix, Supercruise

#5334 Changes shuttle code ownership to supercruise ownership.
  .github/CODEOWNERS
Labels: GitHub

#5342 Syndicate Comms Agent List Fix
  code/modules/ruins/lavalandruin_code/syndicate_base.dm
Labels: Fix

#5344 Fix silicons being unable to interact with intercoms
  code/game/objects/items/devices/radio/intercom.dm
Labels: Fix

#5336 Setting Max Font size in SettingsPanel.js to 24 rather than 32
  tgui/packages/tgui-panel/settings/SettingsPanel.js
Labels: Config Update, TGUI-Changes

#5351 Fixes tgui ButtonInput crashing
  tgui/packages/tgui/components/Button.js
Labels: Fix, TGUI-Changes

#5356 hotfix for AI lab room.
  _maps/RuinGeneration/13x13_ai-lab.dmm
Labels: mapping

#5350 Corporate Sofas
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/beds_chairs/sofa.dm
  icons/obj/sofa.dmi
Labels: Feature, sprites

#5365 Re-adds custom emotes
  code/datums/brain_damage/creepy_trauma.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/simple_animal/eldritch_demons.dm
Labels: Fix

#5349 Adds more logging
  code/game/gamemodes/dynamic/dynamic.dm
  code/modules/client/client_defines.dm
  code/modules/client/verbs/who.dm
  code/modules/keybindings/bindings_client.dm
Labels: Feature

#5347 Admins can now force people to stub their toes.
  code/__DEFINES/admin.dm
  code/__DEFINES/traits.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Administration

#5337 Ports Aquariums
  beestation.dme
  code/__DEFINES/aquarium.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/traits.dm
  code/datums/components/aquarium.dm
  code/datums/components/crafting/recipes.dm
  code/datums/components/storage/concrete/fish_case.dm
  code/datums/components/storage/storage.dm
  code/datums/elements/deferred_aquarium_content.dm
  code/datums/mood_events/generic_negative_events.dm
  code/datums/mood_events/generic_positive_events.dm
  code/modules/aquarium/aquarium.dm
  code/modules/aquarium/aquarium_behaviour.dm
  code/modules/aquarium/fish.dm
  code/modules/aquarium/misc.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/cargo/packs.dm
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/food_and_drinks/recipes/processor_recipes.dm
  code/modules/library/lib_items.dm
  icons/obj/aquarium.dmi
  icons/obj/library.dmi
  icons/obj/storage.dmi
  tgui/packages/tgui/interfaces/Aquarium.js
  tgui/packages/tgui/interfaces/FishCatalog.js
Labels: Feature, sprites, TGUI-Changes

#5316 Replaces get_hearers with range
  code/game/objects/structures/musician.dm
Labels: Tweak, Code Improvement

#5132 Thrownthing refactor, you can now throw stuff at mobs lying on the floor
  code/controllers/subsystem/throwing.dm
  code/game/atoms_movable.dm
  code/modules/mob/living/living_defense.dm
Labels: Tweak, Refactor

#5297 Nerfs the cyborg *spin to be a knockdown instead of a paralyze
  code/datums/components/riding.dm
Labels: Balance/Rebalance

#5192 Flashbang changes (Nerf? Rebalance?)
  code/game/objects/items/grenades/flashbang.dm
Labels: Balance/Rebalance

#5247 Adds a few items to exploration shuttles.
  _maps/shuttles/exploration_corg.dmm
  _maps/shuttles/exploration_delta.dmm
  _maps/shuttles/exploration_shuttle.dmm
Labels: mapping, Feature

#5122 Prevents TK moving objects with people in or buckled to it
  code/_onclick/telekinesis.dm
Labels: Tweak

#5320 ERT Commanders get an Omni Door remote.
  code/modules/clothing/outfits/ert.dm
Labels: Tweak, Vote Passed

#5322 Finished BSA is indestructible.
  code/modules/station_goals/bsa.dm
Labels: Tweak

#5199 Strange seeds are now lavaland-only resource
  code/datums/mapgen/Cavegens/LavalandGenerator.dm
  code/modules/mining/lavaland/ash_flora.dm
  code/modules/research/designs/biogenerator_designs.dm
  icons/obj/lavaland/ash_flora.dmi
Labels: sprites

#5189 Rebalances Meth(Again)
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
Labels: Feature, Balance/Rebalance

#5366 Fixes docking with negative valued sections of lavaland.
  code/__DEFINES/orbit_defines.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_object.dm
Labels: Fix, Somewhat important, Supercruise

#5371 Fixes logging
  code/modules/client/verbs/who.dm
Labels: Administration

#5251 1984: Suppressed Bans
  code/__DEFINES/admin.dm
  code/__HELPERS/type2type.dm
  code/_globalvars/bitfields.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/admin/sql_message_system.dm
  config/admin_ranks.txt
  html/admin/banpanel.js
Labels: Config Update, Administration, server

#5137 Removes use of typecache in get area
  code/__HELPERS/unsorted.dm
  code/modules/mining/equipment/mineral_scanner.dm
Labels: Refactor

#5382 Fixes a meteor hard del source and something that causes map collision zones to be filled with nulls.
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/meteor.dm
Labels: Fix, Supercruise

#5309 Fix mecha recalibration not working
  code/game/mecha/mecha_topic.dm
Labels: Fix

#5145 Cleaning the station and growing plants - cyberpunk style
  code/game/objects/items/storage/bags.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/organs/augments_arms.dm
  icons/obj/hydroponics/equipment.dmi
Labels: Feature, sprites

#5385 You can build shuttles on asteroids
  code/modules/shuttle/shuttle_creation/shuttle_creator.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/asteroid_generator.dm
Labels: Tweak, Supercruise

#5379 Adds a define for the max loop iterations
  code/__DEFINES/misc.dm
Labels: Code Improvement

#5374 [s] Excludes clients in advanced proccall to prevent bypassing of permissions for coders in-game.
  code/modules/admin/callproc/callproc.dm
Labels: security, Administration

#5388 Fixes another case of meteors not moving properly.
  code/modules/events/meteor_wave.dm
Labels: Fix

#5129 Tesla improvements.
  code/__DEFINES/flags.dm
  code/modules/cargo/bounties/engineering.dm
  code/modules/mob/mob_stat.dm
  code/modules/power/lighting.dm
  code/modules/power/supermatter/supermatter.dm
  code/modules/power/tesla/energy_ball.dm
Labels: Needs Testmerge, Refactor, Administration, server

#5394 Mind Crawler by Merct, song for xeno announcement + music in credits
  beestation.dme
  code/_onclick/hud/credits.dm
  code/datums/soundtrack.dm
  code/game/sound.dm
  code/modules/antagonists/nukeop/equipment/nuclear_challenge.dm
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
  code/modules/mob/living/carbon/alien/humanoid/queen.dm
  sound/soundtrack/mind_crawler.ogg
Labels: Feature, sound

#5397 Botany flower additions
  code/datums/components/crafting/tailoring.dm
  code/modules/cargo/bounties/assistant.dm
  code/modules/cargo/bounties/botany.dm
  code/modules/clothing/head/misc.dm
  code/modules/hydroponics/grown/flowers.dm
  code/modules/hydroponics/grown/rainbow_bunch.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/hydroponics/growing_flowers.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
Labels: Feature, sprites, Fix, Code Improvement

#5144 Ports rebindable locking movement key and move intent toggle hotkey from /tg/ again again
  code/datums/keybinding/mob.dm
  code/modules/client/client_defines.dm
  code/modules/keybindings/bindings_atom.dm
  code/modules/keybindings/bindings_client.dm
Labels: Feature

#5173 Levelling up projectile spells makes the projectiles stronger.
  code/modules/projectiles/projectile/magic.dm
  code/modules/projectiles/projectile/magic/spellcard.dm
  code/modules/spells/spell_types/aimed.dm
  code/modules/spells/spell_types/projectile.dm
  code/modules/spells/spell_types/wizard.dm
Labels: Balance/Rebalance

#5262 Charlie station outpost gets more to build
  _maps/RuinGeneration/17x17_charliecrew.dmm
Labels: mapping, Tweak, Feature, Supercruise

#5174 Golems (Excluding bone golems) cannot be trans stung.
  code/modules/mob/living/carbon/human/species_types/golems.dm
Labels: Balance/Rebalance

#5398 Gives the traitor capsule a refinery and pickaxe.
  _maps/shuttles/capsule_traitor.dmm
Labels: mapping, Tweak, Supercruise

#5401 Blind player's screens stuck with blurry effect after being pied and cleaning it off
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/life.dm
Labels: Fix

#5169 Adds Typing Indicator
  beestation.dme
  code/__DEFINES/misc.dm
  code/controllers/subsystem/input.dm
  code/modules/mob/say.dm
  code/modules/mob/typing_indicator.dm
Labels: Feature, Plannedemic💉

#5354 Battle Royale requires +ADMIN instead of +FUN
  code/modules/admin/admin_verbs.dm
  code/modules/admin/battle_royale.dm
Labels: Administration

#5273 Adds the ability to catch thrown people.
  code/modules/mob/living/carbon/carbon.dm
Labels: Tweak, Vote Passed

#5396 fail2topic regex boogaloo
  code/controllers/subsystem/fail2topic.dm
Labels: Code Improvement

#5406 Fixes a bug that causes infinite z-levels to be created and eventual crashing.
  code/controllers/subsystem/zclear.dm
Labels: Fix, Supercruise

#5414 Moves Typing Indicator from Left to Right
  code/modules/mob/typing_indicator.dm
  icons/mob/talk.dmi
Labels: Tweak, sprites

#5416 World reboots will now always call SSdbcore.Disconnect()
  code/game/world.dm
Labels: server

#5415 [PORT] Another fix for laggy tgui tooltips -- Turn off popper event listener…
  tgui/packages/tgui/components/Tooltip.tsx
Labels: Code Improvement, TGUI-Changes

#5425 Warping runes now correctly pass in the slime color
  code/modules/research/xenobiology/crossbreeding/warping.dm
Labels: Fix

#5444 Fix rubbery ducky mines
  code/game/objects/effects/mines.dm
Labels: security, Fix

#5430 Clothes mate refill
  code/modules/cargo/packs.dm
Labels: Feature

#5440 Lets book titles be longer
  code/modules/library/lib_items.dm
Labels: Tweak

#5450 Fix a maintenance airlock on metastation
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: mapping, Fix

#5459 Bumps everything to 514.1568
  Dockerfile
  code/_compile_options.dm
  code/modules/client/client_procs.dm
  config/config.txt
  dependencies.sh
Labels: Tweak, Config Update

#5463 Update Database Schema for Book Title Length PR
  SQL/beestation_schema.sql
  SQL/database_changelog.txt
Labels: sql

#5441 Forcefield projector.
  code/modules/research/techweb/all_nodes.dm
Labels: Tweak, Vote Passed

#5417 Remove delay from say verb caused by typing indicators
  beestation.dme
  code/controllers/subsystem/input.dm
  code/modules/client/verbs/input_box.dm
  code/modules/keybindings/setup.dm
  code/modules/mob/typing_indicator.dm
  interface/skin.dmf
Labels: Needs Testmerge, test merged, Tweak, Golden ⭐, Plannedemic💉

#5469 Update tips.txt to remove out of date, rule-breaking, and wrong information.
  strings/tips.txt
Labels: Tweak
