Repository BeeStation/BeeStation-Hornet, pull requests merged in 2021-11, with the labels that each got.

#5670 Banning panel no longer screams at you if you're not a headmin.
  code/modules/admin/sql_ban_system.dm
Labels: Feature, Administration

#4843 tgui: r&d consoles
  code/modules/asset_cache/asset_list.dm
  code/modules/research/machinery/circuit_imprinter.dm
  code/modules/research/machinery/departmental_circuit_imprinter.dm
  code/modules/research/machinery/departmental_protolathe.dm
  code/modules/research/machinery/protolathe.dm
  code/modules/research/rdconsole.dm
  code/modules/research/techweb/__techweb_helpers.dm
  code/modules/research/techweb/_techweb.dm
  tgui/packages/tgui/interfaces/Techweb.js
  tgui/packages/tgui/styles/interfaces/Techweb.scss
  tgui/packages/tgui/styles/main.scss
Labels: Feature, Triaged, TGUI-Changes

#5674 Fix R&D Console
  tgui/packages/tgui/interfaces/Techweb.js
Labels: Fix, TGUI-Changes

#5675 Fix production machines being unusable
  code/modules/research/machinery/circuit_imprinter.dm
  code/modules/research/machinery/departmental_circuit_imprinter.dm
  code/modules/research/machinery/departmental_protolathe.dm
  code/modules/research/machinery/protolathe.dm
Labels: Fix

#5661 Fixes carp hardsuit sprite
  icons/mob/suit.dmi
Labels: sprites, Fix

#5683 Gives RD actual control over exploration
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/modules/jobs/access.dm
Labels: Tweak, Feature

#5686 Fix R&D Console's destructive analyzer interface
  tgui/packages/tgui/interfaces/Techweb.js
Labels: Fix, TGUI-Changes

#5687 Fixes traitor shuttle not beeing deployable on generated asteroid zlevel
  code/modules/shuttle/bluespace_shuttle_pod/shuttle_capsule.dm
Labels: Fix

#5700 Remove dependency on R&D consoles from protolathes and circuit imprinters
  code/modules/research/machinery/circuit_imprinter.dm
  code/modules/research/machinery/protolathe.dm
Labels: Tweak, Feature

#5695 [s] Fixes multiple security vulnerabilities
  code/__DEFINES/text.dm
  code/__HELPERS/_string_lists.dm
  code/__HELPERS/icons.dm
  code/__HELPERS/text.dm
  code/__HELPERS/unsorted.dm
  code/_globalvars/regexes.dm
  code/controllers/configuration/configuration.dm
  code/controllers/subsystem/mapping.dm
  code/datums/map_config.dm
  code/game/machinery/camera/camera.dm
  code/game/objects/structures/artstuff.dm
  code/modules/asset_cache/asset_list.dm
  code/modules/awaymissions/zlevel.dm
  code/modules/library/lib_machines.dm
  code/modules/tgs/v3210/api.dm
  code/modules/tgui/tgui_window.dm
Labels: test merged, server

#5701 Adds 50 titanium glass sheets to the DIY shuttle
  _maps/shuttles/emergency_construction.dmm
Labels: mapping, Feature

#5654 Adds Dark FairyGrass Floor tile
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/turfs/open/floor/fancy_floor.dm
  code/modules/hydroponics/grown/grass_carpet.dm
Labels: Feature

#5682 Fixes oozelings going below 0% blood volume from fire extinguishers.
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Fix

#5662 [PORT] Lesser Summon Bees
  beestation.dme
  code/modules/antagonists/wizard/equipment/spellbook.dm
  code/modules/spells/spell_types/wizard.dm
  icons/mob/actions/actions_spells.dmi
Labels: Feature, sprites

#5576 Remove duplicate cables from maps
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Mining/Lavaland.dmm
Labels: mapping, Fix

#5688 Fixes alien eggs being deleted before hugger is spawned
  code/game/objects/structures/aliens.dm
Labels: Fix

#5512 Fix changeling's organic space suit overdosing the user on salbutamol
  code/modules/antagonists/changeling/powers/mutations.dm
Labels: Fix

#5636 Fixes a TGUI runtime with null clients
  code/modules/tgui/tgui.dm
Labels: Fix

#5714 Fixes nextmap loading
  code/__DEFINES/text.dm
  code/__HELPERS/_string_lists.dm
  code/datums/map_config.dm
Labels: Fix

#5638 Firelock Refactor
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doors/passworddoor.dm
  code/game/machinery/doors/poddoor.dm
  code/game/machinery/doors/windowdoor.dm
  icons/obj/doors/doorfire.dmi
  icons/obj/doors/doorfireglass.dmi
  icons/obj/doors/doorhazard.dmi
  icons/obj/doors/edge_Doorfire.dmi
  sound/machines/firedoor_close.ogg
  sound/machines/firedoor_open.ogg
Labels: test merged, Feature, sprites, Balance/Rebalance, Refactor, sound

#5720 Firelock description fix
  code/game/machinery/doors/firedoor.dm
Labels: Fix

#5717 Adds a small playtime/age requirement to explorers
  code/modules/jobs/job_types/exploration_team.dm
Labels: Feature, server

#5722 Petty badge update
  config/badges.json
  icons/badges.dmi
Labels: Feature, sprites, Config Update

#5724 Fixes maps again
  beestation.dme
  code/__DEFINES/config_defines.dm
  code/__DEFINES/text.dm
  code/controllers/configuration/configuration.dm
  code/controllers/subsystem/mapping.dm
  code/datums/map_config.dm
Labels: Fix

#5690 Disables Fly & Squid characters
  config/game_options.txt
Labels: Config Update

#5719 Janitorial Rebalance
  code/game/objects/items/holosign_creator.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/research/designs/autolathe_designs.dm
  code/modules/vending/wardrobes.dm
Labels: Balance/Rebalance, Plannedemic💉

#5733 Fixes lowmemorymode not forcing map
  code/_compile_options.dm
  code/controllers/subsystem/mapping.dm
Labels: Fix

#5723 Fixes another runtime with TGUI and null clients
  code/modules/tgui/tgui.dm
Labels: Code Improvement

#5635 Fixes people being stuck in limbo if they fall out a transit with no jetpack
  code/controllers/subsystem/mapping.dm
Labels: Fix

#5693 Moves mindcrawler play time to Hostile Environment trigger
  code/controllers/subsystem/shuttle.dm
  code/modules/mob/living/carbon/alien/humanoid/queen.dm
Labels: Tweak

#5738 Fix for silicon windoor access
  code/game/machinery/doors/windowdoor.dm
Labels: Fix

#5734 Removes Squidpeople from the codebase
  beestation.dme
  code/__DEFINES/mobs.dm
  code/__HELPERS/names.dm
  code/_globalvars/lists/names.dm
  code/datums/components/caltrop.dm
  code/game/objects/effects/decals/cleanable/food.dm
  code/modules/language/language_holder.dm
  code/modules/language/rlyehian.dm
  code/modules/mob/living/carbon/human/species_types/squidpeople.dm
  code/modules/mob/living/living.dm
  code/modules/pool/components/swimming_squid.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/surgery/organs/tongue.dm
  config/game_options.txt
  icons/mob/human_parts.dmi
  icons/mob/human_parts_greyscale.dmi
  strings/names/squid_female.txt
  strings/names/squid_male.txt
Labels: sprites, Config Update, Removal

#5567 virology gameplay tweaks and rebalances (again)
  code/datums/diseases/_disease.dm
  code/datums/diseases/advance/advance.dm
  code/datums/diseases/advance/presets.dm
  code/datums/diseases/advance/symptoms/heal.dm
  code/datums/diseases/advance/symptoms/viral.dm
  code/game/objects/effects/decals/cleanable/humans.dm
  code/game/objects/effects/decals/cleanable/misc.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/structures/lavaland/necropolis_tendril.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/brigphys.dm
  code/modules/jobs/job_types/cargo_technician.dm
  code/modules/jobs/job_types/chemist.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/curator.dm
  code/modules/jobs/job_types/emt.dm
  code/modules/jobs/job_types/exploration_team.dm
  code/modules/jobs/job_types/geneticist.dm
  code/modules/jobs/job_types/gimmick.dm
  code/modules/jobs/job_types/janitor.dm
  code/modules/jobs/job_types/medical_doctor.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/job_types/scientist.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/virologist.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/reagents/reagent_containers/syringes.dm
Labels: Tweak, Feature, Fix

#5681 Removes flash protection from emergency pod helmets.
  code/modules/shuttle/emergency.dm
Labels: Tweak

#5716 Fixes silicons teleporting intellicards and ID cards using modular consoles
  code/modules/modular_computers/computers/item/computer.dm
  code/modules/modular_computers/hardware/ai_slot.dm
  code/modules/modular_computers/hardware/battery_module.dm
  code/modules/modular_computers/hardware/card_slot.dm
Labels: Code Improvement

#5730 Code for roundstart_no_hard_check config option
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/species.dm
  config/game_options.txt
Labels: Fix, Config Update

#5752 Fixes mindless mobs updating objectives on cryo
  code/game/machinery/cryopod.dm
Labels: Fix

#5754 protects the filename regex global
  code/_globalvars/regexes.dm
Labels: Code Improvement

#5760 Medibot Fix
  code/modules/mob/living/simple_animal/bot/medbot.dm
Labels: Fix

#5741 Discovery Scanner and DNA probe now check if the mob is holographic
  code/modules/exploration_crew/discovery_research/discoverable_component.dm
  code/modules/station_goals/dna_vault.dm
Labels: Fix

#5697 Xenomorph queen only triggers hostile environment if it's on the station Z level
  code/modules/mob/living/carbon/alien/humanoid/queen.dm
Labels: Fix

#5748 Fixes Vortex Talisman
  code/modules/mining/equipment/kinetic_crusher.dm
Labels: Fix

#4841 TGUI protolathe, techfab, circuit imprinter
  code/__DEFINES/dcs/signals.dm
  code/datums/components/material_container.dm
  code/datums/components/remote_materials.dm
  code/modules/research/machinery/_production.dm
  tgui/packages/tgui/interfaces/TechFab.js
  tgui/packages/tgui/styles/interfaces/TechFab.scss
  tgui/packages/tgui/styles/main.scss
Labels: Feature, TGUI-Changes

#5756 Logs grenade priming in combat logs
  code/game/objects/items/grenades/grenade.dm
Labels: Feature

#5751 Fix research tier calculation
  code/modules/research/techweb/_techweb.dm
Labels: Fix

#5762 Gun Wielding Refactor
  code/datums/components/twohanded.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
Labels: Refactor

#5545 Expands the Ethereal colour list
  code/_globalvars/lists/flavor_misc.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
Labels: Stale, Feature

#5758 Fix armory spelling
  _maps/RuinGeneration/13x13_corgarmory.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/mapping.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/ruin_part_types.dm
Labels: mapping, Fix

#5713 Fixes chatmessage runtime
  code/datums/chatmessage.dm
Labels: Fix

#5655 Port from Citadel Station for the Ore Redemption machine and vendor icons.
  icons/obj/machines/mining_machines.dmi
Labels: Feature, sprites

#5591 death nettle nerf
  code/modules/hydroponics/grown/nettle.dm
Labels: Balance/Rebalance

#5769 Bans Eris sprites
  .github/CONTRIBUTING.md
Labels: Feature, Removal

#5331 Delta Exploration shuttle tweaks
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/shuttles/exploration_delta.dmm
Labels: mapping, Tweak, Fix, Supercruise

#5727 Adds crossed
  code/game/objects/items/plushes.dm
  icons/obj/plushes.dmi
Labels: Feature, sprites

#5090 Port reproductive extract refractor and fix from tg
  beestation.dme
  code/datums/components/storage/concrete/extract_inventory.dm
  code/modules/research/xenobiology/crossbreeding/reproductive.dm
Labels: Tweak, Fix, Refactor

#5770 hotfixes for viro
  code/datums/diseases/advance/advance.dm
  code/modules/antagonists/disease/disease_disease.dm
Labels: Fix

#5768 Fixes Xeno Eggs not updating sprite after bursting
  code/game/objects/structures/aliens.dm
Labels: Fix

#5773 Fix clicking things with biobag
  code/game/objects/items/storage/bags.dm
Labels: Fix

#5761 Ports NSV map verb
  _maps/boxstation.json
  _maps/corgstation.json
  _maps/deltastation.json
  _maps/kilostation.json
  _maps/metastation.json
  _maps/multiz_debug.json
  _maps/pubbystation.json
  _maps/runtimestation.json
  code/datums/map_config.dm
  interface/interface.dm
Labels: mapping, Refactor

#5413 Morph ambush attack
  code/modules/antagonists/morph/morph.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
Labels: Feature, Vote Passed

#5779 Fixes and minor tweaks to hangover
  code/datums/station_traits/negative_traits.dm
  code/game/objects/effects/spawners/structure.dm
Labels: Tweak, Fix, Removal

#5524 Fixes BoxStation Disposals
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: mapping, Stale, Tweak, Fix

#5274 The Cargo area on the latejoin menu is no longer incorrectly labeled Command
  code/modules/jobs/jobs.dm
Labels: Fix

#5788 Removes the funny word from owospeak
  strings/owo_talk.json
Labels: Removal

#4851 Modernises uplinks
  beestation.dme
  code/__DEFINES/antagonists.dm
  code/__DEFINES/uplink.dm
  code/_globalvars/lists/flavor_misc.dm
  code/datums/components/uplink.dm
  code/datums/mind.dm
  code/game/objects/items/implants/implanter.dm
  code/game/objects/items/implants/implantuplink.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/uplink/uplink_devices.dm
  code/modules/uplink/uplink_items.dm
Labels: Needs Testmerge, Feature, Fix

#5791 Fixes sleepy pen + wrong blood type exploit
  code/modules/paperwork/pen.dm
Labels: Fix

#5481 TGUI Section fixes from tg
  tgui/docs/component-reference.md
  tgui/packages/tgui-panel/styles/themes/light.scss
  tgui/packages/tgui/components/Section.tsx
  tgui/packages/tgui/interfaces/Techweb.js
  tgui/packages/tgui/interfaces/TicketBrowser.js
  tgui/packages/tgui/interfaces/TicketMessenger.js
  tgui/packages/tgui/styles/components/Section.scss
  tgui/packages/tgui/styles/themes/paper.scss
Labels: Needs Testmerge, Fix, Triaged, TGUI-Changes

#5735 Further tgui R&D console fixes
  code/modules/research/rdconsole.dm
  code/modules/research/techweb/_techweb.dm
  tgui/packages/tgui/interfaces/Techweb.js
  tgui/packages/tgui/styles/interfaces/Techweb.scss
Labels: Feature, Fix, TGUI-Changes

#5792 IPCs bleed 10x slower & gives them a cybernetic heart
  code/modules/mob/living/carbon/human/species_types/IPC.dm
  code/modules/surgery/organs/heart.dm
Labels: Fix, Balance/Rebalance

#5799 Fixes IPC Oopsie. Again.
  code/modules/surgery/organs/heart.dm
Labels: Fix

#5711 Changes Gaseous Pores to Confuse instead of Sleep
  code/modules/antagonists/changeling/powers/gaseous_pores.dm
Labels: Balance/Rebalance

#5808 Chasm CanPass Fix
  code/game/turfs/open/chasm.dm
Labels: Fix

#5811 Fix techfabs having a duplicate "Computer Parts" category
  code/modules/research/machinery/techfab.dm
Labels: Fix

#5805 Fixes loading admin nicknames
  beestation.dme
  code/__DEFINES/config_defines.dm
  code/__DEFINES/configuration.dm
  code/__DEFINES/misc.dm
  code/__HELPERS/_string_lists.dm
  code/controllers/configuration/configuration.dm
  code/controllers/subsystem/traumas.dm
  code/datums/brain_damage/split_personality.dm
  code/datums/diseases/transformation.dm
  code/datums/mutations/speech.dm
  code/modules/admin/verbs/deadsay.dm
  code/modules/antagonists/revenant/revenant.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/events/holiday/vday.dm
Labels: Fix, Refactor, Administration

#5816 Adds revolution and traitorchan title cards
  code/game/gamemodes/changeling/traitor_chan.dm
  code/game/gamemodes/revolution/revolution.dm
Labels: Feature

#5821 Fixes floating light switch on MetaStation
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: mapping

#5775 Fixes legacy topic runtime, adds fallback for spacestation13.com
  code/game/world.dm
Labels: Feature, Fix, server

#5818 Fixes Runtime in CI
  _maps/RandomRooms/5x4/sk_rdm032_deltaEVA.dmm
Labels: mapping, Fix

#5793 Shows legcuffs in examine and lets you see what type of cuffs and bola a mob is restrained with
  code/modules/mob/living/carbon/examine.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: Feature

#5772 Updates an outdated Safety Moth poster's description
  code/game/objects/effects/contraband.dm
Labels: Fix

#5780 Fixes to tgchat sorting, you can now sort Mentor PMs
  tgui/packages/tgui-panel/chat/constants.js
Labels: Feature, Fix, TGUI-Changes

#5568 deep frying nonfoods is no longer a qdel v2
  code/modules/food_and_drinks/food/snacks_bread.dm
Labels: Removal

#5849 Fully removes mindread from the game
  _maps/RuinGeneration/13x13_shotelroom.dmm
  code/__DEFINES/DNA.dm
  code/datums/mutations/_combined.dm
  code/datums/mutations/antenna.dm
  code/game/objects/items/dna_injector.dm
Labels: mapping, Removal

#5736 Bunny ears now adapt to the hair color of the wearer
  beestation.dme
  code/datums/components/haircolor_clothes.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/misc_special.dm
Labels: Feature

#5726 [READY] Pubby Pipe Net Multi Layer Project
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: mapping, test merged

#5851 Prevents ugly chat messages from using "~" at the end of messages
  code/modules/mob/living/say.dm
Labels: Tweak

#5854 Heretics no longer gib their sacrifice targets, instead spilling out their internal organs.
  code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
Labels: Balance/Rebalance

#5574 a few more viro symptom tweaks
  code/datums/diseases/advance/advance.dm
  code/datums/diseases/advance/symptoms/beard.dm
  code/datums/diseases/advance/symptoms/blobspores.dm
  code/datums/diseases/advance/symptoms/braindamage.dm
  code/datums/diseases/advance/symptoms/clockwork.dm
  code/datums/diseases/advance/symptoms/cockroach.dm
  code/datums/diseases/advance/symptoms/confusion.dm
  code/datums/diseases/advance/symptoms/deafness.dm
  code/datums/diseases/advance/symptoms/fire.dm
  code/datums/diseases/advance/symptoms/flesh_eating.dm
  code/datums/diseases/advance/symptoms/genetics.dm
  code/datums/diseases/advance/symptoms/hallucigen.dm
  code/datums/diseases/advance/symptoms/heal.dm
  code/datums/diseases/advance/symptoms/lubefeet.dm
  code/datums/diseases/advance/symptoms/nanites.dm
  code/datums/diseases/advance/symptoms/narcolepsy.dm
  code/datums/diseases/advance/symptoms/oxygen.dm
  code/datums/diseases/advance/symptoms/radiation.dm
  code/datums/diseases/advance/symptoms/sensory.dm
  code/datums/diseases/advance/symptoms/shedding.dm
  code/datums/diseases/advance/symptoms/skin.dm
  code/datums/diseases/advance/symptoms/species.dm
  code/datums/diseases/advance/symptoms/spiked.dm
  code/datums/diseases/advance/symptoms/viral.dm
  code/datums/diseases/advance/symptoms/vision.dm
  code/datums/diseases/advance/symptoms/voice_change.dm
  code/datums/diseases/advance/symptoms/vomit.dm
  code/datums/diseases/advance/symptoms/weight.dm
  code/datums/diseases/advance/symptoms/wizarditis.dm
  code/datums/diseases/wizarditis.dm
Labels: Tweak, Fix, Needs Wiki Changes

#5850 Light items no longer break when anything not living moves onto it
  code/modules/power/lighting.dm
Labels: Fix

#5852 standardize all the indents in map json files
  _maps/boxstation.json
  _maps/corgstation.json
  _maps/deltastation.json
  _maps/kilostation.json
  _maps/metastation.json
  _maps/multiz_debug.json
  _maps/pubbystation.json
  _maps/runtimestation.json
Labels: mapping

#5856 Changes the experimental dissection point type from regular research to discovery
  code/modules/surgery/advanced/bioware/experimental_dissection.dm
Labels: Tweak

#5865 Allows the patreon list to be used as a whitelist
  code/controllers/configuration/entries/general.dm
  code/game/world.dm
  config/config.txt
Labels: Config Update

#5676 Adds engineering imprinter
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/research/machinery/departmental_circuit_imprinter.dm
Labels: mapping, Feature

#5866 Fixes setting up whitelist
  code/game/world.dm
  code/modules/admin/whitelist.dm
Labels: Fix, Administration

#5828 Flashes get EMPed properly
  code/modules/assembly/flash.dm
Labels: Fix

#5836 nerfs directional blocking
  code/game/objects/items.dm
  code/game/objects/items/chainsaw.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/extinguisher.dm
  code/game/objects/items/fireaxe.dm
  code/game/objects/items/flamethrower.dm
  code/game/objects/items/his_grace.dm
  code/game/objects/items/holy_weapons.dm
  code/game/objects/items/kitchen.dm
  code/game/objects/items/melee/misc.dm
  code/game/objects/items/mop.dm
  code/game/objects/items/pneumaticCannon.dm
  code/game/objects/items/shields.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/storage/book.dm
  code/game/objects/items/storage/briefcase.dm
  code/game/objects/items/storage/secure.dm
  code/game/objects/items/storage/toolbox.dm
  code/game/objects/items/tools/crowbar.dm
  code/game/objects/items/tools/wrench.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weaponry.dm
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/antagonists/wizard/equipment/artefact.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/instruments/items.dm
  code/modules/mining/equipment/kinetic_crusher.dm
  code/modules/mining/equipment/mining_tools.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/pool/pool_items.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/launchers.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/guns/ballistic/toy.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/pulse.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/magic/staff.dm
  code/modules/projectiles/guns/misc/beam_rifle.dm
  code/modules/projectiles/guns/misc/blastcannon.dm
  code/modules/projectiles/guns/misc/grenade_launcher.dm
  code/modules/vehicles/lavaboat.dm
Labels: Feature, Balance/Rebalance, Removal

#5827 More pod docks
  _maps/map_files/generic/CentCom.dmm
Labels: mapping

#5871 Notes and messages will not automatically expire
  code/controllers/configuration/entries/general.dm
  code/modules/admin/sql_message_system.dm
  config/config.txt
Labels: enhancement, Feature, Config Update, Administration, config

#5429 Syndicate uniform supplies
  code/modules/cargo/packs.dm
Labels: Feature, Vote Passed

#5872 Lets Atmos Techs use Firedoors
  code/game/machinery/doors/firedoor.dm
Labels: Fix

#5873 Ninja allegiance logging
  code/modules/ninja/ninja_event.dm
Labels: Feature
