Repository BeeStation/BeeStation-Hornet, pull requests merged in 2021-05, with the labels that each got.

#3912 Suit sensors can now be adjusted through the strip menu
  code/modules/clothing/clothing.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Stale, Tweak

#4205 Fixes corg's toxins
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: mapping

#4206 Adds role_heretic to banning panel
  code/modules/admin/sql_ban_system.dm
Labels: Administration

#4203 Optimises client MouseMove
  code/__HELPERS/mouse_control.dm
  code/_onclick/drag_drop.dm
  code/datums/components/lockon_aiming.dm
  code/game/objects/structures/manned_turret.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/projectiles/guns/misc/beam_rifle.dm
Labels: Needs Testmerge

#4199 Fixes corgstation science door, requires CE access to eject the SM.
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: mapping

#4214 Removes hatecrimes
  code/__DEFINES/inventory.dm
  code/__HELPERS/game.dm
  code/datums/diseases/wizarditis.dm
  code/datums/mutations/speech.dm
  code/game/machinery/doors/checkForMultipleDoors.dm
  code/game/objects/structures/signs/signs_plaques.dm
  code/modules/admin/secrets.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/jobs/job_types/chaplain.dm
  code/modules/lighting/lighting_corner.dm
  code/modules/mob/living/carbon/alien/humanoid/update_icons.dm
Labels: Administration

#4047 Changelings cannot last resolt while being absorbed and can hear changeling comms.
  code/datums/saymode.dm
  code/modules/antagonists/changeling/powers/headcrab.dm
Labels: Tweak

#4240 Fixes some harddels
  code/game/objects/items/robot/robot_items.dm
  code/game/objects/items/twohanded.dm
  code/modules/reagents/chemistry/machinery/chem_synthesizer.dm
  code/modules/reagents/chemistry/machinery/reagentgrinder.dm
Labels: Fix

#4222 Adds vents/scrubbers and fixes xenobio freezer fix for Corg
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: Feature, Fix, mapping

#4263 Removes wishgranter from lavaland ruin pool
  code/datums/ruins/lavaland.dm
Labels: Removal

#4265 Blacklists the whishgranter ruin on Sage
  config/Sage/lavaruinblacklist.txt
Labels: Config Update

#4087 mirrors reflect lasers
  code/game/objects/structures/mirror.dm
Labels: Feature

#4185 Adds detdrobe, med records and cap's spare to corgstation.
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: mapping

#4213 Ratvarian Spear belt sprite
  icons/mob/belt.dmi
Labels: sprites

#4245 Updated the Witch clothing.
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: sprites

#4210 Modular fabricator interface for exosuit fabs.
  _maps/RandomRooms/10x5/sk_rdm031_deltarobotics.dmm
  _maps/RandomRooms/5x4/sk_rdm047_metarobotics.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_golem_ship.dmm
  _maps/RandomRuins/SpaceRuins/deepstorage.dmm
  _maps/RandomRuins/SpaceRuins/oldstation.dmm
  _maps/RandomZLevels/snowdin.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/debug/runtimestation.dmm
  _maps/map_files/generic/CentCom.dmm
  beestation.dme
  code/datums/wires/autolathe.dm
  code/game/machinery/fabricators/autolathe.dm
  code/game/machinery/fabricators/exosuit_fab.dm
  code/game/machinery/fabricators/modular_fabricator.dm
  code/game/mecha/mech_fabricator.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/research/rdconsole.dm
  code/modules/shuttle/supply.dm
  tgui/packages/tgui/interfaces/ExosuitFabricator.js
  tgui/packages/tgui/interfaces/ModularFabricator.js
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: Needs Testmerge, TGUI-Changes, mapping, test merged

#3883 adds supports for named argument to components/elements + VV for adding/removing components
  beestation.dme
  code/__DEFINES/dcs/flags.dm
  code/__DEFINES/dcs/helpers.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/vv.dm
  code/controllers/subsystem/dcs.dm
  code/datums/components/_component.dm
  code/datums/components/orbiter.dm
  code/datums/components/radioactive.dm
  code/datums/components/remote_materials.dm
  code/datums/components/stationloving.dm
  code/datums/components/thermite.dm
  code/datums/components/wet_floor.dm
  code/datums/datumvars.dm
  code/datums/elements/_element.dm
  code/datums/materials/_material.dm
  code/datums/materials/basemats.dm
  code/game/objects/items/grenades/antigravity.dm
  code/game/objects/structures/statues.dm
  code/game/objects/structures/windoor_assembly.dm
  code/modules/admin/view_variables/topic_basic.dm
  code/modules/assembly/holder.dm
  code/modules/assembly/infrared.dm
  code/modules/integrated_electronics/subtypes/input.dm
  code/modules/integrated_electronics/subtypes/manipulation.dm
  code/modules/mapping/mapping_helpers.dm
  code/modules/mining/machine_silo.dm
Labels: Administration, Code Improvement, Feature, Needs Testmerge, Triaged

#4285 Converts energy gatling gun to a energy weapon
  beestation.dme
  code/modules/mining/equipment/survival_pod.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/autofire.dm
  code/modules/projectiles/boxes_magazines/internal/misc.dm
  code/modules/projectiles/guns/energy/laser_gatling.dm
Labels: Refactor, server

#4280 Small flash refactor
  code/modules/assembly/flash.dm
Labels: Code Improvement, Refactor

#4276 Fixes start landmark harddels
  code/game/objects/effects/landmarks.dm
Labels: Fix, Removal

#4275 Fix proximity checker harddel
  code/game/objects/effects/proximity.dm
Labels: Fix, Removal

#4295 Nerfs & logs blood tomatoes
  code/game/objects/effects/spawners/gibspawner.dm
  code/modules/hydroponics/grown/tomato.dm
Labels: Tweak

#4189 removes security cyborgs via config, refactors security borg transformation module into a research node
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/research/techweb/all_nodes.dm
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Config Update

#4281 Add's a reddit moment
  code/modules/clothing/outfits/standard.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/vending/autodrobe.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, sprites

#4284 Plasmaman now have there own catagory in equip outfit menu
  code/modules/admin/verbs/debug.dm
  code/modules/clothing/outfits/standard.dm
Labels: Administration, Tweak

#4297 Fix load custom outfit
  code/modules/admin/outfits.dm
Labels: Administration, Fix

#4292 Clown tears uses sheets
  code/modules/food_and_drinks/recipes/tablecraft/recipes_soup.dm
Labels: Tweak

#4303 Fixes rare case of special equipment not spawning
  code/game/gamemodes/objective.dm
Labels: Fix

#4184 Adds arabian cat + exotic cats crate
  code/modules/cargo/packs.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  icons/mob/pets.dmi
  icons/mob/pets_held_lh.dmi
  icons/mob/pets_held_rh.dmi
Labels: sprites

#4313 replaces KPa with kPa
  code/modules/atmospherics/gasmixtures/gas_mixture.dm
  code/modules/atmospherics/machinery/components/binary_devices/circulator.dm
Labels: Fix, Grammar and Formatting

#4318 Station traits are less common, can't be rolled twice and tweaks some weights
  code/controllers/subsystem/processing/station.dm
  code/datums/station_traits/neutral_traits.dm
Labels: Tweak

#4326 Fixes riot knight armor runtime
  code/modules/clothing/suits/armor.dm
Labels: Fix

#4311 IsBanned logging extension
  code/modules/admin/IsBanned.dm
  code/modules/tgui_panel/telemetry.dm
Labels: Administration, server

#4248 Removes some in world loops
  code/__HELPERS/unsorted.dm
  code/controllers/subsystem/mapping.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/game/objects/items/devices/PDA/virus_cart.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/diagnostics.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/antagonists/clock_cult/clockwork_massive.dm
  code/modules/awaymissions/zlevel.dm
  code/modules/client/verbs/looc.dm
  code/modules/events/prison_break.dm
  code/modules/events/spacevine.dm
  code/modules/events/wizard/rpgloot.dm
  code/modules/events/wormholes.dm
  code/modules/holodeck/computer.dm
  code/modules/lighting/lighting_setup.dm
  code/modules/mining/equipment/mineral_scanner.dm
  code/modules/security_levels/keycard_authentication.dm
Labels: Administration, Refactor, Removal, Tweak

#4328 Fixes some corg pipes
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: Fix, mapping

#4320 Fixes spawning in lobby screen
  code/controllers/subsystem/job.dm
  code/game/gamemodes/game_mode.dm
  code/modules/mob/mob_helpers.dm
Labels: Fix

#4324 Fixes request console runtime
  code/game/machinery/requests_console.dm
Labels: Fix

#4334 Reverts making space sharks sentient
  code/modules/events/carp_migration.dm
Labels: Removal

#4335 Swarmer beacon and private secoff now get deleted on death, minor true/false audit
  code/game/objects/effects/mainttraps.dm
  code/modules/antagonists/changeling/powers/regenerate.dm
  code/modules/antagonists/slaughter/slaughter.dm
  code/modules/antagonists/swarmer/swarmer.dm
  code/modules/awaymissions/mission_code/TheFactory.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/friendly/cockroach.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  code/modules/mob/living/simple_animal/hostile/bees.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/cat_butcher.dm
  code/modules/mob/living/simple_animal/hostile/eyeballs.dm
  code/modules/mob/living/simple_animal/hostile/heart.dm
  code/modules/mob/living/simple_animal/hostile/hivebot.dm
  code/modules/mob/living/simple_animal/hostile/illusion.dm
  code/modules/mob/living/simple_animal/hostile/macrophage.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/swarmer.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/legionnaire.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
  code/modules/mob/living/simple_animal/hostile/pirate.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/ghost.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/spaceman.dm
  code/modules/mob/living/simple_animal/hostile/russian.dm
  code/modules/mob/living/simple_animal/hostile/skeleton.dm
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  code/modules/mob/living/simple_animal/hostile/tree.dm
  code/modules/mob/living/simple_animal/hostile/venus_human_trap.dm
  code/modules/mob/living/simple_animal/hostile/wizard.dm
  code/modules/mob/living/simple_animal/hostile/zombie.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Code Improvement, Fix, Removal

#4327 Fixes darkpurple stabilized slime runtime
  code/modules/research/xenobiology/crossbreeding/_status_effects.dm
Labels: Fix

#4301 Directional stairs port
  code/game/objects/structures/stairs.dm
  icons/obj/stairs.dmi
Labels: Feature, sprites

#4230 Limits logging after round
  code/__HELPERS/_logging.dm
  code/modules/admin/admin_investigate.dm
  code/modules/mob/mob_helpers.dm
Labels: Administration

#4176 Gives ashwalkers bone spears instead of regular ones and other stuff
  _maps/RandomRuins/LavaRuins/lavaland_surface_ash_walker1.dmm
Labels: mapping

#4337 Adrenaline Nanites gets moved to weaponized tech (now requires illegal tech)
  code/modules/research/designs/nanite_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Balance/Rebalance

#4346 Prevents Crossed from crashing the server
  code/modules/admin/verbs/possess.dm
Labels: Administration, Fix

#4316 Pethats.
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/crab.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/friendly/fox.dm
  code/modules/mob/living/simple_animal/friendly/hamster.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/friendly/snake.dm
  code/modules/mob/living/simple_animal/kalo.dm
  code/modules/mob/living/simple_animal/parrot.dm
  icons/mob/pets_held.dmi
  icons/mob/pets_held_large.dmi
  icons/mob/pets_held_lh.dmi
  icons/mob/pets_held_rh.dmi
Labels: Feature, sprites

#4267 Adds cosmetic versions of sunhuds (again)
  code/datums/components/crafting/tailoring.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/clothing/glasses/hud.dm
Labels: Feature

#3973 Adds Detective's SpyGlasses and related requirements
  beestation.dme
  code/datums/action.dm
  code/datums/components/orbiter.dm
  code/datums/movement_detector.dm
  code/game/objects/items/devices/spyglasses.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Code Improvement, Feature, Fix

#4286 [Port] Adds fingerless insulated gloves as a Assistant heirloom item. (Bee #4255)
  code/datums/traits/negative.dm
  code/modules/clothing/gloves/_gloves.dm
  code/modules/clothing/gloves/color.dm
  icons/mob/hands.dmi
  icons/obj/clothing/gloves.dmi
Labels: Feature, sprites

#4317 Fixes warrant and spawner menu runtimes
  code/datums/spawners_menu.dm
  code/game/machinery/computer/warrant.dm
Labels: Fix

#3703 Tweaks Resource Management in Space, and adds more ruins
  _maps/RandomRuins/SpaceRuins/asteroid10.dmm
  _maps/RandomRuins/SpaceRuins/asteroid6.dmm
  _maps/RandomRuins/SpaceRuins/asteroid7.dmm
  _maps/RandomRuins/SpaceRuins/asteroid8.dmm
  _maps/RandomRuins/SpaceRuins/asteroid9.dmm
  _maps/RandomRuins/SpaceRuins/refference.dmm
  _maps/RandomRuins/SpaceRuins/sos1.dmm
  _maps/RandomRuins/SpaceRuins/sos2.dmm
  _maps/RandomRuins/SpaceRuins/sos3.dmm
  _maps/RandomRuins/SpaceRuins/sos4.dmm
  _maps/RandomRuins/SpaceRuins/sos5.dmm
  _maps/RandomRuins/SpaceRuins/sos6.dmm
  _maps/RandomRuins/SpaceRuins/sos7.dmm
  _maps/RandomRuins/SpaceRuins/sos8.dmm
  _maps/RandomRuins/SpaceRuins/spacearcade.dmm
  _maps/RandomRuins/SpaceRuins/spacedock13.dmm
  _maps/RandomRuins/SpaceRuins/spacehive.dmm
  _maps/RandomRuins/SpaceRuins/swarmerstation13.dmm
  beestation.dme
  code/controllers/configuration/entries/game_options.dm
  code/datums/ruins/space.dm
  code/game/turfs/open/floor/fancy_floor.dm
  code/modules/mob/living/simple_animal/hostile/bees.dm
  code/modules/ruins/spaceruin_code/asteroid10.dm
Labels: Feature, mapping

#4350 Revert "Removes the BS and diamond cost from the BS miners"
  code/game/objects/items/circuitboards/machine_circuitboards.dm
Labels: Removal

#4342 Corg station bulk tweaks from feedback thread
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: Feature, Fix, Tweak, mapping

#4353 Revert "Add's a reddit moment"
  code/modules/clothing/outfits/standard.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/vending/autodrobe.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: sprites

#4340 Fixes some new errors in vscode
  code/datums/traits/neutral.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/porta_turret/portable_turret.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/admin/verbs/one_click_antag.dm
  code/modules/crew_objectives/medical_objectives.dm
  code/modules/crew_objectives/security_objectives.dm
  code/modules/mob/living/simple_animal/hostile/floor_cluwne.dm
  code/modules/research/nanites/nanite_programs.dm
Labels: Administration, Code Improvement

#4345 Fixes cmp.dm runtime
  code/game/gamemodes/objective.dm
  code/modules/admin/team_panel.dm
  code/modules/antagonists/brother/brother.dm
Labels: Administration, Fix

#4322 Fixes blood tomatoes gibspawner
  code/game/objects/effects/spawners/gibspawner.dm
Labels: Fix, Removal

#4319 Fixes proximity monitor runtime
  code/game/objects/effects/proximity.dm
Labels: Fix, Removal

#4361 Lavaland atmos mix is now static
  beestation.dme
  code/__DEFINES/atmospherics.dm
  code/__DEFINES/traits.dm
  code/datums/atmosphere/_atmosphere.dm
  code/datums/atmosphere/planetary.dm
  code/datums/station_traits/neutral_traits.dm
Labels: Removal

#4077 mining keys to open tendrills crates buyable with miner points
  code/datums/components/crafting/recipes.dm
  code/game/objects/items/storage/belt.dm
  code/modules/antagonists/ashwalker/ashwalker.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mining/machine_vending.dm
  icons/obj/lavaland/artefacts.dmi
Labels: Balance/Rebalance, sprites

#4174 Removes donutstation
  README.md
  _maps/_basemap.dm
  _maps/donutstation.json
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/shuttles/arrival_donut.dmm
  code/datums/shuttles.dm
  config/Sage/maps.txt
  config/maps.txt
  interface/interface.dm
Labels: Config Update, mapping

#4233 removes the filter from corg SM waste loop
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: mapping

#4226 Admins will get pop up asking them to start BR if the round end was delayed
  code/modules/admin/admin.dm
  code/modules/admin/battle_royale.dm
  code/modules/mob/mob_stat.dm
  code/modules/tgui_panel/stat.dm
  tgui/packages/tgui-panel/stat/StatStatus.js
  tgui/packages/tgui-panel/stat/reducer.js
  tgui/packages/tgui-panel/styles/components/Stat.scss
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
  tgui/public/tgui-panel.bundle.css
  tgui/public/tgui-panel.bundle.js
Labels: Administration, TGUI-Changes

#4329 SYNTHS CAN HAVE MUTANT BODYPARTS NOW
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species_types/synths.dm
Labels: Fix

#4365 Various trait-related bugfixes
  code/datums/diseases/advance/symptoms/heal.dm
  code/datums/status_effects/buffs.dm
  code/datums/status_effects/neutral.dm
  code/game/objects/items/religion.dm
  code/modules/antagonists/clock_cult/scriptures/prosperity_prism.dm
  code/modules/antagonists/clock_cult/scriptures/sigil_of_vitality.dm
  code/modules/antagonists/eldritch_cult/eldritch_magic.dm
  code/modules/antagonists/eldritch_cult/knowledge/rust_lore.dm
  code/modules/hydroponics/beekeeping/beebox.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/species_types/IPC.dm
  code/modules/mob/living/carbon/human/species_types/apid.dm
  code/modules/mob/living/carbon/human/species_types/oozelings.dm
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
  code/modules/mob/living/carbon/human/species_types/squidpeople.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  code/modules/mob/living/simple_animal/guardian/types/support.dm
  code/modules/projectiles/guns/misc/medbeam.dm
Labels: Code Improvement, Fix

#4336 More Synth Fixes & Changes
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/synths.dm
Labels: Balance/Rebalance, Feature, Fix

#4374 Fixes a bug caused by shitcode
  code/modules/mob/living/carbon/human/species_types/synths.dm
Labels: Fix

#4376 modfabs no longer teleport disks when eject disk is pressed
  code/game/machinery/fabricators/modular_fabricator.dm
Labels: Fix

#4377 Disco Fever just got a little less feverish
  code/game/objects/items/grenades/discogrenade.dm
Labels: Fix, server

#4097 a lil viro tweak
  code/datums/diseases/advance/symptoms/clockwork.dm
  code/datums/diseases/advance/symptoms/heal.dm
  code/datums/diseases/advance/symptoms/necropolis.dm
  code/datums/diseases/advance/symptoms/oxygen.dm
  code/datums/diseases/advance/symptoms/wizarditis.dm
  code/game/objects/effects/spawners/lootdrop.dm
Labels: Fix, Tweak

#4372 Reworks reworked softcrit.
  code/__DEFINES/combat.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species_types/IPC.dm
  code/modules/mob/living/carbon/monkey/combat.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob_helpers.dm
Labels: Refactor

#4369 [PORT] Micro-optimize TGUI_CREATE_MESSAGE
  code/__DEFINES/tgui.dm
  code/__HELPERS/_logging.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/tgui_create_message.dm
Labels: Code Improvement, Port, Refactor, Tweak

#4383 Fixes a material dupe exploit
  code/modules/mining/machine_stacking.dm
Labels: Fix

#4385 Corrected a typo in the Exosuit Fabricator
  code/game/machinery/fabricators/modular_fabricator.dm
Labels: Fix, Grammar and Formatting

#4315 Status message small tweaks
  code/modules/mob/dead/observer/login.dm
  code/modules/mob/dead/observer/logout.dm
  code/modules/mob/living/death.dm
  code/modules/tgui_panel/stat.dm
Labels: Tweak

#4300 Fixes moths being able to eat pets + fixes pet throw runtime
  code/__DEFINES/obj_flags.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/mob/living/inhand_holder.dm
Labels: Fix, Tweak

#3951 Gangs Rework - Less Greytide Stationwide, More Territory Control
  beestation.dme
  code/game/gamemodes/gangs/gang_items.dm
  code/game/gamemodes/gangs/gangs.dm
  code/game/gamemodes/gangs/gangtool.dm
  code/game/gamemodes/gangs/implant_gang.dm
  code/game/gamemodes/gangs/outfits.dm
  code/game/objects/effects/countdown.dm
  code/game/objects/effects/decals/crayon.dm
  code/game/objects/items/crayons.dm
  code/modules/antagonists/_common/antag_spawner.dm
  code/modules/antagonists/gang/gang.dm
  code/modules/antagonists/gang/gang_datums.dm
  code/modules/antagonists/gang/gang_tags.dm
  code/modules/clothing/head/jobs.dm
Labels: Feature

#4388 Fixes hardsuits not holding back pressure.
  code/modules/clothing/spacesuits/hardsuit.dm
Labels: Fix

#4359 Radial blob rerolls
  beestation.dme
  code/__DEFINES/antagonists.dm
  code/_onclick/hud/blob_overmind.dm
  code/_onclick/hud/radial.dm
  code/game/objects/effects/info.dm
  code/modules/antagonists/blob/blobstrains/_blobstrain.dm
  code/modules/antagonists/blob/overmind.dm
  code/modules/antagonists/blob/powers.dm
  code/modules/antagonists/blob/structures/_blob.dm
  icons/effects/effects.dmi
Labels: Feature, sprites

#4366 Species that aren't able to heal cellular damage in any way are now immune to cellular damage.
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/modules/mob/living/carbon/human/species_types/android.dm
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
  code/modules/mob/living/damage_procs.dm
Labels: Tweak

#4387 Slime fix
  code/__DEFINES/mobs.dm
  code/modules/mob/living/simple_animal/slime/powers.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
Labels: Fix, Tweak

#4393 Ports TGS event handler from /tg/
  beestation.dme
  code/datums/helper_datums/getrev.dm
  code/datums/tgs_event_handler.dm
  code/game/world.dm
Labels: server

#4404 Prevents shooting yourself while pacified to create 1 hit kill projectiles.
  code/modules/projectiles/gun.dm
Labels: Fix

#4408 Changes the monkey cube crate's description to accurately reflect its contents.
  code/modules/cargo/packs.dm
Labels: Fix

#4396 fixes LAZYLEN
  code/__HELPERS/_lists.dm
Labels: Code Improvement

#4423 Added photocopier to HoP office on pubbystation
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, mapping

#3969 Actually removes circuits.
  beestation.dme
  code/__DEFINES/integrated_electronics.dm
  code/__DEFINES/logging.dm
  code/_globalvars/lists/objects.dm
  code/controllers/subsystem/processing/circuit.dm
  code/game/data_huds.dm
  code/game/machinery/telecomms/machine_interactions.dm
  code/game/machinery/telecomms/machines/receiver.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/multitool.dm
  code/game/turfs/closed/walls.dm
  code/modules/NTNet/netdata.dm
  code/modules/admin/admin_investigate.dm
  code/modules/integrated_electronics/core/analyzer.dm
  code/modules/integrated_electronics/core/assemblies.dm
  code/modules/integrated_electronics/core/debugger.dm
  code/modules/integrated_electronics/core/detailer.dm
  code/modules/integrated_electronics/core/helpers.dm
  code/modules/integrated_electronics/core/integrated_circuit.dm
  code/modules/integrated_electronics/core/pins.dm
  code/modules/integrated_electronics/core/printer.dm
  code/modules/integrated_electronics/core/saved_circuits.dm
  code/modules/integrated_electronics/core/special_pins/boolean_pin.dm
  code/modules/integrated_electronics/core/special_pins/char_pin.dm
  code/modules/integrated_electronics/core/special_pins/color_pin.dm
  code/modules/integrated_electronics/core/special_pins/dir_pin.dm
  code/modules/integrated_electronics/core/special_pins/index_pin.dm
  code/modules/integrated_electronics/core/special_pins/list_pin.dm
  code/modules/integrated_electronics/core/special_pins/number_pin.dm
  code/modules/integrated_electronics/core/special_pins/ref_pin.dm
  code/modules/integrated_electronics/core/special_pins/selfref_pin.dm
  code/modules/integrated_electronics/core/special_pins/string_pin.dm
  code/modules/integrated_electronics/core/wirer.dm
  code/modules/integrated_electronics/passive/passive.dm
  code/modules/integrated_electronics/passive/power.dm
  code/modules/integrated_electronics/subtypes/access.dm
  code/modules/integrated_electronics/subtypes/arithmetic.dm
  code/modules/integrated_electronics/subtypes/converters.dm
  code/modules/integrated_electronics/subtypes/data_transfer.dm
  code/modules/integrated_electronics/subtypes/input.dm
  code/modules/integrated_electronics/subtypes/lists.dm
  code/modules/integrated_electronics/subtypes/logic.dm
  code/modules/integrated_electronics/subtypes/manipulation.dm
  code/modules/integrated_electronics/subtypes/memory.dm
  code/modules/integrated_electronics/subtypes/mining.dm
  code/modules/integrated_electronics/subtypes/output.dm
  code/modules/integrated_electronics/subtypes/power.dm
  code/modules/integrated_electronics/subtypes/smart.dm
  code/modules/integrated_electronics/subtypes/text.dm
  code/modules/integrated_electronics/subtypes/time.dm
  code/modules/integrated_electronics/subtypes/trig.dm
  code/modules/mob/living/silicon/pai/pai_shell.dm
  code/modules/research/designs/electronics_designs.dm
  code/modules/research/techweb/all_nodes.dm
  html/browser/assembly_ui.css
  tgui/packages/tgui/interfaces/Telecomms.js
  tgui/public/tgui.bundle.js
Labels: Administration, Needs Testmerge, Removal, TGUI-Changes

#4352 Fixes runtime in configuration.dm
  code/controllers/configuration/configuration.dm
  code/game/world.dm
Labels: Fix, Needs Testmerge

#4433 fix ethereals not charging with borg chargers
  code/game/machinery/rechargestation.dm
Labels: Fix

#4362 Ports "Makes client timers not able to perma block normal timers"
  code/__DEFINES/subsystems.dm
  code/controllers/subsystem/timer.dm
  code/game/objects/effects/spawners/xeno_egg_delivery.dm
  code/game/world.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/debug.dm
  code/modules/jobs/job_types/_job.dm
Labels: Administration, Feature, Needs Testmerge
