Repository BeeStation/BeeStation-Hornet, pull requests merged in 2022-02, with the labels that each got.

#6280 Fix corgi stripping
  code/modules/mob/living/simple_animal/friendly/dog.dm
Labels: Fix

#6284 Makes a SECONDS define Implementation consistent
  code/game/objects/items/devices/PDA/PDA_types.dm
Labels: Fix, Code Improvement

#6269 [PORT] Ports and adds sprites and inhands for all syringe types, plus tiny fixes
  code/modules/reagents/reagent_containers/syringes.dm
  icons/mob/inhands/equipment/medical_lefthand.dmi
  icons/mob/inhands/equipment/medical_righthand.dmi
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/obj/projectiles.dmi
  icons/obj/syringe.dmi
Labels: Feature, sprites

#6257 Adds a Check to Inhand BS Bodybag Deployment
  code/game/objects/items/bodybag.dm
Labels: Fix

#6250 Paper improvements
  code/modules/paperwork/paper.dm
Labels: Fix, Refactor

#6282 Fix a couple atmos-related runtimes
  code/modules/mob/living/simple_animal/bot/atmosbot.dm
  code/modules/power/turbine.dm
Labels: Fix, Code Improvement

#6231 Ports some timer fixes
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/timer.dm
  config/config.txt
Labels: Port, Fix, Config Update

#6302 Bumps BYOND to 1575
  Dockerfile
  code/_compile_options.dm
  dependencies.sh
Labels: server

#6274 Port improved reference tracking and harddel testing from tg.
  .vscode/tasks.json
  _maps/templates/unit_tests.dmm
  bin/temp-fast-test.cmd
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/qdel.dm
  code/__DEFINES/vv.dm
  code/__HELPERS/_logging.dm
  code/_compile_options.dm
  code/_globalvars/logging.dm
  code/controllers/subsystem/atoms.dm
  code/controllers/subsystem/garbage.dm
  code/datums/datum.dm
  code/datums/datumvars.dm
  code/game/objects/effects/landmarks.dm
  code/game/world.dm
  code/modules/admin/view_variables/reference_tracking.dm
  code/modules/admin/view_variables/topic_basic.dm
  code/modules/admin/view_variables/view_variables.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/connect_loc.dm
  code/modules/unit_tests/create_and_destroy.dm
  code/modules/unit_tests/find_reference_sanity.dm
  code/modules/unit_tests/spawn_humans.dm
  code/modules/unit_tests/unit_test.dm
Labels: mapping, Administration, Removal, server

#6303 fixes shuttles spamming zlevel generation for effects/other non items objects with the indestructible flag
  code/game/turfs/open/space/transit.dm
Labels: Fix

#5684 Adds hair color gradients
  code/__HELPERS/global_lists.dm
  code/_globalvars/lists/flavor_misc.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/species.dm
  icons/mob/hair_gradients.dmi
Labels: Feature, sprites

#6223 Flandstation - Service Pack 4 (More QoL changes)
  _maps/map_files/FlandStation/FlandStation.dmm
Labels: mapping, Tweak, Fix

#6251 Exploration Expansion Pack: New Targets, New Rooms, And Revisited Old Favorites
  _maps/RuinGeneration/11x11_2_room_cafeteria.dmm
  _maps/RuinGeneration/13x13_ai-lab.dmm
  _maps/RuinGeneration/13x13_cafe.dmm
  _maps/RuinGeneration/13x13_corgarmory.dmm
  _maps/RuinGeneration/13x13_corgrobotics.dmm
  _maps/RuinGeneration/13x13_donutroom.dmm
  _maps/RuinGeneration/13x13_shotelroom.dmm
  _maps/RuinGeneration/13x13_supermatter_containment.dmm
  _maps/RuinGeneration/13x17_chapel.dmm
  _maps/RuinGeneration/13x17_permabrig.dmm
  _maps/RuinGeneration/13x17_shuttledock.dmm
  _maps/RuinGeneration/13x9_josito.dmm
  _maps/RuinGeneration/13x9_medical.dmm
  _maps/RuinGeneration/13x9_researchlab.dmm
  _maps/RuinGeneration/17x11_2_room_corgbar.dmm
  _maps/RuinGeneration/17x17_charliecrew.dmm
  _maps/RuinGeneration/17x9_pubbybridgehall.dmm
  _maps/RuinGeneration/21x17_shuttledock.dmm
  _maps/RuinGeneration/21x21_singularity.dmm
  _maps/RuinGeneration/21x29_solars.dmm
  _maps/RuinGeneration/25x21_shuttleconstructionbay.dmm
  _maps/RuinGeneration/41x41_corgasteroid.dmm
  _maps/RuinGeneration/5x5_hern.dmm
  _maps/RuinGeneration/5x5_roomcross.dmm
  _maps/RuinGeneration/5x9_lounge.dmm
  _maps/RuinGeneration/69x45_charliestation.dmm
  _maps/RuinGeneration/9x13_vault.dmm
  _maps/RuinGeneration/9x5_cloning.dmm
  _maps/RuinGeneration/9x9_checkpoint.dmm
  _maps/RuinGeneration/9x9_chemlab.dmm
  _maps/RuinGeneration/9x9_toxinstorage.dmm
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/objective_types/assassination.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/objective_types/vip_extraction.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/ruin_part_types.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: mapping, Tweak, Feature, sprites, Fix, Code Improvement

#6309 Fixes Round Duration API
  code/datums/world_topic.dm
Labels: Fix

#6315 Fixes "Hopefully prevents some grief"
  code/modules/cargo/packs.dm
Labels: Fix

#6322 Fixes a mistake
  code/modules/shuttle/super_cruise/orbital_poi_generator/loot/artifact_defenses.dm
Labels: Fix

#6279 Macros IS_GUEST_KEY
  code/__DEFINES/is_helpers.dm
  code/__HELPERS/unsorted.dm
  code/modules/admin/IsBanned.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/silicon/pai/personality.dm
Labels: Refactor, Administration

#6313 Fixes clothing coverage
  code/__HELPERS/pronouns.dm
  code/game/objects/structures/shower.dm
  code/modules/mob/living/carbon/examine.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/update_icons.dm
Labels: Fix

#6014 get_hear and get_hearers_in_view optimisations
  code/__HELPERS/game.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/debug.dm
Labels: Needs Testmerge, test merged, Tweak, Administration

#6329 Fixes combat gloves worn icon
  code/modules/clothing/gloves/miscellaneous.dm
Labels: Fix

#6331 Fix (picture-taking) cameras not working
  code/modules/photography/camera/camera.dm
Labels: Fix

#6202 Medical belt resprite
  code/game/objects/items/storage/belt.dm
  icons/mob/belt.dmi
  icons/obj/clothing/belt_overlays.dmi
  icons/obj/clothing/belts.dmi
Labels: Feature, sprites

#6332 Prevents MAPROTATION from picking the same map
  code/controllers/subsystem/mapping.dm
Labels: Tweak, Vote Passed

#6324 Remove a pointless `initial()` call
  code/modules/clothing/chameleon.dm
Labels: Fix, Code Improvement

#5774 Cryopods use signals to handle objectives and other objective improvements
  code/__DEFINES/dcs/signals.dm
  code/__HELPERS/roundend.dm
  code/_globalvars/game_modes.dm
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/ticker.dm
  code/datums/brain_damage/creepy_trauma.dm
  code/datums/mind.dm
  code/game/gamemodes/devil/devil agent/devil_agent.dm
  code/game/gamemodes/devil/objectives.dm
  code/game/gamemodes/hivemind/objectives.dm
  code/game/gamemodes/objective.dm
  code/game/gamemodes/overthrow/objective.dm
  code/game/machinery/cryopod.dm
  code/modules/antagonists/abductor/abductor.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/clock_cult/clockcult_objectives.dm
  code/modules/antagonists/creep/creep.dm
  code/modules/antagonists/cult/cult.dm
  code/modules/antagonists/disease/disease_datum.dm
  code/modules/antagonists/eldritch_cult/eldritch_antag.dm
  code/modules/antagonists/eldritch_cult/eldritch_items.dm
  code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
  code/modules/antagonists/incursion/incursion.dm
  code/modules/antagonists/monkey/monkey.dm
  code/modules/antagonists/ninja/ninja.dm
  code/modules/antagonists/revenant/revenant.dm
  code/modules/antagonists/revolution/revolution.dm
  code/modules/antagonists/roundstart_special/undercover/undercover.dm
  code/modules/antagonists/slaughter/slaughter_antag.dm
  code/modules/antagonists/space_dragon/space_dragon.dm
  code/modules/antagonists/traitor/IAA/internal_affairs.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/antagonists/valentines/valentine.dm
  code/modules/antagonists/wizard/wizard.dm
  code/modules/crew_objectives/_crew_objectives.dm
  code/modules/crew_objectives/cargo_objectives.dm
  code/modules/crew_objectives/civilian_objectives.dm
  code/modules/crew_objectives/command_objectives.dm
  code/modules/crew_objectives/engineering_objectives.dm
  code/modules/crew_objectives/medical_objectives.dm
  code/modules/crew_objectives/science_objectives.dm
  code/modules/crew_objectives/security_objectives.dm
  code/modules/events/wizard/greentext.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/ruins/objects_and_mobs/ash_walker_den.dm
  code/modules/spells/spell_types/hivemind.dm
Labels: Fix, Refactor, Code Improvement

#6314 Ports updates to the cameranet
  code/__DEFINES/sight.dm
  code/game/machinery/computer/camera_advanced.dm
  code/game/objects/items/devices/multitool.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/freelook/cameranet.dm
  code/modules/mob/living/silicon/ai/freelook/chunk.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/shuttle/shuttle_creation/shuttle_creator_console.dm
  code/modules/shuttle/super_cruise/shuttle_components/shuttle_docking.dm
Labels: Fix, Refactor, Removal, Code Improvement

#6337 Adds suspenders to Autodrobe
  code/modules/vending/autodrobe.dm
Labels: Feature

#6297 Ports some New() -> Init() conversions and init profiling
  code/_compile_options.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/plane_master_controller.dm
  code/_onclick/hud/screen_objects.dm
  code/controllers/subsystem/atoms.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/title.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/documents.dm
  code/game/objects/structures/fireplace.dm
  code/game/objects/structures/mirror.dm
  code/game/objects/structures/petrified_statue.dm
  code/game/objects/structures/transit_tubes/transit_tube.dm
  code/game/turfs/closed/_closed.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/antagonists/wizard/equipment/artefact.dm
  code/modules/atmospherics/gasmixtures/auxgm.dm
  code/modules/atmospherics/machinery/airalarm.dm
  code/modules/mob/dead/dead.dm
  code/modules/mob/dead/new_player/new_player.dm
  tools/read_init_times.py
Labels: Feature, Refactor, tools

#6298 Updates lung code
  code/modules/atmospherics/auxgm/breathing_classes.dm
  code/modules/surgery/organs/lungs.dm
Labels: Tweak, Fix, Code Improvement

#6357 Ports making SSrunechat be a timer subsystem
  code/__DEFINES/subsystems.dm
  code/controllers/subsystem/runechat.dm
  code/controllers/subsystem/timer.dm
  code/datums/chatmessage.dm
  code/datums/datum.dm
Labels: Refactor

#5755 Updates Kilo Station and re-adds it to rotation
  _maps/RandomRooms/10x10/sk_rdm159_kilosnakepit.dmm
  _maps/RandomRooms/10x5/sk_rdm161_kilovault.dmm
  _maps/RandomRooms/3x5/sk_rdm158_kilochapelstorage.dmm
  _maps/RandomRooms/3x5/sk_rdm160_kilomaintbar.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/shuttles/emergency_kilo.dmm
  _maps/shuttles/exploration_kilo.dmm
  _maps/shuttles/mining_kilo.dmm
  code/datums/shuttles.dm
  code/datums/weather/weather_types/radiation_storm.dm
  code/modules/mapping/random_rooms.dm
  config/maps.txt
Labels: mapping, test merged, Feature, Config Update, Removal

#6350 Fixes alt states of suits
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Fix

#6365 Fixes few jumpsuit errors
  code/datums/components/crafting/tailoring.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/color.dm
  code/modules/clothing/under/jobs/civilian/civilian.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/vending/wardrobes.dm
  strings/names/carp.txt
  tgui/README.md
Labels: Fix, Removal, TGUI-Changes

#6359 Energetic Chromosome Fix
  code/datums/mutations.dm
  code/datums/mutations/actions.dm
Labels: Fix

#6348 Makes the SMES in pubby AI chamber actually function
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: mapping, Fix

#6367 fixes infinite iron duplication with riggit toolboxes
  code/game/machinery/fabricators/modular_fabricator.dm
Labels: Fix, Code Improvement

#6370 Kilo Quick Fix #1
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: mapping, Fix

#6360 Ports the quick qdel queue
  code/__DEFINES/qdel.dm
  code/controllers/subsystem/garbage.dm
Labels: Code Improvement

#6385 Show server name in round end report
  code/__HELPERS/roundend.dm
Labels: Tweak, server

#6388 Bumps the client version of BYOND to 1575
  code/modules/client/client_procs.dm
Labels: server

#6293 Xenobiology golem nerf
  code/game/objects/items/stacks/sheets/mineral.dm
Labels: Tweak, Balance/Rebalance

#6227 Any paranoia no longer makes you be afraid of your own species
  code/datums/brain_damage/phobia.dm
Labels: Tweak

#6389 Touches Up Some ION_LAW Fragments to current standards
  strings/ion_laws.json
Labels: Tweak

#6380 TGUI dependency maintenance
  tgui/yarn.lock
Labels: test merged, server, TGUI-Changes

#6384 Kilo Quick Fix #2
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: mapping, Fix

#6396 Kilo Quick Fix #3
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/shuttles/exploration_kilo.dmm
Labels: mapping, Feature, Fix

#6295 Fix "Cryogenic Storage" area on Delta, and Delta exploration shuttle's airlocks
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/shuttles/exploration_delta.dmm
Labels: mapping, Feature, Fix

#5560 Changes to handing out mutations
  beestation.dme
  code/datums/wires/dna_scanner.dm
  code/game/machinery/computer/dna_console.dm
  code/game/machinery/dna_scanner.dm
  code/game/objects/items/devices/scanners.dm
  icons/obj/machines/cloning.dmi
  tgui/packages/tgui/interfaces/DnaConsole.js
Labels: Needs Testmerge, Tweak, Feature, sprites, Code Improvement, TGUI-Changes

#6051 Adds Design for Research Disk Locator to Sci Protolathe
  code/modules/research/designs/tool_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature

#5989 nerfs reproductive extracts
  code/datums/components/storage/concrete/extract_inventory.dm
  code/modules/research/xenobiology/crossbreeding/reproductive.dm
Labels: Balance/Rebalance

#5859 Ports putting hats on envirohelms from /tg/
  code/modules/clothing/spacesuits/plasmamen.dm
Labels: Feature

#6055 actually fixes blob spore pathfinding
  code/__HELPERS/path.dm
  code/modules/antagonists/blob/blob_mobs.dm
  code/modules/antagonists/blob/powers.dm
Labels: Tweak, Feature, Fix, Removal

#6378 Some fixes and improvements to hangover
  code/__HELPERS/unsorted.dm
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/processing/station.dm
  code/datums/station_traits/negative_traits.dm
  code/game/objects/effects/landmarks.dm
Labels: Feature, Refactor

#6341 Diversification and alteration of chemical colors for better readability.
  code/game/objects/effects/decals/cleanable/misc.dm
  code/modules/antagonists/blob/blobstrains/regenerative_materia.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Tweak

#6338 Fixes unmanaged z-level runtimes
  code/game/machinery/computer/crew.dm
Labels: Fix

#6325 Fixeswarnings in vsc
  code/__DEFINES/spaceman_dmm.dm
  code/__HELPERS/type2type.dm
  code/datums/brain_damage/severe.dm
  code/datums/diseases/dna_spread.dm
  code/game/machinery/requests_console.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/mob_helpers.dm
  code/modules/pool/components/swimming_felinid.dm
  code/modules/power/singularity/singularity.dm
  code/modules/surgery/advanced/lobotomy.dm
  code/modules/uplink/uplink_items.dm
  code/modules/vending/_vending.dm
Labels: Feature, Fix

#6300 Makes Intern a Negative Trait
  code/datums/station_traits/negative_traits.dm
  code/datums/station_traits/neutral_traits.dm
Labels: Tweak

#6101 Removes debtor
  _maps/RandomRooms/10x5/sk_rdm091_skidrow.dmm
  _maps/RandomRooms/10x5/sk_rdm153_hobowithpeter.dmm
  _maps/RandomRooms/3x3/sk_rdm092_hobohut.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_11_hobobox.dmm
  code/__DEFINES/jobs.dm
  code/game/objects/effects/landmarks.dm
  code/modules/clothing/outfits/plasmaman.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/gimmick.dm
  code/modules/jobs/jobs.dm
  code/modules/mapping/random_rooms.dm
  code/modules/uplink/uplink_items.dm
  icons/mob/hud.dmi
  icons/mob/landmarks.dmi
  tgui/packages/tgui-panel/chat/renderer.js
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: mapping, sprites, Removal, TGUI-Changes

#6320 Nuked Psychotic Brawling From Orbit
  beestation.dme
  code/datums/brain_damage/phobia.dm
  code/datums/brain_damage/special.dm
  code/datums/martial/psychotic_brawl.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
Labels: Removal

#6192 Adds More Achievements
  code/__DEFINES/achievements.dm
  code/__HELPERS/roundend.dm
  code/datums/achievements/misc_achievements.dm
  code/modules/antagonists/nukeop/equipment/nuclear_challenge.dm
  code/modules/cargo/packs.dm
  code/modules/mining/equipment/wormhole_jaunter.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
Labels: Feature

#6294 Resprites and adds inhands for cases and lockboxes plus small lockbox code refactor
  code/game/objects/items/storage/briefcase.dm
  code/game/objects/items/storage/lockbox.dm
  code/game/objects/items/storage/secure.dm
  code/modules/photography/photos/album.dm
  code/modules/projectiles/guns/energy/dueling.dm
  icons/mob/inhands/equipment/briefcase_lefthand.dmi
  icons/mob/inhands/equipment/briefcase_righthand.dmi
  icons/mob/inhands/equipment/case_lefthand.dmi
  icons/mob/inhands/equipment/case_righthand.dmi
  icons/obj/storage.dmi
Labels: sprites

#6116 Chat messages with no language are now handled correctly.
  code/datums/chatmessage.dm
Labels: Fix

#6046 Adds body size options
  code/__DEFINES/mobs.dm
  code/_globalvars/lists/flavor_misc.dm
  code/datums/dna.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/dullahan.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/mob/living/carbon/human/species_types/mushpeople.dm
  code/modules/mob/living/carbon/human/species_types/vampire.dm
Labels: Feature

#6404 Fixes roundend not restarting
  code/__HELPERS/roundend.dm
Labels: Fix

#6410 Fixes worn icon of fingerless gloves
  code/modules/clothing/gloves/miscellaneous.dm
Labels: Fix

#6413 Fixes not being able to drop people and emotes not working
  code/datums/chatmessage.dm
  code/datums/components/riding.dm
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
Labels: Fix

#6422 Fixes Tipped Medibots
  code/__DEFINES/robots.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
Labels: Fix

#6426 replaces return . = ..() with return ..()
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Code Improvement

#6425 Supply Manifest Fix
  code/modules/cargo/order.dm
Labels: Fix

#6421 Adds the F4 hotkey to the admin hotkey list
  interface/interface.dm
Labels: Feature

#6417 Fixes invalid achievements, adds a unit test
  code/__DEFINES/achievements.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/achievement_validation.dm
Labels: Fix, Code Improvement

#6372 Detective can be a traitor again,
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/traitor/traitor.dm
  code/modules/jobs/job_types/detective.dm
Labels: Tweak, Vote Passed

#6415 Enable new TGUI message types by default
  tgui/packages/tgui-panel/chat/model.js
  tgui/packages/tgui-panel/chat/reducer.js
Labels: Tweak, Feature, Config Update, Code Improvement, TGUI-Changes

#6411 probably fixes body size runtime
  code/__HELPERS/mobs.dm
  code/datums/dna.dm
  code/modules/mining/lavaland/necropolis_chests.dm
Labels: test merged, Fix

#6433 Prioritized Job Note On Late join Screen
  code/modules/mob/dead/new_player/new_player.dm
Labels: Feature

#6424 Adminordrazine Deafness Fix
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Fix

#6432 MetaStation Turbine Space Injector
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: mapping, Tweak

#6435 Fixes reflectors not rotating on shuttle move
  code/game/objects/structures/reflector.dm
Labels: Fix
