Repository BeeStation/BeeStation-Hornet, pull requests merged in 2022-03, with the labels that each got.

#6437 Fixes tables clipping in Mac Space ruin
  _maps/RandomRuins/SpaceRuins/Fast_Food.dmm
Labels: mapping, Fix

#6441 Adds space law to book management consoles and SecTech
  code/modules/library/lib_machines.dm
  code/modules/vending/security.dm
Labels: Feature

#6032 Cloning machine major fixes and changes
  code/__DEFINES/machines.dm
  code/__DEFINES/role_preferences.dm
  code/_globalvars/lists/poll_ignore.dm
  code/game/machinery/cloning.dm
  code/game/machinery/computer/cloning.dm
  tgui/packages/tgui/interfaces/CloningConsole.js
Labels: Needs Testmerge, test merged, Tweak, Feature, Fix, Refactor, Administration, Code Improvement, server, TGUI-Changes

#6104 Larry Attachables
  beestation.dme
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/dcs/signals.dm
  code/datums/components/larryknife.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
  icons/mob/inhands/misc/larry.dmi
Labels: Feature, sprites

#6299 Nerfs xenobio cheese
  code/datums/diseases/transformation.dm
Labels: Tweak

#6353 Makes Destroy() call parent & misc cleanup
  code/__HELPERS/game.dm
  code/controllers/globals.dm
  code/controllers/subsystem/acid.dm
  code/controllers/subsystem/augury.dm
  code/controllers/subsystem/fire_burning.dm
  code/controllers/subsystem/garbage.dm
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/mapping.dm
  code/datums/datum.dm
  code/datums/position_point_vector.dm
  code/datums/weakrefs.dm
  code/modules/antagonists/clock_cult/scriptures/_clockwork_scripture.dm
  code/modules/client/client_procs.dm
  code/modules/events/immovable_rod.dm
  code/modules/events/wizard/rpgloot.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/loot/alien_artifact.dm
Labels: Refactor, Code Improvement

#6468 Fixes being able to make degraded sunhuds down into advanced sunglasses
  code/datums/components/crafting/tailoring.dm
Labels: Fix

#6427 Force String Fix
  code/game/objects/items.dm
Labels: Fix

#6197 Ephedrine and Modafinil Changes
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Balance/Rebalance

#6431 Fixes MetaStation Turbine Air Circulation
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: mapping, Feature

#6479 Simplifies the pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: GitHub, Code Improvement

#6464 Light overlay fixes
  code/modules/power/lighting.dm
  icons/obj/lighting_overlay.dmi
Labels: Feature, sprites, Fix

#6457 Nerfs oil slime extract's explosion radius
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
Labels: Balance/Rebalance

#6414 Fixes ai Cntrl click on atmos machinary and some qol changes
  code/_onclick/ai.dm
Labels: Tweak, Feature, Fix

#6484 fixes invisible disposal pipe segments/disposal pipe segments having an icon_state = null
  code/modules/recycling/disposal/construction.dm
Labels: Fix

#6486 Ports an important DNA console fix
  code/game/machinery/computer/dna_console.dm
Labels: Fix

#6489 Fixes typo in exploration room
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: mapping, Grammar and Formatting

#6485 Change brig timer to use real time instead of server time
  code/game/machinery/doors/brigdoors.dm
Labels: Balance/Rebalance, Refactor, server

#6487 Properly sanitizes gene codes
  code/game/machinery/computer/dna_console.dm
Labels: Fix

#6497 Fixes mutations not revealing
  code/datums/mutations/actions.dm
  code/datums/mutations/body.dm
Labels: Fix

#6498 Bump the client version to 1582
  code/modules/client/client_procs.dm
Labels: Feature, Fix, Code Improvement

#6097 New Medical Implant, Surgery minor fix
  code/__DEFINES/DNA.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/loot/research_disks.dm
  code/modules/surgery/organs/augments_internal.dm
  code/modules/surgery/organs/autosurgeon.dm
  code/modules/surgery/surgery.dm
Labels: Voting, Tweak, Feature, Fix, Refactor, Code Improvement, server

#6499 Fix infinite microwaves
  code/modules/food_and_drinks/kitchen_machinery/microwave.dm
Labels: Fix

#6505 Notifies silicon users when their TGUI window pool is exhausted
  code/controllers/subsystem/tgui.dm
Labels: Feature

#6503 Adds mentor chat to the TGUI chat filter and improves MSAY window.
  code/__DEFINES/chat.dm
  code/modules/mentor/mentorsay.dm
  tgui/packages/tgui-panel/chat/constants.js
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: Tweak, Feature, Removal, TGUI-Changes

#6511 Fixes the atmosbot control panel
  code/modules/mob/living/simple_animal/bot/atmosbot.dm
Labels: Fix

#6504 Stops current sounds when you go deaf
  code/datums/mutations/body.dm
  code/modules/surgery/organs/ears.dm
Labels: Tweak

#6514 Makes automatic conveyors actually start
  code/modules/recycling/conveyor2.dm
Labels: Fix

#6513 Stops magic SMES from dividing infinity by infinity
  code/modules/power/smes.dm
Labels: Fix

#6519 Fixes defibrillator overlay not appearing on the pre-loaded wallmount
  code/game/machinery/defibrillator_mount.dm
Labels: Fix

#6522 Fixes issue with pixel perfect 1.5x not saving properly
  code/__HELPERS/sanitize_values.dm
  code/modules/client/preferences_savefile.dm
Labels: Fix

#6488 Another slimeperson murder fix
  code/modules/mob/living/simple_animal/guardian/types/support.dm
Labels: Fix

#6500 Space vines fix
  code/modules/events/spacevine.dm
Labels: Fix

#6447 Repipes Kilo to be less cancer.
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: mapping, Needs Testmerge, Tweak, Feature, Refactor, Somewhat important

#6461 No More Crewsimov
  code/datums/ai_laws.dm
  config/game_options.txt
Labels: Config Update, Vote Passed, Removal

#6474 New ID sprites
  code/game/machinery/PDApainter.dm
  code/game/objects/items/cards_ids.dm
  code/modules/jobs/job_types/brigphys.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/chemist.dm
  code/modules/jobs/job_types/deputy.dm
  code/modules/jobs/job_types/emt.dm
  code/modules/jobs/job_types/geneticist.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/janitor.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/jobs/job_types/virologist.dm
  icons/obj/card.dmi
Labels: Feature, sprites

#6525 Revert "No More Crewsimov"
  code/datums/ai_laws.dm
  config/game_options.txt
Labels: Feature, Config Update

#6533 Fix typo in corazone description
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Grammar and Formatting

#6540 [s] Fix Topic Security Issue
  code/game/world.dm
Labels: Fix, server

#6526 Broadcasts explosions to ghosts
  code/controllers/subsystem/explosion.dm
Labels: Feature

#6521 Vault-Safe and Security TV resprite
  icons/obj/computer.dmi
  icons/obj/structures.dmi
Labels: Feature, sprites

#6472 Removes Sentient Disease
  beestation.dme
  code/datums/diseases/advance/advance.dm
  code/modules/antagonists/disease/disease_datum.dm
  code/modules/antagonists/disease/disease_disease.dm
  code/modules/antagonists/disease/disease_event.dm
  code/modules/antagonists/disease/disease_mob.dm
Labels: Removal

#6539 Fixes Cat Claws, lowers Acid Ooze power.
  code/datums/mutations/actions.dm
  code/datums/mutations/body.dm
Labels: Balance/Rebalance

#6537 Artifact Enemy Rebalance
  code/modules/shuttle/super_cruise/orbital_poi_generator/loot/artifact_defenses.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/objective_types/alien_artifact.dm
Labels: Balance/Rebalance

#6517 Some Delta Station decal fixes and additions
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: mapping, Tweak, Feature, Fix, Needs pictures

#6006 makes ipcs respect nocritdamage, reduces IPC crit damage to be in line with intended amounts (according to a line in the code)
  code/modules/mob/living/carbon/human/species_types/IPC.dm
Labels: Tweak, Fix

#6556 Bumps byond to 1583
  Dockerfile
  code/_compile_options.dm
  code/modules/client/client_procs.dm
  dependencies.sh
Labels: server

#6561 [s] Bumps minimist to 1.2.6
  tgui/yarn.lock
Labels: security, server, TGUI-Changes

#6436 GAGS for plasmamen helmets
  code/datums/action.dm
  code/datums/greyscale/greyscale_configs.dm
  code/datums/greyscale/json_configs/plasmaman_helmet_default.json
  code/datums/greyscale/json_configs/plasmaman_helmet_default_inhand.json
  code/datums/greyscale/json_configs/plasmaman_helmet_default_worn.json
  code/datums/greyscale/json_configs/plasmaman_helmet_mk2.json
  code/datums/greyscale/json_configs/plasmaman_helmet_mk2_inhand.json
  code/datums/greyscale/json_configs/plasmaman_helmet_mk2_worn.json
  code/datums/greyscale/json_configs/plasmaman_helmet_protective.json
  code/datums/greyscale/json_configs/plasmaman_helmet_protective_inhand.json
  code/datums/greyscale/json_configs/plasmaman_helmet_protective_worn.json
  code/game/atoms_movable.dm
  code/modules/clothing/outfits/plasmaman.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/mining/mine_items.dm
  code/modules/vending/wardrobes.dm
  icons/mob/clothing/head.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/obj/clothing/hats.dmi
Labels: Tweak, Feature, Sprites, Fix, Removal

#6560 Make autotransfer vote use real time
  code/controllers/subsystem/autotransfer.dm
Labels: Tweak

#6321 Makes used grenades slightly more obvious. Also prevents DOSing admins.
  beestation.dme
  code/datums/wires/explosive.dm
  code/game/machinery/deployable.dm
  code/game/objects/items/grenades/_grenade.dm
  code/game/objects/items/grenades/antigravity.dm
  code/game/objects/items/grenades/chem_grenade.dm
  code/game/objects/items/grenades/clusterbuster.dm
  code/game/objects/items/grenades/discogrenade.dm
  code/game/objects/items/grenades/emgrenade.dm
  code/game/objects/items/grenades/flashbang.dm
  code/game/objects/items/grenades/ghettobomb.dm
  code/game/objects/items/grenades/plastic.dm
  code/game/objects/items/grenades/smokebomb.dm
  code/game/objects/items/grenades/spawnergrenade.dm
  code/game/objects/items/grenades/syndieminibomb.dm
  code/modules/exploration_crew/exploration_explosives.dm
  code/modules/research/experimentor.dm
Labels: Feature, Fix

#6483 Removes Unused Species
  beestation.dme
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species_types/corporate.dm
  code/modules/mob/living/carbon/human/species_types/mushpeople.dm
Labels: Removal

#6351 Clowns are too sweet to understand death
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/jobs/job_types/clown.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: Tweak

#6069 Adds ectoscopic sniffer
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  beestation.dme
  code/datums/wires/ecto_sniffer.dm
  code/game/machinery/ecto_sniffer.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  icons/obj/machines/research.dmi
  sound/machines/ectoscope_beep.ogg
Labels: Mapping, Feature, Sprites, Sound

#6126 Reinforced and nar'sien bolas now knockdown instead
  code/game/objects/items/handcuffs.dm
Labels: Balance/Rebalance

#6217 Nerfs defensive nanites.
  code/modules/research/nanites/nanite_programs/buffing.dm
Labels: Balance/Rebalance

#6482 Make alpha plane invisible while blind
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/status_procs.dm
Labels: Fix

#6562 Another extrapolator fix
  code/game/objects/items/devices/scanners.dm
Labels: Fix

#6550 The Eminence can no longer jump to cultists on the CC Z Level
  code/modules/antagonists/clock_cult/mobs/eminence.dm
Labels: Fix

#6580 le fishe update (carp gags and Cayenne can carry nuke disk)
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  code/__DEFINES/achievements.dm
  code/__DEFINES/traits.dm
  code/datums/achievements/_achievement_data.dm
  code/datums/achievements/misc_achievements.dm
  code/datums/action.dm
  code/datums/greyscale/greyscale_configs.dm
  code/datums/greyscale/json_configs/carp.json
  code/datums/greyscale/json_configs/carp_disk_mouth.json
  code/game/objects/items/dehy_carp.dm
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
  code/modules/events/wizard/magicarp.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/eyeballs.dm
  icons/UI_Icons/Achievements/cayenne_disk.png
  icons/mob/animal.dmi
  icons/mob/carp.dmi
Labels: Mapping, Feature, Sprites

#6581 Revert "Make alpha plane invisible while blind"
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/status_procs.dm
Labels: Fix, Removal

#6586 Fixes Lia having bad icon state on fland (and corg)
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
Labels: Mapping, Fix

#6583 autosurgeon fix
  code/modules/surgery/organs/autosurgeon.dm
Labels: Fix

#6587 Fixes some small issues with get_hearers_in_view regarding invisible mobs
  code/__HELPERS/game.dm
  code/modules/instruments/songs/_song.dm
  code/modules/mob/mob.dm
Labels: Fix
