Repository BeeStation/BeeStation-Hornet, pull requests merged in 2022-07, with the labels that each got.

#7141 Fixes Zombie Powder spamming *deathgasp
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
Labels: Fix

#7136 Shaft miners start with discovery scanner
  code/modules/jobs/job_types/shaft_miner.dm
Labels: Feature

#7157 now to craft Spicy-pocket you need chili
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
Labels: Fix

#7168 Updates balloon alerts in the aiming component
  code/datums/components/aiming.dm
Labels: Tweak, Good PR

#7094 Plasmaman hats additions
  code/modules/client/loadout/loadout_hat.dm
  code/modules/clothing/spacesuits/plasmamen.dm
Labels: Feature, Removal

#7106 Adds AI_Detect to Observer Data Huds
  code/modules/mob/dead/observer/observer.dm
Labels: Tweak, Server

#7055 Allow lollipops to be worn & bonus longpop
  code/modules/food_and_drinks/food/snacks_other.dm
  icons/mob/mask.dmi
  icons/obj/lollipop.dmi
Labels: Tweak, Feature, Sprites

#6674 [TM Ready] The return of single Z CorgStation
  README.md
  _maps/corgstation.json
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/shuttles/arrival_corg.dmm
  _maps/shuttles/exploration_corg.dmm
  _maps/shuttles/mining_kilo.dmm
Labels: Mapping, Needs Testmerge, Test Merged, Tweak, Feature, Fix

#7175 Fixes incursion radios
  code/modules/antagonists/incursion/incursion.dm
Labels: Fix

#6956 Second sweep of speedup chem nerfs
  code/modules/antagonists/changeling/powers/strained_muscles.dm
  code/modules/ninja/suit/suit.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/station_goals/dna_vault.dm
Labels: Balance/Rebalance

#6998 investigate logs for items to track who picked up and dropped it
  code/__DEFINES/logging.dm
  code/game/machinery/telecomms/machines/message_server.dm
  code/game/objects/items.dm
  code/game/objects/items/blueprints.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/devices/aicard.dm
  code/game/objects/items/devices/beacon.dm
  code/game/objects/items/tanks/jetpack.dm
  code/game/objects/items/teleportation.dm
  code/game/objects/objs.dm
  code/modules/admin/admin_investigate.dm
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/clothing/under/accessories.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/brain/posibrain.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/research/xenobiology/xenobiology.dm
Labels: Feature, Administration

#7170 Various Balloon alert improvements
  code/datums/chatmessage.dm
  code/game/atoms.dm
Labels: Tweak, Good PR

#7163 Fixes bug preventing shuttles from landing in the same custom location multiple times.
  code/modules/shuttle/super_cruise/shuttle_components/shuttle_docking.dm
Labels: Fix, Good PR

#7156 Players who suicide or cryo are not elegible for Antagonist roles for 5 minutes
  code/__HELPERS/game.dm
  code/controllers/configuration/entries/game_tweaks.dm
  code/modules/mob/dead/observer/observer.dm
  config/gameplay_tweaks.txt
Labels: Feature, Config Update, Good PR

#7193 Removes an unused Variable left by the mail PR
  code/controllers/subsystem/economy.dm
Labels: Removal

#7029 EMP nerfs
  code/game/objects/items/stunbaton.dm
  code/modules/projectiles/guns/energy.dm
Labels: Balance/Rebalance

#7183 Removes the ability to make romerol in virology
  code/datums/diseases/advance/symptoms/flesh_eating.dm
Labels: Removal

#7211 Fixes a typo on the explorer gun.
  code/modules/exploration_crew/exploration_laser_gun.dm
Labels: Fix

#7187 Fixes Blood Bolt Barrage
  code/modules/antagonists/cult/cult_items.dm
Labels: Fix

#7191 broken chameleon kit is purchasable to all agents
  code/modules/uplink/uplink_items.dm
Labels: Tweak, Balance/Rebalance

#7176 Votes display percentages, and map votes clearly state it's a chance.
  code/controllers/subsystem/vote.dm
Labels: Tweak

#7209 Making light floor/tiles breakable by lighteater
  code/game/turfs/open/floor/light_floor.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
Labels: Feature, Fix

#7201 Weld effects! (A port from /tg/ which was a port from Tau ceti)
  code/game/objects/items.dm
  code/game/objects/items/tools/weldingtool.dm
  code/modules/projectiles/guns/energy/special.dm
  icons/effects/welding_effect.dmi
Labels: Feature, Sprites

#7169 Adds a cooldown to Sentient Minebot notifications
  code/modules/mining/minebot.dm
Labels: Tweak, Server

#7225 Add health HUD / red vignette to simplemobs
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/elite.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
Labels: Feature

#7181 Amplification module key, Debug Encryption Key
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Feature, Refactor, Administration, Code Improvement

#7177 Mobs with Jaunt type movement can't Strip anymore
  code/datums/elements/strippable.dm
Labels: Tweak

#7119 Fixes chainsaws losing all force when dropped
  code/datums/components/twohanded.dm
Labels: Fix

#7212 Adds the batong, a toy version of security batons
  code/game/machinery/computer/arcade.dm
  code/game/machinery/recharger.dm
  code/game/objects/items/toys.dm
Labels: Feature

#7171 Virology fixes and whatnot
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Mapping, Tweak, Feature, Fix

#7167 Brain surgery term is now Brain Recalibration.
  beestation.dme
  code/__DEFINES/mobs.dm
  code/datums/brain_damage/mild.dm
  code/datums/brain_damage/severe.dm
  code/modules/surgery/brain_recalibration.dm
Labels: Tweak, Refactor, Needs Wiki Changes

#7233 Revert "Players who suicide or cryo are not elegible for Antagonist roles for 5 minutes"
  code/__HELPERS/game.dm
  code/controllers/configuration/entries/game_tweaks.dm
  code/modules/mob/dead/observer/observer.dm
  config/gameplay_tweaks.txt
Labels: Config Update, Removal

#7229 Vending machine stock display now uses product_path as key for retrieving stock
  code/modules/vending/_vending.dm
  tgui/packages/tgui/interfaces/Vending.js
Labels: Fix, TGUI-Changes

#7226 Fixes attack animations
  code/game/atoms_movable.dm
Labels: Fix

#7224 Rework AI Alerts menu to use browser popups instead of raw IE
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Tweak, Fix

#7230 Use defib HUD for changeling fakedeath
  code/game/data_huds.dm
Labels: Tweak

#7112 Hud icons are now based on ID card styles (+crew monitor, crew manifest are based on hud icons than job names + chameleon agent card QoL)
  code/__DEFINES/jobs.dm
  code/datums/datacore.dm
  code/game/data_huds.dm
  code/game/machinery/PDApainter.dm
  code/game/machinery/computer/card.dm
  code/game/machinery/computer/crew.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/clothing/chameleon.dm
  code/modules/crew_objectives/civilian_objectives.dm
  code/modules/economy/account.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/bartender.dm
  code/modules/jobs/job_types/botanist.dm
  code/modules/jobs/job_types/cook.dm
  code/modules/jobs/job_types/curator.dm
  code/modules/jobs/job_types/gimmick.dm
  code/modules/jobs/jobs.dm
  code/modules/modular_computers/file_system/programs/budgetordering.dm
  code/modules/modular_computers/file_system/programs/card.dm
  code/modules/modular_computers/file_system/programs/robocontrol.dm
  code/modules/vending/_vending.dm
  icons/mob/hud.dmi
  icons/obj/card.dmi
  tgui/packages/tgui/interfaces/CrewConsole.js
Labels: Tweak, Feature, Sprites, Refactor, Removal, Code Improvement, TGUI-Changes, Testmerge Passed, Good PR

#7234 Security level change is now handled by signals
  code/__DEFINES/dcs/signals.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/firealarm.dm
  code/modules/security_levels/security_levels.dm
  code/modules/shuttle/emergency.dm
Labels: Code Improvement, Good PR

#7242 Fix dank-pocket recipe having no category
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
Labels: Fix

#7254 ling fake-flesh id card hotfix that shows grey hud icon
  code/game/gamemodes/changeling/changeling.dm
  code/modules/antagonists/changeling/changeling.dm
Labels: Fix

#7231 Client color applies to items in inventory slots
  code/game/objects/items.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/inventory.dm
Labels: Tweak

#7262 Fixes a posibrain bug
  code/modules/mob/living/brain/posibrain.dm
Labels: Fix

#7271 Dead people don't get their mood changed.
  code/datums/components/mood.dm
Labels: Balance/Rebalance

#7263 Fix Corgium
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/spells/spell_types/shapeshift.dm
  icons/obj/chemical.dmi
Labels: Sprites

#7250 Give custom job their own chat color + better revenant chat color
  beestation.dme
  code/__DEFINES/jobs.dm
  code/__HELPERS/jobs.dm
  code/datums/chatmessage.dm
  code/game/say.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/atmospheric_technician.dm
  code/modules/jobs/job_types/bartender.dm
  code/modules/jobs/job_types/botanist.dm
  code/modules/jobs/job_types/brigphys.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/cargo_technician.dm
  code/modules/jobs/job_types/chaplain.dm
  code/modules/jobs/job_types/chemist.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/clown.dm
  code/modules/jobs/job_types/cook.dm
  code/modules/jobs/job_types/curator.dm
  code/modules/jobs/job_types/deputy.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/emt.dm
  code/modules/jobs/job_types/exploration_team.dm
  code/modules/jobs/job_types/geneticist.dm
  code/modules/jobs/job_types/gimmick.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/janitor.dm
  code/modules/jobs/job_types/lawyer.dm
  code/modules/jobs/job_types/medical_doctor.dm
  code/modules/jobs/job_types/mime.dm
  code/modules/jobs/job_types/quartermaster.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/jobs/job_types/scientist.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/shaft_miner.dm
  code/modules/jobs/job_types/station_engineer.dm
  code/modules/jobs/job_types/virologist.dm
  code/modules/jobs/job_types/warden.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: Tweak, Feature, Refactor, TGUI-Changes

#7279 fixes "Give custom job their own chat color + better revenant chat color (#7250)"
  code/datums/chatmessage.dm
  code/game/say.dm
Labels: Fix

#7241 Allow invisible mobs to hear speech in range
  code/modules/mob/living/say.dm
Labels: Fix

#7251 Adds a unit test to validate crafting categories
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/crafting_tests.dm
Labels: Code Improvement

#7258 Fixes botany equipment sprites
  icons/obj/hydroponics/equipment.dmi
Labels: Sprites, Fix

#7210 Tweaks the Glowshrooms sprite
  icons/obj/lighting.dmi
Labels: Feature, Sprites, Vote Passed

#7281 Lets biosuits hold large internal tanks
  code/modules/clothing/suits/bio.dm
Labels: Balance/Rebalance

#7270 New traitor uplink Badassery choice - Box of DonkCo. toys
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature, Code Improvement

#7248 Lag-proofing nightmares
  code/__DEFINES/mobs.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/items/holy_weapons.dm
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/spells/spell_types/shadow_walk.dm
Labels: Tweak, Feature, Fix, Balance/Rebalance, Code Improvement

#7296 Fixes changeling unknown grey hud
  code/modules/antagonists/changeling/changeling.dm
Labels: Fix

#7295 Fixes a fix I made regarding posibrains
  code/modules/mob/living/brain/posibrain.dm
Labels: Fix

#7299 Fix a subsystem priority sort
  code/controllers/master.dm
Labels: Port, Fix

#7253 PDA is now automatically updated when it takes a card / ghost role spawns now have proper HUDs, card names
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/objective_types/vip_extraction.dm
Labels: Tweak, Fix

#7267 No more Xray Malf AI metagame
  code/game/machinery/computer/camera.dm
Labels: Fix

#7197 [PORT]TGUI Sect menu (take 2)
  beestation.dme
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/misc.dm
  code/datums/components/religious_tool.dm
  code/modules/religion/religion_sects.dm
  code/modules/religion/rites.dm
  code/modules/tgui/states/never.dm
  tgui/packages/tgui/interfaces/ReligiousTool.js
Labels: Tweak, Feature, TGUI-Changes

#7304 New space ambience song "Drifting"
  code/_globalvars/lists/ambience.dm
  sound/ambience/qwerty/drifting.ogg
Labels: Feature, Sound

#7298 Fixes an issue with xeno infection HUDs
  code/modules/mob/living/carbon/alien/alien.dm
  code/modules/mob/living/carbon/alien/special/alien_embryo.dm
Labels: Fix

#7246 Latejoin window no longer shows improper "Command" category to Cargo/Civilian jobs
  code/modules/jobs/jobs.dm
  code/modules/mob/dead/new_player/new_player.dm
Labels: Fix

#7328 fixes TGUI 'Colored names' option for custom job colours + minor fix to PDA painter
  code/__HELPERS/jobs.dm
  tgui/packages/tgui-panel/chat/renderer.js
Labels: Fix, TGUI-Changes

#6885 Tweaks xeno chestbursting
  code/modules/mob/living/carbon/alien/special/alien_embryo.dm
Labels: Tweak

#6999 replaces the bartender objective responsibility with cocktail
  code/modules/crew_objectives/civilian_objectives.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
Labels: Tweak, Feature, Removal

#6993 [PORT] Ports new station goal: Bluespace mining tap from Paradise station
  beestation.dme
  code/modules/cargo/packs.dm
  code/modules/station_goals/bluespace_tap.dm
  icons/obj/machines/bluespace_tap.dmi
  tgui/packages/tgui/interfaces/BluespaceTap.js
Labels: Feature, Sprites, TGUI-Changes

#7147 Adds Necromatic Sect
  code/game/objects/effects/temporary_visuals/cult.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/religion/religion_sects.dm
  code/modules/religion/rites.dm
Labels: Feature, Server

#7148 Adds blood smearing onto objects and turfs
  code/datums/components/forensics.dm
  code/datums/elements/decals/blood.dm
  code/game/machinery/_machinery.dm
  code/modules/detectivework/detective_work.dm
Labels: Feature

#7172 Makes Brain Tumor quirk less harsh
  code/__DEFINES/traits.dm
  code/datums/mood_events/generic_positive_events.dm
  code/datums/traits/negative.dm
  code/game/objects/items/storage/firstaid.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/reagent_containers/pill.dm
Labels: Feature, Balance/Rebalance

#7336 RPG title to gimmick jobs, gimmick code refactor+give them a supervisor
  code/modules/jobs/job_types/gimmick.dm
Labels: Tweak, Refactor, Code Improvement

#7345 Lasso Fix
  code/datums/components/riding.dm
  code/game/objects/buckling.dm
  code/game/objects/items/carp_lasso.dm
  code/modules/mob/living/living.dm
  code/modules/uplink/uplink_items.dm
  icons/obj/carp_lasso.dmi
Labels: Sprites, Fix

#7348 Players cannot see runtimes during a round (OOC information revealed)
  code/modules/client/verbs/ooc.dm
Labels: Tweak

#7332 [TGUI] Upgrades terser to 5.14.2
  tgui/package.json
  tgui/yarn.lock
Labels: Needs Testmerge, Server, TGUI-Changes, Testmerge Passed

#7349 Replaces the door to Robotics with a glass version on Meta Station
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Mapping, Tweak

#7353 Fix buckling crew
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
Labels: Fix

#7346 Changelings can now use the Reviving Stasis in the Monkey Form
  code/modules/antagonists/changeling/powers/fakedeath.dm
Labels: Fix

#7335 [TG PORT] Gets our HoP console / ID console code up to date with TG
  code/game/machinery/computer/_computer.dm
  code/game/machinery/computer/apc_control.dm
  code/game/machinery/computer/card.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/computer/warrant.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/storage/wallets.dm
  code/modules/jobs/access.dm
  code/modules/mining/machine_redemption.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/mob.dm
  code/modules/modular_computers/computers/item/computer.dm
  code/modules/modular_computers/hardware/card_slot.dm
Labels: Tweak, Feature, Code Improvement

#6619 Removes airborne transmission from advanced diseases
  code/datums/diseases/_disease.dm
  code/datums/diseases/advance/advance.dm
  code/datums/diseases/advance/symptoms/cough.dm
  code/datums/diseases/advance/symptoms/fire.dm
  code/datums/diseases/advance/symptoms/pierrot.dm
  code/datums/diseases/advance/symptoms/sneeze.dm
Labels: Tweak, Balance/Rebalance, Removal, 🔑 Close Key (1/2)

#7355 Minor supercruise fixes and objective payout changes.
  code/modules/projectiles/projectile/special/vortex.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/loot/vortex_rifle.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/objective_types/alien_artifact.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/objective_types/assassination.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/objective_types/nuke_ruin.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/objective_types/recover_blackbox.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/generator_settings/generator_ratvar.dm
Labels: Tweak, Fix

#7392 Fixes player-panel not working, and corrects some job defines
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/hivemind/hivemind.dm
  code/modules/admin/player_panel.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/living/brain/MMI.dm
  code/modules/research/designs/mechfabricator_designs.dm
Labels: Mapping, Fix, Refactor, Administration, Tools

#7391 Fixes cargo cap flipping
  code/modules/clothing/head/soft_caps.dm
Labels: Fix

#7399 Fix duplicates in minimal runtimes and lag caused by it
  code/modules/error_handler/error_viewer.dm
Labels: Fix

#7363 Completely reworks the "Radio" uplink
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/radio.dm
  code/datums/components/uplink.dm
  code/datums/mind.dm
  code/game/communications.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/mob/living/say.dm
  html/antagtips/traitor.html
Labels: Tweak, Feature, Removal, Code Improvement

#7293 Revenants can phase in and out at will
  code/datums/elements/strippable.dm
  code/modules/antagonists/revenant/revenant.dm
  code/modules/antagonists/revenant/revenant_abilities.dm
  icons/mob/actions/actions_revenant.dmi
Labels: Feature, Sprites

#7333 Adjusts VV dropdown perms
  code/datums/datumvars.dm
  code/game/atoms.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/view_variables/mark_datum.dm
  code/modules/admin/view_variables/topic_basic.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/mob.dm
Labels: Administration

#7404 Now Cancel Buttons in the Create-antagonist verb work as intended
  code/modules/admin/topic.dm
Labels: Fix, Administration

#7383 adds the mothroach
  beestation.dme
  code/datums/components/crafting/recipes.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/modules/food_and_drinks/food/snacks/meat.dm
  code/modules/mob/living/simple_animal/friendly/mothroach.dm
  icons/mob/animal.dmi
  icons/mob/pets_held.dmi
  icons/mob/pets_held_lh.dmi
  icons/mob/pets_held_rh.dmi
  icons/obj/stack_objects.dmi
Labels: Feature, Sprites

#7185 fixes deadchat spam caused by viro + tweaks wizarditis teleport
  code/datums/diseases/advance/symptoms/pierrot.dm
  code/datums/diseases/advance/symptoms/wizarditis.dm
  code/datums/diseases/wizarditis.dm
  code/datums/helper_datums/teleport.dm
Labels: Tweak, Fix

#7118 His Grace / Romerol is only purchasable upon murderbone objective
  code/datums/components/uplink.dm
  code/datums/mind.dm
  code/game/gamemodes/objective.dm
  code/modules/uplink/uplink_items.dm
Labels: Tweak, Balance/Rebalance, Refactor

#7370 nerfs meme-induced lag
  code/datums/diseases/advance/symptoms/meme.dm
Labels: Tweak

#7398 (Re)moved the (accidental) MD spawn in Delta's Virology
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Mapping, Fix

#7366 Screwdriver Pen!
  code/_globalvars/lists/maintenance_loot.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/paperwork/pen.dm
  icons/obj/bureaucracy.dmi
Labels: Feature, Sprites

#7387 Cogscarabs no longer dodge bullets fired over them.
  code/modules/antagonists/clock_cult/mobs/cogscarab.dm
  code/modules/mob/living/living_defense.dm
  code/modules/projectiles/projectile.dm
Labels: Balance/Rebalance

#7081 [PORT] Refactor cult dagger rune drawing and null rod rune clearing into components + minor rune / blood magic tweaks [Ivniinvi PR recoup]
  beestation.dme
  code/__DEFINES/antagonists.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/shuttles.dm
  code/datums/action.dm
  code/datums/components/cult_ritual_item.dm
  code/datums/components/effect_remover.dm
  code/datums/shuttles.dm
  code/game/objects/effects/effects.dm
  code/game/objects/items/holy_weapons.dm
  code/game/objects/items/mop.dm
  code/game/objects/structures/girders.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/antagonists/cult/cult_structures.dm
  code/modules/antagonists/cult/ritual.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/antagonists/eldritch_cult/eldritch_effects.dm
Labels: Refactor

#7316 Adds a few new emotes
  code/modules/mob/living/emote.dm
Labels: Feature
