Repository BeeStation/BeeStation-Hornet, pull requests merged in 2022-08, with the labels that each got.

#7367 Adds inspect text for the title screen
  code/__DEFINES/configuration.dm
  code/game/turfs/closed/_closed.dm
  strings/splash.json
Labels: Feature

#7208 Some Minebot improvements and additions
  beestation.dme
  code/_onclick/hud/minebot.dm
  code/_onclick/hud/screen_objects.dm
  code/modules/mining/machine_vending.dm
  code/modules/mining/minebot.dm
  code/modules/mob/living/emote.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  icons/mob/aibots.dmi
Labels: Tweak, Feature, Sprites, Balance/Rebalance, Refactor, Code Improvement, Good PR

#7329 Morph TGUI & refactor + icon2base64 fixes from TG
  beestation.dme
  code/__HELPERS/icons.dm
  code/modules/antagonists/morph/morph.dm
  code/modules/antagonists/morph/morph_stomach.dm
  tgui/packages/tgui/interfaces/Morph.js
Labels: Tweak, Feature, Fix, Refactor, Removal, Code Improvement, TGUI-Changes

#6857 [PORT] The roundstart SM Crystal delamination now spawns anomalies across the station + New Anomalies + Anomaly Code improvements
  beestation.dme
  code/__DEFINES/research/anomalies.dm
  code/__DEFINES/traits.dm
  code/game/objects/effects/anomalies.dm
  code/modules/assembly/signaler.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/clothing/suits/reactive_armour.dm
  code/modules/events/anomaly.dm
  code/modules/events/anomaly_delimber.dm
  code/modules/events/anomaly_hallucination.dm
  code/modules/jobs/job_types/gimmick.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/power/supermatter/supermatter.dm
  code/modules/power/supermatter/supermatter_delamination.dm
  icons/effects/effects.dmi
  icons/obj/assemblies/new_assemblies.dmi
Labels: Feature, Sprites, Fix, Balance/Rebalance, Refactor, Removal

#7371 fixes an ancient viro exploit
  code/datums/diseases/advance/symptoms/heal.dm
Labels: Fix, Balance/Rebalance

#7428 Mesons properly protect you from SM hallucinations again
  code/modules/power/supermatter/supermatter.dm
Labels: Fix

#7445 Fixes Cognac Description
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Labels: Tweak

#7442 Cluwne rune can no longer be scribed by cultist
  code/game/objects/effects/mainttraps.dm
Labels: Fix

#7437 More Logging - Cigarette reagents and explosions
  code/game/objects/items/cigs_lighters.dm
Labels: Administration

#7453 Fixes logging whoops
  code/game/objects/items/cigs_lighters.dm
Labels: Fix

#7461 Fixes fail2topic IP banning
  code/controllers/subsystem/fail2topic.dm
Labels: Fix

#7462 Rework hearing for INVISIBILITY_MAXIMUM mobs
  code/__DEFINES/sight.dm
  code/datums/brain_damage/imaginary_friend.dm
  code/game/objects/items/robot/ai_upgrades.dm
  code/game/say.dm
  code/modules/antagonists/traitor/equipment/Malf_Modules.dm
  code/modules/instruments/songs/_song.dm
  code/modules/mob/camera/camera.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/mob/mob.dm
Labels: Fix, Code Improvement

#7422 Staff of Change improvements with silicons and message to prevent self-antag
  code/modules/projectiles/projectile/magic.dm
Labels: Feature, Fix

#7452 Refactor and small fix for the cyborg power connector
  code/game/objects/items/robot/robot_items.dm
Labels: Feature, Fix, Refactor, Code Improvement

#7318 [TG PORT] New titanium tile sprite and titanium tile reskinning
  beestation.dme
  code/_onclick/hud/radial.dm
  code/game/objects/items/stacks/tiles/tile_mineral.dm
  code/game/objects/items/stacks/tiles/tile_reskinning.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/turfs/open/floor.dm
  code/game/turfs/open/floor/mineral_floor.dm
  code/game/turfs/open/floor/misc_floor.dm
  code/game/turfs/open/floor/plasteel_floor.dm
  icons/obj/tiles.dmi
  icons/turf/floors.dmi
Labels: Feature, Sprites, Code Improvement

#7435 Makes Thermal Vision (the mutation) no longer obtainable
  code/datums/mutations/sight.dm
Labels: Balance/Rebalance

#7429 Tweaks Xenomorph embryo growth times
  code/modules/mob/living/carbon/alien/special/alien_embryo.dm
Labels: Balance/Rebalance

#7425 Nostalgic & Atmos Winter Coats in Shop
  code/modules/client/loadout/loadout_suit.dm
Labels: Feature

#7421 nerfs pituitary disruption's disruption
  code/datums/diseases/advance/symptoms/heal.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/effects/spawners/mailspawner.dm
Labels: Tweak, Balance/Rebalance, Removal

#7412 Makes the transfer valve and signaler logging a little more robust, also makes it tgui.
  code/game/objects/items/devices/PDA/radio.dm
  code/game/objects/items/devices/transfer_valve.dm
  code/modules/assembly/signaler.dm
Labels: Feature

#7466 Updates fail2topic logging
  code/controllers/subsystem/fail2topic.dm
Labels: Server

#7104 The Great Radio Rework: NTNET Part 1 of many. - second try
  beestation.dme
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/networks.dm
  code/controllers/subsystem/air.dm
  code/controllers/subsystem/atoms.dm
  code/controllers/subsystem/machines.dm
  code/controllers/subsystem/processing/networks.dm
  code/datums/components/ntnet_interface.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas.dm
  code/game/area/areas/away_content.dm
  code/game/area/areas/centcom.dm
  code/game/area/areas/holodeck.dm
  code/game/machinery/airlock_control.dm
  code/game/machinery/computer/atmos_control.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/machinery/embedded_controller/airlock_controller.dm
  code/game/objects/items/control_wand.dm
  code/game/objects/objs.dm
  code/modules/NTNet/netdata.dm
  code/modules/NTNet/network.dm
  code/modules/NTNet/relays.dm
  code/modules/NTNet/services/_service.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/atmospherics/machinery/other/meter.dm
  code/modules/jobs/access.dm
  code/modules/mapping/map_template.dm
  code/modules/mob/living/simple_animal/bot/mulebot.dm
  code/modules/modular_computers/computers/item/computer.dm
  code/modules/modular_computers/file_system/programs/antagonist/dos.dm
  code/modules/modular_computers/file_system/programs/ntmonitor.dm
  code/modules/modular_computers/hardware/network_card.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/ntnetwork_tests.dm
Labels: Needs Testmerge, Feature, Code Improvement

#7331 Reduces the amount of money cargo gets for coffins
  code/modules/cargo/exports/large_objects.dm
Labels: Tweak

#7439 Changelings can now use augmented eyesight as monkeys
  code/modules/antagonists/changeling/powers/augmented_eyesight.dm
  code/modules/mob/transform_procs.dm
Labels: Tweak

#7438 Modern Dynamic
  beestation.dme
  code/__DEFINES/dynamic.dm
  code/__HELPERS/roundend.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_hijacking.dm
  code/game/gamemodes/dynamic/dynamic_midround_rolling.dm
  code/game/gamemodes/dynamic/dynamic_rulesets.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/dynamic/dynamic_unfavorable_situation.dm
  code/game/gamemodes/dynamic/readme.md
  code/game/gamemodes/dynamic/ruleset_picking.dm
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/antagonists/ashwalker/ashwalker.dm
  code/modules/antagonists/brainwashing/brainwashing.dm
  code/modules/antagonists/creep/creep.dm
  code/modules/antagonists/ert/ert.dm
  code/modules/antagonists/fugitive/fugitive.dm
  code/modules/antagonists/fugitive/hunter.dm
  code/modules/antagonists/greentext/greentext.dm
  code/modules/antagonists/highlander/highlander.dm
  code/modules/antagonists/revolution/revolution.dm
  code/modules/antagonists/valentines/valentine.dm
  code/modules/events/operative.dm
  code/modules/events/pirates.dm
  code/modules/mob/mob_lists.dm
  code/modules/unit_tests/dynamic_ruleset_sanity.dm
Labels: Test Merged, Feature, Fix, Balance/Rebalance, Server

#7319 [TG PORT] Improved decal painters, new tile sprayers + QoL
  code/_globalvars/lists/maintenance_loot.dm
  code/game/objects/items/airlock_painter.dm
  code/game/objects/items/storage/belt.dm
  code/modules/paperwork/photocopier.dm
  code/modules/research/designs/autolathe_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/objects.dmi
  tgui/docs/component-reference.md
  tgui/packages/tgui/components/Button.js
  tgui/packages/tgui/interfaces/DecalPainter.js
  tgui/packages/tgui/interfaces/DecalPainter.tsx
  tgui/packages/tgui/styles/components/Button.scss
Labels: Tweak, Feature, Sprites, Code Improvement, TGUI-Changes

#7473 [S]Protects Fail2Topic config from admin edits
  code/controllers/configuration/entries/general.dm
Labels: Config Update

#7433 [PORT] Improves Chat Highlighting + Messages by yourself no longer highlight
  code/__HELPERS/mobs.dm
  code/modules/mob/dead/observer/say.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob.dm
  tgui/packages/tgui-panel/chat/middleware.js
  tgui/packages/tgui-panel/chat/renderer.js
  tgui/packages/tgui-panel/settings/SettingsPanel.js
  tgui/packages/tgui-panel/settings/reducer.js
Labels: Tweak, Feature, Fix, TGUI-Changes

#7338 [TG PORT] Gets our Modular PCs (mostly) up to date with TG + small runtime fix
  beestation.dme
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/machines.dm
  code/game/machinery/recharger.dm
  code/modules/jobs/job_types/atmospheric_technician.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/modular_computers/computers/_modular_computer_shared.dm
  code/modules/modular_computers/computers/item/computer.dm
  code/modules/modular_computers/computers/item/computer_components.dm
  code/modules/modular_computers/computers/item/computer_ui.dm
  code/modules/modular_computers/computers/item/laptop.dm
  code/modules/modular_computers/computers/item/processor.dm
  code/modules/modular_computers/computers/item/tablet.dm
  code/modules/modular_computers/computers/item/tablet_presets.dm
  code/modules/modular_computers/computers/machinery/console_presets.dm
  code/modules/modular_computers/computers/machinery/modular_computer.dm
  code/modules/modular_computers/file_system/program.dm
  code/modules/modular_computers/file_system/program_events.dm
  code/modules/modular_computers/file_system/programs/airestorer.dm
  code/modules/modular_computers/file_system/programs/alarm.dm
  code/modules/modular_computers/file_system/programs/antagonist/contract_uplink.dm
  code/modules/modular_computers/file_system/programs/antagonist/dos.dm
  code/modules/modular_computers/file_system/programs/antagonist/revelation.dm
  code/modules/modular_computers/file_system/programs/arcade.dm
  code/modules/modular_computers/file_system/programs/atmosscan.dm
  code/modules/modular_computers/file_system/programs/borg_monitor.dm
  code/modules/modular_computers/file_system/programs/budgetordering.dm
  code/modules/modular_computers/file_system/programs/card.dm
  code/modules/modular_computers/file_system/programs/cargobounty.dm
  code/modules/modular_computers/file_system/programs/configurator.dm
  code/modules/modular_computers/file_system/programs/crewmanifest.dm
  code/modules/modular_computers/file_system/programs/file_browser.dm
  code/modules/modular_computers/file_system/programs/jobmanagement.dm
  code/modules/modular_computers/file_system/programs/ntdownloader.dm
  code/modules/modular_computers/file_system/programs/ntmonitor.dm
  code/modules/modular_computers/file_system/programs/ntnrc_client.dm
  code/modules/modular_computers/file_system/programs/portrait_printer.dm
  code/modules/modular_computers/file_system/programs/powermonitor.dm
  code/modules/modular_computers/file_system/programs/radar.dm
  code/modules/modular_computers/file_system/programs/robocontrol.dm
  code/modules/modular_computers/file_system/programs/secureye.dm
  code/modules/modular_computers/file_system/programs/sm_monitor.dm
  code/modules/modular_computers/hardware/_hardware.dm
  code/modules/modular_computers/hardware/ai_slot.dm
  code/modules/modular_computers/hardware/battery_module.dm
  code/modules/modular_computers/hardware/card_slot.dm
  code/modules/modular_computers/hardware/portable_disk.dm
  code/modules/modular_computers/hardware/printer.dm
  code/modules/modular_computers/hardware/sensor_package.dm
  code/modules/modular_computers/laptop_vendor.dm
  code/modules/power/supermatter/supermatter.dm
  code/modules/research/designs/computer_part_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/vending/modularpc.dm
  tgui/packages/tgui/interfaces/ComputerFabricator.js
  tgui/packages/tgui/interfaces/NtosFileManager.js
  tgui/packages/tgui/interfaces/NtosMain.js
  tgui/packages/tgui/interfaces/NtosNetDownloader.js
Labels: Tweak, Feature, Fix, Balance/Rebalance, Refactor, Removal, Code Improvement, TGUI-Changes

#7469 Makes the atmospherics beret obtainable from the AtmosDrobe vendor
  code/modules/vending/wardrobes.dm
Labels: Tweak

#7490 Fix tablet flashlight incorrectly starting on
  code/modules/modular_computers/computers/item/computer.dm
Labels: Fix

#7477 Adds a cancel button to the play cinematic menu
  code/modules/admin/verbs/cinematic.dm
Labels: Tweak, Feature, Administration

#7471 [PORT] runtime fix for nulled forensic component runtime
  code/modules/detectivework/detective_work.dm
Labels: Fix

#7385 Removes xray camera upgrades
  code/game/machinery/camera/camera.dm
  code/game/machinery/camera/camera_assembly.dm
  code/game/machinery/camera/presets.dm
Labels: Balance/Rebalance

#7488 Intern announcer no longer blocks shuttle call reason
  code/modules/shuttle/emergency.dm
Labels: Tweak

#7460 New Cargo Crate - Mothroach
  code/modules/cargo/packs.dm
Labels: Feature

#7470 Lets the carp lasso tame dolphins
  code/game/objects/items/carp_lasso.dm
Labels: Feature

#7410 Engineering Once Again Gets Generic Circuit Imprinters
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/research/machinery/departmental_circuit_imprinter.dm
Labels: Mapping, Tweak

#7494 Gas synthesis gives discovery research
  code/modules/atmospherics/gasmixtures/reactions.dm
Labels: Tweak

#7486 reverted scrubber/vent names
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
Labels: Tweak

#7511 Atmos machines properly initialize when loaded from a map not at round start.
  code/controllers/subsystem/air.dm
Labels: Fix

#7509 Changelings can now open their disguise's mail
  code/game/objects/items/mail.dm
Labels: Feature

#7499 Finally fixes the Social Anxiety quirk (and adds mood change!)
  code/datums/mood_events/generic_negative_events.dm
  code/datums/traits/negative.dm
Labels: Feature, Balance/Rebalance

#7525 Mods can no longer use the supplypod menu
  code/modules/admin/admin_verbs.dm
  code/modules/cargo/centcom_podlauncher.dm
Labels: Administration

#7529 Revises a few delimber anomaly features
  code/game/objects/effects/anomalies.dm
  code/modules/clothing/suits/reactive_armour.dm
  code/modules/events/anomaly_delimber.dm
Labels: Balance/Rebalance, Removal

#7527 Corg Bureacracy Update (+ Robo Ghost Sniffer)
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: Mapping, Tweak, Feature, Removal

#7535 Fixes alien plasma transfer
  code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
Labels: Fix

#7487 adds various scarfs to the ooc store
  code/modules/client/loadout/loadout_accessories.dm
Labels: Mapping, Feature

#7534 Lets silicons speak apid
  code/modules/language/language_holder.dm
Labels: Tweak

#7485 adds description to air scrubber and pump
  code/modules/atmospherics/machinery/portable/pump.dm
  code/modules/atmospherics/machinery/portable/scrubber.dm
Labels: Tweak

#7532 Getting batonned makes you shake and stutter
  code/game/objects/items/stunbaton.dm
Labels: Feature

#7037 Fixes alt click not opening labcoat's inventory
  code/__DEFINES/dcs/signals.dm
  code/datums/ai/dog/dog_controller.dm
  code/datums/components/gps.dm
  code/datums/components/rotation.dm
  code/datums/components/storage/storage.dm
  code/modules/clothing/suits/toggles.dm
  code/modules/wiremod/shell/controller.dm
Labels: Tweak

#7513 Cult Resprite by Naevi
  beestation.dme
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/inhands/equipment/shields_lefthand.dmi
  icons/mob/inhands/equipment/shields_righthand.dmi
  icons/mob/inhands/weapons/polearms_lefthand.dmi
  icons/mob/inhands/weapons/polearms_righthand.dmi
  icons/mob/inhands/weapons/swords_lefthand.dmi
  icons/mob/inhands/weapons/swords_righthand.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/cult.dmi
  icons/obj/items_and_weapons.dmi
  icons/obj/kitchen.dmi
  icons/obj/shields.dmi
  icons/obj/wizard.dmi
Labels: Tweak, Sprites, Needs Wiki Changes

#7264 Adds Depleted Uranium Windows - For Rad-proofing areas
  code/__DEFINES/radiation.dm
  code/game/objects/effects/spawners/structure.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/structures/window.dm
  icons/obj/smooth_structures/du_window.dmi
  icons/obj/structures.dmi
  icons/obj/structures_spawners.dmi
Labels: Feature, Sprites

#7285 Brings our MC up to date with TG
  beestation.dme
  code/__DEFINES/MC.dm
  code/__DEFINES/_tick.dm
  code/controllers/admin.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/failsafe.dm
  code/controllers/globals.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/controllers/subsystem/augury.dm
  code/controllers/subsystem/blackbox.dm
  code/controllers/subsystem/disease.dm
  code/controllers/subsystem/garbage.dm
  code/controllers/subsystem/input.dm
  code/controllers/subsystem/metrics.dm
  code/controllers/subsystem/nightshift.dm
  code/controllers/subsystem/profiler.dm
  code/controllers/subsystem/server_maint.dm
  code/controllers/subsystem/shuttle.dm
  code/controllers/subsystem/stat.dm
  code/controllers/subsystem/sun.dm
  code/controllers/subsystem/time_track.dm
  code/controllers/subsystem/title.dm
  code/datums/helper_datums/stack_end_detector.dm
  code/datums/weather/weather.dm
  code/game/objects/structures/traps.dm
  code/game/world.dm
  code/modules/admin/view_variables/reference_tracking.dm
  code/modules/power/lighting.dm
  code/modules/tgchat/to_chat.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/subsystem_metric_sanity.dm
  config/config.txt
Labels: THIS IS VERY IMPORTANT, Fix, Config Update, Administration, Code Improvement, Testmerge Passed

#7566 Actually removes xray camera upgrade
  code/game/machinery/camera/camera.dm
Labels: Tweak

#7565 Removes a loose white pixel from the Virologist action toy
  icons/obj/toy.dmi
Labels: Sprites, Fix

#7548 More minor text fixes
  code/game/objects/items/devices/scanners.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
Labels: Grammar and Formatting

#7539 fixes Salicyclic Acid's overdose, updates the description of Salicyclic Acid and Oxandrolone
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Feature, Removal

#7520 Setting for self highlighting in chat
  tgui/packages/tgui-panel/chat/middleware.js
  tgui/packages/tgui-panel/chat/renderer.js
  tgui/packages/tgui-panel/settings/SettingsPanel.js
  tgui/packages/tgui-panel/settings/reducer.js
Labels: Feature, TGUI-Changes

#7491 [Port of a port] Better melee attack animations
  code/game/atoms_movable.dm
Labels: Feature, 🔑 Close Key (1/2)

#7495 IPC loses ability to talk with no tongue/voicebox
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/IPC.dm
Labels: Tweak, Fix

#6967 Updates optical ecto-scanners
  code/datums/components/team_monitor.dm
  code/modules/clothing/glasses/_glasses.dm
Labels: Tweak, Fix

#7553 Transparent PDA colorizer for the BeeCoin store
  beestation.dme
  code/game/objects/items/colorizers/colorizer.dm
  code/game/objects/items/colorizers/items.dm
  code/modules/client/loadout/loadout_colorizers.dm
Labels: Feature

#7555 Moves the code for the "give" action to the proper file
  code/datums/status_effects/neutral.dm
  code/datums/traits/neutral.dm
Labels: Fix, Code Improvement

#7326 Gun Dryness: Energy gunfire sound pitch now varies based on how much ammo is left. Also guns now have bolt sounds for low ammo. [PORT]
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/magic.dm
  sound/weapons/effects/ballistic_click.ogg
  sound/weapons/effects/energy_click.ogg
Labels: Feature, Sound

#7557 ID debug vv
  code/__DEFINES/vv.dm
  code/game/objects/items/cards_ids.dm
Labels: Administration

#7505 Mind-to-mind communication now capitalizes and punctuates
  code/game/gamemodes/clock_cult/clockcult.dm
  code/game/machinery/computer/prisoner/management.dm
  code/game/objects/items/implants/implant_bb.dm
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/antagonists/blob/blob_mobs.dm
  code/modules/antagonists/blob/overmind.dm
  code/modules/antagonists/cult/cult_comms.dm
  code/modules/antagonists/eldritch_cult/eldritch_magic.dm
  code/modules/antagonists/revenant/revenant.dm
  code/modules/guardian/guardian.dm
  code/modules/mob/living/brain/say.dm
  code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
  code/modules/mob/living/carbon/alien/say.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/simple_animal/guardian/guardian.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/spells/spell_types/hivemind.dm
  code/modules/spells/spell_types/personality_commune.dm
  code/modules/spells/spell_types/telepathy.dm
Labels: Tweak

#7420 Heads can send messages to CentCom during Red Alert
  code/game/machinery/computer/communications.dm
  tgui/packages/tgui/interfaces/CommunicationsConsole.js
Labels: Tweak, TGUI-Changes

#7574 You can't slap tables at a distance or through cams anymore
  code/game/objects/items/weaponry.dm
Labels: Fix

#7569 Adds more emojis
  icons/emoji.dmi
Labels: Feature, Sprites, Fix

#7585 Adds round date to the issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: GitHub

#7507 Adds a new, sick way to unmount a skateboar
  code/modules/vehicles/scooter.dm
  code/modules/vehicles/vehicle_actions.dm
Labels: Feature

#7381 Change chat colour of custom command
  code/__DEFINES/jobs.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: Tweak, TGUI-Changes

#7449 Adds Pingles, a chefmade variety of chips
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  icons/obj/food/food.dmi
Labels: Feature, Sprites

#7354 Gives wizards pierce protection on their standard robes.
  code/modules/clothing/suits/wiz_robe.dm
Labels: Balance/Rebalance

#7467 A couple minebot tweaks
  code/modules/mining/minebot.dm
  code/modules/mob/living/silicon/robot/emote.dm
Labels: Tweak, Fix, Balance/Rebalance
