Repository BeeStation/BeeStation-Hornet, pull requests merged in 2022-04, with the labels that each got.

#6029 Adds 2 new bundles for Curator Beacon - Sword Saint and Carp Hunter
  code/controllers/subsystem/traumas.dm
  code/game/objects/items/kitchen.dm
  code/game/objects/items/miscellaneous.dm
  code/game/objects/items/religion.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/under/costume.dm
  icons/mob/clothing/uniform.dmi
  icons/mob/inhands/equipment/kitchen_lefthand.dmi
  icons/mob/inhands/equipment/kitchen_righthand.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/kitchen.dmi
Labels: Feature, Sprites

#6541 Make energy bola catchable again
  code/game/objects/items/handcuffs.dm
Labels: Fix

#6605 Fixes decal painter can paint walls
  code/game/objects/items/airlock_painter.dm
Labels: Fix

#6593 Adds a plushy crate
  code/modules/cargo/packs.dm
Labels: Feature

#6568 Improved Immovable Rod Targeting
  code/game/gamemodes/meteor/meteors.dm
  code/modules/events/immovable_rod.dm
Labels: Tweak

#6542 Adds medical departmental medals
  code/game/objects/items/storage/lockbox.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/clothing/under/accessories.dm
  icons/mob/accessories.dmi
  icons/obj/clothing/accessories.dmi
Labels: Feature, Sprites

#6463 small blob spore fix
  code/modules/antagonists/blob/blob_mobs.dm
  code/modules/antagonists/blob/powers.dm
Labels: Tweak, Fix

#6608 Fixes antag pick failures
  code/controllers/subsystem/ticker.dm
  code/game/gamemodes/game_mode.dm
Labels: Fix

#6602 Battle Royale fixes
  code/modules/admin/battle_royale.dm
  code/modules/mob/living/brain/posibrain.dm
Labels: Fix, Administration

#6520 Makes deaf people unable to be sound-stunned
  code/modules/mob/living/carbon/carbon_defense.dm
Labels: Balance/Rebalance

#6599 Makes local testing less CBT
  code/_debugger.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
Labels: Feature, Fix, Server

#6613 meclizine typo fix
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Fix

#6567 Chaplains arrive with their nullrod + armor beacon + smoke spell book
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/_globalvars/religion.dm
  code/game/objects/items/holy_weapons.dm
  code/modules/jobs/job_types/chaplain.dm
  code/modules/vending/wardrobes.dm
Labels: Mapping, Tweak, Fix, Removal

#6616 Fixes being able to bypass the IC spam filter by spamming emotes
  code/modules/mob/living/say.dm
Labels: Fix

#6606 Removes Soporific Slugs
  code/modules/projectiles/ammunition/ballistic/shotgun.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
  code/modules/research/designs/weapon_designs.dm
Labels: Fix, Balance/Rebalance, i ded

#6618 Adds config ability to disable cross server bans
  code/controllers/configuration/entries/general.dm
  code/modules/admin/sql_ban_system.dm
  config/game_options.txt
Labels: Feature, Config Update, Administration, Server

#6260 Custom shuttles can be editted after designation and other shuttle designator changes.
  code/__HELPERS/type2type.dm
  code/modules/shuttle/bluespace_shuttle_pod/pod_computer.dm
  code/modules/shuttle/bluespace_shuttle_pod/shuttle_capsule.dm
  code/modules/shuttle/custom_shuttle.dm
  code/modules/shuttle/shuttle.dm
  code/modules/shuttle/shuttle_creation/shuttle_creator.dm
  code/modules/shuttle/shuttle_creation/shuttle_creator_actions.dm
  code/modules/shuttle/shuttle_creation/shuttle_creator_console.dm
  code/modules/shuttle/shuttle_creation/shuttle_creator_overlay.dm
  code/modules/shuttle/super_cruise/shuttle_components/shuttle_docking.dm
  icons/mob/actions/actions_shuttle.dmi
  tgui/packages/tgui/interfaces/OrbitalMap.js
  tgui/packages/tgui/interfaces/ShuttleDesignator.js
Labels: Needs Testmerge, Tweak, Feature, Sprites, Fix, TGUI-Changes

#6638 Makes overriding signals more clear as to what is being overriden.
  code/datums/components/_component.dm
Labels: Code Improvement

#6634 Mr. Freeze gets no slip boots.
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/clothing/shoes/miscellaneous.dm
Labels: Balance/Rebalance

#6640 Fixes ninja suit terminate() proc not being called on ninja's death.
  code/modules/ninja/suit/suit.dm
Labels: Fix, Removal

#6639 Fixes monkey AI behaviour disposal runtime
  code/datums/ai/monkey/monkey_subtrees.dm
Labels: Fix

#6637 Fixes wormhole runtimes
  code/modules/events/wormholes.dm
Labels: Fix

#6636 Fixes a potential runtime in zclear
  code/controllers/subsystem/zclear.dm
Labels: Fix

#6635 Fix: Fixes xenobiology camera checking area for flags instead of area.area_flags
  code/modules/research/xenobiology/xenobio_camera.dm
Labels: Fix

#6564 Fixes Hellbound
  code/datums/diseases/advance/symptoms/necropolis.dm
  code/datums/mind.dm
  code/game/machinery/cloning.dm
  code/game/machinery/computer/cloning.dm
  code/game/objects/items/defib.dm
  code/game/objects/structures/morgue.dm
  code/modules/awaymissions/mission_code/Academy.dm
  code/modules/hydroponics/grown/replicapod.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/transform_procs.dm
  code/modules/paperwork/contract.dm
  code/modules/projectiles/projectile/magic.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/research/nanites/nanite_programs/healing.dm
  code/modules/surgery/advanced/revival.dm
  code/modules/surgery/bodyparts/bodyparts.dm
Labels: Fix

#6477 Removes the backsurge event, but keeps the beer nuke
  beestation.dme
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
  code/modules/events/beer_clog.dm
  code/modules/events/vent_clog.dm
Labels: Removal

#6531 Kilo Quick Fix #5
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Mapping, Feature, Fix, Needs Pictures

#6620 fixes extrapolators again
  code/game/objects/items/devices/scanners.dm
Labels: Fix

#6621 Stealth Mode announces your stealth CKEY to other admins
  code/modules/admin/admin_verbs.dm
Labels: Administration

#6549 Crewmonitor fixes and refactors
  code/game/machinery/computer/crew.dm
  tgui/packages/tgui/interfaces/CrewConsole.js
Labels: Fix, Refactor, Code Improvement, TGUI-Changes

#6530 [PORT] Rust Improvements
  beestation.dme
  code/__DEFINES/tools.dm
  code/__DEFINES/traits.dm
  code/datums/elements/rust.dm
  code/game/objects/items/debug_items.dm
  code/game/objects/items/tools/wirebrush.dm
  code/game/turfs/closed/wall/misc_walls.dm
  code/game/turfs/closed/wall/reinf_walls.dm
  code/game/turfs/closed/walls.dm
  code/game/turfs/open/chasm.dm
  code/game/turfs/open/floor/misc_floor.dm
  code/game/turfs/open/floor/plasteel_floor.dm
  code/game/turfs/open/floor/plating.dm
  code/game/turfs/open/lava.dm
  code/game/turfs/open/openspace.dm
  code/game/turfs/open/space/space.dm
  code/game/turfs/turf.dm
  code/modules/antagonists/revenant/revenant_abilities.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/research/designs/tool_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/effects/rust_overlay.dmi
  icons/obj/tools.dmi
Labels: Feature, Sprites, Code Improvement

#6534 fixes a few wing bugs
  code/modules/surgery/organs/wings.dm
Labels: Fix

#6516 Small fix
  code/modules/research/xenobiology/crossbreeding/_status_effects.dm
Labels: Removal, Code Improvement

#6536 [PORT] Split personality communication
  beestation.dme
  code/datums/brain_damage/split_personality.dm
  code/modules/spells/spell_types/personality_commune.dm
Labels: Feature

#6400 PubbyStation Atmosia changes [First PR]
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Mapping, Tweak, Fix

#6356 Fixes a lot of create_and_destroy runtimes
  code/_onclick/hud/hud.dm
  code/_onclick/hud/plane_master_controller.dm
  code/controllers/subsystem/throwing.dm
  code/datums/action.dm
  code/datums/brain_damage/imaginary_friend.dm
  code/datums/components/_component.dm
  code/datums/components/orbiter.dm
  code/datums/dna.dm
  code/datums/forced_movement.dm
  code/datums/progressbar.dm
  code/game/gamemodes/meteor/meteors.dm
  code/game/machinery/launch_pad.dm
  code/game/machinery/navbeacon.dm
  code/game/machinery/teleporter.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/effects/proximity.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/chameleonproj.dm
  code/game/objects/items/devices/forcefieldprojector.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/admin/poll_management.dm
  code/modules/antagonists/clock_cult/ratvarian_cyborg_modules.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/buildmode/buildmode.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/guardian/abilities/minor/teleport.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/simple_animal/bot/ed209bot.dm
  code/modules/paperwork/contract.dm
  code/modules/power/apc.dm
  code/modules/power/singularity/containment_field.dm
  code/modules/projectiles/guns/energy/dueling.dm
  code/modules/projectiles/guns/magic.dm
  code/modules/projectiles/projectile/special/curse.dm
  code/modules/projectiles/projectile/special/gravity.dm
  code/modules/projectiles/projectile/special/hallucination.dm
  code/modules/shuttle/bluespace_shuttle_pod/pod_computer.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/loot/alien_artifact.dm
  code/modules/unit_tests/create_and_destroy.dm
Labels: Fix, Administration, Removal

#6121 Cult bolas no longer affect holy-proof individuals.
  code/modules/antagonists/cult/cult_items.dm
Labels: Balance/Rebalance

#6335 Random Name refactor
  code/__HELPERS/mobs.dm
  code/__HELPERS/names.dm
  code/datums/brain_damage/imaginary_friend.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/security.dm
  code/game/objects/items/cardboard_cutouts.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/IPC.dm
  code/modules/mob/living/carbon/human/species_types/apid.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/mob/living/carbon/human/species_types/oozelings.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/mob_helpers.dm
Labels: Refactor, Code Improvement

#6626 Intelligence potions don't bypass ghost role spawners flag
  code/modules/research/xenobiology/xenobiology.dm
Labels: Fix

#6624 Fixes LOWMEMORYMODE runtimes
  code/controllers/subsystem/mapping.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/space_station.dm
Labels: Fix

#6630 virus food no longer improves non-virus virus speed
  code/modules/reagents/chemistry/reagents/food_reagents.dm
Labels: Tweak

#6657 Welded firelocks can no longer be opened by IDs
  code/game/machinery/doors/firedoor.dm
Labels: Fix

#6610 Fixes fireman carry bug
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/mob.dm
Labels: Fix

#6659 You drop your items on death in battle royale, drop items on death trait
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/modules/admin/battle_royale.dm
  code/modules/mob/living/carbon/human/death.dm
Labels: Feature, Administration

#6668 Closets will no longer attempt to abduct effects
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Fix

#6672 Kilo Quick Fix #6
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Mapping

#6656 [Mappers QoL] New icons for zones and items ported from /tg/
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas/centcom.dm
  code/game/area/areas/holodeck.dm
  code/game/objects/effects/spawners/lootdrop.dm
  icons/effects/landmarks_spawners.dmi
  icons/effects/landmarks_static.dmi
  icons/turf/areas.dmi
Labels: Feature, Sprites

#6677 Necromantic Stone is now logged
  code/modules/antagonists/wizard/equipment/artefact.dm
Labels: Administration

#6598 Makes ectoscopic sniffer more obvious, plus fix
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/machinery/ecto_sniffer.dm
Labels: Mapping, Feature, Fix

#6475 Slows nuka cola and meth down
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Balance/Rebalance

#6507 Refactor/documentation on various headwear
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  _maps/RandomRuins/SpaceRuins/bigderelict1.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  code/datums/action.dm
  code/game/objects/items.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/cargo/packs.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/head/_head.dm
  code/modules/clothing/head/beanie.dm
  code/modules/clothing/head/collectable.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/head/soft_caps.dm
  code/modules/jobs/job_types/cook.dm
  code/modules/ninja/suit/head.dm
  code/modules/vending/wardrobes.dm
  icons/mob/clothing/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Mapping, Feature, Sprites, Fix, Refactor, Removal, Code Improvement

#6679 Fixes a spelling mistake
  code/modules/shuttle/super_cruise/orbital_poi_generator/_orbital_objective.dm
Labels: THIS IS VERY IMPORTANT, Grammar and Formatting

#6683 Fixes wooden walls
  code/game/machinery/deployable.dm
Labels: Fix

#6645 Fixes crew monitors and implements global suit sensors list
  code/__DEFINES/misc.dm
  code/__DEFINES/traits.dm
  code/_globalvars/lists/mobs.dm
  code/game/machinery/computer/crew.dm
  code/modules/awaymissions/corpse.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/under/_under.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/research/nanites/nanite_programs/utility.dm
Labels: Feature, Fix

#6123 Magical / Holy EMP + explosions are protected by anti-magic
  code/controllers/subsystem/explosion.dm
  code/datums/diseases/rhumba_beat.dm
  code/datums/mutations/actions.dm
  code/game/objects/empulse.dm
  code/game/objects/items/granters.dm
  code/game/objects/items/plushes.dm
  code/modules/antagonists/clock_cult/items/clockwork_weapon.dm
  code/modules/antagonists/clock_cult/scriptures/sigil_of_vitality.dm
  code/modules/antagonists/clock_cult/structure/clockwork_sigil.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/antagonists/eldritch_cult/eldritch_magic.dm
  code/modules/awaymissions/mission_code/Academy.dm
  code/modules/projectiles/guns/magic/wand.dm
  code/modules/projectiles/projectile/magic.dm
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
  code/modules/research/xenobiology/crossbreeding/warping.dm
  code/modules/research/xenobiology/xenobiology.dm
  code/modules/spells/spell_types/emplosion.dm
  code/modules/spells/spell_types/explosion.dm
Labels: Balance/Rebalance

#6129 Changeling ability rebalancing
  beestation.dme
  code/__DEFINES/status_effects.dm
  code/__DEFINES/traits.dm
  code/datums/mutations/chameleon.dm
  code/datums/saymode.dm
  code/datums/status_effects/buffs.dm
  code/game/data_huds.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/machinery/porta_turret/portable_turret.dm
  code/game/machinery/scan_gate.dm
  code/game/objects/effects/mines.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/changeling/powers/adrenaline.dm
  code/modules/antagonists/changeling/powers/biodegrade.dm
  code/modules/antagonists/changeling/powers/chameleon_skin.dm
  code/modules/antagonists/changeling/powers/fleshmend.dm
  code/modules/antagonists/changeling/powers/gaseous_pores.dm
  code/modules/antagonists/changeling/powers/hivemind.dm
  code/modules/antagonists/changeling/powers/organic_mindshield.dm
  code/modules/antagonists/changeling/powers/shriek.dm
  code/modules/antagonists/changeling/powers/tiny_prick.dm
  code/modules/antagonists/changeling/powers/transform.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  icons/mob/actions/actions_changeling.dmi
  icons/mob/screen_alert.dmi
Labels: Tweak, Feature, Sprites, Removal

#6689 Fixes de-sword runtime
  code/game/objects/items/dualsaber.dm
Labels: Fix

#6690 Fixes some logic in suit tracking
  code/controllers/subsystem/processing/nanites.dm
  code/game/data_huds.dm
  code/modules/clothing/under/_under.dm
  code/modules/modular_computers/file_system/programs/radar.dm
  code/modules/research/nanites/nanite_programs/utility.dm
Labels: Fix

#5894 Ports aiming component from NSV13
  beestation.dme
  code/__DEFINES/dcs/signals.dm
  code/_onclick/hud/radial.dm
  code/_onclick/hud/radial_persistent.dm
  code/datums/components/aiming.dm
  code/game/objects/items.dm
  code/modules/projectiles/autofire.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/toy.dm
  icons/effects/aiming.dmi
Labels: Feature, Sprites, Fix

#6693 RWalls are no longer rusted by default
  code/game/turfs/closed/wall/misc_walls.dm
Labels: Fix

#6687 Observers can no longer use OOC pre-game
  code/modules/client/verbs/ooc.dm
Labels: Tweak, Server

#6698 Sensors
  code/modules/clothing/under/_under.dm
Labels: Fix

#6700 Gives pre-game OOC
  code/modules/client/verbs/ooc.dm
Labels: Fix

#6703 Makes nukies use antag_pick
  code/game/gamemodes/nuclear/nuclear.dm
Labels: Fix

#6708 Forces minimist's resolution to 1.2.6
  tgui/package.json
  tgui/yarn.lock
Labels: Server, TGUI-Changes

#6709 Fixes null is jammed runtime
  code/game/machinery/computer/crew.dm
  code/modules/clothing/under/_under.dm
Labels: Fix

#6544 medbot voice lines
  code/modules/mob/living/simple_animal/bot/medbot.dm
  sound/voice/medbot/fuck_you.ogg
  sound/voice/medbot/im_different.ogg
  sound/voice/medbot/oh_fuck.ogg
  sound/voice/medbot/shindemashou.ogg
Labels: Feature, Sound, TGS

#6712 Fixes Radial Hard Dels
  code/_onclick/hud/radial.dm
Labels: THIS IS VERY IMPORTANT, Fix, Removal

#6509 Smelter improvements
  _maps/map_files/Mining/Lavaland.dmm
  code/modules/mining/machine_processing.dm
  code/modules/mining/machine_stacking.dm
Labels: Mapping, Feature, Code Improvement

#6429 Fixes misuse of transform in some animate() calls
  code/datums/components/waddling.dm
  code/datums/diseases/advance/symptoms/heal.dm
  code/game/machinery/dance_machine.dm
Labels: Feature, Fix

#6706 Fixes shuttle docking on war-ops
  code/modules/shuttle/super_cruise/shuttle_components/shuttle_console.dm
Labels: Fix

#6705 Botany fixes
  code/modules/events/spacevine.dm
  code/modules/hydroponics/grown/berries.dm
  code/modules/hydroponics/grown/cereals.dm
  code/modules/hydroponics/grown/corn.dm
  code/modules/hydroponics/grown/garlic.dm
  code/modules/hydroponics/grown/grass_carpet.dm
  code/modules/hydroponics/grown/mushrooms.dm
  code/modules/hydroponics/grown/rainbow_bunch.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/hydroponics/growninedible.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/hydroponics/seed_extractor.dm
  code/modules/hydroponics/seeds.dm
  icons/obj/hydroponics/growing_flowers.dmi
Labels: Sprites, Fix

#6666 Fixes clockcult pressure sensors
  code/modules/antagonists/clock_cult/traps/senders/pressure_sensor.dm
Labels: Fix

#6713 Disables the radiation storm "the air begins to grow warm" message
  code/datums/weather/weather_types/radiation_storm.dm
Labels: Tweak

#6653 Improves the winter boots no slip
  code/__DEFINES/traits.dm
  code/modules/clothing/shoes/miscellaneous.dm
Labels: Fix

#6717 Yet another Crewmonitor fix
  code/modules/research/nanites/nanite_programs/utility.dm
Labels: Fix

#6707 [PORT] Makes HE pipe min temp diff not so low
  code/modules/atmospherics/machinery/pipes/heat_exchange/he_pipes.dm
Labels: Tweak, Balance/Rebalance

#6722 Adds proximity check to Acid Ooze
  code/datums/mutations/actions.dm
Labels: Fix

#6723 Power monitors correctly hide cogged APCs
  code/modules/modular_computers/file_system/programs/powermonitor.dm
  code/modules/power/monitor.dm
Labels: Fix

#6506 Adds gimmick objectives for traitors
  beestation.dme
  code/__DEFINES/configuration.dm
  code/__DEFINES/departments.dm
  code/datums/mind.dm
  code/game/gamemodes/objective.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  strings/dept_gimmick_objectives.txt
  strings/gimmick_objectives.txt
  strings/target_gimmick_objectives.txt
Labels: Tweak, Feature, Testmerge Passed

#6732 Fixes chicken nugget box alignment
  icons/obj/food/containers.dmi
Labels: Sprites, Fix

#6727 Fixes crewmonitor's width
  tgui/packages/tgui/interfaces/CrewConsole.js
Labels: Tweak, TGUI-Changes

#6730 Adds missing short_desc for fugitive spawners
  code/game/objects/structures/fugitive_role_spawners.dm
Labels: Fix

#6731 Tiny Hand Labeler
  code/modules/paperwork/handlabeler.dm
Labels: Tweak

#6735 Actually fixes null light runtime
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
Labels: Fix

#6733 Hypospray refills work again
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Tweak, Fix

#6317 Ports the ability to disable harddels
  code/__DEFINES/qdel.dm
  code/__DEFINES/time.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/garbage.dm
  code/modules/admin/verbs/debug.dm
  config/config.txt
Labels: Config Update, Administration, Server

#6576 [PORT] Locker sounds from TG
  sound/machines/closet_close.ogg
  sound/machines/closet_open.ogg
Labels: Feature, Vote Passed, Sound

#6491 Converts ai tracking towards using signals
  code/_onclick/ai.dm
  code/game/machinery/camera/tracking.dm
  code/game/objects/items/devices/multitool.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/death.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
Labels: Tweak, Refactor, Code Improvement, Testmerge Passed, Good PR

#6741 Fixes stickyban runtime
  code/controllers/subsystem/stickyban.dm
Labels: Fix

#6726 Bumps minimum client version to 1583
  code/_compile_options.dm
  config/config.txt
Labels: Config Update, Server

#6755 Fixes attachment overlays on guns
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
Labels: Fix

#6760 fix pun pun saving
  code/modules/mob/living/carbon/monkey/punpun.dm
Labels: Grammar and Formatting, Server

#6454 CTF species whitelist
  code/modules/awaymissions/capture_the_flag.dm
Labels: Tweak, Fix

#6729 Vend-a-tray shards fix + new breaking sound.
  code/game/objects/structures/displaycase.dm
Labels: Fix

#6774 Fixes flamethrowers lighting runtime
  code/game/objects/items/flamethrower.dm
Labels: Fix

#6773 Fixes double qdel in wielded
  code/datums/components/twohanded.dm
Labels: Fix, Removal
