Repository BeeStation/BeeStation-Hornet, pull requests merged in 2022-11, with the labels that each got.

#7999 Adds biohazard closets to xenobio on MetaStation (I forgor edition)
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Mapping, Feature

#8003 Capitalizes RCD research node names
  code/modules/research/techweb/all_nodes.dm
Labels: Fix

#7890 Make newscaster images less breakage-prone
  code/game/machinery/newscaster/newscaster_data.dm
  code/game/machinery/newscaster/newscaster_machine.dm
Labels: Tweak, Fix

#8004 Fix abductor not properly being muted during non-user saycalls
  code/modules/surgery/organs/tongue.dm
Labels: Fix

#8005 Fix emagging cyborg not unlocking
  code/modules/mob/living/silicon/robot/robot_defense.dm
Labels: Fix

#8006 Fix character slot resetting
  code/modules/client/preferences2/preferences2.dm
Labels: Fix

#8007 Adds metrics tracking for TiDi and harddels
  code/controllers/subsystem/metrics.dm
Labels: Removal, Server

#8008 TGUI Chores
  code/controllers/subsystem/tgui.dm
  code/modules/tgui/tgui.dm
  code/modules/tgui/tgui_window.dm
  code/modules/tgui_panel/tgui_panel.dm
  dependencies.sh
  tgui/.gitignore
  tgui/.yarnrc.yml
  tgui/README.md
  tgui/docs/component-reference.md
  tgui/docs/tgui-for-custom-html-popups.md
  tgui/docs/writing-tests.md
  tgui/global.d.ts
  tgui/package.json
  tgui/packages/tgui-panel/index.js
  tgui/packages/tgui-panel/ping/middleware.js
  tgui/packages/tgui-panel/stat/StatStatus.js
  tgui/packages/tgui-panel/stat/StatTabs.js
  tgui/packages/tgui-panel/stat/StatText.js
  tgui/packages/tgui-panel/stat/StatTicket.js
  tgui/packages/tgui-panel/stat/middleware.js
  tgui/packages/tgui-panel/telemetry.js
  tgui/packages/tgui-polyfill/00-html5shiv.js
  tgui/packages/tgui-polyfill/01-ie8.js
  tgui/packages/tgui-polyfill/02-dom4.js
  tgui/packages/tgui-polyfill/03-css-om.js
  tgui/packages/tgui-polyfill/10-misc.js
  tgui/packages/tgui-polyfill/index.js
  tgui/packages/tgui-polyfill/inferno.js
  tgui/packages/tgui-polyfill/package.json
  tgui/packages/tgui/backend.ts
  tgui/packages/tgui/components/ByondUi.js
  tgui/packages/tgui/components/Popper.tsx
  tgui/packages/tgui/debug/middleware.js
  tgui/packages/tgui/drag.js
  tgui/packages/tgui/focus.js
  tgui/packages/tgui/index.js
  tgui/packages/tgui/layouts/Layout.js
  tgui/packages/tgui/layouts/Window.js
  tgui/packages/tgui/links.js
  tgui/packages/tgui/logging.js
  tgui/packages/tgui/stories/ByondUi.stories.js
  tgui/public/tgui-polyfill.min.js
  tgui/public/tgui.html
  tgui/yarn.lock
  tools/bootstrap/node.bat
  tools/bootstrap/node_.ps1
Labels: Test Merged, Fix, Refactor, Tools, Code Improvement, TGUI-Changes

#7947 Misc Newscaster Fixes + Silicon TGUI Picture Select
  code/game/machinery/computer/security.dm
  code/game/machinery/newscaster/newscaster_machine.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/pai/software.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/modular_computers/file_system/programs/ntmessenger.dm
  code/modules/paperwork/photocopier.dm
  code/modules/photography/camera/silicon_camera.dm
  code/modules/tgui/tgui_select_picture.dm
  tgui/packages/tgui/interfaces/Newscaster.js
  tgui/packages/tgui/interfaces/PictureSelectModal.js
Labels: Tweak, Fix, TGUI-Changes

#8026 Tweaks how brain death is handled and adds repeatable brain surgery
  code/game/objects/items/defib.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/surgery/brain_recalibration.dm
Labels: Tweak, Balance/Rebalance

#8018 fixes some bugs of encryption key & compression box
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Fix, Code Improvement

#7993 Fire extinguishers move with speed according to move_resist, fixes secway exploit
  code/game/objects/items/extinguisher.dm
  code/game/objects/structures/beds_chairs/bed.dm
  code/game/objects/structures/beds_chairs/chair.dm
  code/game/objects/structures/guillotine.dm
  code/game/objects/structures/kitchen_spike.dm
  code/game/objects/structures/manned_turret.dm
  code/modules/vehicles/motorized_wheelchair.dm
  code/modules/vehicles/wheelchair.dm
Labels: Fix, Balance/Rebalance

#7992 Fixes null ref in mob holder
  code/modules/mob/living/inhand_holder.dm
Labels: Fix, hacktoberfest-accepted

#7990 Fixes null user runtime
  code/game/objects/effects/decals/misc.dm
Labels: Fix, hacktoberfest-accepted

#7981 Miscelaneous Pubby Fixes and OSHA update
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Mapping, Tweak, Feature, Fix, Removal

#7741 [PORT]Particool System - Port of a port of a port
  beestation.dme
  code/__DEFINES/particles.dm
  code/__DEFINES/vv.dm
  code/game/atoms_movable.dm
  code/game/objects/items/devices/flashlight.dm
  code/modules/admin/holder2.dm
  code/modules/client/client_procs.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/particles/byond_particles/emitter/burst.dm
  code/modules/particles/byond_particles/emitter/fire.dm
  code/modules/particles/byond_particles/emitter/misc.dm
  code/modules/particles/byond_particles/emitter/smoke.dm
  code/modules/particles/byond_particles/emitter/spark.dm
  code/modules/particles/byond_particles/emitter/weather.dm
  code/modules/particles/byond_particles/particle/burst.dm
  code/modules/particles/byond_particles/particle/fire.dm
  code/modules/particles/byond_particles/particle/misc.dm
  code/modules/particles/byond_particles/particle/rain.dm
  code/modules/particles/byond_particles/particle/smoke.dm
  code/modules/particles/byond_particles/particle/spark.dm
  code/modules/particles/byond_particles/particle_holder.dm
  code/modules/particles/byond_particles/particle_procs.dm
  code/modules/particles/byond_particles/particle_usage.md
  code/modules/particles/byond_particles/particool.dm
  icons/effects/particles/rocks.dmi
  icons/effects/particles/shapes.dmi
  icons/effects/particles/smoke.dmi
  icons/effects/particles/weather.dmi
  tgui/.eslintrc.yml
  tgui/packages/tgui/interfaces/Particool.js
Labels: Feature, Sprites, Administration, Code Improvement, TGUI-Changes

#8030 Remove Text Macros in strings without interpolated expression
  code/modules/antagonists/clock_cult/mobs/eminence.dm
  code/modules/clothing/suits/wiz_robe.dm
  code/modules/hydroponics/seeds.dm
Labels: Fix

#8012 Fix flammable & malfunction traits - xenoarch goof
  code/__DEFINES/xenoartifact_materials.dm
  code/modules/xenoarchaeology/traits/xenoartifact_malfunctions.dm
  code/modules/xenoarchaeology/traits/xenoartifact_minors.dm
  code/modules/xenoarchaeology/xenoartifact.dm
Labels: Tweak, Fix

#7375 Flandstation - Service Pack 5 (AKA Flandstation 2.0)
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/shuttles/arrival/arrival_fland.dmm
  _maps/shuttles/cargo/cargo_fland.dmm
  _maps/shuttles/emergency/emergency_fland.dmm
  _maps/shuttles/exploration/exploration_fland.dmm
  _maps/shuttles/labour/labour_fland.dmm
  _maps/shuttles/whiteship/whiteship_fland.dmm
  code/game/area/Space_Station_13_areas.dm
  code/game/objects/structures/holosign.dm
  code/modules/mining/laborcamp/laborshuttle.dm
  icons/effects/effects.dmi
  icons/turf/areas.dmi
Labels: Mapping, Feature, Sprites

#7581 Lets slimes use custom emotes
  code/modules/mob/living/emote.dm
Labels: Feature, 🔑 Close Key (1/2)

#7536 [PORT] Notes now show the player's living playtime at the time of noting
  SQL/beestation_schema.sql
  SQL/database_changelog.txt
  code/__DEFINES/subsystems.dm
  code/modules/admin/sql_message_system.dm
Labels: SQL, Feature, Administration

#7929 Adds custom title details to roundend report and credit
  code/__HELPERS/roundend.dm
  code/game/gamemodes/game_mode.dm
Labels: Tweak

#7862 adds Chemical bag, that is printable from ChemMaster
  beestation.dme
  code/__DEFINES/reagents.dm
  code/game/atoms.dm
  code/game/machinery/iv_drip.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/reagents/chemistry/machinery/reagentgrinder.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
  code/modules/reagents/reagent_containers/bottle.dm
  code/modules/reagents/reagent_containers/chem_bag.dm
  tgui/packages/tgui/interfaces/ChemMaster.js
Labels: Tweak, Feature, Fix, Code Improvement, TGUI-Changes

#7995 Floor resprite - Desouling
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  code/game/turfs/open/floor/plasteel_floor.dm
  icons/obj/atmospherics/pipes/disposal.dmi
  icons/obj/doors/blastdoor.dmi
  icons/obj/doors/shutters.dmi
  icons/obj/smooth_structures/catwalk.dmi
  icons/turf/decals.dmi
  icons/turf/floors.dmi
Labels: Mapping, Tweak, Feature, Sprites, Testmerge Passed

#8049 Removes random piece of paper from corgstation bridge hallway
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: Mapping

#8014 Player Panel: Redux
  beestation.dme
  code/datums/keybinding/admin.dm
  code/modules/admin/adminmenu.dm
  code/modules/admin/holder2.dm
  code/modules/admin/player_panel.dm
  code/modules/tgui/states/admin_holder.dm
  code/modules/tgui_panel/telemetry.dm
  code/modules/tgui_panel/tgui_panel.dm
  icons/mob/hud.dmi
  tgui/packages/tgui-bench/tests/Tooltip.test.tsx
  tgui/packages/tgui/assets/bg-beestation.svg
  tgui/packages/tgui/components/Dropdown.js
  tgui/packages/tgui/components/Input.js
  tgui/packages/tgui/components/Tooltip.tsx
  tgui/packages/tgui/interfaces/CrewConsole.js
  tgui/packages/tgui/interfaces/PlayerPanel.js
  tgui/packages/tgui/styles/components/Tooltip.scss
  tgui/packages/tgui/styles/layouts/TitleBar.scss
  tgui/packages/tgui/styles/themes/admin.scss
Labels: Tweak, Sprites, Fix, Refactor, Administration, Tools, TGUI-Changes, Testmerge Passed

#8051 BoxStation remapping pack - Command Edition
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Mapping

#8054 Shift boxstation atmos bottom gas chambers 1 tile right
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Mapping

#8042 Fix check greps not applying sometimes
  _maps/RuinGeneration/13x13_corgrobotics.dmm
  _maps/RuinGeneration/5x9_gateway.dmm
  _maps/RuinGeneration/9x13_kitchen.dmm
  _maps/RuinGeneration/9x9_chemlab.dmm
  _maps/shuttles/exploration/exploration_shuttle.dmm
  tools/ci/check_grep.sh
Labels: Mapping, Fix, Tools

#7826 Pumpkinpeople - A Halloween special
  beestation.dme
  code/modules/language/language_holder.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species_types/pumpkin_man.dm
  code/modules/surgery/bodyparts/species_parts/misc_bodyparts.dm
  icons/mob/human_parts.dmi
Labels: Feature, Sprites, hacktoberfest-accepted

#7978 Milkshakes!
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  icons/obj/drinks.dmi
Labels: Feature, Sprites

#8020 Flash buff
  code/modules/assembly/flash.dm
Labels: Balance/Rebalance

#7041 Parallax subsystem & Highpop parallax disable config
  beestation.dme
  code/__DEFINES/dcs/signals/datum_signals/datum_signals.dm
  code/__DEFINES/subsystems.dm
  code/_onclick/hud/parallax.dm
  code/_onclick/observer.dm
  code/_onclick/telekinesis.dm
  code/controllers/configuration/entries/performance.dm
  code/controllers/subsystem/parallax.dm
  code/datums/components/moved_relay.dm
  code/game/atoms_movable.dm
  code/modules/client/client_procs.dm
  code/modules/holodeck/area_copy.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/mob/login.dm
  code/modules/mob/logout.dm
  code/modules/mob/mob.dm
  code/modules/shuttle/on_move.dm
  code/modules/shuttle/shuttle.dm
  config/config.txt
  config/performance.txt
Labels: Config Update, Balance/Rebalance, Refactor, Code Improvement, Somewhat Important, Testmerge Passed, Good PR

#8074 Fixes the airlock painter/tile painter empty status
  code/game/objects/items/airlock_painter.dm
  icons/obj/objects.dmi
Labels: Sprites

#8063 Fixes Emissives, aswell as adds an atomized version of update_appearance
  beestation.dme
  code/__DEFINES/apc.dm
  code/__DEFINES/dcs/flags.dm
  code/__DEFINES/dcs/signals/atom_signals.dm
  code/__DEFINES/lighting.dm
  code/__HELPERS/_lists.dm
  code/_onclick/hud/plane_master.dm
  code/_onclick/hud/screen_objects.dm
  code/datums/mutable_appearance.dm
  code/game/area/areas.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/machinery/computer/_computer.dm
  code/game/machinery/firealarm.dm
  code/game/machinery/telecomms/machines/message_server.dm
  code/game/objects/items/plushes.dm
  code/game/objects/items/singularityhammer.dm
  code/game/objects/items/stacks/cash.dm
  code/game/objects/structures/door_assembly.dm
  code/game/turfs/closed/wall/reinf_walls.dm
  code/game/turfs/open/floor/plasteel_floor.dm
  code/game/turfs/open/space/transit.dm
  code/modules/antagonists/abductor/machinery/experiment.dm
  code/modules/food_and_drinks/food/customizables.dm
  code/modules/hydroponics/gene_modder.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/lighting/emissive_blocker.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/mulebot.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  code/modules/paperwork/paper.dm
  code/modules/power/apc.dm
  code/modules/power/lighting.dm
  code/modules/reagents/reagent_containers/chem_heirloom.dm
Labels: Port, Refactor, Somewhat Important, Good PR

#8061 More Pubby wire fixes
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Mapping

#8057 Minor BoxStation improvements
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Mapping

#8089 Fix fire alarm under sign
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Mapping

#8098 runtime station clonepod has now full of synthflesh
  _maps/map_files/debug/runtimestation.dmm
Labels: Mapping

#8062 [Port] Big Moth Pref Update and fixes
  code/__DEFINES/DNA.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/lists/flavor_misc.dm
  code/modules/admin/create_mob.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences2/character_save.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  code/modules/surgery/organs/wings.dm
  icons/mob/moth_antennae.dmi
  icons/mob/moth_markings.dmi
  icons/mob/moth_wings.dmi
  icons/mob/moth_wingsopen.dmi
Labels: Sprites, Administration

#8097 fixes clone pod requiring experimental pod
  code/game/machinery/computer/cloning.dm
Labels: Fix

#8086 Make player panel search bar empty on open
  code/modules/admin/player_panel.dm
Labels: Tweak, Administration

#8092 Fixes Cameras by giving them all planes.
  code/_onclick/hud/plane_master.dm
  code/game/machinery/computer/camera.dm
  code/game/objects/items/devices/spyglasses.dm
  code/game/turfs/open/openspace.dm
  code/game/turfs/turf.dm
Labels: Fix

#8079 atmos analyzers report volume even for empty containers + made analyzer description accurate
  code/game/objects/items/devices/scanners.dm
Labels: Tweak, Fix

#8077 Makes ghosts continuously float
  code/modules/mob/dead/observer/observer.dm
Labels: Fix

#8104 Brings back the cargo pie joke
  code/modules/cargo/bounties/chef.dm
Labels: Fix

#7441 MRat V2
  beestation.dme
  code/__HELPERS/game.dm
  code/controllers/configuration/entries/general.dm
  code/datums/brain_damage/mrat.dm
  code/modules/client/client_procs.dm
  code/modules/mentor/mentor_verbs.dm
  config/config.txt
  icons/mob/animal.dmi
Labels: Tweak, Feature, Sprites, Fix, Config Update

#8115 Ecto sniffer logging and slight tweak
  code/game/machinery/ecto_sniffer.dm
Labels: Tweak, Administration

#8099 Demoted job title is now "Demoted" instead of "Unassigned"
  code/game/machinery/computer/card.dm
Labels: Tweak

#8085 Flandstation fix batch (FlandStation Sp5.1)
  _maps/map_files/FlandStation/FlandStation.dmm
Labels: Mapping, Tweak, Feature, Fix

#8122 Updates the Github CI to use Ubuntu 20 over 22
  .github/workflows/continuous_integration.yml
Labels: GitHub

#8121 Fixes HoP card console bugs that can't change bank / crew manifest
  code/game/machinery/computer/card.dm
Labels: Fix

#8109 Add null default keybind handling
  code/modules/client/preferences2/preferences2.dm
Labels: Fix

#8130 Several moth wing related fixes
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/lists/flavor_misc.dm
  code/datums/diseases/advance/symptoms/clockwork.dm
  code/modules/admin/create_mob.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences2/character_save.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/human/species.dm
  icons/mob/moth_antennae.dmi
  icons/mob/moth_wings.dmi
  icons/mob/moth_wingsopen.dmi
Labels: Tweak, Feature, Sprites, Fix, Administration, Removal, Code Improvement

#8100 Agent card no longer uses meaningless reset feature to forge
  code/__HELPERS/jobs.dm
  code/game/machinery/PDApainter.dm
  code/game/objects/items/cards_ids.dm
Labels: Tweak, Feature, Removal, Code Improvement

#8081 Holo projectors QOL
  code/game/objects/items/holosign_creator.dm
Labels: Feature

#8111 Adjustements to the IV Drip, Anesthetic Tank Holder, Defibrillator Wall Mount and other wall-mounted items.
  code/game/machinery/defibrillator_mount.dm
  code/game/machinery/iv_drip.dm
  code/game/objects/items/defib.dm
  code/game/objects/structures/extinguisher.dm
  code/modules/surgery/anesthetic_machine.dm
Labels: Tweak, Feature, Fix

#8112 Makes nanites forced speech / skull echo not spammable + send skull echo message to ghosts
  code/modules/research/nanites/nanite_programs.dm
  code/modules/research/nanites/nanite_programs/suppression.dm
Labels: Tweak, Feature, Code Improvement

#8132 adds station trait information in roundend report
  code/__HELPERS/roundend.dm
Labels: Feature

#7986 Disable revolutionary gamemode
  config/dynamic.json
  config/game_options.txt
Labels: Config Update

#8126 Tweaks HoP job disk selling vendor
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  beestation.dme
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/cargo/packs.dm
  code/modules/vending/cartridge.dm
  code/modules/vending/job_disk.dm
Labels: Mapping, Tweak, Code Improvement

#8035 Add shuttle danger warning
  code/__DEFINES/shuttles.dm
  code/datums/shuttles.dm
  code/game/machinery/computer/communications.dm
  tgui/packages/tgui/interfaces/CommunicationsConsole.js
Labels: Tweak, Feature, TGUI-Changes

#8047 Camera console micro-optimization
  code/game/machinery/computer/camera.dm
  code/modules/modular_computers/file_system/programs/secureye.dm
Labels: Code Improvement

#8067 Overall reverses lavaland powercreep
  code/__DEFINES/atmospherics.dm
  code/__HELPERS/game.dm
  code/game/objects/structures/lavaland/geyser.dm
  code/game/objects/structures/lavaland/necropolis_tendril.dm
  code/modules/mining/equipment/kinetic_crusher.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/swarmer.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/basilisk.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/goldgrub.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  code/modules/uplink/uplink_items.dm
Labels: Balance/Rebalance

#7943 Crew Objectives Refactor
  code/__DEFINES/reagents.dm
  code/__HELPERS/roundend.dm
  code/controllers/subsystem/job.dm
  code/datums/diseases/_disease.dm
  code/game/machinery/newscaster/newscaster_data.dm
  code/game/machinery/newscaster/newscaster_machine.dm
  code/modules/crew_objectives/_crew_objectives.dm
  code/modules/crew_objectives/cargo_objectives.dm
  code/modules/crew_objectives/civilian_objectives.dm
  code/modules/crew_objectives/command_objectives.dm
  code/modules/crew_objectives/engineering_objectives.dm
  code/modules/crew_objectives/medical_objectives.dm
  code/modules/crew_objectives/science_objectives.dm
  code/modules/crew_objectives/security_objectives.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/spells/spell_types/mime.dm
Labels: Tweak, Feature, Fix, Removal, Code Improvement, Server
