Repository BeeStation/BeeStation-Hornet, pull requests merged in 2022-06, with the labels that each got.

#6551 X-ray guns have 60% armour penetration.
  code/modules/projectiles/projectile/beams.dm
Labels: Balance/Rebalance, 🔑 Close Key (1/2)

#6958 Config change to enable map voting
  code/__HELPERS/roundend.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/vote.dm
  config/config.txt
Labels: Fix, Config Update

#7009 Fixes exploration radio not being included when filtering radio messages in chat.
  tgui/packages/tgui-panel/chat/constants.js
Labels: Fix, TGUI-Changes

#7002 Adminordrazine fix
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Fix

#7005 Fixes conjugation for plural gender limb examines
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/surgery/bodyparts/bodyparts.dm
Labels: Fix

#6979 Fixes rubber autorifles not taking in lethal mags.
  code/modules/projectiles/guns/ballistic/automatic.dm
Labels: Fix

#6888 Gave positronic brains non-crew harm
  code/modules/mob/living/brain/posibrain.dm
Labels: Tweak

#7014 Fixes lighteater
  code/game/atoms.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/photography/camera/silicon_camera.dm
Labels: Fix

#7021 fixes runtime with round-end map vote popup
  code/controllers/subsystem/vote.dm
Labels: Fix

#6991 Adds QM turtleneck and turtleneck skirt
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/modules/clothing/under/jobs/cargo.dm
  icons/mob/clothing/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, Sprites

#6805 Colossus gets tells + new Kinetic Crusher ability from Hiero
  code/modules/mining/equipment/kinetic_crusher.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
Labels: Tweak, Balance/Rebalance, Good PR

#7040 Fixes some inconsistencies related to the word "Centcomm" instead of being "Centcom"
  beestation.dme
  code/modules/clothing/under/jobs/centcom.dm
  strings/redpill.json
Labels: Fix

#7036 Blobs can no longer destroy indestructible items.
  code/game/objects/items.dm
  code/modules/power/antimatter/control.dm
Labels: Fix

#7000 Vampire Blood Fix + Vampire Bat speed-up
  code/modules/mob/living/carbon/human/species_types/vampire.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/bat.dm
  code/modules/spells/spell_types/shapeshift.dm
Labels: Fix, Balance/Rebalance

#7038 Fixes brain problems not equipping medicine properly.
  code/datums/traits/negative.dm
Labels: Fix

#7026 Fixes Mask of Madness recipe
  code/modules/antagonists/eldritch_cult/knowledge/ash_lore.dm
Labels: Fix

#7045 Fixes clockcult pressure sensors
  code/modules/antagonists/clock_cult/traps/senders/pressure_sensor.dm
Labels: Fix

#7035 Removes bluespace polycrystals
  _maps/RandomRuins/SpaceRuins/hilbertshoteltestingsite.dmm
  code/datums/materials/basemats.dm
  code/game/objects/items/stacks/bscrystal.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/structures/crates_lockers/closets/syndicate.dm
  code/modules/cargo/exports/sheets.dm
  code/modules/research/xenobiology/crossbreeding/charged.dm
  code/modules/research/xenobiology/crossbreeding/warping.dm
  code/modules/ruins/lavaland_ruin_code.dm
Labels: Mapping, Tweak, Balance/Rebalance

#7049 Friendly ninjas are now admin only
  code/modules/antagonists/ninja/ninja.dm
  code/modules/ninja/ninja_event.dm
Labels: Tweak

#6628 remaps viro
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/modules/reagents/chemistry/machinery/pandemic.dm
  icons/obj/chemical.dmi
  icons/obj/objects.dmi
Labels: Mapping, Tweak, Feature, Sprites, Removal

#6960 Small-ish xenomorph refactor, hunter and sentinel rebalance
  code/_onclick/other_mobs.dm
  code/controllers/configuration/entries/game_options.dm
  code/modules/mob/living/carbon/alien/alien.dm
  code/modules/mob/living/carbon/alien/alien_defense.dm
  code/modules/mob/living/carbon/alien/damage_procs.dm
  code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
  code/modules/mob/living/carbon/alien/humanoid/caste/drone.dm
  code/modules/mob/living/carbon/alien/humanoid/caste/hunter.dm
  code/modules/mob/living/carbon/alien/humanoid/caste/praetorian.dm
  code/modules/mob/living/carbon/alien/humanoid/caste/sentinel.dm
  code/modules/mob/living/carbon/alien/humanoid/humanoid.dm
  code/modules/mob/living/carbon/alien/humanoid/humanoid_defense.dm
  code/modules/mob/living/carbon/alien/humanoid/life.dm
  code/modules/mob/living/carbon/alien/humanoid/queen.dm
  code/modules/mob/living/carbon/alien/life.dm
  code/modules/mob/living/carbon/alien/login.dm
  code/modules/mob/living/carbon/alien/logout.dm
  code/modules/mob/living/carbon/alien/organs.dm
  code/modules/mob/living/carbon/alien/say.dm
  code/modules/mob/living/carbon/alien/screen.dm
  code/modules/mob/living/carbon/alien/special/alien_embryo.dm
  code/modules/mob/living/carbon/alien/special/facehugger.dm
  code/modules/mob/living/carbon/alien/update_icons.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  code/modules/mob/mob_helpers.dm
Labels: Balance/Rebalance, Refactor, Code Improvement

#7065 Adds unused HoP suit to HoP locker
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/under/jobs/civilian/civilian.dm
  tools/UpdatePaths/clothingunderrepath.txt
Labels: Feature, Tools

#6795 Law Uploading Overhaul
  code/_globalvars/lists/objects.dm
  code/_globalvars/misc.dm
  code/game/machinery/computer/law.dm
  code/game/machinery/computer/robot.dm
  code/modules/uplink/uplink_items.dm
  tgui/packages/tgui/interfaces/RoboticsControlConsole.js
Labels: Needs Testmerge, Test Merged, Tweak, Feature, Balance/Rebalance, Code Improvement, Needs Wiki Changes, TGUI-Changes

#7089 Fixes a bunch of simple harddels
  code/game/machinery/dna_scanner.dm
  code/game/machinery/ecto_sniffer.dm
  code/game/machinery/quantum_pad.dm
  code/game/machinery/suit_storage_unit.dm
  code/modules/antagonists/clock_cult/items/clockwork_slab.dm
  code/modules/antagonists/clock_cult/scriptures/_clockwork_scripture.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/gutlunch.dm
  code/modules/pool/pool.dm
  code/modules/power/singularity/emitter.dm
  code/modules/power/tesla/coil.dm
  code/modules/surgery/anesthetic_machine.dm
Labels: Fix

#7092 Fix some minors typos
  code/controllers/subsystem/processing/orbits.dm
  code/modules/jobs/job_types/_job.dm
  config/game_options.txt
  tools/HubMigrator/HubMigrator.dm
  tools/WebhookProcessor/github_webhook_processor.php
  tools/minibot/minibot.py
Labels: Grammar and Formatting, Config Update

#7091 Fixed hydroponics shutters on Fland Station
  _maps/map_files/FlandStation/FlandStation.dmm
Labels: Mapping, Fix

#7085 Fixes cells hard deleting in lights
  code/modules/power/lighting.dm
Labels: Fix, Removal

#7087 fixing maints
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Mapping, Tweak, Removal

#7078 Re-adds the admin only plasma decontamination event [Ivniinvi PR recoup]
  beestation.dme
  code/modules/events/plasma_decon.dm
Labels: Feature, Administration

#7056 AI and borgs get the same amount of beecoins as escaping if they remain on the station
  code/modules/metacoin/metacoin.dm
Labels: Tweak

#6966 Revert "Character-based gear loadouts"
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: Removal, Somewhat Important, Frozen

#7067 New SPAM Cartridge + cartridge spam tweak
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/PDA_types.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/modules/vending/cartridge.dm
Labels: Feature, Refactor, Removal

#6920 Door hacking overhaul
  code/datums/wires/_wires.dm
  code/datums/wires/airlock.dm
  code/datums/wires/emitter.dm
Labels: Tweak, Balance/Rebalance, Testmerge Passed

#6948 Tune-ups to Supermatter radiation
  code/modules/power/supermatter/supermatter.dm
Labels: Fix, Removal, Code Improvement, Testmerge Passed

#7110 Morph no longer bites everyone in sight
  code/modules/antagonists/morph/morph.dm
Labels: Fix

#7074 New icons for the Medical tools, defribillator, and reintrodution of the in-hand e-saw for traitors.
  code/game/objects/items/melee/energy.dm
  code/modules/surgery/organs/augments_arms.dm
  code/modules/surgery/tools.dm
  code/modules/uplink/uplink_items.dm
  icons/mob/inhands/equipment/medical_lefthand.dmi
  icons/mob/inhands/equipment/medical_righthand.dmi
  icons/obj/defib.dmi
  icons/obj/machines/defib_mount.dmi
  icons/obj/nuke_tools.dmi
  icons/obj/surgery.dmi
Labels: Feature, Sprites, Vote Passed

#7105 Remove all Monkey Gamemode
  beestation.dme
  code/__DEFINES/role_preferences.dm
  code/__DEFINES/say.dm
  code/datums/diseases/transformation.dm
  code/datums/saymode.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/monkey/monkey.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/antagonists/monkey/monkey.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/simple_animal/hostile/gorilla/gorilla.dm
  code/modules/mob/mob_helpers.dm
  config/game_options.txt
Labels: Good first issue, Config Update, Administration, Removal

#7113 Locks getserverlogs behind the +SERVER permission
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/getlogs.dm
Labels: Administration, Server

#7069 Allows IPCs to wear underwear
  code/modules/mob/living/carbon/human/species_types/IPC.dm
Labels: Tweak

#6826 Fixes genetic resizing issue
  code/datums/mutations/body.dm
Labels: Fix, Needs Pictures

#7120 Incursionists don't get radio Uplinks anymore, getting Traitor-like uplinks instead
  code/datums/mind.dm
  code/modules/antagonists/incursion/incursion.dm
  code/modules/uplink/uplink_devices.dm
Labels: Feature, Good PR

#7129 Fixes multi-z jaunting and reduces gravity message frequency
  code/game/turfs/turf.dm
Labels: Tweak, Fix

#7131 Fix plush description typo
  code/game/objects/items/plushes.dm
Labels: Grammar and Formatting

#7135 Removes the Yiff Decal and adds delay to 3 Tile Decals sprays
  code/game/objects/items/crayons.dm
  icons/effects/96x32.dmi
Labels: Tweak, Sprites, Removal

#7133 Wizards and Nukies get their traits removed
  code/modules/antagonists/nukeop/nukeop.dm
  code/modules/antagonists/wizard/wizard.dm
  code/modules/mob/living/status_procs.dm
Labels: Tweak

#7116 Renames misleading float define
  code/__DEFINES/flags.dm
  code/__DEFINES/maths.dm
  code/modules/admin/verbs/individual_logging.dm
Labels: Administration, Code Improvement

#7109 No more infinite free slabs
  code/game/machinery/fat_sucker.dm
Labels: Fix, Server

#7102 Removes duplicate uranium in darkpurple warping
  code/modules/research/xenobiology/crossbreeding/warping.dm
Labels: Fix

#6897 Chemist Heirloom
  beestation.dme
  code/datums/traits/negative.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/reagents/reagent_containers/chem_heirloom.dm
  icons/obj/chemical.dmi
Labels: Tweak, Feature, Sprites

#7140 Fixes all TGUI interfaces being broken
  code/modules/tgui/tgui.dm
Labels: Fix

#7054 Ripley drilling now causes sparks when drilling robots
  code/game/mecha/equipment/tools/mining_tools.dm
Labels: Tweak
