Repository BeeStation/BeeStation-Hornet, pull requests merged in 2022-01, with the labels that each got.

#5617 Flandstation
  _maps/RandomRooms/fland/sk_rdm_fln_01_scooterpark.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_02_beelounge.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_03_vendingminimarket.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_04_conveniencestore.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_05_apiary.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_06_publicgarden.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_07_theletterh.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_08_zenroom.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_09_barbershop.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_10_readingroom.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_11_hobobox.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_12_magicstage.dmm
  _maps/_basemap.dm
  _maps/flandstation.json
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/shuttles/arrival_fland.dmm
  _maps/shuttles/cargo_fland.dmm
  _maps/shuttles/emergency_fland.dmm
  _maps/shuttles/exploration_fland.dmm
  _maps/shuttles/ferry_fland.dmm
  _maps/shuttles/labour_fland.dmm
  _maps/shuttles/mining_fland.dmm
  _maps/shuttles/whiteship_fland.dmm
  beestation.dme
  code/datums/shuttles.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/machinery/computer/atmos_control.dm
  code/game/machinery/gulag_teleporter.dm
  code/game/objects/effects/decals/turfdecal/guideline.dm
  code/game/objects/effects/decals/turfdecal/markings.dm
  code/game/objects/effects/decals/turfdecal/tilecoloring.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/effects/spawners/roomspawner.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/items/storage/boxes.dm
  code/game/turfs/open/floor/fancy_floor.dm
  code/modules/mapping/random_rooms.dm
  code/modules/mining/laborcamp/laborshuttle.dm
  config/maps.txt
  icons/effects/landmarks_static.dmi
  icons/obj/decals.dmi
  icons/obj/device.dmi
  icons/obj/tiles.dmi
  icons/turf/areas.dmi
  icons/turf/decals.dmi
  icons/turf/floors.dmi
  icons/turf/floors/carpet_grimy.dmi
Labels: mapping, test merged, Feature, sprites, Config Update, Code Improvement, hacktoberfest-accepted, Based and Qwertypilled

#6077 Flandstation - Service pack 1 (Commemorative Edition)
  _maps/map_files/FlandStation/FlandStation.dmm
  code/game/objects/effects/decals/turfdecal/markings.dm
  code/game/turfs/open/floor/misc_floor.dm
Labels: mapping, Feature, Fix, Removal

#6067 Monkeys burn their hands on lights
  code/modules/power/lighting.dm
Labels: Tweak, Fix

#6064 Make mysterious pillars in the prison cube indestructible
  code/modules/ruins/lavalandruin_code/puzzle.dm
Labels: Balance/Rebalance

#6095 Preference For Syndicate Excommunicate Separate from Traitor
  code/__DEFINES/role_preferences.dm
  code/modules/antagonists/incursion/incursion.dm
Labels: Feature

#6096 Fixes Spetsnaz Pyro Backpack icon_state and item_state
  code/game/objects/items/tanks/watertank.dm
Labels: Fix

#6087 Fixes #6025 - Swarmer blockades can be walked through by anyone
  code/modules/antagonists/swarmer/swarmer.dm
Labels: Fix

#6089 Motion cameras no longer detect invisible mobs.
  code/game/machinery/camera/motion.dm
Labels: Fix

#6088 Fixes #6023 - Adds in an adjustable uniform icon state unit test
  beestation.dme
  code/game/objects/items/holy_weapons.dm
  code/modules/clothing/under/jobs/civilian/civilian.dm
  code/modules/clothing/under/jobs/civilian/clown_mime.dm
  code/modules/clothing/under/suits.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/check_adjustable_clothing.dm
Labels: Fix, Code Improvement

#6086 Fixes cult and clockie magic not checking for holy protection, nerfs the bible.
  code/datums/components/anti_magic.dm
  code/game/objects/items/storage/book.dm
  code/modules/antagonists/clock_cult/items/clockwork_weapon.dm
  code/modules/antagonists/clock_cult/scriptures/kindle.dm
  code/modules/antagonists/clock_cult/scriptures/sigil_of_vitality.dm
  code/modules/antagonists/clock_cult/structure/clockwork_sigil.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/antagonists/eldritch_cult/eldritch_magic.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
Labels: Fix, Balance/Rebalance

#6083 Fixes #6054 - Fixes void thrusters not operating without a heater
  code/game/machinery/shuttle/shuttle_engine.dm
Labels: Fix

#6084 Moves the full auto var to the guns themselves
  code/modules/awaymissions/capture_the_flag.dm
  code/modules/projectiles/autofire.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/guns/energy/laser_gatling.dm
Labels: Code Improvement

#6085 Fixes #6031 - Xenos can no longer pickup items embedded in them.
  code/datums/components/embedded.dm
Labels: Fix

#6090 Fixes #6017 - Pubbystation book scanner too far away from inventory console, preventing book upload
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: mapping, Fix

#6091 Fixes #5998 - Sunglasses not providing protection from welding tools is now intentional.
  code/game/objects/items/tools/weldingtool.dm
Labels: Balance/Rebalance, Code Improvement

#4572 Ports "Arcononomy: Personal Departmental Cargo Ordering" from tg
  beestation.dme
  code/game/objects/structures/crates_lockers/crates/secure.dm
  code/modules/cargo/orderconsole.dm
  code/modules/cargo/packs.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/modular_computers/computers/item/tablet_presets.dm
  code/modules/modular_computers/file_system/programs/budgetordering.dm
  tgui/packages/tgui/interfaces/Cargo.js
  tgui/packages/tgui/interfaces/NtosCargo.js
Labels: Tweak, Feature, TGUI-Changes

#5155 Silicons no longer get off-station access, turret control panels now require the correct access.
  _maps/shuttles/hunter_bounty.dmm
  _maps/shuttles/hunter_russian.dmm
  _maps/shuttles/hunter_space_cop.dmm
  _maps/shuttles/pirate_default.dmm
  code/__DEFINES/access.dm
  code/_onclick/ai.dm
  code/_onclick/cyborg.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/porta_turret/portable_turret.dm
  code/game/objects/items/cards_ids.dm
  code/modules/antagonists/fugitive/fugitive_outfits.dm
  code/modules/antagonists/fugitive/fugitive_ship.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/jobs/access.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_defense.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/power/apc.dm
Labels: mapping, Refactor

#5551 Ports pineapple juice, creme de coconut, pina colada and painkiller.
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/food_and_drinks/food/snacks_frozen.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_frozen.dm
  code/modules/hydroponics/grown/pineapple.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  icons/obj/drinks.dmi
Labels: Feature, sprites, Needs Wiki Changes

#5646 Det's starting revolver and ammo are now MOSTLY non-lethal (and adds new .38 rubber bullets)
  code/modules/clothing/under/accessories.dm
  code/modules/projectiles/ammunition/ballistic/revolver.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/boxes_magazines/internal/revolver.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/projectile/bullets/revolver.dm
  code/modules/research/designs/autolathe_designs.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature, Balance/Rebalance, hacktoberfest-accepted

#5671 Adds Meclizine, a medicine that prevents vomiting
  code/__DEFINES/traits.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
Labels: Feature, Needs Wiki Changes

#5677 Ports RPG Titles (a Wizard event) from TG
  beestation.dme
  code/__DEFINES/dcs/signals.dm
  code/modules/events/wizard/rpgtitles.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/atmospheric_technician.dm
  code/modules/jobs/job_types/bartender.dm
  code/modules/jobs/job_types/botanist.dm
  code/modules/jobs/job_types/brigphys.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/cargo_technician.dm
  code/modules/jobs/job_types/chaplain.dm
  code/modules/jobs/job_types/chemist.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/clown.dm
  code/modules/jobs/job_types/cook.dm
  code/modules/jobs/job_types/curator.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/emt.dm
  code/modules/jobs/job_types/exploration_team.dm
  code/modules/jobs/job_types/geneticist.dm
  code/modules/jobs/job_types/gimmick.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/janitor.dm
  code/modules/jobs/job_types/lawyer.dm
  code/modules/jobs/job_types/medical_doctor.dm
  code/modules/jobs/job_types/mime.dm
  code/modules/jobs/job_types/quartermaster.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/jobs/job_types/scientist.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/shaft_miner.dm
  code/modules/jobs/job_types/station_engineer.dm
  code/modules/jobs/job_types/virologist.dm
  code/modules/jobs/job_types/warden.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/login.dm
Labels: Feature

#5445 [PORT] tgui: Communications Console
  code/controllers/subsystem/shuttle.dm
  code/datums/world_topic.dm
  code/game/machinery/computer/communications.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/modules/admin/verbs/pray.dm
  code/modules/mob/living/silicon/ai/ai.dm
  tgui/packages/tgui/components/Blink.js
  tgui/packages/tgui/components/index.js
  tgui/packages/tgui/interfaces/CommunicationsConsole.js
Labels: Needs Testmerge, Feature, Administration, Triaged, TGUI-Changes

#5782 Disable TGUI's hotkey passthrough when on non-hotkey mode with input box focused
  tgui/packages/tgui/hotkeys.js
Labels: Tweak, TGUI-Changes

#5830 Nerfs firebreath interaction with power chromosomes
  code/datums/mutations/actions.dm
Labels: Balance/Rebalance

#5874 Added Sections to PR Template to improve maintainability
  .github/PULL_REQUEST_TEMPLATE.md
Labels: GitHub, server

#5882 Opens another viro slot
  code/modules/jobs/job_types/virologist.dm
Labels: Tweak, Feature

#6082 Adds a new ion law
  code/modules/events/ion_storm.dm
Labels: Feature

#5954 Re-adds the follow button to the arena controller
  code/game/machinery/computer/arena.dm
Labels: Feature

#5906 Adds a wiremod shell that acts as an assembly
  beestation.dme
  code/modules/assembly/assembly.dm
  code/modules/research/designs/wiremod_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/wiremod/shell/assembly.dm
  icons/obj/assemblies/new_assemblies.dmi
Labels: Feature, sprites

#5948 Allows the number of BeeCoins earned for achievements to be adjusted.
  code/__DEFINES/metacoin.dm
  code/datums/achievements/_awards.dm
  code/datums/achievements/misc_achievements.dm
Labels: Feature

#5913 New Plasmamen Helmets
  code/__DEFINES/preferences.dm
  code/_globalvars/lists/flavor_misc.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/outfits/plasmaman.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/lawyer.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/apid.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Feature, sprites

#6047 Hostile Ruin Adjustments
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/generator_settings/generator_ratvar.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/generator_settings/generator_xeno.dm
Labels: Balance/Rebalance, Removal

#5980 Lowers threat needed for Summon Events/Magic/Guns
  code/modules/antagonists/wizard/equipment/spellbook.dm
Labels: Tweak

#6020 Fixes Eminence Bugs
  code/modules/antagonists/clock_cult/mobs/eminence.dm
Labels: Fix

#6015 Allows Admins to Delete Library Books
  code/modules/admin/admin_verbs.dm
Labels: Administration, Removal

#6016 Extends Box Toxins Test Area
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: mapping, Fix

#6056 Roomba Cleanbots
  code/datums/components/crafting/recipes.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
  code/modules/mob/living/simple_animal/bot/construction.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/mob/aibots.dmi
  icons/obj/janitor.dmi
Labels: Feature, sprites

#6049 Fixes Explorer Gun Damage Increase On Simple Mobs
  code/modules/exploration_crew/exploration_laser_gun.dm
Labels: Fix

#6133 Larry
  code/datums/components/crafting/recipes.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
  code/modules/mob/living/simple_animal/bot/construction.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/mob/aibots.dmi
  icons/obj/janitor.dmi
Labels: Tweak, sprites

#5744 Changed WASD to keybindings
  code/__DEFINES/keybinding.dm
  code/controllers/subsystem/input.dm
  code/datums/keybinding/mob.dm
  code/modules/client/preferences_savefile.dm
Labels: Needs Testmerge, test merged, Feature

#6100 Flandstation - Service Pack 2
  _maps/map_files/FlandStation/FlandStation.dmm
  code/datums/weather/weather_types/radiation_storm.dm
  code/game/area/Space_Station_13_areas.dm
  icons/obj/doors/airlocks/hatch/centcom.dmi
  icons/obj/doors/airlocks/hatch/maintenance.dmi
  icons/obj/doors/airlocks/hatch/overlays.dmi
Labels: mapping, Tweak, Feature, sprites, Fix, Balance/Rebalance

#5705 TGUI Strip menu - list edition
  beestation.dme
  code/__DEFINES/mobs.dm
  code/__DEFINES/strippable.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/_lists.dm
  code/datums/elements/strippable.dm
  code/datums/mocking/client.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/alien/humanoid/humanoid.dm
  code/modules/mob/living/carbon/alien/larva/larva.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_stripping.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_stripping.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/mob.dm
  code/modules/tgui/states.dm
  code/modules/tgui/status_composers.dm
  tgui/packages/common/collections.spec.ts
  tgui/packages/common/collections.ts
  tgui/packages/common/math.ts
  tgui/packages/tgfont/icons/air-tank-slash.svg
  tgui/packages/tgfont/icons/air-tank.svg
  tgui/packages/tgfont/icons/nanotrasen-logo.svg
  tgui/packages/tgfont/icons/syndicate-logo.svg
  tgui/packages/tgui/interfaces/StripMenu.tsx
  tgui/packages/tgui/styles/interfaces/StripMenu.scss
  tgui/packages/tgui/styles/main.scss
Labels: Needs Testmerge, test merged, Feature, Refactor, Code Improvement, TGUI-Changes

#6142 Fixes the linters
  code/datums/mocking/client.dm
  code/modules/tgui/status_composers.dm
  tgui/packages/common/collections.spec.ts
  tgui/packages/tgfont/icons/air-tank-slash.svg
  tgui/packages/tgfont/icons/air-tank.svg
Labels: Fix, Code Improvement, TGUI-Changes

#6147 [Port] Cat AI Core
  code/_globalvars/lists/flavor_misc.dm
  icons/mob/ai.dmi
Labels: Feature, sprites

#6156 Hotfixes pubby pod
  _maps/map_files/generic/CentCom.dmm
Labels: mapping, Fix

#6153 Hardsuit lighting fix
  code/modules/clothing/spacesuits/hardsuit.dm
Labels: Fix

#6150 Fixes the delta ORM
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: mapping, Fix

#6128 Revert harmbaton nerf
  code/game/objects/items/stunbaton.dm
Labels: Balance/Rebalance

#6155 Fix runtime on empy folder examination, alt-click
  code/modules/paperwork/folders.dm
Labels: Fix

#6162 Cargo can now once again accept requests with their own budget. (#54748)
  code/modules/cargo/orderconsole.dm
Labels: Fix

#6164 Adds intercom in Pubby toxins launch, moves Delta's intercom.
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: mapping, Tweak

#6166 fix game_options typo
  config/game_options.txt
Labels: Config Update

#6161 Flandstation - Service Pack 3
  _maps/map_files/FlandStation/FlandStation.dmm
Labels: mapping, Tweak, Fix

#5932 Xenomorphs Stop Gasping due to atmospheric conditions
  code/modules/mob/living/carbon/alien/life.dm
Labels: Feature, Fix, Code Improvement

#6175 Persian cat 2.0
  icons/mob/pets.dmi
Labels: Feature, sprites

#6201 Stops Nightmares from bricking Borgs
  code/modules/photography/camera/silicon_camera.dm
Labels: Fix

#6165 Revert "Nuclear particles no longer directly deal toxin damage throug…
  code/modules/projectiles/projectile/energy/nuclear_particle.dm
Labels: Tweak

#6208 The turf reference is now set before rune activation or other teleports
  code/modules/research/xenobiology/crossbreeding/warping.dm
Labels: Tweak

#6209 Animates Gas Analyzers
  icons/obj/device.dmi
Labels: Feature, sprites

#5813 Slight changes to retro theme
  code/_onclick/hud/generic_dextrous.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/screen_objects.dm
  icons/mob/screen_retro.dmi
Labels: Tweak, Feature, sprites, Fix

#5798 fixes a years-old stamcrit bug
  code/modules/mob/living/carbon/status_procs.dm
Labels: Fix

#6206 In-hand plushes + New plushes
  code/game/objects/items/plushes.dm
  icons/mob/inhands/plushes_lefthand.dmi
  icons/mob/inhands/plushes_righthand.dmi
  icons/obj/plushes.dmi
Labels: Tweak, Feature, sprites

#6230 Makes the pacification trauma gain text more noticable
  code/datums/brain_damage/severe.dm
Labels: Tweak

#6199 Adds One (1) [Uno] Bluespace Matter Bin to the animal hospital.
  _maps/RandomRuins/LavaRuins/lavaland_surface_animal_hospital.dmm
Labels: mapping, Tweak

#6218 Wires up the explorer's office on delta station
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: mapping, Fix

#6112 Updates/Buffs Pirate Shuttle 2
  _maps/shuttles/pirate_default.dmm
  code/modules/clothing/outfits/standard.dm
Labels: mapping, Tweak

#6038 Antag banned players should not be able to repossess themselves anymore
  code/modules/antagonists/_common/antag_datum.dm
Labels: Fix

#6183 TGUI Communications Console fixes
  code/game/machinery/computer/communications.dm
  tgui/packages/tgui/interfaces/CommunicationsConsole.js
  tgui/packages/tgui/sanitize.js
Labels: Feature, Fix, Code Improvement, TGUI-Changes

#6237 Remove hypnotic stupor from fourth wall
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Labels: Tweak

#5841 [BEARAXE] Fight Pit Bears now scale to server population.
  code/modules/shuttle/special.dm
Labels: Balance/Rebalance

#6174 Refactor Some Cyborg Upgrade Modules to Handling Addition/Removal Properly
  code/game/objects/items/robot/robot_upgrades.dm
Labels: Fix

#6196 Re-adds stimpacks
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature

#6245 Allows medipens and cores to be activated in-hand
  code/modules/mining/equipment/regenerative_core.dm
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Tweak

#6249 Fix paperwork editing
  tgui/packages/tgui/interfaces/PaperSheet.js
Labels: Fix, TGUI-Changes

#5819 Removes Hygiene
  code/__DEFINES/misc.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/obj_flags.dm
  code/__DEFINES/traits.dm
  code/_globalvars/bitfields.dm
  code/_onclick/item_attack.dm
  code/controllers/subsystem/processing/quirks.dm
  code/datums/components/mood.dm
  code/datums/mood_events/needs_events.dm
  code/datums/mutations/actions.dm
  code/datums/traits/good.dm
  code/game/objects/items/clown_items.dm
  code/game/objects/structures/shower.dm
  code/game/objects/structures/watercloset.dm
  code/modules/clothing/chameleon.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/spacesuits/_spacesuits.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/suits/bio.dm
  code/modules/clothing/suits/utility.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/status_procs.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/pool/pool.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  icons/mob/smelly.dmi
Labels: Needs Testmerge, sprites

#6224 Hopefully prevents some grief
  code/modules/cargo/packs.dm
Labels: Tweak, Balance/Rebalance

#6252 Fixes the orbit menu ghost icon
  tgui/packages/tgui/interfaces/Orbit.js
Labels: Fix, TGUI-Changes

#6191 More Eminence Changes
  code/game/machinery/buttons.dm
  code/game/machinery/telecomms/machines/relay.dm
  code/modules/antagonists/clock_cult/mobs/eminence.dm
  code/modules/antagonists/clock_cult/scriptures/stargazer.dm
Labels: Tweak, Feature, Fix, Removal

#6179 Ports Medibot Tipping
  code/__DEFINES/robots.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  sound/voice/medbot/dont_like.ogg
  sound/voice/medbot/forgive.ogg
  sound/voice/medbot/hey_wait.ogg
  sound/voice/medbot/i_require_asst.ogg
  sound/voice/medbot/i_trusted_you.ogg
  sound/voice/medbot/is_this_the_end.ogg
  sound/voice/medbot/nooo.ogg
  sound/voice/medbot/pain_is_real.ogg
  sound/voice/medbot/please_dont.ogg
  sound/voice/medbot/please_im_scared.ogg
  sound/voice/medbot/please_put_me_back.ogg
  sound/voice/medbot/reported.ogg
  sound/voice/medbot/thank_you.ogg
  sound/voice/medbot/why.ogg
  sound/voice/medbot/youre_good.ogg
Labels: Feature, sound

#6253 Bulk VSCode & Unit Testing Improvements
  .github/CONTRIBUTING.md
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  code/controllers/subsystem/achievements.dm
  code/modules/detectivework/detective_work.dm
  code/modules/mob/living/blood.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/metabolizing.dm
  code/modules/unit_tests/unit_test.dm
Labels: Port, Feature, Fix, GitHub, server

#6132 Digital Camo Refactor
  beestation.dme
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/elements/digital_camo.dm
  code/datums/hud.dm
  code/modules/antagonists/changeling/powers/digitalcamo.dm
  code/modules/antagonists/eldritch_cult/eldritch_items.dm
  code/modules/mob/living/carbon/examine.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/login.dm
Labels: Refactor

#5820 New >>>>ALTERNATIVE<<<< roboticist jumpsuits
  code/modules/cargo/packs.dm
  code/modules/clothing/under/jobs/rnd.dm
  code/modules/vending/wardrobes.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Stale, sprites

#6170 Random rooms now load at roundstart
  code/controllers/subsystem/mapping.dm
  code/game/objects/effects/spawners/roomspawner.dm
  code/modules/mapping/map_template.dm
Labels: Feature

#6094 Statpanel Tweaks and World Topic tweak.
  code/__DEFINES/stat_panel.dm
  code/__HELPERS/stat_helpers.dm
  code/controllers/subsystem/ticker.dm
  code/datums/world_topic.dm
  code/modules/admin/check_antagonists.dm
  code/modules/mob/dead/dead.dm
  code/modules/mob/living/carbon/alien/alien.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/mob_stat.dm
  tgui/packages/tgui-panel/stat/StatText.js
  tgui/packages/tgui-panel/stat/constants.js
Labels: Tweak, Feature, Administration, Removal, Code Improvement, TGUI-Changes

#6256 Minor explo gun rebalance
  code/modules/exploration_crew/exploration_laser_gun.dm
Labels: Balance/Rebalance

#6258 Makes The Syndicate ID Cards Wide
  icons/obj/card.dmi
Labels: Feature, sprites

#6261 Pills created by ChemMasters will actually go into pill bottles inserted into them.
  code/modules/reagents/chemistry/machinery/chem_master.dm
Labels: Fix

#6271 Bumps python to 3.9.10
  .github/workflows/compile_changelogs.yml
  .github/workflows/continuous_integration.yml
  .github/workflows/make_changelogs.yml
  dependencies.sh
  tools/bootstrap/python39._pth
  tools/bootstrap/python_.ps1
  tools/changelog/generate_cl.py
  tools/changelog/requirements.txt
  tools/changelog/ss13_genchangelog.py
  tools/requirements.txt
Labels: GitHub, tools, Code Improvement, server

#6204 Ports GAGS
  beestation.dme
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/materials.dm
  code/__DEFINES/subsystems.dm
  code/__DEFINES/vv.dm
  code/__HELPERS/files.dm
  code/__HELPERS/icons.dm
  code/controllers/subsystem/overlays.dm
  code/controllers/subsystem/processing/greyscale.dm
  code/datums/greyscale/README.md
  code/datums/greyscale/_greyscale_config.dm
  code/datums/greyscale/greyscale_configs.dm
  code/datums/greyscale/json_configs/canister_base.json
  code/datums/greyscale/json_configs/canister_default.json
  code/datums/greyscale/json_configs/canister_double_stripe.json
  code/datums/greyscale/json_configs/canister_hazard.json
  code/datums/greyscale/json_configs/canister_post_effects.json
  code/datums/greyscale/json_configs/canister_proto.json
  code/datums/greyscale/json_configs/canister_stripe.json
  code/datums/greyscale/json_configs/screwdriver.json
  code/datums/greyscale/json_configs/screwdriver_worn.json
  code/datums/greyscale/json_reader.dm
  code/datums/greyscale/layer.dm
  code/datums/materials/_material.dm
  code/datums/materials/basemats.dm
  code/game/atoms.dm
  code/game/objects/items.dm
  code/game/objects/items/theft_tools.dm
  code/game/objects/items/tools/screwdriver.dm
  code/modules/admin/greyscale_modify_menu.dm
  code/modules/admin/view_variables/topic_basic.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/atmospherics/machinery/portable/canister.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/greyscale_config.dm
  icons/Testing/greyscale_error.dmi
  icons/obj/atmos.dmi
  icons/obj/atmospherics/canisters.dmi
  icons/obj/atmospherics/prototype_canister.dmi
  tgui/packages/tgui/components/LabeledList.tsx
  tgui/packages/tgui/interfaces/GreyscaleModifyMenu.tsx
Labels: Feature, sprites, Administration, TGUI-Changes

#6278 Fixes beakers, chem grenades, and mood events hardelling
  code/datums/components/mood.dm
  code/datums/mood_events/mood_event.dm
  code/datums/wires/_wires.dm
  code/game/objects/items/grenades/chem_grenade.dm
Labels: Fix, Removal, Code Improvement
