Repository BeeStation/BeeStation-Hornet, pull requests merged in 2022-12, with the labels that each got.

#8140 Adds new random maintenance rooms
  _maps/RandomRooms/10x10/sk_rdm167_library_ritual.dmm
  _maps/RandomRooms/10x5/sk_rdm161_kilovault.dmm
  _maps/RandomRooms/3x3/sk_rdm162_control_room.dmm
  _maps/RandomRooms/3x3/sk_rdm163_corgi_butcher.dmm
  _maps/RandomRooms/3x3/sk_rdm164_cornucopia.dmm
  _maps/RandomRooms/3x3/sk_rdm_165_library.dmm
  _maps/RandomRooms/3x5/sk_rdm168_offish.dmm
  _maps/RandomRooms/5x4/sk_rdm166_printing_press.dmm
  _maps/RandomRooms/5x4/sk_rdm169_solars.dmm
  code/modules/mapping/random_rooms.dm
Labels: Mapping, Feature

#8138 Moves Xenoarchaeology on Kilo Station
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Mapping, Tweak

#8153 Server reboot delay reason will be notified in Status Tab
  code/modules/mob/mob_stat.dm
Labels: Feature, Removal

#8159 Fixes a couple of oversights with the recent mining adjustments
  code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/swarmer.dm
Labels: Fix

#8151 Always Dynamic
  config/game_options.txt
Labels: Config Update

#8161 Fix invalid turfs on golem ship
  _maps/RandomRuins/LavaRuins/lavaland_surface_golem_ship.dmm
  code/modules/mapping/reader.dm
Labels: Mapping, Fix

#8160 Fix ghosting runtime
  code/datums/elements/weather_listener.dm
Labels: Fix

#8148 exploration nuke bomb will no longer be spawned in weird places
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/ruin_generator.dm
Labels: Fix, Code Improvement

#8156 Revert "Server reboot delay reason will be notified in Status Tab"
  code/modules/mob/mob_stat.dm
Labels: Removal, Server

#8154 change required access of radiant dance machine mark IV
  code/game/machinery/dance_machine.dm
Labels: Tweak

#8039 Xeno "hijack" tweaks++
  code/controllers/subsystem/shuttle.dm
  code/modules/antagonists/xeno/xeno.dm
  code/modules/mob/living/carbon/alien/humanoid/queen.dm
  code/modules/shuttle/emergency.dm
Labels: Tweak

#8066 Changes some Lasso code and adds an ash drake lasso for ashwalkers
  code/datums/ai/tamed/tamed_behaviour.dm
  code/datums/ai/tamed/tamed_controller.dm
  code/datums/components/crafting/recipes.dm
  code/game/objects/items/carp_lasso.dm
  code/modules/antagonists/ashwalker/ashwalker.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature, Balance/Rebalance, Code Improvement

#7959 Bumps Auxmos from 1.1.2 to 2.2.1 and BYOND to 514.1589
  Dockerfile
  auxtools/auxmos.dll
  code/_compile_options.dm
  code/controllers/subsystem/air.dm
  code/modules/atmospherics/environmental/LINDA_system.dm
  code/modules/atmospherics/environmental/LINDA_turf_tile.dm
  code/modules/atmospherics/gasmixtures/gas_mixture.dm
  code/modules/atmospherics/machinery/components/binary_devices/dp_vent_pump.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/he_pipes.dm
  code/modules/client/client_procs.dm
  dependencies.sh
Labels: Server, Testmerge Passed

#8170 ghosts can no longer rename syndie shuttle pod
  code/modules/shuttle/bluespace_shuttle_pod/pod_computer.dm
Labels: Fix, Server

#8179 Changes filtered(?) brain damage word to a more better one
  strings/traumas.json
Labels: Tweak

#8176 Hybridizes Ancient RIG hardsuit suit storage
  code/modules/clothing/spacesuits/hardsuit.dm
Labels: Tweak, Feature, Balance/Rebalance

#8152 Dynamic Abductor Tweak + Sleeper Agent Fix
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
Labels: Tweak, Fix

#8167 Fixes proximity sensors to work on 0 tile now
  code/modules/assembly/proximity.dm
Labels: Fix

#8174 Some changes to list related wiremod components to make them behave better.
  code/modules/wiremod/components/abstract/indexer.dm
  code/modules/wiremod/components/list/append.dm
  code/modules/wiremod/components/list/list_constructor.dm
  code/modules/wiremod/components/list/write.dm
Labels: Tweak, Fix

#8172 Abductor jammer no longer blocks cameras, abductors can teleport to their agent, fixes agent vest exploit
  beestation.dme
  code/__DEFINES/jamming_defines.dm
  code/datums/components/radio_jamming.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/computer/crew.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/devices/traitordevices.dm
  code/game/objects/items/pinpointer.dm
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/antagonists/abductor/machinery/camera.dm
  code/modules/antagonists/abductor/machinery/pad.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/say.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/modular_computers/file_system/programs/radar.dm
Labels: Balance/Rebalance

#8199 Bumps the schema version to 6.1
  SQL/beestation_schema.sql
Labels: SQL, Server

#8055 Area dependant airlock hack difficulty
  beestation.dme
  code/__DEFINES/airlock.dm
  code/datums/wires/_wires.dm
  code/datums/wires/airlock.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas.dm
  code/game/area/areas/away_content.dm
  code/game/area/areas/centcom.dm
  code/game/area/areas/mining.dm
  code/game/area/areas/ruins/_ruins.dm
  code/game/area/areas/shuttles.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/airlock_types.dm
  code/game/objects/structures/door_assembly.dm
Labels: Balance/Rebalance

#8166 Add button to relaunch the game alongside reconnect when you lose connection
  interface/skin.dmf
  tgui/packages/tgui-panel/Panel.js
  tgui/packages/tgui-panel/reconnect.tsx
Labels: Feature, TGUI-Changes

#7804 Add a ton of new emotes + some small species emote refactors
  beestation.dme
  code/__DEFINES/species.dm
  code/datums/emotes.dm
  code/modules/mob/living/carbon/emote.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/IPC.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/mob/living/carbon/human/species_types/oozelings.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/silicon/robot/emote.dm
  icons/effects/overlay_effects.dmi
  sound/emotes/annoyed.ogg
  sound/emotes/clap1.ogg
  sound/emotes/clap2.ogg
  sound/emotes/clap3.ogg
  sound/emotes/clap4.ogg
  sound/emotes/dwoop.ogg
  sound/emotes/female/female_cough_1.ogg
  sound/emotes/female/female_cough_2.ogg
  sound/emotes/female/female_cough_3.ogg
  sound/emotes/female/female_giggle_1.ogg
  sound/emotes/female/female_giggle_2.ogg
  sound/emotes/female/female_sigh.ogg
  sound/emotes/female/female_sneeze.ogg
  sound/emotes/female/female_sniff.ogg
  sound/emotes/female/gasp_f1.ogg
  sound/emotes/female/gasp_f2.ogg
  sound/emotes/female/gasp_f3.ogg
  sound/emotes/female/gasp_f4.ogg
  sound/emotes/female/gasp_f5.ogg
  sound/emotes/female/gasp_f6.ogg
  sound/emotes/male/gasp_m1.ogg
  sound/emotes/male/gasp_m2.ogg
  sound/emotes/male/gasp_m3.ogg
  sound/emotes/male/gasp_m4.ogg
  sound/emotes/male/gasp_m5.ogg
  sound/emotes/male/gasp_m6.ogg
  sound/emotes/male/male_cough_1.ogg
  sound/emotes/male/male_cough_2.ogg
  sound/emotes/male/male_cough_3.ogg
  sound/emotes/male/male_sigh.ogg
  sound/emotes/male/male_sneeze.ogg
  sound/emotes/male/male_sniff.ogg
  sound/emotes/mothchitter.ogg
  sound/emotes/mothlaugh.ogg
  sound/emotes/mothsqueak.ogg
  sound/emotes/scream_moth.ogg
  sound/emotes/snap.ogg
  sound/emotes/snap2.ogg
  sound/emotes/snap3.ogg
  sound/emotes/sweatdrop.ogg
  sound/voice/moth/moth_deathgasp.ogg
Labels: Tweak, Feature, Sprites, Fix, Sound, Code Improvement

#8209 Kills duplicate 512 define
  code/__DEFINES/is_helpers.dm
  code/_onclick/observer.dm
  code/datums/chatmessage.dm
  code/datums/components/beetlejuice.dm
  code/datums/components/edit_complainer.dm
  code/datums/components/explodable.dm
  code/datums/components/infective.dm
  code/datums/components/magnetic_catch.dm
  code/datums/components/orbiter.dm
  code/datums/components/plumbing/_plumbing.dm
  code/datums/components/riding.dm
  code/datums/components/rotation.dm
  code/datums/components/squeak.dm
  code/datums/components/stationloving.dm
  code/datums/components/waddling.dm
  code/datums/elements/cleaning.dm
  code/datums/elements/firestacker.dm
  code/datums/materials/basemats.dm
  code/datums/movement_detector.dm
  code/game/atoms.dm
  code/game/machinery/teleporter.dm
  code/game/mecha/equipment/weapons/weapons.dm
  code/game/objects/effects/step_triggers.dm
  code/game/objects/items/devices/swapper.dm
  code/game/objects/items/theft_tools.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/morgue.dm
  code/game/turfs/turf.dm
  code/modules/antagonists/clock_cult/structure/dimensional_rift.dm
  code/modules/antagonists/wizard/equipment/artefact.dm
  code/modules/buildmode/submodes/copy.dm
  code/modules/events/wormholes.dm
  code/modules/lighting/lighting_atom.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/mob/mob.dm
  code/modules/photography/camera/camera_image_capturing.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/recycling/sortingmachinery.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/objective_types/recover_blackbox.dm
Labels: Code Improvement

#8177 Adds in enumeration and enumerable subsystem.
  beestation.dme
  code/controllers/subsystem/enumeration.dm
  code/datums/components/singularity.dm
  code/datums/enumeration/callback_enumerator.dm
  code/datums/enumeration/enumeration_operations.dm
  code/datums/enumeration/enumerator.dm
  code/datums/enumeration/list_enumerator.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/enumerables.dm
Labels: Code Improvement

#8185 Fixes a faction bug with tamed animals
  code/game/objects/items/carp_lasso.dm
  code/modules/research/xenobiology/xenobiology.dm
Labels: Fix

#8189 Removes some major sleepers, Refactors maploading to be async (100% lag free) 4
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/shuttles/arrival/arrival_kilo.dmm
  _maps/shuttles/aux_base/aux_base_small.dmm
  _maps/shuttles/emergency/emergency_delta.dmm
  _maps/shuttles/emergency/emergency_fland.dmm
  _maps/shuttles/emergency/emergency_imfedupwiththisworld.dmm
  _maps/shuttles/exploration/exploration_kilo.dmm
  _maps/shuttles/infiltrator/infiltrator_advanced.dmm
  _maps/shuttles/whiteship/whiteship_box.dmm
  _maps/shuttles/whiteship/whiteship_cere.dmm
  _maps/shuttles/whiteship/whiteship_meta.dmm
  beestation.dme
  code/__DEFINES/MC.dm
  code/__DEFINES/maps.dm
  code/__HELPERS/stoplag.dm
  code/controllers/master.dm
  code/controllers/subsystem/air.dm
  code/controllers/subsystem/atoms.dm
  code/controllers/subsystem/map_generator.dm
  code/controllers/subsystem/shuttle.dm
  code/datums/map_generators/_map_generator.dm
  code/datums/map_generators/map_placer.dm
  code/datums/mapgen/CaveGenerator.dm
  code/datums/ref.dm
  code/datums/shuttles.dm
  code/game/area/areas/shuttles.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/doors/airlock.dm
  code/modules/admin/verbs/map_template_loadverb.dm
  code/modules/events/fugitive_spawning.dm
  code/modules/events/pirates.dm
  code/modules/holodeck/computer.dm
  code/modules/mapping/map_template.dm
  code/modules/mapping/reader.dm
  code/modules/mapping/ruins.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/ruin_generator.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/shuttle_width_height_correctness.dm
Labels: Mapping, THIS IS VERY IMPORTANT, Fix, Administration, Code Improvement

#8213 Adds clarity to the initial pirate payoff message
  code/modules/events/pirates.dm
Labels: Tweak, Feature

#8083 Space Heater Updates +QoL
  code/game/machinery/spaceheater.dm
  tgui/packages/tgui/interfaces/SpaceHeater.js
Labels: Fix, Balance/Rebalance, Refactor, Removal, Code Improvement, TGUI-Changes

#7982 Language icon is now hidden unless you know those, adds linguist quirk
  code/__DEFINES/language.dm
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/traits/positive_quirk.dm
  code/modules/language/aphasia.dm
  code/modules/language/codespeak.dm
  code/modules/language/common.dm
  code/modules/language/language.dm
Labels: Tweak, Feature, Removal, 🔑 Close Key (1/2)

#8196 Adds limited uses to lassos and tweaks aggo for tamed mobs
  code/__DEFINES/dcs/signals/mob_signals/mob_signals.dm
  code/_onclick/item_attack.dm
  code/datums/ai/tamed/tamed_controller.dm
  code/datums/components/crafting/recipes.dm
  code/game/objects/items/carp_lasso.dm
Labels: Tweak, Balance/Rebalance

#8217 Increase pirate response time
  code/modules/events/pirates.dm
Labels: Tweak

#8178 Map config settings for planetary based maps
  code/__HELPERS/names.dm
  code/datums/map_config.dm
  code/game/gamemodes/meteor/meteors.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/meteor.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/space_station.dm
  tgui/packages/tgui/components/OrbitalMapSvg.js
Labels: Feature, Fix, Config Update, TGUI-Changes

#8205 Adds tech research warning
  code/modules/research/rdconsole.dm
  tgui/packages/tgui/interfaces/Techweb.js
Labels: Feature, TGUI-Changes

#8230 [Port] Access the Wiki from in-game!
  beestation.dme
  code/modules/modular_computers/file_system/programs/wiki_uplink.dm
  code/modules/modular_computers/hardware/hard_drive.dm
  tgui/packages/tgui/interfaces/NtosDatabank.tsx
Labels: Feature, TGUI-Changes

#8207 Ports gastrectomy and cybernetic stomachs from /tg/
  beestation.dme
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/gastrectomy.dm
  code/modules/surgery/organs/stomach.dm
  icons/obj/surgery.dmi
Labels: Feature, Sprites

#8236 Fix for mechanical repair
  code/datums/elements/mechanical_repair.dm
  code/modules/mob/mob_helpers.dm
Labels: Fix

#8191 Miscelaneous box fixes and Engineering small update
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Mapping, Tweak, Fix

#8203 Engineering Plasmamen helmets are now all fireproof
  code/modules/clothing/spacesuits/plasmamen.dm
Labels: Fix, Needs Testing Evidence

#8149 Optional objective is no longer refreshed by unlisted target cryo
  code/game/gamemodes/objective.dm
Labels: Fix

#8239 Fixes shuttle thrusters
  icons/turf/shuttle.dmi
Labels: Sprites, Fix

#8164 Fix rabbit in mail
  code/game/objects/items/mail.dm
  code/modules/jobs/job_mail.dm
  code/modules/mob/living/inhand_holder.dm
Labels: Fix

#8249 Makes the hostile mutant breadloaf drop plain bread slices upon being butchered
  code/modules/mob/living/simple_animal/hostile/bread.dm
Labels: Fix

#8259 Fixes tech web wrong warning
  tgui/packages/tgui/interfaces/Techweb.js
Labels: Fix, TGUI-Changes

#8257 Fix Blob strain choices not rerolling
  code/modules/antagonists/blob/overmind.dm
  code/modules/antagonists/blob/powers.dm
Labels: Fix

#8242 Satchel sprite fix
  icons/mob/clothing/back.dmi
Labels: Sprites, Fix

#8232 Replaces the advanced health analyzer with the ERT medibelt in the Debug outfit
  code/game/objects/items/storage/boxes.dm
Labels: Tweak

#8248 Several APC bug fixes
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/power/apc.dm
Labels: Feature, Fix

#8220 Fixes signals subfile naming scheme
  beestation.dme
  code/__DEFINES/dcs/signals/signals_area.dm
  code/__DEFINES/dcs/signals/signals_atom.dm
  code/__DEFINES/dcs/signals/signals_datum/signals_circuit.dm
  code/__DEFINES/dcs/signals/signals_datum/signals_datum.dm
  code/__DEFINES/dcs/signals/signals_datum/signals_moveloop.dm
  code/__DEFINES/dcs/signals/signals_datum/signals_nanite.dm
  code/__DEFINES/dcs/signals/signals_datum/signals_ntnet.dm
  code/__DEFINES/dcs/signals/signals_datum/signals_storage.dm
  code/__DEFINES/dcs/signals/signals_global.dm
  code/__DEFINES/dcs/signals/signals_lighting.dm
  code/__DEFINES/dcs/signals/signals_mob/signals_carbon.dm
  code/__DEFINES/dcs/signals/signals_mob/signals_human.dm
  code/__DEFINES/dcs/signals/signals_mob/signals_living.dm
  code/__DEFINES/dcs/signals/signals_mob/signals_mob.dm
  code/__DEFINES/dcs/signals/signals_mob/signals_silicon.dm
  code/__DEFINES/dcs/signals/signals_mob/signals_simplemob.dm
  code/__DEFINES/dcs/signals/signals_mob/signals_xenobiology.dm
  code/__DEFINES/dcs/signals/signals_movable.dm
  code/__DEFINES/dcs/signals/signals_obj/signals_atmospheric_machine.dm
  code/__DEFINES/dcs/signals/signals_obj/signals_item/signals_clothing.dm
  code/__DEFINES/dcs/signals/signals_obj/signals_item/signals_grenade.dm
  code/__DEFINES/dcs/signals/signals_obj/signals_item/signals_implant.dm
  code/__DEFINES/dcs/signals/signals_obj/signals_item/signals_item.dm
  code/__DEFINES/dcs/signals/signals_obj/signals_machine/signals_airlock.dm
  code/__DEFINES/dcs/signals/signals_obj/signals_machine/signals_aquarium.dm
  code/__DEFINES/dcs/signals/signals_obj/signals_machine/signals_machinery.dm
  code/__DEFINES/dcs/signals/signals_obj/signals_machine/signals_supermatter.dm
  code/__DEFINES/dcs/signals/signals_obj/signals_mech.dm
  code/__DEFINES/dcs/signals/signals_obj/signals_object.dm
  code/__DEFINES/dcs/signals/signals_obj/signals_projectile.dm
  code/__DEFINES/dcs/signals/signals_turf.dm
Labels: Code Improvement

#8137 [PORT] Gives Revenant the ability to orbit adjacent things with double click or pull key
  code/modules/antagonists/revenant/revenant.dm
  code/modules/antagonists/revenant/revenant_abilities.dm
  code/modules/mob/mob_movement.dm
Labels: Tweak, Feature, Fix, Code Improvement

#8261 Alcohol symptom runtime fix
  code/datums/diseases/advance/symptoms/alcohol.dm
Labels: Fix

#6071 pAI expansion
  beestation.dme
  code/__DEFINES/pai.dm
  code/__DEFINES/preferences.dm
  code/_globalvars/lists/poll_ignore.dm
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/pai.dm
  code/_onclick/other_mobs.dm
  code/controllers/subsystem/pai.dm
  code/datums/components/gps.dm
  code/datums/datacore.dm
  code/game/machinery/camera/camera.dm
  code/game/objects/items/devices/aicard.dm
  code/game/objects/items/devices/gps.dm
  code/game/objects/items/devices/paicard.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/paiwire.dm
  code/game/objects/structures/ai_core.dm
  code/game/objects/structures/ladders.dm
  code/modules/admin/verbs/debug.dm
  code/modules/assembly/signaler.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences2/preferences2.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/pai/pai_shell.dm
  code/modules/mob/living/silicon/pai/personality.dm
  code/modules/mob/living/silicon/pai/say.dm
  code/modules/mob/living/silicon/pai/software.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/friendly/drone/interaction.dm
  code/modules/photography/camera/camera.dm
  code/modules/photography/camera/silicon_camera.dm
  code/modules/tgui/states/paicard.dm
  icons/mob/screen_pai.dmi
  icons/obj/aicards.dmi
  tgui/packages/tgui/interfaces/PaiCard.tsx
  tgui/packages/tgui/interfaces/PaiInterface.tsx
  tgui/packages/tgui/interfaces/PaiSubmit.tsx
Labels: Needs Testmerge, Tweak, Feature, Sprites, Administration, Code Improvement, TGUI-Changes
