Repository BeeStation/BeeStation-Hornet, pull requests merged in 2022-05, with the labels that each got.

#6763 Removes try catch from exploration generators
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/asteroid_generator.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/exoplanets/exoplanet_generator.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/ruin_generator.dm
Labels: Code Improvement

#6649 Acid fix
  code/game/objects/effects/alien_acid.dm
  code/game/objects/obj_defense.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/monkey/monkey_defense.dm
Labels: Fix

#6781 Fixes being able to eat through gas masks if you're on harm intent
  code/modules/reagents/reagent_containers.dm
Labels: Fix

#6736 Fixes thick runtime
  code/datums/components/embedded.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#6782 Sentinel's Compromise tweaks
  code/modules/antagonists/clock_cult/scriptures/sentinels_compromise.dm
Labels: Tweak, Balance/Rebalance

#6771 Fixes null runtime in teleporter
  code/game/machinery/teleporter.dm
Labels: Fix

#6734 Removes support for invalid timers
  code/controllers/subsystem/timer.dm
Labels: Server

#6747 Fixes adding component to qdeleting object runtime
  code/game/machinery/computer/buildandrepair.dm
  code/game/machinery/constructable_frame.dm
  code/game/machinery/doors/door.dm
  code/game/objects/items.dm
  code/game/objects/items/dehy_carp.dm
  code/game/objects/items/devices/lightreplacer.dm
  code/game/objects/items/stacks/cash.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/sheets/light.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/items/toys.dm
  code/game/objects/structures.dm
  code/game/objects/structures/fireaxe.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/plasticflaps.dm
  code/game/objects/structures/windoor_assembly.dm
  code/game/objects/structures/window.dm
  code/modules/assembly/holder.dm
  code/modules/mining/ores_coins.dm
  code/modules/paperwork/photocopier.dm
  code/modules/power/lighting.dm
  code/modules/recycling/conveyor2.dm
Labels: Fix

#6789 Corrects nitryl to the same calculation stimulum uses.
  code/modules/surgery/organs/lungs.dm
Labels: Fix

#6553 [PORT] New sounds when interacting with stuff
  code/__DEFINES/machines.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/buttons.dm
  code/game/machinery/computer/_computer.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/computer/dna_console.dm
  code/game/machinery/firealarm.dm
  code/game/machinery/lightswitch.dm
  code/game/objects/items/devices/scanners.dm
  code/game/sound.dm
  code/modules/atmospherics/machinery/airalarm.dm
  code/modules/mining/equipment/mineral_scanner.dm
  code/modules/power/apc.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/recycling/conveyor2.dm
  code/modules/vending/_vending.dm
  sound/effects/fastbeep.ogg
  sound/effects/ping.ogg
  sound/items/hypospray2.ogg
  sound/machines/button1.ogg
  sound/machines/button2.ogg
  sound/machines/button3.ogg
  sound/machines/button4.ogg
  sound/machines/keyboard/keypress1.ogg
  sound/machines/keyboard/keypress2.ogg
  sound/machines/keyboard/keypress3.ogg
  sound/machines/keyboard/keypress4.ogg
  sound/machines/keyboard/keystroke1.ogg
  sound/machines/keyboard/keystroke2.ogg
  sound/machines/keyboard/keystroke3.ogg
  sound/machines/keyboard/keystroke4.ogg
  sound/machines/switch1.ogg
  sound/machines/switch2.ogg
  sound/machines/switch3.ogg
Labels: Feature, Vote Passed, Sound, Testmerge Passed

#6790 Fixes Kilo's ghost Z-level
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Mapping, Fix

#6748 Possibly fixes null client on tgui intialize runtime
  code/modules/asset_cache/asset_list.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/tgui/tgui_window.dm
Labels: Fix

#6753 Various things involving the Captain's Laser and display cases.
  _maps/RandomRuins/LavaRuins/lavaland_surface_biodome_winter.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/objects/structures/displaycase.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/stun.dm
Labels: Mapping, Tweak, Fix, Balance/Rebalance

#6667 Fixes whiteships and other shuttle ruins not loading
  _maps/shuttles/ruin_caravan_victim.dmm
  _maps/shuttles/ruin_pirate_cutter.dmm
  _maps/shuttles/ruin_syndicate_dropship.dmm
  _maps/shuttles/ruin_syndicate_fighter_shiv.dmm
  _maps/shuttles/whiteship_box.dmm
  _maps/shuttles/whiteship_cere.dmm
  _maps/shuttles/whiteship_delta.dmm
  _maps/shuttles/whiteship_fland.dmm
  _maps/shuttles/whiteship_meta.dmm
  _maps/shuttles/whiteship_pubby.dmm
  code/controllers/subsystem/shuttle.dm
  code/modules/shuttle/shuttle.dm
Labels: Mapping, Feature, Fix, Code Improvement, Testmerge Passed

#6113 Some orbital map improvements + supercruise code changes
  code/__DEFINES/orbit_defines.dm
  code/controllers/subsystem/processing/orbits.dm
  code/modules/shuttle/super_cruise/interface/orbital_map_interface.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_map.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_object.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/beacon.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/lavaland.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/meteor.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/phobos.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/shuttle.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/space_station.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/star.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/z_linked.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_vector.dm
  code/modules/shuttle/super_cruise/shuttle_components/shuttle_console.dm
  tgui/packages/tgui/components/OrbitalMapComponent.js
  tgui/packages/tgui/components/OrbitalMapSvg.js
  tgui/packages/tgui/components/index.js
  tgui/packages/tgui/interfaces/OrbitalMap.js
  tgui/packages/tgui/styles/interfaces/OrbitalMap.scss
Labels: Tweak, TGUI-Changes, Testmerge Passed

#6207 Reworks gentle bluespace/bluespace extract luminescent interaction
  code/modules/research/xenobiology/crossbreeding/gentle.dm
  code/modules/research/xenobiology/crossbreeding/regenerative.dm
  code/modules/research/xenobiology/xenobiology.dm
Labels: Balance/Rebalance, Removal

#6801 borgs can hold kpa normally again
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
Labels: Tweak

#6800 Speedmerge plz. Fixes a miners redeeming points they shouldn't.
  code/modules/mining/machine_processing.dm
Labels: Fix

#6787 Fixes various maintenance sofas
  _maps/RandomRooms/10x10/sk_rdm106_sanitarium.dmm
  _maps/RandomRooms/10x10/sk_rdm144_smallmagician.dmm
Labels: Mapping, Fix

#6062 Fixes a potential failure in clockcult setup, reworks stargazer enchantments
  beestation.dme
  code/game/gamemodes/clock_cult/clockcult.dm
  code/modules/antagonists/clock_cult/enchantments/_enchantment.dm
  code/modules/antagonists/clock_cult/enchantments/antimagic.dm
  code/modules/antagonists/clock_cult/enchantments/blocking.dm
  code/modules/antagonists/clock_cult/enchantments/burn.dm
  code/modules/antagonists/clock_cult/enchantments/electricution.dm
  code/modules/antagonists/clock_cult/enchantments/penetration.dm
  code/modules/antagonists/clock_cult/enchantments/sharpness.dm
  code/modules/antagonists/clock_cult/enchantments/soul_tap.dm
  code/modules/antagonists/clock_cult/enchantments/tiny.dm
  code/modules/antagonists/clock_cult/items/clockwork_item.dm
  code/modules/antagonists/clock_cult/scriptures/stargazer.dm
Labels: Fix, Refactor

#6445 Removes miasma, corpseflowers, and the rot component
  beestation.dme
  code/__DEFINES/atmospherics.dm
  code/__DEFINES/reactions.dm
  code/datums/components/rot.dm
  code/game/objects/effects/decals/cleanable/humans.dm
  code/modules/atmospherics/auxgm/gas_types.dm
  code/modules/atmospherics/gasmixtures/reactions.dm
  code/modules/atmospherics/machinery/airalarm.dm
  code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
  code/modules/atmospherics/machinery/portable/canister.dm
  code/modules/cargo/exports/large_objects.dm
  code/modules/hydroponics/grown/misc.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/simple_animal/bot/atmosbot.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/loot/alien_artifact.dm
  code/modules/surgery/organs/lungs.dm
Labels: Ike Like, Balance/Rebalance, Removal, Code Improvement

#6811 Adds supply Beret to the cargodrobe
  code/modules/vending/wardrobes.dm
Labels: Feature

#6804 Fixes certain gloves showing up as white gloves when worn
  code/modules/clothing/gloves/boxing.dm
  code/modules/clothing/gloves/miscellaneous.dm
Labels: Fix

#6806 Fixes dumb oversight in #6753
  code/modules/projectiles/guns/energy.dm
Labels: Fix

#6809 fixes space heater turn off when no active apc area
  code/game/machinery/spaceheater.dm
Labels: Fix

#6816 Fixes SM bumping with indestructable item crashing the server
  code/modules/power/supermatter/supermatter.dm
Labels: Fix, Server

#6768 Hopefully final crewmonitor fix
  code/game/machinery/computer/crew.dm
  code/modules/research/nanites/nanite_programs/utility.dm
Labels: Fix

#6631 Syndie Team Leaders start loudmode
  code/game/gamemodes/nuclear/nuclear.dm
Labels: Stale, Tweak, Vote Passed

#6830 Fixes alternate augment icons
  code/datums/diseases/advance/symptoms/clockwork.dm
  code/game/machinery/aug_manipulator.dm
  icons/mob/augmentation/augments_mining.dmi
Labels: Sprites, Fix

#6721 Adds score for biggest toxins bomb
  beestation.dme
  code/__DEFINES/achievements.dm
  code/datums/achievements/_achievement_data.dm
  code/datums/achievements/misc_scores.dm
  code/game/machinery/doppler_array.dm
  code/modules/client/client_procs.dm
Labels: Feature

#6724 Various improvements to multi-Z travel
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/debug/multiz.dmm
  beestation.dme
  code/game/atoms_movable.dm
  code/game/objects/structures/stairs.dm
  code/game/turfs/open/openspace.dm
  code/game/turfs/turf.dm
  code/modules/antagonists/blob/overmind.dm
  code/modules/antagonists/revenant/revenant_abilities.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_movement.dm
  code/modules/mob/mob_movement.dm
  code/modules/power/cable.dm
  code/modules/shuttle/super_cruise/shuttle_components/shuttle_docking.dm
  code/modules/vehicles/ridden.dm
  icons/obj/power_cond/cables.dmi
Labels: Mapping, Tweak, Feature, Sprites, Fix, Code Improvement, Server

#6786 fixes retaliate signal runtime and some possible harddeletes that would come out of this
  code/modules/mob/living/simple_animal/hostile/retaliate/retaliate.dm
Labels: Fix

#6281 Chemical Synthesizer rework
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/plumbing/plumbers/synthesizer.dm
Labels: Tweak, Fix, Balance/Rebalance, Removal

#6835 Fixes a minor mistake in the bomb score PR
  code/datums/achievements/_achievement_data.dm
Labels: Fix

#6836 Headspiders shouldn't teleport or headspider post-mortem
  code/modules/antagonists/changeling/powers/headcrab.dm
Labels: Fix

#6831 Getting implanted now gives the user an alert about it
  code/game/objects/items/implants/implanter.dm
Labels: Feature

#6827 Ketamine now causes a randomized trauma
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
Labels: Tweak

#6716 New Medikit sprites and a Randomized medkit
  code/game/objects/items/storage/firstaid.dm
  icons/mob/inhands/equipment/medical_lefthand.dmi
  icons/mob/inhands/equipment/medical_righthand.dmi
  icons/obj/storage.dmi
Labels: Voting, Feature, Sprites

#6843 Fixes clients being deleted before their disconnect reason is shown.
  code/modules/client/client_procs.dm
Labels: Fix, Somewhat Important

#6779 Yellow slime cores now have a more reasonable recharge rate
  code/modules/power/cell.dm
  code/modules/research/xenobiology/crossbreeding/_misc.dm
Labels: Balance/Rebalance

#6839 Properly escape keybind preference HTML (#6838)
  code/modules/client/preferences.dm
Labels: Fix

#6832 Adds some new emotes and an IPC dialup sound on revival
  code/datums/emotes.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/carbon/human/species_types/IPC.dm
  code/modules/mob/living/emote.dm
  sound/voice/dialup.ogg
Labels: Feature, Sound, Code Improvement

#6849 [PORT]Removes AOE hit detection from fireball
  code/datums/mutations/actions.dm
  code/modules/events/wizard/magicarp.dm
  code/modules/projectiles/ammunition/special/magic.dm
  code/modules/projectiles/guns/magic/staff.dm
  code/modules/projectiles/projectile/magic.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/research/experimentor.dm
  code/modules/spells/spell_types/aimed.dm
  code/modules/spells/spell_types/devil.dm
Labels: Balance/Rebalance

#6848 Removes unused TRAIT_APPRAISAL
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/modules/clothing/gloves/color.dm
  code/modules/reagents/reagent_containers/pill.dm
Labels: Removal

#6813 new icons for DNA Injectors, implanters and their cases
  code/game/objects/items/dna_injector.dm
  code/game/objects/items/implants/implantcase.dm
  code/game/objects/items/implants/implanter.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  icons/mob/inhands/equipment/medical_lefthand.dmi
  icons/mob/inhands/equipment/medical_righthand.dmi
  icons/obj/items_and_weapons.dmi
  icons/obj/syringe.dmi
Labels: Feature, Sprites, Fix, Vote Passed

#6858 Fixes cable joining
  code/modules/power/cable.dm
Labels: Fix

#6852 Protect against floating-point inaccuracy in log()
  code/__DEFINES/maths.dm
Labels: Fix

#6861 Fix tablet battery ejection
  code/modules/modular_computers/hardware/battery_module.dm
Labels: Fix

#6841 Fixes runtime when headspidering, fixes another changeling exploit and removes mentions of hivemind chat
  code/__DEFINES/say.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/changeling/powers/fakedeath.dm
  code/modules/antagonists/changeling/powers/headcrab.dm
  code/modules/mob/living/say.dm
  html/antagtips/changeling.html
Labels: Fix, Removal

#6824 Improves bubble alerts
  code/datums/chatmessage.dm
  code/datums/components/storage/concrete/rped.dm
  code/datums/components/storage/storage.dm
  code/datums/elements/rust.dm
  code/game/machinery/ecto_sniffer.dm
  code/game/mecha/combat/durand.dm
  code/game/mecha/equipment/tools/work_tools.dm
  code/game/mecha/mecha_actions.dm
  code/game/objects/items/control_wand.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/melee/energy.dm
  code/game/objects/items/melee/transforming.dm
  code/game/objects/items/stunbaton.dm
  code/game/objects/items/tools/powertools.dm
  code/game/objects/items/tools/weldingtool.dm
  code/game/objects/structures/catwalk.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/noticeboard.dm
  code/game/objects/structures/shower.dm
  code/game/objects/structures/watercloset.dm
  code/game/turfs/closed/wall/reinf_walls.dm
  code/game/turfs/closed/walls.dm
  code/game/turfs/turf.dm
  code/modules/atmospherics/machinery/components/binary_devices/passive_gate.dm
  code/modules/atmospherics/machinery/components/binary_devices/pressure_valve.dm
  code/modules/atmospherics/machinery/components/binary_devices/pump.dm
  code/modules/atmospherics/machinery/components/binary_devices/temperature_gate.dm
  code/modules/atmospherics/machinery/components/binary_devices/temperature_pump.dm
  code/modules/atmospherics/machinery/components/binary_devices/volume_pump.dm
  code/modules/atmospherics/machinery/components/trinary_devices/filter.dm
  code/modules/atmospherics/machinery/components/trinary_devices/mixer.dm
  code/modules/atmospherics/machinery/components/unary_devices/outlet_injector.dm
  code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/patch.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/surgery/helpers.dm
  code/modules/wiremod/components/usb_port.dm
  code/modules/wiremod/integrated_circuit.dm
  code/modules/wiremod/shell/compact_remote.dm
  code/modules/wiremod/shell/controller.dm
  code/modules/wiremod/shell/moneybot.dm
  code/modules/wiremod/shell/scanner.dm
  code/modules/wiremod/shell/server.dm
  code/modules/wiremod/usb_cable.dm
Labels: Tweak, Fix, Grammar and Formatting

#6814 Removes Gondolapockets from cargo
  code/modules/cargo/packs.dm
Labels: Tweak, Removal

#6854 [PORT] Vended items now go into hand
  code/modules/vending/_vending.dm
Labels: Tweak

#6865 cp1251 -> UTF8
  code/modules/mob/living/say.dm
Labels: Fix

#6872 Fixes those huge gaps in between the apid names.
  strings/names/apid_first_female.txt
Labels: Fix

#6807 Positronic Brain spawns limited to 1/round.
  code/_globalvars/lists/mobs.dm
  code/modules/mob/living/brain/posibrain.dm
Labels: Tweak

#6876 Fixes misleading ritual information in Flesh Path
  code/modules/antagonists/eldritch_cult/knowledge/flesh_lore.dm
Labels: Fix

#6135 EMP Effect Update
  code/__DEFINES/layers.dm
  code/__DEFINES/obj_flags.dm
  code/_onclick/hud/plane_master.dm
  code/game/alternate_appearance.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/telecomms/machine_interactions.dm
  code/game/machinery/telecomms/telecomunications.dm
  code/game/objects/items/stunbaton.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/clothing/suits/reactive_armour.dm
  code/modules/mob/mob.dm
  code/modules/power/power.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  code/modules/projectiles/guns/energy/pulse.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/misc/beam_rifle.dm
  code/modules/research/server.dm
  sound/machines/capacitor_charge.ogg
  sound/machines/capacitor_discharge.ogg
Labels: Tweak, Balance/Rebalance, Sound

#6658 Makes tongues control the say mods instead of species
  code/modules/language/language_holder.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/IPC.dm
  code/modules/mob/living/carbon/human/species_types/abductors.dm
  code/modules/mob/living/carbon/human/species_types/android.dm
  code/modules/mob/living/carbon/human/species_types/apid.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/mob/living/carbon/human/species_types/oozelings.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
  code/modules/mob/living/carbon/human/species_types/snail.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/surgery/organs/tongue.dm
  icons/obj/surgery.dmi
Labels: Tweak, Feature, Sprites

#6871 Contracted mobs wont recieve toxin damage by mistake anymore
  code/modules/antagonists/traitor/syndicate_contract.dm
Labels: Fix

#6850 [PORT] New floor borders and new broken floor glass
  code/game/objects/effects/decals/turfdecal/markings.dm
  icons/turf/decals.dmi
  icons/turf/floors.dmi
Labels: Feature, Sprites

#6728 Assistant heirloom adjustments
  code/datums/traits/negative.dm
  code/game/objects/items/storage/toolbox.dm
  code/modules/clothing/gloves/color.dm
Labels: Tweak, Feature, Fix, Balance/Rebalance, Removal

#6891 Fixes shuttle parallax
  code/_onclick/hud/parallax.dm
Labels: Fix, Somewhat Important

#6884 Cleanup dead code uses of "drop_item"
  code/_onclick/telekinesis.dm
  code/game/mecha/mecha.dm
  code/modules/mob/mob_movement.dm
Labels: Removal, Code Improvement

#6775 Fixes bugged behaviour with jumpsuits
  code/modules/clothing/under/_under.dm
Labels: Fix

#6890 Adds plasmaglass shard spear righthand and back sprites
  icons/mob/clothing/back.dmi
  icons/mob/inhands/weapons/polearms_lefthand.dmi
  icons/mob/inhands/weapons/polearms_righthand.dmi
Labels: Tweak, Sprites, Fix

#6870 Fixes odd mismatching icons on the manual valve
  icons/obj/atmospherics/components/binary_devices.dmi
Labels: Sprites, Fix

#6859 Explosive ducks now have a brief, dramatic delay before exploding
  code/game/objects/effects/mines.dm
Labels: Tweak, Fix, Removal

#6881 Inducers are now clearly different and printable in their respective lathes
  code/game/objects/items/inducer.dm
  code/modules/cargo/packs.dm
  code/modules/research/designs/power_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Tweak, Feature, Balance/Rebalance

#6866 Moth plush update + small tweaks to the plushes overall
  code/game/machinery/computer/arcade.dm
  code/game/objects/items/plushes.dm
  code/modules/research/xenobiology/crossbreeding/warping.dm
  icons/mob/inhands/plushes_lefthand.dmi
  icons/mob/inhands/plushes_righthand.dmi
  icons/obj/plushes.dmi
Labels: Feature, Sprites

#6896 [s] Removes protected variable exploit
  code/controllers/globals.dm
Labels: Fix

#6195 Adds Force Cryo as a Smite
  beestation.dme
  code/__DEFINES/admin.dm
  code/modules/admin/verbs/forcecryo.dm
  code/modules/admin/verbs/randomverbs.dm
Labels: Administration

#6902 Fixes an error in quirk mob transfer
  code/datums/traits/_quirk.dm
Labels: Fix, Code Improvement

#6900 Fingerguns can't trigger reactive armor
  code/modules/clothing/suits/reactive_armour.dm
Labels: Fix

#5624 2021 viro expansion pack
  beestation.dme
  code/__DEFINES/DNA.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/movespeed_modification.dm
  code/__DEFINES/status_effects.dm
  code/__DEFINES/traits.dm
  code/datums/diseases/_disease.dm
  code/datums/diseases/advance/advance.dm
  code/datums/diseases/advance/presets.dm
  code/datums/diseases/advance/symptoms/alcohol.dm
  code/datums/diseases/advance/symptoms/clockwork.dm
  code/datums/diseases/advance/symptoms/gravity.dm
  code/datums/diseases/advance/symptoms/heal.dm
  code/datums/diseases/advance/symptoms/kitty.dm
  code/datums/diseases/advance/symptoms/light.dm
  code/datums/diseases/advance/symptoms/meme.dm
  code/datums/diseases/advance/symptoms/organs.dm
  code/datums/diseases/advance/symptoms/radiation.dm
  code/datums/diseases/advance/symptoms/sensory.dm
  code/datums/diseases/advance/symptoms/skin.dm
  code/datums/diseases/advance/symptoms/spiked.dm
  code/datums/diseases/advance/symptoms/symptoms.dm
  code/datums/diseases/advance/symptoms/viral.dm
  code/datums/diseases/appendicitis.dm
  code/datums/mood_events/generic_negative_events.dm
  code/datums/mood_events/generic_positive_events.dm
  code/datums/status_effects/debuffs.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/food_and_drinks/food/snacks/meat.dm
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/species_types/vampire.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/silicon/damage_procs.dm
  code/modules/mob/living/simple_animal/hostile/redgrub.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/bottle.dm
  icons/mob/animal.dmi
  icons/mob/screen_alert.dmi
  icons/obj/food/food.dmi
Labels: Test Merged, Feature, Sprites, Removal

#6910 Removes gravity symptom
  beestation.dme
  code/datums/diseases/advance/symptoms/gravity.dm
Labels: Removal

#6899 Fixes hiero staff being usable with sleeping carp
  code/modules/mining/lavaland/necropolis_chests.dm
Labels: Fix

#6908 Tim's Hard-Del Crusade: Radial Menu Center Buttons
  code/_onclick/hud/radial.dm
Labels: Fix

#6913 Fix: Belt overlay not updating on dumping items
  code/game/atoms.dm
Labels: Fix

#6845 adds a check for moveloops to check if the loop it tries to add already exists
  code/controllers/subsystem/movement/move_handler.dm
  code/controllers/subsystem/movement/movement_types.dm
Labels: Feature, Fix, Removal, Testmerge Passed

#6746 New PDA and Cartridges Icons
  code/game/machinery/PDApainter.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/PDA_types.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/game/objects/items/devices/PDA/virus_cart.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/botanist.dm
  code/modules/jobs/job_types/brigphys.dm
  code/modules/jobs/job_types/deputy.dm
  code/modules/jobs/job_types/emt.dm
  code/modules/jobs/job_types/gimmick.dm
  icons/obj/pda.dmi
Labels: Voting, Tweak, Feature, Sprites, Fix, Testmerge Passed

#6452 Re-Add Psychotic Brawling for Bath Salts
  beestation.dme
  code/datums/martial/psychotic_brawl.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
Labels: Feature, Balance/Rebalance

#6495 Moth wings can now open
  code/__HELPERS/global_lists.dm
  code/_globalvars/lists/flavor_misc.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/emote.dm
  code/modules/surgery/organs/wings.dm
  icons/mob/moth_wingsopen.dmi
Labels: Tweak, Feature, Sprites

#6914 Speeds up blob spores (again) and fixes some runtimes in the moveloop
  code/controllers/subsystem/movement/movement_types.dm
  code/modules/antagonists/blob/blob_mobs.dm
Labels: Fix, Balance/Rebalance, Removal

#6825 Adds printable medipens
  code/modules/research/designs/medical_designs.dm
  code/modules/research/machinery/_production.dm
  code/modules/research/techweb/all_nodes.dm
  tgui/packages/tgui/interfaces/TechFab.js
Labels: Tweak, Feature, TGUI-Changes

#6714 Adds mute quirk (this time it's neutral)
  code/controllers/subsystem/processing/quirks.dm
  code/datums/traits/neutral.dm
Labels: Feature, Balance/Rebalance

#6918 Makes spider directives more obvious
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  interface/stylesheet.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: Tweak, TGUI-Changes

#6921 Fixes a harddel with heretic blades
  code/modules/antagonists/eldritch_cult/eldritch_items.dm
Labels: Fix, Removal

#6685 All shuttles now have sound
  code/modules/shuttle/arrivals.dm
  code/modules/shuttle/docking.dm
  code/modules/shuttle/emergency.dm
  code/modules/shuttle/shuttle.dm
Labels: Feature, Sound

#6758 Fixes changeling abilities.
  code/datums/status_effects/buffs.dm
Labels: Fix

#6772 So that should fix that plane_master_controller harddel
  code/_onclick/hud/map_popups.dm
  code/game/machinery/computer/camera.dm
  code/game/objects/items/devices/spyglasses.dm
  code/modules/modular_computers/file_system/programs/secureye.dm
  code/modules/projectiles/ammunition/caseless/_caseless.dm
  code/modules/projectiles/guns/ballistic.dm
Labels: Fix, Removal, Good PR

#6715 Forensic scanners can no longer be printed
  code/modules/research/techweb/all_nodes.dm
Labels: Balance/Rebalance

#6684 Updates the labor camp consoles to reflect new space law
  code/game/machinery/computer/prisoner/gulag_teleporter.dm
  code/game/machinery/computer/prisoner/management.dm
  code/game/machinery/gulag_item_reclaimer.dm
  code/game/machinery/gulag_teleporter.dm
  code/game/objects/items/cards_ids.dm
  code/modules/mining/laborcamp/laborstacker.dm
  tgui/packages/tgui/interfaces/GulagTeleporterConsole.js
Labels: Feature, TGUI-Changes

#6629 nerfs silver extracts
  code/__HELPERS/unsorted.dm
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
Labels: Balance/Rebalance

#6905 Fixes eminence getting flashbanged and vendors throwing items at it
  code/__HELPERS/radiation.dm
  code/modules/antagonists/clock_cult/mobs/eminence.dm
  code/modules/antagonists/revenant/revenant.dm
  code/modules/vending/_vending.dm
Labels: Fix

#6793 Refactors item giving
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/status_effects.dm
  code/_onclick/hud/alert.dm
  code/datums/traits/neutral.dm
  code/game/objects/items.dm
  code/game/objects/items/weaponry.dm
  code/modules/mob/living/carbon/inventory.dm
Labels: Feature, Fix, Refactor, Code Improvement

#6502 Quadruple Sec/Quintuple Sec nerf and Silencer/Papier Blanc rebalance
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Labels: Tweak, Balance/Rebalance

#6558 chemical flag refactoring for random chemical / can_synth check
  code/__DEFINES/reagents.dm
  code/game/mecha/equipment/tools/medical_tools.dm
  code/modules/antagonists/blob/blobstrains/_reagent.dm
  code/modules/antagonists/blob/blobstrains/blazing_oil.dm
  code/modules/antagonists/blob/blobstrains/electromagnetic_web.dm
  code/modules/antagonists/blob/blobstrains/energized_jelly.dm
  code/modules/antagonists/blob/blobstrains/explosive_lattice.dm
  code/modules/antagonists/blob/blobstrains/networked_fibers.dm
  code/modules/antagonists/blob/blobstrains/pressurized_slime.dm
  code/modules/antagonists/blob/blobstrains/reactive_spines.dm
  code/modules/antagonists/blob/blobstrains/regenerative_materia.dm
  code/modules/antagonists/blob/blobstrains/replicating_foam.dm
  code/modules/antagonists/blob/blobstrains/shifting_fragments.dm
  code/modules/antagonists/blob/blobstrains/synchronous_mesh.dm
  code/modules/antagonists/blob/blobstrains/zombifying_pods.dm
  code/modules/crew_objectives/civilian_objectives.dm
  code/modules/crew_objectives/medical_objectives.dm
  code/modules/food_and_drinks/food/snacks_egg.dm
  code/modules/hydroponics/seeds.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/simple_animal/hostile/jungle/leaper.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/vehicles/cars/clowncar.dm
Labels: Tweak, Feature, Refactor, Code Improvement, Testmerge Passed

#6566 Makes clockcult more robust against antag_pick failures
  code/game/gamemodes/clock_cult/clockcult.dm
  code/game/gamemodes/game_mode.dm
Labels: Fix

#6493 Ports holding down space to toggle throw mode from tg
  code/__DEFINES/combat.dm
  code/__DEFINES/keybinding.dm
  code/__DEFINES/mobs.dm
  code/_onclick/click.dm
  code/datums/keybinding/carbon.dm
  code/game/gamemodes/clown_ops/clown_weapons.dm
  code/game/objects/items/melee/misc.dm
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/client/preferences_savefile.dm
  code/modules/hydroponics/grown/citrus.dm
  code/modules/keybindings/bindings_client.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/mob_defines.dm
  code/modules/ninja/suit/n_suit_verbs/ninja_stars.dm
  code/modules/paperwork/paperplane.dm
  code/modules/spells/spell_types/wizard.dm
  code/modules/surgery/organs/vocal_cords.dm
Labels: Feature

#6671 Shuttle Docking Camera now changes size to the shuttle size + Fixes hyperspace being an area on all shuttles
  code/modules/shuttle/shuttle.dm
  code/modules/shuttle/super_cruise/shuttle_components/shuttle_console.dm
  code/modules/shuttle/super_cruise/shuttle_components/shuttle_docking.dm
Labels: Fix, Refactor, Somewhat Important, Testmerge Passed

#6823 Fixes/improves the automute filter
  code/modules/admin/verbs/randomverbs.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Fix, Administration

#6808 fixes anchored bug with contaiment field gens and change glass to plasma on deltastation
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Mapping, Tweak, Fix, Removal

#6652 Spirit realm now only sustains 1 cult ghost
  code/modules/antagonists/cult/runes.dm
Labels: Balance/Rebalance

#6627 Fix light eater not being able to break mech lights or wisps
  code/__DEFINES/dcs/signals.dm
  code/game/atoms.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_actions.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/photography/camera/silicon_camera.dm
Labels: Tweak, Fix

#6688 Buffs laser shotgun shells.
  code/modules/projectiles/projectile/beams.dm
Labels: Balance/Rebalance

#6867 Adds integration cog and replica fabricator toys
  code/game/machinery/computer/arcade.dm
  code/game/objects/items/toys.dm
Labels: Feature

#6743 Ports Atom Initialize fixes for mapload/round initialize
  code/controllers/subsystem/atoms.dm
Labels: Needs Testmerge, Fix

#6930 fixes sparks/atom subsystem breaking
  code/controllers/subsystem/atoms.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/ruin_generator.dm
Labels: Test Merged, Fix

#6894 Fixes slimes being unable to feed on buckled players
  code/modules/mob/mob.dm
Labels: Fix

#6776 Map votes now draw from a hat
  code/controllers/subsystem/vote.dm
  code/modules/client/preferences.dm
Labels: Tweak, Good PR

#6934 Fix RCL icon not updating after refilling an empty RCL
  code/game/objects/items/RCL.dm
Labels: Fix

#6932 fixes a small bug with Hematophagy
  code/datums/diseases/advance/symptoms/heal.dm
Labels: Fix

#6754 PTSD: Now standard issue for all heads of staff
  code/game/objects/items/melee/misc.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
  code/modules/projectiles/guns/energy/stun.dm
  icons/obj/guns/energy.dmi
Labels: Feature, Sprites, Balance/Rebalance

#6893 Wallshoves, kick stuns and disarms v4
  code/__DEFINES/combat.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Tweak, Feature, Balance/Rebalance, Removal, Testmerge Passed, Good PR

#6931 Simplifies and improves lone op counter
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
Labels: Tweak

#6939 Fixes hulk yelling being permanent
  code/datums/mutations/hulk.dm
Labels: Fix

#6938 Add radiation to the Supermatter Monitor
  code/modules/modular_computers/file_system/programs/sm_monitor.dm
  code/modules/power/supermatter/supermatter.dm
  tgui/packages/tgui/interfaces/NtosSupermatterMonitor.js
Labels: Feature, TGUI-Changes

#6944 Fixes not being able to throw people
  code/_onclick/click.dm
Labels: Fix

#6949 Fixes <span class='sans'> in wacky mutation
  code/datums/mutations/speech.dm
Labels: Fix

#6745 Stimulum has a drawback again, and also flavor text
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Tweak, Fix, Balance/Rebalance

#6796 Refactors some xenobio extract code
  code/modules/research/xenobiology/crossbreeding/gentle.dm
  code/modules/research/xenobiology/crossbreeding/regenerative.dm
  code/modules/research/xenobiology/xenobiology.dm
Labels: Tweak, Refactor, Code Improvement

#6819 Character-based gear loadouts
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: Feature

#6875 [PORT] TG's maid costume
  code/modules/clothing/gloves/color.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/neck/_neck.dm
  code/modules/vending/autodrobe.dm
  icons/mob/accessories.dmi
  icons/mob/clothing/hands.dmi
  icons/mob/clothing/head.dmi
  icons/mob/clothing/uniform.dmi
  icons/mob/neck.dmi
  icons/obj/clothing/accessories.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/neck.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, Sprites, Fix

#6924 Document and refactor the current situation with WIRE_IDSCAN.
  code/datums/wires/airlock.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/windowdoor.dm
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/jobs/access.dm
Labels: Refactor

#6886 Refactor handling of movement with modifier keys
  code/__DEFINES/keybinding.dm
  code/datums/keybinding/keybinding.dm
  code/datums/keybinding/mob.dm
  code/game/atoms.dm
  code/modules/client/preferences_savefile.dm
  code/modules/keybindings/bindings_atom.dm
  code/modules/keybindings/bindings_client.dm
  code/modules/mob/mob.dm
Labels: Fix, Removal

#6963 Fixes the extra "the" when stripping someone
  code/datums/elements/strippable.dm
  code/modules/mob/living/living.dm
Labels: Fix

#6937 changes automute logic back to old timing logic(purly logic not code)
  code/modules/client/client_procs.dm
Labels: Tweak

#6954 Monke small fix
  code/modules/mob/living/living.dm
Labels: Fix

#6975 Revert "Monke small fix (#6954)"
  code/modules/mob/living/living.dm
Labels: Tweak, Feature, Sprites, Fix, Grammar and Formatting, Config Update, Balance/Rebalance, Refactor, Sound, Administration, Removal, Code Improvement, Server

#6971 Fixes a harddel with atmos backpack nozzle
  code/game/objects/items/tanks/watertank.dm
Labels: Fix, Removal

#6968 Fixes href logging
  code/modules/client/client_procs.dm
Labels: THIS IS VERY IMPORTANT, Fix

#6961 Fixes move-upwards and move-downwards
  code/game/turfs/turf.dm
Labels: Fix

#6952 fixes warping grey extracts
  code/modules/research/xenobiology/crossbreeding/warping.dm
Labels: Fix

#6928 reworks random code generator (for nuke codes and technically pda antag uplinks)
  code/__HELPERS/unsorted.dm
  code/datums/components/uplink.dm
  code/modules/admin/topic.dm
  code/modules/antagonists/nukeop/nukeop.dm
  code/modules/paperwork/paper.dm
  code/modules/requests/request_manager.dm
Labels: Feature, Refactor, Administration, Code Improvement

#6972 Removes the redundant species ID from limb names
  code/modules/surgery/bodyparts/bodyparts.dm
Labels: Grammar and Formatting

#6982 Updates CODEOWNERS
  .github/CODEOWNERS
Labels: GitHub

#6990 Fixes a missing string on the power flow control console's emag_act
  code/game/machinery/computer/apc_control.dm
Labels: Fix
