Repository BeeStation/BeeStation-Hornet, pull requests merged in 2022-09, with the labels that each got.

#7533 Corg Maint Airlock, Wiring, Service Lathe Fixes
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: Mapping, Tweak, Feature, Fix, Removal

#7356 Nuke ops now get an extra 10 minutes before the shuttle can be called.
  code/modules/antagonists/nukeop/equipment/nuclear_challenge.dm
Labels: Balance/Rebalance

#7342 Space Carp Sect
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/religion/religion_sects.dm
  code/modules/religion/rites.dm
Labels: Feature, Server

#7327 Tweaks to Technophile Sect
  code/modules/religion/religion_sects.dm
  code/modules/religion/rites.dm
Labels: Tweak, Feature

#7551 ModPC Update V2
  beestation.dme
  code/__DEFINES/machines.dm
  code/__DEFINES/supermatter.dm
  code/game/machinery/computer/card.dm
  code/game/objects/items/devices/pressureplates.dm
  code/modules/assembly/signaler.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/jobs/job_types/scientist.dm
  code/modules/modular_computers/NTNet/NTNRC/conversation.dm
  code/modules/modular_computers/computers/item/computer.dm
  code/modules/modular_computers/computers/item/computer_components.dm
  code/modules/modular_computers/computers/item/tablet_presets.dm
  code/modules/modular_computers/file_system/program.dm
  code/modules/modular_computers/file_system/programs/atmosscan.dm
  code/modules/modular_computers/file_system/programs/card.dm
  code/modules/modular_computers/file_system/programs/file_browser.dm
  code/modules/modular_computers/file_system/programs/jobmanagement.dm
  code/modules/modular_computers/file_system/programs/ntdownloader.dm
  code/modules/modular_computers/file_system/programs/ntnrc_client.dm
  code/modules/modular_computers/file_system/programs/robocontrol.dm
  code/modules/modular_computers/file_system/programs/signaller.dm
  code/modules/modular_computers/file_system/programs/sm_monitor.dm
  code/modules/modular_computers/hardware/CPU.dm
  code/modules/modular_computers/hardware/_hardware.dm
  code/modules/modular_computers/hardware/ai_slot.dm
  code/modules/modular_computers/hardware/battery_module.dm
  code/modules/modular_computers/hardware/card_slot.dm
  code/modules/modular_computers/hardware/hard_drive.dm
  code/modules/modular_computers/hardware/modules.dm
  code/modules/modular_computers/hardware/portable_disk.dm
  code/modules/modular_computers/hardware/recharger.dm
  code/modules/power/supermatter/supermatter.dm
  code/modules/research/designs/computer_part_designs.dm
  code/modules/vending/modularpc.dm
  icons/obj/modular_laptop.dmi
  icons/obj/modular_tablet.dmi
  icons/obj/module.dmi
  tgui/packages/tgui/interfaces/NtosAtmos.js
  tgui/packages/tgui/interfaces/NtosFileManager.js
  tgui/packages/tgui/interfaces/NtosNetChat.js
  tgui/packages/tgui/interfaces/NtosNetDownloader.js
  tgui/packages/tgui/interfaces/NtosSignaller.js
  tgui/packages/tgui/interfaces/NtosSupermatterMonitor.js
  tgui/packages/tgui/interfaces/Signaler.js
Labels: Tweak, Feature, Sprites, Fix, Refactor, Removal, Code Improvement, Server, TGUI-Changes

#7440 A new wizard ritual, New apprentice "Wild Magic" school with two random spells
  code/__DEFINES/antagonists.dm
  code/modules/antagonists/_common/antag_spawner.dm
  code/modules/antagonists/wizard/equipment/spellbook.dm
  code/modules/antagonists/wizard/wizard.dm
Labels: Feature, Fix, Refactor, Code Improvement

#7530 Tweaks changeling readapting
  code/modules/antagonists/changeling/changeling.dm
Labels: Balance/Rebalance

#7330 VIP gets their own department budget than the civilian budget, and gets paid from it. (+department account lock feature)
  code/__DEFINES/economy.dm
  code/__HELPERS/jobs.dm
  code/controllers/subsystem/economy.dm
  code/game/machinery/PDApainter.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/cloning.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/mail.dm
  code/modules/economy/account.dm
  code/modules/jobs/job_types/gimmick.dm
  code/modules/modular_computers/file_system/programs/budgetordering.dm
Labels: Tweak, Feature, Fix, Refactor

#7576 Traitors get two regular objectives in addition to the gimmick one
  code/modules/antagonists/traitor/datum_traitor.dm
Labels: Feature

#7594 Fix for Corporate Benches and Chair deconstruction + Time to build for chairs
  code/datums/greyscale/greyscale_configs.dm
  code/datums/greyscale/json_configs/corporate_bench_left.json
  code/datums/greyscale/json_configs/corporate_bench_middle.json
  code/datums/greyscale/json_configs/corporate_bench_right.json
  code/datums/mutable_appearance.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/beds_chairs/bench.dm
  code/game/objects/structures/beds_chairs/chair.dm
  icons/obj/beds_chairs/benches.dmi
Labels: Mapping, Feature, Sprites, Fix

#7320 Beer goggles now can measure Booze power and expect tastes
  code/__DEFINES/obj_flags.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/unsorted.dm
  code/_globalvars/bitfields.dm
  code/game/atoms.dm
  code/modules/awaymissions/corpse.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/jobs/job_types/bartender.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/mob_helpers.dm
  code/modules/shuttle/special.dm
Labels: Feature

#7393 Makes a fake all-access card dispenser
  code/_globalvars/lists/maintenance_loot.dm
  code/game/machinery/allaccess.dm
  code/game/machinery/computer/arcade.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/toys.dm
  icons/obj/card.dmi
Labels: Tweak, Feature, Sprites

#7502 Refactors area moods to optionally restrict to jobs (+ new area moods!)
  code/datums/components/mood.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas.dm
Labels: Feature, Refactor

#7482 Adjusts oozelings to use slime speaking verbs
  code/modules/mob/living/carbon/human/say.dm
  code/modules/surgery/organs/tongue.dm
Labels: Tweak, Refactor

#7597 [Testmerge] Revert "Brings our MC up to date with TG"
  beestation.dme
  code/__DEFINES/MC.dm
  code/__DEFINES/_tick.dm
  code/controllers/admin.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/failsafe.dm
  code/controllers/globals.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/controllers/subsystem/augury.dm
  code/controllers/subsystem/blackbox.dm
  code/controllers/subsystem/disease.dm
  code/controllers/subsystem/garbage.dm
  code/controllers/subsystem/input.dm
  code/controllers/subsystem/metrics.dm
  code/controllers/subsystem/nightshift.dm
  code/controllers/subsystem/profiler.dm
  code/controllers/subsystem/server_maint.dm
  code/controllers/subsystem/shuttle.dm
  code/controllers/subsystem/stat.dm
  code/controllers/subsystem/sun.dm
  code/controllers/subsystem/time_track.dm
  code/controllers/subsystem/title.dm
  code/datums/helper_datums/stack_end_detector.dm
  code/datums/weather/weather.dm
  code/game/objects/structures/traps.dm
  code/game/world.dm
  code/modules/admin/view_variables/reference_tracking.dm
  code/modules/power/lighting.dm
  code/modules/tgchat/to_chat.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/subsystem_metric_sanity.dm
  config/config.txt
Labels: Test Merged, Config Update, Administration

#7351 [TG PORT] Removes Robot Commands and replaces it with an integrated control tablet program + silicons start with HUD on
  beestation.dme
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/ai.dm
  code/_onclick/hud/robot.dm
  code/datums/wires/robot.dm
  code/game/machinery/computer/robot.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/mob/living/silicon/robot/death.dm
  code/modules/mob/living/silicon/robot/emote.dm
  code/modules/mob/living/silicon/robot/laws.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_defense.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/modular_computers/computers/item/computer.dm
  code/modules/modular_computers/computers/item/computer_ui.dm
  code/modules/modular_computers/computers/item/tablet.dm
  code/modules/modular_computers/computers/item/tablet_presets.dm
  code/modules/modular_computers/computers/machinery/modular_computer.dm
  code/modules/modular_computers/file_system/programs/antagonist/revelation.dm
  code/modules/modular_computers/file_system/programs/borg_monitor.dm
  code/modules/modular_computers/file_system/programs/borg_self_monitor.dm
  code/modules/modular_computers/hardware/hard_drive.dm
  code/modules/modular_computers/hardware/network_card.dm
  code/modules/modular_computers/hardware/recharger.dm
  code/modules/photography/camera/silicon_camera.dm
  code/modules/tgui/states.dm
  icons/mob/screen_cyborg.dmi
  icons/program_icons/borg_self_monitor.gif
  tgui/packages/tgui/interfaces/NtosCyborgSelfMonitor.js
  tgui/packages/tgui/interfaces/NtosMain.js
Labels: Tweak, Feature, Sprites, Removal, TGUI-Changes

#7489 [TG PORT] Replaces rust wave with entropic plume
  beestation.dme
  code/__DEFINES/status_effects.dm
  code/datums/status_effects/debuffs.dm
  code/game/turfs/closed/wall/reinf_walls.dm
  code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
  code/modules/antagonists/eldritch_cult/eldritch_magic.dm
  code/modules/antagonists/eldritch_cult/knowledge/rust_lore.dm
  code/modules/spells/spell_types/cone_spells.dm
  icons/effects/160x160.dmi
  icons/effects/eldritch.dmi
  icons/mob/actions/actions_elites.dmi
Labels: Feature, Sprites, Fix, Removal, Needs Wiki Changes

#7605 Removes an unused proc `/obj/item/proc/GetJobName()` from the code
  code/modules/jobs/access.dm
Labels: Code Improvement

#7598 Fix client timers having invalid <1ds waits
  code/controllers/subsystem/timer.dm
Labels: Code Improvement

#7596 Make icon2base64 calls use frame=1
  code/game/objects/structures/displaycase.dm
  code/modules/vending/_vending.dm
Labels: Fix

#7608 Fix spawning multiple pirate ships and refactor comms console answer keys
  code/__DEFINES/misc.dm
  code/game/machinery/computer/communications.dm
  code/modules/events/pirates.dm
  tgui/packages/tgui/interfaces/CommunicationsConsole.js
Labels: Fix, Refactor, TGUI-Changes

#7311 Abductees no longer get deep rooted trauma once given objectives
  code/modules/antagonists/abductor/abductor.dm
Labels: Tweak, Needs Testing Evidence

#7614 Bulldog shotguns have inhand sprites again
  code/modules/projectiles/guns/ballistic/shotgun.dm
Labels: Fix

#7609 adds an option menu for card style from agent card forging
  code/game/machinery/PDApainter.dm
  code/game/objects/items/cards_ids.dm
Labels: Feature, Code Improvement

#7446 adds in a midround zombie outbreak event
  beestation.dme
  code/modules/events/wizard/blobies.dm
  code/modules/events/zombie_outbreak.dm
Labels: Tweak, Feature

#7587 [PORT] Bot Multi-Z Movement
  beestation.dme
  code/__DEFINES/bot_defines.dm
  code/_globalvars/lists/objects.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/game/objects/structures/bot_elevator.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/mulebot.dm
  code/modules/modular_computers/file_system/programs/robocontrol.dm
  icons/obj/structures/bot_elevator.dmi
Labels: Feature, Sprites

#7562 Exempts all medical staff from Doctor's Delight hunger drain by adding a new medical_metabolism mind trait.
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/modules/jobs/job_types/brig_physician.dm
  code/modules/jobs/job_types/chemist.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/geneticist.dm
  code/modules/jobs/job_types/gimmick.dm
  code/modules/jobs/job_types/medical_doctor.dm
  code/modules/jobs/job_types/paramedic.dm
  code/modules/jobs/job_types/virologist.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
Labels: Tweak, Feature

#7414 Creates a Janitor Bluespace Light Replacer
  code/game/objects/items/devices/lightreplacer.dm
  code/modules/research/designs/power_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/obj/janitor.dmi
Labels: Tweak, Feature, Sprites

#7610 icon2html optimizations
  code/__DEFINES/flags.dm
  code/__HELPERS/icon_smoothing.dm
  code/__HELPERS/icons.dm
  code/game/machinery/doors/airlock.dm
  code/modules/asset_cache/asset_cache_item.dm
  code/modules/asset_cache/transports/asset_transport.dm
Labels: Refactor, Code Improvement, Good PR

#7616 Pai cards flash and play a noise when a ghost submits
  code/game/objects/items/devices/paicard.dm
  icons/obj/aicards.dmi
Labels: Tweak, Sprites

#7623 Inform dead AIs of their revival from modpc app
  code/modules/modular_computers/file_system/programs/airestorer.dm
Labels: Fix

#7626 Shuttle engines and emitters apply wrenching from before the board is…
  code/game/shuttle_engines.dm
  code/modules/power/singularity/emitter.dm
Labels: Feature, Fix

#7634 Restores and Updates Turbine Sprites
  icons/obj/atmospherics/pipes/simple.dmi
Labels: Feature, Sprites

#7595 Remove ! from all verbs and add to check_grep + check_grep improvements
  code/modules/mob/dead/dead.dm
  code/modules/mob/dead/observer/observer.dm
  tools/ci/check_grep.sh
Labels: Fix, Tools, Code Improvement

#7641 Fix linux auxmos performance with one easy trick
  code/_compile_options.dm
Labels: Server

#7643 Adds the Magic Eightball to the BeeCoin shop
  code/modules/client/loadout/loadout_general.dm
Labels: Feature

#7642 Fixes plasma anti-wildlife turrets
  code/game/machinery/porta_turret/portable_turret.dm
Labels: Fix

#7652 Make PAI is now in admin panel
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
Labels: Administration

#7272 Bumps Auxmos from 0.2.4 to 1.1.2
  auxtools/auxmos.dll
  code/modules/atmospherics/auxgm/gas_types.dm
  code/modules/atmospherics/gasmixtures/auxgm.dm
  code/modules/atmospherics/gasmixtures/gas_mixture.dm
  code/modules/atmospherics/gasmixtures/reactions.dm
  dependencies.sh
Labels: Server

#7657 Fix pirate ship spawning again
  code/modules/events/pirates.dm
Labels: Fix

#7656 slimepeople now take damage from zombie tumors
  code/modules/zombie/organs.dm
Labels: Balance/Rebalance

#7478 [PORT] Port of shielded component
  beestation.dme
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/layers.dm
  code/datums/components/shielded.dm
  code/game/objects/items.dm
  code/game/objects/items/holy_weapons.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/suits/wiz_robe.dm
Labels: Feature, Removal, Somewhat Important

#7577 magic mirror no longer shows standard makeup window
  code/game/objects/structures/mirror.dm
Labels: Fix

#7625 Add Ghost SM Monitoring
  code/game/objects/effects/countdown.dm
  code/modules/antagonists/roundstart_special/undercover/undercover.dm
  code/modules/modular_computers/file_system/programs/sm_monitor.dm
  code/modules/power/supermatter/supermatter.dm
  tgui/packages/tgui/interfaces/NtosSupermatterMonitor.js
  tgui/packages/tgui/interfaces/SupermatterMonitor.js
Labels: Feature, TGUI-Changes

#7343 Necro Sect - New Rite, Speed and Cost Tweaks, Bugfix
  beestation.dme
  code/modules/religion/religion_sects.dm
  code/modules/religion/rites.dm
  code/modules/spells/spell_types/lesserlichdom.dm
Labels: Tweak, Feature, Fix

#7159 Edited Hub Entry
  code/game/world.dm
Labels: Feature

#7629 Dynamic Incursion
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/incursion/incursion.dm
  code/modules/antagonists/incursion/incursion.dm
Labels: Feature

#7591 [PORT] Lighting improvements and cleanup
  code/controllers/subsystem/lighting.dm
  code/game/turfs/change_turf.dm
  code/modules/lighting/lighting_corner.dm
  code/modules/lighting/lighting_object.dm
  code/modules/lighting/lighting_source.dm
  code/modules/lighting/lighting_turf.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/loot/alien_artifact.dm
Labels: Code Improvement

#7621 Adds station name to the announcements welcomer
  code/game/machinery/announcement_system.dm
  tgui/packages/tgui/interfaces/AutomatedAnnouncement.js
Labels: Tweak, TGUI-Changes

#7628 Intercoms have some nice overlays for indicating mic and broadcast
  code/game/objects/items/devices/radio/intercom.dm
  icons/obj/radio.dmi
Labels: Tweak, Sprites

#7622 Emagged and syndicate borg self-desctruct
  code/game/machinery/computer/robot.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/modular_computers/file_system/programs/borg_self_monitor.dm
  tgui/packages/tgui/interfaces/NtosCyborgSelfMonitor.js
Labels: Tweak, Feature, TGUI-Changes

#7639 Converts typecheck wiremod component into a typecast component
  beestation.dme
  code/__DEFINES/wiremod.dm
  code/modules/research/designs/wiremod_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/wiremod/components/utility/typecast.dm
  code/modules/wiremod/components/utility/typecheck.dm
Labels: Tweak

#7638 Makes Shield Generator Satellite crates and Shield System Control Board crates always available for purchase.
  code/modules/cargo/packs.dm
  code/modules/events/meteor_wave.dm
  code/modules/station_goals/shield.dm
Labels: Tweak

#7586 Improve dynamic's handling of midround execute() failure
  code/game/gamemodes/dynamic/dynamic_rulesets.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
Labels: Fix, Code Improvement, Server

#7537 Deny access to clients that don't send telemetry
  code/__DEFINES/tgui.dm
  code/modules/tgui_panel/telemetry.dm
Labels: Needs Testmerge, Test Merged, Administration, Server

#7661 Rad Window cost adjustment
  code/game/objects/items/stacks/sheets/mineral.dm
Labels: Tweak

#7685 Fixes mining cyborg plasma cutters scattering
  code/modules/projectiles/guns/energy/special.dm
Labels: Fix

#7673 Fix the adminbus chrono-suit
  code/game/objects/items/chrono_eraser.dm
  code/modules/clothing/spacesuits/chronosuit.dm
Labels: Fix

#7677 Skate crafting recipie spawns the item not the board
  code/datums/components/crafting/recipes.dm
Labels: Tweak

#7664 Post-round nukes dont mute ooc
  code/datums/cinematic.dm
Labels: Administration

#7650 Fixes repairing cyborgs with plasma cutters
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Fix

#7695 Fixes a single letter typo for Heretics
  code/modules/antagonists/eldritch_cult/eldritch_antag.dm
Labels: Fix, Grammar and Formatting

#7694 Adds gas ignitor setups for Box/Delta Xenobio
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Mapping, Feature

#7670 Fix +1 traitor objectives
  code/modules/antagonists/traitor/datum_traitor.dm
  config/game_options.txt
Labels: Fix, Config Update

#7618 Fixes for 2 of my previous prs
  beestation.dme
  code/datums/components/mood.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/toys.dm
Labels: Tweak, Fix

#7631 Fixes broken icon for bedsheets, also refactor the whole thing
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  beestation.dme
  code/game/objects/items/bedsheets.dm
  code/game/objects/structures/bedsheet_bin.dm
  icons/mob/neck.dmi
  icons/obj/beds_chairs/beds.dmi
Labels: Mapping, Sprites, Fix, Refactor, Code Improvement

#7676 Screwdriver pen has a noise on retracting/extending
  code/modules/paperwork/pen.dm
Labels: Tweak

#7620 Cyborg Monitoring Improvements
  code/modules/modular_computers/file_system/programs/borg_monitor.dm
  code/modules/modular_computers/hardware/hard_drive.dm
  tgui/packages/tgui/interfaces/NtosCyborgRemoteMonitor.js
  tgui/packages/tgui/interfaces/NtosCyborgRemoteMonitorSyndicate.js
Labels: Tweak, Feature, TGUI-Changes

#7699 Blood brothers implant no longer shows fake names
  code/game/objects/items/implants/implant_bb.dm
Labels: Fix

#7570 IPC/etheral recharge with inducers
  code/game/objects/items/inducer.dm
Labels: Feature

#7709 Dynamic: Lower midround Xenos weight
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
Labels: Tweak

#7476 Adds New Medieval Mutation
  code/__DEFINES/DNA.dm
  code/__DEFINES/configuration.dm
  code/datums/mutations/speech.dm
  code/game/objects/items/dna_injector.dm
  strings/medieval_speech.json
Labels: Feature

#7572 Cuffs are now included in get_equipped_items() (mob transformation fix)
  code/datums/diseases/transformation.dm
  code/game/objects/items.dm
  code/modules/mob/inventory.dm
  code/modules/mob/transform_procs.dm
Labels: Fix, Removal

#7152 Docks and nested shuttles
  _maps/map_files/KiloStation/KiloStation.dmm
  beestation.dme
  code/controllers/subsystem/atoms.dm
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/processing/orbits.dm
  code/controllers/subsystem/shuttle.dm
  code/controllers/subsystem/zclear.dm
  code/datums/shuttles.dm
  code/game/area/areas.dm
  code/game/area/areas/shuttles.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/turfs/change_turf.dm
  code/game/turfs/open/floor/dock_floor.dm
  code/game/turfs/turf.dm
  code/modules/mapping/map_template.dm
  code/modules/mapping/space_management/space_level.dm
  code/modules/mining/aux_base.dm
  code/modules/shuttle/bluespace_shuttle_pod/shuttle_capsule.dm
  code/modules/shuttle/docking.dm
  code/modules/shuttle/on_move.dm
  code/modules/shuttle/shuttle.dm
  code/modules/shuttle/shuttle_creation/shuttle_creator.dm
  code/modules/shuttle/shuttle_creation/shuttle_creator_actions.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/beacon.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/shuttle.dm
  code/modules/shuttle/super_cruise/shuttle_components/shuttle_console.dm
  code/modules/shuttle/super_cruise/shuttle_components/shuttle_docking.dm
  code/modules/shuttle/super_cruise/shuttle_supercruise.dm
  code/modules/turbolift/turbolift_docks.dm
  icons/obj/tiles.dmi
  icons/turf/floors.dmi
Labels: Mapping, Needs Testmerge, Tweak, Feature, Sprites, Balance/Rebalance, Refactor, Code Improvement, Golden ⭐

#7715 Fixes to all the benches
  code/game/objects/structures/beds_chairs/bench.dm
  icons/obj/beds_chairs/benches.dmi
Labels: Sprites, Fix

#7688 Fixes Signaller ModPC program issue
  code/modules/modular_computers/file_system/program.dm
  code/modules/modular_computers/file_system/programs/alarm.dm
  code/modules/modular_computers/file_system/programs/antagonist/contract_uplink.dm
  code/modules/modular_computers/file_system/programs/antagonist/revelation.dm
  code/modules/modular_computers/file_system/programs/ntdownloader.dm
  code/modules/modular_computers/file_system/programs/powermonitor.dm
  code/modules/modular_computers/file_system/programs/signaller.dm
  code/modules/modular_computers/file_system/programs/sm_monitor.dm
Labels: Fix, Code Improvement

#7615 Micro-optimization of build_appearance_list
  code/controllers/subsystem/overlays.dm
Labels: Code Improvement

#7696 Minor tweaks to Virology room + fixes windoor access requirement
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Mapping, Fix, Removal

#7693 Adds a blacklist to Pun-Pun's hat & mask saving
  code/modules/mob/living/carbon/monkey/punpun.dm
Labels: Tweak

#7687 Dynamic Incursion: Fix restricted roles for excomms
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/game_mode.dm
  code/modules/antagonists/incursion/incursion.dm
Labels: Fix

#7672 MedHUD and SSD improvements
  code/datums/mind.dm
  code/game/data_huds.dm
  code/modules/mob/dead/dead.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/living_defense.dm
  code/modules/spells/spell_types/lesserlichdom.dm
  icons/mob/hud.dmi
Labels: Tweak, Sprites, Fix, Good PR

#7658 Dynamic: Block traitors/heretics/lings/bros during cults/nukies/wiz/revs
  code/__DEFINES/dynamic.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
Labels: Needs Testmerge, Balance/Rebalance

#7727 Fix runtime with MedHUD SSD indicator
  code/modules/mob/dead/dead.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Fix, Server

#7728 Fix MedHUD SSD Runtimes 2
  code/datums/mind.dm
Labels: Fix

#7721 Lavaland 2.1 (or the reason why we do TMs)
  _maps/map_files/Mining/Lavaland.dmm
Labels: Mapping, Feature, Fix

#7552 PKAs are now as weak in a vacuum as they are in a pressurized environment
  code/__DEFINES/atmospherics.dm
  code/__HELPERS/game.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  code/modules/uplink/uplink_items.dm
Labels: Balance/Rebalance

#7731 The Filterening (Poly, Nanites, Most "Alternate" Speech/Telepathy)
  code/game/machinery/computer/communications.dm
  code/game/machinery/computer/prisoner/management.dm
  code/game/machinery/requests_console.dm
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/antagonists/blob/blob_mobs.dm
  code/modules/antagonists/blob/overmind.dm
  code/modules/antagonists/cult/cult_comms.dm
  code/modules/antagonists/eldritch_cult/eldritch_magic.dm
  code/modules/antagonists/revenant/revenant.dm
  code/modules/guardian/guardian.dm
  code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
  code/modules/mob/living/carbon/alien/say.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/silicon/ai/say.dm
  code/modules/mob/living/silicon/say.dm
  code/modules/mob/living/simple_animal/guardian/guardian.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/say.dm
  code/modules/research/nanites/nanite_programs.dm
  code/modules/research/nanites/nanite_remote.dm
  code/modules/spells/spell_types/hivemind.dm
  code/modules/spells/spell_types/personality_commune.dm
Labels: Fix, Administration

#7590 Airlock/Decal Painters have new sprites for low ink
  code/game/objects/items/airlock_painter.dm
  icons/obj/objects.dmi
Labels: Tweak, Sprites, Refactor

#7523 Adds the militaristic captain colouriser + colourisers can have multiple uses
  code/game/objects/items/colorizers/clothing.dm
  code/game/objects/items/colorizers/colorizer.dm
  code/modules/client/loadout/loadout_colorizers.dm
  code/modules/clothing/head/jobs.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Mapping, Feature, Sprites, Code Improvement

#7561 Some of heads' lockers contents are compressed into a box, so that their locker can take the stuff properly
  code/__DEFINES/movespeed_modification.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
Labels: Tweak, Feature, Refactor

#7736 Grants mapping ownership to PestoVerde
  .github/CODEOWNERS
Labels: GitHub

#7735 Genetics pubby doors + miscelaneous fixes
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Mapping, Fix, Removal

#7706 Fixes the Engine camera consoles on box station
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Mapping, Fix

#7584 [PORT] Changes how weather sends sound to players, reduces sound loop overtime and Weather ztraits
  beestation.dme
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/maps.dm
  code/__DEFINES/weather.dm
  code/controllers/subsystem/weather.dm
  code/datums/components/area_sound_manager.dm
  code/datums/elements/weather_listener.dm
  code/datums/looping_sounds/_looping_sound.dm
  code/datums/weather/weather.dm
  code/datums/weather/weather_types/acid_rain.dm
  code/datums/weather/weather_types/ash_storm.dm
  code/game/machinery/fat_sucker.dm
  code/game/machinery/race_converter.dm
  code/game/objects/items/devices/geiger_counter.dm
  code/game/objects/items/devices/reverse_bear_trap.dm
  code/game/objects/structures/shower.dm
  code/modules/admin/verbs/possess.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
  code/modules/food_and_drinks/kitchen_machinery/grill.dm
  code/modules/food_and_drinks/kitchen_machinery/microwave.dm
  code/modules/mob/login.dm
  code/modules/power/port_gen.dm
  code/modules/power/supermatter/supermatter.dm
Labels: Administration, Code Improvement, Somewhat Important

#7732 Lighten glasses tint/client coloring
  code/modules/client/client_colour.dm
Labels: Tweak
