Repository BeeStation/BeeStation-Hornet, pull requests merged in 2023-04, with the labels that each got.

#8788 Fixes April Fools subsystem init order
  code/__DEFINES/subsystems.dm
Labels: Fix

#8521 Beecoin store jumpsuits change to jumpskirts based on active character preference.
  code/modules/client/loadout/loadout.dm
  code/modules/client/loadout/loadout_uniform.dm
  code/modules/client/preferences.dm
  code/modules/clothing/under/color.dm
  code/modules/jobs/job_types/_job.dm
Labels: Feature

#8696 Getting unmonkified now restores you to your original species
  code/datums/mutations/body.dm
  code/modules/mob/transform_procs.dm
Labels: Tweak

#8809 Fixes some additional proc references for 515
  code/datums/diseases/advance/symptoms/necropolis.dm
  code/datums/status_effects/buffs.dm
  code/game/machinery/computer/arcade.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_defense.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/extinguisher.dm
  code/game/objects/items/grenades/clusterbuster.dm
  code/game/objects/structures/false_walls.dm
  code/modules/admin/verbs/mentorhelp.dm
  code/modules/antagonists/clock_cult/clockwork_turfs.dm
  code/modules/antagonists/clock_cult/scriptures/kindle.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/antagonists/hivemind/spells/hivemind_dominance.dm
  code/modules/antagonists/hivemind/spells/hivemind_panic.dm
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
  code/modules/asset_cache/transports/asset_transport.dm
  code/modules/jobs/job_exp.dm
  code/modules/mining/equipment/wormhole_jaunter.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/simple_animal/bot/construction.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
  code/modules/mob/living/simple_animal/hostile/wumborian_fugu.dm
  code/modules/reagents/chemistry/machinery/reagentgrinder.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/research/rdmachines.dm
  code/modules/shuttle/on_move.dm
  code/modules/surgery/organs/vocal_cords.dm
  code/modules/vehicles/cars/car.dm
Labels: Administration, Code Improvement

#8730 Ports "You can now print cable coils and welding helmets from scilathes and engilathes"
  code/modules/power/cable.dm
  code/modules/research/designs/autolathe_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Tweak

#8715 Ports vent directional control
  code/modules/atmospherics/machinery/airalarm.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  tgui/packages/tgui/interfaces/AirAlarm.js
  tgui/packages/tgui/interfaces/common/AtmosControls.js
Labels: Feature, TGUI-Changes

#8805 Fixes looping sounds
  code/datums/looping_sounds/_looping_sound.dm
Labels: Fix

#8751 Sanity gradually moves towards a neutral state
  code/datums/components/mood.dm
Labels: Tweak

#8756 Replaces the fedora in the DetDrobe with a noir fedora
  beestation.dme
  code/datums/dog_fashion.dm
  code/modules/clothing/head/jobs.dm
  code/modules/vending/wardrobes.dm
  icons/mob/corgi_head.dmi
Labels: Feature, Sprites

#8808 Fixes Metastation's Turbine Ignitor
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Mapping, Fix

#8742 Smelter/furnace QOL update
  _maps/map_files/Mining/Lavaland.dmm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/mining/machine_processing.dm
  code/modules/research/machinery/_production.dm
  code/modules/research/techweb/all_nodes.dm
  tgui/packages/tgui/interfaces/Smelter.js
Labels: Mapping, Tweak, Feature, Code Improvement, TGUI-Changes

#8701 Monkey transformations now properly carry over your implants.
  code/game/objects/items/implants/implant.dm
  code/modules/mob/transform_procs.dm
Labels: Fix

#8735 Quirks are now handled by the mind (and other quirk code changes)
  code/controllers/subsystem/processing/quirks.dm
  code/controllers/subsystem/ticker.dm
  code/datums/mind.dm
  code/datums/traits/_quirk.dm
  code/datums/traits/negative_quirk.dm
  code/datums/traits/neutral_quirk.dm
  code/datums/traits/positive_quirk.dm
  code/game/machinery/cloning.dm
  code/game/machinery/computer/cloning.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/antagonists/creep/creep.dm
  code/modules/antagonists/nukeop/nukeop.dm
  code/modules/antagonists/wizard/wizard.dm
  code/modules/hydroponics/grown/replicapod.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/blood.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/status_procs.dm
Labels: Tweak, Fix, Code Improvement

#8779 Fix admin Dynamic tools not working with secret
  code/controllers/subsystem/ticker.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
Labels: Administration

#8797 TG manifest/records optimizations & fixes
  code/__HELPERS/icons.dm
  code/datums/datacore.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/security.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix, Balance/Rebalance, Refactor, Code Improvement

#8801 Deconstructing blast doors now gives 15 plasteel
  code/game/machinery/doors/poddoor.dm
Labels: Fix

#8803 Revenant orbitting shows a warning notice
  code/modules/antagonists/revenant/revenant.dm
Labels: Feature

#8763 Replace Discord webhook proxy with RUSTG POST
  beestation.dme
  code/__HELPERS/roundend.dm
  code/modules/admin/admin.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/client/verbs/ooc.dm
  code/modules/discord/discord.dm
  code/modules/relay/relay.dm
  config/comms.txt
  config/config.txt
  tools/discord/config.yml
  tools/discord/server.py
Labels: Test Merged, Fix, Config Update, Administration, Tools, Server

#8777 Add some CODEOWNERS to itsmeow
  .github/CODEOWNERS
Labels: GitHub

#8819 Converts the old send2chat messages to datums
  code/__HELPERS/chat.dm
  code/controllers/subsystem/ticker.dm
  code/modules/admin/chat_commands.dm
Labels: Administration, Code Improvement, TGS

#8773 The surgical serverlink brain implant can now download surgeries from held disks
  code/modules/surgery/organs/augments_internal.dm
Labels: Feature, Server

#8775 Fix stationloving objects (nuke disk) teleporting from allowed shuttles
  code/datums/components/stationloving.dm
Labels: Fix

#8785 Ports overlay lighting as underlay refactor
  code/__HELPERS/icon_smoothing.dm
  code/datums/components/overlay_lighting.dm
  code/game/objects/effects/overlays.dm
Labels: Refactor

#8816 ID manipulation console no longer strips unrelated accesses
  code/game/machinery/computer/card.dm
  code/modules/jobs/access.dm
  code/modules/modular_computers/file_system/programs/card.dm
Labels: Fix, Code Improvement

#8611 Better crab-17 behavior and better code
  code/game/objects/items/crab17.dm
Labels: Balance/Rebalance, Code Improvement

#8835 Fix bug with surgeries imported via disk into the serverlink implant
  code/modules/surgery/organs/augments_internal.dm
Labels: Fix, Server

#8843 Radiation Storms no longer cover Solar Arrays
  code/datums/weather/weather_types/radiation_storm.dm
Labels: Tweak

#8794 Nerfs beepsky
  code/modules/mob/living/simple_animal/bot/secbot.dm
Labels: Balance/Rebalance

#8856 Restores mistakenly deleted tgui_say.initialize() to client procs
  code/modules/client/client_procs.dm
Labels: Fix

#8866 Fixes plumbing pipes
  code/modules/plumbing/plumbers/_plumb_machinery.dm
  code/modules/plumbing/plumbers/acclimator.dm
  code/modules/plumbing/plumbers/bottle_dispenser.dm
  code/modules/plumbing/plumbers/destroyer.dm
  code/modules/plumbing/plumbers/filter.dm
  code/modules/plumbing/plumbers/grinder_chemical.dm
  code/modules/plumbing/plumbers/patch_dispenser.dm
  code/modules/plumbing/plumbers/pill_press.dm
  code/modules/plumbing/plumbers/pumps.dm
  code/modules/plumbing/plumbers/reaction_chamber.dm
  code/modules/plumbing/plumbers/splitters.dm
  code/modules/plumbing/plumbers/synthesizer.dm
  code/modules/reagents/chemistry/machinery/smoke_machine.dm
Labels: Fix

#8566 Sniper rifle buff 2
  beestation.dme
  code/game/objects/items/storage/briefcase.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/awaymissions/mission_code/TheFactory.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/projectiles/ammunition/ballistic/sniper.dm
  code/modules/projectiles/boxes_magazines/external/sniper.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/sniper.dm
  code/modules/projectiles/projectile/bullets/sniper.dm
  code/modules/ruins/lavaland_ruin_code.dm
  code/modules/spells/spell_types/rightandwrong.dm
  code/modules/uplink/uplink_items.dm
  icons/obj/ammo.dmi
Labels: Sprites, Balance/Rebalance, Removal

#8841 Properly transfer hair gradients with DNA
  code/__DEFINES/DNA.dm
  code/datums/dna.dm
  code/modules/mob/living/carbon/human/human_defines.dm
Labels: Fix

#8703 Makes several adjustments to monkey mutadone interactions.
  code/datums/mutations/body.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/transform_procs.dm
Labels: Tweak, Feature, Fix, Code Improvement

#8599 Wearing flowers now gives you a mood boost + small flower code refactor
  _maps/RandomRooms/10x5/sk_rdm040_deltabotnis.dmm
  _maps/RandomRuins/SpaceRuins/oldstation.dmm
  _maps/RuinGeneration/13x13_shotelroom.dmm
  _maps/RuinGeneration/13x9_josito.dmm
  _maps/holodeck/chapelcourt.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/GlowStation/GlowStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/shuttles/whiteship/whiteship_box.dmm
  _maps/templates/hilbertshotel.dmm
  code/_globalvars/lists/maintenance_loot.dm
  code/datums/components/crafting/recipes.dm
  code/datums/components/crafting/tailoring.dm
  code/datums/mood_events/generic_positive_events.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
  code/modules/antagonists/eldritch_cult/knowledge/flesh_lore.dm
  code/modules/cargo/bounties/assistant.dm
  code/modules/cargo/bounties/botany.dm
  code/modules/cargo/packs.dm
  code/modules/clothing/head/misc.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_cake.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  code/modules/holiday/holidays.dm
  code/modules/hydroponics/grown/ambrosia.dm
  code/modules/hydroponics/grown/flowers.dm
  code/modules/hydroponics/grown/grass_carpet.dm
  code/modules/hydroponics/grown/rainbow_bunch.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/vending/megaseed.dm
Labels: Mapping, Tweak, Feature, Fix, Grammar and Formatting, Refactor, Administration

#8869 Fixes a single missing letter from dmi file
  icons/obj/medicine_containers.dmi
Labels: Sprites, Fix

#8871 Fixes Missing Swarmer Catwalk Sprites
  code/modules/mob/living/simple_animal/hostile/megafauna/swarmer.dm
Labels: Fix

#8872 Fix body cloning not working
  code/game/machinery/cloning.dm
Labels: Fix

#8876 Resize corgstation back to the right size (255x255)
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: Mapping, Fix

#8877 Fixes some Area turf being transparent in the map editor
  icons/turf/areas.dmi
Labels: Sprites, Fix

#8886 Fixes Medibots Ignoring Old Patients
  code/modules/mob/living/simple_animal/bot/medbot.dm
Labels: Fix

#8594 MultiZ and Shuttle fixes and improvements
  code/_globalvars/bitfields.dm
  code/controllers/subsystem/movement/zfall.dm
  code/controllers/subsystem/throwing.dm
  code/datums/ai/dog/dog_controller.dm
  code/game/atoms_movable.dm
  code/game/machinery/computer/camera_advanced.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doors/poddoor.dm
  code/game/machinery/doors/shutters.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/machinery/shieldgen.dm
  code/game/machinery/shuttle/shuttle_engine.dm
  code/game/machinery/shuttle/shuttle_heater.dm
  code/game/mecha/mecha.dm
  code/game/objects/effects/effect_system/effects_foam.dm
  code/game/objects/effects/forcefields.dm
  code/game/objects/items/devices/forcefieldprojector.dm
  code/game/objects/structures/ai_core.dm
  code/game/objects/structures/door_assembly.dm
  code/game/objects/structures/false_walls.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/window.dm
  code/game/shuttle_engines.dm
  code/modules/antagonists/clock_cult/items/clockwork_weapon.dm
  code/modules/clothing/head/_head.dm
  code/modules/guardian/abilities/special/absolution.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/living_movement.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/shuttle/super_cruise/shuttle_components/shuttle_docking.dm
Labels: Mapping, Tweak, Feature, Fix

#8874 Cleans up some residual human flaticon errors
  code/modules/antagonists/cult/cult.dm
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Fix

#8786 You can now manually link stasis beds to operating computers
  code/game/machinery/computer/Operating.dm
  code/game/machinery/stasis.dm
Labels: Tweak, Feature

#8896 Tweaks how IPC antennas layer
  code/modules/mob/living/carbon/human/species.dm
  icons/mob/ipc_accessories.dmi
Labels: Tweak, Feature, Sprites

#8902 Changed Emergency Fire Suit Sprite
  icons/mob/clothing/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Tweak, Sprites

#8870 You can now build frames on indestructible floors
  code/__DEFINES/is_helpers.dm
  code/game/objects/items/stacks/stack.dm
Labels: Tweak

#8879 Stamina damage is now logged
  code/game/atoms.dm
Labels: Feature

#8890 Minor sleeper tweaks
  code/game/machinery/Sleeper.dm
Labels: Tweak, Feature

#8916 Fixes the Reagents in Rice
  code/modules/hydroponics/grown/cereals.dm
Labels: Fix

#8920 Fixes Meteors Being Too Slow
  code/modules/events/meteor_wave.dm
Labels: Fix

#8888 MultiZ Tracking Beacon HUD
  code/datums/components/team_monitor.dm
  code/game/machinery/syndicatebomb.dm
  code/modules/antagonists/clock_cult/mobs/eminence.dm
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
  code/modules/antagonists/revenant/revenant.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/ghost.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature, Code Improvement

#8926 Fixes spawned humans always being bald
  code/modules/mob/living/carbon/human/species.dm
  code/modules/surgery/bodyparts/dismemberment.dm
Labels: Fix

#8921 Fixes The Gulag's Furnace
  _maps/map_files/Mining/Lavaland.dmm
Labels: Mapping, Fix

#8937 Fix newscaster showing name as job
  code/game/machinery/newscaster/newscaster_machine.dm
Labels: Fix

#8840 Lavaland Spawners will now spawn more Ashwalkers, Golems, and Syndicate Bases
  code/datums/ruins/lavaland.dm
Labels: Balance/Rebalance

#8837 Fixes exploit with framestacking, is_blocked_turf optimization, adds unit test
  code/__DEFINES/construction.dm
  code/__HELPERS/atoms.dm
  code/__HELPERS/game.dm
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/minor_mapping.dm
  code/game/atoms_movable.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/deployable.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/machinery/fabricators/modular_fabricator.dm
  code/game/machinery/porta_turret/portable_turret.dm
  code/game/objects/items/holosign_creator.dm
  code/game/objects/items/scrolls.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/railings.dm
  code/game/objects/structures/windoor_assembly.dm
  code/game/objects/structures/window.dm
  code/game/turfs/turf.dm
  code/modules/antagonists/clock_cult/clockwork_turfs.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/antagonists/cult/cult_comms.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/antagonists/traitor/syndicate_contract.dm
  code/modules/cargo/expressconsole.dm
  code/modules/events/shuttle_loan.dm
  code/modules/mining/aux_base_camera.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/pool/components/swimming.dm
  code/modules/projectiles/guns/energy/dueling.dm
  code/modules/research/xenobiology/crossbreeding/_structures.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/ruin_generator.dm
  code/modules/shuttle/supply.dm
  code/modules/spells/spell_types/shadow_walk.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/rcd.dm
Labels: Fix, Code Improvement

#8736 Transform sting refactor + nerf
  code/__DEFINES/status_effects.dm
  code/datums/dna.dm
  code/datums/status_effects/debuffs.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/antagonists/changeling/powers/tiny_prick.dm
Labels: Balance/Rebalance

#8789 Spider balance 3 (buffs + new ability)
  _maps/shuttles/whiteship/whiteship_delta.dmm
  beestation.dme
  code/__DEFINES/antagonists.dm
  code/game/mecha/mecha.dm
  code/game/objects/effects/spiders.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/projectiles/projectile/special/spidernet.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  icons/effects/throwweb_target.dmi
  icons/mob/actions/actions_animal.dmi
  icons/obj/projectiles.dmi
Labels: Mapping, Tweak, Feature, Sprites, Fix, Balance/Rebalance

#8806 Adds/Restores some digitigrade clothing variants
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/under/jobs/command.dm
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/clothing/under/suits.dm
Labels: Feature

#8616 Hiero club, crusher trophy and resonator tweaks
  code/modules/mining/equipment/resonator.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
Labels: Tweak, Fix, Balance/Rebalance

#8852 more preset gas/atmos miner machines
  code/modules/atmospherics/machinery/other/miner.dm
Labels: Feature

#8860 Minor armor improvements
  code/__DEFINES/inventory.dm
  code/modules/clothing/clothing.dm
Labels: Feature, Code Improvement

#8887 Fixes pAI Medical and Security Record Program
  code/modules/mob/living/silicon/pai/software.dm
  tgui/packages/tgui/interfaces/PaiInterface.tsx
Labels: Fix, TGUI-Changes

#8895 Emagged Borgs don't lose their brain when exploded
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Tweak

#8931 Corgstation disposals fixes
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: Mapping, Fix

#8932 remakes Box comms
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Mapping, Feature

#8930 adds linings to kilo
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Mapping, Feature

#8955 Unwrenching hotfix
  code/game/machinery/_machinery.dm
Labels: Fix

#8947 Errors will print to the chat while the debugger is enabled.
  code/modules/error_handler/error_handler.dm
Labels: Code Improvement
