Repository BeeStation/BeeStation-Hornet, pull requests merged in 2023-09, with the labels that each got.

#9737 Allows Obsessed crewmemebrs to open the mail of their obsession targets
  code/game/objects/items/mail.dm
Labels: Feature

#9753 Revert "Abductors can now make custom abductee objectives"
  code/modules/antagonists/abductor/abductee/abductee_objectives.dm
  code/modules/antagonists/abductor/abductor.dm
  code/modules/antagonists/abductor/machinery/experiment.dm
  code/modules/surgery/advanced/lobotomy.dm
  tgui/packages/tgui/interfaces/ProbingConsole.js
Labels: Removal, TGUI-Changes

#9730 Makes crafting items put the result on a rack/table in front of the user if the user's hands are full
  code/datums/components/crafting/crafting.dm
Labels: Tweak

#9736 Makes the shove intent stun of an emagged/combat defib be blocked by shields
  code/game/objects/items/defib.dm
Labels: Balance/Rebalance

#9763 Fix NtOS notepad easily hitting rate limits
  tgui/packages/tgui/interfaces/NtosNotepad.js
Labels: Fix, TGUI-Changes

#9697 Fullscreen mode
  beestation.dme
  code/__DEFINES/keybinding.dm
  code/__byond_version_compat.dm
  code/datums/keybinding/client.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences/entries/player/fullscreen.dm
  interface/skin.dmf
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/fullscreen.tsx
Labels: Feature, TGUI-Changes, Testmerge Passed

#9748 Fixes Radstation's Airmix so that it isn't completely borked
  _maps/map_files/RadStation/RadStation.dmm
Labels: Mapping, Fix

#9700 Makes machines and lockers no longer block diagonal clicks
  code/__DEFINES/flags.dm
  code/_onclick/adjacent.dm
  code/game/machinery/_machinery.dm
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Feature, Code Improvement

#9773 Makes lights turning off roundstart in unstaffed departments a config option
  code/controllers/configuration/entries/game_options.dm
  code/game/machinery/lightswitch.dm
  config/game_options.txt
Labels: Config Update

#9352 Virology QoL update (+ some refactoring)
  code/__DEFINES/dcs/signals/signals_atom.dm
  code/__DEFINES/diseases.dm
  code/__DEFINES/is_helpers.dm
  code/datums/components/infective.dm
  code/datums/diseases/advance/presets.dm
  code/datums/diseases/advance/symptoms/blobspores.dm
  code/datums/diseases/advance/symptoms/heal.dm
  code/datums/diseases/advance/symptoms/macrophage.dm
  code/datums/status_effects/debuffs.dm
  code/game/atoms.dm
  code/game/objects/effects/decals/cleanable/humans.dm
  code/game/objects/effects/decals/cleanable/misc.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/antagonists/blob/blob_mobs.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/mapping/mapping_helpers.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/friendly/hamster.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/hostile/macrophage.dm
  code/modules/mob/living/simple_animal/hostile/redgrub.dm
  code/modules/mob/living/simple_animal/hostile/wumborian_fugu.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/syringes.dm
Labels: Tweak, Feature, Fix, Refactor

#9778 Fix incorrect custom virus names being shown
  code/datums/diseases/advance/advance.dm
Labels: Fix

#9744 Fix obsession heirloom objectives
  code/modules/antagonists/obsessed/obsessed.dm
Labels: Fix

#9734 Fix flaky operating computer linking test
  code/game/machinery/computer/Operating.dm
  code/game/machinery/stasis.dm
  code/game/objects/structures/tables_racks.dm
Labels: Fix, Code Improvement

#9768 Makes sleepers no longer block reagents other than Epinephrene for patients in crit + small sleeper bugfix
  code/game/machinery/sleeper.dm
  tgui/packages/tgui/interfaces/Sleeper.js
Labels: Tweak, Fix, TGUI-Changes

#9466 Tweaks the Aurora Caelus event
  code/datums/mood_events/generic_positive_events.dm
  code/modules/events/aurora_caelus.dm
Labels: Tweak, Feature, Fix, Code Improvement

#9747 Converts deployables into a component
  _maps/RandomRooms/10x10/sk_rdm159_kilosnakepit.dmm
  _maps/RandomRooms/10x5/sk_rdm011_barbershop.dmm
  _maps/RandomRooms/5x4/sk_rdm090_tinybarbershop.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_09_barbershop.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_animal_hospital.dmm
  _maps/RandomRuins/SpaceRuins/crashedship.dmm
  _maps/RandomRuins/SpaceRuins/hilbertshoteltestingsite.dmm
  _maps/RandomRuins/SpaceRuins/oldstation.dmm
  _maps/RandomRuins/SpaceRuins/onehalf.dmm
  _maps/RandomZLevels/SnowCabin.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/shuttles/hunter/hunter_russian.dmm
  _maps/shuttles/whiteship/whiteship_delta.dmm
  _maps/templates/shelter_4.dmm
  beestation.dme
  code/__DEFINES/dcs/signals/signals_obj/signals_item/signals_item.dm
  code/_globalvars/lists/maintenance_loot.dm
  code/datums/components/deployable.dm
  code/datums/traits/negative_quirk.dm
  code/game/objects/items/deployable/barricade.dm
  code/game/objects/items/deployable/bodybag.dm
  code/game/objects/items/deployable/bot.dm
  code/game/objects/items/deployable/capsule.dm
  code/game/objects/items/deployable/deployable.dm
  code/game/objects/items/deployable/rollerbed.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/structures/beds_chairs/bed.dm
  code/game/objects/structures/crates_lockers/closets/bodybag.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/cargo/bounties/science.dm
  code/modules/cargo/exports/large_objects.dm
  code/modules/cargo/packs.dm
  code/modules/jobs/job_types/exploration_team.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/station_goals/shield.dm
  code/modules/vending/security.dm
Labels: Mapping, Tweak, Code Improvement

#9642 Players cannot view the contents of trash bags
  code/datums/components/storage/storage.dm
  code/game/objects/items/storage/bags.dm
Labels: Tweak, Balance Approved

#8117 Atmos firefighting backpack researchable upgrades
  code/__DEFINES/dcs/signals/signals_datum/signals_moveloop.dm
  code/__DEFINES/flags.dm
  code/_globalvars/bitfields.dm
  code/controllers/subsystem/movement/movement_types.dm
  code/game/objects/effects/effect_system/effects_foam.dm
  code/game/objects/items/tanks/watertank.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/research/designs/tool_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/effects/effects.dmi
  icons/mob/clothing/back.dmi
  icons/mob/inhands/equipment/backpack_lefthand.dmi
  icons/mob/inhands/equipment/backpack_righthand.dmi
  icons/mob/inhands/equipment/mister_lefthand.dmi
  icons/mob/inhands/equipment/mister_righthand.dmi
  icons/mob/reagent_overlays.dmi
  icons/obj/atmospherics/equipment.dmi
  icons/obj/hydroponics/equipment.dmi
  icons/obj/reagentfillings.dmi
Labels: Feature, Sprites, Balance/Rebalance

#9692 Beaker, dropper, bottle syringe and pill bottle resprite
  code/modules/paperwork/pen.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/bottle.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/syringes.dm
  icons/obj/chemical.dmi
  icons/obj/medicine_containers.dmi
  icons/obj/reagentfillings.dmi
  icons/obj/syringe.dmi
Labels: Feature, Sprites

#9771 Prevent rust heretic from mansus grasping floors/walls/objects when on harm intent
  code/modules/antagonists/heretic/knowledge/rust_lore.dm
Labels: Tweak

#9787 Fixes a couple of bugs with the atmos firefighting backpack
  code/game/objects/items/tanks/watertank.dm
Labels: Fix

#9207 Fixes dead body place holder reality break
  _maps/RandomRooms/10x5/sk_rdm154_butchersden.dmm
  _maps/RuinGeneration/13x17_chapel.dmm
  _maps/RuinGeneration/9x5_morgue.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  code/modules/mapping/mapping_helpers.dm
Labels: Mapping, Fix, Code Improvement

#9795 Inverting an if statement to fix buttons
  code/_onclick/hud/movable_screen_objects.dm
Labels: Fix

#9793 removes mystery meat from vegetarian burritos (and a typo fix)
  code/modules/food_and_drinks/food/snacks_other.dm
Labels: Fix, Grammar and Formatting

#9750 Mapping QoL/Fix for Atmospheric Mixers, Temperature Pumps, and Temperature Gates
  code/modules/atmospherics/machinery/components/binary_devices/temperature_gate.dm
  code/modules/atmospherics/machinery/components/binary_devices/temperature_pump.dm
  code/modules/atmospherics/machinery/components/binary_devices/volume_pump.dm
  code/modules/atmospherics/machinery/components/trinary_devices/mixer.dm
  icons/obj/atmospherics/components/binary_devices.dmi
  icons/obj/atmospherics/components/trinary_devices.dmi
Labels: Feature, Sprites, Fix

#9779 Fixes AI holocall runechat shows chat mods
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Fix

#9803 Syndicate bombs no longer get negative timers
  code/datums/wires/syndicatebomb.dm
Labels: Fix

#9780 Meta and delta medbay map fixes
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Mapping, Fix, Removal

#9786 Fixes holopad hologram plays record where it shouldn't exist anylonger
  code/game/machinery/hologram.dm
Labels: Fix

#9794 No Unanchoring Holopads Anymore
  code/game/machinery/hologram.dm
Labels: Removal

#9804 Cyborgs can unbuckle people, same as any other mob
  code/game/machinery/_machinery.dm
  code/game/machinery/stasis.dm
  code/game/objects/buckling.dm
Labels: Feature

#9759 Add new greeting sounds for some antags
  code/__DEFINES/sound.dm
  code/modules/antagonists/abductor/abductor.dm
  code/modules/antagonists/brainwashing/brainwashing.dm
  code/modules/antagonists/brother/brother.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/clock_cult/servant_of_ratvar.dm
  code/modules/antagonists/cult/cult.dm
  code/modules/antagonists/heretic/heretic_antag.dm
  code/modules/antagonists/heretic/heretic_monsters.dm
  code/modules/antagonists/hivemind/hivemind.dm
  code/modules/antagonists/hypnotization/hypnotized.dm
  code/modules/antagonists/incursion/incursion.dm
  code/modules/antagonists/nukeop/nukeop.dm
  code/modules/antagonists/obsessed/obsessed.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  sound/ambience/antag/abductee.ogg
  sound/ambience/antag/brainwash.ogg
  sound/ambience/antag/hypnosis.ogg
  sound/ambience/antag/incursion.ogg
  sound/attributions.txt
Labels: Tweak, Feature, Sound

#9819 Fix message monitor UI not flowing properly
  tgui/packages/tgui/interfaces/MessageMonitor.js
Labels: Fix, TGUI-Changes

#9820 Projectile Shrapnel Embed Fix
  code/datums/components/embedded.dm
  code/datums/elements/embed.dm
  code/game/objects/items.dm
  code/modules/projectiles/projectile.dm
Labels: Fix

#9783 Fix Rust heretic's mansus grasp on doors
  code/modules/antagonists/heretic/knowledge/rust_lore.dm
Labels: Fix

#9821 AZERTY + Misc keybind fixes
  code/modules/keybindings/bindings_client.dm
  code/modules/keybindings/setup.dm
  tgui/packages/tgui/interfaces/PreferencesMenu/KeybindingsPage.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/ServerPreferencesFetcher.tsx
Labels: Tweak, Fix, TGUI-Changes

#9683 Makes the emag run on charges
  code/game/atoms.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/objs.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
  code/modules/mob/living/silicon/robot/robot_defense.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  icons/obj/card.dmi
Labels: Feature, Sprites, Balance/Rebalance, 🔑 Close Key (1/3)

#9386 Datumized mats, for coins
  code/__DEFINES/materials.dm
  code/datums/materials/_material.dm
  code/datums/materials/basemats.dm
  code/game/atoms.dm
  code/game/machinery/fabricators/modular_fabricator.dm
  code/game/machinery/slotmachine.dm
  code/game/objects/items/stacks/sheets/mineral/exotics.dm
  code/game/objects/items/stacks/sheets/organic/wood.dm
  code/modules/cargo/exports/materials.dm
  code/modules/cargo/exports/sheets.dm
  code/modules/mining/coins.dm
  code/modules/mining/mint.dm
  icons/obj/economy.dmi
Labels: Feature, Sprites, Removal, Code Improvement

#9799 Glue tweaks
  code/game/objects/items/devices/glue.dm
  code/modules/clothing/head/_head.dm
  code/modules/uplink/uplink_items.dm
Labels: Tweak, Feature, Fix

#9529 Clean move delay calculation buffer fix, for cheap
  code/modules/mob/mob_movement.dm
Labels: Test Merged, Fix, Removal, Testmerge Passed

#9848 Fix BYOND 515 switch shenanigans with holopara rework
  code/modules/holoparasite/holoparasite_health.dm
Labels: Fix

#9839 Better armour comparisons
  code/__HELPERS/_lists.dm
  code/modules/clothing/clothing.dm
Labels: Tweak

#9760 Abductor mental interface devices messages are now shown to deadchat
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/antagonists/abductor/equipment/gland.dm
Labels: Feature

#9826 Fix Z-Clear not properly removing baseturfs
  code/__HELPERS/string_lists.dm
  code/controllers/subsystem/zclear.dm
Labels: Tweak, Fix, Testmerge Passed

#9822 Introducing the Cardigan Welsh Corgi
  code/modules/mob/living/simple_animal/friendly/dog.dm
  icons/mob/pets.dmi
  icons/mob/pets_held.dmi
  icons/mob/pets_held_lh.dmi
  icons/mob/pets_held_rh.dmi
Labels: Sprites

#9852 Fixes one (1) runtime in antag_panel.dm
  code/modules/admin/antag_panel.dm
Labels: Fix, Administration, Server

#9818 Remove breath-related moodlets and alerts whenever NOBREATH is added
  code/modules/surgery/organs/lungs.dm
Labels: Fix

#9808 Slight armour slowdowns.
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/mob/mob_movement.dm
Labels: Mapping, Fix, Balance/Rebalance

#9812 Add recharging station to Kilo
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Mapping

#9833 Update changeling_lefthand.dmi
  icons/mob/inhands/antag/changeling_lefthand.dmi
  icons/mob/inhands/antag/changeling_righthand.dmi
Labels: Sprites

#9847 Toy shurikens in maint
  _maps/RandomRooms/5x3/sk_rdm089_nastytrap.dmm
  code/_globalvars/lists/maintenance_loot.dm
  code/game/objects/items/weaponry.dm
Labels: Mapping, Tweak

#9775 Fixes spawned humans always having masculine bodytype
  code/__HELPERS/mobs.dm
  code/datums/dna.dm
Labels: Fix

#8883 Ports Dramatic Shuttles
  beestation.dme
  code/__DEFINES/dcs/signals/signals_movable.dm
  code/__DEFINES/dcs/signals/signals_turf.dm
  code/__DEFINES/movement.dm
  code/__DEFINES/shuttles.dm
  code/__DEFINES/subsystems.dm
  code/__DEFINES/traits.dm
  code/controllers/subsystem/movement/hyperspace_drift.dm
  code/controllers/subsystem/movement/movement_types.dm
  code/datums/components/shuttle_cling.dm
  code/game/atoms_movable.dm
  code/game/turfs/open/space/transit.dm
  code/modules/antagonists/revenant/revenant.dm
  code/modules/events/immovable_rod.dm
  code/modules/mapping/space_management/space_reservation.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/space_dragon.dm
Labels: Tweak, Feature

#9853 Adds proper holodeck logging
  code/modules/holodeck/computer.dm
Labels: Administration

#9851 Minor detective tweaks
  _maps/map_files/MetaStation/MetaStation.dmm
  code/modules/cargo/packs.dm
  code/modules/vending/wardrobes.dm
Labels: Mapping, Tweak, Feature, Removal

#9850 Iterator Wiremod Component
  beestation.dme
  code/modules/research/designs/wiremod_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/wiremod/components/utility/iterator.dm
Labels: Feature

#9857 Fixes one (1) minor runtime in rust_lore.dm
  code/modules/antagonists/heretic/knowledge/rust_lore.dm
Labels: Fix

#9825 Removes dna lock from mechs
  code/game/mecha/combat/honker.dm
  code/game/mecha/equipment/tools/work_tools.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_topic.dm
Labels: Balance/Rebalance

#9870 Fixes a critical bug that lets you interact through everything
  code/_onclick/adjacent.dm
Labels: Fix

#9859 Fixes removing wigs from hats not updating the mob's hair
  code/modules/clothing/head/_head.dm
Labels: Fix

#9862 Created holoparasites no longer have their stats linked to their injector
  code/modules/holoparasite/holoparasite_builder.dm
  code/modules/holoparasite/holoparasite_stats.dm
Labels: Fix

#9836 TGUI Crew Manifest: Shion Edition
  beestation.dme
  code/__DEFINES/dcs/signals/signals_global.dm
  code/__DEFINES/jobs.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/jobs.dm
  code/_globalvars/lists/jobs.dm
  code/datums/datacore.dm
  code/modules/client/client_defines.dm
  code/modules/mob/dead/crew_manifest.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/silicon/silicon.dm
  tgui/packages/tgui/interfaces/CrewManifest.tsx
  tgui/packages/tgui/styles/colors.scss
  tgui/packages/tgui/styles/interfaces/CrewManifest.scss
  tgui/packages/tgui/styles/interfaces/PreferencesMenu.scss
  tgui/packages/tgui/styles/main.scss
Labels: Feature, TGUI-Changes

#9873 Logging for Inserting & Removing Things Surgically
  code/modules/surgery/cavity_implant.dm
  code/modules/surgery/implant_removal.dm
  code/modules/surgery/organ_manipulation.dm
Labels: Feature, Administration

#9827 Billy Clubs (and now Fireaxes) Bash Glass (and Grills, Tables, Windoors) Harder
  code/game/objects/items/fireaxe.dm
  code/game/objects/items/weaponry.dm
Labels: Feature

#9871 Fixes the janitor water backpack sprayer not working
  code/game/objects/items/tanks/watertank.dm
Labels: Fix

#9872 Advanced wirebrush fix and small tweak
  code/datums/elements/rust.dm
  code/game/objects/items/tools/wirebrush.dm
Labels: Tweak, Fix

#9877 Fix the H.O.N.K. mech assembly process by redefining the bikehorn as a tool
  code/__DEFINES/tools.dm
  code/game/mecha/mecha_construction_paths.dm
  code/game/objects/items/clown_items.dm
Labels: Fix

#9811 New syndie derringer, .38 dart & EMP bullets. Nerfs .38 specialty ammos.
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/projectiles/ammunition/ballistic/revolver.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/boxes_magazines/internal/revolver.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/projectile/bullets/dart_syringe.dm
  code/modules/projectiles/projectile/bullets/revolver.dm
  code/modules/uplink/uplink_items.dm
  icons/obj/ammo.dmi
  icons/obj/guns/projectile.dmi
Labels: Feature, Sprites, Fix, Balance/Rebalance

#9889 ERT Intro Typo Fix
  code/modules/antagonists/ert/ert.dm
Labels: Grammar and Formatting

#9860 Newfood atomization: Burgers & Pizzas & Processable element
  _maps/RandomRooms/10x5/sk_rdm151_ratburger.dmm
  _maps/RandomRooms/3x3/sk_rdm163_corgi_butcher.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_pizzaparty.dmm
  _maps/RandomRuins/SpaceRuins/Fast_Food.dmm
  _maps/RandomZLevels/SnowCabin.dmm
  _maps/RuinGeneration/13x17_pizzaroom.dmm
  _maps/arenas/beach.dmm
  _maps/arenas/soviet.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/shuttles/emergency/emergency_luxury.dmm
  _maps/shuttles/ruin/ruin_caravan_victim.dmm
  beestation.dme
  code/__DEFINES/tools.dm
  code/__HELPERS/pronouns.dm
  code/__HELPERS/randoms.dm
  code/_onclick/telekinesis.dm
  code/datums/components/food/edible.dm
  code/datums/elements/food/processable.dm
  code/game/atoms.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items/food/burgers.dm
  code/game/objects/items/food/pizza.dm
  code/game/objects/items/food/spaghetti.dm
  code/game/objects/items/kitchen.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/awaymissions/corpse.dm
  code/modules/cargo/bounties/chef.dm
  code/modules/food_and_drinks/food/customizables.dm
  code/modules/food_and_drinks/food/snacks.dm
  code/modules/food_and_drinks/food/snacks/dough.dm
  code/modules/food_and_drinks/food/snacks_burgers.dm
  code/modules/food_and_drinks/food/snacks_pizza.dm
  code/modules/food_and_drinks/pizzabox.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_burger.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pizza.dm
  code/modules/paperwork/fax.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/station_goals/bluespace_tap.dm
  code/modules/vending/liberation.dm
  icons/obj/food/pizza.dmi
  icons/obj/food/pizzaspaghetti.dmi
  icons/obj/food/spaghetti.dmi
  tools/UpdatePaths/Scripts/9860-NEWFOODpizzaburger.txt
Labels: Mapping, Tweak, Feature, Sprites, Tools, Removal, Code Improvement

#9573 Fixes turf_movespeed modifiers affecting flying/floating mobs
  code/modules/mob/living/living_movement.dm
Labels: Balance/Rebalance

#9882 Being on the Emergency Shuttle now counts as "escaping"
  code/game/atoms.dm
Labels: Fix

#9915 Cleanup Crew Manifest UI
  tgui/packages/tgui/components/index.js
  tgui/packages/tgui/interfaces/CrewManifest.tsx
  tgui/packages/tgui/styles/interfaces/CrewManifest.scss
Labels: Tweak, Feature, TGUI-Changes

#9886 Attack effects no longer can apply to entire Areas directly
  code/game/atoms_movable.dm
  code/modules/antagonists/swarmer/swarmer.dm
Labels: Fix, :ballot_box_with_check: Good PR

#9919 Newfood duplication fix + cleans up edibility
  code/__DEFINES/dcs/signals/signals_obj/signals_item/signals_food.dm
  code/datums/components/food/edible.dm
  code/game/objects/items.dm
  code/modules/food_and_drinks/food/customizables.dm
  code/modules/food_and_drinks/food/snacks/dough.dm
  code/modules/surgery/organs/organ_internal.dm
Labels: Fix

#9846 Ports: Adds Sequential mode to SQDL2
  code/modules/admin/verbs/SDQL2/SDQL_2.dm
Labels: Administration

#9896 Fixed missing icon for the docking_port helpers
  code/modules/shuttle/shuttle.dm
  icons/effects/landmarks_static.dmi
Labels: Feature, Sprites, Fix

#9913 I am serious. Removes techweb.dm
  code/modules/modular_computers/file_system/programs/techweb.dm
Labels: Removal

#9865 Changes power_change() to respect parent calls, modernizes and makes it suck less
  code/__DEFINES/dcs/signals/signals_obj/signals_machine/signals_machinery.dm
  code/game/machinery/PDApainter.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/ai_slipper.dm
  code/game/machinery/announcement_system.dm
  code/game/machinery/aug_manipulator.dm
  code/game/machinery/buttons.dm
  code/game/machinery/computer/_computer.dm
  code/game/machinery/dna_scanner.dm
  code/game/machinery/doors/brigdoors.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doppler_array.dm
  code/game/machinery/droneDispenser.dm
  code/game/machinery/embedded_controller/access_controller.dm
  code/game/machinery/firealarm.dm
  code/game/machinery/flasher.dm
  code/game/machinery/gulag_teleporter.dm
  code/game/machinery/hologram.dm
  code/game/machinery/igniter.dm
  code/game/machinery/lightswitch.dm
  code/game/machinery/porta_turret/portable_turret.dm
  code/game/machinery/recharger.dm
  code/game/machinery/rechargestation.dm
  code/game/machinery/recycler.dm
  code/game/machinery/requests_console.dm
  code/game/machinery/slotmachine.dm
  code/game/machinery/stasis.dm
  code/game/machinery/teleporter.dm
  code/game/machinery/transformer.dm
  code/modules/atmospherics/machinery/airalarm.dm
  code/modules/atmospherics/machinery/components/binary_devices/passive_gate.dm
  code/modules/atmospherics/machinery/components/binary_devices/pump.dm
  code/modules/atmospherics/machinery/components/binary_devices/volume_pump.dm
  code/modules/atmospherics/machinery/components/trinary_devices/filter.dm
  code/modules/atmospherics/machinery/components/trinary_devices/mixer.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/atmospherics/machinery/components/unary_devices/outlet_injector.dm
  code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/mining/machine_redemption.dm
  code/modules/mining/machine_vending.dm
  code/modules/modular_computers/computers/machinery/modular_computer.dm
  code/modules/power/generator.dm
  code/modules/power/gravitygenerator.dm
  code/modules/power/lighting/light.dm
  code/modules/power/power.dm
  code/modules/power/singularity/emitter.dm
  code/modules/power/singularity/field_generator.dm
  code/modules/power/singularity/particle_accelerator/particle_control.dm
  code/modules/power/solar.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/recycling/conveyor.dm
  code/modules/recycling/disposal/bin.dm
  code/modules/research/nanites/nanite_chamber.dm
  code/modules/research/nanites/public_chamber.dm
  code/modules/vending/_vending.dm
Labels: Code Improvement

#9902 Fixes the heretic's TGUI menu text not stretching with the window width
  tgui/packages/tgui/interfaces/AntagInfoHeretic.tsx
Labels: Fix, TGUI-Changes

#9920 Small heretic and other antag fix
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/antagonists/heretic/heretic_antag.dm
Labels: Fix

#9923 Fix ranged holopara fire rate
  code/modules/holoparasite/abilities/weapon/projectile.dm
Labels: Fix

#9931 Fix the Shuttle Designator
  code/modules/power/power.dm
  code/modules/shuttle/shuttle_creation/shuttle_creator_console.dm
Labels: Fix

#9928 ports dirt linings
  code/game/objects/effects/decals/turfdecal/weather.dm
  icons/turf/decals.dmi
Labels: Feature, Sprites

#9927 Hedges
  code/game/objects/structures/fluff.dm
Labels: Feature, Code Improvement

#9934 Fixes a holoparasite exploit
  code/modules/holoparasite/holoparasite_reset.dm
Labels: Fix
