Repository BeeStation/BeeStation-Hornet, pull requests merged in 2023-12, with the labels that each got.

#10238 Fix `0.get_idcard()` runtime with holoparasites
  code/modules/holoparasite/_holoparasite.dm
Labels: Fix

#10234 Fix HTML encoding issues with inputs, mainly admin PMs
  code/modules/admin/verbs/_help.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/mentor/mentorpm.dm
  tgui/packages/tgui/interfaces/ListInputModal.tsx
  tgui/packages/tgui/interfaces/TextInputModal.tsx
  tgui/packages/tgui/layouts/Window.js
Labels: Fix, Administration, TGUI-Changes

#10205 Buckled mobs will now be checked for access alongside the mount
  code/modules/jobs/access.dm
Labels: Tweak

#10228 Adds Atmos Devices to Meta Chapel
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Mapping, Fix

#10241 Fix inconsistent changelog generation
  tools/changelog/generate_cl.py
Labels: Tools

#10229 Fixes holopara code using blood brothers chat format color (cfc)
  code/__DEFINES/colors.dm
  code/modules/holoparasite/_holoparasite.dm
  code/modules/holoparasite/holoparasite_builder.dm
  code/modules/holoparasite/holoparasite_setters.dm
Labels: Code Improvement

#10144 Fix light boxes being unable to store lights again
  code/game/objects/items/storage/boxes.dm
Labels: Fix

#10215 Fixes Nanite Nutrition Sensor Rule Display
  code/modules/research/nanites/rules.dm
Labels: Fix

#10095 Lethal shotgun ammo rebalance 2
  code/modules/projectiles/ammunition/ballistic/shotgun.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
Labels: Balance/Rebalance, hacktoberfest-accepted

#10207 Fixes being unable to postpone a subsystem whilst its firing
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/modules/admin/view_variables/reference_tracking.dm
Labels: Administration, Server

#10123 Adds 2 New chems: Barber's Afro Mania and Barber's Shaving Aid.
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
Labels: Feature, Needs Wiki Changes

#10202 Fixes a moved relay bug
  code/datums/components/jam_receiver.dm
  code/datums/components/moved_relay.dm
  code/datums/components/radio_jamming.dm
  code/modules/mob/logout.dm
Labels: Fix

#10251 Revert "Revert "Fixes GetComponents() returning a list with a null entry when there's no component of a given type""
  code/datums/components/_component.dm
Labels: Code Improvement

#10252 Fixes "/datum/component/jam_receiver" throwing runtime
  code/datums/components/jam_receiver.dm
Labels: Code Improvement

#10244 The botany mini dispenser now is actually mini
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
Labels: Fix

#10267 Revert "Fix inconsistent changelog generation (#10241)"
  tools/changelog/generate_cl.py
Labels: Tools

#10247 A cargo crate with several paper bins
  code/modules/cargo/packs.dm
Labels: Feature

#10263 Newfood Atomization: Canned (Beans included)
  _maps/RandomRooms/5x3/sk_rdm061_pubbyclutter4.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_biodome_winter.dmm
  _maps/RandomRuins/SpaceRuins/deepstorage.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/shuttles/emergency/emergency_pubby.dmm
  _maps/shuttles/whiteship/whiteship_meta.dmm
  beestation.dme
  code/_globalvars/lists/maintenance_loot.dm
  code/game/objects/items/food/packaged.dm
  code/modules/cargo/packs.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/vending/mining.dm
  icons/obj/food/canned.dmi
  tools/UpdatePaths/Scripts/10263_NEWFOODpackaged.txt
Labels: Mapping, Feature, Sprites, Tools

#10235 Force-cryo refactor + improvements
  code/__HELPERS/game.dm
  code/modules/admin/admin.dm
  code/modules/admin/player_panel.dm
  code/modules/admin/smites/forcecryo.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/forcecryo.dm
  tgui/packages/tgui/interfaces/PlayerPanel.js
Labels: Administration, TGUI-Changes

#10261 Remove weird viro culture description
  code/modules/uplink/uplink_items.dm
Labels: Tweak

#10262 Newfood Atomization: Sandwiches (Ketchup isn't a Vegetable)
  _maps/RandomRuins/SpaceRuins/Fast_Food.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/shuttles/emergency/emergency_luxury.dmm
  _maps/shuttles/whiteship/whiteship_delta.dmm
  beestation.dme
  code/game/objects/items/food/sandwichtoast.dm
  code/modules/cargo/bounties/chef.dm
  code/modules/food_and_drinks/food/snacks_sandwichtoast.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_bread.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_sandwich.dm
  icons/obj/food/burgerbread.dmi
  tools/UpdatePaths/Scripts/10262_NEWFOODPackaged.txt
Labels: Mapping, Tweak, Feature, Sprites, Tools

#10253 Fixes sends_insanity_pulse() proc using a wrong proc ref macro + minor pop change
  code/game/objects/effects/anomalies/anomaly_insanitypulse.dm
  code/modules/events/anomaly_insanitypulse.dm
Labels: Tweak, Fix

#10230 Adds Bloom
  beestation.dme
  code/__DEFINES/layers.dm
  code/__DEFINES/lighting.dm
  code/_onclick/hud/rendering/plane_master.dm
  code/_onclick/hud/rendering/plane_master_controller.dm
  code/modules/atmospherics/environmental/LINDA_fire.dm
  code/modules/client/preferences/entries/player/bloom.dm
  code/modules/client/preferences/preference_entry.dm
  code/modules/lighting/lighting_corner.dm
  code/modules/lighting/lighting_object.dm
  code/modules/mob/mob.dm
  code/modules/power/apc/apc_main.dm
  code/modules/power/supermatter/supermatter.dm
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/bloom.tsx
Labels: Needs Testmerge, Tweak, Feature, Code Improvement, TGUI-Changes

#10287 Newfood Atomization: Eggs
  _maps/RandomRuins/SpaceRuins/Fast_Food.dmm
  _maps/RandomZLevels/SnowCabin.dmm
  _maps/RuinGeneration/13x13_shotelroom.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/shuttles/emergency/emergency_luxury.dmm
  beestation.dme
  code/controllers/subsystem/traumas.dm
  code/game/objects/effects/spawners/bundle.dm
  code/game/objects/items/food/egg.dm
  code/game/objects/items/storage/fancy.dm
  code/modules/antagonists/abductor/equipment/gland.dm
  code/modules/cargo/bounties/chef.dm
  code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm
  code/modules/food_and_drinks/food/snacks_egg.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_bread.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_burger.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_egg.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_soup.dm
  code/modules/holiday/easter.dm
  code/modules/holiday/halloween.dm
  code/modules/holiday/holidays.dm
  code/modules/hydroponics/grown/eggplant.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/station_goals/bluespace_tap.dm
  icons/obj/food/egg.dmi
  tools/UpdatePaths/Scripts/10287_NEWFOODeggs
Labels: Mapping, Feature, Sprites, Tools

#10248 Ports enhanced Reflector TGUI menu from aetherstation
  code/game/objects/structures/reflector.dm
  tgui/packages/tgui/interfaces/Reflector.tsx
Labels: Feature, TGUI-Changes

#10297 Icewing watcher fixes
  code/datums/status_effects/gas.dm
Labels: Tweak, Fix

#10306 Renames a map-related datum and subsystem to reduce confusion
  beestation.dme
  code/controllers/subsystem/async_map_generator.dm
  code/controllers/subsystem/atoms.dm
  code/controllers/subsystem/shuttle.dm
  code/datums/map_generators/_async_map_generator.dm
  code/datums/map_generators/map_placer.dm
  code/datums/shuttles.dm
  code/modules/admin/verbs/map_template_loadverb.dm
  code/modules/events/fugitive_spawning.dm
  code/modules/events/pirates.dm
  code/modules/holodeck/computer.dm
  code/modules/mapping/map_template.dm
  code/modules/mapping/ruins.dm
  code/modules/ruins/spaceruin_code/hilbertshotel.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/ruin_generator.dm
Labels: Administration, Code Improvement

#10292 Ports a fix for the supply console contraband feature
  code/game/machinery/_machinery.dm
  code/game/objects/items/circuitboards/circuitboard.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/modules/cargo/orderconsole.dm
Labels: Fix

#10285 Bug Fix: Flypeople and eating.
  code/game/objects/effects/decals/cleanable/misc.dm
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
Labels: Tweak, Fix

#8195 RCD, Airlock QoL
  code/__DEFINES/construction.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/airlock_electronics.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/items/RCD.dm
  code/game/objects/items/debug_items.dm
  code/game/objects/items/stacks/rods/rods.dm
  code/game/objects/items/stacks/sheets/mineral/glass.dm
  code/game/objects/items/stacks/sheets/mineral/metals.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/structures/door_assembly.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/tables_racks.dm
  code/game/turfs/open/floor.dm
  code/modules/mining/aux_base_camera.dm
  code/modules/research/designs/tool_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/mob/radial.dmi
  tgui/packages/tgui/interfaces/AirlockElectronics.js
Labels: Tweak, Feature, Sprites, TGUI-Changes

#9876 (Recoup) Ports superior environmental handlers & species-specific temperature handling. Adds warm hugs!
  code/__DEFINES/atmospherics.dm
  code/datums/diseases/advance/symptoms/fever.dm
  code/datums/diseases/advance/symptoms/shivering.dm
  code/datums/mood_events/generic_positive_events.dm
  code/datums/status_effects/buffs.dm
  code/datums/status_effects/gas.dm
  code/modules/mob/living/carbon/alien/alien.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_animal/slime/life.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/research/nanites/nanite_programs/healing.dm
  code/modules/research/xenobiology/crossbreeding/_status_effects.dm
Labels: Feature, Fix, Balance/Rebalance, Refactor

#9824 Nar'sian Beautification - Cult Constructs Resprites & Fixes
  _maps/shuttles/emergency/emergency_narnar.dmm
  code/__DEFINES/antagonists.dm
  code/__DEFINES/cult.dm
  code/_globalvars/lists/mobs.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/book.dm
  code/game/objects/items/weaponry.dm
  code/modules/admin/topic.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/antagonists/cult/cult_structures.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/antagonists/revenant/revenant.dm
  code/modules/antagonists/toddsie.dm
  code/modules/antagonists/wizard/equipment/soulstone.dm
  code/modules/events/portal_storm.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/shade.dm
  code/modules/spells/spell_types/construct_spells.dm
  code/modules/spells/spell_types/ethereal_jaunt.dm
  code/modules/spells/spell_types/shapeshift.dm
  icons/mob/actions/actions_cult.dmi
  icons/mob/cult.dmi
  icons/mob/mob.dmi
  icons/obj/narsie.dmi
  icons/obj/wizard.dmi
  sound/effects/constructform.ogg
Labels: Mapping, Feature, Sprites, Fix, Refactor, Sound, Administration

#10316 Fixes a compilation issue in species
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix, Code Improvement

#10319 Caps Kilo at 20 max players.
  config/maps.txt
Labels: Config Update, i ded

#10321 Update psychic.dmi
  icons/mob/psychic.dmi
Labels: Sprites

#10288 Newfood Atomization: Sweets
  _maps/RandomRooms/3x5/sk_rdm013_boxkitchen.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  _maps/RandomRuins/SpaceRuins/listeningstation.dmm
  _maps/RandomZLevels/undergroundoutpost45.dmm
  _maps/RuinGeneration/13x13_listening_base.dmm
  _maps/RuinGeneration/9x13_kitchen.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/shuttles/emergency/emergency_birdboat.dmm
  _maps/shuttles/emergency/emergency_corg.dmm
  _maps/shuttles/emergency/emergency_luxury.dmm
  _maps/shuttles/emergency/emergency_raven.dmm
  _maps/shuttles/ruin/ruin_caravan_victim.dmm
  _maps/shuttles/whiteship/whiteship_box.dmm
  _maps/shuttles/whiteship/whiteship_delta.dmm
  _maps/shuttles/whiteship/whiteship_meta.dmm
  beestation.dme
  code/game/objects/items/food/sweets.dm
  code/game/objects/items/robot/robot_items.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/fancy.dm
  code/modules/clothing/head/jobs.dm
  code/modules/events/holiday/halloween.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/recipes/food_mixtures.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_cake.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_egg.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pie.dm
  code/modules/holiday/easter.dm
  code/modules/jobs/job_mail.dm
  code/modules/mob/living/carbon/human/species_types/pumpkin_man.dm
  code/modules/vending/snack.dm
  code/modules/vending/sustenance.dm
  icons/obj/food/lollipop.dmi
  tools/UpdatePaths/Scripts/10277_NEWFOODsweets.txt
Labels: Mapping, Tweak, Feature, Sprites, Tools

#10312 Adds a warning to C4/X4 being planted on you
  code/game/objects/items/grenades/plastic.dm
Labels: Balance/Rebalance

#10286 Newfood Atomization: Frozen & Ice Cream
  _maps/RandomRuins/SpaceRuins/Fast_Food.dmm
  _maps/shuttles/emergency/emergency_luxury.dmm
  beestation.dme
  code/game/objects/items/food/frozen.dm
  code/game/objects/items/robot/robot_items.dm
  code/game/objects/structures/morgue.dm
  code/modules/cargo/bounties/chef.dm
  code/modules/food_and_drinks/food/snacks_frozen.dm
  code/modules/food_and_drinks/kitchen_machinery/icecream_vat.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_cake.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_frozen.dm
  code/modules/vending/mining.dm
  tools/UpdatePaths/Scripts/10286_NEWFOODfrozen.txt
Labels: Mapping, Feature, Tools

#10049 CTF rework & fixes pt. 1
  code/game/objects/items.dm
  code/modules/admin/secrets.dm
  code/modules/admin/topic.dm
  code/modules/awaymissions/capture_the_flag.dm
Labels: Fix, Administration, Code Improvement, hacktoberfest-accepted

#10326 Adds a spare full outfit for the clown and the mime for the AutoDrobe
  code/modules/vending/autodrobe.dm
Labels: Tweak, Feature

#10167 More moth customization
  code/modules/mob/dead/new_player/sprite_accessories.dm
  icons/mob/moth_antennae.dmi
  icons/mob/moth_wings.dmi
  icons/mob/moth_wingsopen.dmi
Labels: Feature, Sprites, Fix

#10324 Heretic touhou minigame no longer leaves bluespace wakes
  code/modules/antagonists/heretic/knowledge/sacrifice_knowledge/sacrifice_knowledge.dm
Labels: Fix

#10334 Fixes phsycozia plane masters
  code/_onclick/hud/rendering/plane_master.dm
Labels: Fix

#10146 Minor refactor to machine construction + Fake Computer Toy
  beestation.dme
  code/game/machinery/_machinery.dm
  code/game/machinery/computer/arcade.dm
  code/game/machinery/computer/buildandrepair.dm
  code/game/machinery/computer/fake_toy_computer.dm
  code/game/machinery/constructable_frame.dm
Labels: Feature, Code Improvement

#10213 Nitpicks of Meta Station
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Mapping, Tweak, Feature, Fix, Balance/Rebalance

#9390 Fixes orbit transfer function + some orbit code improvement
  code/_onclick/hud/alert.dm
  code/_onclick/observer.dm
  code/controllers/subsystem/augury.dm
  code/datums/components/orbiter.dm
  code/datums/mind.dm
  code/game/atoms.dm
  code/game/machinery/computer/camera_advanced.dm
  code/modules/admin/admin_follow.dm
  code/modules/antagonists/revenant/revenant_abilities.dm
  code/modules/events/immovable_rod.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/dead/observer/orbit.dm
  code/modules/mob/transform_procs.dm
  code/modules/projectiles/projectile/magic.dm
Labels: Tweak, Fix, Administration, Code Improvement

#9864 [PORT-ISH] Removes (almost) all of the goon folder, refactor gym code
  _maps/RandomRuins/LavaRuins/lavaland_biodome_beach.dmm
  _maps/RandomZLevels/SnowCabin.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  beestation.dme
  code/game/machinery/bank_machine.dm
  code/game/machinery/dish_drive.dm
  code/game/objects/structures/gym/punching_bag.dm
  code/game/objects/structures/gym/weight_machine.dm
  code/game/objects/structures/gym/weight_machine_action.dm
  code/modules/hydroponics/grown/cannabis.dm
  code/modules/mining/lavaland/ruins/gym.dm
  goon/icons/obj/fitness.dmi
  goon/icons/obj/goon_terminals.dmi
  goon/icons/obj/hydroponics.dmi
  goon/icons/obj/kitchen.dmi
  goon/sound/effects/spring.ogg
  icons/obj/computer.dmi
  icons/obj/fitness.dmi
  icons/obj/hydroponics/growing.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/kitchen.dmi
  icons/obj/xenoarchaeology/xenoartifact.dmi
  sound/machines/creak.ogg
Labels: Mapping, Tweak, Feature, Sprites, Refactor, Sound, Removal

#10132 Ensures COMSIG_ATOM_EX_ACT is always called
  code/__DEFINES/combat.dm
  code/__DEFINES/dcs/signals/signals_atom.dm
  code/__DEFINES/explosions.dm
  code/controllers/subsystem/explosion.dm
  code/datums/components/explodable.dm
  code/datums/martial/wrestling.dm
  code/datums/materials/basemats.dm
  code/game/atoms.dm
  code/game/gamemodes/meteor/meteors.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/syndicatebomb.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/items/devices/chameleonproj.dm
  code/game/objects/items/grenades/_grenade.dm
  code/game/objects/items/grenades/plastic.dm
  code/modules/events/immovable_rod.dm
  code/modules/holoparasite/abilities/major/explosive.dm
  code/modules/projectiles/guns/misc/blastcannon.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
  code/modules/reagents/reagent_containers.dm
Labels: Code Improvement

#10308 *ONLY* adds an Icecream Vat to Radstation freezer where a food cart is (brain working 2023)
  _maps/map_files/RadStation/RadStation.dmm
Labels: Mapping, Fix

#10309 CMO Stamp no longer missing from Meta and Delta + fixes the lower airlock in Delta secondary engine room
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Mapping, Fix

#10302 [Port] Fixes Embeds from being blocked by shields and adds the ability to see embeds in health analyzer scans
  code/datums/elements/embed.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/mob/living/living_defense.dm
Labels: Feature, Fix

#10011 All investigate logs include ckey of source (if applicable)
  code/__HELPERS/files.dm
  code/_globalvars/misc.dm
  code/datums/dna.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/computer/warrant.dm
  code/game/machinery/doors/brigdoors.dm
  code/game/objects/items/gift.dm
  code/game/objects/items/peppercloud.dm
  code/modules/admin/admin_investigate.dm
  code/modules/atmospherics/machinery/portable/canister.dm
  code/modules/atmospherics/machinery/portable/pump.dm
  code/modules/atmospherics/machinery/portable/scrubber.dm
  code/modules/cargo/orderconsole.dm
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/seeds.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/modular_computers/file_system/programs/budgetordering.dm
  code/modules/power/singularity/boh_tear.dm
  code/modules/research/machinery/_production.dm
  code/modules/research/nanites/nanite_cloud_controller.dm
  code/modules/research/rdconsole.dm
Labels: Administration, Code Improvement, hacktoberfest-accepted

#10280 More Winter Coats - Expansion Pack
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/mining/mine_items.dm
  code/modules/vending/wardrobes.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Tweak, Feature, Sprites, Code Improvement

#10250 The Dish-Drive no longer disembowels its stock parts upon attack_hand
  code/game/machinery/dish_drive.dm
Labels: Fix

#10283 Day night cycle map config setting
  beestation.dme
  code/__DEFINES/maps.dm
  code/__DEFINES/subsystems.dm
  code/__DEFINES/time.dm
  code/__HELPERS/time.dm
  code/controllers/subsystem/natural_light_cycle.dm
  code/datums/map_config.dm
  code/modules/holiday/holidays.dm
Labels: Feature, Config Update

#10299 Ports 'Save 0.6-0.7s of init time by splitting registering lists of signals into its own proc' and micro-optimizes the SEND_SIGNAL() define
  code/__DEFINES/dcs/helpers.dm
  code/__DEFINES/qdel.dm
  code/datums/ai/dog/dog_controller.dm
  code/datums/components/_component.dm
  code/datums/components/creamed.dm
  code/datums/components/embedded.dm
  code/datums/components/explodable.dm
  code/datums/components/footstep.dm
  code/datums/components/pellet_cloud.dm
  code/datums/components/plumbing/_plumbing.dm
  code/datums/components/shuttle_cling.dm
  code/datums/components/singularity.dm
  code/datums/components/snail_crawl.dm
  code/datums/components/sound_player.dm
  code/datums/components/spawner.dm
  code/datums/components/squeak.dm
  code/datums/components/stationloving.dm
  code/datums/components/waddling.dm
  code/datums/datum.dm
  code/datums/elements/earhealing.dm
  code/datums/elements/item_scaling.dm
  code/datums/elements/rust.dm
  code/datums/status_effects/neutral.dm
  code/game/machinery/computer/station_alert.dm
  code/game/objects/items/tanks/jetpack.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/holoparasite/holoparasite_antag.dm
  code/modules/holoparasite/abilities/major/scout.dm
  code/modules/holoparasite/abilities/weapon/dextrous.dm
  code/modules/mining/machine_processing.dm
  code/modules/mob/living/simple_animal/heretic_monsters.dm
  code/modules/modular_computers/file_system/programs/alarm.dm
  code/modules/recycling/disposal/construction.dm
Labels: Refactor, Code Improvement

#9962 Ports "Resprites ventriloquist dummy" from TG
  code/game/objects/items/toys.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/toy.dmi
Labels: Feature, Sprites, hacktoberfest-accepted

#10336 fix bluespace compression kit
  code/game/objects/items.dm
  code/game/objects/items/devices/compressionkit.dm
Labels: Fix

#10301 Ports damage deflection to messages to complement the Turf Integrity rework
  code/__HELPERS/mobs.dm
  code/_onclick/item_attack.dm
  code/datums/components/pellet_cloud.dm
  code/game/machinery/_machinery.dm
  code/game/objects/obj_defense.dm
  code/game/objects/objs.dm
  code/modules/projectiles/projectile.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  code/modules/surgery/bodyparts/head.dm
Labels: Feature, Fix, Code Improvement

#10323 Psyphoza soul glimmer changes, TGUI chat support
  code/_globalvars/soul_glimmer.dm
  code/datums/components/blind_sense.dm
  code/datums/mind.dm
  code/game/atoms.dm
  code/modules/mob/living/carbon/human/examine.dm
  tgui/packages/tgui-panel/styles/chat-format/chat-dark-theme.scss
  tgui/packages/tgui-panel/styles/chat-format/chat-light-theme.scss
Labels: Feature, Fix, TGUI-Changes

#10127 Rebalances Rubbershot, Beanbag Slugs, .38 Rubber, and 4.6x30mm (WT-550) Rubber Ammunition
  code/modules/projectiles/ammunition/ballistic/shotgun.dm
  code/modules/projectiles/projectile/bullets/revolver.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
  code/modules/projectiles/projectile/bullets/smg.dm
Labels: Balance/Rebalance

#10351 Hotfix: Fixes holding the perfect amount of sheets erroneously consuming the sheets & not progressing construction
  code/game/objects/items/stacks/stack.dm
Labels: Fix

#10352 Fix some improper proc refs
  code/controllers/subsystem/timer.dm
  code/modules/admin/verbs/debug.dm
Labels: Fix, Administration

#10369 Fix lights always turning on at roundstart
  code/modules/power/lighting/light.dm
Labels: Fix

#10359 Adds more lights to BoxStation
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Mapping, Tweak, Feature

#10355 Heretic QoL Pass: Lite Edition
  code/__DEFINES/antagonists.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/turfs.dm
  code/datums/helper_datums/teleport.dm
  code/modules/antagonists/heretic/heretic_antag.dm
  code/modules/antagonists/heretic/heretic_knowledge.dm
  code/modules/antagonists/heretic/heretic_living_heart.dm
  code/modules/antagonists/heretic/heretic_monsters.dm
  code/modules/antagonists/heretic/influences.dm
  code/modules/antagonists/heretic/knowledge/sacrifice_knowledge/sacrifice_knowledge.dm
Labels: Tweak, Feature, Fix

#10378 Revert "Minor refactor to machine construction + Fake Computer Toy"
  beestation.dme
  code/game/machinery/_machinery.dm
  code/game/machinery/computer/arcade.dm
  code/game/machinery/computer/buildandrepair.dm
  code/game/machinery/computer/fake_toy_computer.dm
  code/game/machinery/constructable_frame.dm
Labels: Test Merged

#10020 Ballistics Firearm Operations Overhaul and New Improvised Firearms
  _maps/shuttles/hunter/hunter_russian.dmm
  code/__DEFINES/combat.dm
  code/datums/components/crafting/recipes.dm
  code/game/objects/items/shrapnel.dm
  code/modules/projectiles/ammunition/_ammunition.dm
  code/modules/projectiles/ammunition/ballistic/pistol.dm
  code/modules/projectiles/ammunition/ballistic/revolver.dm
  code/modules/projectiles/ammunition/ballistic/rifle.dm
  code/modules/projectiles/ammunition/ballistic/shotgun.dm
  code/modules/projectiles/boxes_magazines/_box_magazine.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/boxes_magazines/external/shotgun.dm
  code/modules/projectiles/boxes_magazines/external/smg.dm
  code/modules/projectiles/boxes_magazines/internal/_cylinder.dm
  code/modules/projectiles/boxes_magazines/internal/_internal.dm
  code/modules/projectiles/boxes_magazines/internal/rifle.dm
  code/modules/projectiles/boxes_magazines/internal/shotgun.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/guns/ballistic/sniper.dm
  code/modules/projectiles/projectile/bullets/pistol.dm
  code/modules/projectiles/projectile/bullets/revolver.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
  code/modules/research/designs/autolathe_designs.dm
  code/modules/surgery/tools.dm
  icons/mob/inhands/weapons/64x_guns_left.dmi
  icons/mob/inhands/weapons/64x_guns_right.dmi
  icons/obj/ammo.dmi
  icons/obj/guns/projectile.dmi
  icons/obj/tools.dmi
  sound/items/hacksaw.ogg
  sound/weapons/leveractionrack_close.ogg
  sound/weapons/leveractionrack_open.ogg
  sound/weapons/shotgunpump_close.ogg
  sound/weapons/shotgunpump_open.ogg
  sound/weapons/sniper_rack_close.ogg
  sound/weapons/sniper_rack_open.ogg
Labels: Mapping, Tweak, Feature, Sprites, Balance/Rebalance, Refactor, Sound, Code Improvement

#10366 Virology QoL: chem reaction tweaks, more extrapolator details, better culture printing
  code/datums/diseases/advance/advance.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/machinery/pandemic.dm
  code/modules/reagents/chemistry/recipes.dm
  code/modules/reagents/chemistry/recipes/others.dm
Labels: Tweak, Feature, Code Improvement

#10348 Adds Sneakers to the ClothesMate Vendor
  code/modules/clothing/shoes/color.dm
  code/modules/vending/clothesmate.dm
Labels: Feature

#10225 Bluespace launchpad nerf
  code/game/machinery/launch_pad.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
Labels: Balance/Rebalance

#10313 Returning from Ninja Dojo now checks for bad atmosphere + fixes another tiny unrelated issue
  code/modules/ninja/suit/n_suit_verbs/energy_net_nets.dm
  code/modules/vending/security.dm
Labels: Fix

#10357 Adds Quirk Customization: Take 2
  SQL/beestation_schema.sql
  SQL/database_changelog.txt
  beestation.dme
  code/__DEFINES/language.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/subsystems.dm
  code/_globalvars/lists/flavor_misc.dm
  code/controllers/subsystem/traumas.dm
  code/datums/traits/_quirk.dm
  code/datums/traits/negative_quirk.dm
  code/datums/traits/positive_quirk.dm
  code/modules/client/preferences/entries/character/quirks.dm
  code/modules/client/preferences/entries/character/quirks/alcoholic.dm
  code/modules/client/preferences/entries/character/quirks/junkie.dm
  code/modules/client/preferences/entries/character/quirks/multilingual.dm
  code/modules/client/preferences/entries/character/quirks/phobia.dm
  code/modules/client/preferences/entries/character/quirks/prosthetic.dm
  code/modules/client/preferences/entries/character/quirks/smoker.dm
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/custom_quirk.tsx
Labels: SQL, Feature, TGUI-Changes

#9837 Be enthused about Art! Ports the Art element
  beestation.dme
  code/__DEFINES/art.dm
  code/datums/elements/art.dm
  code/datums/mood_events/generic_negative_events.dm
  code/datums/mood_events/generic_positive_events.dm
  code/game/objects/items/weaponry.dm
  code/game/objects/structures/artstuff.dm
  code/game/objects/structures/statues.dm
  code/modules/photography/photos/frame.dm
Labels: Feature
