Repository BeeStation/BeeStation-Hornet, pull requests merged in 2023-10, with the labels that each got.

#9863 Adds linting for and attach() element, and equipped() proc
  code/_onclick/telekinesis.dm
  code/controllers/globals.dm
  code/datums/components/twohanded.dm
  code/datums/elements/_element.dm
  code/datums/martial/boxing.dm
  code/datums/martial/krav_maga.dm
  code/datums/martial/wrestling.dm
  code/game/objects/items.dm
  code/game/objects/items/cigs_lighters.dm
  code/game/objects/items/pitchfork.dm
  code/game/objects/items/robot/robot_items.dm
  code/game/objects/items/weaponry.dm
  code/modules/awaymissions/mission_code/Academy.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/soft_caps.dm
  code/modules/clothing/masks/cluwne.dm
  code/modules/clothing/shoes/cluwne.dm
  code/modules/mob/living/carbon/alien/special/facehugger.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
Labels: Feature, Code Improvement

#9587 Color correction
  beestation.dme
  code/game/area/Space_Station_13_areas.dm
  code/game/area/area_color_correction.dm
  code/game/area/areas.dm
  code/game/area/areas/mining.dm
  code/modules/mapping/mapping_helpers.dm
  code/modules/mob/living/carbon/carbon_movement.dm
  code/modules/mob/living/living.dm
  icons/effects/mapping_helpers.dmi
Labels: Feature, Sprites

#9935 Fix broken dropdowns in tgui chat
  tgui/packages/tgui/components/Dropdown.tsx
Labels: Fix, TGUI-Changes

#9713 Buffs atmosbots
  code/modules/mob/living/simple_animal/bot/atmosbot.dm
Labels: Balance/Rebalance

#9892 Finally fixed that AI node to meta
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Mapping, Fix

#9924 Fixes breaching charges runtiming if they haven't been planted.
  code/modules/exploration_crew/exploration_explosives.dm
Labels: Fix

#9945 Fix simplemobs not properly disabling AI when using set_playable
  code/modules/mob/living/living_sentience.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Fix

#9946 Fixes stacking machines letting you cheese gulag
  code/modules/mining/laborcamp/laborstacker.dm
Labels: Fix

#9925 Fixes integrated hardsuit jetpacks
  code/game/objects/items/tanks/jetpack.dm
  code/modules/clothing/spacesuits/hardsuit.dm
Labels: Fix

#9926 Single-symptom viruses will no longer have random names
  code/datums/diseases/advance/advance.dm
Labels: Fix

#9936 removes gatfruit from silver extracts
  code/__HELPERS/randoms.dm
Labels: Removal

#9895 Fix portrait printer runtime
  code/modules/modular_computers/file_system/programs/portrait_printer.dm
Labels: Fix

#9956 fixes wall-mounted sparkers & floor igniters
  code/game/machinery/igniter.dm
Labels: Fix

#9944 Allows for express supply consoles to be "hacked" with a multitool to enable contraband.
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/modules/cargo/expressconsole.dm
Labels: Feature, Fix, Removal

#9908 TG Chat color standardisation
  code/__DEFINES/colors.dm
  code/game/objects/items/implants/implant_bb.dm
  code/modules/antagonists/brother/brother.dm
  code/modules/mob/living/simple_animal/hostile/space_dragon.dm
  tgui/packages/tgui-panel/styles/chat-format/chat-dark-theme.scss
  tgui/packages/tgui-panel/styles/chat-format/chat-light-theme.scss
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
  tgui/packages/tgui-panel/styles/main.scss
  tgui/packages/tgui-panel/styles/themes/light.scss
Labels: Feature, Code Improvement, TGUI-Changes

#9739 Fix html encoding with brainwashing objectives in tgui
  tgui/packages/tgui/interfaces/AntagInfoBrainwashed.tsx
  tgui/packages/tgui/interfaces/common/ObjectiveSection.tsx
Labels: Fix, TGUI-Changes

#9719 Stasis beds no longer protect against changeling eggs, xeno eggs or zombie tumours
  code/modules/mob/living/carbon/alien/special/alien_embryo.dm
  code/modules/mob/living/simple_animal/hostile/headcrab.dm
  code/modules/zombie/organs.dm
Labels: Balance/Rebalance

#9655 Stat panel general cleanup + Improvements (Partial Bounty)
  code/game/atoms.dm
  code/modules/admin/verbs/_help.dm
  code/modules/mob/mob_stat.dm
  tgui/packages/tgui-panel/stat/StatText.js
  tgui/packages/tgui-panel/styles/components/Stat.scss
Labels: Feature, Fix, Administration, TGUI-Changes

#9478 world.fps and SStimers safety check
  code/controllers/master.dm
  code/game/world.dm
  code/modules/admin/verbs/fps.dm
Labels: Administration, Code Improvement

#9961 Fixed icon discrepancy on R-tables
  icons/obj/smooth_structures/tables/reinforced_table.dmi
Labels: Sprites, Fix

#9953 Abductors can no longer permanently brainwash
  code/modules/surgery/advanced/brainwashing.dm
Labels: Balance/Rebalance

#9963 Makes chocolate milk distinct from normal milk when in a glass
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
Labels: Fix

#9831 Improve consistency with genetics stuff
  code/datums/mutations.dm
  code/datums/mutations/actions.dm
  code/datums/mutations/antenna.dm
  code/datums/mutations/body.dm
  code/datums/mutations/chameleon.dm
  code/datums/mutations/cluwne.dm
  code/datums/mutations/cold.dm
  code/datums/mutations/hulk.dm
  code/datums/mutations/radioactive.dm
  code/datums/mutations/sight.dm
  code/datums/mutations/space_adaptation.dm
  code/datums/mutations/speech.dm
  code/datums/mutations/touch.dm
  code/game/machinery/computer/dna_console.dm
  code/game/machinery/dna_scanner.dm
  code/modules/spells/spell_types/godhand.dm
  code/modules/spells/spell_types/telepathy.dm
  code/modules/spells/spell_types/touch_attacks.dm
Labels: Tweak, Feature, Fix, Sound, Code Improvement

#9834 Computer smoothing from Bay
  _maps/RandomRuins/LavaRuins/lavaland_surface_golem_ship.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_seed_vault.dmm
  code/__DEFINES/icon_smoothing.dm
  code/__HELPERS/icon_smoothing.dm
  code/game/machinery/computer/_computer.dm
  code/game/machinery/computer/arcade.dm
  code/game/machinery/computer/atmos_alert.dm
  code/game/machinery/computer/camera.dm
  code/game/machinery/computer/card.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/security.dm
  code/game/objects/structures/showcase.dm
  code/modules/library/lib_machines.dm
  code/modules/modular_computers/computers/machinery/modular_console.dm
  code/modules/power/solar.dm
  code/modules/shuttle/emergency.dm
  icons/obj/computer.dmi
  icons/obj/modular_console.dmi
Labels: Mapping, Feature, Sprites, Code Improvement

#9972 Fixes Z-Copy breaking stat tabs & Adds in validation for MC stat panels
  code/controllers/subsystem/zcopy.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/stat_mc.dm
Labels: Feature, Somewhat Important

#9984 Fixes a runtime associated with touch spells
  code/modules/antagonists/heretic/magic/mansus_grasp.dm
  code/modules/spells/spell_types/godhand.dm
  code/modules/spells/spell_types/touch_attacks.dm
Labels: Fix

#9977 Fix negative eye_blind leading to permanent blindness
  code/modules/mob/status_procs.dm
Labels: Fix, Somewhat Important

#9978 Ports Tarot Cards, for Thematics:tm:
  beestation.dme
  code/game/objects/items/toys.dm
  code/modules/client/loadout/loadout_general.dm
  code/modules/games/tarot.dm
  code/modules/vending/games.dm
  icons/obj/toy.dmi
Labels: Feature, Sprites

#10000 FARTIN' SHARTIN' CLOWNS (SOVLFUL PR #10000)
  code/modules/mob/living/carbon/human/emote.dm
Labels: Feature, Server

#10002 Revert "Adds the soul back (#10000)"
  code/modules/mob/living/carbon/human/emote.dm
Labels: Removal, i ded, Ike Hates Fun, 🔑 Close Key (1/3)

#9942 Fixes Particle Accelerators being unable to activate tesla/singulo engine.
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/energy/accelerator_particle.dm
Labels: Fix, Code Improvement

#9981 Removes Deputy from the preferences menu
  code/__DEFINES/jobs.dm
  code/modules/jobs/job_types/deputy.dm
Labels: Removal

#9980 nanite cloud controller hotfix
  code/modules/research/nanites/nanite_cloud_controller.dm
Labels: Test Merged, Fix

#9973 Steal objectives now check holoparasite inventories
  code/game/gamemodes/objectives/basic/steal.dm
Labels: Fix

#9985 Fix color correction runtime
  code/game/area/area_color_correction.dm
Labels: Fix

#10004 Fixes MC tab breaking 2
  code/controllers/subsystem/profiler.dm
  code/modules/unit_tests/stat_mc.dm
  tgui/packages/tgui-panel/stat/StatText.js
Labels: Fix, TGUI-Changes, Somewhat Important

#9982 Removes a useless duplicate of the spell burger recipe
  code/modules/food_and_drinks/recipes/tablecraft/recipes_burger.dm
Labels: Fix

#9975 Converts Suit Storage Units to use radials!
  code/game/machinery/suit_storage_unit.dm
  icons/mob/radial.dmi
  tgui/packages/tgui/interfaces/SuitStorageUnit.js
Labels: Feature, Sprites, Code Improvement, TGUI-Changes

#10006 Button.Input TGUI component now accepts Enter and Esc
  tgui/packages/tgui/components/Button.js
Labels: Fix, TGUI-Changes

#9999 Goliath tweaks
  code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
Labels: Tweak

#9979 Zombie tumors now do brain damage instead of toxin
  code/modules/mob/living/carbon/human/species_types/zombies.dm
  code/modules/zombie/organs.dm
Labels: Tweak, Removal

#9987 Converts emp component into an element
  beestation.dme
  code/datums/components/empprotection.dm
  code/datums/elements/empprotection.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/camera/presets.dm
  code/game/machinery/porta_turret/portable_turret.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/grenades/chem_grenade.dm
  code/game/objects/items/grenades/plastic.dm
  code/modules/antagonists/traitor/equipment/Malf_Modules.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
  code/modules/power/cell.dm
  code/modules/power/singularity/emitter.dm
  code/modules/power/singularity/field_generator.dm
Labels: Code Improvement

#9989 Makes emitter code less terrible
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  code/modules/awaymissions/mission_code/challenge.dm
  code/modules/power/singularity/containment_field.dm
  code/modules/power/singularity/emitter.dm
  icons/obj/turrets.dmi
Labels: Mapping, Feature, Sprites, Fix, Code Improvement

#9952 Adds the ability to hold people at gunpoint.
  code/datums/chatmessage.dm
  code/datums/components/aiming.dm
  code/modules/projectiles/gun.dm
  icons/effects/aiming.dmi
Labels: Feature, Sprites

#9966 Improves item's action_button updating code
  code/game/atoms.dm
  code/game/objects/items.dm
  code/game/objects/items/chainsaw.dm
  code/game/objects/items/defib.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/tanks/jetpack.dm
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/glasses/engine_goggles.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/shoes/bananashoes.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/suits/toggles.dm
  code/modules/mining/equipment/regenerative_core.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/surgery/organs/augments_chest.dm
Labels: Feature, Code Improvement

#9971 "Fixes" small pockets, Nerfs hat storage, Limits candleboxes, Removes sign storage
  code/datums/components/storage/concrete/pockets.dm
  code/game/objects/items/storage/fancy.dm
  code/modules/clothing/suits/miscellaneous.dm
Labels: Balance/Rebalance, Balance Approved

#10012 Fix duplicate bulletproof armour in metastation armoury
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Mapping, Fix

#10017 Removes newline that makes Fland not load
  _maps/map_files/FlandStation/FlandStation.dmm
Labels: Mapping, Fix

#10018 Excommunicates can't purchase syndicate comms anymore
  code/__DEFINES/uplink.dm
  code/datums/mind.dm
  code/modules/uplink/uplink_items.dm
Labels: Balance/Rebalance

#10008 Adds Mosin Obrez (Sawn-Off Mosin Nagant) & Sawing-Off Tweaks
  code/game/objects/items/melee/energy.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/obj/guns/projectile.dmi
Labels: Tweak, Feature, Sprites, Balance/Rebalance, Refactor, Code Improvement

#10013 Makes automatic shotguns semi-automatic (and fixes a sound runtime)
  _maps/shuttles/pirate/pirate_default.dmm
  code/game/gamemodes/nuclear/nuclear.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/spells/spell_types/rightandwrong.dm
  code/modules/uplink/uplink_items.dm
Labels: Mapping, Feature, Fix, Code Improvement

#10019 Hotfix for pizzaboxes
  code/modules/food_and_drinks/pizzabox.dm
Labels: Fix

#10031 Fix Sabotage and Explosion Objectives For Telecommunications
  code/game/gamemodes/objectives/open/destroy_equipment.dm
  code/game/gamemodes/objectives/open/explosion.dm
Labels: Fix

#10015 Fixes for Computer Smoothing
  code/__DEFINES/icon_smoothing.dm
  code/__HELPERS/icon_smoothing.dm
  code/game/machinery/bank_machine.dm
  code/game/machinery/computer/_computer.dm
  code/modules/antagonists/abductor/machinery/camera.dm
  code/modules/antagonists/clock_cult/structure/clockwork_camera.dm
  code/modules/mining/aux_base.dm
  code/modules/modular_computers/computers/machinery/modular_console.dm
  code/modules/power/solar.dm
  code/modules/station_goals/bsa.dm
  icons/obj/computer.dmi
  icons/obj/modular_console.dmi
Labels: Feature, Sprites, Fix, Code Improvement

#10030 Fire rate crosshair
  code/__HELPERS/mouse_control.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  icons/effects/cooldown_cursors/cooldown_1.dmi
  icons/effects/cooldown_cursors/cooldown_2.dmi
  icons/effects/cooldown_cursors/cooldown_3.dmi
  icons/effects/cooldown_cursors/cooldown_4.dmi
  icons/effects/cooldown_cursors/cooldown_5.dmi
  icons/effects/cooldown_cursors/cooldown_6.dmi
  icons/effects/cooldown_cursors/cooldown_7.dmi
  icons/effects/cooldown_cursors/cooldown_8.dmi
  icons/effects/cooldown_cursors/cooldown_9.dmi
Labels: Feature, Sprites

#10026 Fixes tablecrafted newfood recipes not getting reagents from ingredients
  code/datums/components/food/edible.dm
  code/game/atoms.dm
Labels: Fix

#9570 Mobility Atomization 3: Unconsciousness
  beestation.dme
  code/__DEFINES/traits.dm
  code/_onclick/cyborg.dm
  code/datums/diseases/advance/symptoms/heal.dm
  code/datums/status_effects/debuffs.dm
  code/modules/antagonists/changeling/powers/fakedeath.dm
  code/modules/mob/living/carbon/alien/larva/larva.dm
  code/modules/mob/living/carbon/alien/larva/life.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/monkey/monkey_defense.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/init_signals.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_defense.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/living/status_procs.dm
Labels: Fix, Balance/Rebalance, Code Improvement

#10041 [HOTFIX: "Okay, *what*?" edition] Fixes Immortal simple_animals
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Fix

#10025 Fix Index Table Component
  code/modules/wiremod/components/list/index_table.dm
Labels: Fix

#10036 Fixes stat atom light mode
  tgui/packages/tgui-panel/styles/components/Stat.scss
Labels: Fix, TGUI-Changes

#9899 Refactor preference loading, add extensive logging
  code/__DEFINES/preferences.dm
  code/__HELPERS/_logging.dm
  code/_globalvars/logging.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/preferences.dm
  code/game/world.dm
  code/modules/client/preferences/middleware/antags.dm
  code/modules/client/preferences/middleware/keybindings.dm
  code/modules/client/preferences/middleware/loadout.dm
  code/modules/client/preferences/middleware/names.dm
  code/modules/client/preferences/middleware/quirks.dm
  code/modules/client/preferences/middleware/random.dm
  code/modules/client/preferences/preference_entry.dm
  code/modules/client/preferences/preferences.dm
  code/modules/client/preferences/serialization/preferences_character.dm
  code/modules/client/preferences/serialization/preferences_database.dm
  code/modules/client/preferences/serialization/preferences_player.dm
  code/modules/client/preferences/submodules/preference_character_preview.dm
  code/modules/client/preferences/submodules/preference_jobs.dm
  code/modules/client/preferences/submodules/preference_keybindings.dm
  code/modules/client/preferences/submodules/preference_randomization.dm
  config/config.txt
Labels: SQL, Feature, Config Update, Administration, Code Improvement, Testmerge Passed

#9705 AFK players now show up as SSD on examine (+ soft ping port)
  beestation.dme
  code/__DEFINES/dcs/signals/signals_mob/signals_mob.dm
  code/__DEFINES/subsystems.dm
  code/controllers/subsystem/ping.dm
  code/game/data_huds.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/tgui/tgui.dm
  code/modules/tgui/tgui_window.dm
  tgui/packages/tgui-panel/game/constants.js
  tgui/packages/tgui-panel/game/middleware.js
  tgui/packages/tgui-panel/ping/actions.js
  tgui/packages/tgui-panel/ping/constants.js
  tgui/packages/tgui-panel/ping/middleware.js
  tgui/packages/tgui-panel/ping/reducer.js
  tgui/packages/tgui/backend.ts
Labels: Feature, Fix, TGUI-Changes

#10044 Fixes there being an internal radio implant instead of a radio in the metastation's medbay security post
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Mapping, Fix

#9754 Area flag for hidden stashes
  code/__DEFINES/flags.dm
  code/_globalvars/bitfields.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas/holodeck.dm
  code/game/gamemodes/objectives/_objective.dm
Labels: Fix

#9314 Machines now store components in contents + dumping inventory cleanup
  code/game/machinery/_machinery.dm
  code/game/machinery/computer/_computer.dm
  code/game/machinery/computer/arcade.dm
  code/game/machinery/computer/buildandrepair.dm
  code/game/machinery/constructable_frame.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/machinery/teleporter.dm
  code/game/objects/items/circuitboards/circuitboard.dm
  code/game/objects/objs.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/antagonists/swarmer/swarmer.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/atmospherics/machinery/components/binary_devices/circulator.dm
  code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
  code/modules/food_and_drinks/kitchen_machinery/gibber.dm
  code/modules/food_and_drinks/kitchen_machinery/microwave.dm
  code/modules/food_and_drinks/kitchen_machinery/processor.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/power/generator.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/research/server.dm
  code/modules/vending/cola.dm
  code/modules/vending/snack.dm
Labels: Feature, Fix, Refactor

#9909 Newfood atomization: Dough & Mexican food
  _maps/RandomRuins/SpaceRuins/Fast_Food.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  _maps/shuttles/emergency/emergency_corg.dmm
  _maps/shuttles/emergency/emergency_luxury.dmm
  _maps/shuttles/whiteship/whiteship_box.dmm
  beestation.dme
  code/__DEFINES/construction.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items/food/dough.dm
  code/game/objects/items/food/mexican.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/cargo/bounties/chef.dm
  code/modules/food_and_drinks/food/condiment.dm
  code/modules/food_and_drinks/food/snacks/dough.dm
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/recipes/food_mixtures.dm
  code/modules/food_and_drinks/recipes/processor_recipes.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_bread.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_burger.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_mexican.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pie.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pizza.dm
  code/modules/station_goals/bluespace_tap.dm
  icons/obj/food/food.dmi
  icons/obj/food/mexican.dmi
  tools/UpdatePaths/Scripts/9909_NEWFOODdoughmexican.txt
Labels: Mapping, Feature, Sprites, Fix, Balance/Rebalance, Tools, Code Improvement

#9893 Add playtime support for removed jobs
  code/modules/jobs/job_exp.dm
  code/modules/jobs/job_report.dm
  code/modules/jobs/jobs.dm
  tgui/packages/tgui/interfaces/TrackedPlaytime.js
Labels: Code Improvement, TGUI-Changes

#10056 Revert "AFK players now show up as SSD on examine (+ soft ping port) …
  beestation.dme
  code/__DEFINES/dcs/signals/signals_mob/signals_mob.dm
  code/__DEFINES/subsystems.dm
  code/controllers/subsystem/ping.dm
  code/game/data_huds.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/tgui/tgui.dm
  code/modules/tgui/tgui_window.dm
  tgui/packages/tgui-panel/game/constants.js
  tgui/packages/tgui-panel/game/middleware.js
  tgui/packages/tgui-panel/ping/actions.js
  tgui/packages/tgui-panel/ping/constants.js
  tgui/packages/tgui-panel/ping/middleware.js
  tgui/packages/tgui-panel/ping/reducer.js
  tgui/packages/tgui/backend.ts
Labels: Removal, TGUI-Changes

#10033 Durathread buff
  code/modules/clothing/head/beanie.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/color.dm
  code/modules/hydroponics/grown/cotton.dm
Labels: Balance/Rebalance

#10047 Fixes bad initialize with random vendors
  _maps/RandomRooms/10x10/sk_rdm133_oldoffice.dmm
  _maps/RandomRooms/10x5/sk_rdm045_deltacafeteria.dmm
  _maps/RandomRooms/10x5/sk_rdm161_kilovault.dmm
  _maps/RandomRooms/5x3/sk_rdm101_minibreakroom.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_03_vendingminimarket.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  _maps/RandomRuins/SpaceRuins/clownplanet.dmm
  _maps/RandomRuins/SpaceRuins/listeningstation.dmm
  _maps/RandomZLevels/TheBeach.dmm
  _maps/RandomZLevels/snowdin.dmm
  _maps/RuinGeneration/13x13_donutroom.dmm
  _maps/RuinGeneration/13x13_listening_base.dmm
  _maps/RuinGeneration/13x17_permabrig.dmm
  _maps/RuinGeneration/17x9_pubbybridgehall.dmm
  _maps/RuinGeneration/21x17_shuttledock.dmm
  _maps/RuinGeneration/5x9_lounge.dmm
  _maps/arenas/dorms.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/map_files/RadStation/RadStation.dmm
  _maps/templates/shelter_3.dmm
  _maps/templates/warped_room.dmm
  beestation.dme
  code/game/objects/effects/spawners/vending.dm
  code/modules/vending/cola.dm
  code/modules/vending/snack.dm
Labels: Mapping, Refactor, Removal, :ballot_box_with_check: Good PR

#10043 Adds SOP Books
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  code/game/objects/items/manuals.dm
  code/modules/library/lib_machines.dm
  icons/obj/library.dmi
Labels: Mapping, Feature, Sprites

#10040 Mobility atomization 4: Immobilized
  code/__DEFINES/dcs/signals/signals_mob/signals_living.dm
  code/__DEFINES/dcs/signals/signals_movable.dm
  code/__DEFINES/traits.dm
  code/datums/components/chasm.dm
  code/datums/status_effects/debuffs.dm
  code/datums/status_effects/gas.dm
  code/game/atoms_movable.dm
  code/game/objects/buckling.dm
  code/game/objects/items/robot/robot_parts.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/mining/fulton.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/vehicles/wheelchair.dm
Labels: Code Improvement

#10045 Fixes Nightmare outfit oversight
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
Labels: Fix, Balance/Rebalance

#9965 Converts more update_icons to update_appearance, improves update_x calls, fixes broken sprites
  beestation.dme
  code/datums/action.dm
  code/datums/components/armor_plate.dm
  code/datums/elements/update_icon_blocker.dm
  code/datums/elements/update_icon_updates_onmob.dm
  code/game/machinery/harvester.dm
  code/game/machinery/iv_drip.dm
  code/game/machinery/recharger.dm
  code/game/mecha/mech_bay.dm
  code/game/mecha/mecha.dm
  code/game/mecha/working/ripley.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/RCD.dm
  code/game/objects/items/RCL.dm
  code/game/objects/items/candle.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/chrono_eraser.dm
  code/game/objects/items/cigs_lighters.dm
  code/game/objects/items/crayons.dm
  code/game/objects/items/defib.dm
  code/game/objects/items/devices/geiger_counter.dm
  code/game/objects/items/devices/lightreplacer.dm
  code/game/objects/items/devices/powersink.dm
  code/game/objects/items/devices/quantum_keycard.dm
  code/game/objects/items/devices/swapper.dm
  code/game/objects/items/devices/taperecorder.dm
  code/game/objects/items/dice.dm
  code/game/objects/items/etherealdiscoball.dm
  code/game/objects/items/flamethrower.dm
  code/game/objects/items/handcuffs.dm
  code/game/objects/items/hot_potato.dm
  code/game/objects/items/hourglass.dm
  code/game/objects/items/implants/implantcase.dm
  code/game/objects/items/implants/implantchair.dm
  code/game/objects/items/implants/implanter.dm
  code/game/objects/items/implants/implantpad.dm
  code/game/objects/items/inducer.dm
  code/game/objects/items/melee/misc.dm
  code/game/objects/items/pet_carrier.dm
  code/game/objects/items/pinpointer.dm
  code/game/objects/items/pneumaticCannon.dm
  code/game/objects/items/robot/robot_items.dm
  code/game/objects/items/robot/robot_parts.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/game/objects/items/shields.dm
  code/game/objects/items/stacks/rods/rods.dm
  code/game/objects/items/stacks/rods/rods_recipes.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/storage/bags.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/fancy.dm
  code/game/objects/items/storage/lockbox.dm
  code/game/objects/items/storage/toolbox.dm
  code/game/objects/items/storage/wallets.dm
  code/game/objects/items/stunbaton.dm
  code/game/objects/items/theft_tools.dm
  code/game/objects/items/tools/weldingtool.dm
  code/game/objects/items/tools/wirecutters.dm
  code/game/objects/items/toys.dm
Labels: Fix, Code Improvement

#10010 [MDB Ignore]DMM Supercruise - Assorted Fixes
  _maps/RuinGeneration/13x13_ai-lab.dmm
  _maps/RuinGeneration/13x13_corgrobotics.dmm
  _maps/RuinGeneration/13x13_donutroom.dmm
  _maps/RuinGeneration/13x13_listening_base.dmm
  _maps/RuinGeneration/13x13_shotelroom.dmm
  _maps/RuinGeneration/13x17_chapel.dmm
  _maps/RuinGeneration/13x17_permabrig.dmm
  _maps/RuinGeneration/13x9_medical.dmm
  _maps/RuinGeneration/13x9_researchlab.dmm
  _maps/RuinGeneration/17x17_charliecrew.dmm
  _maps/RuinGeneration/21x21_singularity.dmm
  _maps/RuinGeneration/41x41_corgasteroid.dmm
  _maps/RuinGeneration/5x5_hern_damaged.dmm
  _maps/RuinGeneration/5x5_hernsw_damaged.dmm
  _maps/RuinGeneration/5x5_hernw.dmm
  _maps/RuinGeneration/5x5_hernw_damaged.dmm
  _maps/RuinGeneration/5x5_hers.dmm
  _maps/RuinGeneration/5x5_hers_damaged.dmm
  _maps/RuinGeneration/5x5_hersw.dmm
  _maps/RuinGeneration/5x5_hersw_damaged.dmm
  _maps/RuinGeneration/5x5_hesrnw_damaged.dmm
  _maps/RuinGeneration/5x5_heswrn_damaged.dmm
  _maps/RuinGeneration/5x5_hew_damaged.dmm
  _maps/RuinGeneration/5x5_hewrn_damaged.dmm
  _maps/RuinGeneration/5x5_hewrns_damaged.dmm
  _maps/RuinGeneration/5x5_hewrs_damaged.dmm
  _maps/RuinGeneration/5x5_hnersw_damaged.dmm
  _maps/RuinGeneration/5x5_hnesrw_damaged.dmm
  _maps/RuinGeneration/5x5_hnewrs_damaged.dmm
  _maps/RuinGeneration/5x5_hnresw_damaged.dmm
  _maps/RuinGeneration/5x5_hns_damaged.dmm
  _maps/RuinGeneration/5x5_hnswre_damaged.dmm
  _maps/RuinGeneration/5x5_hnwres_damaged.dmm
  _maps/RuinGeneration/5x5_hsrnew_damaged.dmm
  _maps/RuinGeneration/5x5_hswrne_damaged.dmm
  _maps/RuinGeneration/5x5_hwres.dmm
  _maps/RuinGeneration/5x5_hwres_damaged.dmm
  _maps/RuinGeneration/5x5_hwrn.dmm
  _maps/RuinGeneration/5x5_hwrn_damaged.dmm
  _maps/RuinGeneration/5x5_hwrne.dmm
  _maps/RuinGeneration/5x5_hwrne_damaged.dmm
  _maps/RuinGeneration/5x5_hwrnes_damaged.dmm
  _maps/RuinGeneration/5x5_hwrns.dmm
  _maps/RuinGeneration/5x5_hwrns_damaged.dmm
  _maps/RuinGeneration/5x5_hwrs.dmm
  _maps/RuinGeneration/5x5_hwrs_damaged.dmm
  _maps/RuinGeneration/5x9_lounge.dmm
  _maps/RuinGeneration/9x9_elevator.dmm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/mapping.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/ruin_part_types.dm
Labels: Mapping, Fix

#9257 Closed valves and pumps and vents now block ventcrawling and other tweaks
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/atmospherics/machinery/components/binary_devices/dp_vent_pump.dm
  code/modules/atmospherics/machinery/components/binary_devices/pump.dm
  code/modules/atmospherics/machinery/components/binary_devices/valve.dm
  code/modules/atmospherics/machinery/components/binary_devices/volume_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/atmospherics/machinery/components/unary_devices/passive_vent.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
Labels: Tweak, Balance/Rebalance, 🔑 Close Key (1/3)

#9888 Fixes dead people spamming "drowning" messages
  code/modules/pool/components/swimming.dm
Labels: Fix

#9914 Oozeling hair buff
  code/__DEFINES/traits.dm
  code/datums/diseases/advance/symptoms/shedding.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/oozelings.dm
Labels: Tweak

#10060 Removes double definition introduced by #9965 so the game can compile
  code/game/objects/items/robot/robot_items.dm
Labels: Test Merged, Code Improvement

#10058 Fixes Damage Overlays
  code/modules/mob/living/carbon/update_icons.dm
  code/modules/surgery/bodyparts/bodyparts.dm
Labels: Fix

#10055 Witch Wing Wing Sprite Port
  code/modules/mob/dead/new_player/sprite_accessories.dm
  icons/mob/moth_antennae.dmi
  icons/mob/moth_wings.dmi
  icons/mob/moth_wingsopen.dmi
Labels: Feature, Sprites

#10032 Fixes boxstation air around the front of engineering
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Mapping, Fix

#10064 Fixes ventcrawling
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/atmospherics/machinery/components/binary_devices/dp_vent_pump.dm
  code/modules/atmospherics/machinery/components/binary_devices/pump.dm
  code/modules/atmospherics/machinery/components/binary_devices/valve.dm
  code/modules/atmospherics/machinery/components/binary_devices/volume_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/mob/living/ventcrawling.dm
Labels: THIS IS VERY IMPORTANT, Fix

#9604 Stack overflow detection for the Master Controller.
  beestation.dme
  code/controllers/failsafe.dm
  code/controllers/master.dm
  code/datums/helper_datums/stack_end_detector.dm
Labels: Test Merged, Feature, Server

#9704 Food Supply Changes and Food Fillers
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  code/game/objects/items/storage/fancy.dm
  code/modules/cargo/packs.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/food/snacks_pastry.dm
  code/modules/food_and_drinks/food/snacks_vend.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/vending/security.dm
Labels: Mapping, Feature, Balance/Rebalance, Removal, Balance Approved

#9216 Nanitemania: more nanite programs and stuff!
  beestation.dme
  code/__DEFINES/mobs.dm
  code/__DEFINES/nanites.dm
  code/datums/components/nanites.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/research/designs/electronics_designs.dm
  code/modules/research/designs/nanite_designs.dm
  code/modules/research/nanites/nanite_cloud_controller.dm
  code/modules/research/nanites/nanite_misc_items.dm
  code/modules/research/nanites/nanite_programs.dm
  code/modules/research/nanites/nanite_programs/buffing.dm
  code/modules/research/nanites/nanite_programs/protocol.dm
  code/modules/research/nanites/nanite_programs/sensor.dm
  code/modules/research/nanites/nanite_programs/utility.dm
  code/modules/research/nanites/nanite_remote.dm
  code/modules/research/nanites/rules.dm
  code/modules/research/techweb/all_nodes.dm
  icons/effects/blood.dmi
  icons/mob/inhands/weapons/melee_lefthand.dmi
  icons/mob/inhands/weapons/melee_righthand.dmi
  icons/obj/nanite.dmi
  tgui/packages/tgui/interfaces/NaniteCloudControl.js
Labels: Tweak, Feature, Sprites, Balance/Rebalance, Needs Wiki Changes, TGUI-Changes

#9688 Emags no longer have a permanent effect on airlocks
  code/datums/wires/airlock.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
Labels: Tweak, Fix

#10069 Adds carving to Pumpkin People
  code/__DEFINES/obj_flags.dm
  code/modules/mob/living/carbon/human/species_types/pumpkin_man.dm
  code/modules/surgery/bodyparts/species_parts/misc_bodyparts.dm
  code/modules/surgery/organs/tongue.dm
  icons/mob/pumpkin_faces.dmi
Labels: Tweak, Feature, Sprites

#10074 Batongs no longer have power on par with Pool Noodles
  code/datums/components/embedded.dm
  code/modules/antagonists/revenant/revenant_abilities.dm
  code/modules/antagonists/revenant/revenant_blight.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/carbon/status_procs.dm
Labels: Fix

#10057 Firefighter helmet now covers your face
  code/modules/clothing/head/hardhat.dm
Labels: Fix

#9881 Teleporter machinery now autolinks. Adds unit test.
  code/game/machinery/computer/teleporter.dm
  code/game/machinery/teleporter.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/teleporters.dm
Labels: Tweak, Feature, Code Improvement

#10088 Updates the CI to use a system supplied node to cut down on NodeJS ratelimits
  .github/workflows/continuous_integration.yml
Labels: GitHub

#10081 Glowing goo can be destroyed by the lighteater.
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
Labels: Balance/Rebalance

#10065 Moth Wings Fix
  icons/mob/moth_wingsopen.dmi
Labels: Tweak, Sprites

#10042 Adds a mapping helper that can cycle multiple airlocks regardless of dir/location
  _maps/map_files/MetaStation/MetaStation.dmm
  code/game/machinery/doors/airlock.dm
  code/modules/mapping/mapping_helpers.dm
  icons/effects/mapping_helpers.dmi
Labels: Mapping, Feature, Sprites

#10085 Spiderlings no longer Initialize twice
  code/game/objects/effects/spiders.dm
Labels: Code Improvement

#10071 Fixes typo in preference logging
  code/modules/client/preferences/serialization/preferences_player.dm
Labels: Fix, Grammar and Formatting

#10070 Replaces inconsistent implementations of the square root of 2
  code/__DEFINES/maths.dm
  code/datums/components/riding.dm
  code/modules/mob/mob_movement.dm
Labels: Code Improvement

#10034 Adds in unholstering delay + slowdown
  code/__DEFINES/movespeed_modification.dm
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/guns/magic.dm
  code/modules/projectiles/guns/misc/medbeam.dm
Labels: Sprites, Balance/Rebalance, Testmerge Passed

#10086 Flashes don't ignore the blindness check anymore
  code/modules/assembly/flash.dm
Labels: Fix

#9954 Robotized/Roundstart borgs now transfer DNA and quirks from their old body correctly
  code/controllers/subsystem/ticker.dm
  code/datums/traits/negative_quirk.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/brain/MMI.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/transform_procs.dm
Labels: Tweak, Fix

#10072 Adds Bubble tea to the game / Fixes drinks name
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/vending/coffee.dm
  icons/obj/drinks.dmi
Labels: Feature, Sprites, Fix

#10078 Mobility Atomization 5: Floored
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/status_effects/debuffs.dm
  code/game/atoms_movable.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/status_procs.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/status_procs.dm
Labels: Code Improvement

#10089 Integrated headwear (from hooded and hard suits) are now Fireproofed by the Fireproof chaplain spell
  code/modules/religion/rites.dm
Labels: Feature, Fix

#10052 Mulebot code cleanup, bot battery level & running over orphans
  code/__DEFINES/dcs/signals/signals_mob/signals_mob.dm
  code/__DEFINES/dcs/signals/signals_movable.dm
  code/game/atoms_movable.dm
  code/game/data_huds.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/mulebot.dm
  code/modules/mob/mob_movement.dm
Labels: Feature, Refactor, Code Improvement

#10087 Shadow Sect
  code/__DEFINES/is_helpers.dm
  code/__HELPERS/global_lists.dm
  code/_globalvars/religion.dm
  code/datums/components/religious_tool.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/religion/religion_sects.dm
  code/modules/religion/religion_structures.dm
  code/modules/religion/rites.dm
  code/modules/uplink/uplink_items.dm
  icons/obj/hand_of_god_structures.dmi
Labels: Feature, Sprites

#9937 Newfood Atomization: Splits Pastries.dm into 4, converts to newfood
  _maps/RandomRooms/5x3/sk_rdm071_pubbykitchen.dmm
  _maps/RandomRooms/5x4/sk_rdm021_boxdinner.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_animal_hospital.dmm
  _maps/RandomRuins/SpaceRuins/derelict6.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/shuttles/emergency/emergency_luxury.dmm
  _maps/shuttles/emergency/emergency_zeta.dmm
  _maps/shuttles/whiteship/whiteship_box.dmm
  _maps/shuttles/whiteship/whiteship_delta.dmm
  beestation.dme
  code/__DEFINES/food.dm
  code/controllers/subsystem/traumas.dm
  code/datums/components/food/edible.dm
  code/datums/recipe.dm
  code/game/machinery/fat_sucker.dm
  code/game/machinery/syndicatebomb.dm
  code/game/objects/effects/spawners/mailspawner.dm
  code/game/objects/items/RSF.dm
  code/game/objects/items/food/donkpockets.dm
  code/game/objects/items/food/donuts.dm
  code/game/objects/items/food/pancakes.dm
  code/game/objects/items/food/pastries.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/fancy.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/awaymissions/mission_code/Academy.dm
  code/modules/cargo/bounties/assistant.dm
  code/modules/cargo/bounties/chef.dm
  code/modules/events/holiday/halloween.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/food/snacks_pastry.dm
  code/modules/food_and_drinks/food/snacks_sandwichtoast.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_bread.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_burger.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_egg.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pizza.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_sandwich.dm
  code/modules/holiday/halloween.dm
  code/modules/jobs/job_mail.dm
  code/modules/mining/equipment/survival_pod.dm
  code/modules/mob/living/carbon/human/species_types/pumpkin_man.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/paperwork/fax.dm
  code/modules/ruins/lavalandruin_code/puzzle.dm
  code/modules/station_goals/bluespace_tap.dm
  code/modules/vending/mining.dm
  tools/UpdatePaths/Scripts/9937_NEWFOODpastries.txt
Labels: Mapping, Tweak, Feature, Administration, Tools

#10094 Fixes saying codeword to uplink for all cases
  code/__DEFINES/dcs/signals/signals_obj/signals_item/signals_item.dm
  code/__DEFINES/say.dm
  code/datums/components/uplink.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/mob/living/say.dm
Labels: Fix, Code Improvement

#10110 Reverts donk pocket reagent changes added in #9937
  code/game/objects/items/food/donkpockets.dm
Labels: Fix

#10106 Fixes Shadow Eyes rite message
  code/modules/religion/rites.dm
Labels: Fix

#10111 Fixes softlock bug with fultons
  code/modules/mining/fulton.dm
Labels: Fix

#10108 Clockcult execute failure protection
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
Labels: Fix

#9974 Properly buffer holoparasite builder to avoid rate limits
  tgui/packages/tgui/components/BufferedTextArea.tsx
  tgui/packages/tgui/components/index.js
  tgui/packages/tgui/interfaces/HoloparasiteBuilder.tsx
  tgui/packages/tgui/interfaces/NtosNotepad.js
Labels: Fix, TGUI-Changes

#10079 Adds 2 new moth plushies
  code/game/objects/items/plushes.dm
  icons/obj/plushes.dmi
Labels: Feature, Sprites, hacktoberfest-accepted

#10103 Substantially nerfs maltodextrin
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/food/snacks_vend.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
Labels: Tweak, Balance/Rebalance, hacktoberfest-accepted

#10117 Revert "Adds 2 new moth plushies"
  code/game/objects/items/plushes.dm
  icons/obj/plushes.dmi
Labels: Sprites, Removal, Code Improvement

#8865 Refactors /turf/var/intact, cleans up some hide issues
  code/__DEFINES/turfs.dm
  code/controllers/subsystem/minor_mapping.dm
  code/datums/components/plumbing/_plumbing.dm
  code/datums/elements/undertile.dm
  code/game/machinery/navbeacon.dm
  code/game/mecha/equipment/tools/work_tools.dm
  code/game/objects/effects/anomalies.dm
  code/game/objects/effects/effect_system/effects_foam.dm
  code/game/objects/items/RCL.dm
  code/game/objects/items/devices/powersink.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/obj_defense.dm
  code/game/turfs/open/floor.dm
  code/game/turfs/open/floor/dock_floor.dm
  code/game/turfs/open/floor/plating.dm
  code/game/turfs/open/openspace.dm
  code/game/turfs/open/space/space.dm
  code/game/turfs/turf.dm
  code/modules/antagonists/blob/blob_report.dm
  code/modules/antagonists/revenant/revenant_abilities.dm
  code/modules/atmospherics/machinery/pipes/layermanifold.dm
  code/modules/holodeck/computer.dm
  code/modules/holodeck/turfs.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/power/apc/apc_attack.dm
  code/modules/power/cable.dm
  code/modules/power/power.dm
  code/modules/power/smes.dm
  code/modules/power/terminal.dm
  code/modules/procedural_mapping/mapGenerators/repair.dm
  code/modules/recycling/disposal/construction.dm
  code/modules/recycling/disposal/pipe.dm
Labels: Fix, Refactor

#9897 Improves logging for stopping dragging things and fixes a runtime.
  code/game/atoms_movable.dm
Labels: Fix

#9757 Fixes BCI overlay components
  code/game/alternate_appearance.dm
  code/modules/wiremod/components/bci/hud/bar_overlay.dm
  code/modules/wiremod/components/bci/hud/counter_overlay.dm
  code/modules/wiremod/components/bci/hud/object_overlay.dm
  code/modules/wiremod/shell/brain_computer_interface.dm
Labels: Tweak, Feature, Fix, Code Improvement
