Repository BeeStation/BeeStation-Hornet, pull requests merged in 2023-01, with the labels that each got.

#8269 Makes the 'face' selection of pAIs use a radial menu.
  code/_globalvars/lists/flavor_misc.dm
  code/modules/mob/living/silicon/pai/software.dm
Labels: DO NOT MERGE, Feature

#8222 Removes an unwanted description from chicken sandwiches
  code/modules/food_and_drinks/food/snacks_burgers.dm
Labels: Tweak, Feature, Needs Testing Evidence

#8193 Maint hoodies & Stack files standardization
  code/datums/components/crafting/tailoring.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/client/loadout/loadout_suit.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/vending/clothesmate.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, Sprites, Code Improvement, Good PR

#8206 Makes the 'research mode' of radiation collectors and tesla coins generate discovery research instead of generic research.
  code/modules/power/singularity/collector.dm
  code/modules/power/tesla/coil.dm
Labels: Tweak, Feature

#7921 Adds support for variably sized lobby screens
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/title.dm
  code/datums/view.dm
  code/game/objects/effects/landmarks.dm
  config/config.txt
Labels: Feature, Config Update

#8201 Adds the ability to see most poll types
  code/_globalvars/misc.dm
  code/modules/admin/poll_management.dm
  code/modules/admin/topic.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/dead/new_player/poll.dm
Labels: Administration

#8288 Fixes bad icon call with directional uranium glass
  code/game/objects/structures/window.dm
Labels: Fix

#8283 Fixes animated title screens
  code/controllers/subsystem/title.dm
Labels: Fix

#8289 Fixes unused variable in unit tests
  code/modules/unit_tests/shuttle_width_height_correctness.dm
Labels: Fix

#8294 Fix titlescreen runtime
  code/controllers/subsystem/title.dm
Labels: Test Merged, Fix

#8064 Greatly improve supply pod logging
  code/modules/cargo/centcom_podlauncher.dm
Labels: Feature

#8287 Tweak the error message when compiling in OD
  code/_compile_options.dm
Labels: Tweak

#7936 Nerfs basic medicines to make these only effective for minor injuries
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Balance/Rebalance, Needs Wiki Changes

#8292 Adds vertical disposal pipes to RPDs
  code/game/objects/items/RPD.dm
  icons/obj/atmospherics/pipes/disposal.dmi
Labels: Feature, Sprites

#8302 Fixes phobia gain message not showing
  code/datums/brain_damage/phobia.dm
Labels: Fix

#8110 operating computer uses alldirs
  code/game/machinery/computer/Operating.dm
  code/game/machinery/stasis.dm
  code/game/objects/structures/tables_racks.dm
Labels: Tweak, Needs Testing Evidence

#8273 Ports better Mixer Node Indicators
  code/modules/atmospherics/machinery/components/trinary_devices/filter.dm
  icons/obj/atmospherics/components/trinary_devices.dmi
  tgui/packages/tgui/interfaces/AtmosMixer.js
Labels: Tweak, Feature, Sprites, TGUI-Changes

#8311 Fixes Seraph and Mauler Looking like Marauder
  code/game/mecha/combat/marauder.dm
Labels: Fix

#8286 Removes speechmods from the obsessed trauma
  code/datums/brain_damage/creepy_trauma.dm
  code/modules/antagonists/creep/creep.dm
Labels: Tweak, Grammar and Formatting

#8290 adds range checks to railings.dm , windoor_assembly.dm , and window.dm
  code/game/objects/structures/railings.dm
  code/game/objects/structures/windoor_assembly.dm
  code/game/objects/structures/window.dm
Labels: Fix

#8265 Belt for botanists.
  code/game/objects/items/storage/belt.dm
  code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
  code/modules/hydroponics/hydroitemdefines.dm
  code/modules/research/designs/biogenerator_designs.dm
  icons/mob/clothing/belt.dmi
  icons/mob/inhands/equipment/belt_lefthand.dmi
  icons/mob/inhands/equipment/belt_righthand.dmi
  icons/obj/clothing/belt_overlays.dmi
  icons/obj/clothing/belts.dmi
Labels: Feature, Sprites, Code Improvement

#8264 Removes blocks_air
  _maps/RandomRuins/LavaRuins/lavaland_surface_pride.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_sloth.dmm
  code/__HELPERS/areas.dm
  code/controllers/subsystem/air.dm
  code/game/turfs/change_turf.dm
  code/game/turfs/closed/_closed.dm
  code/game/turfs/open/_open.dm
  code/game/turfs/turf.dm
  code/modules/admin/admin_verbs.dm
  code/modules/atmospherics/environmental/LINDA_system.dm
  code/modules/atmospherics/environmental/LINDA_turf_tile.dm
  code/modules/atmospherics/machinery/datum_pipeline.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/he_pipes.dm
  code/modules/mob/living/simple_animal/bot/atmosbot.dm
  code/modules/shuttle/on_move.dm
Labels: Mapping, THIS IS VERY IMPORTANT, Test Merged, Administration, Code Improvement

#8318 fix statues
  code/modules/mob/living/simple_animal/hostile/statue.dm
Labels: Fix

#8322 Fixes Detective's Spyglass kit
  code/game/objects/items/devices/spyglasses.dm
Labels: Fix

#8305 Places safes in all heads offices on corg
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: Mapping, Feature

#8216 Adds logging and admin messaging to crafting
  code/datums/components/crafting/crafting.dm
  code/datums/components/crafting/recipes.dm
  code/game/atoms.dm
  code/game/objects/items/teleprod.dm
  code/game/objects/items/tools/weldingtool.dm
  code/game/objects/items/weaponry.dm
Labels: Feature, Code Improvement

#8210 Carbons suffer from "appearing faint" instead of pale from bloodloss
  code/modules/mob/living/carbon/human/examine.dm
Labels: Tweak

#8330 Codex Cicatrix now fits into book bags and bookshelves
  code/game/objects/items/storage/bags.dm
  code/modules/library/lib_items.dm
Labels: Tweak

#8313 Pirates can now speak the tongue of... pirates
  code/__DEFINES/language.dm
  code/modules/antagonists/pirate/pirate.dm
Labels: Feature

#8284 Adds logging and admin messaging to buying items from an uplink
  code/game/atoms.dm
  code/modules/antagonists/traitor/equipment/contractor.dm
  code/modules/uplink/uplink_items.dm
Labels: Code Improvement

#8334 Fixes butchering geese
  code/modules/mob/living/simple_animal/hostile/goose.dm
Labels: Fix

#8080 Add TGUI inputs and alerts
  beestation.dme
  code/datums/components/cult_ritual_item.dm
  code/game/machinery/computer/launchpad_control.dm
  code/game/machinery/computer/law.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/launch_pad.dm
  code/game/objects/items/implants/implant_explosive.dm
  code/modules/admin/admin.dm
  code/modules/admin/permissionedit.dm
  code/modules/admin/secrets.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/admin/stickyban.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/_help.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/healall.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/admin/view_variables/mass_edit_variables.dm
  code/modules/admin/view_variables/modify_variables.dm
  code/modules/antagonists/brainwashing/brainwashing.dm
  code/modules/antagonists/changeling/powers/headcrab.dm
  code/modules/antagonists/clock_cult/mobs/cogscarab.dm
  code/modules/antagonists/clock_cult/structure/eminence_beacon.dm
  code/modules/antagonists/nukeop/equipment/nuclear_challenge.dm
  code/modules/antagonists/traitor/equipment/Malf_Modules.dm
  code/modules/awaymissions/corpse.dm
  code/modules/client/client_procs.dm
  code/modules/events/pirates.dm
  code/modules/hydroponics/grown/replicapod.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/brain/posibrain.dm
  code/modules/mob/living/living_sentience.dm
  code/modules/mob/living/simple_animal/friendly/drone/drones_as_items.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/elite.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/research/destructive_analyzer.dm
  code/modules/tgui/tgui_alert.dm
  code/modules/tgui/tgui_input_list.dm
  code/modules/tgui/tgui_input_number.dm
  code/modules/tgui/tgui_input_text.dm
  interface/interface.dm
  tgui/packages/tgui/components/Autofocus.tsx
  tgui/packages/tgui/components/RestrictedInput.js
  tgui/packages/tgui/components/index.js
  tgui/packages/tgui/interfaces/AlertModal.tsx
  tgui/packages/tgui/interfaces/ListInputModal.tsx
  tgui/packages/tgui/interfaces/NumberInputModal.tsx
  tgui/packages/tgui/interfaces/TextInputModal.tsx
  tgui/packages/tgui/interfaces/common/InputButtons.tsx
  tgui/packages/tgui/interfaces/common/Loader.tsx
  tgui/packages/tgui/styles/components/Button.scss
  tgui/packages/tgui/styles/interfaces/AlertModal.scss
  tgui/packages/tgui/styles/interfaces/ListInput.scss
  tgui/packages/tgui/styles/main.scss
Labels: Tweak, Feature, Fix, Administration, TGUI-Changes

#8090 no 'Follow' ghost option to simple mob emotes
  code/__DEFINES/preferences.dm
  code/datums/emotes.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_toggles.dm
Labels: Feature

#8171 Adds a radial menu for the skin selection of Detective's revolver, Bartender's Shotgun and Captain's Fountain Pen, Chaplain's Bible
  code/game/objects/items/holy_weapons.dm
  code/game/objects/items/storage/book.dm
  code/game/objects/objs.dm
  code/modules/paperwork/pen.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
Labels: Tweak, Feature, Fix, Refactor, Code Improvement

#8094 TGUI Message Monitor + PDA Admin Verb
  beestation.dme
  code/game/machinery/telecomms/computers/message.dm
  code/game/machinery/telecomms/machines/message_server.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/modular_computers/file_system/programs/ntmessenger.dm
  code/modules/tgui/tgui_input_pda_message.dm
  tgui/packages/tgui/interfaces/MessageMonitor.js
  tgui/packages/tgui/interfaces/NtosMessenger.js
  tgui/packages/tgui/interfaces/PDAInputModal.js
Labels: Tweak, Feature, Fix, Administration, Removal, Server, TGUI-Changes

#8268 Ghoul examine text is no longer visible with obscured eyes
  code/datums/status_effects/debuffs.dm
  code/datums/status_effects/status_effect.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: Fix

#8324 Tweaks plasma canister coloring
  code/modules/atmospherics/machinery/portable/canister.dm
Labels: Tweak

#8340 Dynamic 2023
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
Labels: Tweak, Balance/Rebalance, Somewhat Important

#8274 Fixes the Hilbert's Hotel bug and adds an emergency escape option.
  _maps/templates/hilbertshotel.dmm
  code/modules/ruins/spaceruin_code/hilbertshotel.dm
Labels: Mapping, Feature, Fix

#8326 Adds an Alt+Click Interaction to Plasma Refineries
  code/modules/shuttle/super_cruise/shuttle_components/plasma_refiner.dm
Labels: Feature

#8337 Fixes title screens wtih a new approach
  code/controllers/subsystem/title.dm
  config/title_screens/README.txt
Labels: Fix, Config Update

#8350 Plasma refinery alt+click Fix
  code/modules/shuttle/super_cruise/shuttle_components/plasma_refiner.dm
Labels: Fix

#8198 Alien weed fix and further fixes to the broken smoothing system
  _maps/map_files/generic/CentCom.dmm
  code/__DEFINES/icon_smoothing.dm
  code/game/area/areas/shuttles.dm
  code/game/objects/structures/aliens.dm
  code/game/objects/structures/beds_chairs/alien_nest.dm
  code/game/objects/structures/catwalk.dm
  code/game/objects/structures/lattice.dm
  code/game/turfs/closed/_closed.dm
  code/game/turfs/closed/wall/mineral_walls.dm
  code/modules/antagonists/clock_cult/clockwork_turfs.dm
  icons/turf/mining.dmi
  icons/turf/shuttle.dmi
Labels: Mapping, Tweak, Sprites, Fix

#8136 [PORT/Revival] Custom say emotes and Emphasis
  code/__DEFINES/logging.dm
  code/__DEFINES/say.dm
  code/__HELPERS/_logging.dm
  code/_globalvars/misc.dm
  code/datums/chatmessage.dm
  code/datums/emotes.dm
  code/game/atoms.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/say.dm
  code/modules/client/verbs/ooc.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
  code/modules/mob/mob.dm
  code/modules/mob/say.dm
Labels: Mapping, SQL, Feature, Sprites, Sound, Good PR

#7686 Explosives Rebalancing
  beestation.dme
  code/controllers/subsystem/explosion.dm
  code/datums/wires/syndicatebomb.dm
  code/game/gamemodes/sandbox/h_sandbox.dm
  code/game/machinery/syndicatebomb.dm
  code/game/objects/effects/effect_system/effects_other.dm
  code/game/objects/items/devices/transfer_valve.dm
  code/game/objects/items/grenades/_grenade.dm
  code/game/objects/items/grenades/chem_grenade.dm
  code/game/objects/items/grenades/syndieminibomb.dm
  code/game/objects/items/tanks/tanks.dm
  code/modules/assembly/bomb.dm
  code/modules/reagents/chem_splash.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  code/modules/research/experimentor.dm
  code/modules/ruins/lavalandruin_code/syndicate_base.dm
  code/modules/uplink/uplink_items.dm
Labels: Mapping, Needs Testmerge, Balance/Rebalance, Removal, Bounty

#7500 Space Dragon Rework and Dynamic Ruleset
  beestation.dme
  code/__DEFINES/dcs/signals/signals_mob/signals_living.dm
  code/__DEFINES/movespeed_modification.dm
  code/__DEFINES/role_preferences.dm
  code/controllers/subsystem/processing/gravity_aura.dm
  code/datums/action.dm
  code/datums/components/gravity_aura.dm
  code/datums/martial/tribal_claw.dm
  code/datums/saymode.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/modules/antagonists/space_dragon/carp_rift.dm
  code/modules/antagonists/space_dragon/space_dragon.dm
  code/modules/events/space_dragon.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
  code/modules/mob/living/simple_animal/hostile/space_dragon.dm
  icons/mob/actions/actions_space_dragon.dmi
  icons/mob/spacedragon.dmi
  icons/obj/carp_rift.dmi
  sound/creatures/space_dragon_roar.ogg
Labels: Tweak, Feature, Sprites, Refactor, Sound

#8134 Moth Cocoon PR 2, I learn how to use ghub bogaloo
  code/__DEFINES/status_effects.dm
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/surgery/organs/wings.dm
  icons/effects/effects.dmi
Labels: Tweak, Feature, Sprites, Fix, Refactor

#8327 Flandstation fix batch (FlandStation Sp5.2)
  _maps/map_files/FlandStation/FlandStation.dmm
  icons/turf/decals.dmi
Labels: Mapping, Feature, Sprites, Fix

#8354 Adds missing icons for held snakes/PAI snakes
  icons/mob/pai_item_lh.dmi
  icons/mob/pai_item_rh.dmi
  icons/mob/pets_held_lh.dmi
  icons/mob/pets_held_rh.dmi
Labels: Feature, Sprites, Fix

#8252 Orbit panel job icons
  code/modules/mob/dead/observer/orbit.dm
  tgui/packages/tgui/interfaces/Orbit.js
Labels: Feature, TGUI-Changes

#8254 Cyborg welding tool now gets temporarity disabled by Nightmare's lighteater instead of being deleted
  code/game/objects/items/tools/weldingtool.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/surgery/organs/augments_arms.dm
Labels: Feature, Removal, Code Improvement

#8325 Fixed deconstructing railings not dropping iron rods
  code/game/objects/structures/railings.dm
Labels: Fix

#8364 Make railings take time to deconstruct
  code/game/objects/structures/railings.dm
Labels: Tweak

#8240 Fixes a few issues with the Tablet PDAs
  code/modules/mob/living/silicon/silicon.dm
  code/modules/modular_computers/computers/item/tablet.dm
  code/modules/modular_computers/file_system/programs/notepad.dm
  code/modules/modular_computers/hardware/hard_drive.dm
Labels: Removal, Code Improvement

#8360 Removes mentions of °K
  code/game/objects/items/grenades/chem_grenade.dm
  code/modules/atmospherics/machinery/airalarm.dm
Labels: Grammar and Formatting

#8345 Adds Smile IPC Screen
  code/modules/mob/dead/new_player/sprite_accessories.dm
  icons/mob/ipc_accessories.dmi
Labels: Feature, Sprites

#8331 Some custom shuttle related bugfixes
  code/modules/shuttle/arrivals.dm
  code/modules/shuttle/shuttle.dm
  code/modules/shuttle/shuttle_creation/shuttle_creator.dm
  code/modules/shuttle/shuttle_creation/shuttle_creator_actions.dm
  code/modules/shuttle/super_cruise/shuttle_components/shuttle_docking.dm
  code/modules/shuttle/supply.dm
Labels: Fix

#8363 Fixes weird layering with light liz snouts
  icons/mob/mutant_bodyparts.dmi
Labels: Sprites, Fix

#8366 [PORT] Moves Changeling code out of click code
  code/__DEFINES/dcs/signals/signals_mob/signals_mob.dm
  code/_onclick/click.dm
  code/_onclick/cyborg.dm
  code/_onclick/overmind.dm
  code/modules/antagonists/changeling/changeling.dm
Labels: Feature, Code Improvement

#8361 Fixes blindfolds not properly counting as blind
  code/datums/brain_damage/phobia.dm
  code/datums/brain_damage/severe.dm
  code/datums/chatmessage.dm
  code/datums/diseases/advance/symptoms/organs.dm
  code/datums/diseases/advance/symptoms/vision.dm
  code/datums/dna.dm
  code/game/machinery/computer/camera_advanced.dm
  code/game/objects/effects/anomalies.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/camera_bug.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/devices/laserpointer.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/assembly/flash.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/library/lib_items.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/hostile/statue.dm
  code/modules/mob/living/status_procs.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_helpers.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/shuttle/shuttle_creation/shuttle_creator_console.dm
Labels: Fix

#8357 Ports pet and bot shoving
  code/modules/mob/living/simple_animal/animal_defense.dm
Labels: Tweak

#8272 Adds setter for density, adds more replacement update_appearance
  code/datums/ai/dog/dog_behaviors.dm
  code/game/atoms.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/deployable.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/machinery/washing_machine.dm
  code/game/mecha/mecha_construction_paths.dm
  code/game/objects/items/devices/powersink.dm
  code/game/objects/items/shooting_range.dm
  code/game/objects/structures.dm
  code/game/objects/structures/beds_chairs/bed.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/bodybag.dm
  code/game/objects/structures/displaycase.dm
  code/game/objects/structures/false_walls.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/fireaxe.dm
  code/game/objects/structures/fireplace.dm
  code/game/objects/structures/guncase.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/transit_tubes/transit_tube_pod.dm
  code/game/objects/structures/watercloset.dm
  code/game/objects/structures/windoor_assembly.dm
  code/game/objects/structures/window.dm
  code/modules/antagonists/blob/structures/_blob.dm
  code/modules/antagonists/cult/cult_structures.dm
  code/modules/assembly/infrared.dm
  code/modules/cargo/supplypod.dm
  code/modules/events/spacevine.dm
  code/modules/mining/fulton.dm
  code/modules/mob/living/silicon/pai/pai_shell.dm
  code/modules/mob/living/simple_animal/hostile/jungle/leaper.dm
  code/modules/mob/living/simple_animal/hostile/jungle/mook.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  code/modules/power/gravitygenerator.dm
  code/modules/ruins/objects_and_mobs/necropolis_gate.dm
  code/modules/spells/spell.dm
  code/modules/spells/spell_types/projectile.dm
  code/modules/vehicles/motorized_wheelchair.dm
  code/modules/vehicles/scooter.dm
Labels: Feature, Code Improvement

#8133 adds html tooltip, adds a tooltip to character pref about naming policy
  beestation.dme
  code/__DEFINES/html_assistant.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/text.dm
  code/_globalvars/misc.dm
  code/game/world.dm
  code/modules/client/preferences.dm
  config/tooltips.txt
Labels: Feature, Config Update, Code Improvement

#8349 Save Our Ears
  code/game/sound.dm
  code/modules/shuttle/shuttle.dm
Labels: Tweak

#8221 Fixes character setup not properly displaying preferences for moths and lizards
  code/modules/client/preferences2/character_save.dm
  code/modules/surgery/organs/wings.dm
Labels: Fix, Code Improvement

#8384 Fixes cultists being unable to use their spells
  code/modules/antagonists/space_dragon/space_dragon.dm
Labels: Fix

#8389 Fixes bomb logs
  code/game/objects/items/tanks/tanks.dm
Labels: Fix

#8277 The antag datum expansion
  beestation.dme
  code/__DEFINES/atom_hud.dm
  code/__DEFINES/role_preferences.dm
  code/datums/brain_damage/hypnosis.dm
  code/datums/hud.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/antagonists/hypnotization/hypnotized.dm
  code/modules/antagonists/morph/morph.dm
  code/modules/antagonists/morph/morph_antag.dm
  code/modules/antagonists/nightmare/nightmare.dm
  code/modules/antagonists/pirate/pirate.dm
  code/modules/antagonists/swarmer/swarmer.dm
  code/modules/antagonists/xeno/xeno.dm
  icons/mob/hud.dmi
Labels: Feature, Sprites, Refactor, Administration

#8385 Tweaks toy/figure weight class
  code/game/objects/items/toys.dm
Labels: Tweak, Feature, Fix

#8374 Fixed goliath hides and removed false coal
  _maps/templates/shelter_4.dmm
  beestation.dme
  code/game/objects/items/trash.dm
  code/modules/mining/equipment/goliath_hide.dm
Labels: Mapping, Fix, Removal

#8368 Give emote
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/inventory.dm
Labels: Feature

#8392 Fixes that "Offer mob to ghost vv" does not work
  code/modules/mob/mob_helpers.dm
Labels: Fix

#8381 Fix blob being able to place core on nonspace but still disallowed tiles
  code/modules/antagonists/blob/overmind.dm
  code/modules/antagonists/blob/powers.dm
Labels: Fix

#7870 Adds sentient spiders to midround events
  beestation.dme
  code/__DEFINES/atom_hud.dm
  code/__DEFINES/role_preferences.dm
  code/datums/hud.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/objects/effects/spiders.dm
  code/modules/antagonists/_common/tips.dm
  code/modules/antagonists/abductor/equipment/gland.dm
  code/modules/antagonists/spider/spider.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/events/spider_infestation.dm
  code/modules/language/language_holder.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/research/xenobiology/xenobiology.dm
  code/modules/spells/spell_types/shapeshift.dm
  html/antagtips/spider.html
  html/img/hunter.png
  html/img/midwife.png
  html/img/nurse.png
  html/img/spider.png
  html/img/tarantula.png
  html/img/viper.png
  icons/mob/hud.dmi
Labels: Needs Testmerge, Tweak, Feature, Sprites, Balance/Rebalance

#8393 Fixes techfloor_"grey"
  icons/turf/floors.dmi
Labels: Sprites, Fix

#8391 [PORT] Moves Dejavu component out of crossbreeding
  beestation.dme
  code/datums/components/dejavu.dm
  code/modules/research/xenobiology/crossbreeding/_misc.dm
Labels: Code Improvement

#8335 Ports the pop out cake from /vg/
  beestation.dme
  code/game/objects/structures/popout_cake.dm
  code/modules/food_and_drinks/food/snacks_cake.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_cake.dm
  code/modules/uplink/uplink_items.dm
  icons/mob/actions/actions_items.dmi
  icons/obj/structures.dmi
Labels: Feature, Sprites

#8278 Adds a line of text showing the alert level to the side bar.
  code/modules/mob/mob_stat.dm
Labels: Feature

#8358 The Hissening, ports X speech variations to lizards
  code/modules/surgery/organs/tongue.dm
Labels: Feature

#8359 The Snoot-ening, separates HIDEMASK and HIDESNOUT
  code/__DEFINES/inventory.dm
  code/game/objects/items/holy_weapons.dm
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/antagonists/eldritch_cult/eldritch_items.dm
  code/modules/clothing/chameleon.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/masks/boxing.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/hailer.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/spacesuits/_spacesuits.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/clothing/suits/bio.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/suits/utility.dm
  code/modules/holiday/easter.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#8398 Adds weights to phobias
  code/controllers/subsystem/traumas.dm
  code/datums/brain_damage/phobia.dm
Labels: Tweak

#8304 Adds more medibot skins
  code/__DEFINES/bot_defines.dm
  code/game/objects/items/storage/firstaid.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  icons/mob/aibots.dmi
Labels: Tweak, Feature, Sprites

#8329 Makes the bears spawned by xenoarch artifacts weaker
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/xenoarchaeology/traits/xenoartifact_malfunctions.dm
Labels: Tweak, Feature, Balance/Rebalance

#8307 Geneticist is now med
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  code/__DEFINES/economy.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/geneticist.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/jobs/job_types/scientist.dm
Labels: Mapping, Tweak, Fix, Removal, Code Improvement

#8406 Fix BUCKET_POS for ticklags with non-integer reciprocals
  code/controllers/subsystem/timer.dm
Labels: Code Improvement

#8367 Fixes a few Custom Say Issues
  code/modules/client/verbs/ooc.dm
  code/modules/mob/living/say.dm
  code/modules/mob/say.dm
Labels: Fix
