Repository BeeStation/BeeStation-Hornet, pull requests merged in 2023-11, with the labels that each got.

#10109 Death notice message
  code/controllers/configuration/entries/policies.dm
  code/modules/mob/living/carbon/human/death.dm
  config/policies.txt
  interface/stylesheet.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: Feature, Config Update, TGUI-Changes, hacktoberfest-accepted

#10099 Fixes a runtime with bots in closets
  _maps/shuttles/emergency/emergency_corg.dmm
  code/modules/mob/living/simple_animal/bot/bot.dm
Labels: Mapping, Tweak, Fix, hacktoberfest-accepted

#10114 Glitter chemical recipes
  beestation.dme
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
Labels: Tweak, Feature, Needs Wiki Changes, hacktoberfest-accepted

#10128 blacklist storage capsule from deep fryer
  code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
Labels: Fix

#10116 Add relative coordinates component to Wiremod
  beestation.dme
  code/__HELPERS/atoms.dm
  code/modules/research/designs/wiremod_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/wiremod/components/atom/relative_coords.dm
Labels: Feature, Code Improvement, hacktoberfest-accepted

#9950 Locks the 357 revolver to 25 pop and above
  code/modules/uplink/uplink_items.dm
Labels: Balance/Rebalance, hacktoberfest-accepted

#10054 Breathes new life into Venus Human Traps
  code/game/objects/effects/countdown.dm
  code/modules/events/spacevine.dm
  code/modules/language/language_holder.dm
  code/modules/mob/living/simple_animal/hostile/venus_human_trap.dm
  code/modules/unit_tests/create_and_destroy.dm
  icons/effects/beam.dmi
  icons/effects/spacevines.dmi
  icons/mob/animal.dmi
  sound/creatures/venus_trap_death.ogg
  sound/creatures/venus_trap_hit.ogg
  sound/creatures/venus_trap_hurt.ogg
Labels: Tweak, Feature, Sprites, Fix, Balance/Rebalance, Sound, Code Improvement, Server, hacktoberfest-accepted

#10134 Removes extra Initialize() proc from safes
  code/game/objects/structures/safe.dm
Labels: Code Improvement

#10129 Fixes radio channels defaulting to common when no encryption key
  code/game/objects/items/devices/radio/radio.dm
Labels: Feature, Fix

#10145 Cogscarab Dynamic Fix + suppressor warning fix
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/modules/projectiles/guns/ballistic.dm
Labels: Fix, Code Improvement

#10138 Makes the heretic blademaking ritual shatter blades over the limit when new ones are made
  code/modules/antagonists/heretic/heretic_knowledge.dm
  code/modules/antagonists/heretic/knowledge/ash_lore.dm
  code/modules/antagonists/heretic/knowledge/flesh_lore.dm
  code/modules/antagonists/heretic/knowledge/rust_lore.dm
  code/modules/antagonists/heretic/knowledge/void_lore.dm
Labels: Tweak

#9596 High-speed gun inaccuracy modifiers
  code/game/atoms_movable.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/mob_defines.dm
  code/modules/multiz/movement/turf/turf_zmove.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/launchers.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
Labels: Balance/Rebalance, Code Improvement

#9767 Fixes Lazarus injector has a small bug + Lazarus QoL
  code/modules/mining/equipment/lazarus_injector.dm
Labels: Feature, Fix

#9807 Megafauna no longer gib bodies
  code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
Labels: Balance/Rebalance, Balance Approved

#9940 Ghost QoL: invisible things are visible to ghosts (uses SSvis_overlay)
  code/controllers/subsystem/vis_overlays.dm
  code/game/objects/effects/forcefields.dm
  code/game/objects/effects/overlays.dm
  code/game/objects/items/implants/implant_stealth.dm
  code/game/objects/objs.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/antagonists/heretic/influences.dm
Labels: Feature, hacktoberfest-accepted

#9503 Turf integrity and turf damage reworking
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Mining/Lavaland.dmm
  beestation.dme
  code/__DEFINES/mobs.dm
  code/_onclick/item_attack.dm
  code/datums/mapgen/JungleGenerator.dm
  code/game/turfs/closed/_closed.dm
  code/game/turfs/closed/minerals.dm
  code/game/turfs/closed/wall/mineral_walls.dm
  code/game/turfs/closed/wall/reinf_walls.dm
  code/game/turfs/closed/walls.dm
  code/game/turfs/open/_open.dm
  code/game/turfs/open/chasm.dm
  code/game/turfs/open/floor.dm
  code/game/turfs/open/floor/dock_floor.dm
  code/game/turfs/open/floor/fancy_floor.dm
  code/game/turfs/open/floor/light_floor.dm
  code/game/turfs/open/floor/mineral_floor.dm
  code/game/turfs/open/floor/plasteel_floor.dm
  code/game/turfs/open/floor/plating.dm
  code/game/turfs/open/floor/plating/asteroid.dm
  code/game/turfs/open/floor/plating/misc_plating.dm
  code/game/turfs/open/floor/reinf_floor.dm
  code/game/turfs/open/lava.dm
  code/game/turfs/open/openspace.dm
  code/game/turfs/open/space/space.dm
  code/game/turfs/turf.dm
  code/game/turfs/turf_integrity.dm
  code/modules/antagonists/clock_cult/clockwork_turfs.dm
  code/modules/awaymissions/mission_code/snowdin.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
  icons/turf/damage.dmi
  icons/turf/mining.dmi
Labels: Mapping, Sprites, Balance/Rebalance, Refactor

#10143 Adds a short do_after to unwrapping wrapped stuff
  code/modules/recycling/sortingmachinery.dm
Labels: Tweak

#10124 Gives the det a chem scanner in the PDA
  code/modules/modular_computers/hardware/job_disk.dm
Labels: Tweak

#10141 Morphs can no longer perform stomach functions inside of pipes
  code/modules/antagonists/morph/morph_stomach.dm
Labels: Fix

#9789 Tweaks for icons of items within vendor UIs.
  code/_onclick/drag_drop.dm
  code/game/objects/items.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm
  code/modules/hydroponics/hydroitemdefines.dm
  code/modules/reagents/reagent_containers/bottle.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/vending/_vending.dm
  icons/obj/chemical.dmi
  icons/obj/drinks.dmi
Labels: Tweak, Feature, Sprites, Code Improvement

#9858 Dynamic lategame & Midround simulations
  code/__DEFINES/dynamic.dm
  code/__HELPERS/roundend.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_hijacking.dm
  code/game/gamemodes/dynamic/dynamic_logging.dm
  code/game/gamemodes/dynamic/dynamic_midround_rolling.dm
  code/game/gamemodes/dynamic/dynamic_rulesets.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/dynamic/dynamic_simulations.dm
  code/game/gamemodes/dynamic/dynamic_unfavorable_situation.dm
  code/game/gamemodes/dynamic/ruleset_picking.dm
Labels: Tweak

#9861 Ports a couple of minor logging/admin related PRs from TG
  code/__HELPERS/areas.dm
  code/game/machinery/computer/law.dm
  code/modules/admin/check_antagonists.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/elite.dm
  code/modules/station_goals/bsa.dm
Labels: Tweak, Administration, Removal

#9976 Overhauled how linebreaks works for moodlets.
  beestation.dme
  code/datums/components/mood.dm
  code/datums/mood_events/drink_events.dm
  code/datums/mood_events/drug_events.dm
  code/datums/mood_events/generic_negative_events.dm
  code/datums/mood_events/generic_positive_events.dm
  code/datums/mood_events/needs_events.dm
  code/modules/antagonists/heretic/knowledge/sacrifice_knowledge/sacrifice_moodlets.dm
  code/modules/pool/pool.dm
  code/modules/pool/pool_moodlets.dm
Labels: Feature, Fix, Removal, Code Improvement, hacktoberfest-accepted

#9669 Removes necrotic metabolism's ability to have diseases act inside dead bodies.
  code/datums/diseases/_disease.dm
  code/datums/diseases/advance/symptoms/heal.dm
  code/datums/diseases/advance/symptoms/species.dm
Labels: Balance/Rebalance

#10142 Fixes scanner gate and server shell
  code/datums/components/shell.dm
  code/modules/wiremod/shell/scanner_gate.dm
  code/modules/wiremod/shell/server.dm
Labels: Tweak, Fix, Server

#10131 Fixes Blackpowder & Teslium so they pass their scaling args
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
Labels: Tweak, Fix

#10161 IPC brains appearing as IPC brains inside MMI
  code/modules/mob/living/brain/MMI.dm
  icons/obj/assemblies.dmi
Labels: Tweak, Sprites

#10169 Fixes minimum spread and a compile warning
  code/modules/projectiles/gun.dm
Labels: Fix

#10001 Toy Rubber Duck Mine
  code/datums/components/crafting/recipes.dm
  code/game/objects/effects/mines.dm
Labels: Feature, hacktoberfest-accepted

#10121 Fixes a couple of alien embryo runtimes
  code/modules/mob/living/carbon/alien/special/alien_embryo.dm
Labels: Fix, Removal

#10176 Fixes magnetic spearguns
  code/game/objects/items/pneumaticCannon.dm
Labels: Fix

#10150 Fixes GetComponents() returning a list with a null entry when there's no component of a given type
  code/datums/components/_component.dm
Labels: Server

#10179 Fixes megafauna attacking dead people
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
Labels: Fix

#10157 TGUI AI Robot Control
  beestation.dme
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/robot_control.dm
  tgui/packages/tgui/interfaces/RemoteRobotControl.js
Labels: Feature, TGUI-Changes

#10195 Fixes the write component
  code/modules/wiremod/components/list/write.dm
Labels: Fix

#10172 New Anomaly: Sanity Disruptor (known as "insanity pulse" of old explorer artefacts) + some anomaly code clean up
  beestation.dme
  code/__HELPERS/turfs.dm
  code/game/objects/effects/anomalies.dm
  code/game/objects/effects/anomalies/_anomalies.dm
  code/game/objects/effects/anomalies/anomaly_bluespace.dm
  code/game/objects/effects/anomalies/anomaly_delimber.dm
  code/game/objects/effects/anomalies/anomaly_flux.dm
  code/game/objects/effects/anomalies/anomaly_gravity.dm
  code/game/objects/effects/anomalies/anomaly_hallucination.dm
  code/game/objects/effects/anomalies/anomaly_insanitypulse.dm
  code/game/objects/effects/anomalies/anomaly_pyro.dm
  code/game/objects/effects/anomalies/anomaly_vortex.dm
  code/game/turfs/turf.dm
  code/modules/events/anomaly_insanitypulse.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/loot/alien_artifact.dm
Labels: Feature, Fix, Code Improvement

#9575 Sound looping cleanup, adds missing audio falloff/reverb where it is very much needed
  code/__DEFINES/instruments.dm
  code/_onclick/item_attack.dm
  code/datums/components/area_sound_manager.dm
  code/datums/components/footstep.dm
  code/datums/components/squeak.dm
  code/datums/looping_sounds/_looping_sound.dm
  code/datums/looping_sounds/item_sounds.dm
  code/datums/looping_sounds/machinery_sounds.dm
  code/game/objects/items.dm
  code/game/objects/items/clown_items.dm
  code/game/objects/items/melee/energy.dm
  code/game/objects/items/powerfist.dm
  code/modules/clothing/shoes/bananashoes.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/under/jobs/civilian/clown_mime.dm
  code/modules/instruments/songs/play_synthesized.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/power/supermatter/supermatter.dm
Labels: Tweak, Feature, Code Improvement

#10163 Debug omnitool uses TGUI as tool selection (debug QoL)
  code/game/objects/items/debug_items.dm
  code/modules/asset_cache/asset_list_items.dm
  tgui/packages/tgui/interfaces/ToolSelection.tsx
Labels: Code Improvement, TGUI-Changes

#10201 Revert "Fixes GetComponents() returning a list with a null entry when there's no component of a given type"
  code/datums/components/_component.dm
Labels: Code Improvement

#10038 The antimatter engine is no more
  beestation.dme
  code/modules/cargo/exports/large_objects.dm
  code/modules/cargo/packs.dm
  code/modules/power/antimatter/containment_jar.dm
  code/modules/power/antimatter/control.dm
  code/modules/power/antimatter/shielding.dm
  icons/obj/machines/antimatter.dmi
Labels: Sprites, Removal, Needs Wiki Changes, hacktoberfest-accepted

#10170 KiloSatation service maintenance access fix + Addition of windows in the protolathe room
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Mapping, Tweak

#10186 Fixes VHT vine beams remaining indefinitely
  code/modules/mob/living/simple_animal/hostile/venus_human_trap.dm
Labels: Fix

#10204 Newfood Atomization: Oatmeal isn't a Salad or a Vegetable
  _maps/RandomRuins/SpaceRuins/Fast_Food.dmm
  _maps/RandomZLevels/spacebattle.dmm
  _maps/shuttles/emergency/emergency_luxury.dmm
  beestation.dme
  code/__HELPERS/randoms.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items/food/salad.dm
  code/game/objects/items/food/soup.dm
  code/modules/cargo/bounties/chef.dm
  code/modules/food_and_drinks/food/snacks_salad.dm
  code/modules/food_and_drinks/food/snacks_soup.dm
  code/modules/food_and_drinks/recipes/food_mixtures.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_egg.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_salad.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_soup.dm
  code/modules/holiday/easter.dm
  code/modules/station_goals/bluespace_tap.dm
  code/modules/vending/mining.dm
  icons/obj/food/soupsalad.dmi
Labels: Mapping, Tweak, Feature, Sprites, Balance/Rebalance

#10197 Refactor holoparasite dexterity ability into a weapon
  beestation.dme
  code/_onclick/hud/holoparasite.dm
  code/modules/holoparasite/_holoparasite.dm
  code/modules/holoparasite/abilities/major/dextrous.dm
  code/modules/holoparasite/abilities/major/healing.dm
  code/modules/holoparasite/abilities/weapon/dextrous.dm
  code/modules/holoparasite/holoparasite_dexterity.dm
Labels: Balance/Rebalance

#10208 Subsystems now track their average & last tick allocations
  code/controllers/subsystem.dm
Labels: Server

#10209 Converts Ghost role candidate polls to TGUI
  code/__HELPERS/game.dm
  code/datums/brain_damage/imaginary_friend.dm
  code/datums/brain_damage/split_personality.dm
  code/datums/diseases/transformation.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/machinery/cloning.dm
  code/game/objects/items/holy_weapons.dm
  code/modules/admin/battle_royale.dm
  code/modules/admin/fun_balloon.dm
  code/modules/admin/secrets.dm
  code/modules/admin/verbs/one_click_antag.dm
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/antagonists/_common/antag_spawner.dm
  code/modules/antagonists/blob/powers.dm
  code/modules/antagonists/changeling/powers/teratoma.dm
  code/modules/antagonists/clock_cult/scriptures/sigil_of_vitality.dm
  code/modules/antagonists/clock_cult/scriptures/summon_marauder.dm
  code/modules/antagonists/clock_cult/structure/eminence_beacon.dm
  code/modules/antagonists/cult/cult_comms.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/antagonists/heretic/heretic_knowledge.dm
  code/modules/antagonists/heretic/knowledge/flesh_lore.dm
  code/modules/antagonists/revenant/revenant.dm
  code/modules/antagonists/traitor/equipment/contractor.dm
  code/modules/antagonists/wizard/equipment/soulstone.dm
  code/modules/awaymissions/mission_code/Academy.dm
  code/modules/clothing/head/mind_monkey_helmet.dm
  code/modules/events/fugitive_spawning.dm
  code/modules/events/ghost_role.dm
  code/modules/events/holiday/xmas.dm
  code/modules/events/pirates.dm
  code/modules/events/wizard/imposter.dm
  code/modules/holoparasite/holoparasite_builder.dm
  code/modules/holoparasite/holoparasite_reset.dm
  code/modules/mob/living/carbon/alien/special/alien_embryo.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/elite.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/transform_procs.dm
  code/modules/projectiles/projectile/magic.dm
  code/modules/religion/rites.dm
  code/modules/research/xenobiology/crossbreeding/warping.dm
  code/modules/research/xenobiology/xenobiology.dm
  code/modules/xenoarchaeology/traits/xenoartifact_minors.dm
Labels: Feature, Fix, Administration

#10212 absolute value component for wiremod
  beestation.dme
  code/modules/research/designs/wiremod_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/wiremod/components/math/absolute.dm
Labels: Feature

#9905 Sane chat sorting - radio only edition
  code/game/gamemodes/clock_cult/clockcult.dm
  code/game/say.dm
  code/modules/antagonists/cult/cult_comms.dm
  code/modules/holoparasite/holoparasite_chat.dm
  code/modules/mob/living/carbon/alien/say.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/say.dm
  code/modules/mob/living/silicon/say.dm
  code/modules/mob/living/simple_animal/friendly/drone/say.dm
  code/modules/mob/living/simple_animal/hostile/space_dragon.dm
  code/modules/mob/say_readme.md
  tgui/packages/tgui-panel/chat/constants.js
Labels: Feature, Fix, Code Improvement, TGUI-Changes

#10115 Fix simplemobs being unable to use intent hotkeys
  code/__DEFINES/keybinding.dm
  code/datums/keybinding/carbon.dm
  code/datums/keybinding/living.dm
Labels: Fix, hacktoberfest-accepted

#10090 Space dragons are no longer instantly killed by devestating explosions
  code/modules/mob/living/simple_animal/hostile/space_dragon.dm
Labels: Balance/Rebalance, i ded, hacktoberfest-accepted

#10120 Fixes more foodstuff caused by 9937 + 10103
  code/game/objects/items/food/donkpockets.dm
  code/game/objects/items/food/donuts.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/food/snacks_vend.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
Labels: Tweak, Fix, Code Improvement

#9677 Fixes incorrect color brightness check
  code/__HELPERS/colors.dm
  code/__HELPERS/type2type.dm
  code/game/objects/items/crayons.dm
  code/modules/client/preferences/entries/character/species_features/mutants.dm
  code/modules/holoparasite/holoparasite_builder.dm
  code/modules/modular_computers/computers/item/computer_ui.dm
Labels: Fix, Code Improvement

#9957 Change material values of Plastitanium tiles
  code/game/objects/items/stacks/tiles/tile_mineral.dm
Labels: Fix, Needs Testing Evidence

#10193 Newfood Atomization: Pies
  _maps/RandomRuins/SpaceRuins/Fast_Food.dmm
  _maps/RuinGeneration/13x13_cafe.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/shuttles/emergency/emergency_luxury.dmm
  beestation.dme
  code/__HELPERS/randoms.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items/food/dough.dm
  code/game/objects/items/food/pie.dm
  code/game/objects/items/pneumaticCannon.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  code/game/objects/structures/crates_lockers/crates/wooden.dm
  code/modules/cargo/bounties/chef.dm
  code/modules/clothing/suits/chaplainsuits.dm
  code/modules/food_and_drinks/food/snacks_pie.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pie.dm
  code/modules/jobs/job_mail.dm
  code/modules/mob/living/carbon/human/species_types/pumpkin_man.dm
  code/modules/spells/spell_types/godhand.dm
  code/modules/spells/spell_types/taeclowndo.dm
  code/modules/station_goals/bluespace_tap.dm
  tools/UpdatePaths/Scripts/9909_NEWFOODdoughmexican.txt
Labels: Mapping, Tweak, Feature, Balance/Rebalance, Tools

#10237 3 character fix for a really bad bug
  code/datums/components/storage/storage.dm
Labels: Fix

#10218 Fixed deadminning in round not giving old mentors mentor status
  code/modules/admin/holder2.dm
Labels: Fix, Administration

#10239 Strangles some severe BSRPED grief exploits in the crib
  code/__DEFINES/dcs/signals/signals_datum/signals_datum.dm
  code/game/machinery/_machinery.dm
  code/modules/power/cell.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/research/stock_parts.dm
Labels: Fix, Balance/Rebalance
