Repository BeeStation/BeeStation-Hornet, pull requests merged in 2023-03, with the labels that each got.

#8552 PDA Theme Preference
  code/__DEFINES/devices.dm
  code/__DEFINES/misc.dm
  code/__DEFINES/preferences.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences2/preferences2.dm
  code/modules/modular_computers/computers/item/computer.dm
  code/modules/modular_computers/computers/item/role_tablet_presets.dm
  code/modules/modular_computers/computers/item/tablet.dm
  code/modules/modular_computers/file_system/programs/configurator.dm
Labels: Feature, Removal

#8589 Fix climbing over railings
  code/game/objects/structures.dm
Labels: Fix

#8546 [PORT] Spans out and Alphabetizes the Lists in _globalvars/lists
  code/_globalvars/lists/ambience.dm
  code/_globalvars/lists/flavor_misc.dm
  code/_globalvars/lists/maintenance_loot.dm
  code/_globalvars/lists/mapping.dm
  code/_globalvars/lists/mobs.dm
  code/_globalvars/lists/names.dm
  code/_globalvars/lists/objects.dm
  code/_globalvars/lists/poll_ignore.dm
Labels: Code Improvement

#8467 Chaplain QOL
  code/datums/components/religious_tool.dm
  code/modules/religion/religion_sects.dm
  code/modules/religion/religion_structures.dm
  code/modules/religion/rites.dm
Labels: Tweak, Feature

#8530 Improves reliability of wormhole jaunter
  code/modules/mining/equipment/wormhole_jaunter.dm
Labels: Tweak

#8540 Readds burst fire for the Saber SMG and its toy counterpart.
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/toy.dm
Labels: Feature

#8296 Remaps all turbines for Atmos Tech QoL and to reduce radleak incidents
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Mapping, Tweak, Feature, Balance/Rebalance, Administration

#8518 Reworks PASSGLASS
  code/__DEFINES/flags.dm
  code/_globalvars/bitfields.dm
  code/game/atoms.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/machinery/shieldgen.dm
  code/game/objects/effects/effect_system/effects_foam.dm
  code/game/objects/items/devices/forcefieldprojector.dm
  code/game/objects/items/shields.dm
  code/game/objects/structures/holosign.dm
  code/game/objects/structures/plasticflaps.dm
  code/game/objects/structures/transit_tubes/transit_tube.dm
  code/game/objects/structures/windoor_assembly.dm
  code/game/objects/structures/window.dm
  code/modules/assembly/infrared.dm
  code/modules/mob/living/simple_animal/hostile/floor_cluwne.dm
  code/modules/projectiles/guns/misc/medbeam.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/energy/nuclear_particle.dm
  code/modules/projectiles/projectile/special/hallucination.dm
  code/modules/projectiles/projectile/special/plasma.dm
  code/modules/projectiles/projectile/special/wormhole.dm
Labels: Tweak

#8486 Minor fix to deadchat discord ooc
  code/modules/client/verbs/ooc.dm
Labels: Fix

#8380 Chaplain Nature based Sect
  code/game/objects/effects/temporary_visuals/cult.dm
  code/modules/hydroponics/seeds.dm
  code/modules/religion/religion_sects.dm
  code/modules/religion/religion_structures.dm
  code/modules/religion/rites.dm
  icons/effects/religion_effects.dmi
  icons/obj/religion.dmi
Labels: Feature, Sprites

#8339 moves rcd content to its proper layer
  code/__DEFINES/layers.dm
  code/_onclick/hud/radial.dm
Labels: Fix

#8567 flandstation medical fixes
  _maps/map_files/FlandStation/FlandStation.dmm
Labels: Mapping, Fix

#8576 Various spider fixes
  code/__DEFINES/mobs.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/modules/antagonists/spider/spider.dm
  code/modules/events/spider_infestation.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
Labels: Tweak, Fix

#8582 [MDB IGNORE] fix delta sec escape pod emergency launch
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Mapping, Fix

#8588 Space Dragon now costs more threat
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
Labels: Balance/Rebalance

#8578 Adds loggin and admin messaging to a certain science subdepartment
  code/modules/mob/living/simple_animal/slime/slime.dm
  code/modules/research/xenobiology/crossbreeding/__corecross.dm
  code/modules/research/xenobiology/crossbreeding/_status_effects.dm
  code/modules/research/xenobiology/crossbreeding/burning.dm
  code/modules/research/xenobiology/crossbreeding/chilling.dm
  code/modules/research/xenobiology/crossbreeding/crystalized.dm
  code/modules/research/xenobiology/crossbreeding/industrial.dm
  code/modules/research/xenobiology/crossbreeding/stabilized.dm
  code/modules/research/xenobiology/crossbreeding/warping.dm
  code/modules/research/xenobiology/xenobiology.dm
Labels: Administration

#8597 Fixes map merge conflict error with corg
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: Mapping, Fix

#8598 Fix Policies config - Polymorph and Cloning text
  code/__DEFINES/admin.dm
  code/controllers/configuration/entries/policies.dm
  code/modules/projectiles/projectile/magic.dm
  config/config.txt
  config/policies.txt
Labels: Tweak, Config Update

#8600 Fixes the chaplains Nature Orb
  code/modules/religion/religion_structures.dm
Labels: Fix

#8545 [PORT] Fix the spectral blade trapping ghosts
  code/datums/components/orbiter.dm
Labels: Fix

#8551 [PORT] Removes some dead/unused code
  beestation.dme
  code/game/machinery/camera/camera.dm
  code/game/machinery/doors/checkForMultipleDoors.dm
  code/game/objects/items/implants/implantchair.dm
  code/game/turfs/open/floor.dm
  code/game/turfs/turf.dm
  code/modules/hydroponics/grown/mushrooms.dm
  code/modules/hydroponics/seeds.dm
  code/modules/mob/living/living.dm
Labels: Code Improvement

#8615 Updates the compile workflow to use a new action
  .github/workflows/compile_changelogs.yml
Labels: GitHub, Server

#8266 Ports atmos hide rework and plumbing mapping
  _maps/RandomZLevels/moonoutpost19.dmm
  _maps/RandomZLevels/undergroundoutpost45.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  beestation.dme
  code/__DEFINES/dcs/signals/signals_obj/signals_object.dm
  code/controllers/subsystem/minor_mapping.dm
  code/datums/components/plumbing/_plumbing.dm
  code/datums/elements/undertile.dm
  code/game/area/areas.dm
  code/game/atoms.dm
  code/game/machinery/Beacon.dm
  code/game/machinery/magnet.dm
  code/game/machinery/navbeacon.dm
  code/game/machinery/pipe/construction.dm
  code/game/objects/effects/effect_system/effects_foam.dm
  code/game/objects/effects/effect_system/effects_smoke.dm
  code/game/objects/items/devices/pressureplates.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/obj_defense.dm
  code/game/objects/objs.dm
  code/game/objects/structures/safe.dm
  code/game/objects/structures/window.dm
  code/game/turfs/open/floor.dm
  code/game/turfs/open/floor/plating.dm
  code/game/turfs/turf.dm
  code/modules/antagonists/clock_cult/clockwork_turfs.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/atmospherics/machinery/components/binary_devices/binary_devices.dm
  code/modules/atmospherics/machinery/components/binary_devices/dp_vent_pump.dm
  code/modules/atmospherics/machinery/components/components_base.dm
  code/modules/atmospherics/machinery/components/unary_devices/outlet_injector.dm
  code/modules/atmospherics/machinery/components/unary_devices/passive_vent.dm
  code/modules/atmospherics/machinery/components/unary_devices/portables_connector.dm
  code/modules/atmospherics/machinery/components/unary_devices/unary_devices.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/atmospherics/machinery/other/meter.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/he_pipes.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/junction.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/manifold.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/manifold4w.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/simple.dm
  code/modules/atmospherics/machinery/pipes/layermanifold.dm
  code/modules/atmospherics/machinery/pipes/manifold.dm
  code/modules/atmospherics/machinery/pipes/manifold4w.dm
  code/modules/atmospherics/machinery/pipes/mapping.dm
  code/modules/atmospherics/machinery/pipes/multiz.dm
  code/modules/atmospherics/machinery/pipes/pipes.dm
  code/modules/atmospherics/machinery/pipes/simple.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/plumbing/ducts.dm
  code/modules/power/cable.dm
  code/modules/power/terminal.dm
  code/modules/projectiles/guns/misc/beam_rifle.dm
  code/modules/recycling/disposal/construction.dm
  code/modules/recycling/disposal/pipe.dm
  code/modules/shuttle/on_move.dm
Labels: Mapping, Needs Testmerge, Tweak, Feature, Fix, Grammar and Formatting, Refactor, Code Improvement

#8626 Makes the "Operative" Exploration Assasination target spawn with a hardsuit rather than just a helmet.
  code/modules/shuttle/super_cruise/orbital_poi_generator/objective_types/assassination.dm
Labels: Fix

#8606 [PORT(?)] light code cleanup and update
  beestation.dme
  code/modules/power/lighting/_light_defines.dm
  code/modules/power/lighting/light.dm
  code/modules/power/lighting/light_construct.dm
  code/modules/power/lighting/light_items.dm
  code/modules/power/lighting/light_wallframes.dm
Labels: Code Improvement, Good PR

#8614 Fix one mind vessels still having the pink glow and HUD after being deconverted
  code/modules/antagonists/hivemind/spells/hivemind_dominance.dm
  code/modules/antagonists/hivemind/spells/hivemind_thrall.dm
  code/modules/antagonists/hivemind/vessel.dm
Labels: Fix

#8617 Optimizes 'for' loops and minor list optimizations
  code/__HELPERS/_lists.dm
  code/__HELPERS/files.dm
  code/__HELPERS/icons.dm
  code/__HELPERS/text.dm
  code/_onclick/hud/alert.dm
  code/controllers/subsystem/processing/networks.dm
  code/controllers/subsystem/vote.dm
  code/datums/ai_laws.dm
  code/datums/martial/wrestling.dm
  code/game/gamemodes/meteor/meteors.dm
  code/game/machinery/computer/arcade.dm
  code/game/machinery/computer/dna_console.dm
  code/game/machinery/fabricators/modular_fabricator.dm
  code/game/machinery/slotmachine.dm
  code/game/objects/effects/effect_system/effects_smoke.dm
  code/game/objects/effects/spawners/gibspawner.dm
  code/game/objects/items/devices/taperecorder.dm
  code/game/objects/items/extinguisher.dm
  code/game/objects/items/granters.dm
  code/game/objects/items/storage/secure.dm
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  code/modules/admin/verbs/SDQL2/SDQL_2.dm
  code/modules/admin/verbs/_help.dm
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/antagonists/abductor/machinery/dispenser.dm
  code/modules/antagonists/eldritch_cult/eldritch_magic.dm
  code/modules/antagonists/traitor/equipment/contractor.dm
  code/modules/clothing/shoes/_shoes.dm
  code/modules/events/electrical_storm.dm
  code/modules/events/shuttle_loan.dm
  code/modules/events/wormholes.dm
  code/modules/food_and_drinks/recipes/food_mixtures.dm
  code/modules/mapping/space_management/space_transition.dm
  code/modules/mining/abandoned_crates.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/silicon/robot/laws.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/transform_procs.dm
  code/modules/power/lighting/light.dm
  code/modules/procedural_mapping/mapGenerator.dm
  code/modules/procedural_mapping/mapGenerators/cellular.dm
  code/modules/projectiles/boxes_magazines/_box_magazine.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/reagents/chem_splash.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/reagents/chemistry/recipes.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/research/xenobiology/crossbreeding/burning.dm
  code/modules/research/xenobiology/crossbreeding/industrial.dm
  code/modules/research/xenobiology/crossbreeding/selfsustaining.dm
  code/modules/ruins/spaceruin_code/hilbertshotel.dm
  code/modules/spells/spell.dm
  code/modules/spells/spell_types/conjure.dm
  code/modules/spells/spell_types/projectile.dm
  code/modules/vending/_vending.dm
Labels: Administration, Code Improvement

#8632 Clockcult fixes
  code/modules/antagonists/clock_cult/clockwork_turfs.dm
  code/modules/antagonists/clock_cult/scriptures/dimensional_breach.dm
Labels: Fix

#8621 Cayeene will no longer be attacked by carps
  code/modules/mob/living/simple_animal/hostile/carp.dm
Labels: Balance/Rebalance

#8620 Faster windoors
  code/game/machinery/doors/windowdoor.dm
  icons/obj/doors/windoor.dmi
  sound/machines/windowdoor.ogg
Labels: Tweak, Sprites, Balance/Rebalance, Sound

#8601 [PORT] Updates the Smelter UI into a TGUI format
  code/modules/mining/machine_processing.dm
  tgui/packages/tgui/interfaces/Smelter.js
Labels: Refactor, TGUI-Changes

#8592 Spell code improvement
  beestation.dme
  code/__DEFINES/magic.dm
  code/__DEFINES/misc.dm
  code/__DEFINES/say.dm
  code/datums/mutations/actions.dm
  code/modules/antagonists/clock_cult/mobs/eminence.dm
  code/modules/antagonists/clock_cult/scriptures/summon_spear.dm
  code/modules/antagonists/eldritch_cult/eldritch_magic.dm
  code/modules/antagonists/hivemind/spells/hivemind_add.dm
  code/modules/antagonists/hivemind/spells/hivemind_barrier.dm
  code/modules/antagonists/hivemind/spells/hivemind_dominance.dm
  code/modules/antagonists/hivemind/spells/hivemind_heal.dm
  code/modules/antagonists/hivemind/spells/hivemind_integrate.dm
  code/modules/antagonists/hivemind/spells/hivemind_invasion.dm
  code/modules/antagonists/hivemind/spells/hivemind_loyalty.dm
  code/modules/antagonists/hivemind/spells/hivemind_panic.dm
  code/modules/antagonists/hivemind/spells/hivemind_probe.dm
  code/modules/antagonists/hivemind/spells/hivemind_rally.dm
  code/modules/antagonists/hivemind/spells/hivemind_spells.dm
  code/modules/antagonists/hivemind/spells/hivemind_thrall.dm
  code/modules/awaymissions/mission_code/Academy.dm
  code/modules/guardian/abilities/_ability.dm
  code/modules/guardian/abilities/special/time.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/research/xenobiology/crossbreeding/_mobs.dm
  code/modules/spells/spell.dm
  code/modules/spells/spell_types/aimed.dm
  code/modules/spells/spell_types/barnyard.dm
  code/modules/spells/spell_types/blind.dm
  code/modules/spells/spell_types/charge.dm
  code/modules/spells/spell_types/cluwnecurse.dm
  code/modules/spells/spell_types/cone_spells.dm
  code/modules/spells/spell_types/conjure.dm
  code/modules/spells/spell_types/construct_spells.dm
  code/modules/spells/spell_types/devil.dm
  code/modules/spells/spell_types/devil_boons.dm
  code/modules/spells/spell_types/ethereal_jaunt.dm
  code/modules/spells/spell_types/forcewall.dm
  code/modules/spells/spell_types/infinite_guns.dm
  code/modules/spells/spell_types/knock.dm
  code/modules/spells/spell_types/lesserlichdom.dm
  code/modules/spells/spell_types/lichdom.dm
  code/modules/spells/spell_types/lightning.dm
  code/modules/spells/spell_types/mind_transfer.dm
  code/modules/spells/spell_types/rod_form.dm
  code/modules/spells/spell_types/santa.dm
  code/modules/spells/spell_types/shapeshift.dm
  code/modules/spells/spell_types/soultap.dm
  code/modules/spells/spell_types/spacetime_distortion.dm
  code/modules/spells/spell_types/summonitem.dm
  code/modules/spells/spell_types/taeclowndo.dm
  code/modules/spells/spell_types/the_traps.dm
  code/modules/spells/spell_types/touch_attacks.dm
  code/modules/spells/spell_types/wizard.dm
Labels: Tweak, Code Improvement

#8627 Cuts the health of Lavaland Elite mobs in half.
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/goliath_broodmother.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/herald.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/legionnaire.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/pandora.dm
Labels: Tweak, Balance/Rebalance

#8536 Fixed the bug of snow not showing up, minor typo fix and merged ores.dmi with materials.dmi
  beestation.dme
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/stacks/ores/ore.dm
  code/game/objects/items/stacks/sheets/mineral/materials.dm
  code/game/objects/items/stacks/sheets/miscellaneous/miscellaneous_mats.dm
  code/game/objects/items/stacks/sheets/miscellaneous/miscellaneous_mats_recipes.dm
  code/game/objects/items/stacks/sheets/organic/cloths.dm
  code/game/objects/items/stacks/sheets/organic/miscellaneous_organics.dm
  code/game/objects/items/stacks/wrap.dm
  code/modules/asset_cache/asset_list_items.dm
  icons/obj/stacks/minerals.dmi
  icons/obj/stacks/miscellaneous.dmi
  icons/obj/stacks/ores.dmi
Labels: Sprites, Fix

#8529 Megafauna no longer permanently remove victims from the round
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
Labels: Tweak

#8574 Fixes monkey hat and mask offset
  code/modules/mob/living/carbon/human/species_types/monkey.dm
Labels: Fix

#8470 Fixes ghosts runtiming when update_icon is called on them.
  code/modules/client/preferences_toggles.dm
  code/modules/mob/dead/observer/login.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Fix

#8443 Allows for wall mirror frames to be crafted
  code/datums/components/crafting/recipes.dm
  code/game/machinery/newscaster/newscaster_machine.dm
  code/game/objects/structures/artstuff.dm
  code/game/objects/structures/extinguisher.dm
  code/game/objects/structures/mirror.dm
  code/modules/photography/photos/frame.dm
  icons/obj/wallframe.dmi
Labels: Feature, Sprites, Fix, Code Improvement

#8534 Updates the shuttle construction maintenance room to use drydocks instead of a hole to space.
  _maps/RandomRooms/10x10/sk_rdm088_bigconstruction.dmm
Labels: Mapping

#8638 Ports 'Prevents negative mats'
  code/datums/components/material_container.dm
  code/modules/mining/machine_redemption.dm
Labels: Fix

#8619 Fixed the security belt worn sprite
  code/game/objects/items/storage/belt.dm
Labels: Fix

#8642 misc. say fixes (mostly custom say emote fixes)
  code/__HELPERS/text.dm
  code/_globalvars/misc.dm
  code/modules/mob/dead/observer/say.dm
  code/modules/mob/living/say.dm
  code/modules/mob/say.dm
Labels: Fix, Code Improvement

#8555 Fixes being unable to send ellipses at the beginning of sentences correctly
  code/modules/mob/say.dm
Labels: Tweak

#8587 Ports 'Item Pickup Brush-Up' from TG
  code/__DEFINES/obj_flags.dm
  code/_globalvars/bitfields.dm
  code/game/atoms_movable.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/powersink.dm
  code/game/objects/items/toys.dm
  code/game/objects/structures/flora.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/carbon.dm
Labels: Feature

#8643 Only ID cards can go in the Captain's Spare Safe.
  code/game/objects/items/storage/secure.dm
Labels: Tweak

#8608 Fixes RPD not unwrenching and repainting + minor debug tweak
  code/game/objects/items/RPD.dm
  code/game/objects/items/debug_items.dm
Labels: Feature, Fix

#8610 Improves player security checks for Cyborg and Mechs
  code/__DEFINES/role_preferences.dm
  code/game/mecha/mecha_defense.dm
  code/game/objects/items/robot/robot_parts.dm
  code/modules/jobs/job_types/ai.dm
  code/modules/jobs/job_types/atmospheric_technician.dm
  code/modules/jobs/job_types/brig_physician.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/chemist.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/cyborg.dm
  code/modules/jobs/job_types/deputy.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/exploration_team.dm
  code/modules/jobs/job_types/geneticist.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/medical_doctor.dm
  code/modules/jobs/job_types/paramedic.dm
  code/modules/jobs/job_types/quartermaster.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/jobs/job_types/scientist.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/station_engineer.dm
  code/modules/jobs/job_types/virologist.dm
  code/modules/jobs/job_types/warden.dm
  code/modules/mob/living/brain/posibrain.dm
Labels: Tweak, Feature, Code Improvement

#8604 Ports the storage squash animation from TG
  code/datums/components/storage/concrete/_concrete.dm
  code/datums/components/storage/storage.dm
  code/game/objects/items/storage/bags.dm
Labels: Feature, Good PR

#8664 Fixes SSvote votes
  code/controllers/subsystem/vote.dm
Labels: Fix

#8586 Update to Python 3.11.2, Node 18.14.2, Inferno 8, Typescript 4.9, Yarn 3.4
  .github/workflows/compile_changelogs.yml
  .github/workflows/continuous_integration.yml
  .github/workflows/make_changelogs.yml
  dependencies.sh
  tgui/.eslintrc-sonar.yml
  tgui/.eslintrc.yml
  tgui/.yarn/releases/yarn-3.1.1.cjs
  tgui/.yarn/releases/yarn-3.4.1.cjs
  tgui/.yarn/sdks/eslint/bin/eslint.js
  tgui/.yarn/sdks/eslint/lib/api.js
  tgui/.yarn/sdks/eslint/package.json
  tgui/.yarn/sdks/typescript/bin/tsc
  tgui/.yarn/sdks/typescript/bin/tsserver
  tgui/.yarn/sdks/typescript/lib/tsc.js
  tgui/.yarn/sdks/typescript/lib/tsserver.js
  tgui/.yarn/sdks/typescript/lib/tsserverlibrary.js
  tgui/.yarn/sdks/typescript/lib/typescript.js
  tgui/.yarn/sdks/typescript/package.json
  tgui/.yarnrc.yml
  tgui/package.json
  tgui/packages/tgfont/package.json
  tgui/packages/tgui-bench/package.json
  tgui/packages/tgui-dev-server/package.json
  tgui/packages/tgui-panel/package.json
  tgui/packages/tgui-polyfill/package.json
  tgui/packages/tgui/components/Box.tsx
  tgui/packages/tgui/components/LabeledList.tsx
  tgui/packages/tgui/components/Popper.tsx
  tgui/packages/tgui/components/Section.tsx
  tgui/packages/tgui/components/Tooltip.tsx
  tgui/packages/tgui/interfaces/BountyBoard.js
  tgui/packages/tgui/interfaces/NtosLogViewer.js
  tgui/packages/tgui/interfaces/PlayerPanel.js
  tgui/packages/tgui/interfaces/Stack.js
  tgui/packages/tgui/interfaces/TicketMessenger.js
  tgui/packages/tgui/package.json
  tgui/tsconfig.json
  tgui/yarn.lock
  tools/bootstrap/python311._pth
  tools/bootstrap/python_.ps1
  tools/changelog/requirements.txt
  tools/requirements.txt
Labels: GitHub, Tools, TGUI-Changes, Testmerge Passed

#8645 Adds icons to the description of PKAs and PKCs, fixes the description of the PKC
  code/modules/mining/equipment/kinetic_crusher.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
Labels: Feature, Fix

#8542 spacevine event / deploying kudzu now notifies ghosts
  code/modules/events/spacevine.dm
Labels: Feature

#8667 No longer runs the CI on every push to master.
  .github/workflows/continuous_integration.yml
Labels: GitHub

#8653 Default to human for active character slot when there is no database
  code/controllers/configuration/entries/game_options.dm
  code/modules/client/preferences.dm
  config/game_options.txt
Labels: Feature, Config Update

#8631 Ports the edible component from TG
  beestation.dme
  code/__DEFINES/dcs/signals/signals_obj/signals_item/signals_food.dm
  code/__DEFINES/food.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/obj_flags.dm
  code/datums/components/edible.dm
  code/game/objects/items.dm
  code/modules/antagonists/abductor/equipment/gland.dm
  code/modules/food_and_drinks/food.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/mining/equipment/regenerative_core.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/carbon/alien/organs.dm
  code/modules/mob/living/carbon/alien/special/alien_embryo.dm
  code/modules/surgery/organ_manipulation.dm
  code/modules/surgery/organs/appendix.dm
  code/modules/surgery/organs/heart.dm
  code/modules/surgery/organs/liver.dm
  code/modules/surgery/organs/lungs.dm
  code/modules/surgery/organs/organ_internal.dm
  code/modules/surgery/organs/tongue.dm
Labels: Feature, Refactor

#8639 ModPCs use the same TGUI window + ModPC fixes
  code/__DEFINES/time.dm
  code/__HELPERS/_logging.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/security.dm
  code/modules/NTNet/network.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/modular_computers/computers/item/computer.dm
  code/modules/modular_computers/computers/item/computer_ui.dm
  code/modules/modular_computers/computers/item/role_tablet_presets.dm
  code/modules/modular_computers/computers/item/tablet.dm
  code/modules/modular_computers/file_system/program.dm
  code/modules/modular_computers/file_system/programs/airestorer.dm
  code/modules/modular_computers/file_system/programs/alarm.dm
  code/modules/modular_computers/file_system/programs/antagonist/contract_uplink.dm
  code/modules/modular_computers/file_system/programs/antagonist/dos.dm
  code/modules/modular_computers/file_system/programs/antagonist/emag.dm
  code/modules/modular_computers/file_system/programs/antagonist/revelation.dm
  code/modules/modular_computers/file_system/programs/arcade.dm
  code/modules/modular_computers/file_system/programs/atmosscan.dm
  code/modules/modular_computers/file_system/programs/borg_monitor.dm
  code/modules/modular_computers/file_system/programs/borg_self_monitor.dm
  code/modules/modular_computers/file_system/programs/budgetordering.dm
  code/modules/modular_computers/file_system/programs/card.dm
  code/modules/modular_computers/file_system/programs/cargobounty.dm
  code/modules/modular_computers/file_system/programs/configurator.dm
  code/modules/modular_computers/file_system/programs/crewmanifest.dm
  code/modules/modular_computers/file_system/programs/file_browser.dm
  code/modules/modular_computers/file_system/programs/jobmanagement.dm
  code/modules/modular_computers/file_system/programs/log_viewer.dm
  code/modules/modular_computers/file_system/programs/newscaster.dm
  code/modules/modular_computers/file_system/programs/notepad.dm
  code/modules/modular_computers/file_system/programs/ntdownloader.dm
  code/modules/modular_computers/file_system/programs/ntmessenger.dm
  code/modules/modular_computers/file_system/programs/ntmonitor.dm
  code/modules/modular_computers/file_system/programs/ntnrc_client.dm
  code/modules/modular_computers/file_system/programs/phys_scanner.dm
  code/modules/modular_computers/file_system/programs/powermonitor.dm
  code/modules/modular_computers/file_system/programs/radar.dm
  code/modules/modular_computers/file_system/programs/records.dm
  code/modules/modular_computers/file_system/programs/remote_airlock.dm
  code/modules/modular_computers/file_system/programs/robocontrol.dm
  code/modules/modular_computers/file_system/programs/secureye.dm
  code/modules/modular_computers/file_system/programs/signaller.dm
  code/modules/modular_computers/file_system/programs/sm_monitor.dm
  code/modules/modular_computers/file_system/programs/statusdisplay.dm
  code/modules/modular_computers/file_system/programs/techweb.dm
  code/modules/modular_computers/file_system/programs/wiki_uplink.dm
  code/modules/modular_computers/hardware/card_slot.dm
  code/modules/modular_computers/hardware/network_card.dm
  code/modules/tgui/tgui.dm
  tgui/packages/tgui/layouts/NtosWindow.js
Labels: Tweak, Feature, Fix, Balance/Rebalance, Administration, Code Improvement, TGUI-Changes

#8511 [Port] Adds colored stripes to departmental protolathes/techfab
  code/modules/research/machinery/_production.dm
  code/modules/research/machinery/departmental_protolathe.dm
  code/modules/research/machinery/departmental_techfab.dm
  icons/obj/machines/research.dmi
Labels: Feature, Sprites

#8556 [PORT] Various Ambience improvements
  code/__DEFINES/sound.dm
  code/_globalvars/lists/ambience.dm
  code/controllers/subsystem/ambience.dm
  code/controllers/subsystem/server_maint.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas.dm
  code/game/area/areas/mining.dm
  code/game/area/areas/ruins/lavaland.dm
  code/modules/client/client_procs.dm
  sound/ambience/ambiviro.ogg
  sound/ambience/ambiviro1.ogg
  sound/ambience/ambiviro2.ogg
  sound/ambience/cavesound3.ogg
  sound/ambience/magma.ogg
  sound/ambience/maintambience.ogg
  sound/ambience/source_corridor2.ogg
  sound/ambience/source_holehit3.ogg
Labels: Feature, Fix, Sound, Code Improvement

#8661 Makes holoparasites movable lights
  code/modules/guardian/guardian.dm
Labels: Tweak

#8670 Fix SecurEye and Bounty Viewer apps not working
  code/modules/modular_computers/computers/item/computer_ui.dm
  code/modules/modular_computers/file_system/program.dm
  code/modules/modular_computers/file_system/programs/cargobounty.dm
  code/modules/modular_computers/file_system/programs/ntmessenger.dm
  code/modules/modular_computers/file_system/programs/secureye.dm
Labels: Tweak, Fix

#8478 Basic Elevators
  _maps/RandomZLevels/snowdin.dmm
  _maps/map_files/debug/multiz.dmm
  _maps/shuttles/snowdin/snowdin_excavation.dmm
  _maps/shuttles/snowdin/snowdin_mining.dmm
  _maps/shuttles/turbolifts/debug/debug_primary.dmm
  beestation.dme
  code/__DEFINES/dcs/signals/signals_obj/signals_machine/signals_elevator.dm
  code/__DEFINES/sound.dm
  code/__DEFINES/subsystems.dm
  code/datums/shuttles.dm
  code/modules/elevator/elevator_controller.dm
  code/modules/elevator/elevator_indicator.dm
  code/modules/elevator/elevator_interface.dm
  code/modules/elevator/elevator_segment.dm
  code/modules/turbolift/README.md
  code/modules/turbolift/turbolift_areas.dm
  code/modules/turbolift/turbolift_docks.dm
  code/modules/turbolift/turbolift_machines.dm
  icons/obj/elevator.dmi
  icons/obj/turbolift.dmi
  icons/obj/turbolift_door.dmi
  sound/effects/turbolift/elevator_loop.ogg
  tgui/packages/tgui/index.js
  tgui/packages/tgui/interfaces/Elevator.js
  tgui/packages/tgui/interfaces/TurboLift.js
  tgui/packages/tgui/styles/themes/elevator.scss
  tgui/packages/tgui/styles/themes/retro.scss
Labels: Mapping, Tweak, Feature, Sprites, Sound, TGUI-Changes

#8655 Fixes fultons not working on necropolis chests
  code/modules/mining/lavaland/necropolis_chests.dm
Labels: Fix

#8635 Ports "Implements timed_action_flags for do_after-like procs"
  beestation.dme
  code/__DEFINES/timed_action.dm
  code/__HELPERS/atmos.dm
  code/__HELPERS/mobs.dm
  code/datums/components/storage/storage.dm
  code/datums/status_effects/debuffs.dm
  code/game/atoms.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/iv_drip.dm
  code/game/objects/buckling.dm
  code/game/objects/items/carp_lasso.dm
  code/game/objects/items/eightball.dm
  code/game/objects/items/religion.dm
  code/game/objects/items/tools/wirecutters.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/popout_cake.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/watercloset.dm
  code/game/turfs/turf.dm
  code/modules/antagonists/eldritch_cult/eldritch_book.dm
  code/modules/antagonists/eldritch_cult/eldritch_magic.dm
  code/modules/antagonists/hivemind/hiveui.dm
  code/modules/antagonists/hivemind/spells/hivemind_add.dm
  code/modules/antagonists/hivemind/spells/hivemind_heal.dm
  code/modules/antagonists/hivemind/spells/hivemind_invasion.dm
  code/modules/antagonists/hivemind/spells/hivemind_probe.dm
  code/modules/antagonists/hivemind/spells/hivemind_shatter.dm
  code/modules/antagonists/hivemind/spells/hivemind_shock.dm
  code/modules/antagonists/revenant/revenant_abilities.dm
  code/modules/guardian/standarrow.dm
  code/modules/hydroponics/grown/kudzu.dm
  code/modules/library/lib_codex_gigas.dm
  code/modules/mining/minebot.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/mob/living/living_movement.dm
  code/modules/mob/living/simple_animal/friendly/drone/interaction.dm
  code/modules/research/xenobiology/crossbreeding/crystalized.dm
  code/modules/shuttle/super_cruise/shuttle_components/shuttle_docking.dm
  code/modules/spells/spell_types/lesserlichdom.dm
  code/modules/spells/spell_types/lichdom.dm
  code/modules/spells/spell_types/lightning.dm
  code/modules/surgery/anesthetic_machine.dm
  code/modules/vehicles/sealed.dm
Labels: Code Improvement

#8625 Adds engineering ERT plus minor equipment tweaks
  code/datums/ert.dm
  code/game/objects/items/storage/firstaid.dm
  code/modules/clothing/outfits/ert.dm
Labels: Tweak, Feature

#8602 Fixes the moodlets for Clown Shoes, Insulated and Black gloves
  code/modules/clothing/gloves/color.dm
  code/modules/clothing/shoes/miscellaneous.dm
Labels: Fix

#8652 Fix asay color sanitization not applying from the prefs menu
  code/modules/client/preferences.dm
Labels: Fix

#8649 Fix runtime with PDA admin message
  code/modules/tgui/tgui_input_pda_message.dm
Labels: Fix, Administration

#8677 Applies the SQL label to any changes in the SQL folder
  .github/file_labeler.yml
Labels: GitHub

#8548 Adds a new bioluminescence color and a new chemical reaction for Botany
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/turfs/open/floor/fancy_floor.dm
  code/modules/hydroponics/grown/citrus.dm
  code/modules/hydroponics/grown/grass_carpet.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/hydroponics/plant_genes.dm
  code/modules/hydroponics/seeds.dm
Labels: Feature, Needs Wiki Changes

#8668 Fix laser gatling gun
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/laser_gatling.dm
Labels: Fix

#8681 (Partial) Revert "Improves player security checks for Cyborg and Mechs"
  code/modules/jobs/job_types/ai.dm
  code/modules/jobs/job_types/atmospheric_technician.dm
  code/modules/jobs/job_types/brig_physician.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/chemist.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/cyborg.dm
  code/modules/jobs/job_types/deputy.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/exploration_team.dm
  code/modules/jobs/job_types/geneticist.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/medical_doctor.dm
  code/modules/jobs/job_types/paramedic.dm
  code/modules/jobs/job_types/quartermaster.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/jobs/job_types/scientist.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/station_engineer.dm
  code/modules/jobs/job_types/virologist.dm
  code/modules/jobs/job_types/warden.dm
Labels: Tweak

#8503 Makes Genetics a Bleeding-Edge and Unknown Science again
  code/datums/dna.dm
  code/datums/mutations.dm
  code/datums/mutations/actions.dm
  code/datums/mutations/antenna.dm
  code/datums/mutations/body.dm
  code/datums/mutations/chameleon.dm
  code/datums/mutations/cluwne.dm
  code/datums/mutations/cold.dm
  code/datums/mutations/hulk.dm
  code/datums/mutations/radioactive.dm
  code/datums/mutations/sight.dm
  code/datums/mutations/space_adaptation.dm
  code/datums/mutations/speech.dm
  code/datums/mutations/telekinesis.dm
  code/datums/mutations/touch.dm
Labels: Grammar and Formatting, Balance/Rebalance

#8541 Overhauls/adjusts solid plasma ignition in many things
  code/game/atoms.dm
  code/game/machinery/doors/airlock_types.dm
  code/game/objects/items/cigs_lighters.dm
  code/game/objects/items/devices/lightreplacer.dm
  code/game/objects/items/stacks/sheets/mineral/materials.dm
  code/game/objects/structures/false_walls.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/statues.dm
  code/game/turfs/closed/wall/mineral_walls.dm
  code/modules/mining/coins.dm
  code/modules/power/cell.dm
  code/modules/power/lighting/light.dm
  code/modules/power/lighting/light_items.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
Labels: Tweak, Balance/Rebalance, Code Improvement

#8662 Halves Glowshroom/glowcap/shadowshroom HP
  code/game/objects/effects/glowshroom.dm
Labels: Balance/Rebalance

#8644 Buffs the upgraded Malfunctioning AI turrets.
  code/game/machinery/porta_turret/portable_turret.dm
  code/modules/antagonists/traitor/equipment/Malf_Modules.dm
  code/modules/projectiles/projectile/beams.dm
Labels: Balance/Rebalance, Balance Approved

#8407 [PORT] Gender Neutrality
  code/__HELPERS/mobs.dm
  code/__HELPERS/sanitize_values.dm
  code/datums/datacore.dm
  code/datums/dna.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/security.dm
  code/game/objects/structures/mirror.dm
  code/modules/admin/create_mob.dm
  code/modules/admin/secrets.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences2/character_save.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/living.dm
  code/modules/modular_computers/file_system/programs/records.dm
  code/modules/ninja/suit/suit.dm
  code/modules/paperwork/filingcabinet.dm
  code/modules/paperwork/photocopier.dm
  code/modules/research/xenobiology/xenobiology.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  code/modules/surgery/healing.dm
  tgui/packages/tgui/interfaces/NtosRecords.js
Labels: Tweak, Feature, Fix, Grammar and Formatting, Administration, TGUI-Changes

#8650 Add soundtrack preference and separate channel
  SQL/database_changelog.txt
  code/__DEFINES/preferences.dm
  code/__DEFINES/sound.dm
  code/controllers/subsystem/shuttle.dm
  code/datums/soundtrack.dm
  code/game/sound.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/playsound.dm
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_toggles.dm
Labels: SQL, Tweak, Feature, Sound, Administration

#8693 Fixes gamebreaking oversight introduced in #8541
  code/game/atoms.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
Labels: Fix, Removal

#8707 Fixes a couple of uncaught bugs from #8635
  code/__DEFINES/timed_action.dm
  code/__HELPERS/mobs.dm
  code/game/objects/items/cardboard_cutouts.dm
  code/modules/mob/living/carbon/carbon.dm
Labels: Fix

#8700 Staff of storms fix
  code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
Labels: Fix

#8684 Morphs now husk victims on digestion instead of dusting
  code/modules/antagonists/morph/morph_stomach.dm
Labels: Balance/Rebalance, Removal

#8704 Increases the vendor crush animation duration to 80 seconds
  code/modules/vending/_vending.dm
Labels: Tweak

#8702 Fixes floodlights
  code/modules/power/floodlight.dm
Labels: Fix

#8697 Splits apc.dm
  beestation.dme
  code/__DEFINES/power/apc_defines.dm
  code/__DEFINES/power/power.dm
  code/_globalvars/misc.dm
  code/modules/power/apc.dm
  code/modules/power/apc/apc_appearance.dm
  code/modules/power/apc/apc_attack.dm
  code/modules/power/apc/apc_main.dm
  code/modules/power/apc/apc_malf.dm
  code/modules/power/apc/apc_mapping.dm
  code/modules/power/apc/apc_power_proc.dm
  code/modules/power/apc/apc_tool_act.dm
Labels: Code Improvement

#8689 makes occupant use setters
  code/__DEFINES/dcs/signals/signals_obj/signals_machine/signals_machinery.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/cloning.dm
  code/game/machinery/fat_sucker.dm
  code/game/machinery/stasis.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/objects/items/implants/implantchair.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/food_and_drinks/kitchen_machinery/gibber.dm
Labels: Code Improvement

#8687 Overlay subsystem fixes, adds overlay logging
  beestation.dme
  code/__DEFINES/overlays.dm
  code/controllers/subsystem/overlays.dm
Labels: Tweak, Fix

#8712 Fix soundtrack music stopping early
  code/game/sound.dm
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
Labels: Fix

#8665 Removes a certain d20's ability to be refreshed.
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
Labels: Balance/Rebalance, 🔑 Close Key (1/2), Balance Approved

#8395 Fugitive Refresh and Dynamic ruleset
  _maps/shuttles/hunter/hunter_bounty.dmm
  _maps/shuttles/hunter/hunter_russian.dmm
  _maps/shuttles/hunter/hunter_space_cop.dmm
  beestation.dme
  code/__DEFINES/antagonists.dm
  code/__DEFINES/role_preferences.dm
  code/_globalvars/lists/poll_ignore.dm
  code/game/area/areas/shuttles.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/melee/misc.dm
  code/game/objects/items/pinpointer.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/game/objects/structures/fugitive_role_spawners.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/admin/topic.dm
  code/modules/antagonists/fugitive/fugitive.dm
  code/modules/antagonists/fugitive/fugitive_outfits.dm
  code/modules/antagonists/fugitive/fugitive_ship.dm
  code/modules/antagonists/fugitive/fugitive_types.dm
  code/modules/antagonists/fugitive/hunter.dm
  code/modules/antagonists/fugitive/hunter_outfits.dm
  code/modules/antagonists/fugitive/hunter_types.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/hailer.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/suits/armor.dm
  code/modules/events/fugitive_spawning.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/surgery/organs/autosurgeon.dm
  icons/mob/clothing/head.dmi
  icons/mob/mask.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/storage.dmi
  tgui/packages/tgui/interfaces/FugitiveCaptureConsole.js
  tgui/packages/tgui/styles/themes/neutral.scss
Labels: Mapping, Tweak, Feature, Sprites, Fix, Refactor, Administration, Code Improvement, TGUI-Changes, Testmerge Passed

#8719 Fixes titlescreen bugs
  code/controllers/subsystem/title.dm
  code/game/objects/effects/landmarks.dm
Labels: Fix, Somewhat Important

#8720 Update expressconsole.dm
  code/modules/cargo/expressconsole.dm
Labels: Fix

#8721 Fixes xeno active hand icons
  icons/mob/screen_alien.dmi
Labels: Sprites, Fix

#8714 Fix cavity implants not being able to be cauterized with a searing tool
  code/modules/surgery/cavity_implant.dm
Labels: Fix

#8663 Darker black gloves
  icons/mob/clothing/hands.dmi
  icons/obj/clothing/gloves.dmi
Labels: Feature, Sprites

#8727 Fixes some incorrectly set timed_action_flags
  code/game/objects/structures/beds_chairs/alien_nest.dm
  code/game/objects/structures/kitchen_spike.dm
  code/modules/mob/living/carbon/carbon.dm
Labels: Fix

#8722 Tweaks sleeper - accepts chem bag
  code/game/machinery/Sleeper.dm
  code/modules/mining/equipment/survival_pod.dm
  code/modules/reagents/reagent_containers/chem_bag.dm
  tgui/packages/tgui/interfaces/Sleeper.js
Labels: Tweak, Feature, Code Improvement, TGUI-Changes

#8553 Ports 'Pointing at something on yourself now shows the item'
  beestation.dme
  code/__DEFINES/hud.dm
  code/game/atoms.dm
  code/game/objects/effects/decals/misc.dm
  code/game/objects/items.dm
  code/modules/mob/mob.dm
  code/modules/point/point.dm
  icons/effects/effects.dmi
Labels: Feature, Sprites

#8726 Add PTech vendor to Kilo
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Mapping, Feature

#8685 Allow blind people to use modular computers / PDAs again
  code/modules/modular_computers/computers/item/computer_ui.dm
Labels: Tweak

#8660 [PORT] Cream pie component
  beestation.dme
  code/__DEFINES/dcs/signals/signals_datum/signals_datum.dm
  code/datums/components/creamed.dm
  code/datums/elements/cleaning.dm
  code/game/atoms.dm
  code/game/objects/items/clown_items.dm
  code/game/objects/structures/shower.dm
  code/game/objects/structures/watercloset.dm
  code/modules/food_and_drinks/food/snacks_pie.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/surgery/bodyparts/dismemberment.dm
Labels: Feature, Code Improvement

#8729 Medical winter coats can also hold medkits now
  code/modules/clothing/suits/miscellaneous.dm
Labels: Tweak

#8718 Malf AI can no longer occur on lowpop
  code/controllers/configuration/entries/game_options.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/traitor/traitor.dm
  config/game_options.txt
Labels: Tweak, Config Update

#8743 Storage animation tweaks
  code/datums/components/storage/concrete/_concrete.dm
  code/datums/components/storage/storage.dm
  code/game/objects/structures/flora.dm
Labels: Tweak, Feature

#8753 Adds logging files to the github auto-labeler
  .github/file_labeler.yml
Labels: GitHub

#8609 Fixes plumbing pill press to choose pill styles, pill sprite string fix
  code/__DEFINES/reagents.dm
  code/modules/plumbing/plumbers/pill_press.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  tgui/packages/tgui/interfaces/ChemMaster.js
  tgui/packages/tgui/interfaces/ChemPress.js
Labels: Fix, Code Improvement, TGUI-Changes

#8764 Removes another mentor keywords_lookup moment (leaking admin href token)
  code/modules/admin/verbs/mentorhelp.dm
Labels: Fix, Administration

#8769 Actually fix voice of god perma-muting
  code/modules/surgery/organs/vocal_cords.dm
Labels: Fix

#8768 Mute/blindness/stutter/drunk/etc now respects delta time
  code/modules/mob/living/brain/life.dm
  code/modules/mob/living/carbon/alien/life.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/living/simple_animal/slime/life.dm
Labels: Fix

#8750 Redoes Turf-Decalening on Kilo
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Mapping, Fix

#8583 Updates status displays to use vis_contents
  code/game/machinery/status_display.dm
Labels: Tweak

#8781 Updates the bug report issue template.
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: GitHub, Code Improvement

#8135 [PORT] RPED Quality of Life Stuff
  code/datums/components/storage/concrete/rped.dm
  code/game/machinery/constructable_frame.dm
  code/modules/power/cell.dm
  code/modules/research/stock_parts.dm
Labels: Tweak, Feature

#8780 Bumps auxmos to v2.2.2
  auxtools/auxmos.dll
  dependencies.sh
Labels: Dependencies, Server, Testmerge Passed
