Repository BeeStation/BeeStation-Hornet, pull requests merged in 2023-05, with the labels that each got.

#8961 Adds more logging to blood and cult logs
  code/datums/components/cult_ritual_item.dm
  code/game/gamemodes/clock_cult/clockcult.dm
  code/modules/antagonists/clock_cult/clockwork_massive.dm
  code/modules/antagonists/cult/cult.dm
  code/modules/antagonists/cult/cult_comms.dm
Labels: Administration

#8975 Fixes Immobilize() for simplemobs and silicons
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Fix

#8868 Adds the "ISWEAPON" flag to a bunch of items I've forgotten about
  code/_onclick/telekinesis.dm
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/equipment/tools/work_tools.dm
  code/game/objects/items/chrono_eraser.dm
  code/game/objects/items/clown_items.dm
  code/game/objects/items/holy_weapons.dm
  code/game/objects/items/toys.dm
  code/modules/antagonists/clock_cult/items/clockwork_weapon.dm
  code/modules/antagonists/clock_cult/items/integration_cog.dm
  code/modules/instruments/items.dm
  code/modules/spells/spell_types/godhand.dm
Labels: Fix

#8944 Fixes all_access static list is poorly used, fixes some access codes
  _maps/map_files/PubbyStation/job_changes.dm
  code/game/machinery/computer/card.dm
  code/game/mecha/mecha_topic.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/antagonists/highlander/highlander.dm
  code/modules/antagonists/roundstart_special/undercover/undercover.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/jobs/access.dm
  code/modules/mob/living/simple_animal/bot/atmosbot.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
  code/modules/mob/living/simple_animal/bot/ed209bot.dm
  code/modules/mob/living/simple_animal/bot/firebot.dm
  code/modules/mob/living/simple_animal/bot/floorbot.dm
  code/modules/mob/living/simple_animal/bot/honkbot.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  code/modules/mob/living/simple_animal/bot/secbot.dm
  code/modules/modular_computers/file_system/programs/card.dm
  code/modules/research/nanites/nanite_programs/utility.dm
  code/modules/shuttle/supply.dm
Labels: Mapping, Code Improvement

#8878 Re-opening of "Exploration hardsuit's can now locate research disk, objectives and the exploration shuttle"
  code/__DEFINES/research.dm
  code/datums/action.dm
  code/datums/components/team_monitor.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/suits/toggles.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/loot/alien_artifact.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/loot/research_disks.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/objective_types/nuke_ruin.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/objective_types/recover_blackbox.dm
  code/modules/xenoarchaeology/traits/xenoartifact_traits.dm
  code/modules/xenoarchaeology/xenoartifact.dm
  icons/mob/actions.dmi
Labels: Feature, Sprites

#8711 Merges jellypeople and oozelings into one race
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mobs.dm
  code/controllers/subsystem/traumas.dm
  code/datums/components/spooky.dm
  code/datums/diseases/advance/symptoms/heal.dm
  code/datums/diseases/transformation.dm
  code/game/machinery/scan_gate.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/oozelings.dm
  code/modules/mob/living/simple_animal/hostile/redgrub.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
  code/modules/research/xenobiology/crossbreeding/_structures.dm
  code/modules/research/xenobiology/crossbreeding/charged.dm
  code/modules/research/xenobiology/crossbreeding/regenerative.dm
  code/modules/research/xenobiology/xenobiology.dm
  code/modules/surgery/advanced/bioware/experimental_dissection.dm
  code/modules/surgery/organs/lungs.dm
  tgui/packages/tgui/interfaces/ScannerGate.js
Labels: Tweak, Fix, Balance/Rebalance, Removal, TGUI-Changes

#8972 Fixes gain and lose notice of the Linguist trait
  code/datums/traits/positive_quirk.dm
Labels: Fix, Grammar and Formatting

#8977 Adds a pAI holochasis: mothroach
  code/modules/mob/living/silicon/pai/pai.dm
  icons/mob/pai.dmi
  icons/mob/pai_item_head.dmi
  icons/mob/pai_item_lh.dmi
  icons/mob/pai_item_rh.dmi
Labels: Feature, Sprites

#8683 Cyborg balance and QoL v2
  code/__DEFINES/movespeed_modification.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/assembly/flash.dm
  code/modules/mob/living/silicon/robot/inventory.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/silicon_defense.dm
  icons/mob/robots.dmi
Labels: Tweak, Sprites, Fix, Balance/Rebalance

#8706 Links supermatter processing to complete atmos processing
  code/controllers/subsystem/air.dm
  code/modules/power/supermatter/supermatter.dm
Labels: Fix

#8709 Ports "Internals Bugfixes & Internals-Compatible Helmets" from TG
  code/__DEFINES/obj_flags.dm
  code/_globalvars/bitfields.dm
  code/_onclick/hud/screen_objects.dm
  code/datums/outfit.dm
  code/game/gamemodes/gangs/gang_items.dm
  code/game/objects/items/tanks/tank_types.dm
  code/game/objects/items/tanks/tanks.dm
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/antagonists/ert/ert.dm
  code/modules/antagonists/official/official.dm
  code/modules/clothing/chameleon.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/masks/_masks.dm
  code/modules/clothing/masks/breath.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/clothing/spacesuits/_spacesuits.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_stripping.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/carbon/inventory.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/surgery/anesthetic_machine.dm
Labels: Feature, Fix, Refactor, Removal

#8822 Replace GlowStation Secure Elevator with an actual elevator
  _maps/map_files/GlowStation/GlowStation.dmm
  code/modules/elevator/elevator_indicator.dm
  code/modules/elevator/elevator_interface.dm
  code/modules/elevator/elevator_segment.dm
Labels: Mapping, Tweak, Feature, Fix

#8846 Sleeper Code improvement + UX + bluescreen fix
  beestation.dme
  code/game/machinery/sleeper.dm
  tgui/packages/tgui/interfaces/Sleeper.js
Labels: Tweak, Fix, TGUI-Changes

#8850 Frozen optimizations and element
  beestation.dme
  code/__DEFINES/dcs/signals/signals_obj/signals_object.dm
  code/__DEFINES/obj_flags.dm
  code/__DEFINES/reactions.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/icons.dm
  code/_globalvars/bitfields.dm
  code/_onclick/click.dm
  code/datums/components/wet_floor.dm
  code/datums/elements/frozen.dm
  code/game/objects/objs.dm
  code/game/turfs/open/_open.dm
  code/game/turfs/turf.dm
  code/modules/atmospherics/gasmixtures/reactions.dm
  code/modules/projectiles/projectile/special/temperature.dm
Labels: Fix, Code Improvement

#8892 Brainwashing refactor + potential exploit fix
  code/game/machinery/race_converter.dm
  code/game/objects/items/implants/implant_mindshield.dm
  code/game/objects/items/implants/implantchair.dm
  code/modules/antagonists/brainwashing/brainwashing.dm
  code/modules/antagonists/hivemind/vessel.dm
  code/modules/research/nanites/nanite_programs/weapon.dm
  code/modules/surgery/advanced/brainwashing.dm
  code/modules/surgery/advanced/lobotomy.dm
  code/modules/surgery/brain_recalibration.dm
Labels: Feature, Fix, Refactor

#8919 Minor Proximity monitor fixes
  code/controllers/subsystem/zclear.dm
  code/game/area/ai_monitored.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/camera/presets.dm
  code/modules/ruins/spaceruin_code/hilbertshotel.dm
  code/modules/shuttle/on_move.dm
Labels: Fix, Grammar and Formatting

#8939 Multi-Z Battle Royale support
  code/modules/admin/battle_royale.dm
  code/modules/mapping/space_management/traits.dm
Labels: Fix, Administration

#8940 Fixes mindless human self-examine runtime
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Fix, Code Improvement

#8942 Orbit panel now tracks antag team correctly + Minor tweak
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/antagonists/_common/antag_team.dm
  code/modules/antagonists/cult/cult.dm
  code/modules/antagonists/eldritch_cult/eldritch_monster_antag.dm
  code/modules/antagonists/fugitive/fugitive.dm
  code/modules/antagonists/fugitive/fugitive_types.dm
  code/modules/antagonists/fugitive/hunter.dm
  code/modules/antagonists/fugitive/hunter_types.dm
  code/modules/antagonists/guardian/guardian.dm
  code/modules/antagonists/pirate/pirate.dm
  code/modules/antagonists/slaughter/slaughter_antag.dm
  code/modules/antagonists/swarmer/swarmer.dm
  code/modules/antagonists/traitor/equipment/contractor.dm
  code/modules/antagonists/wizard/wizard.dm
  code/modules/antagonists/xeno/xeno.dm
  code/modules/mob/dead/observer/orbit.dm
  tgui/packages/tgui/interfaces/Orbit.js
Labels: Tweak, Feature, Fix, TGUI-Changes

#8954 Adds an extra sanity check to tongueless speech
  code/modules/mob/living/carbon/say.dm
Labels: Fix

#8956 Cleans up silicon deletion, adds stack_trace for erroneous lawset reset/removal
  code/datums/ai_laws.dm
  code/game/objects/structures/ai_core.dm
  code/modules/mob/living/brain/MMI.dm
  code/modules/mob/living/silicon/robot/laws.dm
  code/modules/mob/living/silicon/silicon.dm
Labels: Fix, Removal

#8962 Actually fixes the monkey species runtime this time.
  code/datums/mutations/body.dm
  code/modules/mob/transform_procs.dm
Labels: Fix

#8960 Fixes spider venom / nanite interactions
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
Labels: Fix

#8983 Fixes stabilized rainbow extracts
  code/modules/research/xenobiology/crossbreeding/_status_effects.dm
  code/modules/research/xenobiology/crossbreeding/regenerative.dm
Labels: Fix

#8986 Fix feeding organs to people after inserting them
  code/modules/surgery/organs/organ_internal.dm
Labels: Fix

#8987 Flandstation fix batch (FlandStation Sp5.5 - Medbay edition)
  _maps/RandomRooms/fland/sk_rdm_fln_01_scooterpark.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_02_beelounge.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_03_vendingminimarket.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_04_conveniencestore.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_05_apiary.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_06_publicgarden.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_07_theletterh.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_08_zenroom.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_09_barbershop.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_10_readingroom.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_11_hobobox.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_12_magicstage.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_13_cheeseroom.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  code/game/objects/effects/spawners/roomspawner.dm
  code/modules/mapping/random_rooms.dm
Labels: Mapping, Tweak, Feature, Fix

#8970 Fix for perma locked suit storage.
  code/game/machinery/suit_storage_unit.dm
Labels: Tweak, Feature, Sprites, Fix, Grammar and Formatting, Balance/Rebalance, Refactor, Sound, Removal, Code Improvement, Server

#8999 Fixes plasmamen spawning without open internals
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
Labels: Feature, Fix

#9015 Prevents stabilized metal crossbreeds from being able to replicate TC
  code/modules/research/xenobiology/crossbreeding/_status_effects.dm
Labels: Fix

#9007 Fixes nukie team unnanmed
  code/modules/antagonists/nukeop/nukeop.dm
Labels: Fix

#8989 Doubles the Extrapolator's extraction speed again
  code/game/objects/items/devices/scanners.dm
Labels: Tweak

#8997 Slime crossbreeds and slime colors can now be scanned for discovery points
  code/modules/exploration_crew/discovery_research/discoverable_component.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  code/modules/research/xenobiology/crossbreeding/__corecross.dm
Labels: Tweak, Feature

#9005 Another futile attempt at fixing the species getting set to null after Genetics shenanigans
  code/datums/mutations/body.dm
  code/modules/mob/transform_procs.dm
Labels: Fix

#8694 Refactors the entire alarm system, moves behavior to datums
  beestation.dme
  code/__DEFINES/alarm.dm
  code/__DEFINES/dcs/signals/signals_datum/signals_datum.dm
  code/__DEFINES/dcs/signals/signals_mob/signals_living.dm
  code/datums/alarm.dm
  code/datums/wires/airalarm.dm
  code/game/area/areas.dm
  code/game/area/areas/iceland.dm
  code/game/area/areas/mining.dm
  code/game/area/areas/ruins/lavaland.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/camera/motion.dm
  code/game/machinery/computer/station_alert.dm
  code/game/objects/structures/displaycase.dm
  code/modules/atmospherics/machinery/airalarm.dm
  code/modules/awaymissions/mission_code/moonoutpost19.dm
  code/modules/awaymissions/mission_code/undergroundoutpost45.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  code/modules/modular_computers/file_system/programs/alarm.dm
  code/modules/power/apc/apc_attack.dm
  code/modules/power/apc/apc_main.dm
  code/modules/power/singularity/investigate.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/exoplanets/biomes/_biome.dm
Labels: Refactor, Removal

#8966 Makes several adjustments to Ash Walkers
  _maps/RandomRuins/LavaRuins/lavaland_surface_ash_walker1.dmm
  code/modules/clothing/under/costume.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/surgery/organs/lungs.dm
Labels: Mapping, Tweak, Feature, Balance/Rebalance

#8946 Adds a strict minimum population of 24 to blood and clock cult.
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
Labels: Balance/Rebalance

#9006 Fixes a runtime with Plasmaman job outfits
  code/modules/jobs/job_types/gimmick.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
Labels: Fix

#8433 Pinpointer refactor: z tracking, more indicator sprites, better crew monitor code
  code/controllers/subsystem/processing/orbits.dm
  code/game/objects/items/pinpointer.dm
  code/modules/antagonists/traitor/equipment/contractor.dm
  code/modules/mob/living/silicon/ai/death.dm
  code/modules/modular_computers/file_system/programs/radar.dm
  icons/obj/device.dmi
  tgui/packages/tgui/interfaces/NtosRadar.js
Labels: Tweak, Feature, Sprites, Refactor, Code Improvement, TGUI-Changes

#8690 Adds SI unit formatting proc
  code/__HELPERS/text.dm
  code/game/machinery/spaceheater.dm
  code/game/mecha/mech_bay.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/siunit.dm
Labels: Feature

#8580 Prevents antagonists without a murderbone objective from hijacking the emergency escape shuttle
  code/modules/shuttle/emergency.dm
Labels: Tweak

#8533 Minor buff to Chem Master
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  tgui/packages/tgui/interfaces/ChemMaster.js
Labels: Feature, Balance/Rebalance, TGUI-Changes

#8672 Upgrades are now useful for nanite chambers
  code/modules/research/nanites/nanite_chamber.dm
  code/modules/research/nanites/public_chamber.dm
Labels: Balance/Rebalance

#9019 Fixes health display for TGUI cyborg panel
  code/modules/modular_computers/file_system/programs/borg_self_monitor.dm
Labels: Fix

#9018 Removes Soft AA from HOS
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/GlowStation/GlowStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  code/modules/jobs/job_types/head_of_security.dm
Labels: Mapping, Removal

#9024 [PR RECOUP] Ecto Sniffer yells over Science Comms now
  code/game/machinery/ecto_sniffer.dm
Labels: Tweak

#9014 Makes Sergeant Araneus a proper subtype
  _maps/map_files/GlowStation/GlowStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  code/modules/mob/living/simple_animal/hostile/retaliate/bat.dm
Labels: Mapping, Tweak

#9033 Remove the password door
  beestation.dme
  code/game/machinery/doors/passworddoor.dm
Labels: Removal

#8068 [PORT] pre-newfood cooking-palooza
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/food_and_drinks/food/snacks_pastry.dm
  code/modules/food_and_drinks/food/snacks_pizza.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  code/modules/surgery/organs/tongue.dm
  icons/obj/food/food.dmi
Labels: Feature, Sprites, Fix, Server

#8811 MultiZ Modularization
  .github/CODEOWNERS
  beestation.dme
  code/__HELPERS/turfs.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/objects/structures.dm
  code/game/objects/structures/catwalk.dm
  code/game/objects/structures/lattice.dm
  code/game/turfs/open/openspace.dm
  code/game/turfs/turf.dm
  code/modules/antagonists/revenant/revenant_abilities.dm
  code/modules/mob/living/carbon/carbon_movement.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_movement.dm
  code/modules/multiz/look/living_zlook.dm
  code/modules/multiz/movement/atom/atom_zfall.dm
  code/modules/multiz/movement/atom/atom_zmove.dm
  code/modules/multiz/movement/atom/climbing.dm
  code/modules/multiz/movement/mob/carbon_zfall.dm
  code/modules/multiz/movement/mob/living_zfall.dm
  code/modules/multiz/movement/mob/living_zmove.dm
  code/modules/multiz/movement/turf/turf_zfall.dm
  code/modules/multiz/movement/turf/turf_zmove.dm
  code/modules/multiz/turf_multiz.dm
Labels: GitHub, Code Improvement

#8832 additional warning alert to when you put Bag of holding to another BoH
  code/datums/components/storage/concrete/bag_of_holding.dm
Labels: Feature

#8945 Makes changeling/abductor name code better & BB code nitpick
  code/game/gamemodes/changeling/changeling.dm
  code/game/objects/items/implants/implant_bb.dm
  code/modules/antagonists/abductor/abductor.dm
  code/modules/antagonists/brother/brother.dm
  code/modules/antagonists/changeling/changeling.dm
Labels: Code Improvement

#8968 Adds a VV option to give and remove mutations from carbons
  code/__DEFINES/vv.dm
  code/modules/mob/living/carbon/carbon.dm
Labels: Feature

#8903 Adds upgraded blood filtering surgery!
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/blood_filter.dm
Labels: Feature, Balance/Rebalance

#9020 Makes UI code use Ease-out transitions
  tgui/packages/tgui-panel/styles/components/Chat.scss
  tgui/packages/tgui/styles/components/Dropdown.scss
  tgui/packages/tgui/styles/components/Knob.scss
  tgui/packages/tgui/styles/components/ProgressBar.scss
  tgui/packages/tgui/styles/interfaces/AlertModal.scss
  tgui/packages/tgui/styles/interfaces/ListInput.scss
  tgui/packages/tgui/styles/layouts/TitleBar.scss
Labels: Feature, TGUI-Changes

#9021 Nerfs bunnysuit speedup
  code/modules/holiday/easter.dm
Labels: Balance/Rebalance

#9028 All species can now wag their tails if they get one.
  code/datums/mood_events/generic_negative_events.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/surgery/organs/tails.dm
Labels: Tweak, Refactor, Code Improvement

#8834 [PORT] Cortex Folding and Cortex Imprint surgeries
  beestation.dme
  code/__DEFINES/mobs.dm
  code/__DEFINES/traits.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/advanced/bioware/bioware.dm
  code/modules/surgery/advanced/bioware/cortex_folding.dm
  code/modules/surgery/advanced/bioware/cortex_imprint.dm
  code/modules/surgery/advanced/lobotomy.dm
Labels: Feature

#8881 Brand Intelligence event is no more miserable (mimic venders), makes mimic code a little better
  code/modules/antagonists/traitor/equipment/Malf_Modules.dm
  code/modules/events/brand_intelligence.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
Labels: Tweak, Code Improvement

#8882 Adjusts Sect Summon Flavor Text and adds poll ignore defines
  code/_globalvars/lists/poll_ignore.dm
  code/modules/religion/rites.dm
Labels: Tweak, Feature

#8901 You can now remove individual recipe recordings from chem dispensers.
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  tgui/packages/tgui/interfaces/ChemDispenser.js
Labels: Tweak, TGUI-Changes

#8900 Slightly adjusts virologists uplink viruses
  code/modules/uplink/uplink_items.dm
Labels: Balance/Rebalance, Removal

#9027 Refactors access system - access checking, desc, etc
  code/controllers/subsystem/job.dm
  code/datums/components/nanites.dm
  code/game/gamemodes/sandbox/h_sandbox.dm
  code/game/machinery/computer/card.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/fabricators/autolathe.dm
  code/game/machinery/requests_console.dm
  code/game/mecha/mecha_topic.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/storage/wallets.dm
  code/modules/admin/verbs/debug.dm
  code/modules/antagonists/highlander/highlander.dm
  code/modules/antagonists/roundstart_special/undercover/undercover.dm
  code/modules/awaymissions/corpse.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/clothing/outfits/vr.dm
  code/modules/clothing/outfits/vv_outfit.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/deputy.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/mining/machine_vending.dm
  code/modules/mining/minebot.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/bot/atmosbot.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
  code/modules/mob/living/simple_animal/bot/ed209bot.dm
  code/modules/mob/living/simple_animal/bot/firebot.dm
  code/modules/mob/living/simple_animal/bot/floorbot.dm
  code/modules/mob/living/simple_animal/bot/honkbot.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  code/modules/mob/living/simple_animal/bot/mulebot.dm
  code/modules/mob/living/simple_animal/bot/secbot.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  code/modules/mob/living/simple_animal/hostile/floor_cluwne.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/modular_computers/file_system/program.dm
  code/modules/modular_computers/file_system/programs/budgetordering.dm
  code/modules/modular_computers/file_system/programs/card.dm
  code/modules/modular_computers/file_system/programs/jobmanagement.dm
  code/modules/modular_computers/file_system/programs/robocontrol.dm
  code/modules/paperwork/contract.dm
  code/modules/paperwork/fax.dm
  code/modules/research/nanites/nanite_programs/utility.dm
  code/modules/shuttle/emergency.dm
  code/modules/shuttle/special.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/loot/alien_artifact.dm
Labels: Refactor, Administration, Code Improvement

#8938 Slight brain trauma refactor - nanites and viruses can no longer cure obsession or hypnosis
  code/__DEFINES/mobs.dm
  code/_globalvars/bitfields.dm
  code/datums/brain_damage/brain_trauma.dm
  code/datums/brain_damage/creepy_trauma.dm
  code/datums/brain_damage/hypnosis.dm
  code/datums/brain_damage/imaginary_friend.dm
  code/datums/brain_damage/mrat.dm
  code/datums/brain_damage/phobia.dm
  code/datums/brain_damage/severe.dm
  code/datums/brain_damage/special.dm
  code/datums/diseases/advance/symptoms/organs.dm
  code/datums/status_effects/debuffs.dm
  code/modules/assembly/flash.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/carbon/status_procs.dm
  code/modules/research/nanites/nanite_programs/healing.dm
Labels: Balance/Rebalance, Refactor

#8880 Oozelings can now extinguish people with hugs!
  code/modules/mob/living/carbon/human/species_types/oozelings.dm
Labels: Feature

#8831 admin can bypass no-respawn
  code/modules/mob/mob.dm
Labels: Feature, Tools, Code Improvement

#8717 Fixes processing of deleted objects in SSair
  code/controllers/subsystem/air.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/airlock_cycle_control.dm
  code/game/machinery/computer/atmos_control.dm
  code/game/machinery/spaceheater.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
  code/modules/atmospherics/machinery/other/meter.dm
  code/modules/atmospherics/machinery/portable/canister.dm
  code/modules/atmospherics/machinery/portable/portable_atmospherics.dm
  code/modules/atmospherics/machinery/portable/scrubber.dm
  code/modules/power/generator.dm
  code/modules/power/supermatter/supermatter.dm
Labels: Fix, Removal

#8851 changes naming/path toxin to plasma
  _maps/RandomRooms/10x10/sk_rdm088_bigconstruction.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  _maps/RandomRuins/SpaceRuins/TheDerelict.dmm
  _maps/RandomRuins/SpaceRuins/gasthelizards.dmm
  _maps/RandomRuins/SpaceRuins/spacedock13.dmm
  _maps/RandomZLevels/snowdin.dmm
  _maps/RuinGeneration/25x21_shuttleconstructionbay.dmm
  _maps/RuinGeneration/9x9_toxinstorage.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/GlowStation/GlowStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/shuttles/capsule/capsule_traitor.dmm
  _maps/shuttles/exploration/exploration_corg.dmm
  _maps/shuttles/exploration/exploration_delta.dmm
  _maps/shuttles/exploration/exploration_fland.dmm
  _maps/shuttles/exploration/exploration_shuttle.dmm
  _maps/shuttles/hunter/hunter_bounty.dmm
  _maps/shuttles/hunter/hunter_russian.dmm
  _maps/shuttles/hunter/hunter_space_cop.dmm
  code/__DEFINES/atmospherics.dm
  code/game/gamemodes/sandbox/h_sandbox.dm
  code/game/machinery/computer/atmos_control.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/modules/atmospherics/machinery/components/unary_devices/outlet_injector.dm
  code/modules/atmospherics/machinery/components/unary_devices/tank.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/other/miner.dm
  code/modules/atmospherics/machinery/portable/canister.dm
  code/modules/cargo/packs.dm
  code/modules/uplink/uplink_items.dm
Labels: Mapping, Code Improvement

#8838 CanPass refactor, fixes errors with CanPassThrough
  code/_onclick/adjacent.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/machinery/deployable.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/machinery/recycler.dm
  code/game/machinery/shieldgen.dm
  code/game/machinery/transformer.dm
  code/game/mecha/equipment/tools/medical_tools.dm
  code/game/mecha/mecha.dm
  code/game/objects/buckling.dm
  code/game/objects/effects/spiders.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/holosign.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/morgue.dm
  code/game/objects/structures/plasticflaps.dm
  code/game/objects/structures/railings.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/windoor_assembly.dm
  code/game/objects/structures/window.dm
  code/game/turfs/turf.dm
  code/modules/antagonists/blob/blob_mobs.dm
  code/modules/antagonists/blob/structures/_blob.dm
  code/modules/antagonists/revenant/revenant.dm
  code/modules/antagonists/swarmer/swarmer.dm
  code/modules/awaymissions/away_props.dm
  code/modules/events/spacevine.dm
  code/modules/fields/fields.dm
  code/modules/fields/peaceborg_dampener.dm
  code/modules/fields/turf_objects.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/mining/minebot.dm
  code/modules/mob/living/carbon/alien/humanoid/caste/hunter.dm
  code/modules/mob/living/living_movement.dm
  code/modules/mob/living/simple_animal/hostile/jungle/mook.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/curse_blob.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/elite.dm
  code/modules/plumbing/plumbers/grinder_chemical.dm
  code/modules/power/singularity/containment_field.dm
  code/modules/projectiles/guns/misc/medbeam.dm
  code/modules/projectiles/projectile.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/ruins/objects_and_mobs/necropolis_gate.dm
  code/modules/ruins/objects_and_mobs/sin_ruins.dm
  code/modules/spells/spell.dm
  code/modules/spells/spell_types/forcewall.dm
Labels: Fix

#9036 follow-up fix from access refactor PR
  code/modules/antagonists/highlander/highlander.dm
  code/modules/modular_computers/file_system/programs/card.dm
  tgui/packages/tgui/interfaces/common/AccessList.js
Labels: Fix, Code Improvement, TGUI-Changes

#8963 Replaces Tricordrazine in survival medipens with Regenerative Jelly
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Tweak

#9037 Makes the weathers look better
  icons/effects/weather_effects.dmi
Labels: Feature, Sprites

#9038 Adds a sound effect to the auto transfer vote, attempt 2
  code/controllers/subsystem/vote.dm
Labels: Feature, Sound

#8973 Soft removes bluespace body bag
  code/modules/cargo/bounties/science.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Balance/Rebalance, Removal

#9013 Improves chameleon card behaviour that can be affected by EMP or changeable by outfit selection when it's inside of a PDA
  code/modules/clothing/chameleon.dm
  code/modules/modular_computers/computers/item/tablet.dm
Labels: Tweak

#9039 Partly reverts the access check refactor PR #9027 #9036
  code/controllers/subsystem/job.dm
  code/game/gamemodes/sandbox/h_sandbox.dm
  code/game/machinery/computer/card.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/fabricators/autolathe.dm
  code/game/machinery/requests_console.dm
  code/game/mecha/mecha_topic.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/storage/wallets.dm
  code/modules/admin/verbs/debug.dm
  code/modules/antagonists/highlander/highlander.dm
  code/modules/antagonists/roundstart_special/undercover/undercover.dm
  code/modules/awaymissions/corpse.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/clothing/outfits/vr.dm
  code/modules/clothing/outfits/vv_outfit.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/deputy.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/mining/machine_vending.dm
  code/modules/mining/minebot.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/bot/atmosbot.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
  code/modules/mob/living/simple_animal/bot/ed209bot.dm
  code/modules/mob/living/simple_animal/bot/firebot.dm
  code/modules/mob/living/simple_animal/bot/floorbot.dm
  code/modules/mob/living/simple_animal/bot/honkbot.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  code/modules/mob/living/simple_animal/bot/mulebot.dm
  code/modules/mob/living/simple_animal/bot/secbot.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  code/modules/mob/living/simple_animal/hostile/floor_cluwne.dm
  code/modules/modular_computers/file_system/program.dm
  code/modules/modular_computers/file_system/programs/budgetordering.dm
  code/modules/modular_computers/file_system/programs/card.dm
  code/modules/modular_computers/file_system/programs/jobmanagement.dm
  code/modules/modular_computers/file_system/programs/robocontrol.dm
  code/modules/paperwork/contract.dm
  code/modules/paperwork/fax.dm
  code/modules/research/nanites/nanite_programs/utility.dm
  code/modules/shuttle/emergency.dm
  code/modules/shuttle/special.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/loot/alien_artifact.dm
  tgui/packages/tgui/interfaces/common/AccessList.js
Labels: Refactor, Administration, Code Improvement, TGUI-Changes

#9031 Fixes a possible case that a silicon can't state laws permanently
  code/modules/mob/living/silicon/silicon.dm
Labels: Fix

#9004 Adds new foodtype, GORE, split from GROSS. Shuffles tongue food preferences.
  code/__DEFINES/food.dm
  code/modules/food_and_drinks/food/snacks/meat.dm
  code/modules/food_and_drinks/food/snacks_burgers.dm
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/food_and_drinks/food/snacks_pastry.dm
  code/modules/food_and_drinks/food/snacks_soup.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/hostile/bees.dm
  code/modules/surgery/organs/organ_internal.dm
  code/modules/surgery/organs/tongue.dm
Labels: Feature, Balance/Rebalance

#9048 Fixes upgraded blood filtering surgery
  code/modules/surgery/blood_filter.dm
Labels: Feature, Fix

#8572 Introduces metabolites, tweaks basic medicine and medkits.
  beestation.dme
  code/datums/components/crafting/recipes.dm
  code/game/objects/items/stacks/medical.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/metabolites.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/surgery/organs/lungs.dm
Labels: Tweak, Feature, Balance/Rebalance, Code Improvement

#9047 Interrupting a martial arts granter last second no longer breaks it
  code/game/objects/items/granters.dm
Labels: Fix

#9003 Increases the time to cancel random events by 20 seconds, adds a sound that alerts admins and a preference toggle for it
  SQL/database_changelog.txt
  code/__DEFINES/preferences.dm
  code/game/gamemodes/dynamic/ruleset_picking.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_toggles.dm
  code/modules/events/_event.dm
  code/modules/events/fugitive_spawning.dm
  sound/effects/admin_alert.ogg
  sound/effects/license.txt
Labels: SQL, Tweak, Feature, Sound, Administration

#8988 Some more Chaplain QoL
  code/controllers/subsystem/explosion.dm
  code/datums/components/religious_tool.dm
  code/game/alternate_appearance.dm
  code/game/objects/empulse.dm
  code/game/turfs/turf.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/antagonists/revenant/revenant.dm
  code/modules/antagonists/revenant/revenant_abilities.dm
  code/modules/mob/mob_movement.dm
  code/modules/religion/rites.dm
  code/modules/spells/spell_types/ethereal_jaunt.dm
Labels: Tweak, Feature, Code Improvement

#9054 newfood icon hotfix
  code/game/objects/items/food/cake.dm
  code/game/objects/items/food/spaghetti.dm
  icons/obj/food/burgerbread.dmi
  icons/obj/food/food.dmi
  icons/obj/food/piecake.dmi
  icons/obj/food/pizzaspaghetti.dmi
  icons/obj/food/soupsalad.dmi
Labels: Tweak, Feature, Sprites, Fix

#9062 Fixes lattices not connecting to open turfs
  code/game/turfs/open/floor.dm
Labels: Feature, Fix

#8528 Rad station
  README.md
  _maps/_basemap.dm
  _maps/holodeck/meeting.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/map_files/RadStation/RadStation.dmm
  _maps/radstation.json
  _maps/shuttles/cargo/cargo_rad.dmm
  _maps/shuttles/exploration/exploration_rad.dmm
  _maps/shuttles/mining/mining_rad.dmm
  code/datums/shuttles.dm
  code/game/objects/effects/decals/turfdecal/guideline.dm
  code/game/objects/effects/decals/turfdecal/tilecoloring.dm
  code/game/objects/structures/signs/signs_departments.dm
  code/game/objects/structures/signs/signs_warning.dm
  code/game/shuttle_engines.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/holodeck/holodeck_map_templates.dm
  config/maps.txt
  icons/obj/4x7.dmi
  icons/obj/decals.dmi
  icons/turf/decals.dmi
Labels: Mapping, Needs Testmerge, Tweak, Feature, Sprites, Config Update

#9068 rad hotfixs
  _maps/map_files/RadStation/RadStation.dmm
Labels: Mapping, Tweak, Feature

#9011 Adds the syndicate surgery implant for 12 TC.
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/modules/antagonists/abductor/abductor.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/organs/augments_internal.dm
  code/modules/surgery/organs/autosurgeon.dm
  code/modules/surgery/surgery.dm
  code/modules/surgery/surgery_step.dm
  code/modules/uplink/uplink_items.dm
Labels: Tweak, Feature

#9077 Rad patches 2.0
  _maps/map_files/RadStation/RadStation.dmm
Labels: Mapping, Tweak, Feature, Fix, Removal

#9079 Removes one way road
  beestation.dme
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/_onclick/item_attack.dm
  code/modules/guardian/abilities/special/absolution.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Removal

#9088 Fix gender and skin tone DNA not properly applying
  code/datums/dna.dm
Labels: Fix

#9090 Removes the freebie Incursion radio implant
  code/game/objects/items/implants/implant_misc.dm
  code/modules/antagonists/incursion/incursion.dm
Labels: Balance/Rebalance

#9034 Orbit Panel Overhaul: Antag Icons, Collapsibility, Generic Theme
  code/modules/mob/dead/observer/orbit.dm
  tgui/packages/tgui/components/CollapsibleSection.js
  tgui/packages/tgui/interfaces/Orbit.js
  tgui/packages/tgui/styles/themes/generic.scss
Labels: Tweak, Feature, Fix, TGUI-Changes, Good PR

#9092 Fixes the "bad proc" SDQL runtime error when calling global procs
  code/modules/admin/verbs/SDQL2/SDQL_2.dm
Labels: Fix, Administration

#8897 The :^) has been removed from the tile_opposing_corners (and moved instead as it's own tile decal)
  beestation.dme
  code/game/objects/effects/decals/turfdecal/tilecoloring.dm
  code/game/objects/items/airlock_painter.dm
  icons/turf/decals.dmi
Labels: Tweak, Feature, Sprites

#9094 Fixes Void heretic cloak not hiding correctly
  code/modules/antagonists/heretic/items/heretic_armor.dm
Labels: Fix

#9095 Fixes lemonade reagent colour is wrongly black
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
Labels: Fix

#9084 Fixes a secbot runtime
  code/modules/mob/living/simple_animal/bot/secbot.dm
Labels: Fix

#9089 Prevents softlocking a vending machine with a Hand Drill
  code/modules/vending/_vending.dm
Labels: Fix

#9086 Fixes the cargo tagger sending parcels to the wrong destination
  code/_globalvars/lists/flavor_misc.dm
Labels: Fix

#9093 Fixes Heretic Void Robe Runtime
  code/modules/antagonists/heretic/items/heretic_armor.dm
Labels: Fix

#8969 Makes species be logged into the manifest log
  code/__HELPERS/_logging.dm
Labels: Feature, Administration

#9029 Potential fix for singularity eating itself
  code/datums/components/singularity.dm
  code/modules/power/singularity/singularity.dm
Labels: Fix

#9051 food reagent transfer runtime hotfix
  code/modules/food_and_drinks/food/snacks.dm
Labels: Fix

#9070 Readd tooltips to the R&D console
  code/modules/modular_computers/file_system/programs/techweb.dm
  code/modules/research/rdconsole.dm
  tgui/packages/tgui/interfaces/Techweb.js
Labels: Feature, TGUI-Changes

#9056 Cigarette lighting QoL
  code/game/objects/items/storage/fancy.dm
Labels: Feature

#9109 Removes armour from donator jumpsuit.
  code/modules/clothing/under/miscellaneous.dm
Labels: Balance/Rebalance

#9101 Fixes the recycler not working
  code/game/machinery/recycler.dm
Labels: Fix

#9074 Fixes orbit panel shows a mob twice
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_sentience.dm
Labels: Fix

#9127 Alt fix of "Fix orbit panel showing invalid job huds #9118"
  code/__HELPERS/jobs.dm
  code/modules/mob/dead/observer/orbit.dm
Labels: Fix

#9091 Splits node design IDs into multiple lines in alphabetical order with trailing commas
  code/modules/research/techweb/all_nodes.dm
Labels: Code Improvement

#9098 Renames 'Delimber' anomalies to 'Bioscrambler' anomalies + fixes unintended behavior
  beestation.dme
  code/__DEFINES/anomalies.dm
  code/game/objects/effects/anomalies.dm
  code/modules/assembly/signaler.dm
  code/modules/clothing/suits/reactive_armour.dm
  code/modules/events/anomaly_bioscrambler.dm
  code/modules/events/anomaly_delimber.dm
  code/modules/power/supermatter/supermatter.dm
  icons/effects/effects.dmi
Labels: Tweak, Sprites, Fix, Administration, Removal

#9104 Limits Nar'Sie Plush cheese alternative
  code/game/objects/items/plushes.dm
  code/modules/antagonists/cult/runes.dm
Labels: Balance/Rebalance

#8853 Sets cyborg total positions to 1
  code/modules/jobs/job_types/cyborg.dm
Labels: Tweak, Vote Passed

#8362 Fixes cyborg roleban exploit with robot factories
  code/modules/mob/transform_procs.dm
Labels: Feature

#9117 [PORT] Silicon Station Alert TGUI and minor fixes!
  beestation.dme
  code/_onclick/hud/ai.dm
  code/_onclick/hud/robot.dm
  code/datums/alarm.dm
  code/datums/station_alert.dm
  code/game/machinery/computer/station_alert.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/modular_computers/file_system/programs/alarm.dm
  tgui/packages/tgui/interfaces/NtosStationAlertConsole.js
  tgui/packages/tgui/interfaces/StationAlertConsole.js
Labels: Feature, Fix, Refactor, TGUI-Changes

#9099 Rad patches 3.0
  _maps/map_files/RadStation/RadStation.dmm
  _maps/shuttles/cargo/cargo_rad.dmm
  _maps/shuttles/exploration/exploration_rad.dmm
  _maps/shuttles/labour/labour_box.dmm
  _maps/shuttles/labour/labour_corg.dmm
  _maps/shuttles/labour/labour_kilo.dmm
  code/game/objects/structures/watercloset.dm
Labels: Mapping, Tweak, Feature, Fix, Removal, Server
