Repository BeeStation/BeeStation-Hornet, pull requests merged in 2024-08, with the labels that each got.

#11266 Fix checker tiles
  code/game/objects/items/stacks/tiles/tile_iron.dm
  code/game/turfs/open/floor/iron_floor.dm
Labels: Fix

#11234 Made electric vehicles no longer ignore EMPs
  code/datums/components/riding.dm
  code/modules/vehicles/atv.dm
  code/modules/vehicles/motorized_wheelchair.dm
  code/modules/vehicles/pimpin_ride.dm
  code/modules/vehicles/secway.dm
Labels: Balance/Rebalance

#11276 Fixed Cerulean Pylon's polycrystal spawning logic
  code/modules/research/xenobiology/crossbreeding/_structures.dm
Labels: Tweak

#11262 Fixes time freezing once and for all
  code/__DEFINES/explosions.dm
  code/controllers/subsystem/explosion.dm
  code/datums/components/explodable.dm
  code/datums/materials/basemats.dm
Labels: Priority: Critical, Test Merged, Fix

#11278 Adds baystation border & techfloor decals
  _maps/Prefab/Departments.dmm
  _maps/RandomRooms/10x10/rdm_organ_harvesting.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_seed_vault.dmm
  _maps/shuttles/hunter/hunter_bounty.dmm
  _maps/shuttles/pirate/pirate_default.dmm
  code/game/objects/effects/decals/turfdecal/markings.dm
  code/game/objects/effects/decals/turfdecal/tilecoloring.dm
  icons/turf/decals.dmi
Labels: Mapping, Sprites

#11275 Random Fixes: Nullspace mech, Mining Mech Spawn rate, and a random extra FALSE statement
  code/modules/atmospherics/machinery/pipes/layermanifold.dm
  code/modules/shuttle/white_ship.dm
  code/modules/vehicles/mecha/working/ripley.dm
Labels: Fix

#9802 Buckling check cleanup & documentation. Removes a snowflake buckle with cyborgs
  code/game/objects/buckling.dm
  code/game/turfs/open/lava.dm
  code/modules/awaymissions/mission_code/snowdin.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/surgery/organs/wings.dm
Labels: Balance/Rebalance, Code Improvement

#10160 Sprite smoothing + Map Debugging QoL tool
  _maps/map_files/debug/multidir_sprite_debug.dmm
  code/__DEFINES/maps.dm
  code/__HELPERS/icon_smoothing.dm
  code/__HELPERS/level_traits.dm
  code/game/objects/items/debug_items.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/mining/lavaland/necropolis_chests.dm
Labels: Mapping, Feature

#10322 New mapping helper: Spaceproof/Group directional windows, new maint room
  _maps/RandomRooms/10x10/sk_rdm176_spacewindowroom.dmm
  code/game/objects/effects/spawners/roomspawner.dm
  code/modules/mapping/mapping_helpers.dm
  code/modules/mapping/random_rooms.dm
  icons/effects/mapping_helpers.dmi
Labels: Mapping, Sprites

#10536 Fixes cases of players getting sent to lobby, preference runtimes, & cleans up split personality checks
  code/datums/brain_damage/imaginary_friend.dm
  code/datums/brain_damage/split_personality.dm
  code/modules/antagonists/blob/overmind.dm
  code/modules/antagonists/clock_cult/mobs/clockwork_marauder.dm
  code/modules/antagonists/clock_cult/mobs/eminence.dm
  code/modules/antagonists/devil/true_devil/_true_devil.dm
  code/modules/antagonists/revenant/revenant.dm
  code/modules/holoparasite/_holoparasite.dm
  code/modules/mob/dead/dead.dm
  code/modules/mob/dead/new_player/login.dm
  code/modules/mob/dead/observer/login.dm
  code/modules/mob/living/carbon/alien/login.dm
  code/modules/mob/living/login.dm
  code/modules/mob/living/silicon/ai/login.dm
  code/modules/mob/living/silicon/login.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/robot/login.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  code/modules/mob/living/simple_animal/friendly/drone/extra_drone_types.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/mob/login.dm
Labels: Tweak, Fix, Code Improvement

#11006 Stun resistance from working out
  beestation.dme
  code/datums/status_effects/buffs.dm
  code/game/objects/structures/gym/exercise_status.dm
  code/game/objects/structures/gym/punching_bag.dm
  code/game/objects/structures/gym/weight_machine.dm
  code/modules/mob/living/carbon/human/physiology.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/pool/components/swimming.dm
  icons/mob/screen_alert.dmi
Labels: Sprites, Balance/Rebalance

#11014 Adjusts armour values for alternate security armour options
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/wintercoats.dm
Labels: Balance/Rebalance

#11186 Ports datumized security levels & converts to Subsytem
  beestation.dme
  code/__DEFINES/dcs/signals/signals_datum/signals_datum.dm
  code/__DEFINES/dcs/signals/signals_global.dm
  code/__DEFINES/shuttles.dm
  code/__DEFINES/subsystems.dm
  code/__HELPERS/priority_announce.dm
  code/controllers/subsystem/nightshift.dm
  code/controllers/subsystem/security_level.dm
  code/controllers/subsystem/shuttle.dm
  code/datums/world_topic.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/gangs/dominator.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/defibrillator_mount.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/firealarm.dm
  code/game/objects/structures/displaycase.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/antagonists/blob/overmind.dm
  code/modules/antagonists/clock_cult/clockwork_massive.dm
  code/modules/antagonists/clock_cult/helpers/clockcult_ending.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/antagonists/cult/narsie.dm
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
  code/modules/antagonists/traitor/equipment/Malf_Modules.dm
  code/modules/events/asteroid_impact.dm
  code/modules/mob/living/silicon/ai/death.dm
  code/modules/mob/mob_stat.dm
  code/modules/security_levels/keycard_authentication.dm
  code/modules/security_levels/security_level_datums.dm
  code/modules/security_levels/security_levels.dm
  code/modules/shuttle/emergency.dm
  code/modules/shuttle/shuttle.dm
  code/modules/unit_tests/security_levels.dm
Labels: Feature, Administration, Code Improvement

#10750 Chemical factories: Medical usage edition
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  beestation.dme
  code/game/objects/items/RCD.dm
  code/modules/plumbing/plumbers/bottle_dispenser.dm
  code/modules/plumbing/plumbers/patch_dispenser.dm
  code/modules/plumbing/plumbers/pill_press.dm
  code/modules/plumbing/plumbers/synthesizer.dm
  tgui/packages/tgui/interfaces/BottleDispenser.js
  tgui/packages/tgui/interfaces/ChemPress.js
  tgui/packages/tgui/interfaces/PatchDispenser.js
Labels: Mapping, Tweak, Fix, Balance/Rebalance, Removal, TGUI-Changes

#11093 Medical scanners now show missing organs
  code/game/objects/items/devices/scanners.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Tweak

#11291 Removes erp (for a third time)
  code/game/objects/items/food/meatdish.dm
Labels: Removal

#11294 Revert "Medical scanners now show missing organs"
  code/game/objects/items/devices/scanners.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Removal

#11236 Fixes monkeys teleporting while chasing things or people
  code/modules/movespeed/_movespeed_modifier.dm
Labels: Fix

#11242 Makes humans indomitable. (Adds a single non-gameplay changing perk to humans)
  code/modules/mob/living/carbon/human/species_types/humans.dm
Labels: Feature

#11067 Kilo Radification
  _maps/map_files/KiloStation/KiloStation.dmm
  code/game/area/Space_Station_13_areas.dm
Labels: Mapping, Tweak, Feature, Fix, Balance/Rebalance, Removal

#11069 Adds Pepper Sprays to Box Brig and Adds a Shortcut for Atmospherics
  _maps/map_files/BoxStation/BoxStation.dmm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
Labels: Mapping, Tweak, Feature, Fix

#11113 Adds a tip about "Supermatter SLIVER" for random individual vocabulary
  strings/sillytips.txt
Labels: Feature

#11274 [Revival] Ports the smart pipes mapping helper
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/debug/runtimestation.dmm
  code/modules/atmospherics/machinery/pipes/mapping.dm
  code/modules/mapping/mapping_helpers.dm
  icons/effects/mapping_helpers.dmi
  tools/ci/check_grep.sh
Labels: Mapping, Feature, Sprites, Fix, Tools

#11304 A tiny bundle of one-liner fixes/optimizations (Roundstart Runtimes)
  _maps/map_files/FlandStation/FlandStation.dmm
  code/game/machinery/doors/airlock.dm
  code/modules/clothing/head/helmet.dm
Labels: Mapping, Fix, Code Improvement

#11301 Moves security techfab to the wardens office
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/EchoStation/EchoStation.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
Labels: Mapping, Tweak, Balance/Rebalance, Vote Passed

#10474 WORKING Directional Lighting in 2024
  beestation.dme
  code/__DEFINES/dcs/signals/signals_atom/signals_atom.dm
  code/__DEFINES/dcs/signals/signals_lighting.dm
  code/__DEFINES/layers.dm
  code/__DEFINES/lighting.dm
  code/datums/components/overlay_lighting.dm
  code/datums/mutations/body.dm
  code/game/atoms_movable.dm
  code/game/objects/effects/lighting.dm
  code/game/objects/effects/misc.dm
  code/game/objects/effects/overlays.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/turfs/change_turf.dm
  code/modules/antagonists/clock_cult/scriptures/kindle.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/atmospherics/environmental/LINDA_fire.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/lighting/lighting_atom.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/update_icons.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/modular_computers/computers/item/computer.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  code/modules/research/xenobiology/xenobiology.dm
  code/modules/surgery/organs/heart.dm
  code/modules/wiremod/shell/compact_remote.dm
  code/modules/wiremod/shell/controller.dm
  code/modules/wiremod/shell/drone.dm
  code/modules/wiremod/shell/scanner.dm
  icons/effects/light_overlays/light_cone.dmi
Labels: Mapping, Feature, Sprites, Refactor, Sound, Tools, Testmerge Passed

#11259 Fixed Cheap Lighters not Burning You
  code/game/objects/items/cigs_lighters.dm
Labels: Fix

#11287 AIs and Cyborgs can now change their camera size
  code/_onclick/ai.dm
  code/_onclick/cyborg.dm
  code/_onclick/pai.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/modular_computers/file_system/programs/borg_self_monitor.dm
  code/modules/modular_computers/file_system/programs/ntmessenger.dm
  tgui/packages/tgui/interfaces/NtosCyborgSelfMonitor.js
  tgui/packages/tgui/interfaces/NtosMessenger.js
Labels: Feature, TGUI-Changes

#11106 Replaces PTSD with service/officer pistols
  code/game/machinery/recharger.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/projectiles/ammunition/caseless/misc.dm
  code/modules/projectiles/boxes_magazines/external/rechargable.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
  code/modules/projectiles/projectile/beams.dm
  icons/mob/clothing/belt.dmi
  icons/obj/ammo.dmi
  icons/obj/guns/energy.dmi
  icons/obj/guns/projectile.dmi
  icons/obj/projectiles.dmi
Labels: Sprites, Fix, Balance/Rebalance

#11192 [PORT] improvements to the nightvision code and mobs can't longer read in the dark
  code/__DEFINES/fov.dm
  code/__DEFINES/lighting.dm
  code/datums/traits/negative_quirk.dm
  code/modules/antagonists/blob/blob_mobs.dm
  code/modules/antagonists/blob/overmind.dm
  code/modules/antagonists/clock_cult/mobs/eminence.dm
  code/modules/antagonists/devil/imp/imp.dm
  code/modules/antagonists/morph/morph.dm
  code/modules/antagonists/revenant/revenant.dm
  code/modules/antagonists/slaughter/slaughter.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/mob/living/simple_animal/hostile/heart.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/mining_mobs.dm
  code/modules/mob/living/simple_animal/hostile/skeleton.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  code/modules/mob/mob.dm
  code/modules/surgery/organs/eyes.dm
Labels: Tweak, Code Improvement

#11197 Fixed IPC healing bug
  code/datums/elements/mechanical_repair.dm
  code/modules/mob/mob_helpers.dm
Labels: Fix, Balance/Rebalance, Removal

#11029 Removes unused armor flag
  code/__DEFINES/combat.dm
  code/datums/armor.dm
  code/modules/clothing/clothing.dm
  code/modules/projectiles/guns/magic/staff.dm
  code/modules/projectiles/projectile/magic.dm
Labels: Code Improvement

#11270 Gasses and fire resprite
  icons/effects/atmospherics.dmi
  icons/effects/fire.dmi
Labels: Feature, Sprites

#11057 Medbots will now bandage bleeding patients
  code/modules/mob/living/simple_animal/bot/medbot.dm
Labels: Mapping, Feature, Sprites, Sound, Tools

#11267 AI Vox sound effects, alarms, a chime, etc.
  code/modules/mob/living/silicon/ai/say.dm
  code/modules/mob/living/silicon/ai/vox_sounds.dm
  sound/vox_fem/licensing credits.txt
  sound/vox_fem/soundairhorn.ogg
  sound/vox_fem/soundalarm1.ogg
  sound/vox_fem/soundalarm2.ogg
  sound/vox_fem/soundannounce.ogg
  sound/vox_fem/soundcensor.ogg
  sound/vox_fem/soundhonk.ogg
  sound/vox_fem/soundwhitenoise.ogg
Labels: Tweak, Feature, Sound

#10837 Fixes DB queries having unnecessary delayed starts
  code/controllers/subsystem/dbcore.dm
  code/modules/admin/admin.dm
  code/modules/metacoin/metacoin.dm
Labels: Fix, Administration, Removal, Priority: High

#11315 Tweaks Service Pistol stats
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/projectiles/boxes_magazines/external/rechargable.dm
  code/modules/projectiles/projectile/beams.dm
  icons/obj/ammo.dmi
Labels: Tweak, Sprites, Balance/Rebalance

#10986 Ports the Clarke Mecha from TG
  _maps/RandomRuins/SpaceRuins/Fast_Food.dmm
  _maps/RandomRuins/SpaceRuins/mechtransport.dmm
  _maps/RandomZLevels/SnowCabin.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  beestation.dme
  code/__DEFINES/mecha.dm
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/elements/series.dm
  code/datums/traits/negative_quirk.dm
  code/game/machinery/computer/arcade.dm
  code/game/machinery/fabricators/exosuit_fab.dm
  code/game/objects/items/manuals.dm
  code/game/objects/items/toys.dm
  code/game/turfs/open/floor.dm
  code/game/turfs/open/floor/plating/asteroid.dm
  code/modules/admin/verbs/debug.dm
  code/modules/cargo/bounties/mech.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/clothing/head/collectable.dm
  code/modules/holiday/easter.dm
  code/modules/mining/abandoned_crates.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  code/modules/research/designs/autolathe_designs.dm
  code/modules/research/designs/mecha_designs.dm
  code/modules/research/designs/mechfabricator_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/station_goals/bluespace_tap.dm
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
  code/modules/vehicles/mecha/mecha_construction_paths.dm
  code/modules/vehicles/mecha/mecha_parts.dm
  code/modules/vehicles/mecha/mecha_wreckage.dm
  code/modules/vehicles/mecha/working/clarke.dm
  code/modules/vehicles/mecha/working/ripley.dm
  code/modules/vehicles/mecha/working/working.dm
  icons/mecha/mech_construct.dmi
  icons/mecha/mecha.dmi
  icons/mecha/mecha_equipment.dmi
  icons/obj/toy.dmi
Labels: Mapping, Tweak, Feature, Sprites, Removal

#11317 fix mech construction states
  icons/mecha/mech_construction.dmi
Labels: Sprites, Fix

#10782 Wounds Atomization: repairing clothes
  code/__DEFINES/obj_flags.dm
  code/__HELPERS/type2type.dm
  code/_onclick/item_attack.dm
  code/datums/traits/negative_quirk.dm
  code/game/objects/obj_defense.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/clothing/gloves/_gloves.dm
  code/modules/clothing/head/_head.dm
  code/modules/clothing/masks/_masks.dm
  code/modules/clothing/shoes/_shoes.dm
  code/modules/clothing/spacesuits/_spacesuits.dm
  code/modules/clothing/suits/_suits.dm
  code/modules/clothing/under/_under.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/ninja/suit/gloves.dm
Labels: Feature, Balance/Rebalance, Priority: High, Testmerge Passed, Strategic Milestone

#11201 Buffs breaching tools
  code/datums/wires/_wires.dm
  code/datums/wires/airalarm.dm
  code/datums/wires/airlock.dm
  code/datums/wires/airlock_cycle.dm
  code/datums/wires/apc.dm
  code/datums/wires/autolathe.dm
  code/datums/wires/dna_scanner.dm
  code/datums/wires/ecto_sniffer.dm
  code/datums/wires/explosive.dm
  code/datums/wires/fax.dm
  code/datums/wires/microwave.dm
  code/datums/wires/particle_accelerator.dm
  code/datums/wires/r_n_d.dm
  code/datums/wires/robot.dm
  code/datums/wires/suit_storage_unit.dm
  code/datums/wires/syndicatebomb.dm
  code/datums/wires/vending.dm
  code/game/gamemodes/gangs/dominator.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/machinery/syndicatebomb.dm
  code/game/objects/items/crab17.dm
  code/game/objects/items/devices/paicard.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/weaponry.dm
  code/game/objects/obj_defense.dm
  code/game/objects/objs.dm
  code/game/objects/structures/grille.dm
  code/modules/antagonists/blob/structures/core.dm
  code/modules/antagonists/blob/structures/factory.dm
  code/modules/antagonists/blob/structures/node.dm
  code/modules/antagonists/clock_cult/clockwork_massive.dm
  code/modules/antagonists/space_dragon/carp_rift.dm
  code/modules/holoparasite/abilities/lesser/radio.dm
  code/modules/mob/living/simple_animal/bot/mulebot.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
  code/modules/wiremod/shell/airlock.dm
Labels: Tweak, Fix, Balance/Rebalance

#11326 1 line fix for cardboard boxes
  code/game/objects/structures/crates_lockers/closets/cardboardbox.dm
Labels: Feature, Fix

#11325 Gave the syndicate bomb a balloon alert for indicating the remaining time until explosion
  code/game/machinery/syndicatebomb.dm
Labels: Feature

#11320 fixes buckling adjacency
  code/game/objects/buckling.dm
Labels: Fix

#11271 Adds a cover lock for fire alarms, makes fire alarms trip the lock when a fire is encountered
  code/game/machinery/firealarm.dm
  icons/obj/monitors.dmi
Labels: Feature, Sprites, Balance/Rebalance

#11323 experimental stamina fix
  code/modules/mob/living/carbon/carbon.dm
Labels: Fix

#11150 Replaces the escape pod shuttle
  _maps/map_files/generic/CentCom.dmm
  code/modules/cargo/packs.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  icons/mob/pets.dmi
Labels: Mapping, Feature, Sprites, Fix

#11330 Lets cyborgs close morgues with the tray and restores some old behaviour
  code/game/objects/structures/morgue.dm
Labels: Fix

#10730 (recoup) Spatial gridmap take 3
  beestation.dme
  code/__DEFINES/dcs/signals/signals_global.dm
  code/__DEFINES/dcs/signals/signals_mob/signals_mob.dm
  code/__DEFINES/dcs/signals/signals_spatial_grid.dm
  code/__DEFINES/important_recursive_contents.dm
  code/__DEFINES/radio.dm
  code/__DEFINES/spatial_gridmap.dm
  code/__DEFINES/subsystems.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/game.dm
  code/__HELPERS/spatial_info.dm
  code/controllers/subsystem/spatial_gridmap.dm
  code/datums/datum.dm
  code/datums/holocall.dm
  code/datums/wires/radio.dm
  code/game/atoms_movable.dm
  code/game/machinery/bank_machine.dm
  code/game/machinery/computer/arcade.dm
  code/game/machinery/doors/brigdoors.dm
  code/game/machinery/hologram.dm
  code/game/machinery/requests_console.dm
  code/game/machinery/telecomms/broadcasting.dm
  code/game/machinery/telecomms/machine_interactions.dm
  code/game/machinery/telecomms/machines/broadcaster.dm
  code/game/machinery/telecomms/machines/bus.dm
  code/game/machinery/telecomms/machines/hub.dm
  code/game/machinery/telecomms/machines/message_server.dm
  code/game/machinery/telecomms/machines/processor.dm
  code/game/machinery/telecomms/machines/receiver.dm
  code/game/machinery/telecomms/machines/relay.dm
  code/game/machinery/telecomms/machines/server.dm
  code/game/machinery/telecomms/telecomunications.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/intercom.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/robot/ai_upgrades.dm
  code/game/say.dm
  code/modules/antagonists/clock_cult/mobs/eminence.dm
  code/modules/antagonists/traitor/equipment/Malf_Modules.dm
  code/modules/client/client_procs.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/mapping/reader.dm
  code/modules/mapping/space_management/zlevel_manager.dm
  code/modules/mining/laborcamp/laborstacker.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/brain/MMI.dm
  code/modules/mob/living/carbon/human/species_types/dullahan.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/login.dm
  code/modules/mob/logout.dm
  code/modules/mob/mob.dm
  code/modules/paperwork/fax.dm
  code/modules/power/supermatter/supermatter.dm
  code/modules/projectiles/projectile.dm
  code/modules/security/genpop.dm
  code/modules/vehicles/mecha/mecha_topic.dm
Labels: Code Improvement

#11286 Bluespace cannon update
  code/game/objects/effects/effect_system/effects_sparks.dm
  code/modules/power/power.dm
  code/modules/power/terminal.dm
  code/modules/station_goals/bsa.dm
  icons/obj/lavaland/cannon.dmi
  sound/machines/bsa/bsa_charge.ogg
  sound/machines/bsa/bsa_fire.ogg
  tgui/packages/tgui/interfaces/BluespaceArtillery.js
Labels: Feature, Sprites, Balance/Rebalance, Sound, TGUI-Changes

#11139 FloorCluwne Smites - Adds TraumaCluwne, and Fixes Stalker
  beestation.dme
  code/modules/admin/smites/floorcluwne_stalker.dm
  code/modules/admin/smites/floorcluwne_trauma.dm
  code/modules/mob/living/simple_animal/hostile/floor_cluwne.dm
Labels: Feature, Fix, Administration

#11353 Fixes FastDMM2 Compatibility
  code/modules/mapping/mapping_helpers.dm
Labels: Fix

#11334 Fixes subsystems warnings
  code/__DEFINES/subsystems.dm
  code/controllers/subsystem/blackbox.dm
  code/controllers/subsystem/movement/zfall.dm
  code/controllers/subsystem/natural_light_cycle.dm
  code/controllers/subsystem/spatial_gridmap.dm
  code/modules/elevator/elevator_controller.dm
Labels: Fix, Code Improvement

#11347 fix capitalization in uplink
  code/modules/uplink/uplink_items.dm
Labels: Fix, Grammar and Formatting

#11354 Removes LAssailant
  code/game/objects/items/melee/misc.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/slime/life.dm
  code/modules/mob/mob_defines.dm
  code/modules/recycling/disposal/bin.dm
  code/modules/research/xenobiology/xenobio_camera.dm
Labels: Code Improvement

#11358 Ports sushi and adds seafood crafting tab
  beestation.dme
  code/__DEFINES/construction.dm
  code/datums/components/crafting/crafting.dm
  code/game/objects/items/food/misc.dm
  code/game/objects/items/food/salad.dm
  code/game/objects/items/food/sushi.dm
  code/game/objects/items/storage/bags.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/food_and_drinks/recipes/food_mixtures.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_egg.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_seafood.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_soup.dm
  code/modules/research/designs/biogenerator_designs.dm
  icons/obj/food/food.dmi
  icons/obj/food/food_ingredients.dmi
  icons/obj/food/sushi.dmi
Labels: Feature, Sprites, Balance/Rebalance

#11343 Fixes changeling antagonist information panel, now shows their objectives.
  tgui/packages/tgui/interfaces/AntagInfoChangeling.tsx
Labels: TGUI-Changes

#11360 Replaces "yiff"
  strings/owo_talk.json
Labels: Code Improvement

#11312 Removes sleep() from Zfall
  code/modules/multiz/movement/turf/turf_zfall.dm
Labels: Code Improvement

#11282 Fixes VV bodypart editor after 3 years
  code/modules/mob/living/carbon/carbon.dm
Labels: Fix

#11351 Fixes runtimes when eminances are damaged
  code/game/data_huds.dm
  code/modules/antagonists/clock_cult/mobs/eminence.dm
Labels: Fix, Code Improvement

#11352 Makes the Atmospherics-Maintenance Airlock Bridge No Longer Space Maintenance
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Mapping, Fix

#11283 Modsuit Prep: RCD deconstruction scan
  beestation.dme
  code/__DEFINES/construction.dm
  code/__HELPERS/construction.dm
  code/__HELPERS/icons.dm
  code/game/objects/effects/spawners/structure.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/RCD.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/grille.dm
  code/game/turfs/change_turf.dm
  code/game/turfs/closed/wall/misc_walls.dm
  code/game/turfs/closed/walls.dm
  code/game/turfs/open/floor.dm
  code/game/turfs/turf.dm
  code/modules/antagonists/clock_cult/clockwork_turfs.dm
  sound/items/rcdscan.ogg
Labels: Feature, Fix, Balance/Rebalance, Sound

#11311 Potentially fixes book cases
  code/modules/library/lib_items.dm
Labels: Fix, Testmerge Passed

#11331 Echo fixes 2
  _maps/map_files/EchoStation/EchoStation.dmm
  code/game/objects/effects/landmarks.dm
  code/modules/events/operative.dm
  code/modules/shuttle/shuttle_creation/shuttle_creator.dm
  icons/effects/landmarks_static.dmi
Labels: Mapping, Feature, Sprites, Fix

#11349 Mechs forcefully eject their occupants when destroyed
  code/datums/components/chasm.dm
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/mecha/combat/combat.dm
  code/modules/vehicles/mecha/combat/gygax.dm
  code/modules/vehicles/mecha/combat/marauder.dm
Labels: Mapping, Tweak, Fix, Code Improvement

#11375 Creates a disposal pipe that filters items that haven't found a valid sorting pipe
  code/game/objects/items/RPD.dm
  code/modules/recycling/disposal/holder.dm
  code/modules/recycling/disposal/pipe_sorting.dm
Labels: Tweak, Feature, Code Improvement, Priority: High

#11361 [Port] Movetype refactor
  beestation.dme
  code/__DEFINES/dcs/signals/signals_movable.dm
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/components/caltrop.dm
  code/datums/components/chasm.dm
  code/datums/elements/movetype_handler.dm
  code/game/atoms_movable.dm
  code/game/objects/buckling.dm
  code/game/objects/structures/life_candle.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/antagonists/blob/blob_mobs.dm
  code/modules/antagonists/clock_cult/mobs/clockwork_marauder.dm
  code/modules/antagonists/clock_cult/mobs/eminence.dm
  code/modules/antagonists/clock_cult/traps/receivers/skewer.dm
  code/modules/antagonists/clock_cult/traps/senders/pressure_sensor.dm
  code/modules/antagonists/revenant/revenant.dm
  code/modules/antagonists/revenant/revenant_abilities.dm
  code/modules/holoparasite/_holoparasite.dm
  code/modules/mining/equipment/wormhole_jaunter.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/basic/basic.dm
  code/modules/mob/living/carbon/alien/humanoid/caste/hunter.dm
  code/modules/mob/living/carbon/carbon_movement.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/update_icons.dm
  code/modules/mob/living/init_signals.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/friendly/butterfly.dm
  code/modules/mob/living/simple_animal/hostile/bees.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/eyeballs.dm
  code/modules/mob/living/simple_animal/hostile/jungle/leaper.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/basilisk.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/curse_blob.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/herald.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/bat.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/ghost.dm
  code/modules/mob/living/simple_animal/hostile/space_dragon.dm
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/living/simple_animal/shade.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/living/ventcrawling.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_helpers.dm
  code/modules/surgery/organs/augments_chest.dm
Labels: Fix, Refactor, Administration, Priority: High

#11379 Movement Refactor fixes
  code/__DEFINES/traits.dm
  code/datums/components/orbiter.dm
  code/modules/antagonists/blob/blob_mobs.dm
  code/modules/antagonists/clock_cult/mobs/eminence.dm
  code/modules/holoparasite/_holoparasite.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/hostile/bees.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/curse_blob.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/herald.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/bat.dm
  code/modules/mob/living/simple_animal/hostile/space_dragon.dm
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Fix

#11385 Multple ghosts can now once more orbit the same person.
  code/modules/mob/dead/observer/observer.dm
Labels: Fix

#11303 Delta Science Doors Fix
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Mapping, Tweak, Fix, Code Improvement

#11387 Fixes simplemobs being able to interact with machinery
  code/game/machinery/_machinery.dm
Labels: Fix

#10983 Server framework v2
  _maps/map_files/EchoStation/EchoStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  beestation.dme
  code/__DEFINES/dcs/signals/signals_obj/signals_machine/signals_machinery.dm
  code/__DEFINES/networks.dm
  code/__DEFINES/stat.dm
  code/controllers/subsystem/processing/servers.dm
  code/controllers/subsystem/research.dm
  code/datums/components/ntnet_interface.dm
  code/datums/components/server.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/telecomms/computers/telemonitor.dm
  code/game/machinery/telecomms/machine_interactions.dm
  code/game/machinery/telecomms/machines/broadcaster.dm
  code/game/machinery/telecomms/machines/bus.dm
  code/game/machinery/telecomms/machines/hub.dm
  code/game/machinery/telecomms/machines/message_server.dm
  code/game/machinery/telecomms/machines/processor.dm
  code/game/machinery/telecomms/machines/receiver.dm
  code/game/machinery/telecomms/machines/relay.dm
  code/game/machinery/telecomms/machines/server.dm
  code/game/machinery/telecomms/telecomunications.dm
  code/modules/power/power.dm
  code/modules/research/server.dm
  tgui/packages/tgui/interfaces/Telemonitor.tsx
Labels: Mapping, Tweak, Feature, Fix, Server, TGUI-Changes, Testmerge Passed

#11366 Gibtonite flashes again
  icons/turf/smoothrocks.dmi
Labels: Sprites, Fix

#11391 Edited some FLYING checks to also check for FLOATING
  code/datums/components/conveyor_movement.dm
  code/datums/components/slippery.dm
  code/datums/components/spikes.dm
  code/datums/components/squashable.dm
  code/datums/elements/footstep.dm
  code/datums/weather/weather_types/floor_is_lava.dm
  code/game/objects/effects/alien_acid.dm
  code/game/objects/effects/mainttraps.dm
  code/game/objects/structures/tables_racks.dm
  code/game/turfs/open/_open.dm
  code/game/turfs/open/lava.dm
  code/game/turfs/turf.dm
  code/modules/assembly/mousetrap.dm
  code/modules/awaymissions/mission_code/snowdin.dm
  code/modules/mob/living/carbon/carbon_movement.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/multiz/movement/atom/atom_zfall.dm
Labels: Fix

#11405 RuntimeStation mapping fixes
  _maps/map_files/debug/runtimestation.dmm
Labels: Mapping, Fix

#11218 DeltaStation2 New Brig (and minor fixes/adjustments - Fluked PR edition
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Mapping, Feature, Fix

#11404 Heirloom changes for medical
  code/datums/traits/negative_quirk.dm
Labels: Tweak
