Repository BeeStation/BeeStation-Hornet, pull requests merged in 2024-12, with the labels that each got.

#11928 Ninja dojo newfood
  _maps/map_files/generic/CentCom.dmm
Labels: Mapping, Feature

#11910 NTNet relay on runtime station
  _maps/map_files/debug/runtimestation.dmm
Labels: Mapping, Feature

#11927 Science lootdrop changes
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/mapping.dm
Labels: Tweak

#11955 Alien Weed Fix.
  code/game/objects/structures/aliens.dm
Labels: Fix

#11963 Adds a Better Warning to the RBMK Fuel Rod Crate
  code/modules/cargo/packs.dm
Labels: Tweak

#11965 removes references to polycrystals
  code/modules/research/xenobiology/crossbreeding/charged.dm
Labels: Fix

#11617 [Port] Emote Update
  beestation.dme
  code/__DEFINES/say.dm
  code/__DEFINES/species.dm
  code/_globalvars/bitfields.dm
  code/datums/emotes.dm
  code/modules/asset_cache/asset_list.dm
  code/modules/client/preferences/middleware/antags.dm
  code/modules/client/preferences/middleware/species.dm
  code/modules/clothing/masks/_masks.dm
  code/modules/clothing/masks/hailer.dm
  code/modules/emote_panel/emote_panel.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/basic/basic.dm
  code/modules/mob/living/brain/emote.dm
  code/modules/mob/living/carbon/alien/emote.dm
  code/modules/mob/living/carbon/emote.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/mob/living/carbon/human/species_types/oozelings.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/simple_animal/hostile/gorilla/emotes.dm
  code/modules/mob/living/simple_animal/slime/emote.dm
  code/modules/mob/mob.dm
  code/modules/mob/say.dm
  sound/attributions.txt
  sound/emotes/female/female_cough_4.ogg
  sound/emotes/female/female_cough_5.ogg
  sound/emotes/female/female_cough_6.ogg
  sound/emotes/female/female_cough_7.ogg
  sound/emotes/female/female_sneeze1.ogg
  sound/emotes/female/female_sneeze2.ogg
  sound/emotes/male/male_giggle_1.ogg
  sound/emotes/male/male_giggle_2.ogg
  sound/emotes/male/male_giggle_3.ogg
  sound/emotes/male/male_sneeze1.ogg
  sound/emotes/male/male_sneeze2.ogg
  sound/emotes/moth/moth_flutter.ogg
  sound/emotes/moth/mothchitter.ogg
  sound/emotes/moth/mothlaugh.ogg
  sound/emotes/moth/mothsqueak.ogg
  sound/emotes/moth/scream_moth.ogg
  sound/emotes/whistle1.ogg
  sound/voice/moth/credit.txt
  sound/voice/sec_death.ogg
  tgui/packages/tgui/components/SearchBar.tsx
  tgui/packages/tgui/interfaces/EmotePanel.tsx
Labels: Feature, Fix, Refactor, Sound, Code Improvement, TGUI-Changes

#11874 Moves a deltastation wire
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Mapping, Tweak, Removal

#11883 Updates some drinks sprites
  icons/obj/drinks.dmi
Labels: Feature, Sprites

#11981 Fixes food buff duration
  code/datums/status_effects/food/_food_effect.dm
Labels: Fix

#11986 tgui chat/panel fixes
  tgui/packages/tgui-panel/settings/SettingsPanel.js
  tgui/packages/tgui-panel/settings/constants.js
Labels: Feature, Fix, TGUI-Changes

#11904 [Recoup] Genetics Cluwnes now have cures.
  code/__DEFINES/DNA.dm
  code/datums/mutations/cluwne.dm
  code/game/objects/items/dna_injector.dm
Labels: Tweak, Fix, Balance/Rebalance

#11853 Ashwalker camp overhaul
  _maps/RandomRuins/LavaRuins/lavaland_surface_ash_walker1.dmm
Labels: Mapping, Tweak

#11905 Dionae changes
  code/modules/mob/living/simple_animal/hostile/retaliate/nymph.dm
Labels: Balance/Rebalance

#11969 fixes trashbag worn icons
  code/game/objects/items/storage/bags.dm
  icons/mob/clothing/belt.dmi
Labels: Sprites, Fix

#11960 Buffs the derringer
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/projectiles/ammunition/ballistic/revolver.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/boxes_magazines/internal/revolver.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/projectile/bullets/revolver.dm
  code/modules/uplink/uplink_items.dm
Labels: Balance/Rebalance, Removal

#11406 [Port] Makes gravity event based, QOL additions as well as bugfixes regarding gravity
  code/__DEFINES/dcs/signals/signals_movable.dm
  code/__DEFINES/flags.dm
  code/__DEFINES/gravity.dm
  code/__DEFINES/traits/declarations.dm
  code/__DEFINES/traits/sources.dm
  code/_globalvars/bitfields.dm
  code/_globalvars/traits/_traits.dm
  code/_onclick/hud/alert.dm
  code/controllers/subsystem/mapping.dm
  code/datums/components/caltrop.dm
  code/datums/components/chasm.dm
  code/datums/components/conveyor_movement.dm
  code/datums/components/slippery.dm
  code/datums/components/spikes.dm
  code/datums/components/squashable.dm
  code/datums/components/squeak.dm
  code/datums/elements/forced_gravity.dm
  code/datums/elements/movetype_handler.dm
  code/datums/proximity_monitor/fields/gravity.dm
  code/datums/weather/weather_types/floor_is_lava.dm
  code/game/atoms.dm
  code/game/objects/effects/mines.dm
  code/game/objects/items/handcuffs.dm
  code/game/objects/items/stacks/sheets/mineral/glass.dm
  code/game/objects/structures/kitchen_spike.dm
  code/game/objects/structures/railings.dm
  code/game/objects/structures/tables_racks.dm
  code/game/turfs/open/_open.dm
  code/game/turfs/open/lava.dm
  code/game/turfs/open/openspace.dm
  code/game/turfs/open/space/space.dm
  code/game/turfs/turf.dm
  code/modules/antagonists/clock_cult/traps/receivers/skewer.dm
  code/modules/antagonists/traitor/equipment/Malf_Modules.dm
  code/modules/assembly/mousetrap.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/mapping/space_management/zlevel_manager.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/carbon/carbon_movement.dm
  code/modules/mob/living/carbon/human/dummy.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/init_signals.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_movement.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/living/simple_animal/hostile/jungle/mega_arachnid.dm
  code/modules/mob/mob_movement.dm
  code/modules/movespeed/modifiers/mobs.dm
  code/modules/power/gravitygenerator.dm
  code/modules/projectiles/projectile/energy/net_snare.dm
  code/modules/shuttle/shuttle.dm
  icons/hud/screen_alert.dmi
Labels: Needs Testmerge, Feature, Sprites, Fix, Refactor, Priority: High

#11982 Removes Meteor Shield Sats Deploy Time
  code/modules/station_goals/shield.dm
Labels: Balance/Rebalance

#11964 Fixes Changeling Last resort
  code/modules/mob/living/simple_animal/hostile/headcrab.dm
Labels: Fix

#11844 Emergency response team changes
  _maps/boxstation.json
  _maps/corgstation.json
  _maps/deltastation.json
  _maps/echostation.json
  _maps/map_files/generic/CentCom.dmm
  _maps/metastation.json
  _maps/radstation.json
  _maps/shuttles/ferry/ferry_standard.dmm
  code/datums/shuttles.dm
  code/modules/clothing/outfits/ert.dm
Labels: Mapping, Tweak, Feature

#11994 Fixes reagent grinder juicing
  code/modules/reagents/chemistry/machinery/reagentgrinder.dm
Labels: Fix

#11962 Buffs changeling combat ability + removes absorb requirements
  code/datums/status_effects/buffs.dm
  code/modules/antagonists/changeling/cellular_emporium.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/changeling/changeling_power.dm
  code/modules/antagonists/changeling/powers/absorb.dm
  code/modules/antagonists/changeling/powers/adrenaline.dm
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/antagonists/changeling/powers/teratoma.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Balance/Rebalance

#11976 Fixes guns slowing down while worn on a belt
  code/__DEFINES/obj_flags.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/projectiles/gun.dm
Labels: Fix

#11912 QUICKSTART define
  _maps/_basemap.dm
  beestation.dme
  code/~overrides/quickstart.dm
  code/~~genesis_call/genesis_call.dm
Labels: Mapping, Feature, Code Improvement

#11936 New lizard emote.
  code/modules/mob/living/emote.dm
  sound/attributions.txt
  sound/effects/tail_swipe1.ogg
  sound/effects/tail_swipe2.ogg
Labels: Feature, Sound

#12007 Adds a multicolor Alphabet decal
  beestation.dme
  code/game/objects/effects/decals/turfdecal/alphabet.dm
  icons/turf/alphabet.dmi
Labels: Feature, Sprites

#12025 Primes Autowiki
  .github/workflows/autowiki.yml
Labels: GitHub

#12026 Change autowiki API URL
  tools/autowiki/autowiki.js
Labels: Tools

#11763 Brig physician changes
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/jobs/job_types/brig_physician.dm
Labels: Mapping, Sprites, Balance/Rebalance

#11890 Update CONTRIBUTING.md to ensure ports highlight original content
  .github/CONTRIBUTING.md
Labels: GitHub, Code Improvement

#11996 Fixes Rabbits Eggs Spawning as Errors.
  code/modules/holiday/easter.dm
  code/modules/holiday/holidays.dm
Labels: Fix

#12000 Fixes snowflaked turf armor
  code/game/turfs/closed/wall/reinf_walls.dm
  code/game/turfs/turf_integrity.dm
  code/modules/clothing/clothing.dm
  code/modules/vehicles/mecha/working/ripley.dm
Labels: Fix, Refactor

#11802 Changes maximum limb damage from 50 to 40
  code/modules/surgery/bodyparts/bodyparts.dm
Labels: Tweak, Balance/Rebalance

#12011 You'll get your map when you fix this damn floor!
  code/_globalvars/turf.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas.dm
  code/game/turfs/open/floor/iron_floor.dm
  code/game/turfs/turf.dm
  code/game/turfs/turf_texture.dm
  icons/turf/turf_texture.dmi
Labels: Sprites, Fix

#12059 Fixes echo disposals using undefined piping behaviour
  _maps/map_files/EchoStation/EchoStation.dmm
Labels: Mapping, Fix

#12053 gym fixes
  code/datums/components/crafting/crafting_lists/misc.dm
  code/datums/components/crafting/crafting_lists/structures.dm
  code/game/objects/buckling.dm
  code/game/objects/structures/guillotine.dm
  code/game/objects/structures/gym/exercise_status.dm
  code/game/objects/structures/gym/punching_bag.dm
  code/game/objects/structures/gym/weight_machine.dm
  icons/mob/inhands/equipment/weightlifting.dmi
  icons/obj/fitness.dmi
Labels: Tweak, Feature, Sprites, Fix

#11870 Subtle messages balloon alert
  code/modules/admin/verbs/randomverbs.dm
  code/modules/spells/spell_types/telepathy.dm
Labels: Tweak, Administration

#12035 Adds /obj/effect/warped_rune to the supply shuttle blacklist.
  code/modules/shuttle/supply.dm
Labels: Fix

#12036 Makes Blackbox a bit smaller.
  code/game/machinery/telecomms/machines/message_server.dm
Labels: Tweak

#12044 Fixes Split Personality brain trauma having the ability to RR the original mind of the body
  code/datums/brain_damage/split_personality.dm
Labels: Fix

#12071 Removes the second wire from the c4 charge
  code/datums/wires/explosive.dm
Labels: Tweak

#11968 Fixes custom bubbles/typing indicators after 3 years. Adds new animated ones.
  beestation.dme
  code/__DEFINES/traits/declarations.dm
  code/__DEFINES/traits/sources.dm
  code/_globalvars/traits/_traits.dm
  code/datums/mocking/client.dm
  code/modules/client/client_procs.dm
  code/modules/client/verbs/typing.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob_defines.dm
  code/modules/tgui_input/say_modal/typing.dm
  html/typing_indicator.html
  icons/mob/talk.dmi
  interface/skin.dmf
Labels: Feature, Sprites, Fix, Code Improvement

#11971 Condenses language holders, unit tests them
  code/__DEFINES/language.dm
  code/_onclick/hud/screen_objects.dm
  code/controllers/configuration/configuration.dm
  code/datums/action.dm
  code/datums/brain_damage/mrat.dm
  code/datums/brain_damage/severe.dm
  code/datums/diseases/advance/symptoms/voice_change.dm
  code/datums/dna.dm
  code/datums/mind.dm
  code/datums/mutations/speech.dm
  code/datums/status_effects/debuffs.dm
  code/datums/traits/positive_quirk.dm
  code/game/atoms_movable.dm
  code/game/objects/items/debug_items.dm
  code/game/objects/items/holy_weapons.dm
  code/modules/admin/topic.dm
  code/modules/antagonists/abductor/equipment/gland.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/clock_cult/servant_of_ratvar.dm
  code/modules/antagonists/cult/cult.dm
  code/modules/antagonists/pirate/pirate.dm
  code/modules/antagonists/revenant/revenant.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/antagonists/wizard/equipment/soulstone.dm
  code/modules/clothing/head/pirate.dm
  code/modules/error_handler/error_viewer.dm
  code/modules/events/sentience.dm
  code/modules/holoparasite/abilities/lesser/babel.dm
  code/modules/holoparasite/holoparasite_language.dm
  code/modules/jobs/job_types/curator.dm
  code/modules/language/codespeak.dm
  code/modules/language/language_holder.dm
  code/modules/language/language_menu.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/status_procs.dm
  code/modules/mob/living/carbon/say.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/silicon/pai/software.dm
  code/modules/mob/living/simple_animal/slime/powers.dm
  code/modules/mob/mob.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/research/xenobiology/crossbreeding/transformative.dm
  code/modules/surgery/organs/tongue.dm
  code/modules/tgui/states/language_menu.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/language_transfer.dm
Labels: Fix, Config Update, Refactor, Administration, Removal, Code Improvement

#11993 AI Hologram menu changes + bugfix
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Fix, Refactor

#11125 Fixes Bandanas. Adds GAGS support for Bandanas
  beestation.dme
  code/__DEFINES/dye_keys.dm
  code/__DEFINES/flags.dm
  code/_globalvars/bitfields.dm
  code/datums/greyscale/greyscale_configs.dm
  code/datums/greyscale/json_configs/bandana.json
  code/datums/greyscale/json_configs/bandana_up.json
  code/datums/greyscale/json_configs/bandana_worn.json
  code/datums/greyscale/json_configs/bandana_worn_up.json
  code/datums/greyscale/json_configs/bandskull.json
  code/datums/greyscale/json_configs/bandskull_up.json
  code/datums/greyscale/json_configs/bandskull_worn.json
  code/datums/greyscale/json_configs/bandskull_worn_up.json
  code/datums/greyscale/json_configs/bandstriped.json
  code/datums/greyscale/json_configs/bandstriped_up.json
  code/datums/greyscale/json_configs/bandstriped_worn.json
  code/datums/greyscale/json_configs/bandstriped_worn_up.json
  code/game/machinery/washing_machine.dm
  code/game/objects/items.dm
  code/game/objects/items/stacks/sheets/organic/cloths_recipes.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/cargo/packs.dm
  code/modules/client/loadout/loadout_accessories.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/masks/_masks.dm
  code/modules/clothing/masks/bandana.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/neck/_neck.dm
  code/modules/clothing/suits/chaplainsuits.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/vending/_vending.dm
  code/modules/vending/clothesmate.dm
  code/modules/vending/wardrobes.dm
  icons/mob/clothing/head/costume.dmi
  icons/mob/clothing/head/helmet.dmi
  icons/mob/clothing/mask.dmi
  icons/mob/large-worn-icons/64x64/head.dmi
  icons/obj/clothing/masks.dmi
Labels: Feature, Sprites, Fix, Refactor

#12002 Keycard authenticators now authenticate keycards
  code/modules/security_levels/keycard_authentication.dm
Labels: Balance/Rebalance

#11507 VV expansion: refreshing list, viewable+EDITABLE special lists, filters beta (and mass clean up codes)
  beestation.dme
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/vv.dm
  code/_globalvars/lists/admin.dm
  code/modules/admin/view_variables/debug_variables.dm
  code/modules/admin/view_variables/topic.dm
  code/modules/admin/view_variables/topic_basic.dm
  code/modules/admin/view_variables/topic_list.dm
  code/modules/admin/view_variables/view_variables.dm
  code/modules/admin/view_variables/vv_ghost.dm
Labels: Administration, Code Improvement

#12009 [Port] Gravity fixes that i forgor
  code/__DEFINES/flags.dm
  code/__DEFINES/gravity.dm
  code/__HELPERS/areas.dm
  code/datums/elements/forced_gravity.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas.dm
  code/game/area/areas/away_content.dm
  code/game/area/areas/centcom.dm
  code/game/area/areas/iceland.dm
  code/game/area/areas/mining.dm
  code/game/area/areas/ruins/_ruins.dm
  code/game/area/areas/ruins/space.dm
  code/game/area/areas/shuttles.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/turfs/change_turf.dm
  code/modules/admin/fun_balloon.dm
  code/modules/antagonists/heretic/knowledge/sacrifice_knowledge/sacrifice_map.dm
  code/modules/mining/equipment/survival_pod.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_movement.dm
  code/modules/power/gravitygenerator.dm
  code/modules/research/xenobiology/crossbreeding/warping.dm
  code/modules/ruins/spaceruin_code/hilbertshotel.dm
  code/modules/shuttle/shuttle_creation/shuttle_creator.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/loot/alien_artifact.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/exoplanets/biomes/_biome.dm
Labels: Fix, Administration

#12050 Updates dismemberment/delimbing and weapon sharpness
  code/__DEFINES/combat.dm
  code/game/gamemodes/clown_ops/clown_weapons.dm
  code/game/objects/items.dm
  code/game/objects/items/chainsaw.dm
  code/game/objects/items/cosmetics.dm
  code/game/objects/items/dualsaber.dm
  code/game/objects/items/fireaxe.dm
  code/game/objects/items/holy_weapons.dm
  code/game/objects/items/knives.dm
  code/game/objects/items/melee/energy.dm
  code/game/objects/items/melee/misc.dm
  code/game/objects/items/melee/transforming.dm
  code/game/objects/items/mop.dm
  code/game/objects/items/pitchfork.dm
  code/game/objects/items/sharpener.dm
  code/game/objects/items/shields.dm
  code/game/objects/items/spear.dm
  code/game/objects/items/stacks/sheets/mineral/glass.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weaponry.dm
  code/game/turfs/open/floor/fancy_floor.dm
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/antagonists/changeling/powers/tiny_prick.dm
  code/modules/antagonists/clock_cult/items/clockwork_weapon.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/antagonists/heretic/items/heretic_blades.dm
  code/modules/antagonists/heretic/structures/carving_knife.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/food_and_drinks/plate.dm
  code/modules/hydroponics/hydroitemdefines.dm
  code/modules/mining/equipment/kinetic_crusher.dm
  code/modules/mining/equipment/mining_tools.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/ninja/energy_katana.dm
  code/modules/paperwork/pen.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/magic/staff.dm
  code/modules/reagents/reagent_containers/cups/glassbottle.dm
  code/modules/research/nanites/nanite_programs/buffing.dm
  code/modules/research/xenobiology/crossbreeding/_weapons.dm
  code/modules/surgery/tools.dm
  code/modules/xenoarchaeology/traits/xenoartifact_minors.dm
Labels: Feature, Balance/Rebalance

#11128 Return of Stat icons
  code/__DEFINES/flags.dm
  code/__DEFINES/layers.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/mob/mob_stat.dm
  code/modules/power/cable.dm
  code/modules/tgui/tgui_window.dm
  tgui/global.d.ts
  tgui/packages/tgui-panel/stat/StatText.js
  tgui/packages/tgui-panel/styles/components/Stat.scss
  tgui/public/tgui.html
Labels: Feature, TGUI-Changes, Testmerge Passed, 515 Server Required

#11991 Ports emote keybindings
  beestation.dme
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/keybinding.dm
  code/__HELPERS/global_lists.dm
  code/_globalvars/lists/keybindings.dm
  code/datums/brain_damage/split_personality.dm
  code/datums/emotes.dm
  code/datums/keybinding/_defines.dm
  code/datums/keybinding/emote.dm
  code/modules/mob/camera/camera.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/brain/emote.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/silicon/ai/emote.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob_defines.dm
  code/modules/multiz/movement/mob/living_zmove.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/emoting.dm
Labels: Tweak, Feature

#12073 moves Wipe Core
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Tweak

#12070 Fixes the button size of nuclear bomb interfaces
  tgui/packages/tgui/interfaces/NuclearBomb.js
Labels: Fix, TGUI-Changes

#12068 Fixes a Hard Del in regenerate_organs
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix, Code Improvement

#12058 fixes the techfab cryo syringe description
  code/modules/research/designs/medical_designs.dm
Labels: Fix

#12080 Dismemberment hotfix
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#12078 Ports unit test fix. Shortens CI time significantly.
  code/game/turfs/turf.dm
  code/modules/unit_tests/area_contents.dm
Labels: Code Improvement

#12033 Fixes lavaland syndicate station's explosives being able to be picked up
  code/game/machinery/syndicatebomb.dm
  code/game/turfs/closed/wall/mineral_walls.dm
Labels: Fix

#12072 Restricts the Telecrystal Fuel Rod to Engineers and Atmos techs
  code/modules/uplink/uplink_items.dm
Labels: Balance/Rebalance

#12079 Removes steal plasma canister objective
  code/game/gamemodes/objective_items.dm
Labels: Removal

#12041 Makes EMP'd robotic limbs no longer hardstun you
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Balance/Rebalance

#12008 Fixes Meta-Station ERT Shuttle Docking.
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Mapping, Fix

#12084 Fixes two /me popups happening whenever you pressed M
  code/datums/emotes.dm
  code/modules/mob/living/emote.dm
Labels: Fix, Removal

#12083 Mute people can now make audible sounds again.
  code/datums/emotes.dm
Labels: Fix

#12089 Server framework fixes
  code/__DEFINES/networks.dm
  code/datums/components/server.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/telecomms/computers/telemonitor.dm
  code/game/machinery/telecomms/telecomunications.dm
  code/modules/research/server.dm
Labels: Fix, Server

#12087 Fixes warnings in compiler
  code/datums/brain_damage/severe.dm
  code/modules/mob/mob_helpers.dm
  code/modules/pool/components/swimming_felinid.dm
  code/modules/surgery/advanced/lobotomy.dm
  code/modules/vending/_vending.dm
Labels: Code Improvement

#11951 Lone Operative Landmarks.
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
Labels: Mapping, Feature

#12091 Autowiki
  .github/workflows/autowiki.yml
  beestation.dme
  code/_compile_options.dm
  code/controllers/subsystem/processing/station.dm
  code/controllers/subsystem/shuttle.dm
  code/game/world.dm
  code/modules/autowiki/autowiki.dm
  code/modules/autowiki/pages/base.dm
  code/modules/autowiki/pages/techweb.dm
  code/modules/autowiki/pages/vending.dm
  code/modules/research/designs.dm
  code/modules/research/techweb/_techweb_node.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/autowiki.dm
  tools/autowiki/autowiki.js
  tools/autowiki/package-lock.json
  tools/autowiki/package.json
  tools/build/build.js
Labels: Feature, GitHub, Tools

#12094 Fixes slap emote
  code/modules/mob/living/emote.dm
Labels: Fix

#12095 Adds bitfield editor to machine_stat
  code/_globalvars/bitfields.dm
Labels: Feature
