Repository BeeStation/BeeStation-Hornet, pull requests merged in 2024-09, with the labels that each got.

#11394 Plague Doctor hat no longer covers the face, is no longer a subtype of the bio hood.
  code/controllers/subsystem/traumas.dm
  code/game/objects/effects/spawners/bundle.dm
  code/modules/clothing/head/hat.dm
  code/modules/vending/autodrobe.dm
  code/modules/vending/wardrobes.dm
  icons/mob/clothing/head/bio.dmi
  icons/mob/clothing/head/costume.dmi
  icons/obj/clothing/head/bio.dmi
  icons/obj/clothing/head/costume.dmi
Labels: Sprites, Fix

#11403 Disposals mapping helper
  code/__DEFINES/pipe_construction.dm
  code/_globalvars/lists/flavor_misc.dm
Labels: Feature, Priority: High

#11395 Fixes Double Ocular Warden Spawns
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/ruin_objects.dm
Labels: Fix

#11350 Pacifies all pets spawned by Xenobiology's Stabilized Gold
  code/modules/research/xenobiology/crossbreeding/_status_effects.dm
Labels: Tweak

#11400 Added Efficiency Board to be Printable
  code/modules/research/designs/AI_module_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Tweak, Fix

#11396 Adds stamina damage to 'jumping'
  code/modules/multiz/movement/mob/living_zmove.dm
Labels: Tweak

#11413 Rare Ruko mining buff spotted!
  code/game/objects/items/storage/belt.dm
  code/game/turfs/closed/minerals.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mining/machine_vending.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/elite.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  icons/mob/clothing/hands.dmi
  icons/obj/clothing/gloves.dmi
Labels: Tweak, Feature, Sprites, Balance/Rebalance, Code Improvement

#11412 Deltastation mapping fixes
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Mapping, Fix, Tools

#11417 Pigeon DeltaStation Fixes
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Mapping, Tweak, Fix

#11402 Corgstation mapping fixes
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/shuttles/tram/tram_corg.dmm
Labels: Mapping, Fix, Tools, Priority: High

#11401 Makes Blood Packs printable from the med lathe
  code/modules/research/designs/autolathe_designs.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Tweak, Fix, Needs Testing Evidence

#11162 Adds Positronic Brains to Latejoin Menu
  beestation.dme
  code/__DEFINES/jobs.dm
  code/controllers/subsystem/job.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/cyborg.dm
  code/modules/jobs/job_types/posibrain.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/living/brain/posibrain.dm
Labels: Feature, Fix, Code Improvement

#11219 BoxStation Areas Reworks and Fixes
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Mapping, Tweak, Feature, Fix

#11439 Fixes Centcom Ban DB erroring out with bad index
  code/modules/admin/topic.dm
Labels: Fix, Administration

#11445 Fixes prison holodeck race condition
  code/modules/security/workshop.dm
Labels: Fix

#11446 Fixes flaky tests not running
  tools/pull_request_hooks/package.json
Labels: Fix, Tools

#11449 Fixes a critical mistake in shuttles.dm
  code/__DEFINES/subsystems.dm
  code/controllers/subsystem/async_map_generator.dm
Labels: Priority: Critical, Fix

#11447 Fixes atmos processing race condition
  code/modules/atmospherics/machinery/components/trinary_devices/mixer.dm
Labels: Fix

#11370 Fixes Bandanas
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/neck/_neck.dm
  icons/mob/clothing/neck.dmi
  icons/obj/clothing/neck.dmi
Labels: Sprites, Fix

#11450 Fixes invalid cache in maploader
  code/datums/map_generators/map_placer.dm
Labels: Priority: Critical, Fix

#11414 Fixes space movement + animation fixes port
  code/datums/elements/movetype_handler.dm
  code/modules/mob/living/carbon/carbon_movement.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#11425 Fixes RCD and RPD upgrades
  code/__DEFINES/construction.dm
Labels: Fix

#11426 Posibrains no longer limited to 1, but cyborgs cannot have repeat names
  code/__HELPERS/mobs.dm
  code/_globalvars/lists/mobs.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/mob/living/brain/MMI.dm
  code/modules/mob/living/brain/posibrain.dm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Tweak

#11441 Service and mediborg tweaks and fixes
  code/game/objects/items/robot/robot_items.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/reagents/reagent_containers/borghydro.dm
Labels: Tweak, Fix

#11454 Disables broken uplink items
  code/modules/antagonists/wizard/equipment/spellbook.dm
  code/modules/uplink/uplink_items.dm
Labels: Tweak

#11272 Fixed repeating categories in the crafting menu and sorted all the recipes
  beestation.dme
  code/__DEFINES/construction.dm
  code/__DEFINES/crafting.dm
  code/__DEFINES/time.dm
  code/datums/components/crafting/_recipes.dm
  code/datums/components/crafting/crafting.dm
  code/datums/components/crafting/crafting_lists/drinks.dm
  code/datums/components/crafting/crafting_lists/foodstuffs/_recipes.dm
  code/datums/components/crafting/crafting_lists/foodstuffs/recipes_bread.dm
  code/datums/components/crafting/crafting_lists/foodstuffs/recipes_burger.dm
  code/datums/components/crafting/crafting_lists/foodstuffs/recipes_cake.dm
  code/datums/components/crafting/crafting_lists/foodstuffs/recipes_egg.dm
  code/datums/components/crafting/crafting_lists/foodstuffs/recipes_frozen.dm
  code/datums/components/crafting/crafting_lists/foodstuffs/recipes_meat.dm
  code/datums/components/crafting/crafting_lists/foodstuffs/recipes_mexican.dm
  code/datums/components/crafting/crafting_lists/foodstuffs/recipes_misc.dm
  code/datums/components/crafting/crafting_lists/foodstuffs/recipes_pastry.dm
  code/datums/components/crafting/crafting_lists/foodstuffs/recipes_pie.dm
  code/datums/components/crafting/crafting_lists/foodstuffs/recipes_pizza.dm
  code/datums/components/crafting/crafting_lists/foodstuffs/recipes_salad.dm
  code/datums/components/crafting/crafting_lists/foodstuffs/recipes_sandwich.dm
  code/datums/components/crafting/crafting_lists/foodstuffs/recipes_seafood.dm
  code/datums/components/crafting/crafting_lists/foodstuffs/recipes_soup.dm
  code/datums/components/crafting/crafting_lists/foodstuffs/recipes_spaghetti.dm
  code/datums/components/crafting/crafting_lists/misc.dm
  code/datums/components/crafting/crafting_lists/primal.dm
  code/datums/components/crafting/crafting_lists/robots.dm
  code/datums/components/crafting/crafting_lists/structures.dm
  code/datums/components/crafting/crafting_lists/tailoring/clothing.dm
  code/datums/components/crafting/crafting_lists/tailoring/eyewear.dm
  code/datums/components/crafting/crafting_lists/weaponry/ammunitions.dm
  code/datums/components/crafting/crafting_lists/weaponry/weapons.dm
  code/datums/components/crafting/recipes.dm
  code/datums/components/crafting/tailoring.dm
  code/game/objects/items/religion.dm
  code/game/objects/items/signs.dm
  code/modules/food_and_drinks/recipes/food_mixtures.dm
  code/modules/holiday/easter.dm
  code/modules/hydroponics/fermenting_barrel.dm
  code/modules/mining/lavaland/ash_flora.dm
  code/modules/paperwork/pen.dm
  code/modules/vehicles/lavaboat.dm
Labels: Fix, Balance/Rebalance, Refactor, Code Improvement

#11461 Don't run CI on gh-readonly-queue/master (merge group does it already)
  .github/workflows/ci_suite.yml
Labels: GitHub

#11372 fix clothing eating checks, moves from species to tongues
  code/modules/clothing/clothing.dm
Labels: Tweak, Fix

#11436 Fixes Nanite Communication Remote and compatible programs
  code/modules/research/nanites/nanite_programs/suppression.dm
  code/modules/research/nanites/nanite_remote.dm
Labels: Fix

#10920 Newfood: Plates
  _maps/RandomRooms/10x5/sk_rdm091_skidrow.dmm
  _maps/RandomRooms/10x5/sk_rdm153_hobowithpeter.dmm
  _maps/RandomRooms/3x5/sk_rdm023_boxclutter7.dmm
  _maps/RandomRooms/5x4/sk_rdm021_boxdinner.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_11_hobobox.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_gluttony.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_pizzaparty.dmm
  _maps/RandomRuins/SpaceRuins/derelict2.dmm
  _maps/RandomRuins/SpaceRuins/derelict6.dmm
  _maps/RandomRuins/SpaceRuins/oldstation.dmm
  _maps/RandomZLevels/caves.dmm
  _maps/RandomZLevels/moonoutpost19.dmm
  _maps/RandomZLevels/undergroundoutpost45.dmm
  _maps/holodeck/petpark.dmm
  _maps/holodeck/small/kitchen.dmm
  _maps/holodeck/small/petpark.dmm
  _maps/map_files/EchoStation/EchoStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/map_files/RadStation/RadStation.dmm
  _maps/shuttles/hunter/hunter_space_cop.dmm
  _maps/shuttles/ruin/ruin_caravan_victim.dmm
  _maps/shuttles/whiteship/whiteship_box.dmm
  _maps/shuttles/whiteship/whiteship_delta.dmm
  _maps/shuttles/whiteship/whiteship_meta.dmm
  _maps/templates/holodeck_kitchen.dmm
  beestation.dme
  code/__DEFINES/dcs/signals/signals_atom/signals_atom.dm
  code/_globalvars/bitfields.dm
  code/_onclick/click.dm
  code/datums/elements/shatters_when_thrown.dm
  code/game/machinery/dish_drive.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items/food/cake.dm
  code/game/objects/items/food/egg.dm
  code/game/objects/items/food/pie.dm
  code/game/objects/items/food/sandwichtoast.dm
  code/game/objects/items/food/spaghetti.dm
  code/game/objects/items/storage/bags.dm
  code/game/objects/items/trash.dm
  code/modules/buildmode/buttons.dm
  code/modules/food_and_drinks/plate.dm
  code/modules/holoparasite/holoparasite_builder.dm
  code/modules/multiz/movement/atom/atom_zfall.dm
  code/modules/research/designs/autolathe_designs.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/serving_tray.dm
  code/modules/vending/drinnerware.dm
  icons/mob/clothing/belt.dmi
  icons/obj/food/containers.dmi
  icons/obj/food/egg.dmi
  icons/obj/food/food.dmi
  icons/obj/food/mexican.dmi
  icons/obj/food/piecake.dmi
  icons/obj/food/pizza.dmi
  icons/obj/food/spaghetti.dmi
  icons/obj/kitchen.dmi
  sound/items/ceramic_break.ogg
Labels: Mapping, Tweak, Feature, Sprites, Sound, Code Improvement

#11464 Aggressive OD linting
  __odlint.dm
  beestation.dme
  code/datums/elements/mechanical_repair.dm
  code/game/machinery/computer/card.dm
  code/game/objects/items/crayons.dm
  code/game/objects/items/pet_carrier.dm
  code/modules/admin/permissionedit.dm
  code/modules/antagonists/blob/overmind.dm
  code/modules/antagonists/heretic/knowledge/rust_lore.dm
  code/modules/antagonists/heretic/magic/ash_ascension.dm
  code/modules/mob/living/simple_animal/bot/atmosbot.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
  code/modules/research/xenobiology/crossbreeding/_clothing.dm
  tools/ci/od_lints.dm
Labels: Administration, Tools, Server

#11046 Beam datum updates, assembly code refactor, adds the ability to place assemblies on tanks
  beestation.dme
  code/__DEFINES/assemblies.dm
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/dcs/signals/signals_obj/signals_item/signals_item.dm
  code/__DEFINES/dcs/signals/signals_obj/signals_object.dm
  code/__DEFINES/logging.dm
  code/__DEFINES/machines.dm
  code/__HELPERS/maths.dm
  code/_globalvars/logging.dm
  code/datums/beam.dm
  code/datums/wires/_wires.dm
  code/game/communications.dm
  code/game/machinery/buttons.dm
  code/game/objects/items/carp_lasso.dm
  code/game/objects/items/devices/transfer_valve.dm
  code/modules/assembly/assembly.dm
  code/modules/assembly/holder.dm
  code/modules/assembly/igniter.dm
  code/modules/assembly/infrared.dm
  code/modules/assembly/mousetrap.dm
  code/modules/assembly/proximity.dm
  code/modules/assembly/signaler.dm
  code/modules/assembly/timer.dm
  code/modules/holoparasite/holoparasite_barriers.dm
  code/modules/modular_computers/file_system/programs/signaller.dm
  code/modules/reagents/reagent_dispenser.dm
  code/modules/wiremod/shell/assembly.dm
  code/modules/xenoarchaeology/xenoartifact.dm
  tgui/packages/tgui/interfaces/Signaler.js
Labels: Feature, Fix, Refactor, Administration, Code Improvement, TGUI-Changes

#10005 Kapulimbs Parity Pt. 1
  code/__DEFINES/dcs/signals/signals_mob/signals_carbon.dm
  code/__DEFINES/dcs/signals/signals_mob/signals_living.dm
  code/datums/diseases/advance/symptoms/clockwork.dm
  code/datums/diseases/advance/symptoms/organs.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/antagonists/changeling/powers/regenerate.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/IPC.dm
  code/modules/mob/living/carbon/human/species_types/apid.dm
  code/modules/mob/living/carbon/human/species_types/dullahan.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/mob/living/carbon/human/species_types/psyphoza.dm
  code/modules/mob/living/carbon/human/species_types/pumpkin_man.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/mob/living/carbon/human/species_types/vampire.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  code/modules/surgery/bodyparts/dismemberment.dm
  code/modules/surgery/organs/appendix.dm
  code/modules/surgery/organs/ears.dm
  code/modules/surgery/organs/heart.dm
  code/modules/surgery/organs/liver.dm
  code/modules/surgery/organs/lungs.dm
  code/modules/surgery/organs/organ_internal.dm
  code/modules/surgery/organs/stomach.dm
  code/modules/surgery/organs/tails.dm
  code/modules/surgery/organs/wings.dm
Labels: Test Merged, Tweak, Feature, Fix, Refactor, Code Improvement

#11381 [Port] Reworks universal recorder to be less bad
  code/__DEFINES/say.dm
  code/datums/looping_sounds/item_sounds.dm
  code/game/objects/items/devices/taperecorder.dm
  icons/obj/device.dmi
  icons/obj/radial_tape.dmi
  icons/obj/radial_taperecorder.dmi
  interface/stylesheet.dm
  sound/items/taperecorder/tape_flip.ogg
  sound/items/taperecorder/taperecorder_close.ogg
  sound/items/taperecorder/taperecorder_hiss_mid.ogg
  sound/items/taperecorder/taperecorder_hiss_start.ogg
  sound/items/taperecorder/taperecorder_open.ogg
  sound/items/taperecorder/taperecorder_play.ogg
  sound/items/taperecorder/taperecorder_print.ogg
  sound/items/taperecorder/taperecorder_stop.ogg
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: Tweak, Feature, Sprites, Sound, TGUI-Changes

#11149 Ports mech fixes part 2
  code/__DEFINES/is_helpers.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/clown_ops/clown_weapons.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/simple_animal/hostile/mecha_pilot.dm
  code/modules/mob/mob_movement.dm
  code/modules/projectiles/ammunition/_ammunition.dm
  code/modules/projectiles/ammunition/special/syringe.dm
  code/modules/vehicles/_vehicle.dm
  code/modules/vehicles/cars/car.dm
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/mecha/combat/durand.dm
  code/modules/vehicles/mecha/combat/honker.dm
  code/modules/vehicles/mecha/equipment/mecha_equipment.dm
  code/modules/vehicles/mecha/equipment/tools/medical_tools.dm
  code/modules/vehicles/mecha/equipment/tools/mining_tools.dm
  code/modules/vehicles/mecha/equipment/tools/other_tools.dm
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
  code/modules/vehicles/mecha/mech_bay.dm
  code/modules/vehicles/mecha/mech_melee_attack.dm
  code/modules/vehicles/mecha/mecha_control_console.dm
  code/modules/vehicles/mecha/mecha_defense.dm
  code/modules/vehicles/mecha/mecha_topic.dm
  code/modules/vehicles/mecha/working/clarke.dm
  code/modules/vehicles/sealed.dm
  code/modules/vehicles/vehicle_actions.dm
Labels: Feature, Fix, Refactor, Code Improvement

#11471 Fixes a bad delete on vending machines caused by two unused variables
  _maps/RandomZLevels/snowdin.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  code/modules/vending/_vending.dm
Labels: Mapping, Fix, Removal

#11479 Fixes player panel being broke
  tgui/packages/tgui/interfaces/PlayerPanel.js
Labels: Fix, TGUI-Changes

#11478 Fixes lighteater for nightmares
  code/modules/surgery/organs/heart.dm
Labels: Fix, Code Improvement

#11397 Cyborg Reset via Pulse
  code/datums/wires/robot.dm
Labels: Balance/Rebalance

#11229 [Port] Adds crate shelves to the game
  beestation.dme
  code/game/objects/items/stacks/sheets/mineral/metals_recipes.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/crateshelf.dm
  code/game/objects/structures/tables_racks.dm
  icons/obj/items_and_weapons.dmi
  icons/obj/objects.dmi
Labels: Feature, Sprites

#11489 Makes Ashwalkers Always spawn
  code/datums/ruins/lavaland.dm
Labels: Tweak

#11383 Echo Station Radification
  _maps/map_files/EchoStation/EchoStation.dmm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Mapping, Tweak, Feature, Fix, Balance/Rebalance, Removal

#11495 Removes political AI lawset
  code/datums/ai_laws.dm
Labels: Removal

#11506 Deletes questionable borgi icons
  icons/ui/screen_clockwork.dmi
  icons/ui/screen_midnight.dmi
  icons/ui/screen_operative.dmi
  icons/ui/screen_plasmafire.dmi
  icons/ui/screen_slimecore.dmi
Labels: Sprites, Removal

#11482 Adds 'required_neighbors' to maplint and conditional lints
  _maps/Prefab/Departments.dmm
  _maps/RandomRuins/SpaceRuins/gasthelizards.dmm
  _maps/RandomRuins/SpaceRuins/oldteleporter.dmm
  _maps/RandomRuins/SpaceRuins/power_puzzle.dmm
  _maps/RandomRuins/SpaceRuins/turretedoutpost.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  _maps/map_files/generic/CentCom.dmm
  tools/maplint/README.md
  tools/maplint/lints/apc_has_cable.yml
  tools/maplint/lints/door_name_capitalization.yml
  tools/maplint/lints/mapping_helpers.yml
  tools/maplint/source/common.py
  tools/maplint/source/lint.py
Labels: Mapping, Feature, Tools

#11488 fix kapulimbs mind nulls
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix, Removal, Testmerge Passed

#11509 Fixes recently angered age old issue related to mutant bodyparts (Moths Felinids and Lizards rejoice!)
  code/datums/diseases/advance/symptoms/clockwork.dm
  code/modules/surgery/organs/tails.dm
  code/modules/surgery/organs/wings.dm
Labels: Fix, Testmerge Passed

#11490 Adds Unit Testing: No Glass Placed on Space
  _maps/map_files/EchoStation/EchoStation.dmm
  _maps/map_files/debug/multiz.dmm
  tools/maplint/lints/space_check.yml
Labels: Mapping, Tools, Code Improvement, :ballot_box_with_check: Good PR

#11273 Unholy flask is now a bottle, not a beaker
  code/datums/components/crafting/crafting_lists/drinks.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/antagonists/cult/cult_structures.dm
  code/modules/antagonists/heretic/items/eldritch_flask.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
Labels: Tweak, Balance/Rebalance

#11465 Move see through darkness to the lighting plane backdrops
  code/_onclick/hud/fullscreen.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/rendering/plane_master.dm
  code/_onclick/hud/robot.dm
Labels: Balance/Rebalance

#11526 Fixes EchoStation's Medbay Central APC Power Cable [Now With 100% Fewer Merge Conflicts]
  _maps/map_files/EchoStation/EchoStation.dmm
Labels: Mapping, Fix

#11531 Fixes electronic paper reader looping infinitely
  code/modules/paperwork/paper_reader.dm
Labels: Fix

#11250 Breaks up hallucination.dm into smaller files
  beestation.dme
  code/modules/flufftext/Hallucination.dm
  code/modules/hallucination/HUD.dm
  code/modules/hallucination/_hallucination.dm
  code/modules/hallucination/airlock.dm
  code/modules/hallucination/chat.dm
  code/modules/hallucination/death.dm
  code/modules/hallucination/fire.dm
  code/modules/hallucination/hazard.dm
  code/modules/hallucination/hostile_mob.dm
  code/modules/hallucination/husk.dm
  code/modules/hallucination/item.dm
  code/modules/hallucination/plasma_flood.dm
  code/modules/hallucination/polymorph.dm
  code/modules/hallucination/shock.dm
  code/modules/hallucination/sound.dm
  code/modules/hallucination/stray_bullet.dm
  code/modules/mob/living/carbon/carbon_defines.dm
Labels: Fix, Code Improvement

#11378 Ports TGUI bot menus
  code/modules/mob/living/simple_animal/bot/atmosbot.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
  code/modules/mob/living/simple_animal/bot/ed209bot.dm
  code/modules/mob/living/simple_animal/bot/firebot.dm
  code/modules/mob/living/simple_animal/bot/floorbot.dm
  code/modules/mob/living/simple_animal/bot/honkbot.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  code/modules/mob/living/simple_animal/bot/secbot.dm
  tgui/packages/tgui/interfaces/SimpleBot.tsx
Labels: Mapping, Feature, Sprites, Sound, Tools, TGUI-Changes

#11534 Removes a random period that appears when examining silicons
  code/game/atoms.dm
Labels: Grammar and Formatting

#11548 Fixes not being able to stuncrit people long enough to cuff
  code/modules/mob/living/carbon/carbon.dm
Labels: Priority: Critical, Fix

#11544 Fixes nobody having enough hours for jobs
  code/controllers/subsystem/department.dm
  code/modules/jobs/job_exp.dm
  code/modules/jobs/jobs.dm
Labels: Priority: Critical, Fix

#11542 Changes async map generator to have a synchronous generation proc
  code/controllers/subsystem/async_map_generator.dm
  code/controllers/subsystem/shuttle.dm
  code/modules/shuttle/shuttle.dm
Labels: Fix

#11427 New walls and girders (now with smoothing!) + spare fixes
  beestation.dme
  code/__DEFINES/icon_smoothing.dm
  code/game/objects/structures/girders.dm
  code/game/turfs/closed/_closed.dm
  code/game/turfs/closed/indestructible.dm
  code/game/turfs/closed/wall/mineral_walls.dm
  code/game/turfs/closed/wall/misc_walls.dm
  icons/obj/smooth_structures/girders/girder.dmi
  icons/obj/smooth_structures/girders/reinforced_girder.dmi
  icons/obj/structures.dmi
  icons/turf/walls.dmi
  icons/turf/walls/reinforced_wall.dmi
  icons/turf/walls/wall.dmi
Labels: Test Merged, Feature, Sprites, Fix, Code Improvement, Golden ⭐

#11549 Stasis beds no longer pause stamina recovery
  code/modules/mob/living/carbon/life.dm
Labels: Fix

#11538 Fix mecha teleport equipment
  code/modules/vehicles/mecha/equipment/tools/other_tools.dm
Labels: Fix

#11497 Excludes maplints from crossed's codeowners
  .github/CODEOWNERS
Labels: GitHub

#11560 Fix Holoparasites with Range 1 being unable to recall and seeing barriers
  code/modules/antagonists/wizard/equipment/spellbook.dm
  code/modules/holoparasite/holoparasite_barriers.dm
  code/modules/holoparasite/holoparasite_helpers.dm
  code/modules/holoparasite/holoparasite_movement.dm
  code/modules/uplink/uplink_items.dm
Labels: Tweak, Fix, :ballot_box_with_check: Good PR

#11553 Medbot no longer opens (unused) menu upon beaker insertion
  code/modules/mob/living/simple_animal/bot/medbot.dm
Labels: Tweak, Fix

#11508 Adds night vision science goggles, because I was asked to!
  code/modules/clothing/glasses/_glasses.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/mob/clothing/eyes.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/obj/clothing/glasses.dmi
Labels: Feature, Sprites

#11475 Adds the Rainbow Knife (of xenobiology fame) to Chaplain Null Rod selection.
  code/game/objects/items/holy_weapons.dm
Labels: Feature

#11310 Properly splits attack_ai() and attack_robot() where in make sense
  beestation.dme
  code/__DEFINES/dcs/signals/signals_atom/signals_atom_attack.dm
  code/_onclick/ai.dm
  code/_onclick/cyborg.dm
  code/_onclick/silicon.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/announcement_system.dm
  code/game/machinery/buttons.dm
  code/game/machinery/cell_charger.dm
  code/game/machinery/cloning.dm
  code/game/machinery/computer/apc_control.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/dish_drive.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/firealarm.dm
  code/game/machinery/flasher.dm
  code/game/machinery/igniter.dm
  code/game/machinery/navbeacon.dm
  code/game/machinery/porta_turret/portable_turret.dm
  code/game/machinery/porta_turret/portable_turret_construct.dm
  code/game/machinery/porta_turret/portable_turret_cover.dm
  code/game/machinery/status_display.dm
  code/game/machinery/syndicatebeacon.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/powersink.dm
  code/game/objects/items/devices/radio/intercom.dm
  code/game/objects/structures/barsigns.dm
  code/game/objects/structures/fireaxe.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/morgue.dm
  code/game/turfs/open/floor/light_floor.dm
  code/modules/atmospherics/machinery/other/miner.dm
  code/modules/awaymissions/super_secret_room.dm
  code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
  code/modules/food_and_drinks/kitchen_machinery/grill.dm
  code/modules/holodeck/items.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/modular_computers/computers/item/computer.dm
  code/modules/modular_computers/computers/item/tablet.dm
  code/modules/pool/pool.dm
  code/modules/power/lighting/light.dm
  code/modules/power/port_gen.dm
  code/modules/shuttle/ferry.dm
  code/modules/station_goals/bluespace_tap.dm
Labels: Code Improvement

#11512 Lathe Material Fix
  code/modules/research/machinery/_production.dm
Labels: Tweak, Fix, Code Improvement

#11571 Readds prettier build target
  tools/build/build.js
Labels: Tools, Priority: High

#11567 Fixes Echo's engineering
  _maps/map_files/EchoStation/EchoStation.dmm
Labels: Mapping, Tweak, Feature, Fix

#11189 Updates BoxStation and MetaStation Emergency Shuttles and Adds the Rage Cage Emergency Shuttle
  _maps/shuttles/emergency/emergency_box.dmm
  _maps/shuttles/emergency/emergency_funnypod.dmm
  _maps/shuttles/emergency/emergency_meta.dmm
  _maps/shuttles/emergency/emergency_ragecage.dmm
  code/datums/shuttles.dm
Labels: Mapping, Tweak, Feature, Fix

#11485 Modernises cameras: Automatic mapping of network and phasing out the auto_name subtype
  _maps/Prefab/Departments.dmm
  _maps/RandomRuins/SpaceRuins/deepstorage.dmm
  _maps/RandomZLevels/moonoutpost19.dmm
  _maps/RandomZLevels/undergroundoutpost45.dmm
  _maps/RuinGeneration/13x13_ai-lab.dmm
  _maps/RuinGeneration/21x29_solars.dmm
  _maps/RuinGeneration/9x9_chemlab.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/EchoStation/EchoStation.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/map_files/RadStation/RadStation.dmm
  _maps/map_files/debug/runtimestation.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/shuttles/aux_base/aux_base_default.dmm
  _maps/shuttles/aux_base/aux_base_small.dmm
  _maps/shuttles/emergency/emergency_tiny.dmm
  _maps/shuttles/exploration/exploration_corg.dmm
  _maps/shuttles/exploration/exploration_rad.dmm
  _maps/shuttles/exploration/exploration_shuttle.dmm
  _maps/shuttles/mining/mining_rad.dmm
  _maps/shuttles/mining/mining_tiny.dmm
  _maps/shuttles/ruin/ruin_syndicate_fighter_shiv.dmm
  code/__DEFINES/machines.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/area/ai_monitored.dm
  code/game/area/areas.dm
  code/game/area/areas/centcom.dm
  code/game/area/areas/holodeck.dm
  code/game/area/areas/mining.dm
  code/game/area/areas/ruins/space.dm
  code/game/area/areas/shuttles.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/camera/motion.dm
  code/game/machinery/camera/presets.dm
  code/game/machinery/computer/camera.dm
  code/game/objects/items/implants/implant_camera.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/modular_computers/file_system/programs/secureye.dm
  tools/UpdatePaths/Scripts/11485_updates_cameras.txt
  tools/maplint/lints/manual_camera_networks.yml
Labels: Mapping, Tweak, Tools

#11578 Fixes the Book TGUI query
  code/game/objects/items/manuals.dm
Labels: Fix

#11539 adds a playtime requirement for obsessed
  code/modules/antagonists/obsessed/obsessed.dm
Labels: Tweak

#11565 Adds global cyborg mob list, refactors some silicon related loops
  code/__HELPERS/mobs.dm
  code/__HELPERS/roundend.dm
  code/_globalvars/lists/mobs.dm
  code/game/alternate_appearance.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/computer/robot.dm
  code/game/machinery/hologram.dm
  code/modules/admin/admin.dm
  code/modules/admin/verbs/borgpanel.dm
  code/modules/antagonists/nukeop/equipment/pinpointer.dm
  code/modules/antagonists/traitor/equipment/Malf_Modules.dm
  code/modules/events/communications_blackout.dm
  code/modules/events/processor_overload.dm
  code/modules/jobs/job_types/ai.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/modular_computers/file_system/programs/borg_monitor.dm
Labels: Fix, Refactor, Administration, Code Improvement

#10990 Shielded suit rework
  code/__DEFINES/combat.dm
  code/datums/components/shielded.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/suits/wiz_robe.dm
Labels: Balance/Rebalance

#11563 Updates donut colors when inside donut boxes
  icons/obj/food/donuts.dmi
Labels: Feature, Sprites

#11593 Removes the HonkCo clown shuttle.
  _maps/shuttles/emergency/emergency_honkco.dmm
  code/datums/shuttles.dm
  code/game/objects/items/toys.dm
Labels: Mapping

#11584 EVAC Shuttles Update
  _maps/shuttles/emergency/emergency_asteroid.dmm
  _maps/shuttles/emergency/emergency_bar.dmm
  _maps/shuttles/emergency/emergency_birdboat.dmm
  _maps/shuttles/emergency/emergency_box.dmm
  _maps/shuttles/emergency/emergency_delta.dmm
  _maps/shuttles/emergency/emergency_meta.dmm
  _maps/shuttles/emergency/emergency_tiny.dmm
Labels: Mapping, Tweak, Feature, Fix, Balance/Rebalance, Removal, Balance Approved

#11466 Teleportation Cleanup & Cult Teleports Respecting Anti-Magic
  code/__DEFINES/dcs/signals/signals_atom/signals_atom.dm
  code/__DEFINES/movement.dm
  code/datums/helper_datums/teleport.dm
  code/game/area/areas/centcom.dm
  code/game/atoms.dm
  code/game/objects/items/scrolls.dm
  code/game/objects/items/teleportation.dm
  code/modules/antagonists/abductor/machinery/experiment.dm
  code/modules/antagonists/abductor/machinery/pad.dm
  code/modules/antagonists/clock_cult/helpers/servant_warp.dm
  code/modules/antagonists/clock_cult/structure/dimensional_rift.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/antagonists/heretic/knowledge/sacrifice_knowledge/sacrifice_knowledge.dm
  code/modules/antagonists/revenant/revenant_abilities.dm
  code/modules/antagonists/wizard/equipment/artefact.dm
  code/modules/bluespace_anchor/bluespace_anchor.dm
  code/modules/mob/living/simple_animal/hostile/bread.dm
  code/modules/mob/living/simple_animal/hostile/floor_cluwne.dm
  code/modules/ninja/suit/n_suit_verbs/energy_net_nets.dm
  code/modules/projectiles/guns/magic/wand.dm
  code/modules/spells/spell_types/area_teleport.dm
  code/modules/spells/spell_types/turf_teleport.dm
Labels: Fix, Code Improvement

#11587 Saves 1.03s on asteroid plating initialisation
  code/game/turfs/open/_open.dm
  code/game/turfs/open/floor.dm
  code/game/turfs/open/floor/fancy_floor.dm
  code/game/turfs/open/floor/plating/asteroid.dm
  code/game/turfs/open/floor/plating/planet.dm
  code/modules/holodeck/turfs.dm
  icons/turf/floors.dmi
Labels: Tweak, Sprites

#11574 Bluespace Satchels collect ores in a wider range
  code/game/objects/items/storage/bags.dm
Labels: Feature

#11568 makes donut boxes start closed
  code/game/objects/items/storage/fancy.dm
Labels: Tweak

#11566 Fixes not all escape pods arriving to escape pod shuttle at round end
  _maps/map_files/generic/CentCom.dmm
Labels: Mapping, Fix

#11530 Ports more female outfit cropping masks
  code/__DEFINES/inventory.dm
  code/modules/admin/view_variables/topic.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/under/_under.dm
  code/modules/clothing/under/color.dm
  code/modules/clothing/under/costume.dm
  code/modules/clothing/under/jobs/cargo.dm
  code/modules/clothing/under/jobs/centcom.dm
  code/modules/clothing/under/jobs/civilian/civilian.dm
  code/modules/clothing/under/jobs/civilian/clown_mime.dm
  code/modules/clothing/under/jobs/civilian/curator.dm
  code/modules/clothing/under/jobs/command.dm
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/clothing/under/jobs/medical.dm
  code/modules/clothing/under/jobs/rnd.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/pants.dm
  code/modules/clothing/under/shorts.dm
  code/modules/clothing/under/skirt_dress.dm
  code/modules/clothing/under/suits.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/mob/clothing/under/masking_helpers.dmi
Labels: Feature, Sprites, Fix, Administration

#11511 You can now see the food in the microwave
  code/game/objects/structures/showcase.dm
  code/modules/food_and_drinks/kitchen_machinery/microwave.dm
  icons/obj/kitchen.dmi
  icons/obj/machines/kitchenmachines.dmi
Labels: Tweak, Sprites

#11595 Fixes morgue bodies showing null missing organs when scanned.
  code/modules/mapping/mapping_helpers.dm
Labels: Fix

#11504 Newfood: De-wikify cooking
  code/__HELPERS/names.dm
  code/datums/components/crafting/crafting_lists/foodstuffs/_recipes.dm
  code/datums/components/food/edible.dm
  code/datums/components/grillable.dm
  code/datums/elements/food/processable.dm
  code/modules/food_and_drinks/food/condiment.dm
  code/modules/food_and_drinks/recipes/food_mixtures.dm
Labels: Feature

#11502 Adds the Stechkin APS to the Nuclear Operative Uplink
  code/modules/projectiles/ammunition/ballistic/pistol.dm
  code/modules/projectiles/boxes_magazines/external/pistol.dm
  code/modules/projectiles/projectile/bullets/pistol.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature

#11514 New canned food icons and Dynamic Overlay for maintenance variant
  _maps/RandomRooms/10x10/rdm_dorms.dmm
  _maps/RandomRooms/10x10/sk_rdm083_bigtheatre.dmm
  _maps/RandomRooms/10x10/sk_rdm144_smallmagician.dmm
  _maps/RandomRooms/10x5/sk_rdm091_skidrow.dmm
  _maps/RandomRooms/10x5/sk_rdm153_hobowithpeter.dmm
  _maps/RandomRooms/10x5/sk_rdm155_punjiconveyor.dmm
  _maps/RandomRooms/10x5/sk_rdm156_oldairlock_interchange.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_11_hobobox.dmm
  _maps/arenas/soviet.dmm
  _maps/map_files/EchoStation/EchoStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/shuttles/exploration/exploration_delta.dmm
  _maps/shuttles/exploration/exploration_fland.dmm
  code/game/objects/items/food/packaged.dm
  code/game/objects/items/trash.dm
  icons/obj/food/canned.dmi
  icons/obj/food/food.dmi
Labels: Mapping, Feature, Sprites

#11598 Diona no longer die when splitting (Fixes confusing message)
  code/modules/mob/living/carbon/human/species_types/diona.dm
Labels: Fix

#11586 fixes paramedic spawn on metastation
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Mapping, Fix

#11520 [Port] Better alert and announcement sounds + status display screens
  code/__HELPERS/priority_announce.dm
  code/_globalvars/lists/flavor_misc.dm
  code/controllers/subsystem/communications.dm
  code/controllers/subsystem/security_level.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/requests_console.dm
  code/game/machinery/status_display.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/modular_computers/file_system/programs/statusdisplay.dm
  code/modules/security_levels/security_level_datums.dm
  code/modules/shuttle/emergency.dm
  icons/obj/status_display.dmi
  sound/effects/license.txt
  sound/misc/airraid.ogg
  sound/misc/alert.ogg
  sound/misc/announce_syndi.ogg
  sound/misc/notice3.ogg
  tgui/packages/tgui/interfaces/common/StatusDisplayControls.tsx
Labels: Tweak, Feature, Sprites, Sound, TGUI-Changes

#11540 Making the spetsnaz pyro bundle good
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/tanks/watertank.dm
  code/modules/uplink/uplink_items.dm
Labels: Balance/Rebalance

#11521 Ports the Stamina HUD
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/screen_objects.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/mob.dm
  icons/hud/screen_gen.dmi
Labels: Feature, Sprites, Fix

#11515 Beef Broth and Fizz are now a delicacy for meat lovers
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/log.txt
Labels: Tweak, Balance/Rebalance, Balance Approved

#11600 Fixes active gibtonite plane
  code/game/turfs/closed/minerals.dm
Labels: Fix
