Repository BeeStation/BeeStation-Hornet, pull requests merged in 2024-11, with the labels that each got.

#11774 Fixes cybernetic hearts turning into regular hearts
  code/modules/surgery/organs/heart.dm
  icons/obj/surgery.dmi
Labels: Sprites, Fix, Needs Testing Evidence

#11815 Fixes health assemblies not working
  code/datums/wires/_wires.dm
  code/datums/wires/explosive.dm
Labels: Fix

#11817 Fixes shadow shackles
  code/__DEFINES/traits/declarations.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/traits/_traits.dm
  code/game/objects/items/handcuffs.dm
  code/modules/antagonists/clock_cult/scriptures/_clockwork_scripture.dm
  code/modules/antagonists/clock_cult/scriptures/hateful_manacles.dm
  code/modules/mob/living/carbon/human/dummy.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/handcuff_tests.dm
Labels: Fix

#11824 Fixes erronous mob buckling progress bars
  code/game/objects/buckling.dm
Labels: Fix

#11807 fixes being unable to interact with mysterious bottle
  code/modules/reagents/reagent_containers/cups/drinks.dm
Labels: Fix

#11826 Tones down dynamic lategame rulesets
  code/__DEFINES/dynamic.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_midround_rolling.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_unfavorable_situation.dm
  code/game/gamemodes/dynamic/ruleset_picking.dm
Labels: Tweak

#11837 fixes being unable to orbit explosives
  code/game/objects/items/grenades/plastic.dm
Labels: Fix

#11810 Paramedic bags can now fit all the items they spawn with
  code/game/objects/items/storage/firstaid.dm
Labels: Fix

#11842 Oppenheimer is no longer shot by the syndicate turrets
  code/modules/mob/living/simple_animal/bot/medbot.dm
Labels: Mapping, Fix

#11850 Nerf billy club breaching.
  code/game/objects/items/weaponry.dm
Labels: Balance/Rebalance

#11829 fixes turf integrity check
  code/__HELPERS/spatial_info.dm
  code/game/turfs/turf.dm
  code/modules/reagents/reagent_containers/cups/glassbottle.dm
  code/modules/vending/_vending.dm
Labels: Fix

#11554 Awaymissions are now a memory of the past (almost)
  _maps/RandomRooms/3x5/sk_rdm140_crossroads.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  _maps/RandomRuins/SpaceRuins/caravanambush.dmm
  _maps/RandomZLevels/SnowCabin.dmm
  _maps/RandomZLevels/TheBeach.dmm
  _maps/RandomZLevels/caves.dmm
  _maps/RandomZLevels/moonoutpost19.dmm
  _maps/RandomZLevels/research.dmm
  _maps/RandomZLevels/snowdin.dmm
  _maps/RandomZLevels/spacebattle.dmm
  _maps/RandomZLevels/undergroundoutpost45.dmm
  _maps/arenas/singularity.dmm
  _maps/shuttles/snowdin/snowdin_excavation.dmm
  _maps/shuttles/snowdin/snowdin_mining.dmm
  beestation.dme
  code/datums/weather/weather_types/snow_storm.dm
  code/game/machinery/computer/arcade.dm
  code/game/machinery/wishgranter.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items/deployable/barricade.dm
  code/game/objects/items/trinkets/dice.dm
  code/game/objects/items/trinkets/dicefate.dm
  code/game/objects/items/trinkets/plushes.dm
  code/game/objects/structures/flora.dm
  code/game/turfs/open/dirtystation.dm
  code/modules/antagonists/wizard/wizard.dm
  code/modules/awaymissions/mission_code/Cabin.dm
  code/modules/awaymissions/mission_code/TheFactory.dm
  code/modules/awaymissions/mission_code/caves.dm
  code/modules/awaymissions/mission_code/centcomAway.dm
  code/modules/awaymissions/mission_code/challenge.dm
  code/modules/awaymissions/mission_code/moonoutpost19.dm
  code/modules/awaymissions/mission_code/murderdome.dm
  code/modules/awaymissions/mission_code/research.dm
  code/modules/awaymissions/mission_code/snowdin.dm
  code/modules/awaymissions/mission_code/spacebattle.dm
  code/modules/awaymissions/mission_code/stationCollision.dm
  code/modules/awaymissions/mission_code/undergroundoutpost45.dm
  code/modules/awaymissions/mission_code/wildwest.dm
  code/modules/clothing/masks/hailer.dm
  code/modules/mob/living/inhand_holder.dm
  code/modules/mob/living/simple_animal/corpse.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/psycho.dm
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  code/modules/paperwork/paper_premade.dm
  code/modules/power/singularity/emitter.dm
  code/modules/power/singularity/singularity.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/guns/magic/wand.dm
Labels: Mapping, Removal

#11863 [S] Prevents rust-g proccalls
  code/modules/admin/callproc/callproc.dm
Labels: Fix, Administration

#11814 Removes the supersoldier species
  beestation.dme
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species_types/supersoldier.dm
Labels: Removal

#11856 Fixes cargo maintenance on corg
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: Mapping, Fix

#11777 Fland Minor Mapping Fixes
  _maps/map_files/FlandStation/FlandStation.dmm
Labels: Mapping, Tweak, Fix

#11860 Fixes the admin actor being reported as null if they changed mob during a sleeping admin action
  code/modules/admin/topic.dm
Labels: Fix, Administration, Priority: High

#11805 Removes gangs
  beestation.dme
  code/game/gamemodes/gangs/gang_items.dm
  code/game/gamemodes/gangs/gang_pen.dm
  code/game/gamemodes/gangs/gang_tags.dm
  code/game/gamemodes/gangs/gangs.dm
  code/game/gamemodes/gangs/gangtool.dm
  code/game/gamemodes/gangs/implant_gang.dm
  code/game/gamemodes/gangs/outfits.dm
  code/game/gamemodes/legacy_gang_outfits.dm
  code/game/objects/effects/decals/crayon.dm
  code/game/objects/items/crayons.dm
  code/modules/antagonists/_common/antag_spawner.dm
  code/modules/antagonists/gang/gang.dm
  code/modules/antagonists/gang/gang_datums.dm
  code/modules/antagonists/gang/gang_hud.dm
  code/modules/antagonists/role_preference/role_antagonists.dm
Labels: Removal, Code Improvement

#11843 New nuclear operative item, The Macho Wrestler Bundle!
  code/game/objects/items/storage/backpack.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature, Balance Approved

#11868 Admin proc call rustg warning tells proc name
  code/modules/admin/callproc/callproc.dm
Labels: Administration, Code Improvement

#11819 Gatfruit now hold .38 revolvers chambered with random ammo
  code/modules/hydroponics/grown/misc.dm
  code/modules/projectiles/boxes_magazines/internal/revolver.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
Labels: Balance/Rebalance

#11806 Removes sandbox and meteor gamemode
  beestation.dme
  code/game/gamemodes/meteor/meteor.dm
  code/game/gamemodes/sandbox/h_sandbox.dm
  code/game/gamemodes/sandbox/sandbox.dm
  code/modules/mob/living/login.dm
Labels: Removal

#11855 Reduces CQC Kick and Chokehold sleeping
  code/datums/martial/cqc.dm
Labels: Balance/Rebalance

#11640 Moth Rebalance pack
  code/__DEFINES/food.dm
  code/modules/clothing/clothing.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/surgery/organs/eyes.dm
  code/modules/surgery/organs/tongue.dm
Labels: Tweak, Feature, Balance/Rebalance, Needs Testing Evidence

#11801 Moths can now eat cloth directly!
  code/game/objects/items/stacks/sheets/organic/cloths.dm
  code/modules/clothing/clothing.dm
Labels: Tweak

#11867 Adds vv color RGB hint
  code/__DEFINES/is_helpers.dm
  code/modules/admin/view_variables/debug_variables.dm
  html/admin/view_variables.css
Labels: Administration, Code Improvement

#11878 Explosion batching
  code/controllers/subsystem/explosion.dm
  code/modules/power/lighting/light.dm
Labels: Fix

#11679 Various Slaughter Demon Nerfs
  code/modules/antagonists/slaughter/slaughter.dm
  code/modules/mob/living/bloodcrawl.dm
  code/modules/spells/spell_types/bloodcrawl.dm
Labels: Balance/Rebalance, Removal, Balance Approved

#11869 Fixes server air alarm directions on some maps
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/EchoStation/EchoStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Mapping, Fix, Server

#11848 New bee sprite
  code/modules/mob/living/simple_animal/hostile/bees.dm
  icons/mob/bees.dmi
Labels: Tweak, Sprites

#11709 Modsuit Prep: Ports Proximitymonitor Refactor - bad cpu usage Edition
  beestation.dme
  code/__DEFINES/fields.dm
  code/__DEFINES/subsystems.dm
  code/controllers/subsystem/processing/fields.dm
  code/datums/components/connect_containers.dm
  code/datums/components/connect_loc_behalf.dm
  code/datums/components/connect_range.dm
  code/datums/elements/connect_loc.dm
  code/datums/proximity_monitor/field.dm
  code/datums/proximity_monitor/fields/gravity.dm
  code/datums/proximity_monitor/fields/peaceborg_dampener.dm
  code/datums/proximity_monitor/fields/timestop.dm
  code/datums/proximity_monitor/proximity_monitor.dm
  code/datums/wires/explosive.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/camera/motion.dm
  code/game/machinery/flasher.dm
  code/game/machinery/hologram.dm
  code/game/objects/effects/anomalies/anomaly_gravity.dm
  code/game/objects/effects/proximity.dm
  code/game/objects/items/robot/robot_items.dm
  code/game/objects/structures/aliens.dm
  code/game/turfs/turf.dm
  code/modules/admin/secrets.dm
  code/modules/antagonists/clock_cult/scriptures/interdiction_lens.dm
  code/modules/antagonists/wizard/equipment/spellbook.dm
  code/modules/assembly/proximity.dm
  code/modules/fields/fields.dm
  code/modules/fields/turf_objects.dm
  code/modules/food_and_drinks/kitchen_machinery/processor.dm
  code/modules/mining/machine_processing.dm
  code/modules/mining/machine_stacking.dm
  code/modules/shuttle/on_move.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/loot/artifact_defenses.dm
  code/modules/spells/spell_types/wizard.dm
  code/modules/vehicles/mecha/mech_bay.dm
Labels: Refactor, Administration

#11637 [Port] Updates potted plant behavior
  beestation.dme
  code/__DEFINES/dcs/signals/signals_mob/signals_carbon.dm
  code/__DEFINES/traits/declarations.dm
  code/_globalvars/traits/_traits.dm
  code/datums/components/tactical.dm
  code/game/data_huds.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/structures/flora.dm
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/init_signals.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/mob.dm
Labels: Tweak, Feature, Refactor, Code Improvement

#11704 Adds New Barsign
  code/game/objects/structures/barsigns.dm
  icons/obj/barsigns.dmi
Labels: Feature, Sprites

#11761 [PORTS] Dragon & Carp changes
  code/modules/antagonists/space_dragon/carp_rift.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/space_dragon.dm
Labels: Feature, Sprites, Balance/Rebalance

#11881 Worlds most important mapping change (makes APC on Rad stop floating)
  _maps/map_files/RadStation/RadStation.dmm
Labels: Mapping

#11885 [PORT] Security badges
  code/game/objects/items/storage/wallets.dm
  code/modules/clothing/under/accessories.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/warden.dm
  icons/mob/accessories.dmi
  icons/obj/clothing/accessories.dmi
Labels: Feature, Sprites

#11876 Fixes Toxin and Turbine Airlocks
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/EchoStation/EchoStation.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
Labels: Mapping, Tweak, Fix

#11877 Fixes Syndicate Outpost Rabbit
  code/modules/holiday/easter.dm
  code/modules/mob/living/inhand_holder.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
Labels: Mapping, Fix

#11872 Fixes Offset Table
  _maps/map_files/EchoStation/EchoStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  _maps/templates/shelter_2.dmm
  tools/maplint/lints/table_pixel_shifts.yml
Labels: Mapping, Fix, Tools

#11820 Removes alpha passthrough on laser projectiles
  code/modules/projectiles/projectile.dm
Labels: Sprites, Balance/Rebalance

#11900 fixes badge directionals
  icons/mob/accessories.dmi
Labels: Sprites, Fix

#11901 Fixes an oopsie with potted plants
  code/datums/components/tactical.dm
  code/game/objects/structures/flora.dm
Labels: Fix

#11893 Fixes Meteor Sats: Now Uses Proximity Monitors instead of Processing
  code/modules/station_goals/shield.dm
Labels: Tweak

#11879 Gives Centcom a facelift after 1 million years
  _maps/map_files/generic/CentCom.dmm
  icons/turf/decals.dmi
Labels: Mapping, Tweak, Feature, Sprites

#11892 Fixes natural wigs not showing the proper hair color.
  code/modules/clothing/head/misc_special.dm
Labels: Fix

#11921 Disables Shadow Sect Until #11766 is merged
  beestation.dme
  code/modules/religion/sects/shadow_sect.dm
  code/modules/uplink/uplink_items.dm
Labels: Tweak, i ded

#11919 Rat'var sound fix
  code/modules/antagonists/clock_cult/clockwork_massive.dm
Labels: Fix

#11925 Unique Heretic Ascension Announcements
  code/modules/antagonists/heretic/heretic_antag.dm
  code/modules/antagonists/heretic/heretic_knowledge.dm
  code/modules/antagonists/heretic/heretic_monsters.dm
  code/modules/antagonists/heretic/knowledge/ash_lore.dm
  code/modules/antagonists/heretic/knowledge/flesh_lore.dm
  code/modules/antagonists/heretic/knowledge/rust_lore.dm
  code/modules/antagonists/heretic/knowledge/void_lore.dm
  sound/ambience/antag/heretic/ascend_ash.ogg
  sound/ambience/antag/heretic/ascend_flesh.ogg
  sound/ambience/antag/heretic/ascend_rust.ogg
  sound/ambience/antag/heretic/ascend_void.ogg
  sound/ambience/antag/heretic/heretic_gain.ogg
Labels: Refactor, Sound, Code Improvement

#11913 New security heirloom
  code/datums/traits/negative_quirk.dm
  code/modules/projectiles/ammunition/energy/stun.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/projectile/energy/stun.dm
Labels: Feature

#11917 Fixes contractor helmets
  code/modules/clothing/spacesuits/syndi.dm
Labels: Fix

#11911 Headset tampering
  code/datums/elements/strippable.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/radio/radio.dm
  tgui/packages/tgui/interfaces/Radio.js
  tgui/packages/tgui/interfaces/StripMenu.tsx
Labels: Feature, TGUI-Changes

#10364 Ports the RBMK from NSV (for real this time)
  beestation.dme
  code/__DEFINES/layers.dm
  code/__DEFINES/machines.dm
  code/datums/looping_sounds/machinery_sounds.dm
  code/game/objects/effects/decals/cleanable/nuclear_waste.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/modules/cargo/packs.dm
  code/modules/power/rbmk/_rbmk_defines.dm
  code/modules/power/rbmk/fuel_rods.dm
  code/modules/power/rbmk/rbmk_core.dm
  code/modules/power/rbmk/rbmk_main_processes.dm
  code/modules/power/rbmk/rbmk_monitoring.dm
  code/modules/power/rbmk/rbmk_parts.dm
  code/modules/power/rbmk/rbmk_procs.dm
  code/modules/uplink/uplink_items.dm
  icons/obj/computer.dmi
  icons/obj/control_rod.dmi
  icons/obj/machines/rbmk.dmi
  icons/obj/machines/rbmkparts.dmi
  icons/obj/tools.dmi
  sound/effects/rbmk/alarm.ogg
  sound/effects/rbmk/ambience.ogg
  sound/effects/rbmk/explode.ogg
  sound/effects/rbmk/reactor_hum.ogg
  sound/effects/rbmk/startup.ogg
  sound/effects/rbmk/startup2.ogg
  sound/effects/rbmk/switch1.ogg
  sound/effects/rbmk/switch2.ogg
  sound/effects/rbmk/switch3.ogg
  tgui/packages/tgui/interfaces/NtosGhostRbmkStats.js
  tgui/packages/tgui/interfaces/NtosRbmkStats.js
  tgui/packages/tgui/interfaces/RbmkControlRods.js
Labels: Needs Testmerge, Feature, Sprites, Sound, TGUI-Changes, 🔑 Close Key (1/3), 🔑 Close Key (2/3)

#11934 Fixes radio transceiver menu not showing up for silicons
  code/game/objects/items/devices/radio/radio.dm
Labels: Fix

#11937 RBMK fixes
  code/modules/power/rbmk/rbmk_parts.dm
  code/modules/power/rbmk/rbmk_procs.dm
Labels: Fix

#11933 Fixes spaceman DMM throwing version compatability errors
  code/__byond_version_compat.dm
Labels: Fix

#11942 Cloning scanner fixes
  code/datums/records/manifest.dm
  code/datums/records/record.dm
  code/game/machinery/computer/cloning.dm
Labels: Fix, Refactor

#11918 Debug nanite injectors are no longer available to normal players
  code/game/objects/effects/spawners/mailspawner.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/mapping.dm
Labels: Fix

#11415 Ports ERT features
  _maps/Prefab/Departments.dmm
  _maps/shuttles/hunter/hunter_bounty.dmm
  beestation.dme
  code/datums/browser.dm
  code/datums/ert.dm
  code/game/objects/items/cards_ids.dm
  code/modules/admin/verbs/one_click_antag.dm
  code/modules/antagonists/ert/ert.dm
  code/modules/antagonists/fugitive/hunter_outfits.dm
  code/modules/antagonists/official/official.dm
  code/modules/client/preferences/entries/player/admin.dm
  code/modules/clothing/outfits/ert.dm
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/admin.tsx
Labels: Mapping, Feature, Sprites, Fix, Administration, Code Improvement, TGUI-Changes

#11946 Removes duplicate drink typepath
  _maps/RandomRooms/10x10/rdm_dorms.dmm
  _maps/RandomRooms/10x5/sk_rdm091_skidrow.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_ash_walker1.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  _maps/RandomRuins/SpaceRuins/deepstorage.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  _maps/shuttles/ruin/ruin_caravan_victim.dmm
  _maps/shuttles/whiteship/whiteship_box.dmm
  _maps/shuttles/whiteship/whiteship_delta.dmm
  _maps/shuttles/whiteship/whiteship_fland.dmm
  _maps/shuttles/whiteship/whiteship_meta.dmm
  code/game/objects/items/grenades/chem_grenade.dm
  code/game/objects/items/storage/bags.dm
  code/modules/reagents/reagent_containers/cups/_cup.dm
  code/modules/reagents/reagent_containers/cups/drinks.dm
Labels: Mapping, Fix, Code Improvement

#11932 Toilet direction fixes, bathroom changes.
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/EchoStation/EchoStation.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Mapping

#11898 Makes the Cat Surgeon no longer instantly pacify consious felinids.
  code/modules/mob/living/simple_animal/hostile/cat_butcher.dm
Labels: Balance/Rebalance

#11956 Fixes emitters.
  code/game/objects/structures/reflector.dm
Labels: Fix

#11939 Refactors ebows and kpa's to the same parent
  _maps/RuinGeneration/17x17_charliecrew.dmm
  _maps/shuttles/hunter/hunter_bounty.dmm
  beestation.dme
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/antagonists/role_preference/role_antagonists.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/suits/cloaks.dm
  code/modules/clothing/suits/wintercoats.dm
  code/modules/jobs/job_types/shaft_miner.dm
  code/modules/mining/equipment/explorer_gear.dm
  code/modules/mining/machine_vending.dm
  code/modules/mining/mine_items.dm
  code/modules/mining/minebot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  code/modules/projectiles/guns/energy/recharge.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/spells/spell_types/rightandwrong.dm
  code/modules/uplink/uplink_items.dm
Labels: Mapping, Tweak, Refactor

#11949 a lotta tgui improvements
  tgui/packages/tgui-panel/chat/ChatPageSettings.js
  tgui/packages/tgui-panel/chat/ChatTabs.js
  tgui/packages/tgui-panel/chat/actions.js
  tgui/packages/tgui-panel/chat/middleware.js
  tgui/packages/tgui-panel/chat/model.js
  tgui/packages/tgui-panel/chat/reducer.js
  tgui/packages/tgui-panel/chat/renderer.js
  tgui/packages/tgui-panel/chat/replaceInTextNode.js
  tgui/packages/tgui-panel/reconnect.tsx
  tgui/packages/tgui-panel/settings/SettingsPanel.js
  tgui/packages/tgui-panel/settings/model.js
  tgui/packages/tgui-panel/settings/reducer.js
  tgui/packages/tgui-panel/styles/components/Notifications.scss
  tgui/packages/tgui/styles/components/Button.scss
Labels: Tweak, Feature, Fix, TGUI-Changes

#11916 Fixes a issue with prisoners spawning on corg
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: Mapping, Fix
