Repository BeeStation/BeeStation-Hornet, pull requests merged in 2024-02, with the labels that each got.

#10564 KiloSstation Missed Stuff
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Mapping, Tweak, Feature, Fix

#10567 Kilo Brig/Medbay Fixes
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Mapping, Tweak, Feature, Fix

#10489 Rad brig rework
  _maps/map_files/RadStation/RadStation.dmm
  code/game/area/Space_Station_13_areas.dm
Labels: Mapping, Tweak, Feature, Fix, Balance/Rebalance

#10569 Holodeck offline template fix
  code/modules/holodeck/computer.dm
  code/modules/holodeck/holodeck_map_templates.dm
  code/modules/security/workshop.dm
Labels: Fix

#10547 No more ventcrawling into unconnected atmos pipes
  code/modules/atmospherics/machinery/atmosmachinery.dm
Labels: Fix

#10568 Adds the ability for AI to talk in loud mode for the binary channel
  code/modules/mob/living/silicon/say.dm
Labels: Fix, Server

#10533 Venus human trap adjustments: drains health while outside of vines, and no more pulling.
  code/modules/mob/living/simple_animal/hostile/venus_human_trap.dm
Labels: Tweak, Balance/Rebalance

#10586 Fixes mutation toxins causing healing
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Tweak, Fix

#9126 Traitor Backstories
  beestation.dme
  code/__DEFINES/devices.dm
  code/__DEFINES/traitor.dm
  code/_globalvars/lists/traitor.dm
  code/datums/mind.dm
  code/game/gamemodes/objectives/_objective.dm
  code/game/gamemodes/objectives/basic/assassinate.dm
  code/game/gamemodes/objectives/basic/debrain.dm
  code/game/gamemodes/objectives/basic/destroy_ai.dm
  code/game/gamemodes/objectives/basic/download.dm
  code/game/gamemodes/objectives/basic/maroon.dm
  code/game/gamemodes/objectives/basic/mutiny.dm
  code/game/gamemodes/objectives/basic/protect.dm
  code/game/gamemodes/objectives/basic/silicon/block.dm
  code/game/gamemodes/objectives/basic/silicon/purge.dm
  code/game/gamemodes/objectives/basic/silicon/robot_army.dm
  code/game/gamemodes/objectives/basic/steal.dm
  code/game/gamemodes/objectives/basic/steal_five.dm
  code/game/gamemodes/objectives/finale/nuclear.dm
  code/modules/admin/antag_panel.dm
  code/modules/antagonists/holoparasite/holoparasite_antag.dm
  code/modules/antagonists/traitor/IAA/internal_affairs.dm
  code/modules/antagonists/traitor/backstory/traitor_backstories.dm
  code/modules/antagonists/traitor/backstory/traitor_backstory_ui.dm
  code/modules/antagonists/traitor/backstory/traitor_datum_backstory.dm
  code/modules/antagonists/traitor/backstory/traitor_factions.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/antagonists/traitor/equipment/contractor.dm
  code/modules/antagonists/traitor/traitor_ai.dm
  code/modules/antagonists/traitor/traitor_objectives.dm
  code/modules/holoparasite/_holoparasite.dm
  code/modules/holoparasite/abilities/lesser/snares.dm
  code/modules/holoparasite/abilities/major/scout.dm
  html/antagtips/traitor.html
  icons/mob/actions.dmi
  tgui/packages/tgui/interfaces/AntagInfoTraitor.tsx
  tgui/packages/tgui/interfaces/TraitorBackstoryMenu.js
  tgui/packages/tgui/styles/themes/neutral.scss
Labels: Test Merged, Sprites, Administration, Golden ⭐, TGUI-Changes

#10596 Fixes Incorrect IPC trait Description
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#10577 Increases (cosmetic) jackboot availability. Makes white winter coat and winterboots obtainable in game.
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/client/loadout/loadout_footwear.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/vending/clothesmate.dm
Labels: Tweak, Feature, Removal

#10606 Emergency Meta Brig-fix
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Mapping

#10598 Corg Roboticists Rejoice! Corg Bot Corner Fix
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: Mapping, Fix

#10552 Fix traction & helper
  code/game/turfs/open/_open.dm
  code/game/turfs/open/floor/misc_floor.dm
  code/game/turfs/turf.dm
  code/modules/mapping/mapping_helpers.dm
Labels: Fix

#10428 Port TG ban improvements
  beestation.dme
  code/__DEFINES/subsystems.dm
  code/controllers/subsystem/ban_cache.dm
  code/controllers/subsystem/ticker.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
Labels: Administration

#10571 Six new maintenance maps!
  _maps/RandomRooms/10x10/sk_rdm170_laser_tag.dmm
  _maps/RandomRooms/10x5/sk_rdm171_dead_bodies.dmm
  _maps/RandomRooms/3x3/sk_rdm172_wizard_closet.dmm
  _maps/RandomRooms/3x5/sk_rdm173_chocolate.dmm
  _maps/RandomRooms/5x3/sk_rdm174_rats.dmm
  _maps/RandomRooms/5x4/sk_rdm175_shop.dmm
  code/modules/mapping/random_rooms.dm
Labels: Mapping

#10575 Fixes sanity getting stuck at insane and breaking the UI
  code/datums/components/mood.dm
Labels: Fix

#10546 Visualizes blushing/drunkness and crying. Implements unused drunk status alert.
  code/__DEFINES/colors.dm
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/_onclick/hud/alert.dm
  code/datums/mood_events/drink_events.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/emote.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  icons/mob/human_face.dmi
Labels: Mapping, Sprites

#10426 Fix mentor deadminning and admin loading
  code/modules/admin/holder2.dm
  code/modules/mentor/mentor.dm
  code/modules/mentor/mentor_loading.dm
Labels: Administration

#10217 Adds "Remove All Overlays" Input to BCI Object Overlay: Take 2: Sleep deprived edition
  code/modules/wiremod/components/bci/hud/object_overlay.dm
Labels: Tweak, Feature, Sprites, Fix, Grammar and Formatting, Balance/Rebalance, Refactor, Sound, Removal, Code Improvement, Server

#10367 Port chat reliability subsystem from /tg/
  beestation.dme
  code/__DEFINES/chat.dm
  code/controllers/subsystem/chat.dm
  code/datums/chat_payload.dm
  code/modules/tgchat/to_chat.dm
  tgui/packages/tgui-panel/chat/middleware.js
Labels: Needs Testmerge, Feature, Code Improvement, TGUI-Changes

#10608 Ballistic guns chamber during Initialize again
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
Labels: Tweak

#10600 Adds Three EVAC Decals
  code/game/objects/effects/decals/turfdecal/markings.dm
  icons/turf/decals.dmi
Labels: Feature, Sprites

#10613 Fixes race condition in shuttle loading
  code/controllers/subsystem/shuttle.dm
Labels: Fix

#10595 Fixed Phobia related faint-looping for real this time
  code/datums/brain_damage/phobia.dm
Labels: Tweak, Feature, Fix

#10548 Security Checkpoint Capsule #2
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  _maps/templates/capsule_barricade.dmm
  _maps/templates/capsule_checkpoint.dmm
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/structures/railings.dm
  code/modules/cargo/packs.dm
  code/modules/mining/equipment/survival_pod.dm
  code/modules/mining/shelters.dm
  icons/obj/doors/windoor.dmi
  icons/obj/fluff.dmi
Labels: Mapping, Tweak, Feature, Sprites

#10602 Fixes some initializations being counted as bad inits and a few actual bad inits
  code/_onclick/hud/parallax.dm
  code/controllers/subsystem/atoms.dm
  code/game/objects/items/bedsheets.dm
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/grille.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  code/modules/xenoarchaeology/xenoartifact.dm
Labels: Fix

#10607 Adds a new event and midround ruleset: Prisoners
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  beestation.dme
  code/__DEFINES/atom_hud.dm
  code/__DEFINES/role_preferences.dm
  code/_globalvars/lists/mapping.dm
  code/datums/hud.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/objects/effects/landmarks.dm
  code/modules/antagonists/prisoner/prisoner.dm
  code/modules/antagonists/role_preference/role_midrounds.dm
  code/modules/events/prisoner_spawning.dm
Labels: Mapping, Feature, Sprites, Tools

#10530 nukies can do war below the pop limit without the extra TC
  code/modules/antagonists/nukeop/equipment/nuclear_challenge.dm
Labels: Tweak, Fix

#10616 Fixes shuttle docking zone being cleared too early in the loading process
  code/controllers/subsystem/shuttle.dm
  code/datums/map_generators/_async_map_generator.dm
Labels: THIS IS VERY IMPORTANT, Fix, Removal

#10623 Adds basic html literacy
  code/datums/components/mood.dm
Labels: Fix

#10303 Fixes SM throwing runtime when a ghost examines SM
  code/modules/power/supermatter/supermatter.dm
Labels: Stale, Fix

#10629 Adds Prisoner Spawner points in RadStation and Tweaks maximum number of Prisoners
  _maps/map_files/RadStation/RadStation.dmm
  code/modules/events/prisoner_spawning.dm
Labels: Mapping

#10634 Make eldritch_amulet fire proof & lave proof
  code/modules/antagonists/heretic/items/heretic_necks.dm
Labels: Balance/Rebalance, i ded

#10642 Removed "Deep Throat" from sausage eatverbs
  code/game/objects/items/food/meatdish.dm
Labels: Removal

#10630 Emergency Delta Brig fixes
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Mapping, THIS IS VERY IMPORTANT, Fix

#10638 Fixes broken tiles in russian shuttle
  _maps/shuttles/hunter/hunter_russian.dmm
Labels: Mapping, Fix

#10643 missing single wire on box station
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Mapping, Fix

#10660 Makes emote punctuation standardised
  code/modules/mob/living/emote.dm
Labels: Tweak

#10650 Minor Spell Correction: Eletronic -> Ele c tronic
  code/_onclick/ai.dm
  code/_onclick/cyborg.dm
  code/modules/paperwork/paper_reader.dm
  code/modules/research/designs/misc_designs.dm
Labels: Fix

#10599 Medbots now use internal beakers, no longer tend wounds
  code/__DEFINES/robots.dm
  code/game/machinery/computer/medical.dm
  code/game/objects/items/storage/firstaid.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/reagent_containers/chem_bag.dm
  icons/mob/aibots.dmi
  sound/voice/medbot/fillmebackup.ogg
  sound/voice/medbot/needmedicine.ogg
  sound/voice/medbot/needtorestock.ogg
Labels: Tweak, Feature, Sprites, Balance/Rebalance, Sound

#10668 Hofix for vis overlay & agent box
  code/controllers/subsystem/vis_overlays.dm
Labels: Fix
