Repository BeeStation/BeeStation-Hornet, pull requests merged in 2024-01, with the labels that each got.

#10390 Wild West Crate (Contraband Lever-Action Rifle Crate)
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/toolbox.dm
  code/modules/cargo/packs.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/paperwork/paper_premade.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites

#10296 Launchpad recall
  code/game/machinery/computer/launchpad_control.dm
  tgui/packages/tgui/interfaces/LaunchpadConsole.js
Labels: Balance/Rebalance, TGUI-Changes

#10418 Hotfix: Fixes techfab TGUI issue
  tgui/packages/tgui/interfaces/TechFab.js
Labels: TGUI-Changes

#10304 Expands Departmental Mech Access for Roboticists
  code/game/mecha/mecha.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/job_types/roboticist.dm
Labels: Balance/Rebalance

#10429 Greatly reduces roundstart delay
  code/controllers/master.dm
Labels: Needs Testmerge

#10427 Speed up ByondUI mounting
  tgui/packages/tgui/components/ByondUi.js
Labels: TGUI-Changes

#10206 Removes SS_NO_TICK_CHECK for alleged free performance
  code/__DEFINES/MC.dm
  code/controllers/master.dm
  code/controllers/subsystem/blackbox.dm
  code/controllers/subsystem/nightshift.dm
  code/controllers/subsystem/profiler.dm
  code/controllers/subsystem/shuttle.dm
  code/controllers/subsystem/sun.dm
  code/controllers/subsystem/time_track.dm
Labels: Server

#10368 Overrides the base material iron table with the default one
  code/game/objects/items/stacks/sheets/mineral/metals.dm
Labels: Tweak

#10266 Ports cleaning system refactor
  code/__DEFINES/cleaning.dm
  code/__DEFINES/dcs/signals/signals_datum/signals_datum.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/vv.dm
  code/datums/components/creamed.dm
  code/datums/components/forensics.dm
  code/datums/components/infective.dm
  code/datums/components/radioactive.dm
  code/datums/components/thermite.dm
  code/datums/elements/cleaning.dm
  code/datums/elements/decals/blood.dm
  code/game/atoms.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/machinery/washing_machine.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/effects/decals/cleanable/aliens.dm
  code/game/objects/effects/decals/cleanable/humans.dm
  code/game/objects/effects/decals/cleanable/misc.dm
  code/game/objects/effects/decals/cleanable/robots.dm
  code/game/objects/items.dm
  code/game/objects/items/clown_items.dm
  code/game/objects/items/dualsaber.dm
  code/game/objects/items/mop.dm
  code/game/objects/structures/shower.dm
  code/game/objects/structures/watercloset.dm
  code/game/turfs/open/_open.dm
  code/game/turfs/turf.dm
  code/modules/clothing/gloves/_gloves.dm
  code/modules/clothing/shoes/_shoes.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/detectivework/detective_work.dm
  code/modules/detectivework/footprints_and_rag.dm
  code/modules/lighting/lighting_object.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/pool/pool.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Tweak, Feature, Fix, Balance/Rebalance, Refactor

#10246 Fixes a bad return when get_active_held_item can't find an item
  code/modules/mob/inventory.dm
Labels: Code Improvement

#10430 Sniper rounds no longer paralyze for 10 seconds.
  code/modules/projectiles/projectile/bullets/sniper.dm
Labels: Balance Approved

#10402 Fixes 'random arcade machines' bug
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  _maps/map_files/debug/multiz.dmm
  _maps/map_files/generic/CentCom.dmm
  beestation.dme
  code/game/machinery/computer/arcade.dm
  code/game/objects/effects/spawners/arcade.dm
Labels: Mapping

#10451 Fixes The Atmos Bug
  code/game/objects/structures/plasticflaps.dm
  code/game/objects/structures/railings.dm
  code/game/objects/structures/window.dm
  code/modules/atmospherics/environmental/LINDA_system.dm
  code/modules/atmospherics/machinery/components/components_base.dm
  code/modules/atmospherics/machinery/other/miner.dm
Labels: THIS IS VERY IMPORTANT, Fix, Golden ⭐, :ballot_box_with_check: Good PR

#10453 Fixes being ghosted when Monkeyized
  code/modules/mob/living/brain/brain_item.dm
Labels: Somewhat Important

#10066 Unit Test for Smoothing (and fixes for some uncaught issues)
  code/__DEFINES/icon_smoothing.dm
  code/game/machinery/bank_machine.dm
  code/game/machinery/computer/_computer.dm
  code/game/machinery/computer/arcade.dm
  code/game/machinery/computer/camera.dm
  code/game/machinery/computer/camera_advanced.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/pod.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/slotmachine.dm
  code/game/objects/structures/aliens.dm
  code/game/objects/structures/false_walls.dm
  code/game/turfs/closed/minerals.dm
  code/game/turfs/closed/wall/misc_walls.dm
  code/game/turfs/open/chasm.dm
  code/game/turfs/open/floor/plating/misc_plating.dm
  code/modules/antagonists/clock_cult/clockwork_turfs.dm
  code/modules/antagonists/clock_cult/structure/clockwork_overlay.dm
  code/modules/library/lib_machines.dm
  code/modules/reagents/chemistry/machinery/pandemic.dm
  code/modules/research/nanites/nanite_cloud_controller.dm
  code/modules/shuttle/bluespace_shuttle_pod/pod_computer.dm
  code/modules/shuttle/emergency.dm
  code/modules/shuttle/shuttle_creation/shuttle_creator_console.dm
  code/modules/shuttle/syndicate.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/icon_smoothing_unit_test.dm
  code/modules/xenoarchaeology/xenoartifact_console.dm
  icons/turf/walls/bamboo_wall.dmi
  icons/turf/walls/copper_wall.dmi
  icons/turf/walls/shuttle_wall.dmi
Labels: Sprites, Fix, Code Improvement, hacktoberfest-accepted

#10136 Crates and locker resprite and overhaul
  _maps/RandomZLevels/SnowCabin.dmm
  beestation.dme
  code/game/gamemodes/objectives/stash_component.dm
  code/game/objects/effects/misc.dm
  code/game/objects/items/gift.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/book.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/briefcase.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/items/storage/lockbox.dm
  code/game/objects/items/storage/paperbag.dm
  code/game/objects/items/storage/secure.dm
  code/game/objects/items/storage/storage.dm
  code/game/objects/items/storage/toolbox.dm
  code/game/objects/items/storage/wallets.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/cardboardbox.dm
  code/game/objects/structures/crates_lockers/closets/gimmick.dm
  code/game/objects/structures/crates_lockers/closets/secure/bar.dm
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/crates_lockers/crates/bins.dm
  code/game/objects/structures/crates_lockers/crates/critter.dm
  code/game/objects/structures/crates_lockers/crates/secure.dm
  code/game/objects/structures/guncase.dm
  code/modules/admin/verbs/pray.dm
  code/modules/detectivework/evidence.dm
  code/modules/holiday/easter.dm
  code/modules/mapping/mapping_items/medical_spawners.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mining/mine_items.dm
  code/modules/mob/living/simple_animal/bot/mulebot.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  code/modules/recycling/sortingmachinery.dm
  code/modules/research/designs/stock_parts_designs.dm
  code/modules/research/stock_parts.dm
  code/modules/ruins/objects_and_mobs/sin_ruins.dm
  code/modules/shuttle/emergency.dm
  code/modules/surgery/tools.dm
  icons/mob/aibots.dmi
  icons/mob/easter.dmi
  icons/mob/lavaland/lavaland_monsters.dmi
  icons/obj/closet.dmi
  icons/obj/crates.dmi
  icons/obj/storage.dmi
  icons/obj/storage/backpack.dmi
  icons/obj/storage/basket.dmi
  icons/obj/storage/book.dmi
  icons/obj/storage/box.dmi
  icons/obj/storage/case.dmi
  icons/obj/storage/closet.dmi
  icons/obj/storage/crates.dmi
  icons/obj/storage/medkit.dmi
  icons/obj/storage/paperbag.dmi
  icons/obj/storage/storage.dmi
  icons/obj/storage/toolbox.dmi
  icons/obj/storage/wrapping.dmi
Labels: Mapping, Feature, Sprites, Refactor, Administration, Code Improvement

#10300 Ports refactor of electrocute_act, switches out args for flags
  code/__DEFINES/dcs/signals/signals_mob/signals_living.dm
  code/datums/mutations/touch.dm
  code/game/objects/effects/anomalies/anomaly_flux.dm
  code/game/objects/items/robot/robot_items.dm
  code/game/objects/obj_defense.dm
  code/game/objects/structures/holosign.dm
  code/game/objects/structures/traps.dm
  code/modules/antagonists/revenant/revenant_abilities.dm
  code/modules/antagonists/swarmer/swarmer.dm
  code/modules/clothing/spacesuits/chronosuit.dm
  code/modules/hydroponics/plant_genes.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/silicon_defense.dm
  code/modules/mob/living/simple_animal/bot/ed209bot.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  code/modules/mob/living/simple_animal/hostile/floor_cluwne.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/swarmer.dm
  code/modules/power/lighting/light.dm
  code/modules/power/supermatter/supermatter.dm
  code/modules/power/tesla/energy_ball.dm
  code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
  code/modules/spells/spell_types/lightning.dm
  code/modules/spells/spell_types/wizard.dm
  code/modules/surgery/organs/stomach.dm
Labels: Feature, Refactor

#10133 Fixes trashbag with quick equip belt hotkey
  code/datums/keybinding/human.dm
Labels: Fix

#10059 MC Diagnostic Mode
  code/controllers/configuration/entries/general.dm
  code/controllers/master.dm
  code/controllers/subsystem/metrics.dm
  code/modules/mob/mob_stat.dm
  config/config.txt
Labels: Config Update, Code Improvement, hacktoberfest-accepted

#10425 White Bandana - Small addition
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/vending/wardrobes.dm
  icons/mob/clothing/head.dmi
  icons/mob/mask.dmi
  icons/obj/clothing/masks.dmi
Labels: Sprites

#10339 Fixes Carpets Runtime when they get burned by atmospherics
  code/game/turfs/open/floor/fancy_floor.dm
Labels: Fix

#10398 Adds a Plushie Delivery Beacon to the game.
  code/__DEFINES/traits.dm
  code/datums/traits/positive_quirk.dm
  code/game/objects/items/plushes.dm
  code/modules/instruments/items.dm
  code/modules/vending/games.dm
  icons/obj/device.dmi
Labels: Sprites

#10356 Fix monkeys ripping apart DNA scanners from the inside
  code/datums/ai/monkey/monkey_subtrees.dm
Labels: Fix

#10166 Ports Genpop from NSV
  _maps/holodeck/workshop/donut.dmm
  _maps/holodeck/workshop/offline.dmm
  _maps/holodeck/workshop/plush.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  beestation.dme
  code/__DEFINES/access.dm
  code/__DEFINES/construction.dm
  code/__DEFINES/obj_flags.dm
  code/_globalvars/bitfields.dm
  code/datums/components/crafting/crafting.dm
  code/datums/weather/weather_types/radiation_storm.dm
  code/game/area/areas/holodeck.dm
  code/game/machinery/computer/prisoner/_prisoner.dm
  code/game/machinery/gulag_item_reclaimer.dm
  code/game/objects/effects/spawners/structure.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/stacks/sheets/mineral/metals_recipes.dm
  code/game/objects/items/stacks/sheets/organic/cloths_recipes.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/toys.dm
  code/game/objects/structures/grille.dm
  code/game/turfs/open/floor/plating.dm
  code/game/turfs/open/floor/prison_floor.dm
  code/modules/holodeck/computer.dm
  code/modules/holodeck/holodeck_map_templates.dm
  code/modules/holodeck/turfs.dm
  code/modules/mining/laborcamp/laborstacker.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/security/crimes.dm
  code/modules/security/genpop.dm
  code/modules/security/prison_scanner.dm
  code/modules/security/workshop.dm
  config/space_law.json
  icons/obj/machines/genpop_display.dmi
  icons/obj/machines/turnstile.dmi
  icons/turf/prisonfloor.dmi
  tgui/packages/tgui/interfaces/GenPop.js
  tgui/packages/tgui/interfaces/Workshop.js
Labels: Mapping, Test Merged, Tweak, Feature, Sprites, Config Update, Code Improvement, TGUI-Changes, Somewhat Important

#10484 Fix Mapping & Icon Issues Related to Genpop
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  beestation.dme
  code/modules/holodeck/turfs.dm
  icons/turf/prisonfloor.dmi
Labels: Mapping, Sprites

#10493 NewFood UpdatePaths Fix [MDB IGNORE]
  tools/UpdatePaths/Scripts/10047_vendor_fix.txt
  tools/UpdatePaths/Scripts/10182_NEWFOODplants.txt
  tools/UpdatePaths/Scripts/10193_NEWFOODpies.txt
  tools/UpdatePaths/Scripts/10204_NEWFOODoatmealsalad.txt
  tools/UpdatePaths/Scripts/10262_NEWFOODPackaged.txt
  tools/UpdatePaths/Scripts/10262_NEWFOODsandwiches.txt
  tools/UpdatePaths/Scripts/10263_NEWFOODcanned.txt
  tools/UpdatePaths/Scripts/10263_NEWFOODpackaged.txt
  tools/UpdatePaths/Scripts/10276_floor_resprite.txt
  tools/UpdatePaths/Scripts/10277_NEWFOODsweets.txt
  tools/UpdatePaths/Scripts/10286_NEWFOODfrozen.txt
  tools/UpdatePaths/Scripts/10287_NEWFOODeggs
  tools/UpdatePaths/Scripts/10287_NEWFOODeggs.txt
  tools/UpdatePaths/Scripts/10288_NEWFOODsweets.txt
  tools/UpdatePaths/Scripts/10492_NEWFOOD_all.txt
  tools/UpdatePaths/Scripts/1707_clothingunderrepath.txt
  tools/UpdatePaths/Scripts/8748_NEWFOOD_cakebreadnoodle.txt
  tools/UpdatePaths/Scripts/9337_inventory_adjustments.txt
  tools/UpdatePaths/Scripts/9428_cockroach.txt
  tools/UpdatePaths/Scripts/9860-NEWFOODpizzaburger.txt
  tools/UpdatePaths/Scripts/9860_NEWFOODpizzaburger.txt
  tools/UpdatePaths/Scripts/9864_weightlifter.txt
  tools/UpdatePaths/Scripts/9909_NEWFOODdoughmexican.txt
  tools/UpdatePaths/Scripts/9937_NEWFOODpastries.txt
  tools/UpdatePaths/Scripts/9949_knives.txt
  tools/UpdatePaths/Scripts/9951_NEWFOODmeats
  tools/UpdatePaths/Scripts/9951_NEWFOODmeats.txt
  tools/UpdatePaths/Scripts/9989_emitter_anchored.txt
  tools/UpdatePaths/Scripts/9994_knives.txt
  tools/UpdatePaths/__main__.py
Labels: Mapping, Tools

#10501 Update CODEOWNERS
  .github/CODEOWNERS
Labels: GitHub

#10363 BeeShop Bug Fixes - White Hoodie and Dope necklace
  code/modules/client/loadout/loadout_accessories.dm
  code/modules/client/loadout/loadout_suit.dm
  code/modules/clothing/neck/_neck.dm
  icons/mob/neck.dmi
  icons/obj/clothing/neck.dmi
Labels: Feature, Sprites, Fix

#10512 Fix ByondUI zombies causing lag
  tgui/packages/tgui/backend.ts
  tgui/packages/tgui/components/ByondUi.js
Labels: Fix, TGUI-Changes, Somewhat Important

#10508 Raw Khinkali can be cooked again
  code/game/objects/items/food/meatdish.dm
Labels: Fix

#10502 GenPop workshop alignment and air disto removal
  _maps/holodeck/workshop/donut.dmm
  _maps/holodeck/workshop/plush.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Mapping, Fix

#10497 Portable Seed Extractor now has an action button
  code/datums/action.dm
  code/game/objects/items/storage/bags.dm
Labels: Feature

#10510 Fixes the heavy-duty saline drip getting the wrong icon
  code/game/machinery/iv_drip.dm
Labels: Fix

#10525 Fix ghosts being able to interact with the holoparasite HUD
  code/_onclick/hud/holoparasite.dm
  code/modules/holoparasite/abilities/lesser/snares.dm
  code/modules/holoparasite/abilities/lesser/telepathy.dm
  code/modules/holoparasite/abilities/lesser/teleport.dm
  code/modules/holoparasite/abilities/major/assassin.dm
  code/modules/holoparasite/abilities/major/explosive.dm
  code/modules/holoparasite/abilities/major/scout.dm
Labels: Fix

#10524 Fix heretics getting themselves as a sacrifice target
  code/modules/antagonists/heretic/heretic_antag.dm
Labels: Fix

#10522 Ushanka sprite fix
  icons/mob/clothing/head.dmi
Labels: Sprites, Fix

#10371 Washing Machine - Coolification Expansion
  code/__DEFINES/dye_keys.dm
  code/datums/looping_sounds/machinery_sounds.dm
  code/game/machinery/washing_machine.dm
  code/game/objects/items/manuals.dm
  code/modules/clothing/gloves/_gloves.dm
  code/modules/clothing/gloves/color.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/soft_caps.dm
  code/modules/clothing/shoes/_shoes.dm
  code/modules/clothing/shoes/color.dm
  code/modules/clothing/under/_under.dm
  code/modules/clothing/under/accessories.dm
  code/modules/clothing/under/color.dm
  code/modules/clothing/under/costume.dm
  code/modules/clothing/under/jobs/cargo.dm
  code/modules/clothing/under/jobs/civilian/civilian.dm
  code/modules/clothing/under/jobs/civilian/clown_mime.dm
  code/modules/clothing/under/jobs/civilian/curator.dm
  code/modules/clothing/under/jobs/command.dm
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/clothing/under/jobs/medical.dm
  code/modules/clothing/under/jobs/rnd.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/skirt_dress.dm
  code/modules/clothing/under/suits.dm
  code/modules/hydroponics/grown/banana.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/stamps.dm
  code/modules/projectiles/guns/energy/laser.dm
  icons/mob/clothing/feet.dmi
  icons/mob/clothing/hands.dmi
  icons/mob/clothing/head.dmi
  icons/mob/clothing/uniform.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/uniforms.dmi
  sound/machines/washingmachine/washingmachineend.ogg
  sound/machines/washingmachine/washingmachinestart.ogg
  sound/machines/washingmachine/washingmid1.ogg
  sound/machines/washingmachine/washingmid2.ogg
  sound/machines/washingmachine/washingmid3.ogg
  sound/machines/washingmachine/washingmid4.ogg
  sound/machines/washingmachine/washingmid5.ogg
  sound/machines/washingmachine/washingmid6.ogg
  sound/machines/washingmachine/washingmid7.ogg
  sound/machines/washingmachine/washingmid8.ogg
Labels: Tweak, Feature, Sprites, Fix, Sound, Code Improvement

#10538 Solene Forgot the License.txt
  sound/effects/license.txt
Labels: Feature, Sound, Code Improvement

#10478 Adds unused clothing to drobes and brig phys winter coat to loadout
  code/modules/client/loadout/loadout_suit.dm
  code/modules/vending/autodrobe.dm
  code/modules/vending/clothesmate.dm
Labels: Tweak, Feature

#10516 Fixed bug with catwalks
  code/game/objects/structures/catwalk.dm
Labels: Fix

#10460 Fixes RCDs not being able to build an airlock/windoor in tiles with a Firedoor
  code/game/turfs/open/floor.dm
Labels: Fix

#10479 Changed the Labour Shuttle and Added Recharger
  _maps/map_files/Mining/Lavaland.dmm
  _maps/shuttles/labour/labour_box.dmm
  _maps/shuttles/labour/labour_corg.dmm
  _maps/shuttles/labour/labour_delta.dmm
  _maps/shuttles/labour/labour_fland.dmm
  _maps/shuttles/labour/labour_kilo.dmm
  code/datums/components/gps.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/objects/items/devices/gps.dm
  code/modules/jobs/job_types/exploration_team.dm
  icons/obj/telescience.dmi
Labels: Mapping, Tweak, Feature, Sprites, Balance/Rebalance, Code Improvement

#10541 Ushanka fix! (properly this time)
  icons/mob/clothing/head.dmi
Labels: Sprites, Fix

#10545 Brig Phys Medbay Mech Access
  code/modules/jobs/job_types/brig_physician.dm
Labels: Tweak

#10544 Lowers zombie infection chance when hit
  code/modules/zombie/items.dm
Labels: Tweak

#10553 Fixed Detectives Office and AI Upload Connection
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Mapping, Fix

#10469 Left-click unequips trashbags now
  code/datums/components/storage/storage.dm
Labels: Tweak

#10450 Converts blob overmind shield to update_appearance
  code/modules/antagonists/blob/structures/shield.dm
Labels: Code Improvement

#10504 Optimises ISEVEN() , ISODD() macro
  code/__DEFINES/maths.dm
Labels: Code Improvement

#10558 Re-adds voltaic to the list of languages multilingual quirk users can choose.
  code/__DEFINES/language.dm
Labels: Tweak, Feature, Fix

#10557 Adds prefabs
  _maps/Prefab/Departments.dmm
Labels: Mapping, Feature, :ballot_box_with_check: Good PR

#10483 KiloStation Medbay Rework 4 PR and FINAL
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Mapping, Tweak, Feature

#10550 Fland genpop update
  _maps/Prefab/RandomMapHelper.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  code/__byond_version_compat.dm
Labels: Mapping, Tweak, Feature

#10543 Fixed Kilostation security.
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Mapping, Fix
