Repository BeeStation/BeeStation-Hornet, pull requests merged in 2024-03, with the labels that each got.

#10665 Ombre haircut tweak
  icons/mob/human_face.dmi
Labels: Feature, Sprites

#10669 Ports a big ass comically large lollipop from /TG/Station
  code/game/objects/items/food/sweets.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/vending/snack.dm
  icons/mob/inhands/misc/food_lefthand.dmi
  icons/mob/inhands/misc/food_righthand.dmi
  icons/obj/food/food.dmi
  icons/obj/food/lollipop.dmi
Labels: Feature, Sprites

#10362 Fixes a runtime related to brig doors and a runtime related to roaches
  code/game/machinery/doors/brigdoors.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/mob/living/basic/vermin/cockroach.dm
Labels: Fix

#10661 Gives pepperclouds another charge
  code/game/objects/items/peppercloud.dm
Labels: Balance/Rebalance

#10666 Another Minor Spelling Mistake: Camouflage
  code/__DEFINES/status_effects.dm
  code/datums/status_effects/buffs.dm
Labels: Fix

#10679 Medbot patches
  code/modules/mob/living/simple_animal/bot/medbot.dm
  code/modules/modular_computers/hardware/job_disk.dm
Labels: Tweak, Feature

#10684 Removes innappropriate word from config
  strings/phobia.json
Labels: Removal

#10448 [RECOUP] Componentizes bloody soles, converts to update_appearance, ports blood decal improvements & Unit Tests to prevent regression
  beestation.dme
  code/__DEFINES/blood.dm
  code/__DEFINES/dcs/signals/signals_datum/signals_datum.dm
  code/__DEFINES/dcs/signals/signals_mob/signals_carbon.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/type2type.dm
  code/datums/components/bloodysoles.dm
  code/datums/components/forensics.dm
  code/datums/components/infective.dm
  code/datums/traits/positive_quirk.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/effects/decals/cleanable/humans.dm
  code/game/objects/effects/decals/cleanable/robots.dm
  code/game/objects/items/stacks/sheets/mineral/glass.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/shoes/_shoes.dm
  code/modules/mob/living/blood.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/mob.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/bloody_footprints.dm
  code/modules/unit_tests/unit_test.dm
Labels: Tweak, Feature, Fix

#10555 Customize your milk!
  code/datums/components/udder.dm
  code/modules/admin/view_variables/topic_basic.dm
  code/modules/mob/living/simple_animal/friendly/snake.dm
Labels: Feature, Fix, Administration, Removal, Code Improvement

#10691 [Hotfix] Fix cyborg glass
  code/game/objects/items/stacks/sheets/mineral/glass.dm
Labels: Fix

#10682 Fixes telekinesis mutation throwing runtime when a holder touches an airlock
  code/game/machinery/doors/door.dm
  code/modules/jobs/access.dm
Labels: Fix, Code Improvement

#10699 Fixes moths not being able to eat clothes
  code/datums/armor.dm
  code/modules/clothing/clothing.dm
  code/modules/unit_tests/food_edibility_check.dm
Labels: Fix

#10701 Reverts the removal of `get_recipes()`, fixes basemat recipes
  code/controllers/subsystem/materials.dm
  code/datums/materials/_material.dm
  code/game/objects/items/stacks/ores/ore_type.dm
  code/game/objects/items/stacks/rods/rods.dm
  code/game/objects/items/stacks/sheets/mineral/exotics.dm
  code/game/objects/items/stacks/sheets/mineral/glass.dm
  code/game/objects/items/stacks/sheets/mineral/materials.dm
  code/game/objects/items/stacks/sheets/mineral/metals.dm
  code/game/objects/items/stacks/sheets/miscellaneous/miscellaneous_mats.dm
  code/game/objects/items/stacks/sheets/organic/cloths.dm
  code/game/objects/items/stacks/sheets/organic/hides.dm
  code/game/objects/items/stacks/sheets/organic/leather.dm
  code/game/objects/items/stacks/sheets/organic/miscellaneous_organics.dm
  code/game/objects/items/stacks/sheets/organic/wood.dm
  code/game/objects/items/stacks/stack.dm
  code/modules/power/cable.dm
Labels: Fix, Code Improvement

#10700 Adds medbot beaker logging
  code/modules/mob/living/simple_animal/bot/medbot.dm
Labels: Feature

#10707 removes a duplicate hair style, which also was called a slur in the code
  code/modules/mob/dead/new_player/sprite_accessories.dm
Labels: Removal

#10692 Replace "Red Dead Redemption Two" and "Yanye Kest" from clown random name gen.
  strings/names/clown.txt
Labels: Config Update

#10601 Echo Station Minimap
  code/game/objects/structures/signs/signs_maps.dm
  icons/obj/decals.dmi
Labels: Feature, Sprites

#10695 Hunts the elusive fland hallway lightswitch to extinction
  _maps/map_files/FlandStation/FlandStation.dmm
Labels: Mapping, Removal, 🔑 Close Key (1/3)

#10674 Fixes bug in area initialization code and removes obsolete forced dynamic lighting flag
  code/__DEFINES/lighting.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas.dm
  code/game/area/areas/centcom.dm
  code/game/area/areas/holodeck.dm
  code/game/area/areas/ruins/_ruins.dm
  code/game/area/areas/shuttles.dm
  code/modules/awaymissions/mission_code/Cabin.dm
  code/modules/awaymissions/mission_code/TheFactory.dm
  code/modules/awaymissions/mission_code/snowdin.dm
  code/modules/mining/equipment/survival_pod.dm
  code/modules/research/xenobiology/crossbreeding/warping.dm
  code/modules/ruins/spaceruin_code/hilbertshotel.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/loot/alien_artifact.dm
Labels: Fix, Code Improvement

#10683 Fixes runtime `items.dm, line 420: Cannot read null.len`
  code/game/objects/items.dm
Labels: Fix

#10673 Adds a new moth wing and antennae type: Strawberry
  code/modules/mob/dead/new_player/sprite_accessories.dm
  icons/mob/moth_antennae.dmi
  icons/mob/moth_wings.dmi
  icons/mob/moth_wingsopen.dmi
Labels: Feature, Sprites

#10715 Roundstart cyborgs are no longer RRed if deconstructed or gibbed
  code/modules/mob/living/brain/MMI.dm
  code/modules/mob/living/brain/brain_item.dm
Labels: Fix

#10711 Newfood customfood
  beestation.dme
  code/__DEFINES/dcs/flags.dm
  code/__DEFINES/dcs/signals/signals_atom.dm
  code/__DEFINES/dcs/signals/signals_obj/signals_item/signals_food.dm
  code/__DEFINES/flags.dm
  code/__DEFINES/traits.dm
  code/datums/components/customizable_reagent_holder.dm
  code/datums/components/food/edible.dm
  code/game/atoms.dm
  code/game/objects/items/food/bread.dm
  code/game/objects/items/food/burgers.dm
  code/game/objects/items/food/dough.dm
  code/game/objects/items/food/pizza.dm
  code/game/objects/items/food/salad.dm
  code/game/objects/items/food/spaghetti.dm
  code/modules/reagents/chemistry/holder.dm
Labels: Feature

#10635 Adds a new Banning Panel made with TGUI
  code/modules/admin/admin_verbs.dm
  code/modules/admin/holder2.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/admin/topic.dm
  tgui/packages/tgui/interfaces/BanningPanel.js
Labels: Administration, TGUI-Changes

#10724 Fixes conflicting holodeck program IDs
  code/modules/holodeck/holodeck_map_templates.dm
Labels: Fix, :ballot_box_with_check: Good PR

#10563 Refactor height & Introduce species heights
  code/__DEFINES/DNA.dm
  code/__DEFINES/mobs.dm
  code/datums/dna.dm
  code/modules/client/preferences/preferences.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/apid.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/mob/living/carbon/human/species_types/psyphoza.dm
  code/modules/unit_tests/preferences.dm
  icons/effects/64x64.dmi
Labels: Tweak, Feature, Sprites, Code Improvement

#10725 Allow movement when getting up from the ground
  code/modules/mob/living/living.dm
Labels: Balance/Rebalance

#10744 Ban severity hotfix
  code/modules/admin/sql_ban_system.dm
Labels: Fix, Administration

#10584 Bioscanners, Health analyzer nerfs, and more
  _maps/RuinGeneration/17x17_charliecrew.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  beestation.dme
  code/datums/components/crafting/recipes.dm
  code/datums/looping_sounds/machinery_sounds.dm
  code/game/gamemodes/gangs/gang_items.dm
  code/game/machinery/bioscanner.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/cargo/packs.dm
  code/modules/jobs/job_mail.dm
  code/modules/mob/living/simple_animal/bot/construction.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  code/modules/modular_computers/file_system/programs/phys_scanner.dm
  code/modules/modular_computers/hardware/job_disk.dm
  code/modules/research/designs/autolathe_designs.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/research/xenobiology/crossbreeding/warping.dm
  code/modules/vending/medical.dm
  code/modules/xenoarchaeology/traits/xenoartifact_majors.dm
  icons/obj/cryogenic2.dmi
  tgui/packages/tgui/interfaces/Bioscanner.js
Labels: Mapping, Feature, Sprites, Balance/Rebalance, Removal, TGUI-Changes, Needs Approval

#10749 Emergency Bioscanner fixes
  _maps/map_files/EchoStation/EchoStation.dmm
  code/game/machinery/cryopod.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Mapping, Feature

#10622 Stops oozelings and IPCs dying due to handshakes with an elder god.
  code/modules/antagonists/heretic/knowledge/sacrifice_knowledge/sacrifice_knowledge.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Feature, Fix

#10742 Fixes cult halo doesn't disappear on a deconverted
  code/modules/antagonists/cult/cult.dm
Labels: Feature, Fix, Code Improvement

#10620 Ports the fixed version of TG felinid tailwagging
  icons/mob/mutant_bodyparts.dmi
Labels: Tweak, Sprites

#10763 Hotfix CID check in the Banning Panel
  code/modules/admin/sql_ban_system.dm
Labels: Fix, Administration

#10757 Makes the Stethoscope printable at the Medical lathe
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature

#10762 Makes the compact remote actually compact
  code/modules/wiremod/shell/compact_remote.dm
Labels: Tweak

#10737 adds a library scanner to radstation
  _maps/map_files/RadStation/RadStation.dmm
Labels: Mapping, Feature

#10624 Corg brig remake
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: Mapping, Tweak, Sprites, Sound

#10755 Revert "Bioscanners, Health analyzer nerfs, and more"
  _maps/RuinGeneration/17x17_charliecrew.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/EchoStation/EchoStation.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  beestation.dme
  code/datums/components/crafting/recipes.dm
  code/datums/looping_sounds/machinery_sounds.dm
  code/game/gamemodes/gangs/gang_items.dm
  code/game/machinery/bioscanner.dm
  code/game/machinery/cryopod.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/cargo/packs.dm
  code/modules/jobs/job_mail.dm
  code/modules/mob/living/simple_animal/bot/construction.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  code/modules/modular_computers/file_system/programs/phys_scanner.dm
  code/modules/modular_computers/hardware/job_disk.dm
  code/modules/research/designs/autolathe_designs.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/research/xenobiology/crossbreeding/warping.dm
  code/modules/vending/medical.dm
  code/modules/xenoarchaeology/traits/xenoartifact_majors.dm
  icons/obj/cryogenic2.dmi
  tgui/packages/tgui/interfaces/Bioscanner.js
Labels: Mapping, Test Merged, Sprites, Removal, TGUI-Changes

#10771 Explosion Custom Size is saved in the Supply Pod launcher
  code/modules/cargo/centcom_podlauncher.dm
Labels: Fix

#10776 Fixes plumbing grinder can grind maint pills (floorpills)
  code/modules/plumbing/plumbers/grinder_chemical.dm
Labels: Fix

#10784 Added maze dimension to list of areas shelters cannot be deployed in
  code/modules/mining/shelters.dm
Labels: Tweak

#10753 Medbots can now be more easily re-coloured, cargo medbots now spawn filled, cargo now has a bica-kelo-antox chembag crate
  code/modules/cargo/packs.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  code/modules/reagents/reagent_containers/chem_bag.dm
  code/modules/reagents/reagent_containers/glass.dm
Labels: Feature

#10617 Adds a layer manifold on every gas outlets for every atmos + Boxstation atmos QoL change
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
Labels: Mapping, Tweak

#10759 RadStation Fixes and Minor changes
  _maps/map_files/RadStation/RadStation.dmm
Labels: Mapping, Tweak, Fix

#10770 Gives Radstation's maintenance bar closet the correct carpets
  _maps/map_files/RadStation/RadStation.dmm
Labels: Mapping, Fix

#10779 Fixes Revenant ingame info inaccuracies + minor rev fixes + prevent rev spawning on holytile
  code/__HELPERS/turfs.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/modules/antagonists/revenant/revenant.dm
  code/modules/antagonists/revenant/revenant_abilities.dm
  code/modules/antagonists/revenant/revenant_spawn_event.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Fix

#10793 Fixes leather recipes; A stack of "Initialize"?
  code/game/objects/items/stacks/sheets/organic/leather.dm
Labels: Fix

#10787 sensitive/apathetic only effect bad moodlets
  code/datums/components/mood.dm
  code/datums/traits/negative_quirk.dm
  code/datums/traits/positive_quirk.dm
Labels: Tweak, Needs Wiki Changes

#10243 Ports dbcore refactor, and limits the maximum amount of concurrent async queries to a variable amount
  beestation.dme
  code/__DEFINES/database.dm
  code/__DEFINES/subsystems.dm
  code/__HELPERS/roundend.dm
  code/controllers/configuration/entries/dbconfig.dm
  code/controllers/subsystem/achievements.dm
  code/controllers/subsystem/ban_cache.dm
  code/controllers/subsystem/blackbox.dm
  code/controllers/subsystem/dbcore.dm
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/stickyban.dm
  code/controllers/subsystem/time_track.dm
  code/datums/achievements/_achievement_data.dm
  code/datums/achievements/_awards.dm
  code/datums/world_topic.dm
  code/game/gamemodes/game_mode.dm
  code/modules/admin/admin_ranks.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/create_poll.dm
  code/modules/admin/ipintel.dm
  code/modules/admin/permissionedit.dm
  code/modules/admin/poll_management.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/admin/sql_message_system.dm
  code/modules/admin/stickyban.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/mentors_edit.dm
  code/modules/client/antag_tokens.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences/serialization/preferences_character.dm
  code/modules/client/preferences/serialization/preferences_database.dm
  code/modules/client/preferences/serialization/preferences_player.dm
  code/modules/jobs/job_exp.dm
  code/modules/library/lib_machines.dm
  code/modules/library/random_books.dm
  code/modules/mentor/mentor_loading.dm
  code/modules/metacoin/metacoin.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/dead/new_player/poll.dm
  code/modules/shuttle/emergency.dm
  config/dbconfig.txt
  tools/savefileimporter/code/character_parser.dm
  tools/savefileimporter/code/dbcore.dm
  tools/savefileimporter/code/savefile_parser.dm
  tools/savefileimporter/code/world.dm
Labels: Config Update, Administration, Tools, Server, Testmerge Passed

#10721 Stun baton rebalancing
  code/game/objects/items/stunbaton.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
Labels: Balance/Rebalance, Testmerge Passed

#10097 Botfixes: Cleans up the worst bot in the game, Floorbots
  code/__DEFINES/traits.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/stacks/tiles/light.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/turfs/open/floor/plating.dm
  code/game/turfs/open/floor/reinf_floor.dm
  code/modules/mob/living/simple_animal/bot/floorbot.dm
  sound/effects/whistlereset.ogg
Labels: Feature, Fix, Refactor, Sound, hacktoberfest-accepted

#10769 Adds the black beret to the beecoin shop
  _maps/_basemap.dm
  code/modules/client/loadout/loadout_hat.dm
Labels: Mapping, Feature

#10795 Ports Complete resprites for bread
  beestation.dme
  code/_onclick/hud/drones.dm
  code/game/objects/items/food/bread.dm
  code/game/objects/items/food/sandwichtoast.dm
  icons/obj/food/burgerbread.dmi
  icons/obj/food/food.dmi
  icons/obj/food/meat.dmi
Labels: Feature, Sprites

#10112 Police Tonfa - Sec Stun Baton alternative
  code/game/objects/items/melee/misc.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  code/modules/vending/security.dm
  icons/mob/inhands/equipment/security_lefthand.dmi
  icons/mob/inhands/equipment/security_righthand.dmi
  icons/obj/items_and_weapons.dmi
Labels: Sprites, hacktoberfest-accepted

#10147 Refactor uplink: Shows effective TC use, better logic for illegal tech flag to items, etc
  code/datums/components/uplink.dm
  code/game/atoms.dm
  code/modules/antagonists/incursion/incursion.dm
  code/modules/antagonists/nukeop/nukeop.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/uplink/uplink_items.dm
  code/modules/uplink/uplink_purchase_log.dm
  tgui/packages/tgui/interfaces/Uplink.js
Labels: Tweak, Balance/Rebalance, Refactor, Code Improvement, TGUI-Changes

#10801 4 new lobby screens
  config/title_screens/images/bar.dmi
  config/title_screens/images/engi_party.dmi
  config/title_screens/images/sunset.dmi
Labels: Feature, Config Update
