Repository BeeStation/BeeStation-Hornet, pull requests merged in 2024-07, with the labels that each got.

#11138 adds a floorlight to every abductor pod
  _maps/map_files/generic/CentCom.dmm
Labels: Mapping, Feature, Fix

#11146 Ports bad catwalk layering fix
  code/controllers/subsystem/minor_mapping.dm
  code/datums/components/plumbing/_plumbing.dm
  code/datums/elements/undertile.dm
  code/game/objects/items/devices/pressureplates.dm
  code/game/turfs/open/floor/catwalk_plating.dm
  code/game/turfs/turf.dm
  code/modules/atmospherics/machinery/components/components_base.dm
Labels: Fix, Refactor

#11133 Adminbus now innately has the ability to remove a mob's blocked language from the list of blocked languages.
  code/modules/language/language_menu.dm
Labels: Feature

#11153 Brig Medical Reduction V2 - Not Forgotten Edition
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/EchoStation/EchoStation.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Mapping, Tweak, Feature, Balance/Rebalance, Removal, Balance Approved

#11127 Prevent drifting while not on a turf
  code/datums/components/drift.dm
Labels: Fix

#11164 Fixes hallucination runtime for chameleon item
  code/modules/mob/living/carbon/human/say.dm
Labels: Fix

#11131 [BUGFIX] Emotes that begin with apostrophes and commas no longer leave a space
  code/datums/emotes.dm
  code/game/say.dm
Labels: Fix

#11122 Fixed swarmer traps not dealing any stamina damage.
  code/modules/antagonists/swarmer/swarmer.dm
Labels: Fix

#11130 Paperframe recipe needs less stuff / Paper bundle tweak
  code/datums/components/crafting/recipes.dm
  code/modules/paperwork/paperbin.dm
Labels: Tweak, Feature

#11112 Digitigrade Lizards will no longer experience Toe Stubbing
  code/game/objects/structures/tables_racks.dm
Labels: Balance/Rebalance

#11119 Mechs will now knock people down on melee, rather than make them unconcious.
  code/modules/vehicles/mecha/mech_melee_attack.dm
Labels: Removal, i ded

#10908 Improves client.eye system + advanced camera now accepts observing of mobs
  code/game/atoms.dm
  code/game/machinery/computer/camera_advanced.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/bloodcrawl.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/pai/pai_shell.dm
  code/modules/mob/login.dm
  code/modules/mob/mob.dm
  code/modules/spells/spell_types/devil.dm
Labels: Tweak, Fix, Code Improvement, Testmerge Passed

#11140 Fixes Radstation security disposals.
  _maps/map_files/RadStation/RadStation.dmm
Labels: Mapping, Fix

#11137 Rad Station Decal Fixes
  _maps/map_files/RadStation/RadStation.dmm
  icons/turf/decals.dmi
Labels: Mapping, Sprites, Fix

#11115 Removes the Security item spawner and captain spawner from random-maintenance
  _maps/RandomRooms/5x4/rdm_captain_quarters.dmm
Labels: Mapping, Tweak, Removal

#11151 Corg/fland Glass tiles / catwalks / decal changes
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
Labels: Mapping, Feature, Fix

#11168 Empty Variable for Storage Items
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/items/storage/storage.dm
Labels: Tweak, Code Improvement

#11074 [BUGFIX] Carbons have to be neckgrabbed to be considered incapacitated like before (Fixes Piggybacking)
  code/modules/mob/living/living.dm
Labels: Fix

#11109 Makes you able to butt out cigarettes on people
  code/game/objects/items/cigs_lighters.dm
Labels: Tweak, Feature

#11092 Minor Map Fixes
  _maps/RandomRuins/LavaRuins/lavaland_surface_seed_vault.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/EchoStation/EchoStation.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  _maps/shuttles/emergency/emergency_tiny.dmm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
Labels: Mapping, Tweak, Feature, Fix, Balance/Rebalance

#10452 Removes from existence once and for all the experimentor
  _maps/RandomZLevels/snowdin.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/EchoStation/EchoStation.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/map_files/RadStation/RadStation.dmm
  _maps/shuttles/whiteship/whiteship_delta.dmm
  beestation.dme
  code/__DEFINES/logging.dm
  code/_globalvars/lists/maintenance_loot.dm
  code/controllers/subsystem/research.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/manuals.dm
  code/game/objects/items/peppercloud.dm
  code/modules/admin/admin_investigate.dm
  code/modules/cargo/bounties/assistant.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/experimentor.dm
  code/modules/research/rdconsole.dm
  code/modules/research/rdmachines.dm
  code/modules/research/techweb/all_nodes.dm
  icons/obj/assemblies.dmi
  strings/cas_white.txt
Labels: Mapping, Feature, Sprites, Administration, Removal

#11177 Adds a Sprite for Wearing the Doctor's Bag
  code/game/objects/items/storage/firstaid.dm
  icons/mob/clothing/belt.dmi
Labels: Feature, Sprites

#11172 Revert "Fix mentor deadminning and admin loading"
  code/modules/admin/holder2.dm
  code/modules/mentor/mentor.dm
  code/modules/mentor/mentor_loading.dm
Labels: Fix, Administration

#11171 Fix "Bureaucratic Error" event runtime
  code/modules/events/bureaucratic_error.dm
Labels: Fix

#11107 Makes revolution objectives softer
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/revolution/revolution.dm
  code/game/objects/items/manuals.dm
  code/modules/antagonists/revolution/revolution.dm
Labels: Balance/Rebalance, Testmerge Passed

#10827 Pirate ship Remake
  _maps/shuttles/pirate/pirate_default.dmm
  code/game/objects/effects/decals/misc.dm
  code/game/objects/structures/fluff.dm
Labels: Mapping, Tweak

#11183 fix white & textured tiles
  icons/turf/floors.dmi
Labels: Sprites, Fix

#11072 HoS and Captain's guns now show when they've been blown up
  code/modules/projectiles/guns/energy/energy_gun.dm
  code/modules/projectiles/guns/energy/laser.dm
  icons/obj/guns/energy.dmi
Labels: Tweak, Sprites, Fix

#10832 [PORT] Allows admins to skip some paper sanitization
  code/modules/admin/admin_fax_panel.dm
  code/modules/paperwork/paper.dm
  tgui/packages/tgui/interfaces/AntagInfoBrainwashed.tsx
  tgui/packages/tgui/interfaces/AntagInfoHoloparasite.tsx
  tgui/packages/tgui/interfaces/PaperSheet.tsx
  tgui/packages/tgui/interfaces/common/ObjectiveSection.tsx
  tgui/packages/tgui/sanitize.js
Labels: Administration, TGUI-Changes

#11145 Ports genericized carbon disarms
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/monkey/monkey_defense.dm
Labels: Code Improvement

#11097 Ports TG centcom outfits
  _maps/RandomRuins/SpaceRuins/oldAIsat.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/shuttles/whiteship/whiteship_delta.dmm
  code/controllers/subsystem/traumas.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/admin/battle_royale.dm
  code/modules/awaymissions/corpse.dm
  code/modules/clothing/head/hat.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/wintercoats.dm
  code/modules/clothing/under/jobs/centcom.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/objective_types/vip_extraction.dm
  code/modules/vending/clothesmate.dm
  code/modules/vending/wardrobes.dm
  icons/mob/clothing/head/hats.dmi
  icons/mob/clothing/head/winterhood.dmi
  icons/mob/clothing/mask.dmi
  icons/mob/clothing/suits/armor.dmi
  icons/mob/clothing/suits/jacket.dmi
  icons/mob/clothing/suits/wintercoat.dmi
  icons/mob/clothing/under/centcom.dmi
  icons/obj/clothing/head/hats.dmi
  icons/obj/clothing/head/winterhood.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/suits/armor.dmi
  icons/obj/clothing/suits/jacket.dmi
  icons/obj/clothing/suits/wintercoat.dmi
  icons/obj/clothing/under/centcom.dmi
  icons/obj/vending.dmi
  tools/UpdatePaths/Scripts/1707_clothingunderrepath.txt
Labels: Mapping, Feature, Sprites, Administration, Tools

#11136 Removes a bad word from a poster
  _maps/map_files/FlandStation/FlandStation.dmm
  code/game/objects/effects/contraband.dm
Labels: Mapping, Tweak, 🔑 Close Key (1/3)

#10876 Ports TG's Fit Viewport fix
  code/__byond_version_compat.dm
  code/datums/view.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/verbs/ooc.dm
Labels: Feature, Fix, Code Improvement

#10859 Basemats: Alloy Support
  beestation.dme
  code/__DEFINES/dcs/signals/signals_obj/signals_object.dm
  code/__DEFINES/materials.dm
  code/_globalvars/bitfields.dm
  code/controllers/subsystem/materials.dm
  code/datums/components/material_container.dm
  code/datums/components/remote_materials.dm
  code/datums/elements/obj_regen.dm
  code/datums/materials/_material.dm
  code/datums/materials/alloys.dm
  code/datums/materials/basemats.dm
  code/datums/materials/meat.dm
  code/game/atoms.dm
  code/game/machinery/droneDispenser.dm
  code/game/machinery/fabricators/exosuit_fab.dm
  code/game/machinery/fabricators/modular_fabricator.dm
  code/game/machinery/recycler.dm
  code/game/machinery/sheetifier.dm
  code/game/objects/items/stacks/sheets/mineral/exotics.dm
  code/game/objects/items/stacks/sheets/mineral/glass.dm
  code/game/objects/items/stacks/sheets/mineral/materials.dm
  code/game/objects/items/stacks/sheets/mineral/metals.dm
  code/game/objects/items/stacks/tiles/tile_mineral.dm
  code/game/objects/obj_defense.dm
  code/modules/antagonists/swarmer/swarmer.dm
  code/modules/clothing/shoes/bananashoes.dm
  code/modules/mining/machine_processing.dm
  code/modules/mining/machine_redemption.dm
  code/modules/mining/machine_silo.dm
  code/modules/research/machinery/_production.dm
  icons/obj/beds_chairs/chairs.dmi
Labels: Feature, Sprites, Code Improvement

#11190 Reconsiders my trust in players in regards to VIP Missions, fixes admin mald
  code/modules/clothing/outfits/standard.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/objective_types/vip_extraction.dm
Labels: Tweak

#11169 tonfa now paralyses rather than sleeps
  code/game/objects/items/melee/misc.dm
Labels: Tweak

#11170 Mimites - Mimic based creatures and their midround event
  beestation.dme
  code/__DEFINES/is_helpers.dm
  code/game/alternate_appearance.dm
  code/modules/events/mimite_infestation.dm
  code/modules/mob/living/simple_animal/hostile/mimite.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  icons/mob/animal.dmi
Labels: Feature, Sprites

#11180 freezing now cures advanced mutation toxin
  code/datums/diseases/transformation.dm
Labels: Balance/Rebalance

#11193 Fixes "A Positronic brain has been created in null!"
  code/game/machinery/fabricators/modular_fabricator.dm
  code/modules/mob/dead/new_player/new_player.dm
Labels: Fix, Code Improvement

#11191 Fix: Modular fabricators dumping ore silos onto the floor
  code/game/machinery/fabricators/modular_fabricator.dm
Labels: Fix

#11196 Fixes ody mechs hud removal
  code/modules/vehicles/mecha/medical/odysseus.dm
Labels: Fix

#11194 Mimite Runtime Fixes, Mob Balancing, and more.
  code/_globalvars/lists/mobs.dm
  code/modules/events/mimite_infestation.dm
  code/modules/mob/living/simple_animal/hostile/mimite.dm
Labels: Tweak, Feature, Fix, Balance/Rebalance

#11207 Mimites, final fixes(hopefully) - Requested by EvilDragon
  code/modules/events/mimite_infestation.dm
  code/modules/mob/living/simple_animal/hostile/mimite.dm
Labels: Feature, Code Improvement

#11206 1 line lightswitch fix
  _maps/map_files/Mining/Lavaland.dmm
  code/game/machinery/lightswitch.dm
  code/game/objects/items/wall_mounted.dm
Labels: Mapping, Fix

#11187 Baton shove now requires disarm intent
  code/game/objects/items/stunbaton.dm
Labels: Tweak

#11208 Added 'divable' var to closets and their logic
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/cargo/supplypod.dm
Labels: Tweak, Feature, Code Improvement

#11211 Fixes the bananium sword causing bleed
  code/game/gamemodes/clown_ops/clown_weapons.dm
Labels: Fix

#11221 Pirate shuttle rebalancing and update
  _maps/shuttles/pirate/pirate_default.dmm
Labels: Mapping, Fix, Balance/Rebalance

#11225 small fix for cameras on explo shuttle
  _maps/shuttles/exploration/exploration_shuttle.dmm
Labels: Mapping

#11220 Small Radstation atmos fix and changes take 2
  _maps/map_files/RadStation/RadStation.dmm
Labels: Mapping, Tweak, Fix

#11182 MetaSec brig retiling
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Mapping, Feature

#11228 Revert "Pirate shuttle rebalancing and update"
  _maps/shuttles/pirate/pirate_default.dmm
Labels: Mapping, Balance/Rebalance, Removal

#11121 Fixed space dragon's gust ability hitting people through walls
  code/modules/mob/living/simple_animal/hostile/space_dragon.dm
Labels: Fix, Balance/Rebalance, 🔑 Close Key (1/3)

#11213 Adds the ability to craft different types of lockers.
  code/datums/components/crafting/recipes.dm
  code/game/objects/items/stacks/sheets/mineral/metals_recipes.dm
  code/game/objects/structures/crates_lockers/closets/secure/personal.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
Labels: Feature

#11231 Prevents Free Range Intercoms from Accessing Syndicate and CentCom Radio Channels
  code/__DEFINES/radio.dm
Labels: Fix

#11237 [PORT] simply ports better cone sprites
  icons/mob/clothing/head/utility.dmi
  icons/obj/janitor.dmi
Labels: Feature, Sprites

#11235 [PORT] ports the shark plushie
  code/datums/mood_events/generic_positive_events.dm
  code/game/machinery/computer/arcade.dm
  code/game/objects/items/plushes.dm
  code/modules/research/xenobiology/crossbreeding/warping.dm
  icons/mob/inhands/plushes_lefthand.dmi
  icons/mob/inhands/plushes_righthand.dmi
  icons/obj/plushes.dmi
Labels: Feature, Sprites

#11245 removes holopad from glass floor on corg
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: Mapping, Fix

#11246 Metastation missing wall
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Mapping, Feature, Fix

#11174 Modsuit prep: Bodyheat Audit & Hardsuit temperature regulators
  code/__DEFINES/atmospherics.dm
  code/__DEFINES/dcs/signals/signals_obj/signals_item/signals_clothing.dm
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/map_popups.dm
  code/_onclick/hud/screen_objects.dm
  code/datums/action.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/objects/items/inducer.dm
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/antagonists/role_preference/role_antagonists.dm
  code/modules/antagonists/role_preference/role_midrounds.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/spacesuits/_spacesuits.dm
  code/modules/clothing/spacesuits/chronosuit.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/spacesuits/syndi.dm
  code/modules/clothing/suits/toggles.dm
  code/modules/mining/equipment/explorer_gear.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/ninja/suit/suit.dm
  code/modules/power/cell.dm
  code/modules/research/xenobiology/crossbreeding/_potions.dm
  code/modules/surgery/organs/lungs.dm
  icons/mob/actions/actions_spacesuit.dmi
  icons/mob/screen_gen.dmi
Labels: Feature, Sprites, Fix

#11184 A handful of circuitry fixes and changes
  code/modules/research/designs/wiremod_designs.dm
  code/modules/wiremod/core/component_printer.dm
  code/modules/wiremod/shell/compact_remote.dm
  code/modules/wiremod/shell/controller.dm
  code/modules/wiremod/shell/drone.dm
  code/modules/wiremod/shell/scanner.dm
  code/modules/wiremod/shell/shell_items.dm
Labels: Fix, Balance/Rebalance, Server

#10968 Makes hacking easier
  code/__DEFINES/airlock.dm
  code/datums/wires/airlock.dm
  code/game/area/Space_Station_13_areas.dm
Labels: Balance/Rebalance

#10231 Supports lighting system for client dir rotation
  icons/effects/lighting_object.dmi
Labels: Feature, Sprites

#11135 Puts clown and mimes in the service department on their job datums
  code/modules/jobs/job_types/clown.dm
  code/modules/jobs/job_types/mime.dm
Labels: Tweak, Fix, Code Improvement, 🔑 Close Key (2/3)

#10992 Modsuit prep: Replace CTF Hardsuits
  code/__DEFINES/colors.dm
  code/datums/components/shielded.dm
  code/datums/greyscale/greyscale_configs.dm
  code/datums/greyscale/json_configs/ctf_light.json
  code/datums/greyscale/json_configs/ctf_light_worn.json
  code/datums/greyscale/json_configs/ctf_standard.json
  code/datums/greyscale/json_configs/ctf_standard_worn.json
  code/modules/antagonists/cult/cult_items.dm
  code/modules/awaymissions/capture_the_flag.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/suits/_suits.dm
  code/modules/clothing/suits/wiz_robe.dm
  icons/mob/clothing/suits/ctf.dmi
  icons/obj/clothing/suits/ctf.dmi
Labels: Feature, Sprites, Code Improvement

#11241 clears boxstation /obj/machinery/camera/autoname aberrations
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
Labels: Mapping, Fix

#11258 Removes Missplaced Skeleton Ghost Spawn
  _maps/RandomRooms/10x10/rdm_dorms.dmm
  _maps/RandomRooms/10x10/sk_rdm170_laser_tag.dmm
Labels: Mapping, Fix

#11224 Makes the metastation brig shuttle area have an exit.
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Mapping, Fix

#11264 HOTFIX Standing/lying state hotfix
  code/__HELPERS/atoms.dm
  code/datums/components/spikes.dm
  code/datums/martial/_martial.dm
  code/datums/martial/boxing.dm
  code/datums/martial/karate.dm
  code/datums/martial/sleeping_carp.dm
  code/game/objects/effects/decals/misc.dm
  code/game/objects/items/teleportation.dm
  code/game/objects/structures/plasticflaps.dm
  code/game/objects/structures/tables_racks.dm
  code/game/turfs/open/_open.dm
  code/modules/antagonists/changeling/powers/adrenaline.dm
  code/modules/antagonists/devil/true_devil/_true_devil.dm
  code/modules/assembly/flash.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/bot/ed209bot.dm
  code/modules/pool/components/swimming.dm
  code/modules/power/supermatter/supermatter.dm
  code/modules/projectiles/projectile.dm
  code/modules/surgery/helpers.dm
  code/modules/tgui/status_composers.dm
Labels: Fix
