Repository BeeStation/BeeStation-Hornet, pull requests merged in 2024-04, with the labels that each got.

#10529 Ports clean qdeletion & handling of progressbars.
  code/__HELPERS/mobs.dm
  code/datums/components/storage/concrete/rped.dm
  code/datums/components/storage/storage.dm
  code/datums/progressbar.dm
  code/game/atoms.dm
  code/game/turfs/turf.dm
  code/modules/antagonists/clock_cult/scriptures/_clockwork_scripture.dm
  code/modules/mob/mob.dm
Labels: Feature, Refactor, Removal, Code Improvement

#10807 CorgStation fixes
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: Mapping, Tweak, Feature, Fix, Removal

#10726 Newfood: I just want to griddle for gods sake
  _maps/RandomRuins/SpaceRuins/Fast_Food.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/EchoStation/EchoStation.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  beestation.dme
  code/__DEFINES/dcs/signals/signals_obj/signals_item/signals_food.dm
  code/__DEFINES/flags.dm
  code/_onclick/click.dm
  code/datums/components/food/edible.dm
  code/datums/components/grillable.dm
  code/datums/looping_sounds/machinery_sounds.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/food/_food.dm
  code/game/objects/items/food/meatdish.dm
  code/game/objects/items/food/meatslab.dm
  code/game/objects/items/food/misc.dm
  code/game/objects/items/food/sandwichtoast.dm
  code/game/objects/obj_defense.dm
  code/modules/admin/verbs/cluwneplayer.dm
  code/modules/food_and_drinks/kitchen_machinery/griddle.dm
  code/modules/food_and_drinks/kitchen_machinery/grill.dm
  code/modules/food_and_drinks/kitchen_machinery/processor.dm
  code/modules/food_and_drinks/recipes/processor_recipes.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_burger.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_sandwich.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/effects/steam.dmi
  icons/obj/food/meat.dmi
  icons/obj/machines/kitchenmachines.dmi
  sound/machines/grill/grillsizzle.ogg
Labels: Mapping, Tweak, Feature, Sprites, Fix, Balance/Rebalance, Sound, Administration, Removal, Code Improvement

#10798 Fixes lighting in Capture The Flag
  code/game/area/areas/centcom.dm
Labels: Fix

#10809 Some poster fixes: hard delete boogaloo
  code/game/objects/effects/contraband.dm
Labels: Fix, Removal

#10772 Adds two new clothes, relaxed slacks and circual sunglasses
  code/modules/client/loadout/loadout_accessories.dm
  code/modules/client/loadout/loadout_uniform.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/clothing/under/suits.dm
  code/modules/vending/autodrobe.dm
  code/modules/vending/clothesmate.dm
  icons/mob/clothing/uniform.dmi
  icons/mob/eyes.dmi
  icons/obj/clothing/glasses.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, Sprites

#10703 Basemats 2: Base Meats, Wood datum, and Tile support
  beestation.dme
  code/__DEFINES/flags.dm
  code/__DEFINES/footsteps.dm
  code/__DEFINES/materials.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/traits.dm
  code/controllers/subsystem/materials.dm
  code/datums/components/butchering.dm
  code/datums/components/crafting/guncrafting.dm
  code/datums/components/food/edible.dm
  code/datums/components/radioactive.dm
  code/datums/materials/_material.dm
  code/datums/materials/basemats.dm
  code/datums/materials/meat.dm
  code/game/machinery/fabricators/modular_fabricator.dm
  code/game/machinery/sheetifier.dm
  code/game/objects/items/cigs_lighters.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/food/meatslab.dm
  code/game/objects/items/kitchen.dm
  code/game/objects/items/shields.dm
  code/game/objects/items/stacks/ores/ore_type.dm
  code/game/objects/items/stacks/sheets/mineral/exotics.dm
  code/game/objects/items/stacks/sheets/mineral/exotics_recipes.dm
  code/game/objects/items/stacks/sheets/mineral/materials.dm
  code/game/objects/items/stacks/sheets/miscellaneous/miscellaneous_mats.dm
  code/game/objects/items/stacks/sheets/organic/wood.dm
  code/game/objects/items/stacks/sheets/sheets.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/items/weaponry.dm
  code/game/objects/structures/artstuff.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/noticeboard.dm
  code/game/turfs/closed/wall/material_walls.dm
  code/game/turfs/closed/wall/mineral_walls.dm
  code/game/turfs/open/floor.dm
  code/game/turfs/open/floor/plating.dm
  code/game/turfs/turf.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/photography/photos/frame.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/materials/composite.dmi
  icons/obj/machines/sheetifier.dmi
  icons/obj/stacks/minerals.dmi
  icons/obj/tiles.dmi
  icons/turf/floors.dmi
  icons/turf/walls/materialwall.dmi
  sound/effects/meatslap.ogg
Labels: Tweak, Feature, Sprites, Sound

#10758 [PORT] VV editor expansions + some changes
  beestation.dme
  code/__DEFINES/_helpers.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/keybinding.dm
  code/__DEFINES/typeids.dm
  code/__DEFINES/vv.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/sanitize_values.dm
  code/_globalvars/colorvars.dm
  code/_globalvars/lists/admin.dm
  code/_onclick/click.dm
  code/controllers/globals.dm
  code/controllers/subsystem/idlenpcpool.dm
  code/controllers/subsystem/npcpool.dm
  code/datums/datumvars.dm
  code/datums/keybinding/admin.dm
  code/datums/weakrefs.dm
  code/game/atoms.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/callproc/callproc.dm
  code/modules/admin/holder2.dm
  code/modules/admin/tag.dm
  code/modules/admin/topic.dm
  code/modules/admin/view_variables/color_matrix_editor.dm
  code/modules/admin/view_variables/debug_variables.dm
  code/modules/admin/view_variables/get_variables.dm
  code/modules/admin/view_variables/tag_datum.dm
  code/modules/admin/view_variables/topic.dm
  code/modules/admin/view_variables/topic_basic.dm
  code/modules/admin/view_variables/view_variables.dm
  code/modules/events/brand_intelligence.dm
  icons/misc/colortest.dmi
  tgui/packages/tgui/interfaces/ColorMatrixEditor.js
Labels: THIS IS VERY IMPORTANT, Feature, Sprites, Fix, Administration, Code Improvement, TGUI-Changes

#10831 Fixes plasma loop explosion
  code/datums/components/explodable.dm
Labels: Fix

#10802 Adds 3 more shuttles
  _maps/shuttles/emergency/emergency_funnypod.dmm
  _maps/shuttles/emergency/emergency_honkco.dmm
  _maps/shuttles/emergency/emergency_theatre.dmm
  code/datums/shuttles.dm
Labels: Mapping, Feature

#10830 KiloStation cryo tubes now face the proper direction for them to work.
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Mapping, Tweak

#10838 Fixes lockers not glowing
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Fix

#10834 Updates the Webmap domain and map_link names
  _maps/boxstation.json
  _maps/corgstation.json
  _maps/deltastation.json
  _maps/echostation.json
  _maps/flandstation.json
  _maps/kilostation.json
  _maps/metastation.json
  _maps/radstation.json
  interface/interface.dm
Labels: Mapping, Tweak, :ballot_box_with_check: Good PR

#10841 Fixes that one mining vendor runtime
  code/modules/mining/machine_vending.dm
Labels: Fix

#10825 Ports Meat resprite
  code/game/objects/items/food/meatslab.dm
  icons/obj/food/meat.dmi
Labels: Feature, Sprites

#10835 Fixes "Random Arcades" being a useless machine that doesn't do anything in all Station Maps
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/EchoStation/EchoStation.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
Labels: Mapping, Fix

#10844 Fixes 'view tags' being in Admin.Game category
  code/modules/admin/tag.dm
Labels: Fix, Administration

#10842 Fixes heretics making walking husks if they sacrifice a husk
  code/modules/mob/living/carbon/carbon.dm
Labels: Fix

#10853 Zombies break free from handcuffs when transforming
  code/__DEFINES/traits.dm
  code/datums/mutations/hulk.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
  code/modules/zombie/organs.dm
Labels: Tweak

#10854 LOOC will tell admins if the LOOC was sent by someone in their vision range
  code/modules/client/verbs/looc.dm
Labels: Administration

#10855 Makes output from fabricators actually fall if outputted to openspace
  code/datums/components/material_container.dm
  code/game/machinery/fabricators/modular_fabricator.dm
Labels: Fix

#10833 Cryogenic freezer no longer accepts mobs that were never controlled by a player
  code/game/machinery/cryopod.dm
Labels: Tweak

#10822 Adds Tan suits to the clothesmate
  code/modules/vending/clothesmate.dm
Labels: Feature

#10549 Adds integration test annotations, and codenses tests into dropdowns
  .github/workflows/continuous_integration.yml
  code/__DEFINES/MC.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/achievement_validation.dm
  code/modules/unit_tests/anchored_mobs.dm
  code/modules/unit_tests/antag_datums.dm
  code/modules/unit_tests/area_contents.dm
  code/modules/unit_tests/armour_checks.dm
  code/modules/unit_tests/check_adjustable_clothing.dm
  code/modules/unit_tests/closets.dm
  code/modules/unit_tests/component_tests.dm
  code/modules/unit_tests/crafting_tests.dm
  code/modules/unit_tests/create_and_destroy.dm
  code/modules/unit_tests/dcs_get_id_from_elements.dm
  code/modules/unit_tests/dynamic_ruleset_sanity.dm
  code/modules/unit_tests/food_edibility_check.dm
  code/modules/unit_tests/food_icons.dm
  code/modules/unit_tests/gamemode_sanity.dm
  code/modules/unit_tests/greyscale_config.dm
  code/modules/unit_tests/heretic_knowledge.dm
  code/modules/unit_tests/heretic_rituals.dm
  code/modules/unit_tests/icon_smoothing_unit_test.dm
  code/modules/unit_tests/keybinding_init.dm
  code/modules/unit_tests/preference_species.dm
  code/modules/unit_tests/preferences.dm
  code/modules/unit_tests/projectiles.dm
  code/modules/unit_tests/quirks.dm
  code/modules/unit_tests/random_ruin_mapsize.dm
  code/modules/unit_tests/rcd.dm
  code/modules/unit_tests/reagent_id_typos.dm
  code/modules/unit_tests/reagent_recipe_collisions.dm
  code/modules/unit_tests/shuttle_width_height_correctness.dm
  code/modules/unit_tests/species_whitelists.dm
  code/modules/unit_tests/stat_mc.dm
  code/modules/unit_tests/subsystem_init.dm
  code/modules/unit_tests/subsystem_metric_sanity.dm
  code/modules/unit_tests/techweb_sanity.dm
  code/modules/unit_tests/timer_sanity.dm
  code/modules/unit_tests/unit_test.dm
  code/modules/unit_tests/walls_have_sheets.dm
Labels: Feature, GitHub, Server

#10743 [PORT] Warns in VScode about commits to master
  .vscode/settings.json
Labels: Feature, Code Improvement

#10862 [TG PORT] Adds a few new stamps and changes our current ones
  beestation.dme
  code/__DEFINES/dye_keys.dm
  code/game/machinery/washing_machine.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/jobs/job_types/chaplain.dm
  code/modules/jobs/job_types/mime.dm
  code/modules/paperwork/stamps.dm
  icons/obj/bureaucracy.dmi
  icons/stamp_icons/font.png
  icons/stamp_icons/large_stamp-cap.png
  icons/stamp_icons/large_stamp-ce.png
  icons/stamp_icons/large_stamp-cent.png
  icons/stamp_icons/large_stamp-chap.png
  icons/stamp_icons/large_stamp-clown.png
  icons/stamp_icons/large_stamp-cmo.png
  icons/stamp_icons/large_stamp-deny.png
  icons/stamp_icons/large_stamp-hop.png
  icons/stamp_icons/large_stamp-hos.png
  icons/stamp_icons/large_stamp-law.png
  icons/stamp_icons/large_stamp-mime.png
  icons/stamp_icons/large_stamp-ok.png
  icons/stamp_icons/large_stamp-qm.png
  icons/stamp_icons/large_stamp-rd.png
  icons/stamp_icons/large_stamp-syndicate.png
Labels: Feature, Sprites

#10799 Fixes stacks of 0, selfmerge scenarios, and stacks qdeling on init
  code/datums/components/rad_insulation.dm
  code/game/objects/items/debug_items.dm
  code/game/objects/items/stacks/cash.dm
  code/game/objects/items/stacks/sheets/mineral/glass.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/stacks/wrap.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/mob/inventory.dm
Labels: Feature, Refactor, Removal

#10861 Fix vendors
  code/__DEFINES/economy.dm
  code/modules/vending/_vending.dm
  code/modules/vending/snack.dm
  tgui/packages/tgui/interfaces/Vending.tsx
Labels: Feature, Fix, Code Improvement, TGUI-Changes

#10872 Fixes a bug where attaching a wig to a pet causes the wig to be qdel'd after placing the pet down
  code/modules/clothing/head/_head.dm
  code/modules/mob/living/inhand_holder.dm
Labels: Fix

#10856 Ghost orbiting a zmimic will make you orbit the original atom.
  code/game/atoms.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/multiz/zmimic/mimic_movable.dm
Labels: Fix

#10823 AI emote statusdisplays, radials and fixes
  beestation.dme
  code/__DEFINES/mobs.dm
  code/game/machinery/status_display.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/death.dm
  code/modules/mob/living/silicon/ai/emote.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/living/silicon/ai/login.dm
  code/modules/mob/living/silicon/ai/logout.dm
  code/modules/tgui/states.dm
Labels: Feature, Fix, Refactor

#10775 Fixes weather's bad image rendering code
  code/datums/weather/weather.dm
Labels: Fix, Code Improvement

#10858 Stores BCIs in the contents of the chamber instead of in nullspace
  code/modules/wiremod/shell/brain_computer_interface.dm
Labels: Fix

#10864 Fixes multiple issues with Fancy boxes sprites (Cigarettes and donuts) and Ian santa hat now works properly
  code/game/objects/items/storage/fancy.dm
  icons/mob/corgi_head.dmi
  icons/obj/food/donuts.dmi
Labels: Feature, Sprites, Fix

#10893 Fixes flags_1 define macros
  code/__DEFINES/flags.dm
Labels: Test Merged, Fix, Priority: High

#10888 Ports many more emissives, makes existing emissives that were unused functional
  code/__DEFINES/colors.dm
  code/__DEFINES/lighting.dm
  code/game/machinery/computer/apc_control.dm
  code/game/machinery/computer/card.dm
  code/game/machinery/dance_machine.dm
  code/game/machinery/recharger.dm
  code/game/objects/items/devices/flashlight.dm
  code/modules/antagonists/space_dragon/carp_rift.dm
  code/modules/food_and_drinks/kitchen_machinery/microwave.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/mining/equipment/marker_beacons.dm
  code/modules/mob/living/simple_animal/hostile/jungle/seedling.dm
  code/modules/power/monitor.dm
  code/modules/recycling/disposal/bin.dm
  code/modules/research/xenobiology/crossbreeding/_structures.dm
  code/modules/vending/_vending.dm
  code/modules/vending/assist.dm
  code/modules/vending/autodrobe.dm
  code/modules/vending/boozeomat.dm
  code/modules/vending/cigarette.dm
  code/modules/vending/clothesmate.dm
  code/modules/vending/coffee.dm
  code/modules/vending/cola.dm
  code/modules/vending/drinnerware.dm
  code/modules/vending/engineering.dm
  code/modules/vending/engivend.dm
  code/modules/vending/games.dm
  code/modules/vending/job_disk.dm
  code/modules/vending/liberation.dm
  code/modules/vending/liberation_toy.dm
  code/modules/vending/magivend.dm
  code/modules/vending/medical.dm
  code/modules/vending/medical_wall.dm
  code/modules/vending/megaseed.dm
  code/modules/vending/mining.dm
  code/modules/vending/modularpc.dm
  code/modules/vending/nutrimax.dm
  code/modules/vending/robotics.dm
  code/modules/vending/security.dm
  code/modules/vending/snack.dm
  code/modules/vending/sovietsoda.dm
  code/modules/vending/sustenance.dm
  code/modules/vending/toys.dm
  code/modules/vending/wardrobes.dm
  code/modules/vending/youtool.dm
  icons/obj/atmospherics/pipes/disposal.dmi
  icons/obj/stationobjs.dmi
  icons/obj/vending.dmi
  tools/savefileimporter/code/savefile_parser.dm
Labels: Feature, Sprites, Tools

#10898 Updates the hub entry
  beestation.dme
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/hub.dm
  code/game/world.dm
  code/modules/admin/admin.dm
  code/modules/admin/battle_royale.dm
  config/config.txt
Labels: Tweak, Config Update, Administration

#10879 Update CODEOWNERS to use a mapping team for maps
  .github/CODEOWNERS
Labels: GitHub

#10734 Ports "Allows TGUI labelled lists to use tooltips"
  tgui/docs/component-reference.md
  tgui/packages/tgui/components/LabeledList.tsx
Labels: Code Improvement, TGUI-Changes

#10053 Makes footsteps sane, adds footsteps to more mobs, converts to element(optimizes performance)
  beestation.dme
  code/__DEFINES/footsteps.dm
  code/__DEFINES/is_helpers.dm
  code/datums/components/footstep.dm
  code/datums/elements/footstep.dm
  code/modules/awaymissions/mission_code/TheFactory.dm
  code/modules/mining/minebot.dm
  code/modules/mob/living/carbon/alien/humanoid/humanoid.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/bot/ed209bot.dm
  code/modules/mob/living/simple_animal/cluwne.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/friendly/fox.dm
  code/modules/mob/living/simple_animal/friendly/hamster.dm
  code/modules/mob/living/simple_animal/friendly/penguin.dm
  code/modules/mob/living/simple_animal/friendly/sloth.dm
  code/modules/mob/living/simple_animal/friendly/turtle.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/mob/living/simple_animal/hostile/bosses/paperwizard.dm
  code/modules/mob/living/simple_animal/hostile/faithless.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/mob/living/simple_animal/hostile/gorilla/gorilla.dm
  code/modules/mob/living/simple_animal/hostile/hivebot.dm
  code/modules/mob/living/simple_animal/hostile/jungle/leaper.dm
  code/modules/mob/living/simple_animal/hostile/jungle/mega_arachnid.dm
  code/modules/mob/living/simple_animal/hostile/jungle/mook.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
  code/modules/mob/living/simple_animal/hostile/nanotrasen.dm
  code/modules/mob/living/simple_animal/hostile/pirate.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/spaceman.dm
  code/modules/mob/living/simple_animal/hostile/russian.dm
  code/modules/mob/living/simple_animal/hostile/skeleton.dm
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  code/modules/mob/living/simple_animal/hostile/wizard.dm
  code/modules/mob/living/simple_animal/kalo.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  code/modules/xenoarchaeology/traits/xenoartifact_malfunctions.dm
  sound/effects/tank_treads.ogg
Labels: Feature, Fix, Sound, Code Improvement, hacktoberfest-accepted

#10885 VV editor can now see /appearance types
  beestation.dme
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/vv.dm
  code/modules/admin/view_variables/debug_variable_appearance.dm
  code/modules/admin/view_variables/debug_variables.dm
  code/modules/admin/view_variables/view_variables.dm
  code/modules/unit_tests/create_and_destroy.dm
Labels: Fix, Administration, Code Improvement, Priority: High

#10915 removes a dead-end species proc
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Code Improvement

#10875 Fixes wrong signal usages
  code/_onclick/hud/holoparasite.dm
  code/datums/ai/monkey/monkey_behaviors.dm
  code/datums/components/COMPONENT_TEMPLATE.md
  code/datums/components/area_sound_manager.dm
  code/datums/components/plumbing/_plumbing.dm
  code/datums/components/tether.dm
  code/datums/components/waddling.dm
  code/datums/components/wearertargeting.dm
  code/datums/elements/weather_listener.dm
  code/modules/antagonists/heretic/knowledge/void_lore.dm
  code/modules/antagonists/nukeop/equipment/borgchameleon.dm
  code/modules/holoparasite/abilities/major/explosive.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/surgery/organs/augments_internal.dm
Labels: Fix, Code Improvement

#10927 font awesome centering fix
  html/font-awesome/css/all.min.css
Labels: Fix, Server

#10821 Echo fixes
  _maps/echostation.json
  _maps/map_files/EchoStation/EchoStation.dmm
  _maps/shuttles/emergency/emergency_tiny.dmm
  _maps/shuttles/mining/mining_tiny.dmm
  code/game/turfs/closed/minerals.dm
Labels: Mapping, Tweak, Fix
