Repository BeeStation/BeeStation-Hornet, pull requests merged in 2025-01, with the labels that each got.

#12106 Tear of Veil is now a soundtrack datum thing-i-ma-jig.
  code/datums/soundtrack.dm
  code/modules/antagonists/cult/narsie.dm
Labels: Tweak

#12118 Downgrades dompurify to proper version
  tgui/packages/tgui-panel/package.json
  tgui/packages/tgui-say/package.json
  tgui/packages/tgui/package.json
  tgui/yarn.lock
Labels: Code Improvement, TGUI-Changes

#12077 Adds a "Mapper Comment" mapping helper
  code/modules/mapping/mapping_helpers.dm
  icons/effects/mapping_helpers.dmi
Labels: Feature, Sprites

#12105 Fixes stamina armour
  code/__DEFINES/combat.dm
Labels: Fix

#12064 fixes mobs buckled to the operating table not being forced to lay down
  code/game/objects/structures/tables_racks.dm
Labels: Fix

#11812 Public access to lavaland
  _maps/map_files/Mining/Lavaland.dmm
Labels: Mapping, Tweak

#12110 Reworks nukeop telecrystals, lowers required pop for war TC
  code/modules/antagonists/nukeop/equipment/nuclear_challenge.dm
  code/modules/antagonists/nukeop/nukeop.dm
Labels: Tweak, Balance/Rebalance

#11989 Megaseed Vendor's Dionapod + Cotton, Re-Organized and, Re-Alphabetized
  code/modules/vending/megaseed.dm
Labels: Fix

#12003 Small fixes to delta
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Mapping, Tweak, Fix

#12037 fixes boxstation brigmed not having a nanomed+
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Mapping, Fix

#11950 Clown planet fuel rod.
  _maps/RandomRuins/LavaRuins/lavaland_biodome_clown_planet.dmm
Labels: Mapping, Feature

#12130 Fixes bleeding out while buckled to an operating table
  code/game/objects/structures/tables_racks.dm
Labels: Fix, Testmerge Passed

#12129 Changing crews armblade wepons
  code/game/objects/items/weaponry.dm
  code/modules/research/nanites/nanite_programs/buffing.dm
  code/modules/research/xenobiology/crossbreeding/_weapons.dm
Labels: Balance/Rebalance

#12140 .NET 9 SDK setup action for CI
  .github/workflows/ci_suite.yml
Labels: Feature, Fix, GitHub

#12047 Fix missing floor icons
  _maps/RandomRooms/10x10/sk_rdm033_deltalibrary.dmm
  _maps/RandomRooms/10x10/sk_rdm060_snakefighter.dmm
  _maps/RandomRooms/10x10/sk_rdm142_olddiner.dmm
  _maps/RandomRooms/10x10/sk_rdm145_ladytesla_altar.dmm
  _maps/RandomRooms/10x10/sk_rdm159_kilosnakepit.dmm
  _maps/RandomRooms/10x5/sk_rdm039_deltaclutter1.dmm
  _maps/RandomRooms/3x3/sk_rdm027_hullbreach.dmm
  _maps/RandomRooms/3x3/sk_rdm036_owloffice.dmm
  _maps/RandomRooms/3x3/sk_rdm074_kilotheatre.dmm
  _maps/RandomRooms/3x5/sk_rdm158_kilochapelstorage.dmm
  _maps/RandomRooms/3x5/sk_rdm168_offish.dmm
  _maps/RandomRooms/5x3/sk_rdm042_deltaclutter2.dmm
  _maps/RandomRooms/5x4/sk_rdm012_boxbar.dmm
  _maps/RandomRooms/5x4/sk_rdm029_deltabar.dmm
  _maps/RandomRooms/5x4/sk_rdm041_deltagamble.dmm
  _maps/RandomRooms/5x4/sk_rdm076_kilohauntedlibrary.dmm
  _maps/RandomRooms/5x4/sk_rdm166_printing_press.dmm
  _maps/RandomRooms/fland/sk_rdm_fln_10_readingroom.dmm
  _maps/RandomRuins/SpaceRuins/TheDerelict.dmm
  _maps/RandomRuins/SpaceRuins/caravanambush.dmm
  _maps/RandomRuins/SpaceRuins/clownplanet.dmm
  _maps/RandomRuins/SpaceRuins/crashedship.dmm
  _maps/RandomRuins/SpaceRuins/oldAIsat.dmm
  _maps/RandomRuins/SpaceRuins/oldteleporter.dmm
  _maps/RandomRuins/SpaceRuins/onehalf.dmm
  _maps/RuinGeneration/9x13_teleporter.dmm
  _maps/arenas/Stage.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/shuttles/emergency/emergency_luxury.dmm
  _maps/shuttles/hunter/hunter_space_cop.dmm
  _maps/shuttles/ruin/ruin_caravan_victim.dmm
Labels: Mapping, Fix

#12136 Readds drying meat, rebalances meat producs
  code/game/objects/items/food/meatslab.dm
  code/game/objects/items/food/snacks.dm
  code/game/objects/items/food/sweets.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/surgery/organs/organ_internal.dm
  icons/obj/food/food.dmi
Labels: Feature, Sprites, Fix, Balance/Rebalance

#12145 Zombies can heal in stasis
  code/__DEFINES/traits/declarations.dm
  code/_globalvars/traits/_traits.dm
  code/game/machinery/stasis.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
Labels: Tweak

#12097 Fixes bar dispensers having duplicate glass overlays
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
Labels: Fix

#12038 Some more brig physician fixes, and tweaks
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  code/controllers/subsystem/department.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/jobs/job_types/brig_physician.dm
Labels: Mapping, Tweak, Feature, Fix, Removal

#12034 Fixes reagent grinder juicing. Again.
  code/modules/hydroponics/grown/apple.dm
  code/modules/hydroponics/grown/banana.dm
  code/modules/hydroponics/grown/berries.dm
  code/modules/hydroponics/grown/citrus.dm
  code/modules/hydroponics/grown/cocoa_vanilla.dm
  code/modules/hydroponics/grown/corn.dm
  code/modules/hydroponics/grown/melon.dm
  code/modules/hydroponics/grown/pineapple.dm
  code/modules/hydroponics/grown/potato.dm
  code/modules/hydroponics/grown/pumpkin.dm
  code/modules/hydroponics/grown/root.dm
  code/modules/hydroponics/grown/tomato.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/nymph.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/reagent_grinder.dm
Labels: Fix

#12019 Allows Mappers to map crate shelves with pre placed crates
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/crateshelf.dm
  code/modules/mapping/mapping_helpers.dm
  icons/effects/mapping_helpers.dmi
  icons/obj/objects.dmi
Labels: Tweak, Feature, Sprites

#11689 Updates the bikehorn icons
  icons/obj/items_and_weapons.dmi
Labels: Feature, Sprites

#11906 Shaft miners start with gauze
  code/game/objects/items/storage/boxes.dm
Labels: Tweak, 🔑 Close Key (1/3)

#12142 Fixes writing on photos character limited being 128 instead of the intended 256
  code/modules/photography/photos/photo.dm
Labels: Fix

#12156 Fixes dragon's wall tearing permanently breaking if the wall is destroyed before the timer is finished
  code/modules/mob/living/simple_animal/hostile/space_dragon.dm
Labels: Fix

#12154 Fixes giving emote, adds individual giving
  code/_onclick/hud/alert.dm
  code/datums/status_effects/neutral.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/inventory.dm
Labels: Feature, Fix, Removal

#12120 New jackboot icons and replica white jackboots
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/vending/clothesmate.dm
  icons/mob/clothing/feet.dmi
  icons/obj/clothing/accessories.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/clothing/cloaks.dmi
  icons/obj/clothing/clockwork_garb.dmi
  icons/obj/clothing/flightsuit.dmi
  icons/obj/clothing/glasses.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/monkey_alt.dmi
  icons/obj/clothing/neck.dmi
  icons/obj/clothing/shoes.dmi
Labels: Tweak, Feature, Sprites, Fix

#12157 removes invisible bartending shaker
  code/modules/reagents/reagent_containers/cups/drinks.dm
Labels: Removal

#12152 Emags can open firelocks
  code/game/machinery/doors/firedoor.dm
Labels: Balance/Rebalance

#11625 Smooth Movement: Diagonal fix
  code/_onclick/hud/parallax.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/objects/buckling.dm
  code/game/objects/effects/anomalies/anomaly_gravity.dm
  code/game/objects/effects/temporary_visuals/projectiles/projectile_effects.dm
  code/game/objects/items/storage/fancy.dm
  code/game/shuttle_engines.dm
  code/modules/cargo/supplypod.dm
  code/modules/mining/equipment/mineral_scanner.dm
  code/modules/mob/living/silicon/ai/freelook/cameranet.dm
  code/modules/movespeed/_movespeed_modifier.dm
  code/modules/ruins/lavalandruin_code/surface.dm
  code/modules/ruins/objects_and_mobs/necropolis_gate.dm
  code/modules/shuttle/docking.dm
  code/modules/station_goals/bsa.dm
Labels: SQL, Fix, Removal, Testmerge Passed

#12166 Minor uplink changes
  code/modules/uplink/uplink_items.dm
Labels: Tweak, Balance/Rebalance

#12163 Modular fabricator user interface update
  code/game/machinery/fabricators/autolathe.dm
  code/game/machinery/fabricators/modular_fabricator.dm
  tgui/packages/tgui/interfaces/ModularFabricator.jsx
  tgui/packages/tgui/styles/interfaces/ModularFabricator.scss
Labels: Tweak, TGUI-Changes

#12043 New silicon emote, slowclap + emotes for MMIs
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/silicon/robot/emote.dm
Labels: Tweak, Feature

#12173 tweaks medical doctor & paramedic access
  code/modules/jobs/job_types/medical_doctor.dm
  code/modules/jobs/job_types/paramedic.dm
Labels: Tweak

#11945 UPHOLDS WORKERS RIGHT
  code/__DEFINES/economy.dm
Labels: Balance/Rebalance

#12189 Fixes TGUI Panel + Removes context from TGUI panel
  tgui/packages/common/redux.ts
  tgui/packages/tgui-panel/Panel.jsx
  tgui/packages/tgui-panel/audio/NowPlayingWidget.jsx
  tgui/packages/tgui-panel/audio/hooks.js
  tgui/packages/tgui-panel/chat/ChatPageSettings.jsx
  tgui/packages/tgui-panel/chat/ChatTabs.jsx
  tgui/packages/tgui-panel/game/hooks.js
  tgui/packages/tgui-panel/index.jsx
  tgui/packages/tgui-panel/ping/PingIndicator.jsx
  tgui/packages/tgui-panel/reconnect.tsx
  tgui/packages/tgui-panel/settings/SettingsPanel.jsx
  tgui/packages/tgui-panel/settings/hooks.js
  tgui/packages/tgui-panel/stat/StatStatus.js
  tgui/packages/tgui-panel/stat/StatTabs.js
  tgui/packages/tgui-panel/stat/StatText.js
  tgui/packages/tgui-panel/stat/StatTicket.js
  tgui/packages/tgui/backend.ts
  tgui/packages/tgui/debug/hooks.js
Labels: Priority: Critical, Fix, TGUI-Changes

#12190 Fixes chat badges
  code/modules/asset_cache/spritesheet/batched/batched_spritesheet.dm
Labels: Fix

#12191 Fixes revenant telepathy not having the correct spans
  code/modules/spells/spell_types/telepathy.dm
Labels: Fix

#11992 [Port] Adds the ability to request a spare ID safe code when there are no acting captains or captains
  code/controllers/subsystem/job.dm
  code/game/machinery/computer/communications.dm
  tgui/packages/tgui/interfaces/CommunicationsConsole.jsx
Labels: Feature, Code Improvement, TGUI-Changes

#12170 Fixes Juicing (rkz edition)
  code/__DEFINES/reagents.dm
  code/datums/elements/food/food_trash.dm
  code/game/objects/items.dm
  code/game/objects/items/food/misc.dm
  code/game/objects/items/stacks/stack.dm
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/grown/apple.dm
  code/modules/hydroponics/grown/banana.dm
  code/modules/hydroponics/grown/berries.dm
  code/modules/hydroponics/grown/citrus.dm
  code/modules/hydroponics/grown/cocoa_vanilla.dm
  code/modules/hydroponics/grown/corn.dm
  code/modules/hydroponics/grown/melon.dm
  code/modules/hydroponics/grown/pineapple.dm
  code/modules/hydroponics/grown/potato.dm
  code/modules/hydroponics/grown/pumpkin.dm
  code/modules/hydroponics/grown/root.dm
  code/modules/hydroponics/grown/tomato.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/nymph.dm
  code/modules/plumbing/plumbers/grinder_chemical.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/machinery/reagentgrinder.dm
  code/modules/reagents/reagent_containers/cups/_cup.dm
  code/modules/surgery/organs/organ_internal.dm
  code/modules/unit_tests/reagent_grinder.dm
Labels: Fix, Code Improvement

#11966 RadStation centre holopad Move-al
  _maps/map_files/RadStation/RadStation.dmm
Labels: Mapping, Tweak, Removal, i ded

#12196 Fixes the span defines being stupid and broken
  code/__DEFINES/span.dm
Labels: Fix

#12198 Remove pref for admin login
  code/modules/admin/admin.dm
  code/modules/client/preferences/entries/player/admin.dm
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/admin.tsx
Labels: Administration, TGUI-Changes

#12205 Fix stat size reset condition
  tgui/packages/tgui-panel/Panel.jsx
Labels: Fix, TGUI-Changes

#12192 Lets space vines climb ladders and staircases
  code/modules/events/spacevine.dm
Labels: Feature, Balance/Rebalance

#12209 Fixes monkey crash
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
Labels: Fix
