Repository BeeStation/BeeStation-Hornet, pull requests merged in 2025-04, with the labels that each got.

#12517 Fixes lavaland armour not being nerfed while on station
  code/modules/clothing/clothing.dm
Labels: Fix

#12524 Fines now get enforced mechanically, and users will be informed of arrest warrants
  code/datums/records/record.dm
  code/datums/records/sub_records/crime_record.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Tweak, Feature

#12541 Fix OD compilation by fixing stupidity
  tools/ci/od_lints.dm
Labels: Tools

#12537 Fixes explosive walls
  code/game/turfs/closed/wall/mineral_walls.dm
Labels: Mapping, Fix

#12285 Kills Incursion
  beestation.dme
  code/__DEFINES/atom_hud.dm
  code/__DEFINES/role_preferences.dm
  code/__DEFINES/uplink.dm
  code/controllers/configuration/entries/game_options.dm
  code/datums/mind.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/incursion/incursion.dm
  code/game/gamemodes/objectives/basic/assassinate.dm
  code/game/objects/items/devices/doorCharge.dm
  code/game/objects/items/implants/implant_misc.dm
  code/modules/antagonists/incursion/incursion.dm
  code/modules/antagonists/role_preference/role_antagonists.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/uplink/uplink_items.dm
  config/game_options.txt
  tgui/packages/tgui/interfaces/AntagInfoIncursion.tsx
Labels: Config Update, Removal, TGUI-Changes, :ballot_box_with_check: Good PR

#12502 Fixes the captain's spare ID safe being unlocked at roundstart
  code/game/objects/items/storage/secure.dm
Labels: Fix

#12479 Armour readouts fix
  code/__DEFINES/combat.dm
  code/datums/armor/_armor.dm
  code/modules/clothing/clothing.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/armour_readouts.dm
Labels: Fix

#12476 Small emote fix and adjustments
  code/modules/mob/living/brain/emote.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/silicon/robot/emote.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/multiz/movement/mob/living_zmove.dm
Labels: Tweak, Fix, Removal

#12530 Coconut plant
  beestation.dme
  code/game/objects/items/food/misc.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/hydroponics/grown/coconut.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/reagent_containers/cups/_cup.dm
  code/modules/vending/megaseed.dm
  icons/obj/drinks.dmi
  icons/obj/food/food.dmi
  icons/obj/hydroponics/growing_fruits.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
Labels: Tweak, Feature, Sprites

#12522 Fix and rebalance of RBMK reactor
  code/modules/power/rbmk/_rbmk_defines.dm
  code/modules/power/rbmk/rbmk_core.dm
  code/modules/power/rbmk/rbmk_main_processes.dm
  code/modules/power/rbmk/rbmk_parts.dm
  code/modules/power/rbmk/rbmk_procs.dm
  tgui/packages/tgui/interfaces/NtosGhostRbmkStats.jsx
  tgui/packages/tgui/interfaces/NtosRbmkStats.jsx
Labels: Fix, Balance/Rebalance, TGUI-Changes

#12551 CC Teleport Fix
  code/modules/shuttle/supply.dm
Labels: Fix

#12439 [PORT]: Adds Retaliate Element
  beestation.dme
  code/__DEFINES/ai.dm
  code/__DEFINES/dcs/signals/signals_atom/signals_atom_attack.dm
  code/datums/ai/basic_mobs/basic_subtrees/target_retaliate.dm
  code/datums/ai/basic_mobs/targetting_datums/basic_targetting_datum.dm
  code/datums/ai/monkey/monkey_controller.dm
  code/datums/elements/ai_retaliate.dm
  code/datums/elements/relay_attackers.dm
  code/modules/vehicles/mecha/mech_melee_attack.dm
Labels: Feature, Code Improvement

#12536 Fixes swarmer exploit
  code/modules/antagonists/swarmer/swarmer.dm
Labels: Tweak, Fix

#12556 Fixes two bugs with paper markdown
  tgui/packages/tgui/interfaces/PaperSheet.tsx
Labels: Fix, TGUI-Changes

#12521 Pizza bombs no longer have a chance to explode instantly when EMPed
  code/modules/food_and_drinks/pizzabox.dm
Labels: Balance/Rebalance, i ded

#12561 Fixes /mob/living/get_contents() which also fixes the admin "Check Contents" Verb
  code/modules/mob/living/living.dm
Labels: Fix

#12566 Basic Mobs are no longer immune to temperature and space
  code/modules/mob/living/basic/basic.dm
  code/modules/mob/living/basic/pets/dogs/dog.dm
  code/modules/mob/living/basic/pets/gondolas/gondola.dm
  code/modules/mob/living/basic/pets/pet.dm
Labels: Fix

#12552 KiloStation mining bay no longer spawns with a firelock.
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Mapping, Fix

#12550 More Sound Synthizer Sounds
  code/game/objects/items/devices/sound_synth.dm
Labels: Feature, Removal

#12483 Mapped food and grown food is preserved until moved.
  code/game/objects/items/food/_food.dm
  code/modules/hydroponics/grown.dm
  code/modules/mapping/mapping_helpers.dm
  icons/effects/mapping_helpers.dmi
  tools/maplint/lints/mapping_helpers.yml
Labels: Tweak, Feature, Sprites, Tools

#12475 Fixes robotics control console not alerting crew
  code/game/machinery/computer/robot.dm
Labels: Fix

#12430 Rad sci, med and maints update
  _maps/Prefab/Departments.dmm
  _maps/map_files/RadStation/RadStation.dmm
  _maps/shuttles/mining/mining_rad.dmm
  code/game/machinery/computer/camera.dm
Labels: Mapping, Tweak

#12571 Fixes the plant analyzer creating a runtime error when used on plants.
  code/modules/hydroponics/grown.dm
Labels: Fix

#12565 Converts cows to basic mobs
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/generic/CentCom.dmm
  beestation.dme
  code/__DEFINES/ai.dm
  code/__DEFINES/dcs/signals/signals_mob/signals_simplemob.dm
  code/__HELPERS/ai.dm
  code/_globalvars/lists/flavor_misc.dm
  code/controllers/subsystem/processing/ai_controllers.dm
  code/datums/ai/_ai_behavior.dm
  code/datums/ai/_ai_controller.dm
  code/datums/ai/basic_mobs/basic_ai_behaviors/basic_attacking.dm
  code/datums/ai/basic_mobs/basic_ai_behaviors/targetting.dm
  code/datums/ai/basic_mobs/basic_ai_behaviors/tipped_reaction.dm
  code/datums/ai/basic_mobs/basic_subtrees/find_food.dm
  code/datums/ai/basic_mobs/basic_subtrees/simple_attack_target.dm
  code/datums/ai/basic_mobs/basic_subtrees/simple_find_target.dm
  code/datums/ai/basic_mobs/basic_subtrees/speech_subtree.dm
  code/datums/ai/basic_mobs/basic_subtrees/tipped_subtree.dm
  code/datums/ai/basic_mobs/targetting_datums/basic_targetting_datum.dm
  code/datums/ai/generic/find_and_set.dm
  code/datums/ai/generic_actions.dm
  code/datums/components/udder.dm
  code/datums/elements/basic_eating.dm
  code/datums/elements/movement_turf_changer.dm
  code/game/objects/items/carp_lasso.dm
  code/modules/antagonists/wizard/equipment/artefact.dm
  code/modules/awaymissions/corpse.dm
  code/modules/cargo/packs.dm
  code/modules/events/sentience.dm
  code/modules/holoparasite/abilities/lesser/teleport.dm
  code/modules/holoparasite/abilities/major/explosive.dm
  code/modules/holoparasite/abilities/major/gravity.dm
  code/modules/holoparasite/abilities/major/healing.dm
  code/modules/holoparasite/holoparasite_attack.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/basic/basic.dm
  code/modules/mob/living/basic/farm_animals/cow/_cow.dm
  code/modules/mob/living/basic/farm_animals/cow/cow_ai.dm
  code/modules/mob/living/basic/farm_animals/cow/cow_moonicorn.dm
  code/modules/mob/living/basic/farm_animals/cow/cow_wisdom.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/projectiles/projectile/magic.dm
  icons/mob/animal.dmi
  icons/mob/cows.dmi
  strings/wisdoms.txt
Labels: Mapping, Feature, Sprites, Refactor, Administration

#12567 Pre-Assembled RBMK
  code/modules/power/rbmk/rbmk_parts.dm
  code/modules/power/rbmk/rbmk_procs.dm
Labels: Feature

#12446 Camera Network Changes (some network areas changed, Removed AI "jump to network")
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas/mining.dm
  code/game/machinery/camera/tracking.dm
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Tweak, Fix

#12576 Caltrop fix
  code/datums/components/caltrop.dm
Labels: Fix, Code Improvement

#12449 Ghost Observe and Cancel camera view Hud buttons
  code/__DEFINES/hud.dm
  code/_onclick/hud/ghost.dm
  code/modules/mob/dead/observer/observer.dm
  icons/hud/screen_ghost.dmi
Labels: Feature, Sprites

#12423 Spices up the RD's labcoat
  code/modules/clothing/suits/labcoat.dm
  icons/mob/clothing/suits/labcoat.dmi
  icons/obj/clothing/suits/labcoat.dmi
Labels: Feature, Sprites

#12577 Fixes RGB hint vv
  code/modules/admin/view_variables/debug_variables.dm
  html/admin/view_variables.css
Labels: Fix, Administration

#12419 Adjusts deadchat color to more closely match the previous purple
  tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
Labels: Tweak, TGUI-Changes

#12581 Removes Aquisition Ability of WheelyHeelys via GamesVendor
  code/modules/vending/games.dm
Labels: Tweak

#12591 Revert "Adjusts deadchat color to more closely match the previous purple"
  tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
Labels: Tweak, TGUI-Changes

#12592 Rad Mining Shuttle Fix
  _maps/map_files/Mining/Lavaland.dmm
Labels: Mapping, Fix

#12452 Hotfix firefighting foam turf temperature
  code/game/objects/effects/effect_system/effects_foam.dm
Labels: Fix, Code Improvement

#12560 Coconut PR Process fix + Minor update
  code/game/objects/items/food/misc.dm
  code/modules/hydroponics/grown/coconut.dm
  code/modules/hydroponics/growninedible.dm
Labels: Feature, Fix

#12414 Ports <Dmicon> and adds wall closets
  beestation.dme
  code/controllers/subsystem/early_assets.dm
  code/game/machinery/computer/teleporter.dm
  code/game/objects/items/stacks/sheets/mineral/metals_recipes.dm
  code/game/objects/structures/crates_lockers/wall_closets.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/tgui/tgui.dm
  icons/obj/storage/wall_closet.dmi
  tgui/docs/component-reference.md
  tgui/global.d.ts
  tgui/packages/tgui/components/DmIcon.tsx
  tgui/packages/tgui/components/Image.tsx
  tgui/packages/tgui/components/index.ts
  tgui/packages/tgui/icons.ts
  tgui/packages/tgui/index.tsx
  tgui/packages/tgui/interfaces/WallCloset.tsx
  tgui/packages/tgui/styles/interfaces/WallCloset.scss
  tgui/packages/tgui/styles/main.scss
Labels: Mapping, Feature, Sprites, Code Improvement, TGUI-Changes

#12331 COPS: Law enforcement gear/uniform updates
  code/game/objects/items/handcuffs.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/antagonists/fugitive/hunter_outfits.dm
  code/modules/client/loadout/loadout_uniform.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/jobs/job_types/deputy.dm
  code/modules/jobs/job_types/warden.dm
  code/modules/vending/wardrobes.dm
  icons/mob/clothing/belt.dmi
  icons/mob/clothing/head/beret.dmi
  icons/mob/clothing/head/hats.dmi
  icons/mob/clothing/head/helmet.dmi
  icons/mob/clothing/suits/armor.dmi
  icons/mob/clothing/suits/jacket.dmi
  icons/mob/clothing/under/security.dmi
  icons/obj/clothing/belt_overlays.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/clothing/head/beret.dmi
  icons/obj/clothing/head/hats.dmi
  icons/obj/clothing/head/helmet.dmi
  icons/obj/clothing/suits/armor.dmi
  icons/obj/clothing/suits/jacket.dmi
  icons/obj/clothing/under/security.dmi
Labels: Tweak, Feature, Sprites, Removal

#12341 Circuit Expansion: Variable Length Index + Concatenate and New String Trim and Switch Case components
  beestation.dme
  code/modules/research/designs/wiremod_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/wiremod/components/list/index.dm
  code/modules/wiremod/components/string/concat.dm
  code/modules/wiremod/components/string/trim.dm
  code/modules/wiremod/components/utility/switchcase.dm
Labels: Tweak, Feature

#11627 Begins moving felinid species behaviors to organs: Fall damage.
  code/__DEFINES/status_effects.dm
  code/__DEFINES/traits/declarations.dm
  code/__DEFINES/traits/sources.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/traits/_traits.dm
  code/datums/brain_damage/severe.dm
  code/modules/admin/secrets.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/surgery/organs/organ_internal.dm
  code/modules/surgery/organs/tails.dm
  code/modules/tgui/status_composers.dm
Labels: Tweak, Balance/Rebalance, Administration

#12600 Makes buildmode del rclick usable
  code/modules/buildmode/submodes/delete.dm
Labels: Fix, Removal

#12615 Fixing the volume bug of coconuts
  code/modules/hydroponics/grown/coconut.dm
  code/modules/reagents/reagent_containers/cups/_cup.dm
Labels: Feature, Fix

#12422 Gun code cleanup + Improv round changes
  code/datums/components/pellet_cloud.dm
  code/datums/diseases/advance/symptoms/skin.dm
  code/game/atom_defense.dm
  code/game/objects/items/chrono_eraser.dm
  code/game/objects/items/robot/robot_items.dm
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/antagonists/clock_cult/items/clockwork_weapon.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/projectiles/ammunition/_ammunition.dm
  code/modules/projectiles/ammunition/_firing.dm
  code/modules/projectiles/ammunition/ballistic/pistol.dm
  code/modules/projectiles/ammunition/ballistic/revolver.dm
  code/modules/projectiles/ammunition/ballistic/rifle.dm
  code/modules/projectiles/ammunition/ballistic/shotgun.dm
  code/modules/projectiles/ammunition/caseless/_caseless.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/bow.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/guns/ballistic/toy.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/dueling.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/laser_gatling.dm
  code/modules/projectiles/guns/energy/recharge.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/magic.dm
  code/modules/projectiles/guns/magic/staff.dm
  code/modules/projectiles/guns/misc/blastcannon.dm
  code/modules/projectiles/guns/misc/chem_gun.dm
  code/modules/projectiles/guns/misc/grenade_launcher.dm
  code/modules/projectiles/guns/misc/medbeam.dm
  code/modules/projectiles/guns/misc/syringe_gun.dm
  code/modules/projectiles/projectile/bullets/revolver.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
  code/modules/vehicles/mecha/equipment/tools/medical_tools.dm
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
Labels: Tweak, Balance/Rebalance, Refactor, Removal, Code Improvement, Balance Approved

#12553 Removes HECK suit hallucinations
  code/modules/mining/equipment/explorer_gear.dm
Labels: Removal

#12440 stack_trace() now individually reports runtimes + Runtime count
  beestation.dme
  code/__DEFINES/__stack_trace.dm
  code/__HELPERS/stack_trace.dm
  code/modules/error_handler/error_handler.dm
  code/modules/error_handler/error_viewer.dm
Labels: Code Improvement

#12621 Nerfed syringe bleed and damage
  code/modules/projectiles/projectile/bullets/dart_syringe.dm
Labels: Balance/Rebalance

#12629 Fixing pAI messenger
  code/__DEFINES/hud.dm
  code/modules/mob/living/silicon/pai/software.dm
Labels: Fix

#12645 Adds a safety net for invalid number of positive quirks
  code/controllers/subsystem/processing/quirks.dm
Labels: Fix

#12639 Added blood filter to surgery implant
  code/modules/surgery/organs/augments_arms.dm
  code/modules/surgery/tools.dm
Labels: Feature

#12638 Hotfixes storage implant's storage datum to match it's description
  code/datums/storage/subtypes/implant.dm
Labels: Balance/Rebalance

#12653 Removing a bunch of ghost powers (bugs)
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/storage/fancy.dm
  code/game/objects/items/tanks/watertank.dm
  code/modules/atmospherics/machinery/components/unary_devices/outlet_injector.dm
  code/modules/clothing/masks/breath.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/reagents/reagent_containers/cups/drinks.dm
Labels: Fix
