Repository BeeStation/BeeStation-Hornet, pull requests merged in 2025-03, with the labels that each got.

#12168 Adds in an advanced mode to the preferences screen to hide some preferences
  code/modules/client/preferences/entries/player/chat.dm
  tgui/packages/tgui/interfaces/PreferencesMenu/GamePreferencesPage.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/base.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/admin.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/auto_fit_viewport.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/chat.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/darkened_flash.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/deadmin.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/fullscreen.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/ghost.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/hotkeys.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/item_outlines.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/ooc.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/pixel_size.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/scaling_method.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/sound.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/tgui.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/ui_style.tsx
Labels: Tweak, TGUI-Changes

#12385 abductor console fix
  code/modules/antagonists/abductor/abductor.dm
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/antagonists/abductor/equipment/gland.dm
  code/modules/antagonists/abductor/machinery/camera.dm
  code/modules/antagonists/abductor/machinery/console.dm
  code/modules/surgery/organs/tongue.dm
  code/modules/surgery/surgery.dm
Labels: Fix, Code Improvement

#12378 Fixes combat mode bump pushing
  code/modules/mob/living/living.dm
Labels: Fix

#12370 Don't start an extra database for no reason in CI
  .github/workflows/run_integration_tests.yml
Labels: GitHub

#12374 Fixes zombie organs not progressing
  code/modules/admin/verbs/manipulate_organs.dm
  code/modules/zombie/organs.dm
Labels: Fix, Administration, Code Improvement

#12360 Ports throwing having a sound and animation
  code/modules/mob/living/carbon/carbon.dm
  sound/weapons/attributions.txt
  sound/weapons/throw.ogg
Labels: Feature, Sound

#12369 Adding possibility of fixing walls and fixing gridle on right click
  code/game/turfs/closed/walls.dm
  code/game/turfs/open/floor/plating.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Fix

#12329 Syndicate uniform rework: Ports new sprites for tactical clothes
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/clothing/under/syndicate.dm
  icons/mob/clothing/under/syndicate.dmi
  icons/obj/clothing/under/syndicate.dmi
Labels: Feature, Sprites

#12355 Quirks no longer cost or give points
  code/__DEFINES/mobs.dm
  code/__HELPERS/cmp.dm
  code/controllers/subsystem/processing/quirks.dm
  code/datums/traits/_quirk.dm
  code/datums/traits/negative_quirk.dm
  code/datums/traits/neutral_quirk.dm
  code/datums/traits/positive_quirk.dm
  code/modules/client/preferences/middleware/quirks.dm
  tgui/packages/tgui/interfaces/PreferencesMenu/QuirksPage.tsx
Labels: Tweak, Balance/Rebalance, TGUI-Changes

#12268 Fix: ahelp and mhelp verb buttons give the TGUI prompt now
  code/datums/keybinding/client.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/mentorhelp.dm
Labels: Tweak, Administration

#12265 Virtual multi-z
  beestation.dme
  code/__DEFINES/multi_z.dm
  code/__DEFINES/zmimic.dm
  code/__HELPERS/multiz_helpers.dm
  code/_compile_options.dm
  code/_onclick/hud/ai.dm
  code/controllers/subsystem/zcopy.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/meteor/meteors.dm
  code/game/machinery/porta_turret/portable_turret.dm
  code/game/turfs/change_turf.dm
  code/game/turfs/open/openspace.dm
  code/game/turfs/turf.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/atmospherics/environmental/LINDA_system.dm
  code/modules/mapping/space_management/multiz_helpers.dm
  code/modules/multiz/movement/turf/turf_zmove.dm
  code/modules/multiz/zmimic/documentation.md
  code/modules/multiz/zmimic/mimic_movable.dm
  code/modules/multiz/zmimic/mimic_turf.dm
  code/modules/power/cable.dm
  code/modules/power/supermatter/supermatter.dm
  code/modules/shuttle/super_cruise/orbital_map_components/orbital_objects/meteor.dm
Labels: Refactor, Administration

#12252 [Port] Adds the tippable component + makes borgs able to be tipped over
  beestation.dme
  code/__DEFINES/robots.dm
  code/__DEFINES/traits/declarations.dm
  code/__DEFINES/traits/sources.dm
  code/_globalvars/traits/_traits.dm
  code/datums/components/tippable.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_defense.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
Labels: Feature, Balance/Rebalance, Refactor, Code Improvement, Balance Approved

#12063 fixes mjolnir dropping onto the ground when summoned with a spell
  code/modules/spells/spell_types/self/summon_item.dm
Labels: Stale, Fix

#12390 Fixes Void Phase
  code/modules/antagonists/heretic/magic/void_phase.dm
Labels: Fix

#12235 the malf update (2/3)
  beestation.dme
  code/__DEFINES/ai.dm
  code/__DEFINES/antagonists.dm
  code/__DEFINES/configuration.dm
  code/__DEFINES/role_preferences.dm
  code/_globalvars/lists/objects.dm
  code/controllers/configuration/entries/game_options.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/objectives/finale/survive.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/machinery/transformer.dm
  code/game/objects/items/devices/radio/intercom.dm
  code/game/objects/items/robot/ai_upgrades.dm
  code/modules/antagonists/malf_ai/malf_ai.dm
  code/modules/antagonists/malf_ai/malf_ai_module_picker.dm
  code/modules/antagonists/malf_ai/malf_ai_modules.dm
  code/modules/antagonists/role_preference/role_antagonists.dm
  code/modules/antagonists/role_preference/role_midrounds.dm
  code/modules/antagonists/traitor/IAA/internal_affairs.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/antagonists/traitor/equipment/Malf_Modules.dm
  code/modules/antagonists/traitor/traitor_ai.dm
  code/modules/antagonists/traitor/traitor_objectives.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/laws.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/power/apc/apc_malf.dm
  code/modules/vehicles/mecha/_mecha.dm
  config/game_options.txt
  icons/hud/actions/actions_AI.dmi
  strings/malfunction_flavor.json
  tgui/packages/tgui/interfaces/AiVoiceChanger.tsx
  tgui/packages/tgui/interfaces/AntagInfoMalf.tsx
  tgui/packages/tgui/interfaces/MalfunctionModulePicker.jsx
Labels: Tweak, Feature, Sprites, Fix, Config Update, Refactor, Removal, TGUI-Changes

#12377 Removes pull-moving ventcrawling mobs
  code/__DEFINES/traits/declarations.dm
  code/_globalvars/traits/_traits.dm
  code/game/atoms_movable.dm
  code/modules/mob/living/ventcrawling.dm
Labels: Balance/Rebalance

#12171 [Port] Adds Tackling to the game
  beestation.dme
  code/__DEFINES/dcs/signals/signals_atom/signals_atom.dm
  code/__DEFINES/dcs/signals/signals_mob/signals_living.dm
  code/__DEFINES/dcs/signals/signals_movable.dm
  code/__DEFINES/status_effects.dm
  code/__DEFINES/traits/declarations.dm
  code/_globalvars/lists/maintenance_loot.dm
  code/_globalvars/traits/_traits.dm
  code/datums/components/crafting/crafting_lists/tailoring/clothing.dm
  code/datums/components/tackle.dm
  code/datums/elements/squish.dm
  code/datums/mutations/body.dm
  code/datums/status_effects/debuffs.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/objects/items.dm
  code/game/objects/items/grenades/_grenade.dm
  code/game/objects/items/shields.dm
  code/game/objects/items/stacks/tape.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/admin/battle_royale.dm
  code/modules/antagonists/fugitive/hunter_outfits.dm
  code/modules/antagonists/role_preference/role_antagonists.dm
  code/modules/awaymissions/capture_the_flag.dm
  code/modules/awaymissions/corpse.dm
  code/modules/cargo/packs.dm
  code/modules/clothing/gloves/tacklers.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/clothing/outfits/vr.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/mob/living/simple_animal/corpse.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
  code/modules/mob/living/status_procs.dm
  code/modules/movespeed/modifiers/mobs.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/ruins/lavaland_ruin_code.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/objective_types/assassination.dm
  code/modules/station_goals/bluespace_tap.dm
  code/modules/uplink/uplink_items.dm
  code/modules/vending/security.dm
  icons/mob/clothing/hands.dmi
  icons/obj/clothing/gloves.dmi
  strings/tips.txt
Labels: Feature, Sprites, Balance/Rebalance, Administration, Balance Approved

#12371 Major changes to ion weaponry + EMPs against cybernetics in carbons
  code/datums/status_effects/debuffs.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/projectiles/ammunition/energy/special.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/projectile/special/ion.dm
  code/modules/surgery/organs/augments_arms.dm
  code/modules/surgery/organs/augments_chest.dm
  code/modules/surgery/organs/augments_eyes.dm
  code/modules/surgery/organs/augments_internal.dm
  code/modules/surgery/organs/ears.dm
  code/modules/surgery/organs/eyes.dm
  code/modules/surgery/organs/heart.dm
  code/modules/surgery/organs/liver.dm
  code/modules/surgery/organs/lungs.dm
  code/modules/surgery/organs/stomach.dm
  code/modules/surgery/organs/tongue.dm
Labels: Tweak, Balance/Rebalance

#12361 Readds IPC mutation toxin
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
Labels: Feature

#12349 Improves chem dispenser usability
  code/__DEFINES/reagents.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/food_and_drinks/recipes/food_mixtures.dm
  code/modules/reagents/__DEFINES/reagent_defines.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/chemistry/recipes.dm
  code/modules/reagents/chemistry/recipes/drugs.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
  code/modules/reagents/chemistry/recipes/toxins.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/reagent_id_duplicates.dm
  tgui/packages/tgui/interfaces/ChemDispenser.jsx
  tgui/packages/tgui/interfaces/ChemDispenser.tsx
  tgui/packages/tgui/styles/interfaces/ChemDispenser.scss
  tgui/packages/tgui/styles/main.scss
Labels: Feature, Removal, TGUI-Changes, :ballot_box_with_check: Good PR

#12415 Fixes "You have one or more outdated quirks"
  code/controllers/subsystem/processing/quirks.dm
Labels: Fix, p-Priority: High

#12046 [Port-Ish] Adds leaning to the game
  beestation.dme
  code/__DEFINES/dcs/signals/signals_atom/signals_atom.dm
  code/__DEFINES/dcs/signals/signals_mob/signals_living.dm
  code/__DEFINES/status_effects.dm
  code/__DEFINES/traits/declarations.dm
  code/__DEFINES/vehicles.dm
  code/_globalvars/traits/_traits.dm
  code/datums/components/leanable.dm
  code/datums/elements/climbable.dm
  code/datums/status_effects/neutral.dm
  code/game/atoms.dm
  code/game/machinery/computer/_computer.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/items.dm
  code/game/objects/items/cigs_lighters.dm
  code/game/objects/items/stunbaton.dm
  code/game/objects/structures/target_stake.dm
  code/game/objects/structures/window.dm
  code/game/turfs/closed/walls.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/init_signals.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/silicon/pai/pai_shell.dm
  code/modules/mob/living/simple_animal/hostile/floor_cluwne.dm
  code/modules/modular_computers/computers/machinery/modular_computer.dm
  code/modules/vehicles/_vehicle.dm
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/sealed.dm
  code/modules/xenoarchaeology/traits/xenoartifact_minors.dm
Labels: Feature

#12354 Removes junk mail, makes mail give some more unique items
  code/__DEFINES/economy.dm
  code/_globalvars/lists/flavor_misc.dm
  code/controllers/subsystem/economy.dm
  code/game/objects/items/mail.dm
  code/modules/jobs/job_mail.dm
  code/modules/shuttle/supply.dm
  strings/junkmail.txt
Labels: Tweak, Fix

#12398 exploration missions no longer create a central command announcement when failed
  code/controllers/subsystem/processing/orbits.dm
Labels: Removal

#12334 Lots of new barsigns from TG
  code/game/objects/structures/barsigns.dm
  icons/obj/barsigns.dmi
Labels: Feature, Sprites

#12322 Restaurant on thrusters: A rework of the Fland whiteship
  _maps/shuttles/whiteship/whiteship_fland.dmm
Labels: Mapping, Tweak

#12300 [PORT]: Removes tank dispenser TGUI menu.
  code/game/objects/structures/tank_dispenser.dm
  tgui/packages/tgui/interfaces/TankDispenser.jsx
Labels: Tweak, TGUI-Changes

#12297 Makes painting usable
  beestation.dme
  code/__DEFINES/ai.dm
  code/__DEFINES/dcs/signals/signals_obj/signals_item/signals_item.dm
  code/__DEFINES/paintings.dm
  code/__DEFINES/subsystems.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/roundend.dm
  code/_onclick/hud/radial.dm
  code/_onclick/hud/radial_persistent.dm
  code/controllers/subsystem/persistence.dm
  code/controllers/subsystem/persistent_paintings.dm
  code/datums/components/palette.dm
  code/game/atoms_movable.dm
  code/game/objects/items/RCL.dm
  code/game/objects/items/crayons.dm
  code/game/objects/structures/artstuff.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/painting_manager.dm
  code/modules/art/paintings.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/mob/living/silicon/ai/ai_portrait_picker.dm
  code/modules/modular_computers/file_system/programs/portrait_printer.dm
  code/modules/vending/games.dm
  icons/hud/radials/radial_generic.dmi
  icons/mob/inhands/equipment/palette_lefthand.dmi
  icons/mob/inhands/equipment/palette_righthand.dmi
  icons/obj/artstuff.dmi
  tgui/packages/tgui/components/Button.jsx
  tgui/packages/tgui/interfaces/Canvas.jsx
  tgui/packages/tgui/interfaces/Canvas.tsx
  tgui/packages/tgui/interfaces/NtosPortraitPrinter.jsx
  tgui/packages/tgui/interfaces/PaintingAdminPanel.tsx
  tgui/packages/tgui/interfaces/PortraitPicker.jsx
Labels: Feature, Sprites, Administration, TGUI-Changes

#12187 Add three more ghost scanners, refactors and improves the handheld genetics scanner
  code/_onclick/observer.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Tweak, Feature, Refactor

#12175 Strict random characters
  code/__DEFINES/preferences.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/lists/flavor_misc.dm
  code/modules/admin/create_mob.dm
  code/modules/antagonists/abductor/equipment/gland.dm
  code/modules/client/preferences/entries/character/clothing.dm
  code/modules/client/preferences/entries/character/gender.dm
  code/modules/client/preferences/entries/character/species_features/basic.dm
  code/modules/client/preferences/preference_entry.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/research/xenobiology/crossbreeding/_status_effects.dm
  code/modules/research/xenobiology/crossbreeding/warping.dm
  code/modules/surgery/bodyparts/head.dm
Labels: Tweak, Administration

#12393 Moves cult actions to the top of the screen
  code/__DEFINES/cult.dm
  code/datums/components/cult_ritual_item.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/antagonists/cult/cult_items.dm
Labels: Tweak

#12254 [Port-Ish] Adds new station alert levels to the game + code fix about alerts
  code/__DEFINES/communications.dm
  code/__HELPERS/priority_announce.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/nightshift.dm
  code/game/machinery/computer/communications.dm
  code/modules/antagonists/clock_cult/helpers/clockcult_ending.dm
  code/modules/antagonists/cult/narsie.dm
  code/modules/antagonists/heretic/knowledge/ash_lore.dm
  code/modules/antagonists/heretic/knowledge/flesh_lore.dm
  code/modules/antagonists/heretic/knowledge/rust_lore.dm
  code/modules/antagonists/heretic/knowledge/void_lore.dm
  code/modules/antagonists/nukeop/equipment/nuclear_challenge.dm
  code/modules/security_levels/keycard_authentication.dm
  code/modules/security_levels/security_level_datums.dm
  code/modules/shuttle/emergency.dm
  config/game_options.txt
  sound/misc/black.ogg
  sound/misc/cyanalert.ogg
  sound/misc/epsilon.ogg
  sound/misc/gamma.ogg
  sound/misc/lambda.ogg
  sound/misc/yellowalert.ogg
  tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
  tgui/packages/tgui-panel/styles/tgchat/chat-light.scss
  tgui/packages/tgui/interfaces/CommunicationsConsole.jsx
Labels: Feature, Fix, Config Update, Sound, TGUI-Changes

#12427 Debug hardsuit no longer has a geiger counter
  code/game/objects/items/debug_items.dm
  code/modules/clothing/spacesuits/hardsuit.dm
Labels: Tweak, i ded

#12403 [PORT]: Gondola Basic Mob
  _maps/RandomRooms/3x3/sk_rdm028_tranquility.dmm
  _maps/RandomRuins/SpaceRuins/gondolaasteroid.dmm
  beestation.dme
  code/datums/ai/idle_behaviors/idle_random_walk.dm
  code/datums/diseases/transformation.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/modules/cargo/gondolapod.dm
  code/modules/cargo/supplypod.dm
  code/modules/mob/living/basic/pets/dogs/dog.dm
  code/modules/mob/living/basic/pets/gondolas/gondola.dm
  code/modules/mob/living/basic/pets/gondolas/gondolapod.dm
  code/modules/mob/living/simple_animal/friendly/gondola.dm
Labels: Mapping, Refactor

#12434 Monkey AI removable via lobotomy, transferable with the brain
  code/modules/mob/living/brain/brain_item.dm
  code/modules/surgery/advanced/lobotomy.dm
Labels: Tweak, Feature

#12418 Tweak: "Required votes to leave" never drops to 0
  code/controllers/subsystem/autotransfer.dm
Labels: Tweak

#12399 Adds a color intensity variable to reagents, now you can dye your mixes
  code/modules/reagents/chemistry/colors.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Tweak

#12444 Fixes undocumented changes to revenant abilities
  code/modules/antagonists/revenant/revenant.dm
  code/modules/antagonists/revenant/revenant_abilities.dm
  code/modules/spells/spell_types/list_targets/telepathy.dm
Labels: Tweak, Fix

#12445 Paper doesn't move around during mapload
  code/modules/paperwork/paper.dm
Labels: Tweak

#12451 Fixed shield generator error generating immortality
  code/game/machinery/shieldgen.dm
Labels: Fix

#12441 fix botanist job desc
  code/modules/jobs/job_types/botanist.dm
Labels: Fix

#12412 [IDED] Nerfs Beepsky because I hate him.
  code/modules/mob/living/simple_animal/bot/secbot.dm
Labels: Balance/Rebalance, i ded

#12448 More IPC screens, greek letters edition
  code/modules/mob/dead/new_player/sprite_accessories.dm
  icons/mob/ipc_accessories.dmi
Labels: Feature, Sprites

#12484 Fixes rolling paper not having any papers inside
  code/game/objects/items/storage/fancy.dm
Labels: Fix

#12388 Adds potions
  code/modules/reagents/reagent_containers/cups/bottle.dm
  code/modules/research/designs/autolathe_designs.dm
  icons/obj/chemical.dmi
  icons/obj/lavaland/artefacts.dmi
  icons/obj/reagentfillings.dmi
Labels: Tweak, Feature, Sprites

#12499 HOTFIX: Fixes issues with potions (with no typepath changes)
  code/modules/reagents/reagent_containers/cups/bottle.dm
  code/modules/research/designs/autolathe_designs.dm
Labels: Fix

#12498 Removes the "who" verb
  code/modules/client/verbs/who.dm
Labels: Removal

#12503 516: Fix TGUI Asset Loading
  tgui/public/tgui.html
Labels: Fix, TGUI-Changes

#12493 Fixes tesla coil manual zap not respecting power net load
  code/modules/power/tesla/coil.dm
Labels: Fix

#12462 Fix to admin alert level blocking other keycard actions
  code/modules/security_levels/keycard_authentication.dm
Labels: Tweak, Fix

#12457 Auto-transfer system no longer factors in players who are still in the lobby
  code/controllers/subsystem/autotransfer.dm
  code/modules/client/verbs/ooc.dm
Labels: Tweak

#12431 Furnishes metastation's brig a bit
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Mapping, Tweak

#12510 Changes service experience requirements to collect playtime from the service department
  code/controllers/subsystem/department.dm
Labels: Fix

#12501 Cyborg radios have the same hearing range as normal headsets now.
  code/game/objects/items/devices/radio/radio.dm
Labels: Tweak

#12490 Reenables the GPS
  code/game/machinery/suit_storage_unit.dm
  code/game/objects/items/devices/gps.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/objective_types/vip_extraction.dm
Labels: Fix

#12523 [S] Fixes some bugs with records consoles.
  code/__HELPERS/sanitize_values.dm
  code/__HELPERS/text.dm
  code/game/machinery/computer/records/medical.dm
  code/game/machinery/computer/records/records.dm
  code/game/machinery/computer/records/security.dm
  code/modules/mob/living/carbon/human/human.dm
  tgui/packages/tgui/components/RestrictedInput.jsx
  tgui/packages/tgui/interfaces/SecurityRecords/CrimeWatcher.tsx
  tgui/packages/tgui/interfaces/WarrantConsole.tsx
Labels: p-Priority: Critical, Fix, TGUI-Changes

#12527 transforming hotfix
  code/datums/status_effects/status_effect.dm
  code/game/objects/items/tools/powertools.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  icons/obj/lavaland/artefacts.dmi
  icons/obj/surgery.dmi
Labels: Sprites, Fix
