Repository BeeStation/BeeStation-Hornet, pull requests merged in 2025-07, with the labels that each got.

#12236 TGUI Changelog
  .gitattributes
  .github/workflows/compile_changelogs.yml
  beestation.dme
  code/_globalvars/tgui.dm
  code/datums/changelog/changelog.dm
  code/game/world.dm
  code/modules/asset_cache/asset_list.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/mob/dead/crew_manifest.dm
  code/modules/tgui/tgui.dm
  html/ban.png
  html/bug-minus.png
  html/burn-exclamation.png
  html/changelog.css
  html/changelogs/example.yml
  html/chrome-wrench.png
  html/coding.png
  html/cross-circle.png
  html/hard-hat-exclamation.png
  html/image-minus.png
  html/image-plus.png
  html/music-minus.png
  html/music-plus.png
  html/scales.png
  html/spell-check.png
  html/templates/footer.html
  html/templates/header.html
  html/tick-circle.png
  html/wrench-screwdriver.png
  interface/interface.dm
  tgui/packages/tgfont/config.cjs
  tgui/packages/tgfont/icons/image-minus.svg
  tgui/packages/tgfont/icons/image-plus.svg
  tgui/packages/tgfont/icons/prosthetic-full.svg
  tgui/packages/tgfont/icons/sound-minus.svg
  tgui/packages/tgfont/icons/sound-plus.svg
  tgui/packages/tgui-bench/lib/benchmark.js
  tgui/packages/tgui-dev-server/link/client.cjs
  tgui/packages/tgui/interfaces/Changelog.tsx
  tgui/packages/tgui/package.json
  tgui/packages/tgui/styles/atomic/links.scss
  tgui/packages/tgui/styles/interfaces/Changelog.scss
  tgui/packages/tgui/styles/main.scss
  tgui/yarn.lock
  tools/WebhookProcessor/github_webhook_processor.php
  tools/build/build.js
  tools/changelog/makeChangelog.bat
  tools/changelog/ss13_genchangelog.py
  tools/ci/check_changelogs.sh
  tools/tgs4_scripts/PreSynchronize.ps1
  tools/tgs4_scripts/PreSynchronize.sh
Labels: GitHub, Tools, Server, TGUI-Changes, Testmerge Passed

#12244 Trasen-Knox hud package
  code/__DEFINES/hud.dm
  code/_onclick/hud/hud.dm
  code/modules/tooltip/tooltip.html
  icons/hud/64x16_actions.dmi
  icons/hud/style/screen_clockwork.dmi
  icons/hud/style/screen_midnight.dmi
  icons/hud/style/screen_midnightknox.dmi
  icons/hud/style/screen_nyanknox.dmi
  icons/hud/style/screen_operative.dmi
  icons/hud/style/screen_plasmafire.dmi
  icons/hud/style/screen_plasmaknox.dmi
  icons/hud/style/screen_retro.dmi
  icons/hud/style/screen_slimecore.dmi
  icons/hud/style/screen_trasenknox.dmi
  tools/savefileimporter/code/savefile_parser.dm
Labels: Needs Testmerge, Tweak, Feature, Sprites, Tools, Removal

#12939 fix some opendream and dreamchecker lints
  code/datums/elements/_element.dm
  code/datums/elements/obj_regen.dm
  tools/ci/od_lints.dm
Labels: Tools

#12950 [s] BeeAuth: DO NOT LOG SESSION TOKENS, various fixes
  code/modules/client/client_procs.dm
  code/modules/client/login/client_login.dm
Labels: Fix, Server

#12953 Small firelock map changes
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
Labels: Mapping, Feature, Removal

#12910 [IDED] Rebalances Venus Human Traps
  code/__DEFINES/robots.dm
  code/datums/status_effects/debuffs.dm
  code/modules/mob/living/simple_animal/hostile/venus_human_trap.dm
Labels: Feature, Balance/Rebalance, i ded, :ballot_box_with_check: Good PR

#12940 Updates piercing syringes & pierce protection (+fixes syringe gun not working)
  code/__DEFINES/obj_flags.dm
  code/game/objects/items/kitchen.dm
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/projectiles/projectile/bullets/dart_syringe.dm
  code/modules/projectiles/projectile/energy/ebow.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/xenobiology/crossbreeding/_clothing.dm
Labels: Fix, Balance/Rebalance

#12957 Fixes TGUI_Emoji input
  tgui/packages/tgui/interfaces/EmojiInputModal.jsx
Labels: Fix, TGUI-Changes

#12782 Adds 3 more Mime PDA/OOC/LOOC emojis
  icons/emoji.dmi
Labels: Sprites

#12976 Oxygen Candles / Emergency locker standardisation
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base2.dmm
  _maps/RandomRuins/SpaceRuins/onehalf.dmm
  _maps/RandomRuins/SpaceRuins/power_puzzle.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CardinalStation/CardinalStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/EchoStation/EchoStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  _maps/shuttles/emergency/emergency_tiny.dmm
  _maps/shuttles/whiteship/whiteship_meta.dmm
  beestation.dme
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/devices/oxycandle.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/uplink/uplink_items.dm
  icons/obj/lighting.dmi
Labels: Mapping, Sprites

#12905 [QOL] storage collection improvement
  code/datums/storage/storage.dm
Labels: Feature

#12902 Buffs, bugfixes and tweaks for motorized wheelchairs.
  code/datums/components/riding/riding_vehicle.dm
  code/modules/vehicles/motorized_wheelchair.dm
Labels: Tweak, Fix, Balance/Rebalance

#12977 Personal Airlocks - Claimable Airlocks
  _maps/map_files/CardinalStation/CardinalStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  beestation.dme
  code/game/machinery/doors/airlock_personal.dm
  code/game/objects/items/stacks/sheets/mineral/metals_recipes.dm
  icons/obj/doors/airlocks/station/private.dmi
Labels: Mapping, Sprites

#12158 Reworks the vault's bank machine, now contains all station budgets instead of only cargo's
  code/game/machinery/bank_machine.dm
Labels: Balance/Rebalance, Refactor, Code Improvement

#12937 516: TGUI Say DPI scaling support
  tgui/packages/tgui-say/handlers/componentMount.tsx
  tgui/packages/tgui-say/handlers/enter.tsx
  tgui/packages/tgui-say/handlers/escape.tsx
  tgui/packages/tgui-say/handlers/force.tsx
  tgui/packages/tgui-say/handlers/setSize.tsx
  tgui/packages/tgui-say/helpers/index.tsx
  tgui/packages/tgui-say/interfaces/TguiSay.tsx
  tgui/packages/tgui-say/types/index.tsx
Labels: Feature, TGUI-Changes

#12988 Removes TC fuel rods
  code/modules/power/rbmk/fuel_rods.dm
  code/modules/uplink/uplink_items.dm
Labels: Removal

#12643 Changes the job assignment algorithm and reworks job availability at low populations.
  code/__DEFINES/jobs.dm
  code/__HELPERS/cmp.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/ticker.dm
  code/datums/map_adjustment.dm
  code/datums/station_traits/exclusive_traits.dm
  code/game/machinery/computer/card.dm
  code/game/objects/effects/landmarks.dm
  code/modules/admin/admin.dm
  code/modules/admin/secrets.dm
  code/modules/admin/topic.dm
  code/modules/client/preferences/submodules/preference_jobs.dm
  code/modules/exploration_crew/exploration_vendor.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/ai.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/atmospheric_technician.dm
  code/modules/jobs/job_types/bartender.dm
  code/modules/jobs/job_types/botanist.dm
  code/modules/jobs/job_types/brig_physician.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/cargo_technician.dm
  code/modules/jobs/job_types/chaplain.dm
  code/modules/jobs/job_types/chemist.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/clown.dm
  code/modules/jobs/job_types/cook.dm
  code/modules/jobs/job_types/curator.dm
  code/modules/jobs/job_types/cyborg.dm
  code/modules/jobs/job_types/deputy.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/exploration_team.dm
  code/modules/jobs/job_types/geneticist.dm
  code/modules/jobs/job_types/gimmick.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/janitor.dm
  code/modules/jobs/job_types/lawyer.dm
  code/modules/jobs/job_types/medical_doctor.dm
  code/modules/jobs/job_types/mime.dm
  code/modules/jobs/job_types/paramedic.dm
  code/modules/jobs/job_types/posibrain.dm
  code/modules/jobs/job_types/quartermaster.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/jobs/job_types/scientist.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/shaft_miner.dm
  code/modules/jobs/job_types/station_engineer.dm
  code/modules/jobs/job_types/virologist.dm
  code/modules/jobs/job_types/warden.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/modular_computers/file_system/programs/jobmanagement.dm
  config/game_options.txt
  config/jobs.txt
  tgui/packages/tgui/interfaces/PreferencesMenu/JobsPage.tsx
Labels: Tweak, Config Update, Administration, TGUI-Changes

#12602 Handcuff balance changes, Ruko edition!
  code/__DEFINES/combat.dm
  code/_onclick/hud/alert.dm
  code/game/objects/items/handcuffs.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/clothing/gloves/color.dm
  code/modules/clothing/suits/straightjacket.dm
  code/modules/mob/living/carbon/alien/humanoid/humanoid.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
Labels: Tweak, Balance/Rebalance, Code Improvement, Balance Approved

#12959 Fix spritesheet caches being empty on the server
  code/modules/antagonists/role_preference/role_midrounds.dm
  code/modules/asset_cache/asset_list.dm
Labels: Tweak, Fix

#13008 Clarke now moves slower on station
  code/modules/vehicles/mecha/working/clarke.dm
Labels: i ded

#12951 Fix get_step_multiz UP always returning UP instead of a turf
  code/__HELPERS/multiz_helpers.dm
Labels: Fix

#13050 Fixes weighted pick selecting things with 0 weight and modifying the source list
  code/__HELPERS/_lists.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_unfavorable_situation.dm
  code/game/gamemodes/game_mode.dm
Labels: p-Priority: High

#13048 Poisoned Knife buff
  code/game/objects/items/kitchen.dm
  code/game/objects/items/knives.dm
  code/modules/admin/battle_royale.dm
  code/modules/uplink/uplink_items.dm
Labels: Administration

#13053 MCR - Cell Chargers in Public areas
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CardinalStation/CardinalStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/EchoStation/EchoStation.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
Labels: Mapping

#13029 Proper fix to oversized icons on 516 clients
  code/__DEFINES/screentips.dm
  code/modules/screentips/atom_extensions.dm
  icons/ui_icons/chat/chat_icons.dmi
  icons/ui_icons/screentips/516/cursor_hints.dmi
  icons/ui_icons/screentips/516/tool_hints.dmi
  interface/skin.dmf
Labels: Sprites

#13039 Add library scanner to echostation
  _maps/map_files/EchoStation/EchoStation.dmm
Labels: Mapping
