Repository BeeStation/BeeStation-Hornet, pull requests merged in 2025-02, with the labels that each got.

#12210 Fixes fullscreen being small when unfullscreening
  code/modules/client/preferences/entries/player/fullscreen.dm
Labels: Fix

#12212 Fixes firealarm light issue
  code/modules/power/lighting/light.dm
Labels: Fix

#12165 Added a new traitor book that allows you to pickpocket people stealthily
  code/__DEFINES/traits/declarations.dm
  code/_globalvars/traits/_traits.dm
  code/datums/elements/strippable.dm
  code/game/objects/items/granters.dm
  code/modules/mob/living/carbon/human/human_stripping.dm
  code/modules/uplink/uplink_items.dm
  icons/obj/library.dmi
Labels: Mapping, Feature, Sprites, Balance Approved

#12211 Reverts undocumented Flandstation mapedit
  _maps/map_files/FlandStation/FlandStation.dmm
Labels: Mapping, Feature

#12214 514 warning & Supports 515 compilation features.
  .github/max_required_byond_client.txt
  code/modules/client/client_procs.dm
  config/config.txt
Labels: GitHub, Config Update

#12203 Implements greater job role requirements for consistently misused roles
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/atmospheric_technician.dm
  code/modules/jobs/job_types/botanist.dm
  code/modules/jobs/job_types/chaplain.dm
  code/modules/jobs/job_types/chemist.dm
  code/modules/jobs/job_types/curator.dm
  code/modules/jobs/job_types/cyborg.dm
Labels: Tweak

#12162 [PORT]: The Extremely Qualified Doctor...
  code/modules/mob/living/silicon/robot/robot_modules.dm
  icons/mob/robots.dmi
Labels: Feature, Sprites

#12226 Fixes Xenoarch Crashes
  code/modules/xenoarchaeology/traits/xenoartifact_minors.dm
Labels: Fix

#12230 Makes the RPD stop hitting pipes.
  code/game/objects/items/RPD.dm
Labels: Fix

#12215 Resolves the fullscreen warning issue before we forget
  code/modules/client/preferences/entries/player/fullscreen.dm
Labels: Code Improvement

#12150 [PORT] Heretics dream of objects around unused influences
  code/modules/antagonists/heretic/heretic_antag.dm
  code/modules/flufftext/Dreaming.dm
  strings/dreamstrings.txt
  strings/tips.txt
  tgui/packages/tgui/interfaces/AntagInfoHeretic.tsx
Labels: Feature, Balance/Rebalance, Refactor, Removal, Code Improvement, TGUI-Changes

#12229 Normalizes the sounds of powertools
  sound/items/drill_hit.ogg
  sound/items/drill_use.ogg
  sound/items/jaws_cut.ogg
  sound/items/jaws_pry.ogg
Labels: Tweak, Sound

#12223 Fixes bug from juicing bug fix fix fix
  code/modules/reagents/chemistry/holder.dm
Labels: Fix

#12185 Removes the blindspot from lavaland syndicate base
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
Labels: Mapping, Balance/Rebalance

#12228 Fixes admin-mentor ooc not being hot pink
  code/modules/mentor/mentorsay.dm
Labels: Fix, Administration

#11930 Adds 4 cool jackets
  code/modules/clothing/suits/jacket.dm
  code/modules/vending/autodrobe.dm
  icons/mob/clothing/suits/jacket.dmi
  icons/obj/clothing/suits/jacket.dmi
Labels: Feature, Sprites

#12222 fixes radstation holopads
  _maps/map_files/RadStation/RadStation.dmm
Labels: Mapping, Fix

#12161 Shadow sect rework part 1/2
  beestation.dme
  code/__DEFINES/traits/declarations.dm
  code/__DEFINES/traits/sources.dm
  code/_globalvars/traits/_traits.dm
  code/datums/traits/positive_quirk.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/init_signals.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/religion/sects/shadow_sect.dm
  code/modules/surgery/organs/eyes.dm
Labels: Feature, Removal, Code Improvement

#12231 Adjusts swarmer capabilities
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/modules/antagonists/swarmer/swarmer.dm
  code/modules/antagonists/swarmer/swarmer_event.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/swarmer.dm
Labels: Tweak, Balance/Rebalance

#11846 Syndicate Survey Shuttle - Alternative lavaland spawn
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base2.dmm
  code/datums/ruins/lavaland.dm
  code/game/area/areas/ruins/lavaland.dm
  code/modules/power/apc/apc_mapping.dm
  code/modules/ruins/lavaland_ruin_code.dm
Labels: Mapping, Feature, Balance/Rebalance, Code Improvement

#11760 Merges mob properties with traits, adding value traits & modularising mutant skin colour
  beestation.dme
  code/__DEFINES/_heap_helpers/heap.dm
  code/__DEFINES/_mob_properties.dm
  code/__DEFINES/traits/_traits.dm
  code/__DEFINES/traits/declarations.dm
  code/__DEFINES/traits/priorities.dm
  code/__DEFINES/traits/sources.dm
  code/__HELPERS/heap.dm
  code/__HELPERS/path.dm
  code/_globalvars/traits/_traits.dm
  code/datums/mutations/hulk.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/living.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  code/modules/unit_tests/__DEFINES/test_defines.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/trait_tests.dm
Labels: Fix, Code Improvement

#11957 Fix clock cult armor
  code/modules/antagonists/clock_cult/items/brass_clothing.dm
Labels: Fix, p-Priority: High

#12074 removes disabler from hos loadout
  code/modules/jobs/job_types/head_of_security.dm
Labels: Balance/Rebalance

#12260 Fixes stat crashes
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/nymph.dm
  tgui/packages/tgui-panel/stat/StatStatus.js
Labels: Fix, TGUI-Changes, p-Priority: High

#12248 Fixes admin transforms transferring the wrong minds
  code/datums/dna.dm
  code/modules/mob/mob_transformation_simple.dm
Labels: Fix

#11188 [RECOUP/PORT] large refactor of machine/power code to cut down on processing time and wasted lists + Fixes age-old apc exploit
  code/__DEFINES/machines.dm
  code/controllers/subsystem/machines.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas.dm
  code/game/atoms.dm
  code/game/machinery/Beacon.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/cell_charger.dm
  code/game/machinery/dish_drive.dm
  code/game/machinery/hologram.dm
  code/game/machinery/launch_pad.dm
  code/game/machinery/recharger.dm
  code/game/machinery/rechargestation.dm
  code/game/machinery/stasis.dm
  code/modules/NTNet/relays.dm
  code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/atmospherics/machinery/other/miner.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/holodeck/computer.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/power/apc/apc_main.dm
  code/modules/power/monitor.dm
  code/modules/power/power.dm
  code/modules/power/powernet.dm
  code/modules/power/singularity/emitter.dm
  code/modules/reagents/chemistry/machinery/pandemic.dm
  code/modules/station_goals/shield.dm
Labels: Tweak, Feature, Fix, Refactor, Code Improvement

#12256 "Fine, I'll do it myself." Assblasts chaplain holodeck mob abuse.
  code/modules/religion/sects/necro_sect.dm
Labels: Fix

#12269 Cyborgs can quickdrop modules again
  code/datums/keybinding/_defines.dm
Labels: Fix, i ded

#12262 Moves "Observe" from OOC category.
  code/modules/mob/dead/observer/observer.dm
Labels: Tweak

#12208 Lazarus injector fix and update
  code/modules/mining/equipment/lazarus_injector.dm
Labels: Tweak, Feature, Fix

#12273 Adds the ability to loosen ties to put around your head
  code/modules/clothing/neck/_neck.dm
  icons/mob/clothing/neck.dmi
Labels: Feature, Sprites

#12272 Emissive Spider Eyes + Spider Fixes/QoL
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  icons/hud/actions/actions_animal.dmi
  icons/mob/animal.dmi
Labels: Feature, Sprites, Fix, Removal

#12274 Fixes advanced wirebrush behavior
  code/game/objects/items/tools/wirebrush.dm
Labels: Fix

#12282 Fixes roundstart bolted door lights
  code/game/machinery/doors/airlock.dm
  code/modules/assembly/flash.dm
  code/modules/clothing/glasses/_glasses.dm
Labels: Feature, Fix, Code Improvement

#12281 Fixes chameleon clothing
  code/modules/clothing/chameleon.dm
Labels: Fix

#12243 Janky actions unit test
  code/__HELPERS/test_helpers.dm
  code/datums/actions/action.dm
  code/game/atoms.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/spyglasses.dm
  code/game/objects/items/melee/misc.dm
  code/game/turfs/open/space/space.dm
  code/modules/clothing/chameleon.dm
  code/modules/clothing/shoes/taeclowndo.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/events/wizard/greentext.dm
  code/modules/mining/minebot.dm
  code/modules/modular_computers/computers/item/tablet.dm
  code/modules/multiz/zmimic/mimic_movable.dm
  code/modules/projectiles/guns/energy/laser_gatling.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/spells/spell_types/touch/_touch.dm
  code/modules/surgery/anesthetic_machine.dm
  code/modules/unit_tests/__DEFINES/test_defines.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/janky_actions.dm
  code/modules/wiremod/components/list/pop.dm
Labels: Feature, Fix

#12242 Monkey cube resprites
  code/game/objects/items/food/monkeycube.dm
  icons/obj/food/food.dmi
  icons/obj/storage/box.dmi
Labels: Feature, Sprites

#12201 Some blob changes
  beestation.dme
  code/__DEFINES/antagonists.dm
  code/__DEFINES/blob_defines.dm
  code/_onclick/hud/blob_overmind.dm
  code/datums/diseases/advance/symptoms/blobspores.dm
  code/modules/antagonists/blob/blob.dm
  code/modules/antagonists/blob/blob_mobs.dm
  code/modules/antagonists/blob/blobstrains/_blobstrain.dm
  code/modules/antagonists/blob/blobstrains/_reagent.dm
  code/modules/antagonists/blob/blobstrains/electromagnetic_web.dm
  code/modules/antagonists/blob/blobstrains/replicating_foam.dm
  code/modules/antagonists/blob/blobstrains/shifting_fragments.dm
  code/modules/antagonists/blob/overmind.dm
  code/modules/antagonists/blob/powers.dm
  code/modules/antagonists/blob/structures/_blob.dm
  code/modules/antagonists/blob/structures/core.dm
  code/modules/antagonists/blob/structures/factory.dm
  code/modules/antagonists/blob/structures/node.dm
  code/modules/antagonists/blob/structures/resource.dm
  code/modules/antagonists/blob/structures/shield.dm
  code/modules/mob/transform_procs.dm
Labels: Tweak, Feature, Refactor, Code Improvement

#11849 Assassination target buffs for exploration
  code/modules/clothing/shoes/taeclowndo.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/objective_types/assassination.dm
Labels: Balance/Rebalance

#12249 Adds exploration vouchers, Ghost Shift kit, Gunslinger kit
  beestation.dme
  code/modules/clothing/spacesuits/_spacesuits.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/exploration_crew/exploration_ballistic_gun.dm
  code/modules/exploration_crew/exploration_laser_gun.dm
  code/modules/exploration_crew/exploration_vendor.dm
  code/modules/jobs/job_mail.dm
  code/modules/jobs/job_types/exploration_team.dm
  code/modules/mining/machine_vending.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/generator_settings/generator_abandoned.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/generator_settings/generator_blob.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/generator_settings/generator_netherworld.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/generator_settings/generator_ratvar.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/generator_settings/generator_xeno.dm
  icons/obj/ammo.dmi
  icons/obj/guns/energy.dmi
  icons/obj/guns/projectile.dmi
Labels: Tweak, Feature, Sprites

#11818 Moves the CorgStation gateway
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: Mapping, Feature

#12288 Fixes something in vine code and makes some more voting code use switch()
  code/controllers/subsystem/vote.dm
  code/modules/events/spacevine.dm
Labels: Fix

#12276 Mortar fix and adding syringe use to chem bags
  code/modules/reagents/reagent_containers/blood_pack.dm
  code/modules/reagents/reagent_containers/chem_bag.dm
  code/modules/reagents/reagent_containers/cups/_cup.dm
Labels: Feature, Fix

#12247 Swarmer cost fixes + traps work on mechs
  code/_onclick/hud/swarmer.dm
  code/modules/antagonists/swarmer/swarmer.dm
Labels: Tweak, Fix

#12299 Fixes stale issues
  .github/workflows/stale_issues.yml
  .github/workflows/stale_prs.yml
Labels: GitHub, Config Update, Code Improvement

#11078 New Syndicate Operative Base & ship
  _maps/map_files/generic/CentCom.dmm
  _maps/shuttles/infiltrator/infiltrator_advanced.dmm
  code/__DEFINES/cargo.dm
  code/game/objects/effects/contraband.dm
  code/game/turfs/open/floor/fancy_floor.dm
  code/modules/cargo/supplypod.dm
  icons/obj/contraband.dmi
  icons/obj/supplypods.dmi
Labels: Mapping, Tweak, Feature, Sprites, Fix, Grammar and Formatting, Balance/Rebalance, Refactor, Sound, Removal, Code Improvement, Server, p-Priority: High

#12193 Non-sleeping, grouped chat messages without vertical overflow/underflow
  code/datums/chatmessage.dm
  code/game/atoms.dm
Labels: Fix, Testmerge Passed

#12308 Fixes RBMK duplicating gases
  code/modules/power/rbmk/rbmk_main_processes.dm
Labels: Fix

#12302 Right click no longer picks up items
  code/game/objects/items.dm
Labels: Tweak

#12298 fixes the overlapped item reclaimer
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Mapping, Tweak

#10158 Ports Deadspace navigation
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/EchoStation/EchoStation.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/map_files/RadStation/RadStation.dmm
  _maps/shuttles/emergency/emergency_delta.dmm
  _maps/shuttles/escape_pod/escape_pod_default.dmm
  beestation.dme
  code/__DEFINES/bot_defines.dm
  code/__DEFINES/hud.dm
  code/__HELPERS/path.dm
  code/_globalvars/lists/mapping.dm
  code/_globalvars/lists/objects.dm
  code/_onclick/hud/alien.dm
  code/_onclick/hud/alien_larva.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/pai.dm
  code/_onclick/hud/robot.dm
  code/_onclick/hud/screen_objects.dm
  code/game/area/areas.dm
  code/game/machinery/doors/firedoor.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/structures/ladders.dm
  code/game/objects/structures/stairs.dm
  code/modules/mob/living/navigation.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  icons/effects/landmarks_static.dmi
  icons/effects/navigation.dmi
  icons/hud/style/screen_clockwork.dmi
  icons/hud/style/screen_midnight.dmi
  icons/hud/style/screen_operative.dmi
  icons/hud/style/screen_plasmafire.dmi
  icons/hud/style/screen_slimecore.dmi
Labels: Mapping, Feature, Sprites, Fix

#12321 Fixes right click actions not working on items
  code/game/objects/items.dm
Labels: Fix

#12311 Exploration laser repeater and ammo fixes
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/generator_settings/generator_abandoned.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/generator_settings/generator_blob.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/generator_settings/generator_netherworld.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/generator_settings/generator_ratvar.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/generator_settings/generator_xeno.dm
Labels: Fix, Balance/Rebalance, Balance Approved

#11505 Newfood: Ants & Decomp
  beestation.dme
  code/__DEFINES/dcs/flags.dm
  code/__DEFINES/food.dm
  code/__DEFINES/status_effects.dm
  code/_globalvars/lists/typecache.dm
  code/datums/ai/hunting_behavior/hunting_vermin.dm
  code/datums/components/caltrop.dm
  code/datums/components/crafting/crafting_lists/foodstuffs/recipes_misc.dm
  code/datums/components/crafting/crafting_lists/foodstuffs/recipes_pizza.dm
  code/datums/components/crafting/crafting_lists/foodstuffs/recipes_spaghetti.dm
  code/datums/components/food/decomposition.dm
  code/datums/status_effects/debuffs.dm
  code/datums/status_effects/neutral.dm
  code/datums/status_effects/status_effect.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/effects/decals/cleanable/humans.dm
  code/game/objects/effects/decals/cleanable/misc.dm
  code/game/objects/effects/decals/cleanable/robots.dm
  code/game/objects/items/food/_food.dm
  code/game/objects/items/food/bread.dm
  code/game/objects/items/food/egg.dm
  code/game/objects/items/food/meatslab.dm
  code/game/objects/items/food/misc.dm
  code/game/objects/items/food/packaged.dm
  code/game/objects/items/food/pizza.dm
  code/game/objects/items/food/sweets.dm
  code/game/objects/items/stacks/sheets/mineral/glass.dm
  code/game/objects/items/trinkets/dice.dm
  code/game/turfs/open/dirtystation.dm
  code/modules/food_and_drinks/plate.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/mining/lavaland/ash_flora.dm
  code/modules/mob/living/basic/vermin/cockroach.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/hostile/ant.dm
  code/modules/mob/living/simple_animal/kalo.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/power/lighting/light_items.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/reagent_containers/cups/glassbottle.dm
  code/modules/surgery/organs/tongue.dm
  icons/obj/debris.dmi
  icons/obj/food/food.dmi
  tgui/packages/tgui/interfaces/PreferencesMenu/SpeciesPage.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/data.ts
Labels: Feature, Sprites, TGUI-Changes

#12206 Greatly improve usability of admin brief outfit preference
  code/modules/client/preferences/entries/player/admin.dm
  tgui/packages/tgui/interfaces/PreferencesMenu/GamePreferencesPage.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/base.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/admin.tsx
Labels: Code Improvement, TGUI-Changes

#12315 Fix IPC emotes not having sound
  code/modules/mob/living/carbon/human/emote.dm
Labels: Feature, Fix

#12301 Combat mode hotkeys & Unified looking/moving
  code/datums/keybinding/living.dm
  code/datums/keybinding/mob.dm
  code/modules/mob/living/emote.dm
  code/modules/multiz/movement/mob/living_zmove.dm
Labels: Tweak, Feature

#12330 Ports a Syndicate snake decal from TG
  icons/turf/decals.dmi
Labels: Feature, Sprites

#12296 Adds pipegas overlays
  beestation.dme
  code/controllers/subsystem/air.dm
  code/modules/admin/admin_verbs.dm
  code/modules/atmospherics/Atmospherics.md
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/atmospherics/machinery/datum_pipeline.dm
  code/modules/atmospherics/machinery/pipes/bridge_pipe.dm
  code/modules/atmospherics/machinery/pipes/color_adapter.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/he_pipes.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/junction.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/manifold.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/manifold4w.dm
  code/modules/atmospherics/machinery/pipes/layermanifold.dm
  code/modules/atmospherics/machinery/pipes/multiz.dm
  code/modules/atmospherics/machinery/pipes/pipe_spritesheet_helper.dm
  code/modules/atmospherics/machinery/pipes/pipes.dm
  code/modules/atmospherics/machinery/pipes/smart.dm
  icons/obj/atmospherics/pipes/!pipe_gas_overlays.dmi
  icons/obj/atmospherics/pipes/!pipes_bitmask.dmi
  icons/obj/atmospherics/pipes/pipe_template_pieces.dmi
  icons/obj/atmospherics/pipes/pipes_bitmask.dmi
  tgui/packages/tgui/constants.ts
Labels: Feature, Sprites, Administration, TGUI-Changes

#12289 [PORT]: Objectify smite, transformation animation helper.
  beestation.dme
  code/__DEFINES/status_effects.dm
  code/__DEFINES/traits/sources.dm
  code/__HELPERS/icons.dm
  code/datums/components/itembound.dm
  code/game/objects/items/food/bread.dm
  code/modules/admin/smites/become_object.dm
  code/modules/admin/verbs/randomverbs.dm
  icons/effects/effects.dmi
Labels: Sprites, Administration, Code Improvement

#12342 Fix pathfinding heap
  code/__DEFINES/_heap_helpers/heap.dm
  code/__DEFINES/traits/_traits.dm
  code/__HELPERS/path.dm
Labels: Fix

#12131 Echo Station Atmos 2.0
  _maps/map_files/EchoStation/EchoStation.dmm
Labels: Mapping, Feature, Removal

#12348 Fix holoparasite attacks
  code/modules/holoparasite/holoparasite_attack.dm
Labels: Fix, p-Priority: High

#12327 Fixes RD hardsuit integrated doppler array
  code/game/machinery/doppler_array.dm
  code/modules/clothing/spacesuits/hardsuit.dm
Labels: Fix

#12320 Minor Holiday Change
  code/modules/holiday/holidays.dm
Labels: Tweak

#12169 [MDB Ignore] Removal of glass firelocks and directional firelocks
  _maps/RuinGeneration/13x13_corgarmory.dmm
  _maps/RuinGeneration/13x13_corgrobotics.dmm
  _maps/RuinGeneration/13x13_donutroom.dmm
  _maps/RuinGeneration/13x13_supermatter_containment.dmm
  _maps/RuinGeneration/13x17_permabrig.dmm
  _maps/RuinGeneration/21x17_shuttledock.dmm
  _maps/RuinGeneration/21x29_solars.dmm
  _maps/RuinGeneration/5x5_14_hallway-end-east.dmm
  _maps/RuinGeneration/5x5_14_hallway-end-north.dmm
  _maps/RuinGeneration/5x5_14_hallway-end-south.dmm
  _maps/RuinGeneration/5x5_14_hallway-end-west.dmm
  _maps/RuinGeneration/9x13_kitchen.dmm
  _maps/RuinGeneration/9x9_chemlab.dmm
  _maps/flandstation.json
  _maps/map_files/EchoStation/EchoStation.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/debug/runtimestation.dmm
  _maps/shuttles/emergency/emergency_bar.dmm
  _maps/shuttles/emergency/emergency_corg.dmm
  _maps/shuttles/emergency/emergency_fland.dmm
  _maps/shuttles/emergency/emergency_meta.dmm
  _maps/shuttles/emergency/emergency_omega.dmm
  _maps/shuttles/emergency/emergency_russiafightpit.dmm
  _maps/shuttles/emergency/emergency_scrapheap.dmm
  _maps/shuttles/emergency/emergency_supermatter.dmm
  _maps/shuttles/emergency/emergency_tiny.dmm
  _maps/shuttles/exploration/exploration_rad.dmm
  code/__HELPERS/path.dm
  code/game/machinery/doors/firedoor.dm
  code/game/objects/effects/spawners/structure.dm
  code/game/objects/items/stacks/sheets/mineral/glass_recipes.dm
  code/game/objects/items/stacks/sheets/mineral/metals_recipes.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/ruin_generator/ruin_generator.dm
  icons/obj/doors/firelocks/doorfirewindow.dmi
Labels: Mapping, Tweak, Feature, Sprites, Removal, Code Improvement

#12328 Whiteship revamps: NT Personal Trader & Syndicate Probe
  _maps/shuttles/whiteship/whiteship_box.dmm
  _maps/shuttles/whiteship/whiteship_cere.dmm
  _maps/shuttles/whiteship/whiteship_delta.dmm
  _maps/shuttles/whiteship/whiteship_meta.dmm
  _maps/shuttles/whiteship/whiteship_pubby.dmm
  code/datums/shuttles.dm
Labels: Mapping, Tweak

#12312 Smartwire mapping compatability
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/EchoStation/EchoStation.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
Labels: Mapping, Tweak, p-Priority: Medium

#12332 Syndicate Outpost Atmos Fixes
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base2.dmm
Labels: Mapping, Fix

#12346 Fix: biobags and chembags accept bottles again
  code/game/objects/items/storage/bags.dm
Labels: Fix

#12255 Mentor fixes and TGUIification
  code/datums/brain_damage/mrat.dm
  code/modules/mentor/mentor_verbs.dm
  code/modules/mentor/mentorsay.dm
Labels: Tweak, Fix

#12359 Remakes Pancake and Egg cooking
  beestation.dme
  code/__DEFINES/dcs/signals/signals_atom/signals_atom.dm
  code/__DEFINES/dcs/signals/signals_datum/signals_reagent.dm
  code/datums/components/crafting/crafting_lists/foodstuffs/recipes_cake.dm
  code/datums/components/crafting/crafting_lists/foodstuffs/recipes_egg.dm
  code/datums/components/crafting/crafting_lists/foodstuffs/recipes_pastry.dm
  code/datums/components/grillable.dm
  code/game/objects/items/food/cake.dm
  code/game/objects/items/food/egg.dm
  code/game/objects/items/food/mexican.dm
  code/game/objects/items/food/pancakes.dm
  code/game/objects/items/food/pastries.dm
  code/game/objects/items/food/salad.dm
  code/game/objects/items/food/snacks.dm
  code/game/objects/items/food/spaghetti.dm
  code/game/objects/items/manuals.dm
  code/game/objects/items/stacks/sheets/organic/leather.dm
  code/modules/food_and_drinks/kitchen_machinery/griddle.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/food_and_drinks/recipes/food_mixtures.dm
  code/modules/hydroponics/grown/onion.dm
  code/modules/reagents/chemistry/machinery/reagentgrinder.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  icons/obj/food/egg.dmi
  icons/obj/food/food.dmi
  icons/obj/food/mexican.dmi
  icons/obj/food/pancakes.dmi
  icons/obj/food/pastries.dmi
  icons/obj/food/piecake.dmi
  icons/obj/food/snacks.dmi
Labels: Tweak, Feature, Sprites, Code Improvement
