Repository BeeStation/BeeStation-Hornet, pull requests merged in 2025-05, with the labels that each got.

#12125 GAGS Berets
  _maps/RandomRuins/SpaceRuins/swarmerstation13.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FlandStation/FlandStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  code/__DEFINES/flags.dm
  code/_globalvars/bitfields.dm
  code/datums/greyscale/greyscale_configs.dm
  code/datums/greyscale/json_configs/beret.json
  code/datums/greyscale/json_configs/beret_badge.json
  code/datums/greyscale/json_configs/beret_badge_worn.json
  code/datums/greyscale/json_configs/beret_worn.json
  code/game/gamemodes/legacy_gang_outfits.dm
  code/game/machinery/washing_machine.dm
  code/game/objects/items/tools/screwdriver.dm
  code/game/objects/items/trinkets/plushes.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/admin/greyscale_modify_menu.dm
  code/modules/cargo/packs.dm
  code/modules/clothing/head/collectable.dm
  code/modules/clothing/head/frenchberet.dm
  code/modules/clothing/head/hat.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/masks/bandana.dm
  code/modules/clothing/shoes/color.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/under/color.dm
  code/modules/vending/_vending.dm
  code/modules/vending/autodrobe.dm
  code/modules/vending/clothesmate.dm
  code/modules/vending/wardrobes.dm
  icons/mob/clothing/head/beret.dmi
  icons/mob/clothing/head/beret_unique.dmi
  icons/obj/clothing/head/beret.dmi
  icons/obj/clothing/head/beret_unique.dmi
  tgui/packages/tgui/interfaces/GreyscaleModifyMenu.tsx
  tools/UpdatePaths/Scripts/12125_GAGSberets.txt
Labels: Mapping, Stale, Feature, Sprites, Administration, Tools, Removal, TGUI-Changes

#12669 Fix cyborg swapping.
  code/game/machinery/computer/teleporter.dm
  code/modules/mob/living/living.dm
Labels: Fix

#12670 Fix: Energy Axe sprite
  icons/obj/transforming_energy.dmi
Labels: Sprites, Fix

#12641 Fixes the bounty reward displayed amount
  code/controllers/subsystem/economy.dm
  code/modules/cargo/bounty.dm
Labels: Fix, Code Improvement

#12691 [Hotfix] Disable Artifact Animal Trait
  code/modules/xenoarchaeology/misc/items.dm
  code/modules/xenoarchaeology/traits/majors/animalize.dm
Labels: Tweak, Fix

#12679 makes fortune cookies drop paper again
  code/game/objects/items/food/pastries.dm
Labels: Fix

#12705 Provides a user agent when downloading Byond
  tools/ci/download_byond.sh
Labels: p-Priority: Critical, Tools

#12700 Stops xenoarch from breaking half the tests
  code/modules/xenoarchaeology/misc/items.dm
  code/modules/xenoarchaeology/traits/_misc.dm
Labels: Fix

#12658 Fixes Cyborg Limb Sprite Overlays
  icons/mob/augmentation/augments.dmi
Labels: Sprites, Fix

#12030 Cardinal Station (old Bunched station)
  _maps/RandomRooms/5x4/sk_rdm034_deltadetective.dmm
  _maps/_basemap.dm
  _maps/cardinalstation.json
  _maps/map_files/CardinalStation/CardinalStation.dmm
  _maps/shuttles/arrival/arrival_card.dmm
  _maps/shuttles/cargo/cargo_card.dmm
  _maps/shuttles/emergency/emergency_card.dmm
  _maps/shuttles/exploration/exploration_card.dmm
  _maps/shuttles/labour/labour_card.dmm
  _maps/shuttles/mining/mining_card.dmm
  beestation.dme
  code/__DEFINES/machines.dm
  code/datums/shuttles.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/computer/camera.dm
  code/game/objects/effects/spawners/structure.dm
  code/game/objects/items/credit_holochip.dm
  code/game/objects/items/deployable/barricade.dm
  code/game/objects/items/stacks/ores/bscrystal.dm
  code/game/objects/items/stacks/sheets/sheets.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/trash.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/window.dm
  code/game/shuttle_engines.dm
  code/game/turfs/closed/minerals.dm
  code/game/turfs/open/floor/fancy_floor.dm
  code/game/turfs/open/floor/misc_floor.dm
  code/modules/hydroponics/grown.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/mob/living/simple_animal/friendly/cardinal.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/paperwork/paper_premade.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/research/stock_parts.dm
  config/maps.txt
  icons/mob/animal.dmi
  icons/mob/pets_held.dmi
  icons/mob/pets_held_lh.dmi
  icons/mob/pets_held_rh.dmi
  icons/obj/barsigns.dmi
  icons/obj/engine_chopped.dmi
  icons/obj/flora/bigplant.dmi
  icons/turf/decals.dmi
Labels: Mapping, Tweak, Feature, Sprites, Fix, Config Update, Sound

#12684 Fixes singularity beacon
  code/game/machinery/syndicatebeacon.dm
Labels: Fix

#12687 Buffs service pistol to 22 stamina damage from 18
  code/modules/projectiles/projectile/beams.dm
Labels: Balance/Rebalance

#12656 Allows ghosts to jump
  code/modules/mob/emote.dm
  code/modules/mob/living/emote.dm
Labels: Feature, Code Improvement

#12376 Cyborgs are no longer hardstunned by EMP/Flash
  code/__DEFINES/robots.dm
  code/datums/status_effects/debuffs.dm
  code/game/objects/items/devices/laserpointer.dm
  code/modules/assembly/flash.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_defense.dm
  code/modules/mob/living/silicon/silicon_defense.dm
  code/modules/movespeed/modifiers/status_effects.dm
Labels: Tweak, Feature, Fix, Balance/Rebalance, Testmerge Passed

#12213 Friendship ended with 514, now 515 is my best friend
  .github/workflows/ci_suite.yml
  code/__DEFINES/rust_g.dm
  code/__DEFINES/spaceman_dmm.dm
  code/__HELPERS/_extools_api.dm
  code/__HELPERS/varset_callback.dm
  code/__byond_version_compat.dm
  code/_compile_options.dm
  code/_debugger.dm
  code/controllers/subsystem/garbage.dm
  code/game/world.dm
  code/modules/client/preferences/submodules/preference_character_preview.dm
  code/modules/tgui/tgui_window.dm
  config/config.txt
  tgui/packages/tgui-panel/stat/StatText.js
  tgui/packages/tgui/components/ByondUi.jsx
  tools/build/lib/byond.js
Labels: GitHub, Config Update, Refactor, Tools, Code Improvement, Server, TGUI-Changes

#12649 Fix: Deltastation's genpop arcade
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Mapping, Fix

#12416 Debug tool improvement: Makes mapping range debug verbs more obvious
  code/modules/admin/verbs/mapping.dm
Labels: Tweak, Administration

#12707 Fixes TGUI chat auto-scroll on 516
  tgui/packages/tgui-panel/chat/renderer.jsx
Labels: Fix, TGUI-Changes, p-Priority: High

#12706 Fix TGUI say focus
  code/modules/keybindings/setup.dm
  tgui/packages/tgui-say/handlers/componentMount.tsx
  tgui/packages/tgui-say/styles/button.scss
Labels: Fix, TGUI-Changes, p-Priority: High

#12712 Use Byond cache for windows builds
  .github/workflows/ci_suite.yml
Labels: Tweak, GitHub

#12710 Fixes the ability to create fines
  tgui/packages/tgui/interfaces/SecurityRecords/CrimeWatcher.tsx
Labels: Fix, TGUI-Changes

#12723 Fix: powertools not working on init
  code/game/objects/items/tools/powertools.dm
Labels: Fix

#12718 More Smites - Kill via Unknown Mobs
  beestation.dme
  code/modules/admin/smites/assistantban.dm
  icons/mob/simple_human.dmi
Labels: Feature, Sprites, Administration

#12683 New chess piece icons, and chess/checkers holodeck aesthetic
  _maps/RandomRooms/10x10/sk_rdm157_chess.dmm
  _maps/holodeck/small/spacecheckers.dmm
  _maps/holodeck/small/spacechess.dmm
  _maps/holodeck/spacecheckers.dmm
  _maps/holodeck/spacechess.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CardinalStation/CardinalStation.dmm
  _maps/map_files/RadStation/RadStation.dmm
  beestation.dme
  code/game/objects/effects/decals/turfdecal/markings.dm
  code/game/objects/items/cardboard_cutouts.dm
  code/game/objects/structures/chess.dm
  code/game/turfs/open/floor/misc_floor.dm
  code/modules/cargo/packs.dm
  code/modules/holodeck/turfs.dm
  icons/obj/chess.dmi
  icons/turf/decals.dmi
Labels: Mapping, Tweak, Feature, Sprites

#12650 Removes shapeshift holder in favor of a status effect.
  beestation.dme
  code/__DEFINES/dcs/signals/signals_mob/signals_living.dm
  code/__DEFINES/dcs/signals/signals_spell.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/species.dm
  code/__DEFINES/status_effects.dm
  code/datums/actions/action.dm
  code/datums/mind.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/antagonists/heretic/knowledge/flesh_lore.dm
  code/modules/antagonists/heretic/magic/eldritch_blind.dm
  code/modules/antagonists/heretic/magic/eldritch_emplosion.dm
  code/modules/antagonists/heretic/magic/eldritch_shapeshift.dm
  code/modules/antagonists/heretic/magic/flesh_ascension.dm
  code/modules/antagonists/morph/morph.dm
  code/modules/antagonists/xeno/xeno.dm
  code/modules/events/wizard/magicarp.dm
  code/modules/holoparasite/holoparasite_helpers.dm
  code/modules/holoparasite/holoparasite_manifest.dm
  code/modules/holoparasite/holoparasite_setters.dm
  code/modules/holoparasite/holoparasite_signals.dm
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/mob/living/carbon/human/damage_procs.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/vampire.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/damage_procs.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  code/modules/mob/living/simple_animal/hostile/space_dragon.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  code/modules/mob/mob_transformation_simple.dm
  code/modules/projectiles/ammunition/special/magic.dm
  code/modules/projectiles/guns/magic/staff.dm
  code/modules/projectiles/guns/magic/wand.dm
  code/modules/projectiles/projectile/magic.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/research/xenobiology/crossbreeding/_mobs.dm
  code/modules/spells/spell_types/pointed/mind_transfer.dm
  code/modules/spells/spell_types/self/disable_tech.dm
  code/modules/spells/spell_types/shapeshift/_shape_status.dm
  code/modules/spells/spell_types/shapeshift/_shapeshift.dm
  code/modules/spells/spell_types/shapeshift/dragon.dm
  code/modules/spells/spell_types/shapeshift/shapechange.dm
  code/modules/unit_tests/spell_shapeshift.dm
  code/modules/xenoarchaeology/traits/majors/animalize.dm
  icons/hud/screen_alert.dmi
Labels: Sprites, Fix, Refactor, Administration

#12640 Buff blood filtering surgeries a bit
  code/modules/surgery/blood_filter.dm
Labels: Balance/Rebalance

#12646 Paper inserting "overhaul"
  code/modules/modular_computers/hardware/printer.dm
  sound/attributions.txt
  sound/machines/paper_insert.ogg
Labels: Feature, Sound

#12693 Slight chainsaw refactor
  code/game/objects/items/chainsaw.dm
  code/game/objects/items/holy_weapons.dm
  code/game/objects/items/weaponry.dm
  code/modules/mob/living/simple_animal/hostile/netherworld.dm
  icons/mob/inhands/weapons/chainsaw_lefthand.dmi
  icons/mob/inhands/weapons/chainsaw_righthand.dmi
  icons/obj/items_and_weapons.dmi
  sound/weapons/chainsaw_hit.ogg
  sound/weapons/chainsaw_off.ogg
  sound/weapons/chainsaw_on.ogg
  sound/weapons/energychainsaw_hit1.ogg
  sound/weapons/energychainsaw_hit2.ogg
Labels: Tweak, Sprites, Refactor, Sound, Code Improvement

#12610 Let water wapor and stimulum be sellable + some price rearranging.
  code/modules/atmospherics/gasmixtures/gas_types.dm
  code/modules/cargo/exports/large_objects.dm
Labels: Feature, Balance/Rebalance

#12698 Replaces some xenobio effects that round remove people (and very minorly nerfs clock cult)
  code/modules/antagonists/clock_cult/enchantments/electricution.dm
  code/modules/mob/living/simple_animal/slime/life.dm
  code/modules/research/xenobiology/crossbreeding/_mobs.dm
  code/modules/research/xenobiology/crossbreeding/transformative.dm
  code/modules/research/xenobiology/crossbreeding/warping.dm
Labels: Tweak, Balance/Rebalance, Removal

#12731 Added emergency access control to buttons
  _maps/map_files/EchoStation/EchoStation.dmm
  code/__DEFINES/machines.dm
  code/modules/assembly/doorcontrol.dm
Labels: Mapping, Tweak, Feature

#12740 Fixes stale action
  .github/workflows/stale_issues.yml
Labels: GitHub

#12680 Update CONTRIBUTING.md mapping tools
  .github/CONTRIBUTING.md
Labels: GitHub

#12737 Checks will fail if TESTING or LOWMEMORYMODE is defined
  code/_compile_options.dm
Labels: Code Improvement, :ballot_box_with_check: Good PR

#12616 Magboots buff
  code/__DEFINES/obj_flags.dm
  code/_globalvars/bitfields.dm
  code/modules/clothing/chameleon.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: Feature, Balance/Rebalance, Code Improvement

#12665 Ports many hair resprites from TG
  icons/mob/human_face.dmi
Labels: Feature, Sprites

#12714 Cardinal Station - Content Pack
  _maps/map_files/CardinalStation/CardinalStation.dmm
  _maps/shuttles/emergency/emergency_card.dmm
  beestation.dme
  code/game/objects/structures/chess_board.dm
  code/game/objects/structures/crates_lockers/wall_closets.dm
  code/modules/paperwork/desk_bell.dm
  code/modules/vending/games.dm
  icons/obj/chess_board.dmi
  tgui/packages/tgui/interfaces/ChessBoard.tsx
  tgui/packages/tgui/styles/interfaces/ChessBoard.scss
  tgui/packages/tgui/styles/main.scss
Labels: Mapping, Tweak, Feature, Sprites, Fix, TGUI-Changes

#12722 Fix the stabilised black drain
  code/modules/mob/living/damage_procs.dm
  code/modules/research/xenobiology/crossbreeding/_status_effects.dm
Labels: Fix, Balance/Rebalance

#12708 Blocks 516.1660 during compilation
  code/__byond_version_compat.dm
Labels: Tweak

#12607 Adds Atmos Reaction guide + Nitrium
  beestation.dme
  code/__DEFINES/atmospherics/atmos_gasses.dm
  code/__DEFINES/atmospherics/atmos_identifiers.dm
  code/__DEFINES/atmospherics/atmos_mapping_helpers.dm
  code/__DEFINES/machines.dm
  code/__DEFINES/reactions.dm
  code/__HELPERS/atmospherics.dm
  code/_globalvars/lists/canisters.dm
  code/controllers/subsystem/air.dm
  code/game/machinery/computer/atmos_computers/_atmos_control.dm
  code/game/machinery/computer/atmos_computers/air_sensors.dm
  code/game/machinery/computer/atmos_computers/atmos_controls.dm
  code/game/machinery/computer/atmos_computers/inlets.dm
  code/game/machinery/computer/atmos_computers/outlets.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/game/objects/items/devices/scanners/gas_analyzer.dm
  code/game/objects/items/devices/scanners/scanners.dm
  code/game/objects/items/nitrium_crystals.dm
  code/modules/atmospherics/environmental/LINDA_fire.dm
  code/modules/atmospherics/gasmixtures/gas_mixture.dm
  code/modules/atmospherics/gasmixtures/gas_types.dm
  code/modules/atmospherics/gasmixtures/reaction_factors.dm
  code/modules/atmospherics/gasmixtures/reactions.dm
  code/modules/atmospherics/machinery/components/trinary_devices/filter.dm
  code/modules/atmospherics/machinery/other/miner.dm
  code/modules/atmospherics/machinery/portable/canister.dm
  code/modules/atmospherics/machinery/portable/scrubber.dm
  code/modules/cargo/bounties/engineering.dm
  code/modules/cargo/exports/large_objects.dm
  code/modules/clothing/under/jobs/Plasmaman/medsci.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/simple_animal/bot/atmosbot.dm
  code/modules/modular_computers/computers/item/computer.dm
  code/modules/modular_computers/computers/item/tablet.dm
  code/modules/modular_computers/documentation.md
  code/modules/modular_computers/file_system/program.dm
  code/modules/modular_computers/file_system/programs/atmosscan.dm
  code/modules/modular_computers/file_system/programs/borg_self_monitor.dm
  code/modules/modular_computers/file_system/programs/budgetordering.dm
  code/modules/modular_computers/file_system/programs/notepad.dm
  code/modules/modular_computers/file_system/programs/ntmessenger.dm
  code/modules/modular_computers/file_system/programs/phys_scanner.dm
  code/modules/modular_computers/file_system/programs/radar.dm
  code/modules/modular_computers/file_system/programs/records.dm
  code/modules/modular_computers/file_system/programs/signaller.dm
  code/modules/movespeed/modifiers/reagent.dm
  code/modules/power/rbmk/rbmk_core.dm
  code/modules/power/rbmk/rbmk_main_processes.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/shuttle/super_cruise/orbital_poi_generator/loot/alien_artifact.dm
  code/modules/surgery/organs/lungs.dm
  code/modules/xenoarchaeology/traits/majors/porous.dm
  icons/obj/atmos.dmi
  icons/obj/device.dmi
  tgui/packages/tgui/constants.ts
  tgui/packages/tgui/interfaces/AtmosControlConsole.tsx
  tgui/packages/tgui/interfaces/GasAnalyzer.tsx
  tgui/packages/tgui/interfaces/NtosAtmos.jsx
  tgui/packages/tgui/interfaces/NtosGasAnalyzer.tsx
  tgui/packages/tgui/interfaces/common/AtmosHandbook.tsx
Labels: Feature, Sprites, Fix, Balance/Rebalance, TGUI-Changes

#12751 Xenobio Nerf 2: Rat'var Strikes Back
  code/modules/antagonists/clock_cult/enchantments/electricution.dm
Labels: Balance/Rebalance

#12745 Reenable Artifact Animal Traits
  code/modules/xenoarchaeology/misc/items.dm
  code/modules/xenoarchaeology/traits/majors/animalize.dm
Labels: Tweak

#12750 Chess board fix for 515
  code/game/objects/structures/chess_board.dm
  tgui/packages/tgui/interfaces/ChessBoard.tsx
  tgui/packages/tgui/styles/interfaces/ChessBoard.scss
Labels: Fix, TGUI-Changes

#12746 Fixes and tweaks to the sale of wood products
  code/game/objects/items/stacks/sheets/organic/wood_recipes.dm
  code/modules/cargo/exports/large_objects.dm
Labels: Tweak, Fix, Balance/Rebalance

#12761 Ghosts no longer leak into the world of living by jumping
  code/modules/mob/emote.dm
Labels: Fix

#12756 Removes the mini potted plants
  code/game/objects/structures/flora.dm
  icons/obj/flora/_flora.dmi
  icons/obj/flora/mini.dmi
Labels: Sprites, Removal

#12754 Adjusts the Colors, Badges, and Descriptions of Departmental Berets
  code/modules/clothing/head/jobs.dm
  code/modules/vending/wardrobes.dm
Labels: Tweak, Feature, Removal

#12702 Swarmers are now unable to strip
  code/datums/elements/strippable.dm
Labels: Tweak

#12611 Restores balance to BeeStation(Clown April's Fools Outfit removal)
  icons/mob/clothing/back.dmi
  icons/mob/clothing/feet.dmi
  icons/mob/clothing/mask.dmi
  icons/mob/clothing/under/civilian.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/under/civilian.dmi
Labels: Feature, Sprites, Vote Passed, :ballot_box_with_check: Good PR, 🔑 Close Key (1/3)

#12753 Fixes processor recipes outputting the wrong item
  code/modules/food_and_drinks/kitchen_machinery/processor.dm
Labels: Fix

#12765 Admin requests notification sounds, lower pray sound volume.
  code/modules/admin/verbs/_help.dm
  code/modules/mob/mob_stat.dm
  code/modules/requests/request_manager.dm
  sound/effects/pray.ogg
Labels: Tweak, Feature, Sound, Administration

#12781 Fixes broken antagonist code
  code/modules/antagonists/morph/morph.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/simple_animal/hostile/space_dragon.dm
Labels: p-Priority: High
